cmd/clusterctl/client/cluster/crd_migration.go
cmd/clusterctl/client/cluster/crd_migration_test.go

If objects are still stored in the old version, every time an object is requested
the kube-apiserver will call the conversion webhook. Instead of lots of conversion
webhook calls we once do the migration if possible.
Also increases the timeout used for the migrations: Before running CRD migration
clusterctl usually upgrades cert-manager which may lead to updating Certificates and
rolling out new certificates to our controllers. There is a chance that this can take
up to 90s in which conversion, validating or mutatingwebhooks may be unavailable.
Because the migration gets run more aggresively during upgrades this also increases
the relevant timeouts.
---
This also fixes to not run the CRD version migration, if the stored version is equal to the …

🌱 clusterctl: always run crd migration if possible to reduce conversion webhook usage

---

test/e2e/quick_start_test.go
test/framework/resourceversion_helpers.go

This PR ensures resourceVersions are stable after the quick start tests.
The goal is to detect if some of our controllers are continuously reconcililng objects (and bumping resource versions)
Related: https://github.com/kubernetes/kubernetes/issues/124605
I'll open a corresponding CAPI issue to track the k/k issue soon.
Helps to mitigate #10533

🌱 Ensure resourceVersions are stable

---

docs/book/src/clusterctl/configuration.md

📖 Minor fixed to configuration.md
Instead of duplicating the same command `clusterctl upgrade plan`, change one side to `clusterctl upgrade apply`. Ordered according to https://cluster-api.sigs.k8s.io/clusterctl/commands/commands
Fixes #

📖 Minor fix to configuration.md

---

api/v1beta1/cluster_types.go
docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
exp/runtime/hooks/api/v1alpha1/topologymutation_variable_types.go
exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
internal/controllers/topology/cluster/patches/variables/variables.go
test/infrastructure/docker/internal/docker/loadbalancer.go
test/infrastructure/docker/internal/docker/machine.go

IPFamily is not a concept in Kubernetes. It was originally introduced in CAPI for CAPD.
This PR kicks off the deprecation & removal process, at the end of this process IP Familiy will exist only inside CAPD as a convenience for testing.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7521 

🌱 Deprecate IP Family builtin variable

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
exp/runtime/server/server.go
main.go
test/extension/main.go
test/infrastructure/docker/main.go
test/infrastructure/inmemory/main.go

 🌱 Allow users to specify webhook server cert and key names

---

cmd/clusterctl/client/cluster/ownergraph.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/quick_start_test.go
test/framework/finalizers_helpers.go
test/framework/ownerreference_helpers.go
test/framework/resourceversion_helpers.go

In a rare test case where k8s-upgrade-with-runtime-sdk and the quickstart tests's assertion on `ValidateResourceVersionStable` are run in-parallel, we can have a flaky test because:
Getting the owner graph included the RuntimeExtension. When `k8s-upgrade-with-runtime-sdk` finishes, it deleted the CR again, so the assertion in `ValidateResourceVersionStable` failed and the test failed.
xref: [failure occurency](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/10552/pull-cluster-api-e2e-main/1786405514213593088)
Also: enables the `ValidateResourceVersionStable` test for the `k8s-upgrade-with-runtime-sdk` to also test the ExtensionConfig.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …

🐛 test: filter cluster-wide objects asserted in ResourceVersion tests to exclude objects of parallel tests

---

.github/dependabot.yaml

This PR aims to reduce dependabot toil by:
* bumping all GitHub actions in a single PR
* bumping all patch & minor versions in a single PR
* This should lead rarely to issues (e.g. compile issues), if it does we can still fixup the PR by pushing an additional commit.
* bumping all go modules in a single PR
* https://github.com/dependabot/dependabot-core/issues/1595
* https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
Ideally we'll mostly get 2 PRs every week, one for actions one for go dependencies
I would like to experiment a bit with this config. If it works out well we can keep it (and also use it in other repos like e.g. CAPV)
Example …

🌱 Optimize dependabot config

---

docs/book/src/developer/architecture/controllers/cluster.md
docs/book/src/developer/architecture/controllers/control-plane.md
docs/book/src/developer/architecture/controllers/machine-pool.md
docs/book/src/developer/architecture/controllers/machine.md
docs/book/src/developer/providers/bootstrap.md
docs/book/src/developer/providers/cluster-infrastructure.md
docs/book/src/developer/providers/machine-infrastructure.md
docs/book/src/tasks/automated-machine-management/healthchecking.md

To document in the book that error surfaced by failureReason and Message are considered terminal errors by CAPI controllers (Fatal error = Terminal error, it cannot be recovered)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7191

📖 Document failureReason and Message are considered terminal errors

---

Makefile
Tiltfile
netlify.toml

* Bumping go to the latest released version 1.22.3 https://groups.google.com/g/golang-announce/c/wkkO4P9stm0/m/IcuqZRViCgAJ for v1.8.0 release cycle [Bump the Go version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bump-the-go-version) task
* Part of: https://github.com/kubernetes-sigs/cluster-api/issues/10472

:seedling: Bump go version to 1.22.3

---

config/manager/manager.yaml
controllers/alias.go
controlplane/kubeadm/config/manager/manager.yaml
controlplane/kubeadm/controllers/alias.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/main.go
internal/controllers/machineset/machineset_controller.go
main.go

There is a breaking change to the way InfraMachines are named in v1.7.0. This commit adds a flag to the KCP and core controller for getting the old behavior back. It defaults to disabled so the new behavior stays. It is also marked as deprecated and to be removed in v1.9.
Stop-gap solution for https://github.com/kubernetes-sigs/cluster-api/issues/10463

🌱 Flag for old infra machine naming

---

test/framework/ownerreference_helpers.go

The assertFuncs are passed as a list*. Previously, if two assertFuncs were defined for the same Kind, the assertFunc that appeared later in the list would overwrite the one that appeared earlier.
If someone introduced a second assertFunc for a given Kind, they would receive no signal that the first assertFunc was overwritten. A test relying on the first assertion would give a false positive.
With this change, if two or more assertFuncs are defined for the same Kind, both are evaluated.
\* Example:
https://github.com/kubernetes-sigs/cluster-api/blob/99866da16d2cb24cc7fda10884cc21f79ef741b2/test/e2e/quick_start_test.go#L44-L49
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

🐛 test: Ensure all ownerRef assertions for some Kind are evaluated

---

bootstrap/kubeadm/config/manager/manager.yaml
config/manager/manager.yaml
controlplane/kubeadm/config/manager/manager.yaml
test/extension/config/default/manager.yaml
test/infrastructure/docker/config/manager/manager.yaml
test/infrastructure/inmemory/config/manager/manager.yaml

This ensures we have a useful termination message in the Pod if a manager exits unexpectedly.
/area logging

🌱 Set terminationMessagePolicy to FallbackToLogsOnError for all managers

---

test/e2e/clusterctl_upgrade.go
test/framework/clusterctl/client.go

Currently, the clusterctl upgrade test [hard-codes the controlPlaneMachineCount to 1](https://github.com/kubernetes-sigs/cluster-api/blob/74dcfd5fe52ab68bd4d2d6773970c62846afa545/test/e2e/clusterctl_upgrade.go#L393). There are some scenarios, such as CAPZ's managed cluster, that create a cluster without a control plane machine. This PR will add a fix to add support for those scenarios.
Fixes #
/area testing

🌱  Allow control plane count to be configurable in clusterctl upgrade test.

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller.go

When there are no unhealthy target, skip publishing the `RemediationRestricted` event to avoid misleading.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/10585

🐛 Skip publishing the `RemediationRestricted` event when there are no unhealthy target

---

test/e2e/clusterctl_upgrade.go
test/framework/clusterctl/client.go

This PR is a manual cherry-pick of #10498 and #10584
Fixes #
/area testing

[release-1.7] 🌱 Support MachinePools without MachinePoolMachines in clusterctl upgrade test

---

test/e2e/clusterctl_upgrade.go
test/framework/clusterctl/client.go

This PR is a manual cherry-pick of #10498 and #10584
Fixes #
/area testing

[release-1.6] 🌱 Support MachinePools without MachinePoolMachines in clusterctl upgrade test

---

exp/internal/controllers/machinepool_controller_phases.go

If replicas pointer is nil, machinepool controller gets a runtime error and fails. To prevent this we check that replicas is not nil before getting its value.
Fixes #

🐛 Check that replicas pointer is not nil in machinepool controller

---

controllers/remote/cluster_cache_tracker.go

Not really important but I was reading through the code and it's just easier to reason about if we make it clear that we just use the indexes field and it's not passed in via any exported method.
Fixes #

🌱 ClusterCacheTracker: use indexes field instead of passing it around

---

docs/book/src/tasks/automated-machine-management/healthchecking.md

This PR documents a current KCP limitation
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8465

📖 Document KCP limitation

---

cmd/clusterctl/client/repository/repository_github.go
test/framework/clusterctl/e2e_config.go
test/framework/clusterctl/e2e_config_test.go

Similar to what clusterctl does since this PR got implemented: https://github.com/kubernetes-sigs/cluster-api/pull/10220
We now do it similar to that in e2e tests where it failed before.
Fixes #10450

🌱 test: check for metadata.yaml when resolving releases to not try to use unreleased versions

---

controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate_test.go
test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go

Immutability checks should not fail if the only difference is defaulted fields. In these cases changes are fine because introducing new defaulting for fields should never change the behavior. (e.g. setting format to CloudConfig leads to the same behavior as not setting it)
Fixes #

🐛 KCPTemplate & DockerClusterTemplate webhook: default before immutability check

---

bootstrap/kubeadm/config/rbac/role.yaml
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
config/rbac/role.yaml
controlplane/kubeadm/config/rbac/role.yaml
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/config/rbac/role.yaml
test/infrastructure/docker/exp/controllers/exp.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/config/rbac/role.yaml
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go

I reviewed and changed some permissions to harden RBAC for our controllers.
RBAC removals:
| Controller            | Object                           | Old permissions                             | New permissions               |
|-----------------------|----------------------------------|---------------------------------------------|-------------------------------|
| Core CAPI             | `clusters`                       | `create/delete/get/list/patch/update/watch` | `get/list/patch/update/watch` |
| Core CAPI             | `clusters/status`                | `create/delete/get/list/patch/update/watch` | `get/list/patch/update/watch` |
| Core CAPI             | `clusters/finalizers`            | `create/delete/get/list/patch/update/watch` | …

✨ optimize rbac across controllers

---

docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
test/e2e/clusterctl_upgrade.go

🌱 Drop support for INIT env variables in clusterctl upgrade test

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
exp/addons/api/v1beta1/clusterresourcesetbinding_types_test.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
internal/apis/core/exp/addons/v1alpha3/clusterresourcesetbinding_types_test.go
internal/apis/core/exp/addons/v1alpha4/clusterresourcesetbinding_types_test.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/runtime/client/client_test.go
internal/topology/variables/schema_test.go
util/patch/patch_test.go

🌱 Replace reflect.DeepEqual in tests

---

controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go

This PR improves KCP remediation in case a controller crash happens in between creating the new machine and patching KCP.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8188

🌱 Improve KCP remediation re-entrancy

---

hack/tools/triage/config.yaml

Improve triage query to use new labels applied by bots after https://github.com/kubernetes/test-infra/pull/32465 merged
/area devtools

🌱 Improve triage query

---

test/framework/resourceversion_helpers.go

When hitting a failure with this tests its hard or even not possible to actually see what causes this because the output is unsorted and may be truncated.
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-7/1792576343125266432
This should add an additional output which shows the exact diff instead.
Fixes #

🌱 test: improve output for ValidateResourceVersionStable by using BeComparable instead of Equal

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go
controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
exp/ipam/internal/webhooks/ipaddress.go
exp/ipam/internal/webhooks/ipaddressclaim.go
internal/util/compare/equal.go
internal/util/compare/equal_test.go
test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go
test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook.go

Needs a bit more work and some manual tests (want to see how the diffs are looking in logs)
Fixes #8186
Example logs for KCP controller
```
I0516 16:01:22.008912      58 controller.go:412] "Rolling out Control Plane machines: Machine capi-quickstart-control-plane-xvq7h needs rollout: Machine KubeadmConfig ClusterConfiguration is outdated: diff: &v1beta1.ClusterConfiguration{\n    ... // 3 identical fields\n    KubernetesVersion:    \"\",\n    ControlPlaneEndpoint: \"\",\n    APIServer: v1beta1.APIServer{\n      ControlPlaneComponent: {},\n      CertSANs: []string{\n        \"localhost\",\n- …
```

🌱 Add compare util using go-cmp, modify webhooks & KCP controller

---

.github/workflows/pr-gh-workflow-approve.yaml

Set PR approver workflow top-level permissions to none. This is the best practice for GH actions, and for example OpenSSF Scorecards penalize CAPI for not having it.
/area ci

:seedling: drop pr approver workflow top-level permissions

---

Makefile

Manual cherry-pick of #10569
Fixes #

[release-1.6] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

Makefile
docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md

Context: https://github.com/kubernetes-sigs/controller-runtime/pull/2811
I'm going to backport this to all branches (and also CAPV)
Fixes #

🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/framework/bootstrap/kind_util.go
test/framework/exec/kubectl.go

This PR allow clusterctl E2E tests to use kind as a secondary management cluster (instead of using expensive infrastructure resources)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7613
/area testing

🌱 Use kind as a secondary management cluster for clusterctl E2E tests

---

test/infrastructure/container/docker.go

This fixes an issue when running capd with podmans docker compatibility mode. And it's also incorrect in general.
CAPD currently adds the host ports that are part of a port mapping to the list of 'exposed ports' of the container. This is incorrect and leads to an error when using CAPD with podman, since capd sets the host port to 0 so an available port is automatically selected.
```
controller.go:324] "Reconciler error" err="failed to create load balancer: error creating container \"capi-quickstart-lb\": Error response from daemon: fill out specgen: port numbers must be between 1 and 65535 (inclusive), got 0" controller="dockercluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="DockerCluster"
```
There is no specific …

🐛 capd: don't add host ports to exposed ports of containers

---

Makefile

Manual cherry-pick of #10569
Fixes #

[release-1.7] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

🐛 Defaulting webhook should check class is set in ClusterClass-based clusters

---

internal/webhooks/clusterclass.go

Just a minor fix but saw in e2e tests that this looks wrong
```
spec.workers.machineDeployments.machineHealthCheck[0].unhealthyConditions
```
Now it is
```
spec.workers.machineDeployments[0].machineHealthCheck.unhealthyConditions
```
Fixes #

🐛 Fix indexing in ClusterClass webhook MHC validation

---

test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/framework/bootstrap/kind_util.go
test/framework/exec/kubectl.go

manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10639
/area testing

[release-1.6] 🌱 Use kind as a secondary management cluster for clusterctl E2E tests

---

test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/framework/bootstrap/kind_util.go
test/framework/exec/kubectl.go

manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10639
/area testing

[release-1.7] 🌱 Use kind as a secondary management cluster for clusterctl E2E tests

---

OWNERS_ALIASES

As reminded in this week's SIG chair and lead meeting, it is important to keep our owner files up to date.
I made a pass based on [reviewer stats](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last+year&var-metric=reviews&var-repogroup_name=All&var-repo_name=kubernetes-sigs%2Fcluster-api&var-country_name=All&from=1558110159436&to=1715962959436&viewPanel=5). 
If by chance I made some error, please don't hesitate to reach out.
Let me take this moment to thank you again emeritus reviewers for all the great work in the project so far:
- @stmcginnis 
- @dongsupark 
- @invidian
- @johananl
- @oscr 
/area security
/hold let's give folks time to comment on this PR + I will bring it up next week in …

 🌱 Cleanup owner files

---

OWNERS_ALIASES

manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10642 + a few other changes from main
/area security

[release-1.6] 🌱 Cleanup owner files

---

internal/apis/core/v1alpha3/cluster_types.go

:bug: Use k8s.io/utils/ptr instead of k8s.io/utils/pointer

---

api/v1beta1/cluster_types.go
api/v1beta1/index/cluster.go
cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/topology.go
cmd/clusterctl/client/clusterclass.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/patches/variables/variables.go
internal/webhooks/cluster.go

Adding facilities to grab the Cluster's class namespaced name to facilitate future cross namespace support.
Related to https://github.com/kubernetes-sigs/cluster-api/issues/5673
Fixes #

🌱 Add Cluster.GetClassKey() to retrieve a NamespacedName for classes

---

internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinedeployment/mdutil/util_test.go

Follow-up of this PR #10628 for Machinedeployments
Initial rollout:
```
I0528 09:14:11.164279      17 machinedeployment_sync.go:175] "Creating new MachineSet, no MachineSets exist for the MachineDeployment" controller="machinedeployment" controllerGroup="cluster.x-k8s.io" controllerKind="MachineDeployment" MachineDeployment="default/capi-quickstart-md-0" namespace="default" name="capi-quickstart-md-0" reconcileID="acc1a765-03f6-4e2d-a815-148efc8e5b36" Cluster="default/capi-quickstart" MachineSet="default/capi-quickstart-md-0-fqhwx"
```
Rollout because existing MachineSets don't match
```
I0528 09:14:42.812951      17 machinedeployment_sync.go:175] "Creating new MachineSet, couldn't find MachineSet …
```

🌱 Log reason for MachineDeployment rollouts / MachineSet creations

---

test/e2e/quick_start_test.go
test/framework/finalizers_helpers.go
test/framework/ownerreference_helpers.go

This PR improves ValidateFinalizers and ValidateOwnerRef so the functions in input can get the namespaced name of the objects being processed.
This allows to handle differently e.g. secrets with CAPI certificate and secrets with cloud provider credentials

🌱 Improve E2E ValidateFinalizers and ValidateOwnerRef

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale_test.go

Just some fixups after #10692. Unit tests are now also caching unstructured per default, so in these cases we have to make sure that we wait until the new Unstructured objects are synced to the local cache in the test setup. 
Fixes #

🐛 Fix some KCP unit test flakes

---

config/crd/bases/cluster.x-k8s.io_machinepools.yaml
exp/api/v1beta1/machinepool_types.go
exp/internal/controllers/machinepool_controller_noderef.go
exp/internal/controllers/machinepool_controller_noderef_test.go
exp/internal/controllers/machinepool_controller_phases_test.go

**What this PR does / why we need it**: Making MinReadySeconds work in machinepools
Fixes #8952 

🌱 MinReadySeconds for machinepools

---

docs/book/src/developer/providers/migrations/v0.3-to-v0.4.md

:book: fix broken kubebuilder link in old docs

---

docs/book/src/developer/architecture/controllers/cluster.md
docs/book/src/developer/architecture/controllers/control-plane.md
docs/proposals/20230407-flexible-managed-k8s-endpoints.md
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go

/area api
This small change allows the controlPlaneRef, if set, to conditionally set the controlPlaneEndpoint. This change is a short term solution that allows the control plane provider to be on parity with the infrastructure provider, and helps reduce the heavy requirement on the infrastructureRef we have today.
Eventually, once the `ClusterEndpoint` proposal is implemented, those endpoints will superseded this change.

🌱 Allow control plane provider to set endpoint

---

api/v1beta1/clusterclass_types.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go

Machine controller currently mirrors the `clusterv1.InfrastructureReadyCondition` from infrastructure machines back to the Machine object. When we calculate the node startup timeout, we should take into account when the infrastructure was marked as ready, if at all possible.
Fixes #

:seedling: MachineHealthCheck should take Machine's InfraReady condition

---

controlplane/kubeadm/internal/etcd/etcd.go
internal/controllers/machinedeployment/mdutil/util.go
test/infrastructure/inmemory/pkg/server/mux_test.go

Follow-up from #10699
Dropping the GRPC WithBlock function should be okay according to the docs:
> `FailOnNonTempDialError`, `WithBlock`, and `WithReturnConnectionError` are three
> `DialOption`s that are only supported by `Dial` because they only affect the
> behavior of `Dial` itself. `WithBlock` causes `Dial` to wait until the
> `ClientConn` reports its `State` as `connectivity.Connected`.  The other two deal
> with returning connection errors before the timeout (`WithTimeout` or on the
> context when using `DialContext`).
> 
> The reason these options can be a problem is that connections with a
> `ClientConn` are dynamic -- they may come and go over time.  If your client
> successfully connects, the server could go down 1 second later, and your …

🌱 fix loopvar linter issue and usage of deprecated grpc function

---

test/framework/finalizers_helpers.go
test/framework/ownerreference_helpers.go

Small improvements to E2E tests for finalizers and ownerRefs (better logs, finalizer comparison don't consider finalizers order)

🌱 Improve E2E tests for finalizers and ownerRefs

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.15.0
Which issue(s) this PR fixes: https://github.com/kubernetes-sigs/cluster-api/issues/10726

🌱Bump cert-manager to v1.15.0

---

test/framework/finalizers_helpers.go
test/framework/ownerreference_helpers.go
test/framework/resourceversion_helpers.go

Fix/cleanup finalizer assertions so they wait until the `Eventually` timeout expires + print some more logs.
Area example:

🌱 Fix finalizers assertions

---

CHANGELOG/v1.7.3.md

🚀  Release v1.7.3

---

docs/proposals/20220125-ipam-integration.md
exp/ipam/api/v1beta1/condition_consts.go

This adds three failure reasons for the Ready condition of IPAddressClaims that should be used by IPAM providers when reconciling claims. The goal is to offer some consistency between providers when observing conditions for e.g. alerting.
Related to #8424
/area ipam

🌱 ipam: add Ready condition failure reasons

---

internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/machinedeployment_sync_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
test/e2e/md_scale.go
test/framework/machinedeployment_helpers.go

We had some discussion around what the proper behavior is. 
My current take is:
* MS controller should ensure its own finalizer is set
* MD/MS controller should preserve all existing finalizers (including foregroundDeletion)
Fixes #

🌱 Preserve finalizers during MS/Machine reconciliation

---

test/framework/convenience.go

Context: we have hit an issue in CAPV e2e tests where we are using this scheme because the IPAM types were missing.
Fixes #

🌱 Add IPAM API to test framework convenience scheme

---

controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go

This PR aligns KCP and CRS controllers to other controllers with regard to how they update ObservedGeneration.
Most specifically, ObservedGeneration is updated only when a reconcile is completed without errors.
/area provider/controlplane/kubeadm

🌱 Do not update observed generation if there are reconcile errors

---

internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

Fixes #10588 
/area machine
Machine's default to nodeDrainTimeout: 0s, which blocks indefinitely if a pod can't be evicted.  We can't change the nodeDrainTimeout in-place from the MachineDeployment or MachineSet after a machine is marked for deletion.
This results in a machine that wedged forever but can't be updated using the top level objects that own the machine. 
To fix this, this PR allows fields related to machine deletion to be updated in place even when the machine is marked for deletion. 
NOTE - I did not add unit tests yet for this PR. I want confirmation this is an acceptable approve before investing time into testing.

🌱 Propagate timeout fields from MachineSet to Machine during Machine deletion

---

test/e2e/quick_start_test.go
test/framework/finalizers_helpers.go
test/framework/ownerreference_helpers.go
test/framework/resourceversion_helpers.go

Backport a subset of changes from main to improvements to ownerReferences and finalizers test (better logging, do not use global expect inside Eventually)

[release-1.7] 🌱 Improvements to ownerReferences and finalizers test

---

internal/controllers/machineset/machineset_delete_policy.go
internal/controllers/machineset/machineset_delete_policy_test.go

We recently merged https://github.com/kubernetes-sigs/cluster-api/pull/10712 under the assumption that when deleting machines on older MachineSets, unhealthy machines were prioritized.
This is only true for machines with `NodeHealthy` not set or false, but not for machines with `HealthCheckSucceeded` set to false by MHC.
This PR fixes this, and thus ongoing rollouts now contribute to a faster remediation of unhealthy machines.
cc @vincepri @enxebre @sbueringer

🌱 Ensure unhealthy machines get deletion priority

---

internal/controllers/machine/machine_controller_noderef.go

This PR improves logs & conditions when a machine already got a ProviderID from the infrastructure provider, but the corresponding node is not yet available in Kubernetes.
/area machine

🌱 Improve logs & conditions when machine is waiting for node

---

exp/addons/controllers/alias.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/predicates/resource_predicates.go
exp/addons/internal/controllers/suite_test.go
exp/runtime/controllers/alias.go
exp/runtime/internal/controllers/extensionconfig_controller.go
main.go

This PR introduces a separate cache which is used in the clusterresourceset_controller for watching secrets.
Previously the `WatchesMetadata` for secrets in `clusterresourcesset_controller` did inherit the LabelSelector configured in `main.go`:
https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L322-L329
This label selector gets passed through in controller-runtime for the informer which gets created for the watch.
Secrets for clusterresourcesets may apply for multiple clusters, so the label selector may not even exist at the secrets referred by clusterresourcesets.
Fixes #10557 …

🐛 crs: use separate cache for partial metadata watches on secrets to include all secrets

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

When MHC are remediating an unresponsive node, CAPI drains the node and gives up waiting for pods to be deleted after the `SkipWaitForDeleteTimeoutSeconds`. If one of the pods it gave up on has an attached volume, the machine deletion gets stuck.
This PR aligns the behavior for volume detachment during deletion to what we're doing with the drains: if the node is unreachable, we skip detaching volumes.
Fixes #10661
/area machine

🐛 Machine deletion skips waiting for volumes detached for unreachable Nodes

---

internal/controllers/machine/machine_controller.go

This PR reduces the time we wait for pod deletion in the case of unreachable nodes: we currently wait for the deletionTimestamp to be 5 minutes old. The goal is to allow MHC to replace unreachable nodes faster.
This PR aligns the behavior of CAPI with OpenShift MAPI: https://github.com/openshift/machine-api-operator/blob/dcf1387cb69f8257345b2062cff79a6aefb1f5d9/pkg/controller/machine/drain_controller.go#L164-L171 
This PR is a result from a discussion [here](https://github.com/kubernetes-sigs/cluster-api/pull/10662#issuecomment-2139805627).
Fixes #10705
Area example:
/area machine

🐛 Speed up ignoring terminating Pods when draining unreachable Nodes

---

internal/controllers/machineset/machineset_delete_policy.go
internal/controllers/machineset/machineset_delete_policy_test.go

Follow up of https://github.com/kubernetes-sigs/cluster-api/pull/10755#pullrequestreview-2118434311:
For the sake of prioritization, we are not making any assumption about Health when ConditionUnknown.

🌱 Deprioritize unknown NodeHealthy conditions for deletion

---

exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
exp/addons/internal/controllers/clusterresourceset_helpers.go
exp/addons/internal/controllers/suite_test.go

The existing code does not do optimistic locking on the CRSBinding via
`resourceVersion` and hence concurrent updates (patches) overwrite each
other, leading to races and inconsistent state of the CRSBinding.
This PR fixes that by forcing optimistic locking via the
controller-runtime client patch options. The downside to this is that
it leads to more reconciles and log output of failed updates, but
this is a much better situation than having inconsistent and inaccurate
state stored in CRSBinding.
The first commit in this PR adds a test that applies multiple CRS to the same cluster
concurrently, by increasing the max concurrent reconciles used in the
test suite to 10. The test times out without the fix as the CRSBinding is not
correctly and consistently updated. This can be run …

🐛 Correctly handle concurrent updates to ClusterResourceSetBinding

---

internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller_test.go
internal/controllers/topology/machineset/machineset_controller.go
internal/controllers/topology/machineset/machineset_controller_test.go

We have hit a case where the MS topology controller adds a finalizer to a MS which doesn't have the topology owned label. This happened because of a Cluster update event. 
So now this PR introduces an additional safeguard to return early if the MS/MD doesn't have the topology owned label.
Fixes #

🐛 MD/MS topo reconciler: only add finalizer for owned MD/MS

---

exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
exp/addons/internal/controllers/clusterresourceset_helpers.go
exp/addons/internal/controllers/suite_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10656 (automated cherry-pick failed due to conflicts).
/assign sbueringer

[release-1.7] 🐛 Correctly handle concurrent updates to ClusterResourceSetBinding

---

docs/proposals/20200506-conditions.md
util/conditions/getter.go
util/conditions/getter_test.go
util/conditions/merge.go
util/conditions/merge_strategies.go
util/conditions/merge_test.go
util/conditions/setter.go
util/conditions/setter_test.go

This PR is an iteration on the condition proposal & corresponding utils allowing the implementation of conditions with negative polarity, which is a step toward latest K8s guidelines about conditions
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7635
/area api
cc @JoelSpeed @vincepri @theobarberbany

✨ Add support negative polarity conditions

---

test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/cluster_upgrade_runtimesdk_test.go

Exports the method and types to run `ClusterUpgradeWithRuntimeSDK` in provider e2e tests.
Fixes #
/area testing

🌱 test: export method and types for ClusterUpgradeWithRuntimeSDK

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

github.com/docker/docker v27.0.0 was wrongly tagged as v27.0.0 while doing rc release as per the comment here https://github.com/moby/moby/issues/47980#issuecomment-2168178707. This tag doesn't exist in upstream and results in the following error
`github.com/docker/docker@v27.0.0+incompatible: reading github.com/docker/docker/go.mod at revision v27.0.0: unknown revision v27.0.0`. Bumping it to the new latest v27.0.1. 
/area dependancy

 🌱 Bump github.com/docker/docker to v27.0.1

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.15.1
Which issue(s) this PR fixes: https://github.com/kubernetes-sigs/cluster-api/issues/10806

🌱Bump cert-manager to v1.15.1

---

.golangci.yml
Makefile
Tiltfile
cloudbuild-nightly.yaml
cloudbuild.yaml
hack/ensure-go.sh

Bumps to Go 1.22 to stay on a supported Go version
Fixes #

[release-1.6] ✨ Bump to Go 1.22.4

---

.golangci.yml
Makefile
Tiltfile
cloudbuild-nightly.yaml
cloudbuild.yaml
hack/ensure-go.sh

Bumps to Go 1.22 to stay on a supported Go version
Fixes #

[release-1.7] ✨ Bump to Go 1.22.4

---

internal/topology/variables/clusterclass_variable_validation.go

The main goal of this PR is to minimize the diff to the upstream k/k implementation. This makes it less error-prone to keep up-to-date with changes in k/k.
Additionally this has the benefit that errors in CEL don't block additional CEL or schema validation.
Fixes #

🌱 Separate schema and CEL errors in CC variable validation

---

exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go

While testing owner references resilience for CAPV I discovered that the CRS controller do not apply owner references to resources in case there is no connection to the workload cluster.
This PR fixes this issue.
Area example:

🌱 Ensure CRS controller always add ownerReference to resources

---

Makefile

Bumping to go 1.22 in kubekins broke controller-gen < 0.14.0 because of incompatibility to go >= 1.22
This pins compiling controller-gen to 1.21.
xref: #10813
/area devtools

[release-1.6] 🌱 Makefile: pin controller-gen binary to go 1.21

---

docs/book/src/developer/architecture/controllers/cluster.md
docs/book/src/developer/architecture/controllers/control-plane.md
docs/proposals/20230407-flexible-managed-k8s-endpoints.md
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go

[release-1.7] 🌱 Allow control plane provider to set endpoint

---

test/e2e/clusterctl_upgrade.go

When using `UseKindForManagementCluster: true` in clusterctl upgrade tests:
This allows users of this test specification to define a custom function to create the ClusterProxy for the management cluster.
By that it is possible to create the default ClusterProxy, but with their own scheme and options or even create a custom ClusterProxy which has a different implementation.
Fixes #
xref: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3024

🌱 e2e: add function to create the ClusterProxy when using a secondary kind-based management cluster

---

hack/tools/internal/tilt-prepare/main.go

The in-tree providers have hardcoded their provider options in `Tiltbuild`. Therefor the values we have in `tilt-prepare` do not reflect the real ones.
Since implementing #10244, when using a `tilt-settings.yaml` file without debug configuration for the in-tree providers, tilt-prepare won't adjust the cmd to use `start.sh` and because of that restarts via tilt did not work anymore.
Fixes #10810
/area devtools

🌱 tilt: ensure in-tree providers always use start.sh to allow restarts

---

controllers/remote/cluster_cache_healthcheck_test.go
controllers/remote/cluster_cache_tracker.go

Got some errors like this reported:
> E0605 23:20:08.816431       1 machineset_controller.go:885] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" ...
which is relatively confusing for folks not familiar with CCT 
After this PR:
> E0703 20:13:50.850650     176 machineset_controller.go:935] "Unable to retrieve Node status" err="failed to get client: failed to create cluster accessor: failed to get lock for cluster (probably because another worker is trying to create the client at the moment): cluster is locked already" ...
And the log message of the worker that tries & fails to create a client
> E0703 20:13:13.387351 …

🌱 Improve CCT error logging

---

internal/webhooks/machinedeployment.go
internal/webhooks/machineset.go

Just had a few discussion around this, read the godoc and realized it's not up-to-date.
The docs were talking about a "DefaultAnnotation" but we dropped it (xref: https://github.com/kubernetes-sigs/cluster-api/pull/7990#discussion_r1097326480)
Fixes #

📖 Improve godoc of the autoscaler replica field defaulting

---

test/e2e/clusterclass_rollout.go

Introduced a new field FilterMetadataBeforeValidation in E2E tests
to allow filtering out labels and annotations of Machines,
InfraMachines, BootstrapConfigs, and Nodes before validation.
This feature enables the exclusion of additional infrastructure
provider-specific labels that could otherwise cause test failures.
Fixes #10714

🌱 Enhance E2E Tests to Filter Out Extra Provider-Specific Metadata

---

docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
exp/runtime/hooks/api/v1alpha1/topologymutation_variable_types.go
exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/controllers/topology/cluster/patches/variables/variables.go
internal/controllers/topology/cluster/patches/variables/variables_test.go
internal/webhooks/patch_validation.go

This patch extends the cluster builtins to include the UID of the Cluster object. This can be used by the runtime extensions or JSON patches to set owner references on objects owned by the Cluster object.
Fixes #10823

✨ Extend cluster builtin to include UID

---

util/patch/patch.go
util/patch/patch_test.go
util/patch/utils.go

Currently, patch helper is only useful for CRD or any other object that has spec/status fields, where status is considered a subresource.
Some types like ConfigMap (and others) don't rely on spec being a top level resource, but instead have other top level fields like `data`.
Fixes #

:bug: Patch helper should be able to patch non-spec objects

---

test/framework/cluster_proxy.go

Allows to create a custom ClusterProxy which e.g. adds a custom Dial function to the rest.Config by only overwriting the GetWorkloadCluster function.
xref:
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3072
Fixes #

🌱 test: add restConfigModifier Option to clusterProxy

---

.github/dependabot.yaml
go.mod

🌱 Stop bumping cel-go via dependabot

---

test/e2e/clusterclass_rollout.go

Add union() to convert a potential nil map to an empty map, otherwise the test will faile due to compare a nil map and an empty one.
Fixes #10839
/area testing

🐛 Fix metadata assert failure in clusterclass rollout test

---

internal/webhooks/cluster.go
internal/webhooks/cluster_test.go
internal/webhooks/clusterclass.go
internal/webhooks/clusterclass_test.go

Adds namespace defaulting for the ClusterClass & Cluster.spec.topology.
Fixes #10805

:bug: Fix default namespace of RemediationTemplate for ClusterClass and Topology

---

CHANGELOG/v1.7.4.md

🚀  Release v1.7.4

---

docs/book/src/tasks/automated-machine-management/healthchecking.md

🐛 Clarify cluster paused and skipping remediation steps

---

test/e2e/clusterclass_rollout.go

Just a small cleanup as a follow-up to #10840
Fixes #

🌱 Improve metadata assertions in ClusterClass rollout test

---

docs/book/src/user/quick-start.md

Add missing kubeconfig file to deploy cloud-controller-manager on workload cluster on OpenStack cloud provider
To deploy cloud-controller-manager on provisioned workload cluster on OpenStack provider there was a missing kube configuration file directive to address workload cluster

:book: Add missing kubeconfig file 

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/controllers/topology/cluster/patches/variables/variables.go
internal/controllers/topology/cluster/patches/variables/variables_test.go
internal/topology/variables/cluster_variable_defaulting.go
internal/topology/variables/cluster_variable_defaulting_test.go
internal/topology/variables/cluster_variable_validation.go
internal/topology/variables/cluster_variable_validation_test.go
internal/topology/variables/utils.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/extension/handlers/topologymutation/handler_integration_test.go

This PR contains the following changes:
* ClusterClass controller will now set VariablesReconciled condition on the ClusterClass to false if there are variable conflicts
* The consequence of that will be that the Cluster topology controller will stop reconciling corresponding clusters until the conflicts are resvoled
* Deprecation of the definitionFrom field
* Add "name" as a map key for variable arrays. This will allow separate ownership per variable
* Corresponding changes & cleanups to the variable defaulting and validation code
Part of #10666

⚠️ Adjust CC & Cluster controller to block on variable conflicts, deprecate definitionFrom

---

.golangci.yml
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml

🌱 Deprecate MHC MaxUnhealthy & UnhealthyRange fields

---

.golangci.yml
api/v1beta1/machinedeployment_types.go
api/v1beta1/zz_generated.openapi.go
cmd/clusterctl/client/client.go
cmd/clusterctl/cmd/rollout/undo.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml

🌱 Deprecate MachineDeployment revision management

---

docs/release/releases/release-1.8.md

As per last week's office hours, amending the release calendar to handle the latest news about k8s test infra changes planned in August.
- GA date the 12th of August instead of the 13th
- 1.8.1 tentatively scheduled for the 15th of August
/area release

📖 Amend 1.8 release planning

---

util/patch/patch.go

~~This allows the patch helper to ignore patching the status when creating a patch.~~
The solution for the issue below was to check the object if the finalizers are removed and if the DeletionTimeStamp was not nil and the error after patching the status/spec was `IsNotFound`.  This will cut down on noise as well as achieve with not exposing the internals of the patch helper.
Fixes #10786
/area util

🐛Check errors for IsNotFound after patching spec and status 

---

test/e2e/cluster_upgrade_runtimesdk.go

This PR ensures that resources are dumped before deleting the extensionconfig.
Deleting the extensionconfig pollutes the state of e.g. the ClusterClass and would make the dump lead to wrong conclusions.
Fixes #

🌱 test: Dump resources before deleting extensionconfig

---

test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go

Fixes nil pointer which occurred e.g. here:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1812401250918993920
- CAPD logs: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1812401250918993920/artifacts/clusters/bootstrap/logs/capd-system/capd-controller-manager/capd-controller-manager-64d8bd4d45-77kh8/manager.log
```
{"ts":1720949295165.3877,"caller":"controller/controller.go:110","msg":"Observed a panic in reconciler: assignment to entry in nil map","controller":"dockermachinepool","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"DockerMachinePool","DockerMachinePool":{"name":"autoscaler-qynhbr-mp-0-4hrqc","namespace":"autoscaler-wh9wa3"},"na …
```

🐛 capd: fix nil pointer in dockermachinepool controller

---

internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go

We're currently treating the infrastructureRef as almost a requirement, which in fact isn't and it's an optional reference.
If the Cluster control plane reference is populated, the endpoint is valid, and the control plane is ready, set the phase to provisioned
Fixes #

:bug: Cluster should be provisoned when cpRef and endpoint is set

---

CHANGELOG/v1.8.0-beta.0.md

🚀  Release v1.8.0-beta.0

---

util/patch/patch_test.go

Adds a test for the previously merged PR https://github.com/kubernetes-sigs/cluster-api/pull/10787
/area util

🌱 Add test for patchHelper logic around deletionTimestamps/finalizers

---

bootstrap/kubeadm/main.go
controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/main.go
docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
main.go
test/extension/main.go
test/infrastructure/docker/main.go
test/infrastructure/inmemory/main.go

Before this PR we were using client-go defaults of 5 & 10 qps & burst. This PR changes the defaults to use the same as we use for the mgmt cluster client. It also makes these values configurable to allow fine-tuning at scale.
Fixes #

✨ Add QPS & burst options & flags for ClusterCacheTracker

---

util/patch/patch_test.go

This test has been failing pretty regularly since we merged the test yesterday (#10866)
Fixes #

🐛 Fix race condition in TestPatchHelper test

---

test/framework/autoscaler_helpers.go

We currently use `busybox` from dockerhub for autoscaling tests. This changes the dependency to the `registry.k8s.io/pause` image instead.
Fixes #

🌱 test: use pause image for autoscaler tests

---

test/framework/deployment_helpers.go

Uses pause instead of nginx, e.g. in `capi-e2e: [It] When testing node drain timeout A node should be forcefully removed if it cannot be drained in time`
Fixes #

🌱 test: use pause instead of nginx

---

exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
exp/addons/internal/controllers/suite_test.go
internal/test/envtest/environment.go

ClusterResource set controller doesn't have an ideal implementation for cases where many ClusterResourceSets are targeting the same cluster (might be also the API is not specifically designed for this use case).
This PR is making this case a little bit more predictable, by avoiding a potential impact of exponential backoff delay quickly growing, but it is not solving the underlying issue.
At least, this should help in getting rid of some flakiness in our tests, and there is also a comment providing some more context on what's going on.
Another positive effect of this PR is that it remove a lot of noise from the logs
Related to #10854

🌱 Make ClusterResourceSet controller more predictable

---

docs/community/20231016-in-place-updates.md

After the discussions on the draft proposal, it was suggested to use "Updates" instead of "Upgrades" in the FG naming and notes to avoid the confusion between the two. 
Fixes #

📖 Rename In-place Upgrades Feature Group

---

api/v1beta1/cluster_phase_types.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go

This PR is a small improvement on changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/10873, making sure that cluster provisioned phase isn't including control plane fully ready (which was altering the original semantic of those phases)
Also improved the go comments for the phase const to better reflect current state
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/10885
/area api
cc @vincepri

🌱 Partially revert changes for ":bug: Cluster should be provisoned when cpRef and endpoint is set"

---

test/e2e/clusterctl_upgrade.go

The clusterctl upgrade tests currently delete the second management cluster if skipCleanup was set to true.
Fixes #

🌱 test: skip cleanup of additional kind cluster if flag is set

---

internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

This PR is an attempt to get rid of TestServerSideApplyWithDefaulting flakes.
The assumption is that the test case "no-op_if_neither_is_defaulted" is moving too quickly from creating the webhook and calling NewServerSidePatchHelper, which expect the web up to be already registered/recognized by the API server.
The fix introduces as wait loop after creating the web hook to make sure the webhook is up and running before moving on.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/10902

🐛 Fix TestServerSideApplyWithDefaulting flakes

---

internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go
internal/controllers/cluster/cluster_controller_test.go

… to true
Some clients, like MachineHealthCheck are checking this condition to continue operations. Set it for backward compatibility
Fixes #
/area api

:bug: When infrastructureRef is nil, set InfrastructureReadyCondition to true

---

exp/runtime/topologymutation/walker.go

This PR adjusts the WalkTemplates function provided for runtime extensions to use the original input struct to calculate patches.
Before it did use the typed objects to marshal them and create the patch.
This could lead to invalid patches because the Go struct may have fields which the original input did not have.
Example for `VSphereClusterTemplate` from here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/apis/v1beta1/vsphereclustertemplate_types.go#L33
Consider the following input from the patch request (the template referred by the ClusterClass):
```json
{
"apiVersion": "vmware.infrastructure.cluster.x-k8s.io/v1beta1",
"kind": "VSphereClusterTemplate",
"metadata": {
"name": "quick-start-supervisor",
"namespace": …
```

🐛 topology: use raw input object for patch calculation in WalkTemplates

---

cmd/clusterctl/client/repository/client_test.go
cmd/clusterctl/client/repository/overrides_test.go
cmd/clusterctl/client/repository/repository_local_test.go

This PR is for cleanup.
I replaced from os.MkdirTemp to t.TempDir. 
Fixes #

🌱 use testing.TempDir instead of os.MkdirTemp

---

test/e2e/config/docker.yaml
test/framework/bootstrap/kind_util.go
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

✨ Bump Kubernetes version used for testing to v1.31.0-beta.0

---

exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_test.go
exp/internal/webhooks/machinepool.go
exp/internal/webhooks/machinepool_test.go
internal/controllers/topology/cluster/reconcile_state_test.go

Ignore unreachable cluster while deleting machinePools 
Fixes #10544

✨ MachinePools: Use NodeDeletionTimeout and default it to 10s

---

internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

We're currently always trying to check that the controller can access and set owner references on MachineSets, even if no operations are ongoing. If a MachineSet is scaling down, we should not block operations if the external reference isn't present anymore (was deleted) and we should let the controller proceed.
In most gitops scenarios, it's preferable that any change being rolled out it's done by setting new template references to new resources. For example, let's say we have a MachineDeployment/MachineSet with a boostrap and infrastructure reference set. To apply a rollout and change to all Machines under management, new templates need to be created, and the references changed to the new templates, which will cause a rollout.
With gitops flows, usually new resources replacing old ones …

:bug: MachineSet should allow scale down operations to proceed when templates don't exist

---

test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go

Looks like `br-netfilter` is not loaded anymore in CI.
This ignores the preflight check which also got dropped in v1.30.
xref [Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1721839442841439)
Fixes #
Area example:

🐛 [release-1.6] docker: ignore kubeadm preflight check for FileContent--proc-sys-net-bridge-bridge-nf-call-ip6tables

---

test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

This PR is a test to figure out if setting the feature flag would solve an issue that we found in CI. We will eventually revert this PR but for now we want to now if the feature gate would fix this issue.
The issue:
* Since we bumped our tests to Kubernetes 1.31 the "When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane" test has been failing pretty frequently 
* The root cause is that in some case a 1.31 kubelet tries to list services from a 1.30 apiserver
* This fails because the 1.30 apiserver does not support field selectors for spec.clusterIP: https://github.com/kubernetes/kubernetes/pull/123905
* The problem is that kubeadm join configures the …

🌱 Enable kubeadm ControlPlaneKubeletLocalMode feature gate in e2e tests

---

cmd/clusterctl/client/config/cert_manager_client_test.go
cmd/clusterctl/client/config/providers_client_test.go
cmd/clusterctl/client/repository/overrides_test.go

This PR is for cleanup.
I replaced from os.Setenv to testing.Setenv
Fixes #

🌱  use testing.Setenv instead of os.Setenv

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/upgrade.go
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_test.go
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

This is now the proper fix to the issue discovered and mitigated (in e2e tests) in #10940
The underlying issue is the following
* Since we bumped our tests to Kubernetes 1.31 the "When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane" test has been failing pretty frequently
* The root cause is that in some case a 1.31 kubelet tries to list services from a 1.30 apiserver
* This fails because the 1.30 apiserver does not support field selectors for spec.clusterIP: https://github.com/kubernetes/kubernetes/pull/123905
* The problem is that kubeadm join configures the kubelet to use the apiserver loadbalancer instead of the local apiserver.
With the feature …

✨ KCP: default ControlPlaneKubeletLocalMode feature gate to true for >= 1.31.0

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go

🌱 Reenable 2 MHC unit tests

---

docs/release/releases/release-1.9.md

This PR adds release-1.9 cycle schedule document with preliminary dates taking into account [Kubecon US 2024](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) between November 12-15, 2024 on week 13th in the schedule.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10472

📖 Add Cluster API release-1.9 timeline document

---

controllers/remote/cluster_cache_tracker.go

Allows the tracker to specify which objects should be cached, and how.
Fixes #

🌱 Allow ClusterCacheTracker to set CacheByObject

---

test/framework/machinepool_helpers.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go

I did hit this locally:
I had a case where 3 healthy machine pool machines did exist, but the test expected two while it must be three.
The topology controller may require some time to rollout the change to the MachinePool object.
This ensures we get the right state of the machine pool object to continue checking the right amount of ready replicas.
Fixes #

🌱 test: fix machinepool test to wait for topology controller to set correct number of replicas first

---

test/framework/cluster_proxy.go

```
sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).isDockerCluster(0x1400079a100?, {0x10232c318, 0x140007a8960}, {0x14000a28618, 0x17}, {0x14000764170, 0xc})
/Users/vincepri/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.0-rc.0/framework/cluster_proxy.go:481 +0x200
sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetWorkloadCluster(0x14000399ea0, {0x10232c318, 0x140007a8960}, {0x14000a28618, 0x17}, {0x14000764170, 0xc}, {0x0, 0x0, 0x0})
/Users/vincepri/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.0-rc.0/framework/cluster_proxy.go:358 +0x20c
sigs.k8s.io/cluster-api/test/framework.DumpAllResourcesAndLogs({0x10232c318, 0x140007a8960}, {0x10233ce58, 0x14000399ea0}, {0x14000567540, 0x5a}, 0x140007a6160, 0x14000a3a820) …
```

:bug: test/framework isDockerCluster should check that infra ref is present

---

bootstrap/kubeadm/config/crd/kustomization.yaml
bootstrap/kubeadm/config/crd/patches/cainjection_in_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/patches/cainjection_in_kubeadmconfigtemplates.yaml
config/crd/kustomization.yaml
config/crd/patches/cainjection_in_clusterclasses.yaml
config/crd/patches/cainjection_in_clusterresourcesetbindings.yaml
config/crd/patches/cainjection_in_clusterresourcesets.yaml
config/crd/patches/cainjection_in_clusters.yaml
config/crd/patches/cainjection_in_machinedeployments.yaml
config/crd/patches/cainjection_in_machinehealthchecks.yaml
config/crd/patches/cainjection_in_machinepools.yaml
config/crd/patches/cainjection_in_machines.yaml
config/crd/patches/cainjection_in_machinesets.yaml
controlplane/kubeadm/config/crd/kustomization.yaml
controlplane/kubeadm/config/crd/patches/cainjection_in_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/patches/cainjection_in_kubeadmcontrolplanetemplates.yaml
test/infrastructure/docker/config/crd/kustomization.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockerclusters.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockerclustertemplates.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepools.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepooltemplates.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachines.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinetemplates.yaml
test/infrastructure/inmemory/config/crd/kustomization.yaml
test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemoryclusters.yaml
test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemoryclustertemplates.yaml
test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemorymachines.yaml
test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemorymachinetemplates.yaml

Turns out we are doing this twice. So I dropped some noise :)
We are now only adding the annotations via https://github.com/kubernetes-sigs/cluster-api/blob/1e5634816c129cdeac4d2081e205e75cf8d8926a/bootstrap/kubeadm/config/default/kustomization.yaml#L35-L59
Fixes #

🌱 Remove duplicate ca injection via kustomize

---

bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
config/crd/patches/webhook_in_clusterclasses.yaml
config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
config/crd/patches/webhook_in_clusterresourcesets.yaml
config/crd/patches/webhook_in_clusters.yaml
config/crd/patches/webhook_in_machinedeployments.yaml
config/crd/patches/webhook_in_machinehealthchecks.yaml
config/crd/patches/webhook_in_machinepools.yaml
config/crd/patches/webhook_in_machines.yaml
config/crd/patches/webhook_in_machinesets.yaml
controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml

Starting with Kubernetes 1.31 it won't be possible anymore to continuously apply CRDs that are setting caBundle to an invalid value (in our case `Cg==`). The solution is to simply drop the caBundle field (it was never actually required by kube-apiserver).
For more details see: https://kubernetes.slack.com/archives/C0EG7JC6T/p1722441161968339
Let me know if you have any questions. 
Going to backport this into all supported releases. It's never great to set the caBundle to an invalid value, even before Kubernetes 1.31
Fixes #

🐛 Drop caBundle from CRDs to support Kubernetes 1.31

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go

I discovered that the `applyMutators` function panics if one of the mutators is nil. I updated the function to return an error on any nil mutator.
The first commit adds unit tests, one of which confirms that `applyMutators` panics if a the mutators slice contains a nil mutator.
The second commit fixes the issue.
The third commit fixes a test that passes a nil mutator. The call is incorrect, but the test has never failed, because it enables dry-run, and that does not exercise the mutators.
Fixes #
/kind bug

:bug: Handle a nil mutator by returning an error, not panicking

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go

The `createTargetObject` function is called as part of the move operation. It creates the target object, i.e. the object on the target cluster. If the target object already exists, the function updates the object. 
Previously, the function fixed the name and namespace of the target object before it applied the experimental mutators. If some mutator modified the namespace of the target object, the function would continue to use the namespace established before the mutators were applied.
This adds a new (failing) unit test, and ensures that the target object namespace reflects the changes made by the experimental mutators. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

:bug: Ensure move uses mutated metadata when updating a target object

---

test/framework/autoscaler_helpers.go

🌱 test/framework: Allow ScaleUp Deployment image to be customized

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.15.2
Which issue(s) this PR fixes: https://github.com/kubernetes-sigs/cluster-api/issues/10989

🌱Bump cert-manager to v1.15.2

---

test/e2e/clusterctl_upgrade.go
test/e2e/self_hosted.go

With this changes we prevent using `Consistently` to check for no rollouts to have happened.
This helps in situations where inside the consistently we would hit certificate errors, which do not mean a rollout happened, but will fail the test, which at the end made it flaky.
Fixes #

🌱 test: stop using Consistently for rollout checks

---

bootstrap/kubeadm/internal/cloudinit/cloudinit.go
bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script-pre-k8s-1-31.sh
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go

This adds a new script for useExperimentalRetryJoin for kubernetes >= v1.31 due to the following changes:
* control-plane update-status phase got removed
* new phases got added for the ControlPlaneKubeletLocalMode feature gate
Fixes #

🐛 bootstrap: fix useExperimentalRetryJoin for kubernetes v1.31

---

test/framework/resourceversion_helpers.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go

Probably doesn't fix the entire issue, but related to #10838
Fixes #

🐛 Ensure DockerMachinePool providerIDList is deterministic

---

cmd/clusterctl/client/cluster/proxy.go

Currently, we cannot use clusterctl binary from inside the pod because it can not find the cluster. This PR updates config generation to use GetConfigOrDie() method from `controller-runtime` so that clusterctl can discover the cluster even kubeconfig is not provided.
Fixes #6286
--> [area/clusterctl](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aopen+label%3Aarea%2Fclusterctl+sort%3Aupdated-desc)

🌱 Update Config generation to use inClusterConfig

---

test/framework/autoscaler_helpers.go

Capacity has the entire memory pool that the node carries, while allocatable is the true memory available for scheduling purposes.
/area testing
Fixes #

🌱 test/framework: scale up should use allocatable memory

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

🌱 Bump docker/docker to v25.0.6

---

scripts/ci-e2e-lib.sh
test/e2e/clusterctl_upgrade_test.go

…ase as management cluster
This helps to find upcoming issues like the one fixed in:
- #10972
way more earlier in the cycle and not when we start bumping to beta or rc's for the management cluster.
Fixes #

🌱 test: add coverage to find issues running on the next kubernetes release as management cluster

---

internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

Currently we get a few logs like this in our e2e tests
```
{"ts":1722858941941.0283,"caller":"cluster/reconcile_state.go:317","msg":"Patching DockerMachineTemplate/quick-start-itkrd6-ks4hk, diff: {}","controller":"topology/cluster","controllerGroup":"cluster.x-k8s.io","controllerKind":"Cluster","Cluster":{"name":"quick-start-itkrd6","namespace":"quick-start-k6hnu4"},"namespace":"quick-start-k6hnu4","name":"quick-start-itkrd6","reconcileID":"da094763-efac-489d-9df5-9c518faa3e18","resource":{"group":"infrastructure.cluster.x-k8s.io","version":"v1beta1","resource":"DockerMachineTemplate"},"DockerMachineTemplate":{"name":"quick-start-itkrd6-ks4hk","namespace":"quick-start-k6hnu4"},"v":0}
```
This PR …

🌱 Improve reconcile state logs (don't log empty diff)

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go

follow up to: https://github.com/kubernetes-sigs/cluster-api/pull/10906
increases the timeout further for 2 MHC unit tests as they still sporadically flake with the same issue

🌱 Increase timeout for 2 MHC unit tests

---

test/framework/resourceversion_helpers.go

This PR improves the error ouptut of ValidateResourceVersionStable to make it easier to debug corresponding flakes
Fixes #

🌱 Improve error output of ValidateResourceVersionStable

---

internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

…ates don't exist
Backport of #10913 
Fixes #

[release-1.7] 🐛 MachineSet should allow scale down operations to proceed when templated don't exist

---

internal/runtime/client/client.go

* Log an error when Lifecycle Hook Runtime Extension fails while we set `Ignore` as Failure Policy. 
* I want the error to be on logs even if ignored for investigation.
```
E0808 14:00:07.430045       1 client.go:349] "ignoring error calling extension handler because of FailurePolicy \"Ignore\"" err="http call failed: Post \"https://test-extension-webhook-service.test-extension-system.svc:443/hooks.runtime.cluster.x-k8s.io/v1alpha1/beforeclustercreate/before-cluster-create?timeout=10s\": dial tcp 10.96.93.238:443: connect: connection refused" controller="topology/cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="default/capi-quickstart" namespace="default" name="capi-quickstart" …
```

🌱 Log error when calling a Runtime Extension gets an error that is ignored because of failure policy

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

Consider this scenario:
* Machine is created
* InfraMachine is created
* MachineHealthCheck is set to 10 minutes
* [10 minutes pass]
* Machine is marked as needing remediation
* Machine and InfraMachine goes into deletion flow
* Node finally joins the cluster, say 10 minutes + few seconds
* InfraMachine is still waiting for VM to be deleted
* Machine keeps retrying to delete, but `nodeRef` was never set
* Machine, InfraMachine go away (finalizer removed)
* Node object sticks around in the cluster
This changset allows the Machine controller to look into the cluster during deletion flow if the Node eventually got created before the infrastructure provider was able to fully delete the machine.
**Which issue(s) this PR fixes** *(optional, in `fixes …

:bug: Machine Controller should try to retrieve node on delete

---

docs/book/src/reference/versions.md
test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

* >  Modify CAPD to use the new Kubernetes release after it is GA
* >  Update book
Requirements:
Part of #10653
/area testing
/hold due to waiting for v1.30 GA
Fixes #

✨ Bump Kubernetes in tests to v1.31.0 and claim support for v1.31

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md

Just syncing back some improvements from the 1.31 issue
I'll create the 1.32 issue afterwards
Fixes #

📖 Improve Kubernetes bump issue template

---

scripts/ci-e2e.sh

🌱 test/e2e: increase concurrency

---

docs/book/src/security/index.md

The file got moved via:
- https://github.com/cncf/tag-security/pull/1283
to
https://github.com/cncf/tag-security/blob/main/community/resources/security-whitepaper/secure-defaults-cloud-native-8.md
Fixes #

📖 docs: fix broken link to tag security whitepaper

---

test/framework/deployment_helpers.go
test/framework/deployment_helpers_test.go
test/go.mod

Since CR v0.19 panics in controllers and webhook are recovered per default.
This PR extends our e2e test framework so we still fail our tests if panic occurs (the controller won't crashloop anymore)
Part of #10653

✨ Detect panics in e2e tests

---

Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/kind/mapper.go

* Bumps kind to v0.24.0
* Changes the way we build `kindest/node` images in CI on-demand with the new functionality from kind. This way we propably only have to compile binaries for kind images for lates-ci and reduce e2e duration.
Part of #10653

🌱 Bump kind to v0.24.0

---

test/e2e/clusterctl_upgrade_test.go
test/e2e/self_hosted_test.go

This PR drops redundant e2e tests. Over the last few months/years we continuously added more e2e tests. Now we reached a test duration of over 2 hours. 
This PR will already significantly improve the situation: #11067. But I think additionally we should also only run the e2e tests we actually need
Fixes #

🌱 Remove redundant self-hosted and clusterctl upgrade tests

---

bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh

When I tried to join a worker node to a 1.31 cluster, I encountered the following error during cloud-init:
```
[2024-08-22 23:34:18] /usr/local/bin/kubeadm-bootstrap-script: line 111: try-or-die-command: command not found
```
It appears that before 1.31, we only use `try-or-die-command` when joining a control plane - https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script-pre-k8s-1-31.sh#L131-L132. However, for >= 1.31, we use `try-or-die-command` for kubeadm join regardless of the node role. This PR removes the if condition around the function so that it's available when joining both control plane and worker nodes.

🐛 always declare try-or-die-command function in kubeadm-bootstrap-script.sh

---

test/e2e/autoscaler.go
test/framework/autoscaler_helpers.go
test/framework/deployment_helpers.go
test/framework/machinedeployment_helpers.go
test/framework/machinepool_helpers.go

Adjusts autoscale tests to:
* Allow running cluster-autoscaler inside the management cluster
* Note: for providers there may be no connectivity from the workload to the management cluster running in kind
* make machinepool's optional for the test:
* Note: not all providers support machinepools (e.g. CAPV)
* add option for scale to/from zero tests
Fixes #

🌱 test: improve autoscale tests for to/from zero and running autoscaler in bootstrap cluster

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

This updates cert manager to a newer version 
Fixes #
Last time this was done: https://github.com/kubernetes-sigs/cluster-api/pull/10988

🌱Bump cert-manager to 1.15.3

---

test/framework/docker_logcollector.go

I want to be able to collect more system logs from CAPD clusters than currently offered. This PR introduces a change to the DockerLogCollector structure that allows specifing additional systems logs. 
Fixes #
/area testing

✨ Collect additional logs with CAPD log collector

---

config/metrics/crd-metrics-config.yaml
config/metrics/templates/cluster.yaml
config/metrics/templates/common_metrics.yaml
config/metrics/templates/machine.yaml
config/metrics/templates/machinehealthcheck.yaml
config/metrics/templates/machinepool.yaml
config/metrics/templates/machineset.yaml

This PR adds `nilIsZero: true` to the status conditions `StateSets` and to other status fields.
Fixes #
/cc @chrischdi

🌱 Add nilIsZero to all KSM metric configs where needed

---

config/metrics/crd-metrics-config.yaml
config/metrics/templates/cluster.yaml
config/metrics/templates/common_metrics.yaml
config/metrics/templates/machine.yaml
config/metrics/templates/machinehealthcheck.yaml
config/metrics/templates/machinepool.yaml
config/metrics/templates/machineset.yaml

This reverts commit 82adc3980eea57394503c69ef73c4ec8c3125fbc.
Unfortunately, `nilIsZero` is not implemented for `type: StateSet`, see [`config_metrics_types.go#L48-L59`](https://github.com/kubernetes/kube-state-metrics/blob/main/pkg/customresourcestate/config_metrics_types.go#L48-L59). Sorry folks 😞 
Also there is no error in the logs using it for this type.
Fixes #
/area metrics

🌱 Revert "Add nilIsZero to all KSM metric configs where needed"

---

docs/book/src/user/quick-start.md

This PR fixes the broken links that redirect pages in the CAPZ book.
instead of https://github.com/kubernetes-sigs/cluster-api/pull/11104

📖 Fix CAPZ redirection links in quick-start page

---

docs/release/releases/release-1.9.md

This PR adds v1.9 release team members to release timeline doc 
/area release

🌱 Add v1.9 release team members to timeline doc

---

docs/book/src/clusterctl/commands/alpha-topology-plan.md
docs/book/src/clusterctl/commands/upgrade.md

This PR fixes typos in the clusterctl documentation.

📖 Fix typos in clusterctl doc

---

bootstrap/kubeadm/config/rbac/role.yaml
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
config/rbac/role.yaml
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/config/rbac/role.yaml
test/infrastructure/docker/exp/controllers/exp.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/config/rbac/role.yaml
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go

Fix /finalizers RBAC removed in:
- https://github.com/kubernetes-sigs/cluster-api/pull/10552
Update permissions on /finalizers subresrouce is required on managment clusters with 'OwnerReferencesPermissionEnforcement' plugin enabled. See: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
Fixes [#11098](https://github.com/kubernetes-sigs/cluster-api/issues/11098)
/area api

🐛 re-add /finalizers subresource RBAC

---

exp/internal/controllers/machinepool_controller_phases_test.go

we can see in the failing test results (i.e. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-mink8s-main/1830171842158006272) that this line https://github.com/kubernetes-sigs/cluster-api/blob/703cc70e450f334d9e391294180898f234b08415/exp/internal/controllers/machinepool_controller_phases.go#L437 is only logging once, whereas in the successful tests ([example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1830262439854215168)) , it logs twice as 2 `infraMachine`s are recognized and the 2 machinepool machines are created accordingly
my theory is that a cache sync delay is causing this flake as only 1 of the expected `infraMachine`s is found in the cache when `reconcileMachines` gets …

🌱 Improve TestReconcileMachinePoolMachines unit test

---

docs/book/src/SUMMARY.md
docs/book/src/tasks/automated-machine-management/index.md
docs/book/src/tasks/automated-machine-management/machine_deletions.md
internal/controllers/machine/drain/drain.go
internal/controllers/machine/machine_controller.go

Adds documentation for Machine deletions and Node drains.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10056

📖 Add Node drain documentation

---

docs/book/src/SUMMARY.md
docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md
errors/doc.go

The /errors package has its origin in when capi providers were machineActuators that needed to vendor core capi to function. There's no usage recommendations and value is questionable since we moved to CRDs and conditions for interoperability between core and providers. I think we should deprecate it and if there's any use case relying on it we should support it via conditions
Fixes #10784

🌱  Deprecate obsolete errors pkg

---

docs/book/src/developer/guide.md
docs/book/src/developer/tilt.md

I'm using this setup for a while now and did not hit any issues. It is even more stable for me compared to docker desktop on OSX.
Fixes #

📖 book: document how to use Lima on macOS for development

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go
test/e2e/clusterclass_rollout.go
util/collections/machine_collection.go
util/collections/machine_collection_test.go

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/11138

🐛 KCP: remove etcd member in pre-terminate hook

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go
test/e2e/clusterclass_rollout.go
util/collections/machine_collection.go
util/collections/machine_collection_test.go

Manual cherry-pick of #11137
Fixes #

[release-1.8] 🐛 KCP: remove etcd member in pre-terminate hook

---

internal/controllers/machine/machine_controller.go

Did some experiments around drain recently and noticed that this log statement is highly misleading
Fixes #

🐛 Fix drain log for unreachable Nodes

---

.golangci.yml

We're using an adapted version of CAPI's golangci-lint config. I've recently updated the linter list with comments summarising what each linter does, since it's quite cumbersome to look it up in case you want to know.
This should also make it easier for other projects to adopt this configuration.
I've also removed two linters:
- typecheck - it's no longer listed in the documentation
- rowserrcheck - it's for the `sql` package, and I hope we're not using that anywhere
I also removed one deprecated parameter and moved file exclusions to the new location.
/area ci

🌱 golangci: add comments to enabled linters

---

Makefile
internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/kustomization.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/md.yaml
test/e2e/node_drain_timeout.go
test/e2e/node_drain_timeout_test.go
test/framework/deployment_helpers.go

Extends the test coverage for Node drain.
The test goes through the following steps:
* Create cluster with 3 CP & 1 worker Machine
* Ensure Node label is set & NodeDrainTimeout is set to 0 (wait forever)
* Deploy Deployment with unevictable Pods on CP & MD Nodes
* Deploy Deployment with evictable Pods with finalizer on CP & MD Nodes
* Trigger Scale down to 1 CP and 0 MD Machines
* Verify Node drains for control plane and MachineDeployment Machines are blocked (PDBs & Pods with finalizer)
- DrainingSucceeded conditions should:
- show 1 evicted Pod with deletionTimestamp (still exists because of finalizer)
- show 1 Pod which could not be evicted because of PDB
- Verify the evicted Pod has terminated (i.e. succeeded) and it was evicted
* Unblock …

🌱 Improve node drain e2e test

---

api/v1beta1/machine_types.go
docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11137
Fixes #

📖 Add more documentation about the KCP pre-terminate hook

---

api/v1beta1/machine_types.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11153
Fixes #

[release-1.8] 📖 Add more documentation about the KCP pre-terminate hook

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
internal/controllers/machine/machine_controller.go

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11137
Additional context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1725952675583209
This PR ensures that KCP always removes the pre-terminate hook from Machines if KCP is deleted.
Before this PR this was only done if a Machine didn't have a deletionTimestamp.
There are edge cases where a Machine could have a deletionTimestamp before (or at the same time) as KCP:
* All objects of the cluster are deleted at the same time (this is not technically supported, but some folks are running into this case)
* The Machine already had the deletionTimestamp (e.g. through a scale down or remediation) when the Cluster/KCP object were …

🐛 Make KCP pre-terminate hook more robust

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
internal/controllers/machine/machine_controller.go

Manual cherry-pick of #11161
Fixes #

[release-1.8] 🐛 Make KCP pre-terminate hook more robust

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
cmd/clusterctl/cmd/describe_cluster.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
test/framework/docker_logcollector.go
test/infrastructure/docker/internal/docker/loadbalancer.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/inmemory/pkg/runtime/cache/client.go
test/infrastructure/inmemory/pkg/runtime/cache/hooks.go

This PR bumps golang-ci to  v1.60.2,
a lot of false positive issues have appeared, therefore i deal with them.
Fixes #11075

🌱 Bump golangci to v1.60.2

---

.github/workflows/pr-verify.yaml

The action did use sh instead of bash.
Tested here: https://github.com/chrischdi/cluster-api/actions/runs/10808759886/job/29982425599?pr=204
Fix for #11062

🐛 hack: fix the shell used when running pr-verify

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controllers/remote/cluster_cache_reconciler.go
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
exp/internal/controllers/machinepool_controller.go
exp/runtime/internal/controllers/extensionconfig_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go

This PR tries to improve the logging of predicate to include more key value pairs.
Part of #10818
/area logging

:seedling: Log controller name in predicates

---

cmd/clusterctl/client/cluster/client.go
cmd/clusterctl/client/cluster/ownergraph.go
cmd/clusterctl/client/cluster/proxy.go
cmd/clusterctl/client/cluster/proxy_test.go

Allows the clusterctl user to configure the API client warning handler.
The warning handler is configured by the Proxy. If a user only wants to configure the warning handler, we should not require them to implement their own Proxy. This PR, therefore, exports our Proxy constructor, and adds an option that allows the user to construct a Proxy with their own warning handler.
The PR does not change the existing warning handling behavior. As before, the default warning handler is provided by the controller-runtime client. Its default warning warning handler has not changed.
Fixes #10932

✨ clusterctl: Allow user to suppress API warnings

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

- This PR updates the supported versions for the release cycle (1.9).
@kubernetes-sigs/cluster-api-release-team

📖 Update CAPI support and guarantees for v1.9

---

docs/book/src/reference/versions.md

Extracted from https://github.com/kubernetes-sigs/cluster-api/pull/11163
Fixes #

[release-1.8] 📖 Drop v1.5 column, set v1.6 to EOL in versions.md

---

docs/book/src/reference/ports.md
util/flags/manager.go
util/flags/manager_test.go

Removes MetricsBindAddr flag 
follows : https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#track-remove-previously-deprecated-code
Part of https://github.com/kubernetes-sigs/cluster-api/issues/11092
/area util

🌱 Remove previously deprecated --metrics-bind-addr flag

---

util/kubeconfig/kubeconfig.go
util/kubeconfig/kubeconfig_test.go

Currently, kubeadmconfg's endpoint is liked using fmt.Sprintf. But if the endpoint is `/host:port`, the result is `https:///host:port`. So I use url.JoinPath to concat safely.
Fixes #

🌱 Use url.JoinPath instead of fmt to concat endpoint

---

docs/book/src/introduction.md

k8s.gcr.io happened some time ago now, also, there is a formatting issue (lacks of /aside 😅 )

 📖 Drop k8s.gcr.io deprecation notice

---

internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

When creating a cluster without defining any workers:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
name: test
namespace: default
spec:
topology:
class: quick-start
controlPlane:
metadata: {}
replicas: 1
variables:
version: v1.31.0
```
The reconciliation fails because the cluster cannot be patched anymore because the webhook panic's. This is visible in the cluster's status condition and when trying to patch the cluster (e.g. adding workers):
```yaml
...
status:
conditions:
- lastTransitionTime: "2024-09-19T06:57:27Z"
message: 'error reconciling the Cluster topology: failed to mark "AfterControlPlaneInitialized"
hook(s) as pending: failed to patch Cluster default/test: admission webhook
"default.cluster.cluster.x-k8s.io" denied …
```

🐛 clusterclass: fix nil pointer for empty workers in webhook

---

docs/book/src/SUMMARY.md
docs/book/src/developer/providers/cluster-infrastructure.md
docs/book/src/developer/providers/machine-infrastructure.md
docs/book/src/security/infrastructure-provider-security-guidance.md

relates to https://github.com/kubernetes-sigs/cluster-api/issues/6519#issuecomment-2069579585

:book: infrastructure provider security guidelines

---

internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go

This PR reduces spammy output especially during background deletion of objects like a whole cluster.
Example from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/11146/pull-cluster-api-e2e-blocking-main/1832066840088547328/artifacts/clusters/bootstrap/logs/capi-system/capi-controller-manager/capi-controller-manager-5f5f6bcf4c-4zpjc/manager.log :
Example: owner reference is gone:
```
{"ts":1725634615581.657,"caller":"controller/controller.go:316","msg":"Reconciler error","controller":"machine","controllerGroup":"cluster.x-k8s.io","controllerKind":"Machine","Machine":{"name":"quick-start-0qi0bi-md-0-kskml-96tqh-jg4tt","namespace":"quick-start-ev3dh5"},"namespace":"quick-start-ev3dh5","name":"quick-start-0qi0bi …
```

🌱 machine: prevent error spamming for NodeOutdatedTaint if objects are not found

---

api/v1beta1/condition_consts.go

We do not check `NodeNetworkUnavailable`.
Follow-up of https://github.com/kubernetes-sigs/cluster-api/pull/11145#discussion_r1756583001

🌱 condition: fix godoc for MachineNodeHealthyCondition

---

Makefile
test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/cluster.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/kustomization.yaml
test/framework/controlplane_helpers.go

Implements additional checks to ensure the cluster is operational during an update.
Fixes #

🌱 test: add PreWaitForControlplaneToBeUpgraded to ClusterUpgradeConformanceSpec

---

test/framework/cluster_proxy.go

There is currently no way to restrict for example the options in the cache when it gets created. In restricted environment this can be useful to restrict the cache to specific namespaces and avoid doing list/watch operations globally.
Fixes #

🌱 test/framework: allow users to modify cache.Options

---

test/framework/alltypes_helpers.go

In restricted environments some resources might not be available for retrieval; ensure to print a warning but not fail the operation.
Fixes #

🌱 test/framework: GetCAPIResources should warn on rbac issues

---

internal/test/builder/v1beta2_transition.go
util/conditions/v1beta2/options.go
util/conditions/v1beta2/patch.go
util/conditions/v1beta2/patch_test.go
util/patch/options.go
util/patch/patch.go
util/patch/patch_test.go
util/patch/utils.go
util/patch/utils_test.go

Add support for metav1 conditions (that will be used in v1beta2 types) to patch helper
Please do not review (it depends on 
/area util

🌱 Add support for v1beta2 conditions to patch helper

---

Makefile
bootstrap/kubeadm/types/upstreamv1beta1/conversion_test.go
bootstrap/kubeadm/types/upstreamv1beta2/conversion_test.go
bootstrap/kubeadm/types/upstreamv1beta3/conversion_test.go
bootstrap/kubeadm/types/upstreamv1beta4/conversion_no_fuzz_test.go
bootstrap/kubeadm/types/upstreamv1beta4/conversion_test.go
exp/internal/controllers/machinepool_controller_test.go
exp/ipam/api/v1alpha1/conversion_test.go
internal/apis/bootstrap/kubeadm/v1alpha3/conversion_test.go
internal/apis/bootstrap/kubeadm/v1alpha4/conversion_test.go
internal/apis/controlplane/kubeadm/v1alpha3/conversion_test.go
internal/apis/controlplane/kubeadm/v1alpha4/conversion_test.go
internal/apis/core/exp/addons/v1alpha3/conversion_test.go
internal/apis/core/exp/addons/v1alpha4/conversion_test.go
internal/apis/core/exp/v1alpha3/conversion_test.go
internal/apis/core/exp/v1alpha4/conversion_test.go
internal/apis/core/v1alpha3/conversion_test.go
internal/apis/core/v1alpha4/conversion_test.go
internal/test/envtest/environment.go
test/infrastructure/docker/api/v1alpha3/conversion_test.go
test/infrastructure/docker/api/v1alpha4/conversion_test.go
test/infrastructure/docker/exp/api/v1alpha3/conversion_test.go
test/infrastructure/docker/exp/api/v1alpha4/conversion_test.go

Took the part for the unit tests of the main module from https://github.com/kubernetes-sigs/cluster-api/pull/10899.
I want to get the race detector for this part of our code base ASAP.
This PR:
* enables the race detector for `make test` & `make junit-test`
* `make junit-test` uses `-json`, because of that I had to make sure a proper logger is used in envtest unit tests, otherwise we hit a race condition when writing/reading os.Stderr
* Fuzz tests time out after 10m when run with the race detector, because of that all test files with fuzz tests have been flagged with `go build !race`. Additional test executions have been added to `make test` and `make test-junit` to ensure the tests in these files …

🌱 Enable race detector for main module unit tests

---

util/apiwarnings/doc.go
util/apiwarnings/handler.go
util/apiwarnings/handler_test.go

As described in #10932 and #11065, users see API server warnings from run `clusterctl move`, and in controller logs. We want to offer users the option of hiding these warnings. The warning handler available in client-go allows us to hide all warnings, but we want to hide only specific warnings.
This PR implements a handler that we can customize to our needs. Because Cluster API providers are affected by this issue, we define the handler in a new `util/apiwarnings` package that can be used by providers, which are typically consumers of the `cluster-api` go module.
Future PRs will use this handler to hide warnings in the `clusterctl move` command, and controller logs. …

✨ util: Warning handler that discards messages that match a regular expression

---

scripts/ci-e2e.sh

reduces concurrency, effectively reverting https://github.com/kubernetes-sigs/cluster-api/pull/11067/files
based on conversation here: https://github.com/kubernetes-sigs/cluster-api/issues/11209#issuecomment-2371557610

:seedling: test/e2e: decrease concurrency

---

api/v1beta1/machinedeployment_types.go
api/v1beta1/machineset_types.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
test/e2e/cluster_deletion.go
test/e2e/cluster_deletion_test.go
test/framework/finalizers_helpers.go
util/log/log.go

Supersedes #10791
This PR implements foreground deletion in the machinedeployment and machineset controllers using a finalizer.
Part of #10710

🌱 Foreground deletion for MachineDeployments and MachineSets

---

.github/workflows/pr-verify.yaml

🌱 pr-verify: use env var for passing the PR title

---

exp/internal/controllers/machinepool_controller_noderef.go
internal/controllers/machine/drain/drain.go
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
util/util.go

Was working on something new and realized that Errors are always logged independent of the configured log level.
So using `log.V(4).Error(err, )`, doesn't make sense as the errors are always logged...
godoc of the Error func:
> // Error logs an error, with the given message and key/value pairs as context.
> // It functions similarly to Info, but may have unique behavior, and should be
> // preferred for logging errors (see the package documentations for more
> // information). **The log message will always be emitted, regardless of
> // verbosity level.**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

🐛 Log errors on specific log levels correctly

---

config/manager/manager.yaml
docs/book/src/developer/core/testing.md
docs/book/src/tasks/experimental-features/machineset-preflight-checks.md
feature/feature.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/machineset/machineset_preflight_test.go

Promotes MachineSetPreflightChecks to beta
part of #11117

✨ MachineSet: Promote MachineSetPreflightChecks to Beta

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
main.go

We received a request (#11065) to hide noisy "finalizer name" warnings in controller logs.
In #11129, we hide "finalizer name" warnings by default in the clusterctl `move` command. This PR extends the approach used there to the Cluster API controllers.
Fixes #11065

✨ Suppress finalizer name API warnings in CAPI, CABPK, and KCP controller logs

---

docs/proposals/20240916-improve-status-in-CAPI-resources.md

Follow up from https://github.com/kubernetes-sigs/cluster-api/pull/11234#discussion_r1784020252
cc @sbueringer 

 📖 Clarify MinReadySeconds transition in the v1Beta2 API

---

config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
docs/proposals/20240916-improve-status-in-CAPI-resources.md
exp/addons/api/v1beta1/clusterresourceset_types.go
exp/api/v1beta1/machinepool_types.go
internal/test/builder/crd/test.cluster.x-k8s.io_phase1obj.yaml
internal/test/builder/crd/test.cluster.x-k8s.io_phase2obj.yaml
internal/test/builder/crd/test.cluster.x-k8s.io_phase3obj.yaml
internal/test/builder/v1beta2_transition.go

Found a few more places
Fixes #

🌱 Add maxItems to all condition fields

---

util/conditions/getter.go
util/conditions/matchers.go
util/conditions/merge_strategies.go
util/conditions/patch.go
util/conditions/setter.go
util/conditions/setter_test.go

There are cases when one wants to compare existing condition and the condition to be applied before applying them, to avoid extra PATCH request to the server, but the only way to do it today is to wrap it in gomega.Matcher, like this:
```go
condition := clusterv1.Condition{...}
if existingCondition := conditions.Get(obj, condition.Type); existingCondition != nil {
if ok, _ := conditions.HaveSameStateOf(&condition).Match(existingCondition); ok {
return nil
}
}
conditions.Set(obj, &condition)
return client.Update(ctx, obj)
```
In this PR I propose to export HasSameState, to simplify the code above as (I understand not a big benefit, but just not clear why should we use gomega for simple comparison
```go
condition := clusterv1.Condition{...}
if …
```

🌱Export conditions.HasSameState method

---

hack/verify-container-images.sh

switches to using the ECR mirror for trivy db artifacts
we have this problem in our weekly security scan -- failing scan such as on release-1.8 (https://github.com/kubernetes-sigs/cluster-api/actions/runs/11105678796/job/30852373163) due to some [API rate limiting](https://github.com/kubernetes-sigs/cluster-api/actions/runs/11105678796/job/30852373163#step:5:701) on one of the required security artifacts
- issue on source repo here: https://github.com/aquasecurity/trivy-action/issues/389
- cert-manager did this and it resolved their issue: https://github.com/cert-manager/testing/pull/1062/files#diff-ce3d91fd77957f12a21c34a9d5b2805cf9c1b0fd5be4cc57a6372e9bc7fe500eR146-R147
/area ci

🌱 Switch to using ECR mirror for trivy DB repo in weekly security scan

---

api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml

Follow-up to: #10637 
Effectively `Type` was already optional as it was possible to set `Type` to "".
But since #10637 we actually want this field to be optional to allow schemas like this:
```yaml
testQuantityField:
anyOf:
- type: integer
- type: string
pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
x-kubernetes-int-or-string: true
```
Without this PR the schema would look like this:
```yaml
testQuantityField:
anyOf:
- type: integer
- type: string
pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
type: "" # << this is not intended …
```

🌱 Make Type in ClusterClass variable schema properly optional

---

internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machine/machine_controller_phases_test.go

Improving unit test coverage on reconcileBootstrap and reconcileInfrastructure in the Machine controller
/area machine
/hold for discussing a few test cases

🌱 Improve unit tests for Machine controller

---

hack/tools/internal/tilt-prepare/main.go

My local clone of `cluster-api-provider-aws`, configured in CAPI via `tilt-settings.yaml` ...
```
provider_repos:
- /Users/asommer/dev/e/cluster-api-provider-aws
enable_providers:
- aws
- kubeadm-bootstrap
- kubeadm-control-plane
```
... failed to reload on code changes because `start.sh` wasn't used. It is only used if, for instance, `live_reload_deps` is non-empty. That property was parsed from the config file, but not passed on to the function which fixes up the `Deployment` command.
/area devtools

🌱 Fix parsing of `config.live_reload_deps` from Tilt provider config file

---

docs/book/src/developer/core/controllers/machine.md
docs/book/src/developer/providers/contracts/bootstrap-config.md
docs/book/src/developer/providers/contracts/infra-machine.md
docs/book/src/developer/providers/security-guidelines.md

📖 Fix some nits in BootstrapConfig docs

---

internal/test/envtest/environment.go
test/framework/deployment_helpers.go

🌱 Check for panics during test runs in envtest

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/predicates/cluster_predicates.go
util/predicates/cluster_predicates_test.go
util/predicates/generic_predicates.go

This PR logs objects kind predicates for easier debugging.
Related PR with same changes for few predicates: https://github.com/kubernetes-sigs/cluster-api/pull/11188
Part of #10818
/area utils

:warning: Fix object logging in predicates

---

util/conditions/v1beta2/aggregate.go
util/conditions/v1beta2/aggregate_test.go

This allows to pass in slices like `[]*clusterv1.Machine`.
Otherwise we have to repack them into a `[]Getter` slice via e.g.:
```
getters := []Getter{}
for _, machine := range []*clusterv1.Machine{...} {
getters = append(getters, machine)
}
```
Fixes #

🌱 v1beta2 conditions: make NewAggregate use generics

---

docs/book/src/developer/providers/contracts/infra-cluster.md

This change updates the infra cluster provider contract to account for a new paused
condition.
Relates #10130

📖 Update InfraCluster provider contract to account for the paused condition

---

util/conditions/v1beta2/aggregate_test.go
util/conditions/v1beta2/setter.go
util/conditions/v1beta2/sort.go
util/conditions/v1beta2/sort_test.go
util/conditions/v1beta2/summary_test.go

make sure that well know v1beta2 conditions always appear in the same order
/area utils

🌱 Improve sort for v1beta2 conditions

---

docs/book/src/developer/providers/contracts/infra-machine.md

This change updates the infra machine provider contract to account for a new paused condition.
Relates https://github.com/kubernetes-sigs/cluster-api/issues/10130
(The same as https://github.com/kubernetes-sigs/cluster-api/pull/10519 but for InfraMachine.)

📖 Update InfraMachine contract to include pausing rule

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/finalizers/finalizers.go
util/finalizers/finalizers_test.go

🌱 Handle finalizers early in Reconciles

---

util/conditions/setter.go
util/conditions/setter_test.go

similar to https://github.com/kubernetes-sigs/cluster-api/pull/11254 conditions lexicographicLess method accepts two pointers, but does dereference without any additional checks, resulting in nil-pointer panic:
```console
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
```
The PR adds according tests to proof (that fail with the said above panic) and simple nil-check, that sets nil-condition less than any other
/area util

🐛Fix conditions lexicographicLess nil pointer dereference

---

util/conditions/setter.go
util/conditions/setter_test.go

conditions hasSameState method accepts two pointers, but does dereference without any additional checks, resulting in nil-pointer panic:
```console
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
```
The PR adds according tests to proof (that fail with the said above panic) and simple nil-check, that marks two nil conditions as being the same.
/area util

🐛Fix conditions hasSameState nil pointer dereference

---

docs/book/src/developer/providers/contracts/bootstrap-config.md
docs/book/src/developer/providers/contracts/infra-machine.md

This change updates the BootstrapConfig provider contract to account for a new paused
condition.
Relates https://github.com/kubernetes-sigs/cluster-api/issues/10130

📖 Update BootstrapConfig contract to include pausing

---

api/v1beta1/machine_types.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/v1beta2_condition_consts.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
util/conditions/v1beta2/getter.go
util/conditions/v1beta2/getter_test.go
util/conditions/v1beta2/setter.go
util/conditions/v1beta2/setter_test.go

This PR adds code for updating MachineHealthCheck with v1beta2 status.
Also MachineHealthCheck now updates targeted Machines with v1beta2 status too.

✨ Update MHC with v1Beta2 status

---

api/v1beta1/machine_types.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
exp/addons/api/v1beta1/v1beta2_condition_consts.go
exp/api/v1beta1/v1beta2_condition_consts.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
test/infrastructure/docker/api/v1beta1/v1beta2_condition_consts.go

🌱 Remove unused Paused conditions & minor MHC godoc fixes

---

api/v1beta1/machine_types.go
bootstrap/kubeadm/internal/builder/builders.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
cmd/clusterctl/client/cluster/topology.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_test.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
test/extension/handlers/topologymutation/handler_integration_test.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/conditions/v1beta2/patch.go
util/paused/paused.go
util/paused/paused_test.go
util/predicates/cluster_predicates.go

Note: this excludes currently:
* clusterresourcesetbinding (no status)
* extensionconfig
* clusterclass
* topology controllers for cluster (tracked in parent issue), md, ms
Part of:
- #11105
Also:
- #10130
Fixes #
/area api

🌱 v1beta2 conditions: add function for setting the Paused condition

---

test/framework/kubernetesversions/data/kustomization.yaml

A kustomization file used in the test framework is using an incorrect field name after its change to kustomize v5. Specifically it was using `patch` instead of `path` which cause kustomize to fail when building.
You would only see this if you do something like this in your tests:
```go
import (
"sigs.k8s.io/cluster-api/test/framework/kubernetesversions"
)
ciTemplateForUpgradePath, err := kubernetesversions.GenerateCIArtifactsInjectedTemplateForDebian(
kubernetesversions.GenerateCIArtifactsInjectedTemplateForDebianInput{
ArtifactsDirectory:    e2eCtx.Settings.ArtifactFolder,
SourceTemplate:        sourceTemplateForUpgrade,
PlatformKustomization: platformKustomization,
},
)
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …

🐛 fix: incorrect name used in kustomize path

---

Makefile
test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/cluster.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/kustomization.yaml
test/framework/controlplane_helpers.go

Manual cherry-pick of #11145
Fixes #

[release-1.8] 🌱 test: add PreWaitForControlplaneToBeUpgraded to ClusterUpgradeConformanceSpec

---

controllers/external/fake/controller.go
controllers/external/fake/doc.go
controllers/external/tracker.go
exp/internal/controllers/machinepool_controller_phases_test.go
exp/internal/controllers/machinepool_controller_test.go
internal/controllers/cluster/cluster_controller_phases_test.go
internal/controllers/machine/machine_controller_phases_test.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/topology/cluster/cluster_controller.go

This PR makes changes to make controller param in object tracker a mandatory one, Till today function was behaving as no-op. This mandate make few test files to be updated to set the controller.
Fixes # Follow up of discssion https://github.com/kubernetes-sigs/cluster-api/pull/11188#discussion_r1763202390

:seedling: Make controller mandatory param for external object tracker

---

controlplane/kubeadm/internal/controllers/status.go

manual cherry-pick of:
- #11304
/hold

🐛 [release-1.8] kcp: consider all machines for setting .status.version

---

controlplane/kubeadm/internal/controllers/status.go
util/collections/machine_filters.go
util/collections/machine_filters_test.go

Uses the lowest version of *all* machines when calculating .status.version for KCP.
Otherwise there may still exist CP machines in an old version which still serve the kube-apiserver (as e.g. in #11296).
Before this could have lead to version skew violations, because coming up new worker machines may still have been able to connect to the old apiserver. Altough except for CAPD this is unlikely, because provisioning also takes some time. In the failing test-case though we block the deletion of the old CP machine which increases the propability to hit this race.
Via: #11296

🐛 kcp: consider all machines for setting .status.version

---

internal/controllers/cluster/suite_test.go

Flakes: https://storage.googleapis.com/k8s-triage/index.html?job=periodic-cluster-api-test-.*main
e.g. https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-mink8s-main/1846587606641414144
Follow-up to #11247

🌱 Fix flake in TestClusterReconciler

---

test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
util/predicates/cluster_predicates.go

- #11284
replaces most usages of these predicates due to the changes necessary to support the Paused condition.
The leftover usage in DockerMachinePools will be removed during:
- #11105
Fixes #
/area util

🌱 Deprecate old pausing predicates

---

controllers/remote/cluster_cache_reconciler.go
controllers/remote/cluster_cache_tracker.go
controllers/remote/cluster_cache_tracker_fake.go
controllers/remote/index.go
controlplane/kubeadm/internal/controllers/controller.go
docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md

🌱 Deprecate ClusterCacheTracker

---

test/e2e/config/docker.yaml

removes JSON logging from built from main e2e components to improve ease of troubleshooting per conversation here: https://github.com/kubernetes-sigs/cluster-api/issues/11133#issuecomment-2428586507

:seedling: Remove json logging replacement in e2e test config

---

api/v1beta1/machine_types.go
internal/controllers/machine/machine_controller_status.go
util/conditions/v1beta2/summary.go

Use internal error more consistently in the machine controller

🌱 Use internal error reason consistently

---

controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go

It doesn't make sense to check if the migratoin library supports an upgrade if the code doing the CoreDNS upgrade is skipped. So let's get rid of it
Fixes #

🌱 KCP: Skip validation if CoreDNS migration library supports an upgrade if the library is not used

---

api/v1beta1/machineset_types.go
api/v1beta1/v1beta2_condition_consts.go
internal/controllers/machine/machine_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go
internal/controllers/machineset/machineset_controller_test.go
util/log/log.go

This PR adds code for updating machine with v1beta2 status.
In order to do so, reconcile bootstrap config, infrastructure and getAndAdoptMachines will now always run, ensuring info from those resources are always surfaced.
Also fixes the status information on deletion, which was stale during deletion and with foreground deletion enabled.
Fixes #
xref:
- #11105 
/area api

✨ Update machineset with v1beta2 status test

---

.golangci.yml
api/v1beta1/cluster_types.go
api/v1beta1/machine_types.go
api/v1beta1/machineset_types.go
api/v1beta1/zz_generated.openapi.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
exp/api/v1beta1/machinepool_types.go
internal/contract/bootstrap.go
internal/contract/controlplane.go
internal/contract/infrastructure_cluster.go
internal/contract/infrastructure_machine.go

Deprecates `.status.failureMessage` and `.status.failureReason` as proposed in docs/proposals/20240916-improve-status-in-CAPI-resources.md.
Part of #11105
/area api

🌱 api: deprecate FailureMessage and FailureReason

---

Makefile
test/infrastructure/inmemory/pkg/runtime/cache/sync.go

I added -race option to go test command. This option can find the raced code.
Fixes #

:bug: Add race option to detect raced codes

---

test/infrastructure/inmemory/pkg/runtime/cache/cache_test.go
test/infrastructure/inmemory/pkg/runtime/cache/gc.go

I replace atomic.AddXX function to atomic variable and receiver method itself.
Fixes #

🌱  use latest atomic variable instead of old one

---

exp/internal/controllers/machinepool_controller_noderef.go

The `if` condition has two cases, but the log message didn't reflect that. This came unexpected when it logged `NodeRefs != ReadyReplicas [...] nodeRefs=5 readyReplicas=5` 😆. I improved the message and key-value arguments to explain the situation without having to look up the machine pool status manually.
/area logging

🌱 Improve log when not enough replicas are ready or referenced

---

internal/controllers/machine/drain/drain.go
internal/controllers/machine/drain/filters.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go
main.go
test/infrastructure/inmemory/pkg/server/api/const.go
test/infrastructure/inmemory/pkg/server/api/handler.go
util/log/log.go

Improves `shouldWaitForNodeVolumes` to ignore volumes referred by pods which were ignored during drain.
Fixes #
/area machine

⚠️ Machine: ignore attached Volumes referred by pods ignored during drain

---

internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go

🌱 Improve machine Ready v1beta2 condition

---

util/conditions/v1beta2/options.go
util/conditions/v1beta2/patch.go
util/conditions/v1beta2/patch_test.go
util/patch/patch.go
util/patch/patch_test.go

Enforce sorting of v1beta2 conditions when patching
/area util

🐛 Fix sorting of v1beta2 conditions when patching

---

api/v1beta1/machineset_types.go
api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/collections/machine_filters.go
util/collections/machine_filters_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go

✨ Add more v1beta2 conditions to KCP

---

internal/controllers/machine/machine_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go

We have added necessary input validations for controller to check for nil values for clustercache via PR https://github.com/kubernetes-sigs/cluster-api/pull/11327
So removing this unnecessary checks as it already checked before.
Fixes #

:seedling: Remove clustercache nil checks

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go

Ensures KCP sets the following conditions at its owned Machine's .spec.readinessGates:
- controlplanev1.MachineAPIServerPodHealthyCondition
- controlplanev1.MachineControllerManagerPodHealthyCondition
- controlplanev1.MachineSchedulerPodHealthyCondition
- controlplanev1.MachineEtcdPodHealthyCondition
- controlplanev1.MachineEtcdMemberHealthyCondition
Part of 
- #11105

🌱 kcp: ensure ReadinessGates for v1beta2 conditions get set

---

controllers/remote/cluster_cache_tracker.go

Forgot to deprecate this one, but it's important that folks migrated to ErrClusterNotConnected.
Kudos to @chrischdi for finding it!
Part of #11272

🌱 Deprecate CCT ErrClusterLocked

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

I think we should not publish events every time we get a reconcile errors. This can be very very spamy
Note: We have exponential backoff, but Reconcile will still be additionally triggered by updates on watched events.
P.S. There's another occurence of this, but Fabrizio will take care of that one in #11338
Fixes #

🌱 Drop ReconcileError events

---

controllers/remote/cluster_cache_healthcheck_test.go

Not sure why this test suddenly became flaky without any code changes (as far as I can tell).
(Maybe it was also flaky since a while, not sure)
Let's see if this somehow improves the situation.
Failed runs:
* https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11339/pull-cluster-api-test-main/1850888969013694464
* https://storage.googleapis.com/k8s-triage/index.html?job=.*cluster-api.*main&test=TestClusterCacheHealthCheck&xjob=.*-e2e-.*%7C.*-provider-.*
Fixes #

🐛 Try to fix TestClusterCacheHealthCheck test

---

util/conditions/v1beta2/patch.go
util/conditions/v1beta2/patch_test.go
util/conditions/v1beta2/setter.go
util/conditions/v1beta2/setter_test.go

This PR ensures lastTransitionTime for v1beta2 conditions is rounded down to second, thus making it consistent what we have in memory with what Marshal/Unmarshal will do while the data is sent to/read from the API server.
(this makes writing our tests simpler)

🌱 Truncate lastTransitionTime for v1beta2 conditions

---

test/e2e/clusterctl_upgrade.go
test/framework/cluster_proxy.go

Ensures that applying the cluster template in clusterctl upgrade e2e tests succeeds in dry-run before actually creating/updating
as discussed here: https://github.com/kubernetes-sigs/cluster-api/issues/11133#issuecomment-2432255732

:seedling: Add dry-run CreateOrUpdate call in clusterctl upgrade e2e tests

---

api/v1beta1/machinedeployment_types.go
api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/controllers/status.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_status.go

✨ Add v1beta2 condition to MD controller

---

internal/controllers/clusterclass/clusterclass_controller.go

RuntimeClient is only mandatory if RuntimeSDK feature gate is enabled
xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1730227198605269
Fixes #

🐛 Fix RuntimeClient nil check in ClusterClass controller

---

CONTRIBUTING.md
docs/release/release-team.md
docs/release/release-templates.md

This PR update SIG Cluster Lifecycle mailing list from [old one](https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle)  to [new one](https://groups.google.com/a/kubernetes.io/g/sig-cluster-lifecycle).

📖 Update SIG Cluster Lifecycle mailing list

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/client/config_test.go
cmd/clusterctl/cmd/config_repositories_test.go
docs/book/src/reference/providers.md

This PR adds the Canonical Kubernetes bootstrap and control-plane providers to the `clusterctl` default providers and updates the provider reference accordingly in the documentation.
https://github.com/canonical/cluster-api-k8s

:seedling:  Add Canonical Kubernetes providers

---

test/e2e/scale.go
test/e2e/scale_test.go

Make scale e2e test reusable for CAPM3 and other providers
- Export `ScaleSpec` and `ScaleSpecInput` to allow reuse in other providers.
- Add `PostScaleClusterNamespaceCreated` hook, which is called after generating the cluster name and namespace but before applying the template. This enables provider-specific customizations and allows adapting the cluster template accordingly before application such as adding specific cluster endpoints.
Fixes #11332

🌱 Export scale e2e test to make it reusable by providers

---

internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/machine/machine_controller_phases.go

This PR refactors the cluster controller introducing the same changes recently introduced in machine controller, machineset controller, md controller.
This will allow to add v1beta2 conditions in a follow-up PR
/area cluster

🌱 Refactor Cluster controller

---

docs/book/src/developer/providers/contracts/control-plane.md
docs/proposals/20240916-improve-status-in-CAPI-resources.md

This PR introduces a few small changes to the "Improving status in CAPI resources" proposal aligning it with what is being implemented

📖 Minor changes to Improving status in CAPI resources

---

exp/topology/desiredstate/desired_state.go
exp/topology/desiredstate/desired_state_test.go

Creation of the infrastructure template in desired state for the `Cluster` is always using namespace of the template, while `Cluster` object namespace is ignored. This changes behavior to use `Cluster` namespace for the generated template, which allows referencing `ClusterClass` from a `Cluster` resource located in different namespace, if validating policy allows it.
Related to #5673

:sparkles: ClusterClass: ensure templates are created in the Cluster namespace

---

controllers/remote/cluster_cache_healthcheck_test.go

This PR is a followup of this one: https://github.com/kubernetes-sigs/cluster-api/pull/11343. We're comparing durations with nanosecond precision, which is causing test flakiness. This PR resolves the issue by rounding durations to seconds instead of checking at the nanosecond level.
Failed runs:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11339/pull-cluster-api-test-main/1850888969013694464
https://storage.googleapis.com/k8s-triage/index.html?job=.*cluster-api.*main&test=TestClusterCacheHealthCheck&xjob=.*-e2e-.*%7C.*-provider-.*
Fixes #

🌱 Fixing TestClusterCacheHealthCheck flake

---

util/patch/patch_test.go

🐛 Fix panics in patch unit tests

---

CHANGELOG/v1.8.5.md

Add release notes for v1.8.5
Fixes #
/area release

🚀 Release v1.8.5

---

README.md

In README.md, the link to ClusterAPI's weekly meetings' agenda / minutes doc points to a document that's inaccessible.
This change updates that link to https://cluster-api.sigs.k8s.io/agenda which points to the correct agenda doc.

📖 🐛 README.md: update ClusterAPI meeting agenda link

---

config/manager/manager.yaml
docs/book/src/tasks/experimental-features/experimental-features.md
feature/feature.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

Since https://github.com/kubernetes-sigs/cluster-api/pull/11246 we are now also considering VolumeAttachments. Goal of this feature gate is to allow folks to opt-out in case unexpected problems occur.
Part of #11240

🌱 Add feature gate to consider VolumeAttachments when waiting for volume detach

---

api/v1beta1/machineset_types.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go

Needs a rebase after #11364 is merged

🌱 Implement KCP and MS Deleting conditions

---

controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

✨ Add v1beta2 available condition to KCP

---

api/v1beta1/machine_types.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

✨ Add machine UpToDate condition to KCP

---

api/v1beta1/cluster_types.go
api/v1beta1/condition_consts.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

🌱 Implement Cluster TopologyReconciled v1beta2 condition

---

internal/controllers/cluster/cluster_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go

🌱 Audit patch withOwnedConditions

---

internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinedeployment/mdutil/util_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

✨ Add machine UpToDate condition to MachineSet

---

controlplane/kubeadm/internal/control_plane_test.go

Example test failure: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-main/1855749512954384384
Fixes #

🐛 Fix TestControlPlane/MachinesUpToDate flake

---

controllers/clustercache/cluster_accessor.go
controllers/clustercache/cluster_accessor_test.go
controllers/clustercache/cluster_cache.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go

This PR adds support for typed watched to ClusterCache.
This will be specially useful when you want to reconcile a single object on the workload cluster.
With the current API to reconcile a single object on the workload cluster we need to reconcile an object on the mgt cluster that inturn reconciles all objects on the workload cluster. 
An example use case when the new API would be useful:
Reconciling a single workload cluster node instead of queueing the CAPI Cluster to then reconciler all workload cluster nodes.
Fixes #
/area clustercachetracker

✨  add typed watcher to ClusterCache

---

controllers/external/types.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/clusterclass/clusterclass_controller.go

It doesn't make sense that the ClusterClass and MachinePool controller skip reconcileExternal if an external object is paused. So let's get rid of it
We made the same change to a few other controllers already. So this is just a cleanup for the remaining controllers that have that handling
Fixes #

🌱 Remove paused handling from reconcileExternal

---

Makefile
Tiltfile

🌱 Bump Go version to v1.22.9

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/machine/drain/drain.go
internal/controllers/machine/drain/drain_test.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go
test/e2e/node_drain.go
util/conditions/v1beta2/aggregate_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go
util/conditions/v1beta2/mirror.go
util/conditions/v1beta2/mirror_test.go
util/conditions/v1beta2/summary.go
util/conditions/v1beta2/summary_test.go

Make condition messages more consistent

🌱 Refine v1beta2 condition messages

---

api/v1beta1/cluster_types.go
api/v1beta1/machine_types.go
api/v1beta1/machinedeployment_types.go
api/v1beta1/machineset_types.go
api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go
util/conditions/v1beta2/aggregate.go
util/conditions/v1beta2/aggregate_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go
util/conditions/v1beta2/options.go
util/conditions/v1beta2/summary.go
util/conditions/v1beta2/summary_test.go

Make condition reasons more consistent
Part of #11105

🌱 Refine v1beta2 condition reasons

---

api/v1beta1/cluster_types.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go

We don't need a message in the success case. The reason is good enough. Also the reasons could be shorter
Part of #11105

🌱 Improve Cluster RemoteConnectionProbe condition

---

util/conditions/v1beta2/sort.go
util/conditions/v1beta2/sort_test.go

🌱 Improve v1beta2 condition ordering

---

internal/controllers/cluster/cluster_controller_status.go

Currently the conditions on Cluster level are showing a lot of errors as soon as MachinePools are used, because conditions are not yet implemented for MachinePools.
This PRs temporariliy stops aggregating conditions from MachinePools and MachinePool Machines to end up with a clean status on the Cluster resource. This PR can be reverted once the conditions are implemented on MachinePools and MachinePool Machines.
Part of #11105

🐛 Disable aggregation of not reported MachinePool conditions for Cluster

---

api/v1beta1/cluster_types.go
api/v1beta1/machine_types.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go
util/conditions/v1beta2/mirror.go

Make mirror conditions more consistent

🌱 Refine v1beta2 mirror conditions

---

util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/summary_test.go

Preserve the order of relevance defined by the users (the order of condition types) when computing the summary
/area util

🌱 Refine order for v1beta2 summary util

---

internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go

Make CP machines to show up first when aggregating conditions from many machines
/area util

🌱 Refine v1beta2 aggregation order

---

internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
util/conditions/v1beta2/sort.go
util/conditions/v1beta2/sort_test.go

Improve condition sort so that Readiness/Availability gates shows up before paused/deleting
Align condition order in Cluster Available condition to condition sort order
/area util

🌱 Refine v1beta2 condition order

---

internal/controllers/topology/cluster/cluster_controller.go

RuntimeClient is only mandatory if RuntimeSDK feature gate is enabled
Fixes #

🐛 Fix RuntimeClient nil check in Cluster controller

---

util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go

Improve object sort in aggregation so CP machines always go first
/area util

🌱 Refine v1beta2 object sort for aggregation

---

api/v1beta1/clusterclass_types.go
api/v1beta1/condition_consts.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_status.go
internal/controllers/clusterclass/clusterclass_controller_status_test.go
internal/controllers/clusterclass/clusterclass_controller_test.go

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/11105

🌱 Add v1beta2 conditions to ClusterClass

---

controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go

🌱 Ignore new Machines when calculating MachinesUpToDate condition

---

controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/machineset/machineset_preflight.go
internal/controllers/machineset/machineset_preflight_test.go

Ensure scaling up conditions shows preflight errors using lists

🌱 Refine v1beta2 ScalingUp conditions

---

controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

🌱 Fix messages of conditions used for summaries and aggregations

---

internal/controllers/machine/machine_controller.go

Before this PR only reconcileDelete was rate-limited. reconcileBootstrap, reconcileInfrastructure and updateStatus were still executed. Because of that during Machine deletion the BootstrapReady, InfrastructureReady and Deleting condition were slightly out of sync. This PR makes sure that everything is rate-limited together
Fixes #11105

🌱 Rate-limit entire reconcileDelete

---

internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/options.go
util/conditions/v1beta2/summary_test.go

Refine machine's ready condition by grouping control plane and etcd conditions when they all have the same message
/area machine

🌱  Refine v1beta2 machine ready

---

controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller_status.go
internal/controllers/machineset/machineset_controller_status_test.go

Improve messages for stale machines and makes them consistent across conditions
Note: this PR does not tackle the issue of code duplication that we already have for some func we are using when computing conditions

🌱 Refine v1beta2 stale deletion messages

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

Refine KCP's ControlPlaneHealthy condition by grouping conditions when they all have the same message

🌱 Refine v1beta2 ControlPlaneHealthy condition

---

controllers/clustercache/cluster_accessor_client.go
controllers/remote/cluster_cache_tracker.go

Context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1731096886259339
Fixes #

🐛 Improve context handling in ClusterCache

---

CHANGELOG/v1.9.0-beta.1.md

Add release note for v1.9.0-beta.1
Part Of: https://github.com/kubernetes-sigs/cluster-api/issues/11092
/area release

🚀 Release v1.9.0-beta.1

---

util/conditions/setter.go
util/conditions/setter_test.go

This PR existing behavior of Set condition function as follows
Existing behavior
1. Update condition.LastTransitionTime to current time whenever any one of the fields(Status, Reason, Severity, Message) changes in new condition.
2. Sets the condition.LastTransitionTime to newConidtion.LastTransitionTime if defined only when the newCondition does not exist.
Proposed behavior
1.  Update condition.LastTransitionTime to current time only when Status field of new condition differ from existing condition status.
2. Sets the condition.LastTransitionTime to newCondition.LastTransitionTime  if defined whether the newCondition already exist or new.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

🌱 Update conditions.Set function to set LastTransitionTime only when status of condition changes

---

internal/controllers/machineset/machineset_delete_policy.go
internal/controllers/machineset/machineset_delete_policy_test.go

Right now, the `oldest` and `newest` deletion policies prioritize machines that have the `cluster.x-k8s.io/delete-machine` annotation over unhealthy machines when deciding which machines need to be deleted. This wasn't the case with the `random` deletion policy. This change aligns the latter to the rest, making it honor the deletion annotation.
The unit tests for that part of the code have also been modified to be more strict when comparing machines with this annotation, always comparing them with unhealthy machines.
Fixes #11387 

🐛 Align "random" deletion policy behavior regarding deletion annotations

---

controlplane/kubeadm/internal/etcd/util/util.go

When reading etcd members, it might happen that a member doesn't have yet the name set. 
This PR makes sure the comparison between etcd members list read from different machines takes into account members without name properly.
Note: this is usually a temporary issue
Fixes #

🌱 KCP: handle members without name in MemberNames

---

internal/controllers/machineset/machineset_controller.go

The MS controller reads the MD object to figure out if the Machines of a MachineSet are outdated.
Because we didn't have a watch on MDs it could take up to 10m until the MS controller realized its Machines were outdated.
Note: The impact was limited to UpToDate conditions on Machines being updated up until 10m late.
Part of #11105

🌱 Add MD watch to the MS controller

---

controlplane/kubeadm/internal/etcd/util/util_test.go

Adds unit test coverage for etcd member util functions
Fixes #
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11446

🌱 KCP: add test coverage for etcd member list util

---

controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

Retry in case KCP is scaling/up down/rolling out and well know etcd temporary errors happens while updating etcd conditions

🌱 Retry in case of etcd errors in KCP

---

controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go

Improve KCP available condition so:
- It uses etcd members list as a source of truth when computing etcd availability (this prevent issues when list of machines and list of members are temporarily not aligned while provisioning or deleting a CP machine)
- It takes into account etcd members for computing quorum
- Messages of partial unavailability takes properly account for unhealthy reported/not reported yet

🌱 Refine v1beta2 KCP available condition

---

controlplane/kubeadm/main.go

This PR enable caching for kubeadm static pods only in KCP.
The main reason while we identified this improvement was to improve KCP rollouts when temporary connection issue happens.
With the previous setup, pod where not cached, and thus every KCP reconcile a series of API calls where issues to gather status of the controlplane components in the workload cluster.
However, in case of temporary connection issues, kcp was "freezing" because stuck in a series of get pod--> wait 10s second timeout.
While looking at options to fix this issue, we figured out that by caching selectively the kubeadm Pods we can achieve a good trade off between:
- stability (we keep reading from cache/without errors, while informers behind the scene takes care of the …

🌱 Cache Pods for KCP

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

This PR prevents drain and detatch volume to happen for CP machines where KCP's PreTerminateDeleteHookAnnotation has been already removed.
This prevents drain and detach volume to spam the logs with error messages because at this stage kubelet on CP machines stops to works.
/area machine

🌱 Improve Drain for control plane machines

---

bootstrap/kubeadm/api/v1beta1/v1beta2_condition_consts.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go

🌱 Add v1beta2 conditions to CABPK

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/getting-started.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Cluster-api likes to be at the latest cert-manager version. This PR bumps cert manager to the latest release
Last time this was done: https://github.com/kubernetes-sigs/cluster-api/pull/11322

🌱Bump cert-manager to v1.16.2

---

api/v1beta1/cluster_types.go
api/v1beta1/machinedeployment_types.go
api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/cluster/cluster_controller_status_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
util/conditions/v1beta2/sort.go

🌱 Add v1beta2 RollingOut condition

---

cmd/clusterctl/cmd/version_checker.go

Using `go build` or `go install` to get a clusterctl binary and using it results always in failing commands.
According to the comment in the referenced code, binaries built with go build should fall in the same category as when using a build from dirty git.
This prevents trying to parse an empty git version information.
Fixes #11466

🌱 clusterctl: do not fail when running clusterctl with a build without GitVersion information

---

exp/addons/api/v1beta1/clusterresourceset_types.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go

🌱 crs: implement ResourcesApplied v1beta2 condition

---

cmd/clusterctl/client/describe.go
cmd/clusterctl/client/tree/annotations.go
cmd/clusterctl/client/tree/discovery.go
cmd/clusterctl/client/tree/node_object.go
cmd/clusterctl/client/tree/tree.go
cmd/clusterctl/client/tree/tree_test.go
cmd/clusterctl/client/tree/util.go
cmd/clusterctl/cmd/describe_cluster.go

Add supports for v1beta2 conditions to clusterctl describe
**Which issue(s) this PR fixes***:
Rif #11105 

✨ Add support for v1beta2 conditions to clusterctl describe

---

docs/book/src/SUMMARY.md
docs/book/src/developer/providers/contracts/ipam.md
docs/book/src/developer/providers/contracts/overview.md

Adds the [IPAM contract](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md) to the book. 
/area ipam

📖 book: add ipam contract

---

.github/workflows/pr-md-link-check.yaml

following https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/ci-signal#setup-jobs-and-dashboards-for-a-new-release-branch
update the link check

:seedling: [release-1.9] Update md link check for release-1.9

---

hack/ensure-kind.sh

…v1.30
Downgrades kind to v0.24.0 because v0.25.0 is currently broken in building images from prebuilt binaries for kubernetes < v1.31.
Partially reverts:
- https://github.com/kubernetes-sigs/cluster-api/pull/11473
Fixes #
xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1732652928530129
/area ci

🐛 kind: downgrade binary to v0.24.0 to fix building node images for <= v1.30

---

internal/controllers/machine/machine_controller.go

Sorts the hooks alphabetically so the message is deterministic because the order may change.
Fixes #
/cherry-pick release-1.9

🌱 machine: sort list of hooks for stable condition messages

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

Uses the correct APIVersion when checking ownerreference for KCP for excluding machines from drain & wait for volumes after the pre-terminate hook was removed.
Fixes #
/area machine

🐛 machine: use correct APIVersion for KCP related exclude

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_etcd.go
controlplane/kubeadm/internal/workload_cluster_etcd_test.go

We recently added the list of etcd members to KCP's scope, so we can start dropping calls re-reading the same info.
This is the first one that caught my attention
Area example:

🌱 Drop unnecessary etcd call from KCP

---

internal/controllers/machine/machine_controller_status.go
internal/controllers/machine/machine_controller_status_test.go

Improve NodeHealthy by grouping node conditions when all have the same message
/area machine

🌱 Refine v1beta2 NodeHealthy condition

---

util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/summary_test.go

When computing summary conditions, if a condition is not reporting a message surface reason (it should be more informative than the current generic message)

🌱 Refine v1beta2 summary

---

internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go

When MD is deleting, do not show details about available / min required replicas

🌱 Refine MachineDeployment v1beta2 available condition

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machinehealthcheck/suite_test.go

Flaky test:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-main/1860329478199185408
Was introduced in https://github.com/kubernetes-sigs/cluster-api/pull/11465
Fixes #

:bug: MHC: fix flaky test

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
internal/controllers/machinedeployment/machinedeployment_status.go
internal/controllers/machinedeployment/machinedeployment_status_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/merge_strategies_test.go
util/conditions/v1beta2/summary_test.go

- Improve UpToDate condition applied by KCP/MD to Machines so it shows different reasons using a list (instead of a comma separated string)
- Improve RolloutOut condition in KCP/MD so it takes into account that now Machines's UpToDate is a list
- Improve RolloutOut condition at Cluster level so messages are indented
- Add more test for merge strategies

🌱 Refine v1beta2 UpToDate and Rollout conditions

---

cmd/clusterctl/cmd/describe_cluster.go
cmd/clusterctl/cmd/describe_cluster_test.go

Example:
Before:
After:
Fixes #

🌱 clusterctl: properly indent multiline lists in clusterctl describe

---

.golangci.yml
api/v1beta1/machinedeployment_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml

Fixes #11470
/hold for consensus on the issue

⚠️ Deprecate MD.Spec.ProgressDeadlineSeconds

---

.golangci.yml
api/v1beta1/machinedeployment_types.go
api/v1beta1/machineset_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
exp/api/v1beta1/machinepool_types.go

https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md introduced the idea of having consistent replica fields across all API objects.
This PR adds an early deprecation notice for replica fields that will be dropped when implementing this proposal, so API users can start planning for when this will happen (similar to what we already did for FailureMessage and FailureReason)
/area api

⚠️ Deprecate replica counters planned for removal

---

controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

It seems that this is now unnecessary after recent changes to avoid unnecessary release calls

🌱 Drop retry when computing KCP conditions

---

docs/book/src/tasks/experimental-features/runtime-sdk/index.md

This PR adds a caution note to the documentation indicating that hooks are only invoked for Clusters created using ClusterClass. This clarification is necessary because, despite enabling the RuntimeSDK feature, hooks will not be delivered to clusters not created with ClusterClass.
Fixes #

📖 Add warning note about hook invocation in SDK

---

docs/book/src/introduction.md

📖 add release 1.8 book link

---

test/e2e/node_drain.go
test/e2e/node_drain_test.go
test/framework/convenience.go

…o node drain test
Adds options to the node drain test to check for volume detachments to be blocking as expected.
Fixes #

🌱 test: add options for additional resources and verify volume detach to node drain test

---

test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Bumps kubernetes to v1.32.0-rc.1 in e2e tests.
Fixes #

🌱 Bump kubernetes release to v1.32.0-rc.1

---

internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/machinedeployment_rolling_test.go
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go

1. Create a cluster with rolling machine deployment.
2. Change to onDelete machine deployment
3. Make some change to generate new machineSet
4. DisableMachineCreateAnnotation is set on old machineSet, while new machineSet scales up
5. Switch back to rolling machine deployment
6. Removing the change made in step 3 will try to use the old machineSet but new machines wont be created because of the annotation.
The flow above prevents machines from being created with the following error `Automatic creation of new machines disabled for machine set ` . We should remove this annotation during the machine deployment rolling reconciliation.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …

🐛 remove disableMachineCreate annotation from new machinesets during rolling machine deployment reconciliation

---

Makefile
Tiltfile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11534

[release-1.7] 🌱 Bump go 1.22.10

---

test/e2e/scale.go

Minor fix for the scale test log, which helps properly displaying the namespace name.
Fixes #

:bug: Properly display the namespace name in scale test

---

CHANGELOG/v1.7.9.md

- Release notes for v1.7.9
/area release

🚀 Release v1.7.9

---

CHANGELOG/v1.9.0.md

- Release notes for v1.9.0
/area release

🚀 Release v1.9.0

---

docs/book/src/developer/core/tilt.md
docs/book/src/user/quick-start.md
test/framework/bootstrap/kind_provider.go
test/infrastructure/kind/mapper.go

Kind added a new image for v1.32.0: https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0
Part of:
- #11064
Fixes #

🌱 Bump default kind image to v1.32.0

---

docs/release/releases/release-1.10.md

This PR adds release-1.10 cycle schedule document with preliminary dates taking into account [Kubecon Europe 2025](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) between April 1-4, 2025 on week 16th in the schedule.
/area release

📖 Add Cluster API release-1.10 timeline document

---

docs/book/src/reference/providers.md

This is a minor update on the name of the Canonical Kubernetes. We would rather use the long version of it in the docs.
**Which issue(s) this PR fixes**: None

:book: Use long name version for Canonical Kubernetes

---

.github/workflows/pr-md-link-check.yaml
.github/workflows/weekly-md-link-check.yaml

The current version of the `github-action-markdown-link-check` GH Action is old and has a bug which causes false positives for Markdown links with percent encoding.
Sample failure: https://github.com/kubernetes-sigs/cluster-api/actions/runs/12398892275/job/34612869781
None

:seedling: Bump github-action-markdown-link-check to 1.0.15

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/runtime/internal/controllers/extensionconfig_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/predicates/generic_predicates.go

When hitting the resync period: additional watches lead to additional re-reconciliations.
To prevent this unnecessary work (because we did reconcile the resync event for the secondary object on the main object too) we add a predicate which filters out the event when a "secondary object"'s Generation is unchanged.
Note: the same way, controller-runtime identifies the priority of an event (new feature): 
https://github.com/kubernetes-sigs/controller-runtime/pull/3014/files#diff-3933f25e7d6df3b6e84e6ef6f0d67d5583abc10ec8232fe2f584990ce6da6521R175-R176
Fixes #
/area util

🌱 add TypedAll, ResourceIsUnchanged and TypedResourceIsUnchanged predicates

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/scale.go
util/failuredomains/failure_domains.go
util/failuredomains/failure_domains_test.go

KCP tries to achieve spreading of machines across failure domains
The current implementation achieve the goal by balancing up-to-date/new machines created during scale up/rollout, whitout caring of the placement of outdated/old machines (because they are going away).
This PR improves the behaviour above by considering the entire set of machines as a secondary criteria when there there are  failure domains with the same number of up-to-date/new machines. This ensure a better spreading of machines also during scale up/rollout (not only at the end).
E.g.:
FD 1: Machine A
FD 2: Machine B
FD 3 Machine C
Scale up:
- Adds D to FD 3 (random pick from FD 1, FD 2, FD 3 all of them with the same number of machines at this point)
FD 1: Machine A
FD 2: Machine B …

🌱 Improve KCP scale up when using failure domains

---

hack/observability/grafana/chart/kustomization.yaml
hack/observability/kube-state-metrics/kustomization.yaml
hack/observability/loki/kustomization.yaml
hack/observability/loki/values.yaml
hack/observability/metrics-server/kustomization.yaml
hack/observability/parca/kustomization.yaml
hack/observability/prometheus/kustomization.yaml
hack/observability/promtail/kustomization.yaml
hack/observability/tempo/kustomization.yaml

Updates all helm charts of the observability stack to the latest versions including checks:
* grafana
* checked all dashboards
* kube-state-metrics
* confirmed via dashboards are working
* loki
* queried logs successfully via grafana
* metrics-server
* `kubectl top node` and `kubectl top pod -A`
* parca
* 25 Good endpoints before
* 25 Good endpoints after
* Note: test-extension was broken before and after
* prometheus:
* all scrape targets are green
* same targets exist
* promtail
* queried logs successfully via grafana
* tempo
* was queryable, but did not have any traces (because we don't have traces)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

🌱 observability: bump helm charts to newer versions

---

internal/controllers/topology/cluster/cluster_controller.go

[release-1.9] 🌱 Reconcile topology only when necessary

---

internal/controllers/topology/cluster/cluster_controller.go

The topology controller is responsible to enforce the desired state of the cluster, and it does this ensuring that the spec of the cluster itself and the spec of the dependant objects like e.g. Machine Deployment is consistent with what defined in the ClusterClass.
That means that this controller should not care of changes to objects status (or at least to a subset of changes in status).
This PR introduces two predicates starting to drop reconcile events when the changes are not relevant for the topology controller
/area cluster

🌱 Reconcile topology only when necessary

---

CHANGELOG/v1.9.2.md

🚀 Release v1.9.2

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Partial cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11616
Fix CVE: https://avd.aquasec.com/nvd/2024/cve-2024-45338/
Fixes #

[release-1.8] 🌱 Bump to golang.org/x/net v0.23.0

---

docs/book/src/developer/providers/getting-started/overview.md

Fixes None
Wrong link in https://cluster-api.sigs.k8s.io/developer/providers/getting-started/overview#we-need-your-help.
- Find `[Cluster API videos and tutorials](https://cluster-api.sigs.k8s.io/developer/guide.html#videos-explaining-capi-architecture-and-code-walkthroughs)`.

📖 Fix a link for Cluster API videos and tutorials

---

hack/observability/grafana/dashboards/runtime-extensions.json

Fix a panel title + ensure all bot discoveryvariables and generatepatches are shown (like in other panels)
/area devtools

🌱 Fix reconcile extensions dashboard

---

hack/ensure-kind.sh
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/kind/mapper.go

🌱 Bump sigs.k8s.io/kind to v0.26.0

---

OWNERS_ALIASES
docs/release/releases/release-1.10.md

Updates the release-1.10 cycle documentation to include the release team members
N/A
/area release

📖 Update Cluster API release-1.10 release team members

---

exp/runtime/internal/controllers/extensionconfig_controller.go
internal/controllers/topology/cluster/reconcile_state.go
internal/runtime/client/client.go

🌱 Reduce log level of noisy logs in ExtensionConfig and Cluster controller

---

test/e2e/e2e_suite_test.go

This allows to use e.g. --v=8 to get the detailed client-go log messages
Fixes #

🌱 Add log command line flags to e2e test binary

---

test/infrastructure/inmemory/pkg/runtime/cache/client_test.go
test/infrastructure/inmemory/pkg/runtime/cache/informer.go
test/infrastructure/inmemory/pkg/runtime/cache/sync_test.go

In general generic events only exist in controller-runtime.
Our in-memory kube-apiserver should return update events on resync like the regular kube-apiserver
Fixes #

🐛 Fix periodic resync in in-memory provider

---

controlplane/kubeadm/internal/etcd/etcd.go
go.mod

Noticed during scale tests that `clientv3.New` was creating a new logger every time it was called. This was responsible for ~ 7% of memory allocations in KCP.
Fixes #

🌱 KCP: stop recreating logger for etcd client

---

util/patch/patch.go

Not every time when `patch.NewHelper` is called we also call `Patch`. This change avoids memory allocations in these cases by moving the `toUnstructured` call to the `Patch` func.
Kudos to @fabriziopandini for the idea & implementation
Fixes #

🌱 patchHelper: call toUnstructured only if necessary

---

controlplane/kubeadm/internal/etcd/etcd.go
go.mod

Manual cherry-pick of #11664
Fixes #

[release-1.8] 🌱 KCP: stop recreating logger for etcd client

---

util/patch/patch.go

Co-authored-by: fabriziopandini fpandini@vmware.com
Manual cherry-pick of #11665
Fixes #

[release-1.8] 🌱 patchHelper: call toUnstructured only if necessary

---

hack/observability/grafana/dashboards/controller-runtime.json
hack/observability/loki/values.yaml

* changes controller-runtime dashboard to get filter values from time filtered data, not only latest
* changes controller-runtime dashboard to add min/max/mean to some tables
* adjust loki to allow more throughput
Fixes #
/area devtools

🌱 observability: improvements to grafana and loki

---

.golangci.yml
controlplane/kubeadm/internal/controllers/helpers.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machineset/machineset_controller.go
util/util.go

Manual cherry-pick of #11666
Fixes #

[release-1.8] 🌱 Call patchHelper only if necessary when reconciling external refs

---

internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machine/machine_controller_phases.go
util/util.go

follow-up to #11666
After #11666 we stopped patching external referenced objects when the UID differs. This PR fixes that case.
(Not entirely sure if this case ever happens, because I'm not sure if clusterctl move preserves the ownerRefs, but just playing it safe doesn't hurt)
Fixes #

🐛 Also patch external refs if the UID differs

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets.go

This PR improve logs added when a machine is remediated by adding key value pair for Machine ns/name and another for the node name, while dropping the key "target" which contained a confusing "MHC.Namespace/MHC.Name/Machine.Name/Node.Name".
Also, message now uses a more intuitive "Machine has failed health check..." instead of "Target has failed health check"
/area machinehalthcheck

🌱 Improve Machine remediation logs

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/getting-started.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Cluster-api likes to be at the latest cert-manager version. This PR bumps cert manager to the latest release
Last time this was done: https://github.com/kubernetes-sigs/cluster-api/pull/11462

🌱Bump cert-manager to v1.16.3

---

controllers/clustercache/cluster_accessor_client.go

The clustercache has an issue with concurrent read writes. Found data races:
```
WARNING: DATA RACE
Write at 0x00c000d48480 by goroutine 378:
runtime.mapaccess2()
/Users/schlotterc/.bin/go-archive/go1.23.2.darwin-arm64/src/runtime/map.go:479 +0x28c
sigs.k8s.io/controller-runtime/pkg/cache.defaultOpts()
/Users/schlotterc/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/cache/cache.go:523 +0x650
sigs.k8s.io/controller-runtime/pkg/cache.New()
/Users/schlotterc/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/cache/cache.go:340 +0x70
sigs.k8s.io/cluster-api/controllers/clustercache.createCachedClient()
/Users/schlotterc/go/src/sigs.k8s.io/cluster-api/controllers/clustercache/cluster_accessor_client.go:224 +0x120 …
```

🐛  clustercache: Prevent concurrent map read/write when creating a cache

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/scale.go
internal/controllers/machineset/machineset_controller.go
util/collections/machine_collection.go

This PR improve logs whenever we create a Machine in KCP or MS, more specifically
- All the message text are consistent and include the reason why creation or deletion happened (scale up, scale down, remediation, KCP/MS deleted)
- Missing log messages on KCP machine creation has been added
/area machine

🌱 Improve Machine create and delete logs

---

Makefile

Currently fails https://github.com/kubernetes-sigs/cluster-api/actions/runs/12867580479/job/35872522098, propably due to the Go 1.23 bump.
Note: on main I had the same error as the GH action. Bumping govulncheck fixed it for me.
Fixes #
/area ci

🌱 govulncheck: bump to v1.1.4

---

internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

If you do not delete the bootstrapRef after failing to create the machineRef, it will cause the bootstrapRef to leak.
Fixes #

🌱 MachineSet controller: delete Bootstrap object when creating InfraMachine object failed

---

test/e2e/autoscaler_test.go
test/e2e/cluster_deletion_test.go
test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/cluster_upgrade_test.go
test/e2e/clusterclass_changes_test.go
test/e2e/clusterclass_rollout_test.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/k8s_conformance_test.go
test/e2e/quick_start_test.go
test/e2e/self_hosted_test.go

adds ginkgo labels to e2e tests
Part of #9620

🌱 Add ginkgo labels to e2e tests

---

controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go

In case of more than one unhealthy control plane machines, as of today KCP always remediate the oldest machine, and depending on the severity of the issue on the machines left after remediation, KCP can get stuck because of scale up preflight checks preventing creation of the replacement machine.
This PR tries to improve the chances of KCP automatically by trying to remediate first the "most broken" "most broken" machine among the unhealthy machines, determined as the machine having the highest priority issue that other machines have not.
The following issues are considered (from highest to lowest priority):
- machine without .status.nodeRef
- machine with etcd issue or etcd status unknown (etcd member, etcd pod)
- machine with control plane …

🌱 Improve KCP remediation of multiple failures

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
internal/util/ssa/cache.go
internal/util/ssa/metrics.go
internal/util/ssa/patch.go
internal/util/ssa/patch_test.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go

:seedling: Add SSA cache metrics

---

test/e2e/node_drain.go

The node-drain Docker test template was removed in #11127, but remained as the default flavor for `NodeDrainTimeoutSpec`. This can cause a nil pointer exception when a subsequent function expects `Spec.Toplogy` to be set.
CAPI explicitly supplies the `topology` flavor when calling the spec, so it didn't see this problem (but CAPZ did).
Refs kubernetes-sigs/cluster-api-provider-azure#5316
/area testing

🐛 Default to topology flavor in NodeDrainTimeoutSpec

---

internal/controllers/machineset/machineset_controller_test.go

Fixes flake TestMachineSetReconciler_syncReplicas_WithErrors test by explicitly use scheme in flake client.
Fixes #11722
/area testing

:bug: Fix flake TestMachineSetReconciler test

---

api/v1beta1/cluster_types.go
api/v1beta1/index/cluster.go
api/v1beta1/index/cluster_test.go
api/v1beta1/index/index.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
internal/apis/core/v1alpha4/conversion.go
internal/apis/core/v1alpha4/zz_generated.conversion.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/suite_test.go
internal/topology/check/compatibility.go
internal/topology/check/compatibility_test.go
internal/webhooks/clusterclass.go
internal/webhooks/clusterclass_test.go
util/test/builder/builders.go

Adding `classNamespace` variable to the cluster topology, which allows to point to a ClusterClass in a different namespace. This field is dormant, and is used for differentiation only.
Related to #5673

✨ Add classNamespace to topology

---

internal/topology/check/compatibility.go

Follow up to: https://github.com/kubernetes-sigs/cluster-api/pull/11352
Fixes #
/area topology

🌱 topology: fix godoc for LocalObjectTemplatesAreCompatible

---

config/manager/manager.yaml
controllers/alias.go
controlplane/kubeadm/config/manager/manager.yaml
controlplane/kubeadm/controllers/alias.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/main.go
internal/controllers/machineset/machineset_controller.go
main.go

Removes the flag `--use-deprecated-infra-machine-naming`, which was planned to disappear in CAPI v1.9.
Refs #10576
Refs #11172

⚠️ Remove deprecated flag for old infra machine naming

---

Makefile
Tiltfile

See the [release notes](https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved) for more detail. 
(CAPI's `main` branch is on go v1.23.5 now, which I assume we don't want to cherry-pick into the previous release branches. )

[release-1.9] 🌱 Bump go to v1.22.11

---

Makefile
Tiltfile

See the [release notes](https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved) for more detail. 
(CAPI's `main` branch is on go v1.23.5 now, which I assume we don't want to cherry-pick into the previous release branches. )

[release-1.8] 🌱 Bump go to v1.22.11

---

.github/workflows/pr-golangci-lint.yaml
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
exp/internal/controllers/machinepool_controller_phases.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/topology/desiredstate/desired_state_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/e2e/clusterclass_changes.go
test/e2e/self_hosted.go

This PR updates `golangci-lint` to the latest release and runs `make lint-fix` to fix up any issues that it found post update.
Some of the issues it came up with were odd, eg suggesting 
```
g.Expect(fakeRuntimeClient.CallAllCount(runtimehooksv1.BeforeClusterDelete)).To(Equal(1))
```
Instead of
```
g.Expect(fakeRuntimeClient.CallAllCount(runtimehooksv1.BeforeClusterDelete) == 1).To(Equal(tt.wantHookToBeCalled))
```
Which are not semantically equivalent.
These cases I fixed in a different way.
Some of the fixes that were being applied also removed a whole load of comments, so I didn't commit those, and `make lint-fix` no longer suggests removing those. One of the linters suggested fixes does not appear to be deterministic, sigh.
**Which issue(s) this …

🌱 Update golangci-lint to v1.63.4

---

.golangci.yml
feature/feature.go

Given that the ClusterResourceSet is now GA, the corresponding feature flag shold be deprecated, and it will be removed in 1.12.
Please note that, based on the behaviour implemented by http://k8s.io/component-base for GA flags:
- the ClusterResourceSet flag disappears from the CLI help
- the ClusterResourceSet flag can still be used and it is operational (it can be set to false)
- when you use the ClusterResourceSet flag, you get a warning
Ref https://github.com/kubernetes-sigs/cluster-api/issues/11114

⚠️ Deprecate the ClusterResourceSet feature flag

---

api/v1beta1/common_types.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

This PR contains the changes to priorities the machine with `cluster.x-k8s.io/remediate-machine` annotation
Fixes #11385

:seedling: Prioritize Machine with remediate-machine anotation when selecting the next machine to be remediated

---

test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-inmemory/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
test/e2e/scale.go
test/e2e/scale_test.go
test/framework/clusterctl/clusterctl_helpers.go
test/framework/clusterctl/e2e_config.go

Improvements to the scale test:
* Deploy additional ClusterClasses
* Consistent overwrites for input fields via variables
* Supports testing the cross-ns ClusterClass feature
* Supports testing Runtime Extensions
Kudos to @fabriziopandini & @chrischdi for prototyping most of these changes and the collaboration on scale testing
Additionally makes the ExtensionConfig name in scale & RuntimeSDK test configurable. 
This allows to run e.g. the Runtime SDK test with different ExtensionConfig names in parallel. This can also be useful when these tests are executed by an infra provider that is using a different ExtensionConfig name in their ClusterClass.
**Which issue(s) this PR fixes** *(optional, in …

✨ Extend scale test and make ExtensionConfig name in RuntimeSDK test configurable

---

api/v1beta1/index/cluster.go

Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/11352#pullrequestreview-2564853352
Fixes #

🌱 Deprecate old ClusterClass index

---

docs/book/src/developer/providers/contracts/bootstrap-config.md
docs/book/src/developer/providers/contracts/control-plane.md
docs/book/src/developer/providers/contracts/infra-cluster.md
docs/book/src/developer/providers/contracts/infra-machine.md
docs/book/src/developer/providers/getting-started/building-running-and-testing.md

* Use [labels](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/) to add labels to CRDs
* Fix `kustomize.yaml` -> `kustomization.yaml`
I'm developing a CAPI infrastructure provider, and I got a warning when executing`kustomize build`.
```console
$ kustomize build > /dev/null
```
ref: https://github.com/kubernetes-sigs/kustomize/pull/5464

🌱  Use labels for kustomize

---

docs/book/src/tasks/automated-machine-management/machine_deletions.md
docs/proposals/20240930-machine-drain-rules.md

📖 Update Machine deletion doc

---

controllers/alias.go
docs/book/src/reference/api/metadata-propagation.md
docs/proposals/20220927-label-sync-between-machine-and-nodes.md
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/suite_test.go
main.go

Add an flag to the CAPI manager to dictate the labels that should be synced form the Machine to the node. If the flag is not specified it defaults to:
```
Has node-role.kubernetes.io as prefix.
Belongs to node-restriction.kubernetes.io domain.
Belongs to node.cluster.x-k8s.io domain.
```
Any value specified by the flag would be additional to the list to default values. 
Fixes #11657
/area machine

🌱 Add --additional-sync-machine-labels to allow syncing additional labels to Nodes

---

docs/book/src/user/quick-start.md

Calico CNI troubleshooting section is related to all providers, except vcluster, but was hidden inside the KubeVirt tab which is not clear for users, who implementing Quick Start. This PR moving this section outside the KubeVirt to the common document part inside the `Deploy a CNI solution` section.
Fixes #

:book: Moving CNI troubleshooting section from KubeVirt tab

---

test/e2e/clusterctl_upgrade_test.go

**What this PR does / why we need it**: This is a recommendation from this comment https://github.com/kubernetes-sigs/cluster-api/issues/11610#issuecomment-2607792687 in #11610 to work around flaky upgrade tests and improve our CI signal. The root cause seems to be related to the docker controller but only affects older versions. So the goal is to just reduce the flakey signal by retrying the tests on those older versions (which just show up in our upgrade tests). 
Fixes #11209
Fixes #11610

:seedling: Attempt older version upgrades twice to work around flake with the docker controller

---

controllers/alias.go
docs/book/src/reference/api/metadata-propagation.md
docs/proposals/20220927-label-sync-between-machine-and-nodes.md
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/suite_test.go
main.go

This is an manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11650

[release-1.9] 🌱  Add --additional-sync-machine-labels to allow syncing additional labels to Nodes

---

internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_sync.go

🌱 Improve MachineSet create and delete logs

---

controllers/clustercache/cluster_accessor.go
controllers/clustercache/cluster_accessor_client.go
controllers/clustercache/cluster_accessor_test.go
controllers/clustercache/cluster_cache.go
controllers/clustercache/cluster_cache_test.go
controlplane/kubeadm/internal/cluster_test.go
exp/addons/internal/controllers/suite_test.go
exp/internal/controllers/suite_test.go
internal/controllers/cluster/suite_test.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/suite_test.go
internal/controllers/topology/cluster/suite_test.go
internal/test/envtest/environment.go

🐛 ClusterCache: Increase timeout for informer List+Watch calls from 10s to 11m

---

docs/book/src/user/quick-start.md

The KubeVirt sections in the quickstart guide are a bit old, and are not working as expected, as result of changes in several components.
This PR updates the old KubeVirt sections, to a working instructions. In addition, the guide now presents all the supported boot images.

:book: Update KubeVirt quickstart guide

---

hack/observability/grafana/chart/values.yaml
hack/observability/grafana/kustomization.yaml

…
Often getting the following when using tilt and having grafana enabled:
```
Build Failed: ConfigMap "grafana-dashboards-fb825bbkm2" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes
```
This resolves that by splitting up the dashboards configmap and instead have a single configmap per dashboard.
This way, when re-applying, the `last-applied-configuration' annotations` fits in again.
Fixes #
/area devtools

🌱 observability: split up grafana configmap to not exceed the size limits on reoccuring apply

---

docs/proposals/20240916-improve-status-in-CAPI-resources.md

As per Jan 29th office hour discussion

📖 Move v1beta2 tentative date from Apr 2025 to Aug 2025

---

test/e2e/quick_start.go

**What this PR does / why we need it**: The `e2e.QuickStartSpec` is an easy spec for third party ClusterAPI providers to add e2e tests. Adding `ClusterctlVariables` to the input allows injecting extra variables to the template in a manner that is local to the running tests. Potential alternatives like setting environment variables or generating a separate config file per test are a lot more trouble.
When this is not specified, it is a no-op, so no breaking changes.

:seedling: Add optional ClusterctlVariables to QuickStartSpecInput

---

Makefile
Tiltfile
hack/tools/go.mod
hack/tools/internal/tilt-prepare/main.go

Remove usage of the envsubst binary from the Makefile and tilt.
Affects
* `make generate-metrics-config` which now uses `sed` instead.
* tilt which now uses `clusterctl generate yaml --from` or the go based envsubst instead.
Fixes #
/area devtools

🌱 remove dependency to envsubst binary

---

scripts/ci-e2e-lib.sh

Removes the magic matching on GINKGO_FOCUS and GINKGO_SKIP for defaulting vars for building kind node images.
Instead we now explicitly mention which variables to default on a per-job base in test-infra and pass it as envvar. 
Needs the following PR to merge first:
- https://github.com/kubernetes/test-infra/pull/34252
/hold
Fixes #
/area ci

🌱 CI: default building kind node-images depending on KIND_BUILD_IMAGES env variable instead of ginkgo magic regexes

---

go.mod
internal/controllers/machine/drain/drain.go
internal/controllers/topology/cluster/current_state_test.go

golang.org/x/exp is experimental library, so it's good to use standard lib's API if the API is provided.
Fixes #

🌱  Use std API instead of exp API

---

cmd/clusterctl/client/clusterclass.go
cmd/clusterctl/client/clusterclass_test.go
cmd/clusterctl/client/config.go
cmd/clusterctl/client/repository/template.go
docs/book/src/developer/providers/contracts/clusterctl.md
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/clusterclass_changes.go
test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/quick_start.go
test/extension/handlers/topologymutation/testdata/clusterclass-quick-start-runtimesdk.yaml
test/framework/ownerreference_helpers.go

This PR allows `clusterctl` to create a template with a reference to CC located in a different namespace.
This change allows to perform e2e tests in a multi-ns environment.
Added e2e tests to verify cluster-class quick-start scenario and runtime extension scenario in a cross-namespaced context.
The PR is built on top of:
- https://github.com/kubernetes-sigs/cluster-api/pull/11361
- https://github.com/kubernetes-sigs/cluster-api/pull/11352
Fixes #5673

✨ Add e2e tests & clusterctl changes for cross-ns CC ref

---

test/e2e/clusterctl_upgrade_test.go

This is a manual cherry-pick of #11759

[release-1.8] 🌱 Attempt older version upgrades twice to work around flake with the docker controller

---

controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/etcd/etcd_test.go
controlplane/kubeadm/internal/etcd/fake/client.go

Drop MemberUpdate from etcd client in KCP (unused)

🌱 Drop MemberUpdate from etcd client in KCP

---

docs/release/releases/release-1.10.md

Updates the release-v1.10.md doc ~~to compress the v1.10 schedule in order~~ to accomodate an earlier code freeze and v1.11/v1beta2 schedule.
Refs #11656
/area release

📖 Update v1.10 release cycle schedule

---

controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

Drop un-used code to handle retry when reading KCP conditions

🌱 Drop retry when ready KCP conditions

---

bootstrap/kubeadm/internal/controllers/suite_test.go
controllers/clustercache/suite_test.go
controllers/remote/suite_test.go
controlplane/kubeadm/internal/suite_test.go
exp/internal/controllers/suite_test.go
exp/runtime/internal/controllers/suite_test.go
internal/controllers/cluster/suite_test.go
internal/controllers/clusterclass/suite_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/suite_test.go
internal/controllers/topology/cluster/structuredmerge/suite_test.go
internal/controllers/topology/cluster/suite_test.go

🌱 
This PR adds the cache in test environment to behave similar like in the real world.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/11742
<!-- 
Please label this pull request according to what area(s) you are addressing. For reference on PR/issue labels, see: https://github.com/kubernetes-sigs/cluster-api/labels?q=area+
Area example:

🌱  Sync Cache configuration in tests

---

controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/workload_cluster_conditions.go

Currently KCP reads the etcd alarm list several time for each reconcile, whenever we read the etcd member list.
With this PR, we are reading the etcd alarm list only in updateManagedEtcdConditions, which is the only place where this information is required.

🌱 Read etcd alarm list once per reconcile in KCP

---

test/e2e/cluster_upgrade_runtimesdk_test.go

Small cleanup. We don't run this test with v1.24 anymore :-)
Fixes #

🌱 e2e: drop v1.24 skip for runtime sdk test

---

test/e2e/cluster_upgrade.go
test/e2e/scale.go
test/e2e/self_hosted.go

Makes these variables optional in the scale test just as they are in the others. This makes it easier for providers who do not care about these versions.
Fixes #

🌱 e2e/scale: make coredns and etcd upgrade variables optional

---

Makefile
Tiltfile
netlify.toml

> go1.23.6 (released 2025-02-04) includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command. See the [Go 1.23.6 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.6+label%3ACherryPickApproved) on our issue tracker for details.
N/A

🌱 Bump go to v1.23.6

---

Makefile
Tiltfile
netlify.toml

Updates the Go toolchain to the latest 1.22.x patch release.
> go1.22.12 (released 2025-02-04) includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command. See the [Go 1.22.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.12+label%3ACherryPickApproved) on our issue tracker for details.
N/A

[release-1.9] 🌱 Bump go to v1.22.12

---

Makefile
Tiltfile
netlify.toml

Updates the Go toolchain to the latest 1.22.x patch release.
> go1.22.12 (released 2025-02-04) includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command. See the [Go 1.22.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.12+label%3ACherryPickApproved) on our issue tracker for details.
N/A

[release-1.8] 🌱 Bump go to v1.22.12

---

Makefile

Trying to align a bit more to https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration
Fixes #

🌱 test/e2e: order ginkgo flags, add --fail-on-pending --fail-on-empty, increase timeout to 3h

---

api/v1beta1/cluster_types.go
api/v1beta1/clusterclass_types.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/machineset_types.go
api/v1beta1/zz_generated.openapi.go
bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
internal/apis/bootstrap/kubeadm/v1alpha3/kubeadmconfigtemplate_types.go
internal/apis/bootstrap/kubeadm/v1alpha4/kubeadmconfigtemplate_types.go
internal/apis/controlplane/kubeadm/v1alpha4/kubeadmcontrolplanetemplate_types.go
internal/apis/core/v1alpha3/cluster_types.go
internal/apis/core/v1alpha3/machinehealthcheck_types.go
internal/apis/core/v1alpha3/machineset_types.go
internal/apis/core/v1alpha4/cluster_types.go
internal/apis/core/v1alpha4/machinehealthcheck_types.go
internal/apis/core/v1alpha4/machineset_types.go

* Add missing comments
* Rewrite comments to start with serialized names
* of all Kubernetes API resource
but non-API resources are ignored. This is the list of ignored fields.
* RuntimeHooks
* version package
* clusterctl package
```
❯ ./hack/tools/staticchecker/staticchecker ./... 2>&1 | grep -v " Items " | grep -v " Spec " | grep -v " Status " | grep -v test | grep -v upstreamv1beta
/cluster-api/exp/runtime/hooks/api/v1alpha1/topologymutation_variable_types.go:30:2: Cluster should have a comment starting with 'cluster ' (missing)
/cluster-api/exp/runtime/hooks/api/v1alpha1/topologymutation_variable_types.go:31:2: ControlPlane should have a comment starting with 'controlPlane ' (missing)
/cluster-api/exp/runtime/hooks/api/v1alpha1/topologymutation_ …
```

:seedling: Add missing comments with serialized prefix

---

cmd/clusterctl/client/cluster/mover.go

this PR reorders the removing finalizers and sending the delete request. i believe that this also solves https://github.com/kubernetes-sigs/cluster-api/issues/11812 because `DeletionTimestamp` will be non-zero when the cluster controller looks at the object and will ignore re-applying the finalizer. 
Fixes #

:bug: fix: send delete request before removing finalizers

---

cmd/clusterctl/client/repository/repository_gitlab.go
controllers/clustercache/cluster_accessor_client.go
controllers/remote/cluster_cache_healthcheck_test.go
controllers/remote/cluster_cache_tracker.go
controllers/remote/stoppable_cache.go
controlplane/kubeadm/internal/etcd/etcd.go
exp/runtime/internal/controllers/warmup.go
hack/tools/internal/log-push/main.go
hack/tools/internal/tilt-prepare/main.go
internal/controllers/machine/drain/drain.go
internal/runtime/client/client.go
internal/test/envtest/environment.go

This PR replaces `context.WithTimeoutCause` and `context.WithCancelCause` instead of `context.Timeout`  and `context.WithCancel` for better readability of issues when the standard `context deadline exceeded` error is emitted.
Fixes #11280

:seedling:Use context.WithTimeoutCause and context.WithCancelCause for better readability

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/etcd_client_generator.go
controlplane/kubeadm/internal/etcd_client_generator_test.go
controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go
controlplane/kubeadm/internal/workload_cluster_etcd_test.go

KCP has been designed to prefer stability over speed.
This lead e.g. to ask for the same info (member list and alarms) to all the etcd members as an additional safety.
However, over time we discovered that being too much chatty with etcd has some downsides:
- it introduces race conditions, because we are asking the same info to different members at different time and things can change in between two calls
- it amplifies problems when there are connection issues (each call has its own timeout, so a reconcile is stuck for 3 times timeout)
- it adds to the reconciliation time, thus impacting performance at scale
This PR address some of those issues by reading etcd member list and alarms once (instead of reading the same info from each node) in KCP's …

🌱 Call etcd member list and alarms once in KCP's updateManagedEtcdConditions

---

internal/controllers/cluster/cluster_controller.go

Optimizing the log messages.
Fixes #
Nop
/area cluster

🌱 Improve waiting for CP / InfraCluster deletion logs

---

.github/workflows/pr-golangci-lint.yaml
.golangci-kal.yml
.golangci.yml
Makefile
hack/tools/.custom-gcl.yaml

This PR adds [KAL](https://github.com/JoelSpeed/kal) to the linter workflows to lint API conventions.
The linter is a WIP project that I have been working on and the focus of the project is to try and enforce API conventions via a linter, to take off some of the cognitive load of API review.
At the moment, there are 10 sub-linters implemented, each of which I've listed out within the configuration with a description of what they mean.
We should discuss each one and agree upon them, and then, the intention is that we can use this linter for the new v1beta2 types.
The set up here runs KAL separately from the main golangci-lint run, so that the GitHub workflow for linting can continue to use the official GH action, which has some caching and speed …

🌱 Add KAL linter for linting API conventions

---

scripts/ci-e2e-lib.sh

CI currently builds kubernetes from master branch instead of release branches. This fixes the git checkout part.
The checkout done in clonerefs does only checkout tags and a `git fetch --all` does not bring in branches.
This adapts the way of fetching branches to how its done by clonerefs.
xref: https://kubernetes.slack.com/archives/C08AA0FFWG3/p1739449748554519?thread_ts=1738954219.172549&cid=C08AA0FFWG3
Fixes #
/area ci

🌱 scripts: fix checking out k/k release branch

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/objectgraph_test.go
cmd/clusterctl/client/cluster/ownergraph.go
cmd/clusterctl/internal/test/fake_objects.go

A follow-up on #11395 functionality, which integrates `classNamespace` field with `clusterctl move`.
Related to #5673

✨ clusterctl move support for a cross namespace ClusterClass reference

---

test/e2e/node_drain.go
test/framework/deployment_helpers.go

Since implementing #11545 and bumping to that in CAPV the node-drain test started to fail due to multiple reasons.
This changes the test to properly drain machines when also testing with real volume attachments.
It is okay at that point to skip over the unevictable's because that part is already done at that stage.
Also covers now that removing PDB is okay.
Fixes #

🌱 e2e: ensure node-drain with real volume detachments can get deleted without race conditions

---

.golangci-kal.yml

This PR enables checks for Conditions fields in KAL.
It will enforce:
* `Conditions` is the first item in the status object (this could be disabled if we want)
* The appropriate `+listType=map` and `+listMapKey=type` markers are added
* The conditions are optional
* The conditions are `[]metav1.Condition`
Our existing conditions types fail because they are not `[]metav1.Condition`, but are otherwise compliant. An exception has been added for v1beta1 and v1alpha1 APIs to allow the custom CAPI condition type.
Part of #11834

🌱 Enable the conditions rule from KAL

---

controllers/clustercache/cluster_accessor.go
controllers/clustercache/metrics.go

Part of #11272
/area clustercache

🌱 Add clustercache metrics

---

CHANGELOG/v1.8.10.md

Adds release notes for Cluster API [v1.8.10](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.10).
Refs #11656
/area release

🚀 Release v1.8.10

---

CHANGELOG/v1.9.5.md

Adds release notes for Cluster API [v1.9.5](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.9.5).
Refs #11656
/area release

🚀 Release v1.9.5

---

Makefile

Updates the `conversion-gen` tool to [v0.32.2](https://github.com/kubernetes/code-generator/releases/tag/v0.32.2).
Refs #11656: "Bump dependencies"

🌱 Bump conversion-gen to v0.32.2

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/cmd/config_repositories_test.go
docs/book/src/reference/providers.md
docs/book/src/user/quick-start.md

As k0s is moving to CNCF Sandbox we needed to move k0smotron to a new org in GitHub. Hence this PR to change the location. Luckily GH handles redirects so there should be nothing currently broken. :smile:

:seedling: Change k0smotron repo location

---

Makefile

Updates the `kustomize` tool to [v5.6.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.6.0).
Refs #11656: "Bump dependencies"

🌱 Bump kustomize to v5.6.0

---

Tiltfile

Follow-up fix for:
- #11819
We have the following files and the tilt names then clash:
- test/infrastructure/docker/templates/clusterclass-in-memory.yaml
- test/infrastructure/docker/templates/cluster-template-in-memory.yaml
Fixes #
/area devtools

🌱 tilt: use unique names for local_resources and buttons

---

internal/webhooks/test/machinedrainrules_test.go

CEL validation does not produce error messages with consistent order if the validation is on different fields of an object.
See: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11835/pull-cluster-api-test-main/1891887690366849024
This PR changes the tests to only validate one CEL expression at a time.
The reason is probably that properties are stored in a map here and there is no sorting: https://github.com/kubernetes/kubernetes/blob/5420b2fe9a84af57cc24793c8f8ac8821b65f42f/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation.go#L833
Related Slack thread: https://kubernetes.slack.com/archives/C08AA0FFWG3/p1739975552359909 (in …

🐛 Fix MDR unit test

---

test/framework/cluster_proxy.go

The current cluster_proxy behaves differently from what is expected for empty kubeconfig variables in kubectl load rules.
The behaviour forbids the usage of cluster proxy inside the pod in the cluster.
This checks the possibility of in-cluster configuration and keeps the same behaviour, which is not found. 
/area testing

🌱Use inCluster kubeconfig if empty var provided

---

Makefile
docs/book/src/clusterctl/commands/upgrade.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/v1.7/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.7/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1.7/bases/crs.yaml
test/e2e/data/infrastructure-docker/v1.7/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.7/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.7/cluster-template-topology/kustomization.yaml
test/e2e/data/infrastructure-docker/v1.7/cluster-template/kustomization.yaml
test/e2e/data/infrastructure-docker/v1.7/clusterclass-quick-start.yaml
test/e2e/data/shared/v1.7/metadata.yaml

I think it would be nice to align to the Kubernetes n-3 policy and also test n-3 clusterctl upgrades.
(We already keep the test grid for n-3 around if we need emergency patches for that version)
Fixes #

✨ Test n-3 clusterctl upgrade

---

docs/community/20241112-node-bootstrapping.md

Propose a working group for node bootstrapping and cluster provisioning.
The need for this working group originated from an ongoing discussion around separating cluster provisioning and node bootstrapping, as stated in the WG's User Story.
- https://github.com/kubernetes-sigs/cluster-api/issues/5294
- https://github.com/kubernetes-sigs/cluster-api/issues/9157
**CC**
- "@elmiko"
- "@eljohnson92"
- "@johananl"
- "@tormath1"
**Tags**
/area bootstrap
/kind proposal

:book: :sparkles: :people_holding_hands: add proposal for Node Bootstrapping working group

---

.golangci-kal.yml
cmd/clusterctl/api/v1alpha3/metadata_type.go
cmd/clusterctl/client/cluster/upgrader_info.go
cmd/clusterctl/client/repository/repository_github_test.go
cmd/clusterctl/client/repository/repository_versions.go
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml

This PR is part of #11834 .
Enabled integers rule of KAL.
Fixes #
/kind api-change

🌱  Enable integers lint of KAL

---

.golangci-kal.yml

Part of #11834
Fixes #
/area api

🌱 Enable statussubresource linter

---

.golangci-kal.yml

Part of #11834
Fixes #
/area api

🌱  Enable nofloats linter

---

.golangci-kal.yml

🌱 enable maxlength linter

---

.golangci-kal.yml

Part of #11834 
Fixes #
/area api

🌱 Enable nobools linter

---

.golangci-kal.yml

Part of #11834 
Fixes #
/area api

🌱  Enable requiredfields linter

---

api/v1beta1/v1beta2_condition_consts.go
test/infrastructure/docker/api/v1beta1/devmachine_types.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorymachine_backend.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorymachine_controller_test.go

rif https://github.com/kubernetes-sigs/cluster-api/issues/11474

🌱 Add v1beta2 conditions to DevMachines with InMemory backend

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go

If the join token was cleaned up by Kubernetes before CAPI was able to refresh its expiry, CAPI currently fails. This happened in a few cases for us, using machine pools, and required manual intervention to unset the token so that CAPI would recreate it. This change takes care to autoheal the situation by recreating the token.
Seems to be the same issue as https://github.com/kubernetes-sigs/cluster-api/issues/11034.
/area bootstrap

🐛 Recreate bootstrap token if it was cleaned up

---

.golangci-kal.yml
hack/tools/.custom-gcl.yaml

This is part of #11834 
Enabled jsontags linter
Fixes #

🌱  Enable jsontags lint of KAL

---

cmd/clusterctl/client/config/variables_client.go
cmd/clusterctl/client/repository/client.go
cmd/clusterctl/client/repository/repository_gitlab.go
cmd/clusterctl/client/repository/repository_gitlab_test.go

This PR adds support in clusterctl for gitlab instances that require auth.
Fixes # n/a

✨Add support for clusterctl gitlab auth

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/util/configowner_test.go
controlplane/kubeadm/internal/controllers/controller_test.go
internal/controllers/cluster/cluster_controller_test.go

Small follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11520
Fixes #

🌱 Set MachinePool feature gates in tests correctly with testutil

---

.golangci-kal.yml
hack/tools/.custom-gcl.yaml

* Enable commentstart lint of KAL
* Update KAL to the latest version, which https://github.com/JoelSpeed/kal/pull/50 is introduced in
Fixes #11238
As a part of #11834 
/area misc

:seedling: Enable commentstart lint of KAL

---

CONTRIBUTING.md
docs/book/src/reference/versions.md
docs/proposals/20250124-From CAPD(docker) to CAPD(dev) .md

Version support documentation is currently spread between the reference/versions page and contributors guide.
This PR brings all the info about Version support in one place, give a refresh/cleanup to the existing content and also adds documentation for a set of well-established conventions + tribal knowledge like e.g.
- Skip upgrades
- Downgrades
- Cluster API release vs API versions
- Cluster API release vs contract versions
- Supported Cluster API - Cluster API provider version Skew
- Maximum version skew between various Kubernetes components
cc @sbueringer @chrischdi @enxebre @vincepri 

📖 Cleanup and improve version support page

---

docs/book/src/tasks/experimental-features/machineset-preflight-checks.md
internal/controllers/machineset/machineset_preflight.go
internal/controllers/machineset/machineset_preflight_test.go

Extends the `ControlPlaneIsStable` to also consider a pending Control Plane upgrade from topology as blocking.
Note: this checks that `Cluster.spec.topology.version` is equal to `ControlPlane.spec.version`.
Fixes #

✨ machineset: Extend ControlPlaneIsStable preflight check to check for a pending topology based ControlPlane version upgrade

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
exp/topology/desiredstate/desired_state.go
exp/topology/desiredstate/desired_state_test.go
exp/topology/scope/upgradetracker.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
util/predicates/cluster_predicates.go

*High-level description:*
* KCP: block scale-up/scale-down/rollout/remediation if we know there is an upcoming version upgrade pending from the topology
* Topology: Do not block propagating changes anymore when the ControlPlane is in scaling state
Note: This change only affects topology based Clusters.
*More detailed description:*
Changes to KCP:
* Adds a preflight check for KCP for topology based clusters to check if there is an upgrade pending to get propagated down (`Cluster.spec.topology.version != KCP.spec.version`)
* From the perspective of KCP it should be better to roll-forward with the new desired spec instead of first continuing with the old (propably broken) spec of KCP
Changes to the topology controller:
* Relax …

✨ kcp: add preflight check for pending version upgrade from topology

---

hack/observability/grafana/chart/kustomization.yaml
hack/observability/kube-state-metrics/kustomization.yaml
hack/observability/loki/kustomization.yaml
hack/observability/prometheus/kustomization.yaml
hack/observability/tempo/kustomization.yaml

This PR updates dev observability stack to latest versions
Fixes #
https://github.com/kubernetes-sigs/cluster-api/issues/11881

🌱 Update dev observability stack to latest versions

---

test/extension/handlers/lifecycle/handlers.go

Otherwise with the test-extension and multiple tests using it, its impossible to co-relate the logs to a cluster.
Fixes #

🌱 test: add cluster to logger to co-relate requests to clusters in tests

---

.golangci-kal.yml
api/v1beta1/cluster_types.go
api/v1beta1/clusterclass_types.go
api/v1beta1/machinehealthcheck_types.go
bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
exp/addons/api/v1beta1/clusterresourceset_types.go
exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
exp/api/v1beta1/machinepool_types.go

This PR only enables the KAL linter for `kubebuilder:validation:MaxItems`. There will be other PRs for similar markers soon.
I tried to find a good trade-off between setting some reasonable upper bounds and restricting us too much, e.g. the API fields should not limit the number of MDs or Machines we can support per Cluster.
I also tried to pick similar values for similar fields and also to use only a small set of different values to make this all a bit easier.
Part of #11834

⚠️ Add MaxItems markers to API fields

---

cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
exp/topology/scope/upgradetracker.go

Just makes sense that we should consider a control plane that is provisioning not as stable
Fixes #

🌱 Consider IsProvisioning to determine if ControlPlane is stable

---

internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

The Cluster webhook only prevents concurrent minor version upgrades. With this PR we also block concurrent patch upgrades.
The reason is because the Cluster topology controller cannot handle multiple ongoing upgrades correctly.
Fixes #

🐛 ClusterClass: Don't allow concurrent patch upgrades

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
test/e2e/clusterctl_upgrade.go

This is a manual cherry-pick of 
- #11948
Fixes #

[release-1.9] 🐛 ensure kubeadm controller always sets all v1beta2 conditions

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
main.go
test/extension/main.go
test/infrastructure/docker/main.go

🌱 Log version directly on controller startup

---

test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Part of: https://github.com/kubernetes-sigs/cluster-api/issues/11642

🌱 Bump Kubernetes version used for testing to v1.33.0-beta.0

---

bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/api/v1beta1/zz_generated.deepcopy.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
bootstrap/kubeadm/internal/cloudinit/boot_commands.go
bootstrap/kubeadm/internal/cloudinit/cloudinit.go
bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
bootstrap/kubeadm/internal/cloudinit/node.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/ignition/clc/clc_test.go
bootstrap/kubeadm/internal/webhooks/kubeadmconfig_test.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
controlplane/kubeadm/internal/filters_test.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go
docs/book/src/tasks/bootstrap/kubeadm-bootstrap/index.md
internal/apis/bootstrap/kubeadm/v1alpha3/conversion.go
internal/apis/bootstrap/kubeadm/v1alpha3/zz_generated.conversion.go
internal/apis/bootstrap/kubeadm/v1alpha4/conversion.go
internal/apis/bootstrap/kubeadm/v1alpha4/zz_generated.conversion.go

Adds the ability to provide [bootcmd](https://cloudinit.readthedocs.io/en/latest/reference/examples.html#run-commands-on-first-boot) commands to cloud-init via the KubeadmConfig or KubeadmConfigTemplates custom resources. (Same for KubeadmControlPlane)
~~One thing that I know that **does not work** at the time of creating this PR is validating/mutating webhooks for KubeadmConfig and KubeadmConfigTemplates. Some pointers to where to change that would be appreciated.~~
Fixes #

✨ Add bootCommands to cloud-init file generation

---

internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Unsetting a controlPlaneRef or infrastructureRef is unexpected (changing may be okay).
Especially in case of topology based clusters, unsetting controlPlaneRef or infrastructureRef without deleting an old one (which could happen by accident) leads to having two instances of ControlPlane and/or InfraClusters and leading to issues.
Also maybe helps to figure out: 
- #11750
/test help
Fixes #
/area cluster

🌱 cluster: validate that infrastructureRef and controlPlaneRef cannot be unset

---

internal/controllers/cluster/cluster_controller_status.go
util/conditions/v1beta2/aggregate_test.go

- also fixes util test case (with no conditions specified in the test case, the tested function errors out [because there are no sourceObjs](https://github.com/kubernetes-sigs/cluster-api/blob/3cfb41dee1dc16cb89ebf19e63bc3cd2c64afd34/util/conditions/v1beta2/aggregate_test.go#L430)) this doesnt appear to align with the description of the test case (and no `sourceObjs` behavior is already tested [here](https://github.com/kubernetes-sigs/cluster-api/blob/3cfb41dee1dc16cb89ebf19e63bc3cd2c64afd34/util/conditions/v1beta2/aggregate_test.go#L449)
Fixes #11820
/area cluster

:bug: Modify calling agg cluster conditions

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
exp/internal/controllers/machinepool_controller.go
exp/runtime/internal/controllers/extensionconfig_controller.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterresourceset/clusterresourceset_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
test/infrastructure/docker/internal/controllers/backends/docker/dockercluster_backend.go
test/infrastructure/docker/internal/controllers/backends/docker/dockermachine_backend.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorycluster_backend.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorymachine_backend.go
test/infrastructure/docker/internal/controllers/devcluster_controller.go
test/infrastructure/docker/internal/controllers/devmachine_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
util/conditions/v1beta2/patch.go
util/paused/paused.go
util/paused/paused_test.go

If only the generation of an object changed we currently get an additional patch and requeue just to update the ObservedGeneration of the Paused condition.
This PR avoids these additional reconciles
(on the left: this PR, on the right: main)
Fixes #

🐛 Avoid redundant reconciles if only generation of Paused condition changed

---

.trivyignore

According to govulncheck we are not using code that is affected by CVE 2025 22870, so ignoring it
/area security

[release-1.8] 🌱 Ignore CVE 2025 22870

---

.trivyignore

According to govulncheck we are not using code that is affected by CVE 2025 22870, so ignoring it
/area security

[release-1.9] 🌱 Ignore CVE 2025 22870

---

Tiltfile

When running `tilt up` with a Podman container runtime, the following error will occur on image push actions:
```
`Error: trying to reuse blob sha256:3f33e32e55c2aefb268de101401bbb81bc5d25b156631a084de795662b25be04 at destination: pinging container registry localhost:5001: Get "[https://localhost:5001/v2/":](https://localhost:5001/v2/":) http: server gave HTTP response to HTTPS client` `Build Failed: Custom build "sh -c \"set -ex\\npodman build -t $EXPECTED_REF --build-arg binary_name=manager --target tilt bootstrap/kubeadm/.tiltbuild/bin/\\npodman push --format=docker $EXPECTED_REF\"" failed: exit status 125`
```
This is because Podman uses TLS for pushes by default, whereas Docker does not use TLS for pushes.
This PR sets `--tls-verify=false` as …

:seedling: Disable TLS verification for Podman pushes inside of Tilt

---

Makefile
Tiltfile
docs/release/role-handbooks/release-lead/README.md
netlify.toml

> go1.23.7 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, and the reflect, runtime, and syscall packages. See the [Go 1.23.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.7+label%3ACherryPickApproved) on our issue tracker for details.
Also updates the reference PR for bumping the Go version, since #7981 actually misses a couple of references.
N/A

🌱 Bump go to v1.23.7

---

.github/workflows/release.yaml

Modifies the GitHub release.yaml workflow to accomodate the initial v1.10.0 prereleases being cut from the v1.10-release branch, instead of from `main` as usual.
This is a quick hack; I'm open to advice on making it cleaner but it wasn't obvious how we would pass in an additional env var to trigger this behavior, for example.
Refs #11656
/area release

🐛 Use release branch for v1.10 alpha and beta releases

---

test/framework/cluster_helpers.go

Write `clusterctl describe` output also to ginkgowriter in case of errors.
Fixes #

🌱 e2e: write clusterctl describe to ginkgowriter on failure

---

CHANGELOG/v1.9.6.md

- Release notes for v1.9.6
/area release

🚀 Release v1.9.6

---

internal/controllers/cluster/cluster_controller_status.go
internal/controllers/machine/machine_controller_status.go
util/conditions/v1beta2/aggregate.go
util/conditions/v1beta2/merge_strategies.go
util/conditions/v1beta2/summary.go

With this PR the merge operation is explicitly set, so summary with one conditions is not mistaken as an aggregate operation.
/area conditinos

🌱 Set merge operation

---

scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml
test/e2e/data/cni/kindnet/kindnet.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.6/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.7/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.8/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.9/clusterclass-quick-start.yaml
test/e2e/self_hosted.go

E2E improvement to ensure startup of a machine does not fail due to imagepullbackoff of kindnetd.
Also reduces the amount of required image pulls from remote and thus should make it faster and reduce costs for the community a bit.
Fixes #

🌱 e2e: ensure to always preload kindnetd to not hit ImagePullBackoff

---

.github/workflows/pr-md-link-check.yaml

**What this PR does / why we need it**: This is part of the normal release branch creation process. We set the base-branch for the "PR check Markdown links" github action to be itself, namely release-1.10.
/area ci

:seedling: set base branch for release-1.10 markdown link checks

---

Makefile
docs/book/src/developer/core/tilt.md
hack/kind-install-for-capd.sh
hack/kind-install-for-capk.sh
hack/kind-install.sh

This PR adds support for local development using KubeVirt as an alternative to CAPD.
This is useful in cases where CAPD can't be used for whatever reason, with one example being developing Ignition-related features (since Ignition runs in early boot and therefore can't be containerized easily).
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: None
/area devtools

:seedling: Add KubeVirt support to Tilt dev workflow

---

test/framework/bootstrap/kind_provider.go

🐛  Stop overwriting ExtraPortMappings if WithDockerSockMount option is used

---

bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml

A previous PR set minLength for label to 1. This enforced that folks actually had to set label to a non-empty string.
In that context we noticed that label is actually optional, so this PR now makes it optional to avoid forcing everyone to set a non-empty label.
Fixes #

🐛 Make KubeadmConfig FileSystem.Label optional

---

cmd/clusterctl/client/cluster/upgrader.go
cmd/clusterctl/client/cluster/upgrader_test.go
docs/book/src/clusterctl/commands/upgrade.md

We recently improved CAPI version support policies clarifying that we support only n-3 skip upgrades, and we are now using this assumption as a cornerstone to plan API removal activities in https://github.com/kubernetes-sigs/cluster-api/issues/11919 and https://github.com/kubernetes-sigs/cluster-api/issues/11920
However, I noticed that in the clusterctl upgrade doc we were stating something slightly different, so I removed this inconsistency, but then I started thinking about the fact that clusterctl can help users preventing issue.
So I extended a little bit this PR adding a first version of skip upgrade policy check.
For now this check is hardcoded and limited to core CAPI and providers in the core repo; if there is interest we can consider …

🌱 Enforce skip upgrade policy in clusterctl

---

CHANGELOG/v1.10.0-beta.1.md

Release notes for CAPI v1.10.0-beta.1.
Refs #11656
/area release

🚀 Release v1.10.0-beta.1

---

cmd/clusterctl/client/client.go
cmd/clusterctl/client/cluster/client.go
internal/contract/version.go

We will use the contract version types also from our controllers. Also in general it seems more appropriate to have the contract versions in the contract package
Fixes #

🌱 Move contract version & GetCompatibleVersions to contract package

---

.github/workflows/pr-md-link-check.yaml
docs/release/role-handbooks/ci-signal/README.md

- Use `github.base_ref ` instead of `main` or `release-XX` in markdown-link-check
Fixes #12010 
/area release
/kind cleanup

:seedling: Use github.base_ref in markdown-link-check

---

test/extension/main.go

Cleanup in the context of https://github.com/kubernetes-sigs/cluster-api/issues/11947
Fixes #

🌱 Stop registering API types in the runtime extension scheme

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/getting-started.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Bumps cert-manager to the latest [v1.17.1 release](https://github.com/cert-manager/cert-manager/releases/tag/v1.17.1). See also the [v1.17.0 release](https://github.com/cert-manager/cert-manager/releases/tag/v1.17.0) notes for the significant, hopefully non-breaking changes.
N/A, but see #11699 for prior art.

🌱 Bump cert-manager to v1.17.1

---

Makefile
Tiltfile
netlify.toml

> go1.23.8 (released 2025-04-01) includes security fixes to the net/http package, as well as bug fixes to the runtime and the go command. See the [Go 1.23.8 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.8+label%3ACherryPickApproved) on our issue tracker for details.
N/A, but see #11981 for prior art.

🌱 Bump go to v1.23.8

---

controlplane/kubeadm/internal/workload_cluster_etcd.go

The error message refers to "leader," but should refer to "leader candidate."
Fixes #

:seedling: Fix typo in forward etcd leadership error message

---

test/e2e/clusterctl_upgrade.go

🌱 Add retry for SSA requests against Kubernetes < v1.29 in clusterctl upgrade tests

---

CHANGELOG/v1.10.0-rc.0.md

- Release noted for v1.10.0-rc.0
/area release

🚀 Release v1.10.0-rc.0

---

api/v1beta1/cluster_types.go
api/v1beta2/cluster_types.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Due to existing webhook validation, the effective max length was, and continues to be 63 characters. This updates the annotation (and CRD) to reflect this.
This PR came from a conversation in another PR: https://github.com/kubernetes-sigs/cluster-api/pull/12069#issuecomment-2785764984
Fixes #
/area api

:bug: Fix MaxLength of worker topology Name fields

---

api/v1beta1/cluster_types.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Due to existing webhook validation, the max length was effectively 63 characters. This updates the annotation (and CRD) to reflect this actual max length.
Backport of https://github.com/kubernetes-sigs/cluster-api/pull/12072
Fixes #
/area api

[release-1.10] :bug: Fix MaxLength of worker topology Name fields

---

controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go

All fields for these structs are already mutable. This PR allows unsetting the fields too.
Context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1743103086684469
Note: unsetting one of the following paths using SSA might fail with the following error, when SSA apply uses v1beta1 instead of v1beta2, client side apply works just fine:
* `.spec.kubeadmConfigSpec.clusterConfiguration.dns`
* `.spec.kubeadmConfigSpec.clusterConfiguration.etcd.local`
Error example from using ClusterClass and the topology controller hitting this error:
```
- lastTransitionTime: "2025-04-10T12:36:00Z"
message: 'error reconciling the Cluster topology: failed to create patch helper
for KubeadmControlPlane default/in-memory-10996-jvvxg: server side apply dry-run
failed for …
```

🌱 kcp: allow unsetting etcd.local, etcd.external and dns

---

CHANGELOG/v1.10.0-rc.1.md

Release notes for v1.10.0-rc.1
Which issue(s) this PR fixes
/area release

🚀 Release v1.10.0-rc.1

---

test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

keep up with K8s versions
/area ci

🌱 Bump E2E to Kubernetes v1.33.0-rc.1

---

docs/proposals/20240807-in-place-updates.md

Proposal doc for In-place updates written by the In-place updates feature group.
Starting this as a draft to collect early feedback on the main ideas and high level flow. APIs and some other lower level details are left purposefully as TODOs to focus the conversation on the rest of the doc, speed up consensus and avoid rework.
Fixes #9489

📖 Add In-place updates proposal

---

docs/book/src/reference/versions.md

Fix version support matrix after 1.10 release (+ amend wrong EOL dates for old releases)
/cherry-pick release-1.10

📖 Fix version support matrix

---

docs/book/src/reference/versions.md
test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Part of https://github.com/kubernetes-sigs/cluster-api/issues/11642
/area testing

[release-1.10] ✨ Bump Kubernetes in tests to v1.33.0 and claim support for v1.33

---

bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml

cheery-pick of #12107 
Fixes #

[release-1.10] 🐛 Make joinConfiguration.discovery.bootstrapToken.token optional

---

CHANGELOG/v1.10.1.md

- Added release notes of v1.10.1
/area release

🚀 Release v1.10.1

---

docs/release/releases/release-1.11.md

This PR adds the release-1.11 cycle schedule document with preliminary dates and release team members.
Part of: #11656
/area release

📖 Add Cluster API release-1.11 timeline document

---

docs/book/src/user/quick-start.md

- Update clusterctl version to v1.10.x in quick start
Part of: #11656

📖 Update clusterctl version to v1.10.x in quick start

---

.github/ISSUE_TEMPLATE/release_tracking.md
docs/release/role-handbooks/ci-signal/README.md

This PR updates the CI Signal handbook to clarify the timing for dropping support for n-3 release branches during the new release setup process.
Previously, the instructions implied that support for n-3 (e.g., release-1.7 during the v1.10 cycle) should be removed during the setup phase. However, during the v1.10 release, the team aligned on delaying this step until after the new minor release (e.g., v1.10.0) has been officially cut.
This update ensures consistency with current team practices and avoids premature removal of test coverage for supported versions.
Fixes …

📖 ci-signal: clarified timing for dropping n-3 release support in setup steps

---

docs/book/src/reference/versions.md

📖 Update v1.11 support matrix

---

docs/release/role-handbooks/ci-signal/README.md
docs/release/role-handbooks/release-lead/README.md

We were having failed results in our Weekly scans for weeks because both the Release Lead and CI Manager (aka me) didn't realize there was a security scan github action they were supposed to be checking.  
This PR updates the role documentation to explicitly callout and link to this scan as well as the other results that they should be checking regularly.
Fixes #12162
/area release

:book: Update release role docs to be more clear about checking security and ci test results

---

docs/release/role-handbooks/communications/README.md

cluster-api-provider-nested has already been archived. I fixed broken link to it.
Fixes #

📖 Fix broken link to cluster-api-provider-nested

---

docs/book/src/tasks/using-kustomize.md

The `kustomize build .` command needs a space before the dot.

:book: Add missing space to kustomize build command

---

.github/workflows/pr-golangci-lint.yaml
hack/tools/.custom-gcl.yaml

PRs which dependabot opened must fail since the golangci-lint-action requires >= v2.1.0.
So I upgrade golangci-lint version to dependabot works fine.
Fixes #
/area ci

🐛 Upgrade golangci-lint to v2.1.0

---

api/v1beta1/machine_types.go
api/v1beta2/machine_types.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml

Changes the validation for Machine spec's `bootstrap.dataSecretName` to `// +kubebuilder:validation:MinLength=0`. This allows an empty string, which is an existing use case for managed MachinePools.
Fixes #12161
/area bootstrap

🐛 Relax minLength for bootstrap.dataSecretName to 0

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

* Bumps golang.org/x/net to 0.38 to fix CVE-2025-22872
Fixes GO-2025-3563 found in the weekly security scan.
Ref: #12173 is open to decide what to do with the other issues found in the scan.

:seedling: [release-1.10] Bump modules to fix CVEs

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
Makefile
Tiltfile
cmd/clusterctl/cmd/describe_cluster.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
netlify.toml
test/framework/docker_logcollector.go
test/infrastructure/docker/internal/docker/loadbalancer.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/inmemory/pkg/runtime/cache/client.go
test/infrastructure/inmemory/pkg/runtime/cache/hooks.go

* Bumps go to 1.23.8 in Makefile/netlify/Tiltfile
* Bumps govulncheck to 1.1.4 so it works with go 1.23
* cherry picks #11132 
Fixes GO-2025-3563 found in the weekly security scan.
Ref: #12173 is open to decide what to do with the other issues found in the scan.

:seedling: [release-1.8] Bump go for make/build to 1.23 to fix CVEs

---

Makefile
Tiltfile
netlify.toml

* Bumps go to 1.23.8 in Makefile/netlify/Tiltfile
* Bumps govulncheck to 1.1.4 so it works with go 1.23
Fixes GO-2025-3563 found in the weekly security scan.
Ref: #12173 is open to decide what to do with the other issues found in the scan.

:seedling: [release-1.9] Bump go for make/build to 1.23 to fix CVEs

---

.trivyignore

* Add two CVEs to the `.trivyignore` file, as according to govulncheck our code does not call
these vulnerabilities and we don't want to bump the go.mod go version.
* Ignores CVE-2025-22869 and CVE-2025-22872 in the weekly security scan on this branch.
Ref: #12173 is where we decided to ignore these.
/area ci
/area security

:seedling: [release-1.8] Add CVEs to Trivy ignore file

---

.trivyignore

* Add two CVEs to the `.trivyignore` file, as according to govulncheck our code does not call
these vulnerabilities and we don't want to bump the go.mod go version.
* Ignores CVE-2025-22869 and CVE-2025-22872 in the weekly security scan on this branch.
Ref: #12173 is where we decided to ignore these.
/area ci
/area security

:seedling: [release-1.9] Add CVEs to Trivy ignore file

---

cmd/clusterctl/cmd/version_checker.go
cmd/clusterctl/cmd/version_checker_test.go

Adds the full path of the state.yaml file to the error raised when clusterctl can't parse it as YAML.
Fixes #12182

🌱 Add filename to clusterctl error about bad YAML

---

test/infrastructure/kind/mapper.go

Adding the kind 0.27 v1.33.0 image to mapper.go so that e2e tests can use v1.33 as a source cluster when testing v1.10. Resolves some todo comments in main's clusterctl_upgrade_test.go file.

:seedling: [release-1.10] Add 1.33 kind image to mapper.go file

---

cmd/clusterctl/client/repository/components.go

In some specific scenarios, clusterctl components attempt to add missing namespace object causes to appear an error on resource creation. This happens due to namespace object missing `apiVersion`, so `ProviderComponents().Create()` fails to get resource from untyped unstructured object it is represented with.
This PR makes a small fix which prevents this from happening.
Fixes #

🐛 Add missing API version to NS object

---

test/e2e/clusterctl_upgrade_test.go
test/infrastructure/kind/mapper.go

Adding the kind 0.27 v1.33.0 image to mapper.go so that e2e tests can use v1.33 as a source cluster when testing v1.10. 
Bumps the e2e tests for main and v1.10 in clusterctl_upgrade_test.go to use v1.33.0 kubernetes.  This resolves some todo comments.
Depends on #12192 

:seedling: Bump clusterctl_upgrade_test.go main and 1.10 tests to k8s v1.33.0

---

config/crd/kustomization.yaml
config/crd/patches/webhook_in_ipaddressclaims.yaml
config/crd/patches/webhook_in_ipaddresses.yaml
config/default/kustomization.yaml
main.go

Conversion was never active for the IPAM api types IPAddressClaim and IPAddress.
This PR enables them
Fixes #
/area ipam

🐛 ipam: enable conversion in CRDs

---

test/framework/deployment_helpers.go

This makes the framework watch/collect logs from init containers also. Previously, it only collected the normal container logs.
Fixes #12207 
/area testing

🌱 framework: Watch logs from init containers

---

test/framework/bootstrap/kind_util.go

This PR adds a field to override custom node image name for kind cluster creation in e2e framework.
Fixes #

:seedling:Add an option to override custom node image name for kind cluster

---

Tiltfile
docs/book/src/developer/core/tilt.md
docs/book/src/user/quick-start.md
test/framework/bootstrap/kind_provider.go

Part of https://github.com/kubernetes-sigs/cluster-api/issues/11642

✨ Complete bump to Kubernetes v1.33

---

.golangci-kal.yml
.golangci.yml
Makefile
Tiltfile
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
cloudbuild-nightly.yaml
cloudbuild.yaml
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go
exp/internal/controllers/machinepool_controller_phases.go
go.mod
hack/ensure-go.sh
hack/tools/go.mod
internal/controllers/clusterclass/clusterclass_controller_status.go
internal/controllers/clusterresourceset/clusterresourceset_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/conditions.go
internal/util/tree/tree_test.go
netlify.toml
test/go.mod
test/infrastructure/docker/internal/controllers/backends/docker/dockercluster_backend.go
test/infrastructure/docker/internal/controllers/backends/docker/dockermachine_backend.go
util/conditions/deprecated/v1beta1/getter.go
util/conditions/deprecated/v1beta1/merge.go

🌱  Bump Go 1.24

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/getting-started.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Bumps cert-manager to the latest [v1.17.2 release](https://github.com/cert-manager/cert-manager/releases/tag/v1.17.2) 
N/A, but see https://github.com/kubernetes-sigs/cluster-api/pull/12127 for prior art.
cc @mboersma

🌱Bump cert-manager to v1.17.2

---

test/infrastructure/inmemory/pkg/server/mux.go

TestMux is flaky since if the wcl.lister has already been closed, Close return net.ErrClosed.
This flaky depends on the timing of Serve.
So I made these ignore the error if the server is already closed.
Fixes #
/area test
/kind bug

🌱  Ignore net.ErrClosed error when we already closed lister connection.

---

bootstrap/kubeadm/internal/webhooks/kubeadmconfig.go
bootstrap/kubeadm/internal/webhooks/kubeadmconfigtemplate.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
exp/internal/webhooks/machinepool.go
internal/apis/core/v1alpha4/conversion_test.go
internal/webhooks/cluster.go
internal/webhooks/clusterclass.go
internal/webhooks/clusterresourceset_webhook.go
internal/webhooks/machine.go
internal/webhooks/machinedeployment.go
internal/webhooks/machinehealthcheck.go
internal/webhooks/machineset.go
internal/webhooks/runtime/extensionconfig_webhook.go
test/infrastructure/docker/internal/webhooks/devcluster_webhook.go
test/infrastructure/docker/internal/webhooks/devclustertemplate_webhook.go
test/infrastructure/docker/internal/webhooks/devmachine_webhook.go
test/infrastructure/docker/internal/webhooks/devmachinetemplate_webhook.go
test/infrastructure/docker/internal/webhooks/dockercluster_webhook.go
test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go

⚠️ Remove DefaulterRemoveUnknownOrOmitableFields mutating webhook option

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Validation was wrong because it validated the field for being a subdomain, but it is DNS1123Subdomain instead.
xref: partial cherry-pick from #12235
Fixes #

[release-1.10] 🐛 Fix pattern on Cluster classNamespace field

---

docs/book/src/developer/providers/contracts/control-plane.md
docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

Another iteration on v1.11 migration doc
@sbueringer please check documentation for changes introduced by your recent PRs (I hope everything is captured)
@chrischdi @sivchari please check documentation about providers changes based on your experience in CAPV/CAPD

📖 More documentation on v1.11 migration

---

api/core/v1beta1/conversion_test.go
api/core/v1beta1/zz_generated.conversion.go
api/core/v1beta2/cluster_types.go
api/core/v1beta2/zz_generated.deepcopy.go
api/core/v1beta2/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
internal/apis/core/v1alpha4/conversion_test.go
internal/apis/core/v1alpha4/zz_generated.conversion.go

Note: The corresponding functionality was never implemented!
Part of https://github.com/kubernetes-sigs/cluster-api/issues/12123

⚠️ Remove deprecated Cluster.spec.topology.rolloutAfter field

---

api/core/v1beta2/index/cluster.go
docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

Part of https://github.com/kubernetes-sigs/cluster-api/issues/12123

⚠️ Remove deprecated index ByClusterClassName, ClusterByClusterClassClassName and ClusterClassNameField

---

api/addons/v1beta2/clusterresourcesetbinding_types.go
docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

⚠️ Remove deprecated ClusterResourceSetBinding.DeleteBinding method 

---

api/addons/v1beta2/clusterresourcesetbinding_types.go
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml

Makes the clusterName field in CRSB required as documented in the linked issue
This is safe to do because the field has been set by CRS / CRSB controllers since Cluster API v1.4
Fixes #8267
Part of #10852

⚠️ Make clusterName field in ClusterResourceSetBinding required

---

docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md

📖 Fix broken link in book after API move

---

test/framework/cluster_helpers.go

DescribeCluster may fail when doing clusterctl upgrade e2e tests, if target version is not yet deployed.
This also leads to not dumping any yamls for the cluster objects, which might be required to debug the job.
Fixes #

🌱 e2e: only run DescribeCluster if v1beta2 Cluster CRD is there

---

docs/release/role-handbooks/release-lead/README.md

📖 Improve Go bump instructions

---

hack/ensure-kind.sh
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/kind/mapper.go

This PR bumps sigs.k8s.io/kind from v0.28.0 to v0.29.0 along with the associated node images from this release.
The images are based on the data available here:
[http://github.com/kubernetes-sigs/kind/releases/tag/v0.29.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.29.0).
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/12240

 🌱 Bump sigs.k8s.io/kind to v0.29.0

---

docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

📖 Migration doc: Add CRD migrator reminder, add apiGroups to imports

---

hack/verify-import-restrictions.sh
test/extension/.import-restrictions

🌱 Block dependencies to internal packages for the RX implementation

---

CHANGELOG/v1.11.0-alpha.0.md

- Release notes PR for v1.11.0-alpha.0
/area release

🚀 Release v1.11.0-alpha.0

---

internal/controllers/clusterresourceset/clusterresourceset_scope.go

This is small fix which prevents potential situation when `resourceScope` and `error` values could be `nil` simalteniously.
Fixes #

:bug: Fix potential panic if ClusterResourceSetStrategy is not defined or incorrect

---

docs/book/src/developer/providers/contracts/infra-machine.md

this change updates the infra machine contract docs to include a section on how to add the scale from zero fields.
Fixes #12033 

:book: add scale from zero to contract docs

---

controlplane/kubeadm/internal/controllers/controller.go

This small fix removes large number of stack traces of the workload cluster connection error while it's not ready. The logs spams with predictable stack trace on each reconcile loop with full stack trace instead connection is not ready info. 
```bash
2025-04-16T19:50:59+03:00	INFO	Reconcile KubeadmControlPlane	{"controller": "kubeadmcontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "KubeadmControlPlane", "KubeadmControlPlane": {"name":"test-mgmt-control-plane","namespace":"default"}, "namespace": "default", "name": "test-mgmt-control-plane", "reconcileID": "b5b5f0e9-e0a5-46eb-925a-9536fb144e23", "Cluster": {"name":"test-mgmt","namespace":"default"}}
2025-04-16T19:50:59+03:00	INFO	Scaling up control plane …
```

:seedling: Avoid large number of connection error traces in kubeadm controlplane controller

---

docs/book/src/user/quick-start.md

Updates a broken link to CAPZ's "getting started" docs.
Refs #12357

📖 Fix broken link to CAPZ prerequisites

---

test/e2e/self_hosted.go

The `clusterctl move` command verifies that all Machines have NodeRef before starting the move operation, but the self-hosted test wasn't checking this condition before attempting the move. This caused failures when machines were still provisioning (I think).
Fixes #12340

:seedling: Fix e2e test capi-e2e-release-1.8

---

bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

As of today KCP perform a verbatin comparison between current and desired state of machines, and in case of diffs it triggers a rollout.
With this PR we are making the comparison smarter and ignore diff that are not leading to actual changes on machines.
e.g. `files: []` or `files: nill` are different from a golang point of view, but they lead to the same cloud-init file on the machine, so KCP should not rollout in this case.
Please note that this change will also fix infinite rollouts that might be introduced when we drop the DefaulterRemoveUnknownOrOmitableFields from web hooks
Also, note that in a follow up iteration I would like to move tests currently implemented in the cloudinit package near to the new feature in kcp, but this is not in the …

⚠️ KCP tolerates diff not leading to changes on machines

---

internal/controllers/machinedeployment/machinedeployment_sync.go

while setting machine-deployment status, AvailableReplicas field was not deferred to set the actual value, Because of this on each reconciliation the status was updated and it was causing aggressive/repeated reconciliation.
```
I0626 08:53:46.421877      14 machinedeployment_controller.go:234] "Reconcile MachineDeployment" controller="machinedeployment" controllerGroup="cluster.x-k8s.io" controllerKind="MachineDeployment" MachineDeployment="default/ibm-powervs-1-md-0" namespace="default" name="ibm-powervs-1-md-0" reconcileID="6129cb51-fe99-462c-8263-1b1fe509a47a" Cluster="default/ibm-powervs-1"
I0626 08:53:46.521349      14 machinedeployment_controller.go:234] "Reconcile MachineDeployment" controller="machinedeployment" …
```

:bug: Bug fix to set machinedeployment AvailableReplicas

---

exp/internal/controllers/machinepool_controller_noderef.go
internal/controllers/cluster/cluster_controller_status.go
internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/util/tree/tree.go

Audited all fields after https://github.com/kubernetes-sigs/cluster-api/pull/12410
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/12410

🐛 Ensure all pointer status fields are dereferenced correctly

---

api/bootstrap/kubeadm/v1beta2/kubeadm_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

ExternalEtcd.Endpoints is actually a required field, so an empty array should not be valid
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/12402

🌱 KCP: Set MinItems=1 on ExternalEtcd.Endpoints

---

api/core/v1beta1/conversion.go
api/core/v1beta1/conversion_test.go
internal/api/core/v1alpha3/conversion.go
internal/api/core/v1alpha3/conversion_test.go
internal/api/core/v1alpha4/conversion.go
internal/api/core/v1alpha4/conversion_test.go
internal/contract/infrastructure_cluster.go
internal/contract/infrastructure_cluster_test.go

We have to ensure Cluster.status.failureDomains are always alphabetically sorted. We already did this before when reading from an InfraCluster that was still implementing the v1beta1 contract, this PR adds:
* Alphabetic sorting when reading from an InfraCluster that implements the v1beta2 contract
* conversions
Fixes #

🌱 Ensure Cluster.status.failureDomains are alphabetically sorted

---

api/bootstrap/kubeadm/v1beta1/conversion_test.go
api/bootstrap/kubeadm/v1beta1/zz_generated.conversion.go
api/bootstrap/kubeadm/v1beta2/kubeadm_types.go
api/controlplane/kubeadm/v1beta1/conversion_test.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/kubeadm/types/upstream/upstream.go
bootstrap/kubeadm/types/upstreamv1beta3/conversion.go
bootstrap/kubeadm/types/upstreamv1beta3/conversion_test.go
bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.conversion.go
bootstrap/kubeadm/types/upstreamv1beta4/conversion.go
bootstrap/kubeadm/types/upstreamv1beta4/conversion_test.go
bootstrap/kubeadm/types/upstreamv1beta4/zz_generated.conversion.go
bootstrap/kubeadm/types/utils_test.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
controlplane/kubeadm/internal/filters_test.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go
docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
internal/api/bootstrap/kubeadm/v1alpha3/conversion_test.go
internal/api/bootstrap/kubeadm/v1alpha3/zz_generated.conversion.go
internal/api/bootstrap/kubeadm/v1alpha4/conversion_test.go
internal/api/bootstrap/kubeadm/v1alpha4/zz_generated.conversion.go
internal/api/controlplane/kubeadm/v1alpha3/conversion_test.go
internal/api/controlplane/kubeadm/v1alpha4/conversion_test.go

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/12319#issuecomment-3004553197
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10852

✨ Reintroduce KCP/CABPK ClusterConfiguration controlPlaneEndpoint

---

exp/runtime/internal/controllers/extensionconfig_controller_test.go

**What this PR does**
Fixed a flaky test - `TestExtensionReconciler_Reconcile` by adding proper sync to wait for both Paused and Discovery conditions to be set before performing assertions
**why we need it**
The `paused.EnsurePausedCondition()` function triggers multiple reconciliation cycles:
1. Sets `PausedV1Beta2Condition` and returns `requeue=true` (early return)
2. Executes discovery logic and sets `ExtensionConfigDiscoveredV1Beta2Condition`
The test assertion `g.Expect(v1beta2Conditions).To(HaveLen(2))` was executed immediately after the second reconcile call, but before the patch containing the Discovery condition was fully applied to the API server (race condition I think).
So we need to `Eventually` block to resolve this race condition
**Which issue(s) this PR fixes** *(optional, …

🌱 Fix flaky test in extensionconfig_controller_test.go

---

test/infrastructure/docker/internal/controllers/backends/docker/dockercluster_backend.go
test/infrastructure/docker/internal/controllers/backends/docker/dockermachine_backend.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorymachine_backend.go
test/infrastructure/docker/internal/controllers/backends/inmemory/inmemorymachine_controller_test.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

⚠️ Stop using v1beta1 status in CAPD controllers

---

api/core/v1beta2/clusterclass_types.go
api/core/v1beta2/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml

While infrastructure / controlplane are somehwat optional in Cluster, ClusterClass today only works if both of them are specified. We can consider making infrastructure optional once the Cluster topology controller supports it (CP is always mandatory with ClusterClass as it heavily relies on the ControlPlane object)
Part of #10852

🌱 Make infrastructure and controlPlane required in ClusterClass

---

exp/internal/webhooks/machinepool.go
exp/internal/webhooks/machinepool_test.go
internal/webhooks/machinedeployment.go
internal/webhooks/machinedeployment_test.go
internal/webhooks/machineset.go
internal/webhooks/machineset_test.go

Ideally we would want to remove the spec.template.spec.clusterName field. Unforunately we don't have the time to stop embedding the MachineSpec field in MD/MS/MP for v1beta2. For now we'll enforce at least that the values are set consistently
Part of #10852

🌱 Add validation to ensure ClusterName fields are equal in MD/MS/MP

---

test/infrastructure/docker/internal/controllers/backends/docker/dockermachine_backend.go

See the [comment](https://github.com/kubernetes-sigs/cluster-api/pull/12438#discussion_r2184878636)
Fixes #

⚠️ Keep using v1beta1 condition in CAPD Docker backend

---

hack/tools/release/internal/update_providers/provider_issues.go
hack/tools/release/internal/update_providers/provider_issues_test.go
hack/tools/release/notes/main.go
hack/tools/release/notes/main_test.go

Add a validation logic for `make release-notes`
✅ Now Accepts:
- tags/v1.0.0-alpha.1 (alpha pre-release)
- tags/v1.0.0-beta.1 (beta pre-release)
- tags/v1.0.0-rc.1 (release candidate)
❌ Now Rejects:
- v1.0.0-alpha.1 (missing tags/ prefix)
- tags/v1.0.0 (no pre-release identifier)
- tags/v1.0.0-dev.1 (unsupported pre-release type)
- invalid-version (malformed version)
Fixes #12278
/area release

:seedling: Add validation for PREVIOUS_RELEASE_TAG in release-notes-tool

---

Makefile

The target expects the symlink to be called `cluster-api`, but if the parent directory has a different name (e.g. `/home/circleci/project` => `project`), the last command `rm sigs.k8s.io/cluster-api` just fails. Ensure the symlink always has the same name.
/area ci

🌱 Fix `make generate-go-openapi` if parent directory name does not equal `cluster-api`

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_reconciler_test.go
controllers/clustercache/cluster_accessor_test.go
controllers/clustercache/cluster_cache_test.go
controlplane/kubeadm/internal/cluster_test.go
controlplane/kubeadm/internal/controllers/controller_test.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/clusterresourceset/clusterresourceset_controller_test.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/machine_controller_status_test.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go
util/patch/patch_test.go

Follow-up to a recent discussion around these fields
Cluster API today only supports the following cases:
| spec.topology | spec.controlPlaneRef | spec.infrastructureRef | Supported? |
|---------------|----------------------|------------------------|:-----------|
| -             | -                    | -                      | No, No idea how a cluster without Infra/CP would work         |
| -             | -                    | x                      | Yes        |
| -             | x                    | -                      | Yes        |
| -             | x                    | x                      | Yes        |
| x             | - / x                | - / x                  | Yes …

🌱 Add validation for Cluster spec.controlPlaneRef, spec.infrastructureRef and spec.topology

---

controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate_test.go
exp/topology/desiredstate/desired_state_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machineset/machineset_controller.go
internal/webhooks/machinehealthcheck.go
internal/webhooks/machinehealthcheck_test.go
internal/webhooks/machineset.go
internal/webhooks/machineset_test.go

To test our marshalling after recent changes (omitzero etc.) we tried to apply some minimal YAMLs to verify everything works as expected.
While doing that we noticed that we introduce some noise by explicitly defaulting values. Usually in most newer API fields we stopped explicit defaulting to preserve user intent.
This PR drops explicit defaulting from:
* MS deletePolicy
* MHC maxUnhealthy
* KubeadmControlPlaneTemplate rolloutStrategy
In these cases the defaulting doesn't really add additional value as it's not really important to see the default values in the objects:
* MS `deletePolicy Random` doesn't add much
* MHC `maxUnhealthy: 100%` is more confusing than anything else
* …

🌱 Remove explicit defaulting of MS deletePolicy, MHC maxUnhealthy, KCPTemplate rolloutStrategy

---

controlplane/kubeadm/controllers/alias.go
controlplane/kubeadm/internal/cluster.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/etcd_client_generator.go
controlplane/kubeadm/internal/etcd_client_generator_test.go
controlplane/kubeadm/main.go

This is manual backport of #12271 to release-1.9
Fixes #

[release-1.9] :seedling: Add --etcd-client-log-level flag to KCP

---

api/core/v1beta2/cluster_types.go
api/core/v1beta2/clusterclass_types.go
api/core/v1beta2/machine_types.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml

⚠️ Add Minimum=0 marker to all MinReadySeconds fields

---

api/addons/v1beta1/conversion.go
api/addons/v1beta1/conversion_test.go
api/addons/v1beta1/zz_generated.conversion.go
api/addons/v1beta2/clusterresourcesetbinding_types.go
api/addons/v1beta2/zz_generated.deepcopy.go
cmd/clusterctl/internal/test/fake_objects.go
internal/api/addons/v1alpha3/conversion.go
internal/api/addons/v1alpha3/conversion_test.go
internal/api/addons/v1alpha3/zz_generated.conversion.go
internal/api/addons/v1alpha4/conversion.go
internal/api/addons/v1alpha4/conversion_test.go
internal/api/addons/v1alpha4/zz_generated.conversion.go
internal/controllers/clusterresourceset/clusterresourceset_helpers_test.go
test/framework/clusterresourceset_helpers.go
test/framework/clusterresourceset_helpers_test.go

One of the more interesting conversion PRs..
Part of #10852

⚠️ Change ClusterResourceSetBinding Bindings field from []*ResourceSetBinding to []ResourceSetBinding

---

internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_status.go
internal/controllers/clusterclass/clusterclass_controller_status_test.go

The current condition message makes it sound like it's an error to not use the latest apiVersion (which it is not).
So tried to rephrase a bit
Fixes #

🌱 Improve CC RefVersionsUpToDate condition message

---

test/e2e/data/infrastructure-docker/main/cluster-template-ipv6/cluster-ipv6.yaml

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/12465
which broke the IPv6 test
Fixes #

🐛 Fix IPv6 CAPD e2e test

---

test/e2e/autoscaler_test.go
test/e2e/data/autoscaler/autoscaler-to-workload-workload.yaml
test/framework/autoscaler_helpers.go

Additional context https://kubernetes.slack.com/archives/C8TSNPY4T/p1752765473253889
Fixes #

🐛 Bump cluster-autoscaler to v1.33, adjust RBAC, pin apiVersion to v1beta1

---

docs/book/src/developer/providers/contracts/infra-machine.md
docs/proposals/20210310-opt-in-autoscaling-from-zero.md

This PR updates the contract between the cluster-autoscaler Cluster API provider and the infrastructure provider's controllers that reconcile the Infrastructure Machine Template to support platform-aware autoscale from 0 in clusters consisting of nodes heterogeneous in CPU architecture and OS.
With this commit, the infrastructure providers implementing controllers to reconcile the status of their Infrastructure Machine Templates for supporting autoscale from 0 will be able to fill the status.nodeInfo stanza with additional information about the nodes.
The status.nodeInfo stanza has type corev1.NodeSystemInfo to reflect the same content, the rendered nodes' objects would store in their status field.
The cluster-autoscaler can use that information to …

📖 Update autoscaling from zero enhancement proposal with support for platform-aware autoscale from zero

---

Makefile
Tiltfile
netlify.toml

> go1.24.5 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, the runtime, and the go command. See the [Go 1.24.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.5+label%3ACherryPickApproved) on our issue tracker for details.
N/A, but see #12052 for prior art.

🌱 Bump Go to v1.24.5

---

Makefile
Tiltfile
netlify.toml

Manual cherry-pick of #12530.
Updates the Go toolchain to the latest patch release for the 1.23 series.
> go1.23.11 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, and the runtime. See the [Go 1.23.11 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.11+label%3ACherryPickApproved) on our issue tracker for details.
N/A, but see #12509 for prior art.

[release-1.9] 🌱 Bump Go to v1.23.11

---

test/framework/resourceversion_helpers.go

🌱 Print the entire object diff if resource versions are not stable in e2e tests

---

CHANGELOG/v1.11.0-beta.2.md

Release notes for v1.11.0-beta.2
Which issue(s) this PR fixes
Closes #12542
/area release

🚀 Release v1.11.0-beta.2

---

api/bootstrap/kubeadm/v1beta2/kubeadm_types.go
api/bootstrap/kubeadm/v1beta2/kubeadmconfig_types.go
api/bootstrap/kubeadm/v1beta2/kubeadmconfigtemplate_types.go
api/controlplane/kubeadm/v1beta2/kubeadm_control_plane_types.go
api/controlplane/kubeadm/v1beta2/kubeadmcontrolplanetemplate_types.go
api/core/v1beta2/cluster_types.go
api/core/v1beta2/clusterclass_types.go
api/core/v1beta2/machine_types.go
api/core/v1beta2/machinedeployment_types.go
api/core/v1beta2/machinedrainrules_types.go
api/core/v1beta2/machinepool_types.go
api/core/v1beta2/machineset_types.go
api/ipam/v1beta2/ipaddress_types.go
api/ipam/v1beta2/ipaddressclaim_types.go
api/runtime/v1beta2/extensionconfig_types.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml

... this prevents go types to marshal to invalid yaml
part of https://github.com/kubernetes-sigs/cluster-api/issues/10852
/area api

 ⚠️ Add omitzero on struct without zero value

---

test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

⚠️ Update example manifests

---

controlplane/kubeadm/internal/proxy/dial.go
controlplane/kubeadm/internal/workload_cluster.go

This PR adds proper timeout handling to prevent hanging connections when getting API server certificate expiry. The changes include:
- Add 15-second timeout using `context.WithTimeoutCause()` in `GetAPIServerCertificateExpiry()` 
- Handle context timeout in `DialContext()` by configuring HTTP client timeout based on context deadline
- Add early context cancellation checks to fail fast when context is already cancelled
These changes prevent indefinite blocking during certificate expiry checks and improve debugging with descriptive timeout errors.
Fixes #12460
area/provider/control-plane-kubeadm

🐛  Fix timeout handling in GetAPIServerCertificateExpiry and DialContext

---

api/core/v1beta2/cluster_types.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
internal/topology/check/compatibility.go
internal/topology/check/compatibility_test.go
internal/webhooks/test/cluster_test.go

Co-authored-by: Daniel Lipovetsky daniel.lipovetsky@gmail.com
Fixes #12068
Supersedes #12069

🌱 Improve validation of worker topology names in Cluster resource

---

test/e2e/data/kubetest/dualstack.yaml

Skipping Test:
[Feature:IPv6DualStack] Granular Checks: Services Secondary IP Family [LinuxOnly] should function for service endpoints using hostNetwork
This test is being skipped because it consistently fails on EKS clusters.
It also fails in Kind when running on EKS. However, when running on GKE, the same test passes in both Kind and CAPI.
Since we cannot move CAPI jobs to GKE at this time, we are skipping the test in CAPI e2e for now.
Fixes #

🌱 Skipping test that is failing because of infra issues

---

internal/webhooks/test/cluster_test.go

Error message returned by the apiserver looks slightly different on older Kubernetes versions
xref: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-mink8s-main/1951167127310307328
Fixes #

🐛 Fix Test_ValidateCluster unit tests for mink8s

---

exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
exp/internal/controllers/machinepool_controller_scope.go
exp/internal/controllers/machinepool_controller_status.go

This updates the MachinePool reconciliation to set the values for the v1beta2 replica fields in the status section to be consistent with things like the MachineSets.
If a infra machine pool doesn't have "machine pool machines" then we can't realistically set the values for all the fields, so in this case we set the values the same as the replicas.
This change also introduces setting the "UptoDate" condition on the Machines for the first time. It currently only takes the deletion timestamp into account when determining if a machine is outdated. We can iterate on this going forward.
Fixes #12413 …

✨ feat: set new replica fields for machine pools

---

docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

Updates the migration doc according to the changes in:
* https://github.com/kubernetes-sigs/cluster-api/pull/12545
* https://github.com/kubernetes-sigs/cluster-api/pull/12558
* https://github.com/kubernetes-sigs/cluster-api/pull/12560
* https://github.com/kubernetes-sigs/cluster-api/pull/12565
Fixes #

📖 Update v1.10-to-v1.11.md based on recent changes

---

.gitignore
Makefile
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-runtimesdk-v1beta1/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-runtimesdk-v1beta1/kustomization.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk-v1beta1.yaml
test/e2e/quick_start.go
test/e2e/quick_start_test.go
test/extension/handlers/topologymutation/handler.go

🌱 Add quickstart e2e test with v1beta1 with ClusterClass and RuntimeSDK

---

test/framework/cluster_helpers.go

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/12111
Fixes #

🌱 Improve check for Cluster Available condition in e2e tests

---

internal/test/envtest/environment.go
main.go
webhooks/alias.go

We forgot to export this webhook as well
Fixes #

🐛 Export ExtensionConfig webhook

---

Makefile
Tiltfile
netlify.toml

Manual cherry-pick of #12612.
> go1.23.12 (released 2025-08-06) includes security fixes to the database/sql and os/exec packages, as well as bug fixes to the runtime. See the [Go 1.23.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.12+label%3ACherryPickApproved) on our issue tracker for details.
N/A, but see #12531 for prior art.

[release-1.9] 🌱 Bump Go to v1.23.12

---

api/bootstrap/kubeadm/v1beta2/kubeadmconfig_types.go
bootstrap/kubeadm/internal/webhooks/kubeadmconfig.go
bootstrap/kubeadm/internal/webhooks/kubeadmconfig_test.go
bootstrap/kubeadm/internal/webhooks/kubeadmconfigtemplate.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk-v1beta1.yaml

🐛 Fix ControlPlaneComponentHealthCheckSeconds validation in KubeadmConfigSpec.Validate

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
util/apiwarnings/expressions.go
util/apiwarnings/handler.go
util/apiwarnings/handler_test.go

🌱 Reduce noisy logs

---

api/bootstrap/kubeadm/v1beta1/conversion.go
bootstrap/kubeadm/types/upstreamv1beta4/conversion.go

Turns out the fuzz tests do not detect if the structs are not identical. They would only detect it if after the conversion we would try to read the fields.
So let's stop using unsafe for conversion
Fixes #

🌱 Stop using unsafe for EnvVar conversion

---

internal/controllers/machine/machine_controller_status_test.go

I think this might fix: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-main/1954702482470866944
There are some logs like this right before the test failure:
> E0811 00:41:39.620195   35588 controller.go:353] "Reconciler error" err="no matching Node for Machine \"machine-test\" in namespace \"test-reconcile-machine-phases-lr76c\": cannot find node with matching ProviderID" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="test-reconcile-machine-phases-lr76c/machine-test" namespace="test-reconcile-machine-phases-lr76c" name="machine-test" reconcileID="ebe26c28-de85-422b-9f1b-94476f34bb5a"
So I'm wondering if the client cache is …

🐛 Fix flaky TestReconcileMachinePhases unit test

---

internal/controllers/topology/cluster/reconcile_state_test.go

This should fix: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-mink8s-main/1953071454073393152
ClusterClasses cannot be deleted when they are still used. So we should first delete the Cluster, wait until the client observes the Cluster deletion and then delete the ClusterClass in our tests
Fixes #

🐛 Fix flaky TestReconcileState unit test

---

controllers/clustercache/cluster_cache_fake.go
exp/topology/desiredstate/desired_state.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/extension/handlers/topologymutation/handler_integration_test.go

This PR adds input validation for nil checking for Generator function in desired_state.go file.
Fixes # Ref https://github.com/kubernetes-sigs/cluster-api/issues/12614#issuecomment-3201444805

:seedling: Add input validations for desired state generator function

---

docs/book/src/developer/providers/contracts/clusterctl.md

I had an issue with my air gap setup on how to deal with some private gitlab projects and I found `gitlab-access-token` configuration variable [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/variables_client.go#L23) and no documentation related. So here is a small contribution. 

📖  Added documentation about the gitlab-access-token

---

docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md

I noticed that the ExtraArgs in the v1.10 - v1.11 migration docs didn't match with what I had in my old v1beta1 manifests.
The ExtraArgs are map[string]string in v1beta1 but the examples show them as arrays.
Fixes #

📖 Fix extraArgs examples in v1beta2 migration docs

---

internal/topology/check/compatibility.go

🐛 Fix field paths in ClusterClass compatibility validation errors

---

docs/book/src/user/quick-start.md

- Update clusterctl version to v1.11.x in quick start
/cherry-pick release-1.11

📖 Update clusterctl version to v1.11.x in quick start

---

test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/devmachine_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

🐛 CAPD: Remove finalizers during deletion if ownerRef was never set

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/12677
Fixes #

[release-1.10] 🌱 Bump github.com/go-viper/mapstructure/v2 to fix CVE

---

bootstrap/util/configowner.go

🐛 Always use latest apiVersion when getting owner of KubeadmConfig in CABPK

---

exp/topology/desiredstate/desired_state.go
internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/runtime/client/fake/fake_client.go

Since CAPI v1.11.0 the patch engine always sets the holder field path in a GeneratePatchesRequest for the CP InfraMachineTemplate to `spec.machineTemplate.spec.infrastructureRef`.
This broke existing Runtime Extension implementations that were checking for `spec.machineTemplate.infrastructureRef` (the v1beta1 path).
With this PR we are now setting the holder field path depending on which contract the corresponding control plane object implements.
Examples:
* KCP v1beta1 implements the v1beta1 contract so fieldPath will be set to `spec.machineTemplate.infrastructureRef`
* KCP v1beta2 implements the v1beta2 contract so fieldPath will be set to `spec.machineTemplate.spec.infrastructureRef`
This way …

🐛 Ensure holder field path in GeneratePatchRequest is set based on contract

---

exp/topology/desiredstate/desired_state.go
internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/runtime/client/fake/fake_client.go

[release-1.11] 🐛 Ensure holder field path in GeneratePatchRequest is set based on contract

---

docs/book/src/reference/versions.md
test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

✨ Bump Kubernetes in tests to v1.34.0 and claim support for v1.34

---

docs/release/releases/release-1.12.md

This PR adds the release-1.12 cycle schedule document with preliminary dates.
/area release

📖 Add Cluster API release-1.12 timeline document

---

test/e2e/data/autoscaler/autoscaler-to-workload-workload.yaml

✨ Bump autoscaler to a9cb59fdd

---

bootstrap/kubeadm/types/utils.go
exp/topology/desiredstate/desired_state.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/reconcile_state.go

Before this PR the topology controller was adding the conversion-data annotation to the Cluster object.
This happened because:
* we are calling `v1beta1Cluster.ConvertFrom(cluster)` in a few code paths
* ConvertFrom has a side effect that it adds the conversion annotation
* ideally this would only be added on the v1beta1 Cluster, but the generated conversion code is using `out.ObjectMeta = in.ObjectMeta` for conversion. So both objects are updated
Fixes #

🐛 Stop adding conversion-data annotation to Cluster object

---

Makefile
Tiltfile
docs/release/role-handbooks/release-lead/README.md
netlify.toml

> go1.24.7 (released 2025-09-xx) includes security fixes and bug fixes across standard library packages and the runtime. See the [[Go 1.24.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.7)](https://github.com/golang/go/issues?q=milestone%3AGo1.24.7) on our issue tracker for details.
**Which issue(s) this PR fixes:**
N/A, but see #12509 for prior art.

🌱 Bump go to v1.24.7

---

.golangci-kal.yml
hack/tools/.custom-gcl.yaml

🌱 Bump KAL & add nodurations linter

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go
cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go
controlplane/kubeadm/internal/controllers/status.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/clusterresourceset/clusterresourceset_controller.go
internal/controllers/machine/drain/drain.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machinepool/machinepool_controller_noderef.go
internal/controllers/machinepool/machinepool_controller_phases.go

Go has errors package to use Is() and As(). These API can check recursively if the err is one we want.
So I use errors package to check recursively.
Fixes #

🌱  Use errors package of Go

---

.golangci.yml

This PR ensures that no FIXME comments are merged. I think we should use FIXME's only locally and TODO otherwise
Fixes #

🌱 Block FIXME comments

---

config/metrics/crd-clusterrole.yaml
config/metrics/crd-metrics-config.yaml
config/metrics/kustomization.yaml
hack/observability/grafana/dashboards/cluster-api-state.json

Updates the metrics configuration to use the v1beta2 api version instead of v1beta1.
Small adjustments to metrics:
- Added ClusterClass classref namespace metric (`capi_clusterclass_spec_topology_classref_namespace`)
- renamed `capi_clusterclass_spec_topology_class` to `capi_clusterclass_spec_topology_classref_name`
- dropped metrics related to .Status.UnavailableReplicas (deprecated)
- dropped metrics related to .Status.UpdatedReplicas
- Added metrics for .Status.UpToDateReplicas
- MHC: removed label `maxUnhealthy`, added `remediation_triggerif_unhealthylessthanorequalto` and `remediation_triggerif_unhealthyrange`
Adjustments to dashboards:
* For KCP and MD: use uptodate metric instead of updated
**Which issue(s) this PR fixes** *(optional, in …

🌱 update metrics configuration to v1beta2

---

docs/book/src/tasks/experimental-features/machine-pools.md

Adds a markdown table of known implementors of `MachinePool`. 
This was a task we talked about at the first MP working group meeting. I visited all listed provider repos and grepped for `MachinePool`. (I hear GCP has an implementation in progress as well.)
Refs #9005

📖 List provider implementations of MachinePools

---

controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

Part of https://github.com/kubernetes-sigs/cluster-api/issues/12291

🌱 Simplify KCP matchesKubeadmConfig

---

internal/controllers/machinedeployment/machinedeployment_rollout_sequence_test.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinedeployment/mdutil/util_test.go
internal/controllers/machineset/machineset_controller.go

This PR refactor MachineTemplateUpToDate to surface info that will be require when we are going to introduce the "canUpgrade in-place" check.
On top of this changes, also the FindNewMachineSet /  FindOldMachineSets func have been refactored to allow an easier consumption of the output of MachineTemplateUpToDate, as well as the integration in the same set of NotUpToDateResults of the output of the decision about rolloutAfter.
(we also agreed to proceed with small incremental changes given the complexity of this part of the codebase)
Part of #12291

🌱 Refactor MachineTemplateUpToDate

---

controllers/clustercache/cluster_accessor.go
controllers/clustercache/cluster_accessor_client.go
controllers/clustercache/cluster_accessor_test.go
controllers/clustercache/cluster_cache.go
controllers/clustercache/cluster_cache_fake.go

Adds GetUncachedClient method to the ClusterCache interface to support live (uncached) API calls to workload clusters. This helps reduce memory usage when you want to cache only a few types instead of having to exclude most types via DisableFor. 
The uncached client is created alongside the cached one during connection setup and follows the same lifecycle (connect/disconnect).
Note: This introduces a breaking change to any existing implementations that are directly using ClusterCache.
Fixes #12784 
/area controllers
/area clustercache

✨ ClusterCache: Add GetUncachedClient()

---

internal/controllers/machine/machine_controller_status_test.go
internal/test/envtest/environment.go

**What this PR does / why we need it**: Mitigates flaking test
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/12785 
This adds CreateAndWait on machine creation in the TestReconcileMachinePhases envtests. Also adds a DeleteAndWait function for the test that runs the delete to check machine phase.

:seedling: Fix TestReconcileMachinePhases flake

---

internal/controllers/machine/machine_controller_status_test.go
internal/test/envtest/environment.go

**What this PR does / why we need it**: reduce flake in envtest test
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/12785 
use APIReader with helper Get function. My comment in the issue explains what I'm thinking is going. For some of the flake you can see the logs reconcile so the status must be set to i.e. `Pending`. Instead the phase is empty and reads as `Unknown`. Completed reconciliations would set the status and the logs show those completing so the cache must be stale on the check where we `Get` the object and validate the status. This adds helper function and uses it for validation where it queries directly …

:seedling: TestReconcileMachinePhases: use apireader to directly talk to apiserver
