kubernetes-sigs/cluster-api

test/helpers/kind/setup.go
Fixes #2396 
Makes tests less dependent on the specific version of kind.
=> test: Set kindest image to 1.16 for CRDv1 compat

api/v1alpha3/machinedeployment_webhook.go, api/v1alpha3/machinedeployment_webhook_test.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go
Moved MachineDeployment Cluster Label Name to webhook as per #2302 
**Which issue(s) this PR fixes**  :
Fixes #2302
=> ✨ Moved MachineDeployment Cluster Label Name to webhook

README.md
Updates our community blurb based on feedback recieved.
=> :book: Update our community blurb

util/util.go, util/util_test.go
Updates our utilities to make sure we're properly updating the references instead of duplicating them if they actually refer to the same object with different versions.
/assign @ncdc @detiber
=> :bug: util.EnsureOwnerRef should ignore version when comparing objects

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
This PR adds a condition for Kubeadm Control Plane Controller to not fail if getting a timeout from the load-balancer in case it is self-hosted in the target cluster (and does not answer while the first node is not up
Fixes #2408
=> 🐛 KCP: expect timeout from target cluster load-balancer

test/infrastructure/docker/Makefile, test/infrastructure/docker/e2e/docker_test.go
By default, the e2e tests will run the basic create test that takes ~300s (5m) on my laptop. However, by modifying the FOCUS var is possible to run the full test (upgrades and any other actions beyond create) that takes closer to 12 minutes on my laptop and is not suitable (my opinion) for every PR.
This can merge before the upgrade PR merges as there is no change in existing default behavior.
=> 🏃 Adds an upgrade test

bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, bootstrap/util/configowner.go
Signed-off-by: Juan-Lee Pang <jpang@microsoft.com>
Adds MachinePool as a valid boostrap provider config owner. Without this, a machine pool's kubeadm boostrap config will never be generated.
Fixes #2405
=> 🐛 Recognize MachinePool as a bootstrap config owner

api/v1alpha3/machineset_types.go, config/crd/bases/cluster.x-k8s.io_machinesets.yaml
Add printer columns(Replicas, Available, Ready) to machinesets, similar to what we have for machinedeployments
Closes https://github.com/kubernetes-sigs/cluster-api/issues/2415
=> ✨Add printer colums to machinesets

test/infrastructure/docker/Makefile, test/infrastructure/docker/e2e/docker_test.go
Forgot to escape the regex. If we don't have this, a regex like 'Basic|Full' will fail.
=> 🐛 Fix makefile escaping for capd-e2e focus

test/framework/dump_resources.go, test/infrastructure/docker/e2e/docker_suite_test.go
This PR dumps actual state of `cluster-api` resources to artifacts output. The main benefit of this is the ability to look at resources at the moment of fail. To get more detailed information, look at the issue below.
I'm not sure if this the best solution for the problem, hopefully, PR will start a conversation on it. Happy to see what others think!
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2231
=> ✨ [test-framework] Dump resources YAML to artifact output

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/config/rbac/role.yaml, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/failure_domain.go, controlplane/kubeadm/internal/failure_domain_test.go, controlplane/kubeadm/internal/machine_collection.go, controlplane/kubeadm/internal/machine_filters_test.go, go.mod, go.sum
Implements the functionality for the KubeadmControlPlane upgrades
Fixes #2242 
Builds on #2379 #2380 #2381 #2382 #2383
=> :sparkles: Implement KubeadmControlPlane upgrade functionality

OWNERS, OWNERS_ALIASES
@CecileRobertMichon expressed interested in getting more involved in Cluster API PR reviews. Let's make that happen :)
=> :running: Add Cecile to reviewer list

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go
This PR updates the kubernetes version found in the kubeadm configuration config map as well as refactors some of the kubelet upgrading to keep it outside of the reconciler
This PR intentionally includes code that is easily refactored. I do not intend to consolidate repeated code in this PR and will save that for an exercise for later.
To run a test locally with this PR, first check it out, then run
```
export FOCUS='Basic|Full` # I know, I know...but it's fine for now
make test-capd-e2e-images
```
Fixes #2448 
Fixes #2427 
Fixes #2429 
This is the …
=> 🏃 Update kubeadm config on upgrade

controlplane/kubeadm/internal/cluster.go
Before:
```
E0225 23:47:06.883670       8 kubeadm_control_plane_controller.go:577] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before adding an additional control plane machine" "error"="there are 3 control plane nodes, but 0 etcd members" "cluster"="test" "kubeadmControlPlane"="test" "namespace"="test"
```
After:
```
E0226 01:48:29.726200     166 kubeadm_control_plane_controller.go:577] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before adding an additional control plane machine" "error"="[could not check etcd member health, node \"ip-10-0-0-3.ec2.internal\": failed to create etcd client: unable to create etcd client: context deadline exceeded, node …
```
=> :bug: Report all KCP healthcheck errors

api/v1alpha3/machine_webhook.go, api/v1alpha3/machine_webhook_test.go, api/v1alpha3/machinedeployment_webhook.go, api/v1alpha3/machinedeployment_webhook_test.go, api/v1alpha3/machinepool_webhook.go, api/v1alpha3/machinepool_webhook_test.go, api/v1alpha3/machineset_webhook.go, api/v1alpha3/machineset_webhook_test.go
This PR adds a validation webhook check to Machine, MachineDeployment, MachineSet, and MachinePool types to make Spec.ClusterName field immutable.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/2439
=> 🏃Add validation webhook check to make Spec.ClusterName immutable

controlplane/kubeadm/internal/cluster.go
I believe this was test code that made it through the review in order to test the recent changes to the error handling. However, it prevents the health check from ever passing if there are 1 or more control plane nodes (aka always)
Fixes #2467
=> 🐛   Allow kcp etcd health check to pass

api/v1alpha3/machine_types.go, config/crd/bases/cluster.x-k8s.io_machines.yaml, controllers/machine_controller_phases.go, controllers/machine_controller_phases_test.go
Update the `LastUpdated` field in the `Machine` status whenever the `Phase` is changed from one state to another
Fixes #2452
=>  🐛 Set LastUpdated on Machine status when Phase changes

controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/etcd_client_generator.go
This starts improving the cluster abstraction. I believe this cleans up the constant client cert generation by only generating one bundle and reusing that. 
This is related to the various error issues we have open. This should start to refactor some code to make it easier to test.
Related to #2454 and #2455
=> 🏃 refactor the etcd client in the cluster object

controlplane/kubeadm/internal/cluster_test.go
This codifies (in tests) the expectations we make around meta health checks.
Here are a list of checks included in this PR:
- When a machine's node was not checked for health. An absence of health from a node is bad.
- The health check returns an error not related to a node's health. For example, the health check cannot connect to the api server to get a list of nodes.
- More nodes than machines were checked. This means there are control plane nodes not managed by cluster api and that is considered unhealthy.
- A machine has a nil node reference. This means the control plane hasn't actually been created or is in the process of being deleted. The control plane cannot be healthy.
cc @dlipovetsky If i'm missing anything you can think of, please let …
=> 🏃 Add unit tests for health check function

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go
The goal here is to unblock folks I know are going to be writing tests soon and without this refactor, it's really hard to write specific tests.
This PR continues improving the abstraction of cluster/workload cluster as well as improving the ability to unit test very specific pieces of code instead of using a large pseudo integration test that is fragile and hard to read and hard to write. They can be replaced by more specific unit tests of the individual pieces along with unit tests of the reconciler. We can lean on the e2e tests to ensure integration is working.
The biggest change is that the workload cluster now stands on its own allowing the reconciler to directly talk to the workload cluster and …
=> 🏃 Refactor workload cluster out of cluster

cmd/clusterctl/pkg/client/cluster/upgrader.go, cmd/clusterctl/pkg/client/cluster/upgrader_info.go, cmd/clusterctl/pkg/client/cluster/upgrader_info_test.go, cmd/clusterctl/pkg/client/cluster/upgrader_test.go
All the providers in a management group are expected to support the same API Version of Cluster API (contract).
This PR makes upgrade plan fully compatible with the above expectation by dropping incomplete plans - plan where not all the providers have a target version -  when changing the contract version. So
v1alpha3 --> v1alpha3
Incomplete plans are supported (some provider will be updated, some other are already up to date)
v1alpha3 --> v1alpha4
Incomplete plans are dropped because all the provider are required to change the contract at the same time
If instead, the plan is complete (there is a target
Rif #1729
=> 🐛clusterctl: drop incomplete plans if contract change

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Instead of assigning r.managementCluster every time Reconcile() is
invoked, do it once, in SetupWithManager.
Fixes #
=> :running: KCP: set managementCluster in SetupWithManager

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
This PR simplifies the reconciler by removing core logic and putting that core logic on the workload cluster. This also adds tests to the two functions that were moved.
=> 🏃 Refactors config reconciliation to the workload cluster and tests it

api/v1alpha3/common_types.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
This PR adds a type to the secret created by the kubeadm bootstrap controller.
Fixes #2440
=> ✨Bootstrap secret type

OWNERS_ALIASES, bootstrap/kubeadm/OWNERS, cmd/clusterctl/OWNERS, docs/book/OWNERS, test/infrastructure/docker/OWNERS
- Moves all groups to be in OWNER_ALIASES
- Creates a group dedicated for `clusterctl` with maintainers and reviewers
=> :running: Refactor OWNERS files throughout the repo

controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go
- Don't retry requests for all nodes. Use requeue to retry.
- Don't remove the etcd member if cluster has fewer than 2 control plane nodes.
- Add unit tests.
Addresses feedback for #2435
Fixes #2474 
/assign @detiber @chuckha
=> :running: kubeadmcontrolplane: clean up removeMemberForNode

controlplane/kubeadm/internal/hash/hash.go
Updates the hashing used by KubeadmControlPlane to include changes to Spec.KubeadmConfigSpec, so that we can make at least a subset of that field mutable in the future.
=> :running: Update KCP hash to include KubeadmConfigSpec

Makefile
Signed-off-by: SataQiu <1527062125@qq.com>
Fix the bug that clusterctl version command does not show correct output
Test result:
```
clusterctl version: &version.Info{Major:"0", Minor:"2", GitVersion:"v0.2.5-1108-91703dd55221c7", GitCommit:"91703dd55221c76e151783255133526f751840ba", GitTreeState:"clean", BuildDate:"2020-03-02T05:23:39Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
```
Fixes #2449
=> 🐛 Fix the bug that clusterctl version command does not show correct output

.golangci.yml
This PR disables the [Interfacer linter](https://github.com/mvdan/interfacer) which has been deprecated and is currently blocking #2494 from merging
/cc @ncdc
=> 🏃Disable Interfacer Linter

api/v1alpha2/conversion.go, util/conversion/conversion.go, util/conversion/conversion_test.go
This PR excludes all metadata from annotations when converting objects from hub(v1a3) to v1a2.
Fixes #2441
=> ✨Excluded metadata in annotation during conversion

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/machine_controller_test.go, controllers/machinedeployment_sync.go, controllers/machinepool_controller_noderef.go, controllers/machinepool_controller_test.go, controllers/machineset_controller_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go, test/framework/failure_domains.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/e2e/docker_test.go, util/kubeconfig/kubeconfig.go, util/secret/certificates.go
This PR replaces types.NamespacedName with client.ObjectKey or utils.ObjectKey whenever controller-runtime is imported.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2459
=> :running: Use controller-runtime's client ObjectKey instead of types.NamespacedName

test/infrastructure/docker/config/manager/manager.yaml, test/infrastructure/docker/main.go
Add liveness/readiness probes similar did here https://github.com/kubernetes-sigs/cluster-api/pull/2156
- also change a bit the code to be similar that is made in capi
related https://github.com/kubernetes-sigs/cluster-api/issues/1855
/cc @vincepri
=> ✨manager/docker: add liveness/readiness probes

docs/book/src/SUMMARY.md, docs/book/src/clusterctl/commands/init.md, docs/book/src/tasks/upgrade.md
Documents how to upgrade from v1alpha2 to v1alpha3. 
Fixes #1550
=>  📖 Upgrade v1alpha2 to v1alpha3 documentation

cmd/clusterctl/client/cluster/proxy.go
This PR improves error messages for most common problems when connecting to kubernetes:
Missing kubeconfig now returns:
```
invalid kubeconfig file; clusterctl requires a valid kubeconfig file to connect to the management cluster: no configuration has been provided
```
(the last bit is the error from `k8s.io/client-go/tools/clientcmd`)
Existing kubeconfig, but connection errors:
```
failed to connect to the management cluster: Get https://127.0.0.1:32784/api?timeout=32s: dial tcp 127.0.0.1:32784: connect: connection refused
```
(the last bit is the error from controller runtime client)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2515
/assign @wfernandes @detiber
=> 🐛 clusterctl: improve connection error messages

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/workload_cluster.go, test/framework/control_plane.go, test/infrastructure/docker/e2e/docker_test.go
This PR aligns the KCP `Initialized` field with the comment on the field in the API type as well as sets the `Ready` status when it is appropriate to set. 
Fixes #2480 
~I'm holding this because I might have to make changes to the capd e2es now that we're actually setting Ready based on NodeReady which requires CNI to exist on the cluster. CAPD may now how to install a CNI to pass which it really should do anyway in order to scale machine deployments.~
In general, my experience with the tests for the reconciler are that we are testing many things …
=> 🏃 Wire up kubeadm control plane Ready status

test/infrastructure/docker/cloudinit/kindadapter.go, test/infrastructure/docker/cloudinit/kindadapter_test.go, test/infrastructure/docker/cloudinit/runcmd.go, test/infrastructure/docker/cloudinit/runcmd_test.go, test/infrastructure/docker/cloudinit/unknown.go, test/infrastructure/docker/cloudinit/unknown_test.go, test/infrastructure/docker/cloudinit/writefiles.go, test/infrastructure/docker/cloudinit/writefiles_test.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/e2e/local-e2e.conf
This removes the cloud init package from running commands and only generating
the commands equivalent to a cloud init configuration file.
This PR reduces the scope of the cloud init module in CAPD in order to take advantage of the new CommandContext available in `kind` (this will come in a following PR since it's fairly invasive).
Related to reducing flakes in capd
=> 🏃 cloud init package has reduced responsibilities

docs/book/src/roadmap.md
Propose AWS spot instances support https://github.com/kubernetes-sigs/cluster-api/issues/1876 for the roadmap
Fixes #
=> Propose spot instances support for roadmap

cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/components.go, cmd/clusterctl/client/cluster/inventory.go, cmd/clusterctl/client/cluster/mover.go
This PR makes create objects more resilient by:
- Adding retry loops for each operation
- Ensuring every retry loop/wait loop gets a new client at each iteration
The same improvement was implemented for create Inventory CRD objects, create cert-manager objects, create provider objects.
/assign @vincepri @ncdc
=>  🐛clusterctl: add retries on create objects

cmd/clusterctl/client/config/providers_client.go, docs/book/src/clusterctl/overview.md, docs/book/src/reference/providers.md
Metal3 Provider repository was renamed from cluster-api-provider-baremetal to
cluster-api-provider-metal3. This PR updates those references.
=> 🏃 Modify Metal3 provider repository

cmd/clusterctl/cmd/move.go
:bug: Update error message for clusterctl move when --to-kubeconfig isn't specified to align with command requirements.
Fixes #
=> 🐛 Update error message for clusterctl move

api/v1alpha3/machinehealthcheck_webhook.go, api/v1alpha3/machinehealthcheck_webhook_test.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_targets.go, controllers/machinehealthcheck_targets_test.go
This PR adds the final part of the MHC logic which is responsible to short circuiting remediation if the `maxUnhealthy` field would be violated by remediating the node and otherwise, remediating the node.  
Machine health check remediation logic from #1990
=> ✨ Add MHC remediation logic

controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
This is in order to help #2525 test with way less pain and abstraction layer violations. 
The big changes here are:
1) Define the management cluster interface -> this work is incomplete as the reconciler still directly interfaces with the client, but this work can be done in future PRs
2) Define the workload cluster interface -> This allows us to more closely unit test the reconciler and control the behavior of various sub-systems.
3) Inlining of several functions as they were only single use, not complex, not independently tested and short
4) Refactored the `Cluster` struct to a more useful name, `Workload` and updated receivers.
/cc @alexander-demichev @dlipovetsky 
=> 🏃 continue improving management/workload abstraction

Makefile, cmd/clusterctl/test/e2e/go.mod
This sneaks in way too often, let's add a validation check for it
=> :running: Add a validation check in place against client-go@incompatible

docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
- Add instructions in docs for providers to upgrade to CRD v1
Fixes #2546
=> 📖Add instructions for providers to upgrade to CRD v1

controlplane/kubeadm/internal/workload_cluster.go
This PR adds a health check that looks for NoExecute taint on control plane nodes.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2469
=> 🏃Add NoExecute taint check for KubeadmControlPlane nodes

cmd/clusterctl/client/cluster/cert_manager.go
as per https://github.com/kubernetes-sigs/cluster-api/issues/2535#issuecomment-595411092, make the wait loop for cert-manager in clusterctl resilient to connection glitch
/assign @ncdc 
/assing @vincepri
=> 🐛clusterctl: fix wait cert-manager

test/infrastructure/docker/e2e/docker_test.go
Calico have removed the `v3.12` hosted version of their docs ([the link 404s](https://docs.projectcalico.org/v3.12/manifests/calico.yaml)) and now the [CAPD tests are failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/2549/pull-cluster-api-capd-e2e/1235856630076149760) because the file they're downloading is not valid YAML
I've quickly verified and calico currently seem to host the calico manifest at three locations: 
- `manifests/calico.yaml` (this matches the current latest release)
- `v3.13/manifests/calico.yaml`
- `master/manifests/calico.yaml`
If we use a specific release, it's likely this test is going to break regularly as they create new releases, I propose we use the naked …
=> 🐛 Fix CAPD Calico manifest URL

config/crd/kustomization.yaml, config/crd/patches/cainjection_in_machinehealthchecks.yaml, config/crd/patches/webhook_in_machinehealthchecks.yaml, config/kustomization.yaml, config/rbac/role.yaml, controllers/machinehealthcheck_controller.go, main.go
This PR registers the controller and webhook for MachineHealthCheck controller and adds the required RBAC. This makes the controller live within peoples deployments!
All of the business logic is merged so this is the final step to making MHC usable!
Part of #1990
=> ✨ Register MachineHealthCheck controller and add RBAC

api/v1alpha3/machine_webhook.go, api/v1alpha3/machine_webhook_test.go, api/v1alpha3/machinedeployment_webhook.go, api/v1alpha3/machinedeployment_webhook_test.go, api/v1alpha3/machinehealthcheck_webhook.go, api/v1alpha3/machinehealthcheck_webhook_test.go, api/v1alpha3/machineset_webhook.go, api/v1alpha3/machineset_webhook_test.go, exp/api/v1alpha3/machinepool_webhook.go, exp/api/v1alpha3/machinepool_webhook_test.go
=> ✨ Defaulting webhooks should always set label from Spec.ClusterName

cmd/clusterctl/client/config/reader_viper.go
This PR make clusterctl to consider the empty env variables (because empty is different than unset !)
xref https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/800
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2497
/assign @randomvariable 
=> 🐛clusterctl: allow empty variables

.dockerignore, .gitignore, scripts/ci-capd-e2e.sh, test/infrastructure/docker/.gitignore, test/infrastructure/docker/api/v1alpha3/dockermachine_types.go, test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml, test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml, test/infrastructure/docker/controllers/dockermachine_controller.go
=> :bug: Allow noderef setting to be re-entrant in CAPD

test/infrastructure/docker/api/v1alpha3/dockermachine_types.go, test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
This PR changes the ready field to be optional. This cause an error log to be produced that was unnecessary.
/cc @randomvariable
=> 🏃 capd: Make ready an optional field

controllers/external/tracker.go
This is an effort to avoid logging sensitive information when the controller starts watching external resources.
If we pass the whole object, the controller-runtime object will log it out including all fields also within spec. This PR uses an unstructured object with only GVK set to issue the watch instead.
/assign @ncdc
=> :running: Pass a stripped down object to controller.Watch

cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/config/client.go, cmd/clusterctl/client/config/imagemeta_client.go, cmd/clusterctl/client/config/imagemeta_client_test.go, cmd/clusterctl/internal/test/fake_reader.go, cmd/clusterctl/internal/util/objs.go, cmd/clusterctl/internal/util/objs_test.go, cmd/clusterctl/test/e2e/go.sum, go.mod, go.sum, test/infrastructure/docker/go.sum
The cert-manager manifest is embedded in clusterctl so it cannot be easily changed like e.g. provider manifests. This PR adds configurations to allow to set imageRepository/ImageTag (similar to ImageMeta for etcd/CoreDns in kubeadm)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2555
/assing  @vincepri @ncdc
=> ✨clusterctl: allow cert-manager image overrides

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, go.mod
This PR loosens the web hook restriction allowing for changes to the etcd field but disallowing any other ClusterConfiguation field change. 
Allows setting the etcd local image metadata after creation
Allows unsetting the etcd local image metadata after having set it
Denies changing any non-etcd local image metadata (either setting or unsetting)
Related to #2543
=> 🏃 Loosen webhook validation on control plane to allow etcd changes

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/workload_cluster.go
~/hold~
~Depends on #2553~
This PR allows KCP to keep track of the local etcd version and manage the value stored in the kubeadm config map. The result is that when an upgrade is performed it will use the value found in the kubeadm config map.
The workflow I tested with was:
1. Create a 3 node control plane cluster where the control plane is managed by a kubeadm control plane resource
2. Find the image tag of etcd (3.3.15-0)
3. Locate a list of existing etcd versions found at `k8s.gcr.io/etcd` (`gcloud container images list-tags k8s.gcr.io/etcd`)
4. Pick a newer patch version (3.3.17-0)
5. Update the kubeadm control plane's kubeadm cluster local etcd configuration to use the tag `3.3.17-0`.
6. Wait for the upgrade to finish
7. Check the image of …
=> ✨  Etcd version

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Attempts to fix a flake due to ordering not being stable. 
Example flake: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/2581/pull-cluster-api-test/1236061219702444033
/assign @chuckha
=> 🏃 Fix flake test in KCP webhook TestPaths

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
/assign @chuckha @ncdc @detiber 
=> :bug: Allow KCP spec.version to be mutable

docs/book/src/clusterctl/commands/move.md
- Add message about possible problem when doing clusterctl move
releated to #2499
=> 📖 Add message about possible problem when doing clusterctl move

cmd/clusterctl/client/cluster/cert_manager.go
This PR restores cert-manager waiting timeout to 10 minutes
=> 🐛clusterctl: fix cert-manager timeout

controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster.go
Follow-up to #2579 
- Adds a conditional check to avoid issuing an Update to the ConfigMap hasn't changed.
- Adds unit tests against `UpdateEtcdMeta`.
/assign @chuckha @ncdc 
/cc @wfernandes 
=> KCP etcd upgrade: handle conditional update & add tests

cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/installer.go, cmd/clusterctl/client/cluster/installer_test.go, cmd/clusterctl/client/cluster/upgrader.go, cmd/clusterctl/client/cluster/upgrader_info.go, cmd/clusterctl/client/cluster/upgrader_info_test.go, cmd/clusterctl/client/cluster/upgrader_test.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/delete_test.go, cmd/clusterctl/client/init_test.go, cmd/clusterctl/client/repository/client.go, cmd/clusterctl/client/repository/client_test.go, cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_client.go, cmd/clusterctl/client/repository/components_client_test.go, cmd/clusterctl/client/upgrade_test.go
This PR is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/2558 designed to improve clusterctl support for air-gapped environments by supporting the following image override config:
```
images:
all:
repository: us.gcr.io/myRepo/cluster-api
```
Thus allowing to use upstream manifest for air-gapped environments without requiring manual modifications to components yaml for all the providers.
The real change is really simple, but unfortunately, it requires refactoring the signature of a method that is used in many places.
For helping reviewers to better understand the above point, the refactor and the real change are in separate commits.
/assign @ncdc
=> ✨clusterctl: improve support for air-gapped environments all image overrides

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
This PR enables changes to the the upgradeAfter field to pass webhook validation.
Fixes #2603 
=> 🐛 Enable upgradeAfter field to be modifiable 

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go, test/infrastructure/docker/go.sum, util/util.go
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2544
=> ✨Upgrade `kube-proxy` daemonset as part of KCP upgrades

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
- add validation in webhook to check that only one of local and external etcd is set
Fixes #2580
=> 🐛validation for not having both local and external etcd in control plane

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Fixes a panic when validating the etcd settings in KubeadmControlPlane if ClusterConfiguration is nil.
Fixes #2613
=> :bug: Fix NPE when validating KCP etcd settings

test/infrastructure/docker/e2e/docker_suite_test.go, test/infrastructure/docker/e2e/docker_test.go
This prints all of the resources before they get deleted in order to improve debug-ability in prow-like environments.
Related to #2593
=> 🏃Improve capd e2e artifact output

cmd/clusterctl/api/v1alpha3/provider_type_test.go
standardize gomega imports for `cmd/clusterctl/api/*/***` tests
/cc @vincepri 
=> 🏃cmd-clusterctl-api/tests: standardize gomega imports - follow up

docs/book/src/clusterctl/commands/config-cluster.md, docs/book/src/user/quick-start.md
This PR makes a small fix to the quick start so the user explicitly asks for a given number of control-plane and worker machines.
By being explicit here we can hopefully avoid questions/feedbacks that can arise by the default (arbitrary) number of control-plane and worker machines being used when the parameters are not set.
=> 🐛small fix to quick-start

docs/book/src/SUMMARY.md, docs/book/src/tasks/kubeadm-control-plane.md
This PR adds basic upgrade instructions for kubeadm control plane resource.
Related to #2244 
I'm opening this initially to give us a place to add more documentation as we need it. It doesn't quite close #2244 but it gets us closer.
/assign @detiber @randomvariable
=> 📖 Add documentation around KubeadmControlPlane

docs/book/src/clusterctl/configuration.md
This PR document changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/2558 and by https://github.com/kubernetes-sigs/cluster-api/pull/2586
/assign @ncdc 
=> 📖clusterctl: doc config for air-gapped environments

docs/book/src/developer/providers/machine-infrastructure.md, docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
- Updates the provider documentation around FailureDomain support, migration, and provider expectations.
=> :book: Update provider documentation for failureDomains

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/workload_cluster.go
This requires the `kubeadmControlPlane.spec.version` to simply pass `semver.ParseTolerant`. That means it can have a `v` or not, it does not matter as the code will handle each case individually using a `semver.Version`.
/cc @vincepri 
=> 🏃 Be consistent with versioning in  KubeadmControlPlane

test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/machine.go
This was the cause of a number of failures. I believe there is some condition we hit that causes `kubeadm reset` to hang. However, we have this functionality in the KubeadmControlPlane which is used as part of the e2es so the docker machine controller doesn't need to run kubeadm reset any more.
This has the added benefit of aligning with other providers that don't have direct access to running commands on nodes. 
Fixes #2618 
=> 🏃 Do not kubeadm reset in capd any more

controlplane/kubeadm/main.go
=> :running: Increase default KCP concurrency to 10

docs/book/src/user/quick-start.md
Fixes a typo in the quick start guide.
Fixes #2639
=> quick-start.md: fix typo related to clusterctl

cmd/clusterctl/client/config/imagemeta_client_test.go, cmd/clusterctl/client/config/providers_client_test.go, cmd/clusterctl/client/config/reader_viper_test.go, cmd/clusterctl/client/config/variables_client_test.go
standardize gomega imports for `cmd/clusterctl/client/config/**` tests
=> 🏃cmd-clusterctl-client-config/tests: standardize gomega imports

cmd/clusterctl/client/cluster/components_test.go, cmd/clusterctl/client/cluster/installer_test.go, cmd/clusterctl/client/cluster/inventory_managementgroup_test.go, cmd/clusterctl/client/cluster/inventory_test.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph_test.go, cmd/clusterctl/client/cluster/template_test.go, cmd/clusterctl/client/cluster/upgrader_info_test.go, cmd/clusterctl/client/cluster/upgrader_test.go
standardize gomega imports for `cmd/clusterctl/client/cluster/**` tests
=> 🏃cmd-clusterctl-client-cluster/tests: standardize gomega imports

bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go, bootstrap/kubeadm/internal/cloudinit/controlplane_test.go, bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go, bootstrap/kubeadm/types/v1beta1/bootstraptokenstring_test.go, bootstrap/kubeadm/types/v1beta2/bootstraptokenstring_test.go
standardize gomega imports for `bootstrap/**/***` test
/cc @vincepri 
=> 🏃 bootstrap/tests: standardize gomega imports - follow up

controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
When checking if we need to upgrade etcd, guard against an NPE by
checking that KCP.Spec.KubeadmConfigSpec.ClusterConfiguration is not
nil.
Fixes #2633
=> :bug: KCP: fix NPE if ClusterConfiguration is nil

api/v1alpha3/machinehealthcheck_webhook.go, api/v1alpha3/machinehealthcheck_webhook_test.go
It is currently possible to put `{"spec": {"maxUnhealthy": 1}}` and `{"spec": {"maxUnhealthy": "1"}}` and get different behaviour within MHC. Within the `apps` group types, they validate that the string values are valid percentages before persisting, thus allowing the bug that I hit during the demo today to go unnoticed for such a long time.
I've added this validation to the webhook for MHC and this should prevent users from hitting this in the future
=> 🐛 Validate MHC MaxUnhealthy strings are percentages

controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
This PR adds unit tests to the coredns upgrade feature that were lost as part of the original rebase. They've been refactored and cleaned up.
N/A
=> 🏃Add tests for coredns upgrade

controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/machine_collection.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
Related to #2423, by moving these filters out and rewriting the tests to only work with the exposed APIs, this allows us to continue standardizing around dot-import gomega in the kcp/internal package.
/assign @cpanato 
/cc @detiber 
/milestone v0.3.1
=> :running: Move KCP/internal machine filters in a package

cmd/clusterctl/test/e2e/go.sum, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/workload_cluster_test.go, test/infrastructure/docker/go.sum
This PR adds a semver validation for KubeadmControlPlane.spec.version.
=> 🏃[KCP] Add KCP spec.version semver check

docs/book/src/clusterctl/overview.md
Make it a little clearer that there is no GUI for `clusterctl`
Fixes #
=> 🏃  Update clusterctl overview to remove confusion on presence of GUI

controlplane/kubeadm/main.go
This PR move KCP flags to pflags for consistency with the rest of the code base.
=> 🏃KCP: Migrate from flags to pflags

cmd/clusterctl/client/repository/client_test.go, cmd/clusterctl/client/repository/components_client_test.go, cmd/clusterctl/client/repository/components_test.go, cmd/clusterctl/client/repository/metadata_client_test.go, cmd/clusterctl/client/repository/repository_github_test.go, cmd/clusterctl/client/repository/repository_local_test.go, cmd/clusterctl/client/repository/template_client_test.go, cmd/clusterctl/client/repository/template_test.go
standardize gomega imports for `cmd/clusterctl/client/repository/**` tests
=> 🏃cmd-clusterctl-client-repository/test: standardize gomega imports

docs/book/src/user/quick-start.md
Fixes something reported by @detiber 
> Just noticed an issue with the docs thanks to a discussion with @christianh814. It looks like if you click on one of the tabs in this section https://cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers, it expands and links to the associated tab in the Initialization for common providers section rather than it's own section
=> Separate tabs in quick start

controllers/machinedeployment_sync_test.go
standardize gomega imports for `controllers/` tests
=> 🏃 controllers/test: standardize gomega imports

cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/components.go, cmd/clusterctl/client/cluster/inventory.go, cmd/clusterctl/client/cluster/mover.go
this PR make clusterctl to use retries with exponential backoff (10 retries, up to ~40s max for each operation).
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2665
/assign @ncdc
=> 🏃clusterctl: use exponential backoff

.dockerignore, Tiltfile, test/infrastructure/docker/Dockerfile
Reduced repeat work on image builds, and shrinks the docker context that gets sent over the wire.
=> 🏃 speed up e2e image builds

cmd/clusterctl/client/common_test.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/delete_test.go, cmd/clusterctl/client/init_test.go, cmd/clusterctl/client/upgrade_test.go
standardize gomega imports for `cmd/clusterctl/client/*` tests
=> 🏃 cmd-clusterctl-client/tests: standardize gomega imports

util/kubeconfig/kubeconfig_test.go, util/secret/certificates_test.go, util/util_test.go, util/yaml/yaml_test.go
standardize gomega imports for `util/*/***` tests
=> 🏃 util/tests: standardize gomega imports

test/framework/types_test.go, test/infrastructure/docker/cloudinit/kindadapter_test.go, test/infrastructure/docker/cloudinit/runcmd_test.go, test/infrastructure/docker/cloudinit/unknown_test.go, test/infrastructure/docker/cloudinit/writefiles_test.go, test/infrastructure/docker/controllers/dockermachine_controller_test.go
standardize gomega imports for `test/*/***` tests
=> 🏃test/tests: standardize gomega imports

cmd/clusterctl/client/cluster/mover.go
clusterctl: log which value clusterctl mover is setting when pausing
Fixes #2677
=> 🏃 clusterctl: log which value clusterctl mover is setting when pausing

controllers/mdutil/util_test.go, controllers/noderefutil/providerid_test.go, controllers/noderefutil/util_test.go
standardize gomega imports for `controllers/mdutil` and `controllers/noderefutil` tests
=> 🏃tests: standardize gomega imports for controllers/mdutil and controllers/noderefutil

bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, bootstrap/kubeadm/types/v1beta1/types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Perhaps easier to iterate on than a full kubernetes cluster
Addresses some odd defaulting behavior in the KCP webhook, as well as smoothing out some UX.
Fixes #1941
=> 🏃mark defaulted fields as optional

controllers/machine_controller.go, controllers/machine_controller_test.go
If there were an edge case where we deleted an unreachable node and therefore removing any pod from etcd, but an stateful process were still running on the underlying host, we'll be immediately freeing up the pod name from the apiserver. "This would let the StatefulSet controller create a replacement Pod with that same identity; this can lead to the duplication of a still-running Pod, and if said Pod can still communicate with the other members of the StatefulSet, will violate the at most one semantics that StatefulSet is designed to guarantee."
To mitigate this it'd be safer to delete the node only after the owned infraMachine is gone. This would give stronger guarantees that the underlying host is destroyed and so there's no chance of a stateful …
=> :bug: Ensure infrastructure is destroyed before deleting the node

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go, test/infrastructure/docker/e2e/docker_test.go, util/util.go, util/util_test.go
Normalises the image name for kube-proxy to support build suffixes for versioning.
Fixes #2689 
Marking as WIP as smoke tests are conducted.
=> :bug: controlplane: Normalise image name for kube-proxy, and validate Kubernetes versions

api/v1alpha3/machine_webhook.go, api/v1alpha3/machine_webhook_test.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
This PR adds semver version validation for Machine type.
Fixes #2657
=>   🏃Add semver version validation rules to Machine type and fix KCP version validation

OWNERS_ALIASES
Adds me as a reviewer to the project. I've been getting involved in the project for the last couple of months and would like to get more involved where possible. I've touched a reasonably wide area of the code by implementing the MHC project (#1990) and have been trying to review some other PRs as they have been coming in. Hopefully this gives me a good grounding for becoming an effective official reviewer
=> 🏃 Add JoelSpeed as reviewer

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/etcd/etcd.go, controlplane/kubeadm/internal/etcd_client_generator.go, controlplane/kubeadm/internal/workload_cluster.go
During the scaledown process, we need to be sure that the control plane machine that is about to be deleted is not etcd leader. This PR always moves the leadership to the first follower. It also introduces a few minor changes to etcd client, it missed the ability to get the leader ID
Closes https://github.com/kubernetes-sigs/cluster-api/issues/2398
=> ✨Forward etcd leadership from machine that is being deleted

controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/machine_collection.go, controlplane/kubeadm/internal/workload_cluster.go
This PR is a follow-up to #2525. To avoid multiple leadership changes, we now use the information available to the controller to always move the leadership to the last Machine created.
/milestone v0.3.2
/priority critical-urgent
/assign @detiber @ncdc 
/cc @chuckha @rudoi @sethp-nr
=> ✨ KCP: Move etcd leadership to newest Machine when upgrading

controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, util/util.go, util/util_test.go
=> 🐛CoreDNS validation should only look at major.minor.patch

controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
/assign @frapposelli 
/milestone v0.3.2
/priority critical-urgent
=> :bug: KCP spec.clusterConfiguration.imageRepository should not have "coredns/"

controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/etcd/fake/client.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
This PR allows the control plane to upgrade through an expected state where there are 4 control planes and 3 etcd members. This happens when the control plane controller dies after removing a member but not marking it as having been removed. It's one step closer to removing the annotations that manage state.
Some slightly larger changes due to fixing a stale fake etcd client that went unused in tests.
Adds a test for the particular case we are trying to fix.
Fixes #2651
/cc @sethp-nr @rudoi 
=> 🐛 Change the number of expected etcd members

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Giving users some info when a reconcile happens
=> :running: Add log line when reconciling KubeadmControlPlane

Makefile
This PR fixes the verify job by only checking local links and not external links.
=> :bug: Disable link checker for external links in book

controlplane/kubeadm/internal/workload_cluster.go
If a node is not a member, it can't be a leader. Instead of erroring, consider it a job well done.
Also fixes a typo in my previous PR.
Fixes #
=> :bug: leadership forwarding for removed members

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, test/infrastructure/docker/e2e/docker_test.go
This PR removes the concept of marking a machine after removing the etcd member on that node. Since all the functions being called are now idempotent, it's ok if the process crashes at any point, it will not fail on these three specific lines.
Related to #2702
=> 🐛 Remove a troublesome annotation

bootstrap/kubeadm/main.go, controlplane/kubeadm/main.go, main.go, third_party/kubernetes-drain/README.md, third_party/kubernetes-drain/drain.go
Enables setting manager LeaderElection options via command line flags
Fixes #2653 
I just implemented the optional settings in these two files but there's 3 other files where they could be implemented as well:
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/main.go
https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/main.go
https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/example-provider/main.go
Do you think it makes sense to add the flags there too?
=> ✨LeaderElection configuration as flags

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/cluster.go
Adds a restConfig timeout to 10 seconds to avoid getting stuck when deleting a self-managed cluster
Fixes #2705
=> 🐛 KCP should set a timeout when trying to connect to remote cluster

cmd/clusterctl/test/e2e/go.sum, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, go.mod, go.sum, test/infrastructure/docker/go.sum
- Skips validation if ClusterConfiguration undefined
- Skips validation if previous version undefined
This PR validates CoreDNS upgrade compatibility in the KCP webhook. It utilizes a function in the coredns-migration library that will compare two versions and determine if it can be upgraded from one to the other. 
Fixes #2620
=> ✨Validates CoreDNS version update

cmd/clusterctl/client/repository/metadata_client.go
Add CAPO to the embedded hardcoded metadata. For the v0.3.* series of CAPO releases we will keep the metadata.yaml to avoid breaking old clusterctl versions
=> ✨ Add CAPO to clusterctl embedded metadata

controlplane/kubeadm/internal/failure_domain_test.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/machine_collection.go, controlplane/kubeadm/internal/machine_collection_test.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
The cleans up the imports since there is no longer any name conflict and adds a test to machine collection as well as exports a necessary field for use in fixing #2702
=> 🏃 clean up tests

cmd/clusterctl/test/testdata/docker/v0.3.0/cluster-template.yaml
This change removes the hardcoded version for a worker node and replaces
it with the same template variable that is used for the master. If used
as a template it would always deploy a worker at version "1.14.2", it
should now properly substitute the same version for both master and
worker nodes.
=> 🐛 update worker kubernetes version in capd test template

cmd/clusterctl/client/config/variables_client_test.go, cmd/clusterctl/client/repository/client.go, cmd/clusterctl/client/repository/components_client.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/client/repository/metadata_client_test.go, cmd/clusterctl/client/repository/overrides.go, cmd/clusterctl/client/repository/overrides_test.go, cmd/clusterctl/client/repository/template_client.go, cmd/clusterctl/test/run-e2e.sh, docs/book/src/clusterctl/configuration.md, docs/book/src/clusterctl/developers.md
This PR adds configurability to the overrides directory from within the clusterctl config yaml file. 
`clusterctl` still defaults to `~/.cluster-api/overrides` if this property is not specified.
Fixes #2404
=> ✨ Clusterctl local overrides

controlplane/kubeadm/internal/workload_cluster.go
=> 🐛 Etcd should talk to leader when moving leadership

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, controlplane/kubeadm/internal/workload_cluster_test.go
standardize gomega imports for `controlplane/kubeadm/` tests
=> 🏃 controlplane-kubeadm/test: standardize gomega imports

test/infrastructure/docker/e2e/docker_test.go
This PR tries to fix a specific timeout I see in CAPD failures. It seems to be the only one I'm seeing these days and nothing looks wrong in the cluster. I just finishes riiiiight on the 3 minute mark a lot of the time.
=> 🏃 Increase a constantly failing timeout in capd

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Currently the clusterctl quickstart instructions say To verify the control plane is up, check if the control plane is ready before the step to deploy a CNI solution even though the control planes don’t become ready until after the CNI is deployed. 
context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1584567341487700
Fixes #
=> 📖 clarify order of steps in quickstart to deploy workload cluster

controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go
This is part of a larger effort to shrink the reconciler and reduce the use of annotations. This type adds a bunch of functions that do small tasks or access pieces of information in a clean way.
Because we are moving away from annotations on machines we need a way to idempotently find values. This holds those functions.
This type explicitly does not have any connections to any services and is just the logic that was found in the reconciler that is nicer outside of it.
Related to #2702
=> 🏃 Adds a control plane struct to clean up the reconciler

Makefile
This should fix the issue where `clusterctl version` shows `vx.y.z-dirty`
/assign @CecileRobertMichon @fabriziopandini 
/milestone v0.3.3
=> :running: Build binaries first during release

controllers/machinedeployment_controller.go
=> :bug: MachineDeployment controller should actually return errors

controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machineset_controller.go, docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md, util/util.go, util/util_test.go
In an effort to standardize ways to get notifications when a `Cluster.Spec.Paused` flips, we now provide a util function to add a predicate-based watcher, and a generic function that maps a Cluster to a list of objects.
/assign @ncdc @nader-ziada 
/cc @frapposelli @fabriziopandini @wfernandes @yastij @CecileRobertMichon @detiber 
/milestone v0.3.3
=> 🏃 Improve Cluster.Spec.Paused watchers and provide utils

controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machinehealthcheck_controller.go, controllers/machineset_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/workload_cluster.go, docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md, exp/controllers/machinepool_controller.go
=> 🏃 rewrite kubeadm control plane logs for consistency

docs/book/src/user/quick-start.md
:book: Converting colons into equals to ensure a copy-and-paste is valid syntax for exporting vars.
Replaces colons with equals in docs to ensure if a user copies the text blob and tries to source it or add to a script, the syntax is valid. 
Fixes #
=> 📖 Update quick-start.md

cmd/clusterctl/client/repository/repository_github_test.go
standardize gomega imports for some missing tests that were not in the gomega format
I did a walkthrough in the repo and did not find any missing tests that are not using gomega.
So I think we can close the issue, or there are any more things to do related to that? 
- Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/2433
=> 🏃 tests: standardize gomega imports

cmd/clusterctl/client/cluster/inventory.go
This PR wraps to the creation of the inventory entry into a retry loop
=> 🐛clusterctl: retry create inventory

test/infrastructure/docker/e2e/docker_suite_test.go, test/infrastructure/docker/e2e/docker_test.go
This PR avoid deleting the shared cluster after each test.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2654
=> 🐛[e2e] Avoid deleting the shared cluster after each test

docs/book/src/user/quick-start.md
Updates the OpenStack prereqs in the ClusterAPI book for v1alpha3
Is the book currently deployed from master?
WIP because those 2 PRs must be merged first:
* I linked to the PR right now. After the qemu PR is merged I would update the book a link to the image-builder book
=> 📖 update OpenStack prerequisites in the ClusterAPI book

controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
This PR replaces the removed tests from #2734 and adds a few more tests for the control plane object.
Related to #2702 
Depends on #2734 merging first
=> 🏃Finish the pending tests and clean up a few other tests

controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go
As per https://github.com/kubernetes-sigs/cluster-api/pull/2742#issuecomment-602848211, addressing pending @JoelSpeed comments in https://github.com/kubernetes-sigs/cluster-api/pull/2742
/assign @JoelSpeed 
=> 🏃address 2472 pending comments

docs/book/src/user/quick-start.md
image-builder PR has been merged: https://github.com/kubernetes-sigs/image-builder/pull/169
So let's update the link
=> 📖 Update CAPO image-builder links

controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go
Select the failure domain with most machines in a smaller set of machines instead of all controlplane machines.
Fixes #2760
=> 🐛[KCP] fix for machine selection logic during scale down

controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/helpers_test.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/status_test.go, controlplane/kubeadm/controllers/upgrade_test.go
Following https://github.com/kubernetes-sigs/cluster-api/pull/2767, this PR reorganize KCP unite tests.
No issue is created for this.
=>  🏃[KCP] reorganize unit tests

cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/components.go, cmd/clusterctl/client/cluster/inventory.go, cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph.go, cmd/clusterctl/client/cluster/proxy.go
This PR add some more retries to clusterctl. More specifically
- adds retries for handling temporary connection problems with clusters
- adds retries for all the read/write operations triggered clusterctl move
=> 🏃clusterctl: add retries to clustectl move

test/infrastructure/docker/Makefile, test/infrastructure/docker/e2e/docker_test.go
This PR enables an existing e2e test that does KCP upgrade for CI.
Also, timeout is increased as it takes longer than 3 minutes in local setups.
Fixes #2654
=>  🏃[e2e] enable all docker e2e tests for CI

docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md, util/conversion/conversion.go
This is a bugfix to separator problem issued in [2775](https://github.com/kubernetes-sigs/cluster-api/issues/2775)
=> 🐛 Bugfix to separator problem in issue #2775

bootstrap/kubeadm/main.go, cmd/example-provider/main.go, controlplane/kubeadm/main.go, main.go, test/infrastructure/docker/main.go
Seed the random number generator, as (at least) controller-runtime uses
it to add jitter to shared informer resync periods.
Fixes #
=> 🏃 Seed the random number generator

test/infrastructure/docker/e2e/docker_test.go
This PR add kube-proxy version check during KCP upgrade in e2e test.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2608
=> 🏃[e2e] add kube-proxy version check

util/util.go
This bugfix will fix the matching issue discussed in [2775](https://github.com/kubernetes-sigs/cluster-api/issues/2775) using match on group kind and not version in.
=> ⚠️ util.{Machine,Cluster}ToInfrastructureMapFunc should exclude version when parsing object references

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, controlplane/kubeadm/internal/workload_cluster_test.go, util/util.go, util/util_test.go
- Update kube-proxy and coreDNS images
- Allow modification in webhook
Allows users to update the global image registry after having created a cluster.
Fixes #2777
=> ✨ Support modifying spec.kubeadmConfigSpec.clusterConfiguration.imageRepository

docs/book/src/user/quick-start.md
This PR adds a couple export bash commands to the Cluster API Book quickstart, specifically for Azure. 
The change will help users export the correct variables from their created azure service principal.
=> 📖 Updating Azure quickstart

test/framework/control_plane.go, test/framework/workload_cluster.go, test/infrastructure/docker/Makefile, test/infrastructure/docker/e2e/docker_suite_test.go, test/infrastructure/docker/e2e/docker_test.go, test/infrastructure/docker/e2e/docker_upgrade_test.go
This PR adds an e2e test for testing etcd upgrades.
Ref #2753
=> 🏃Add Etcd e2e tests

controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster.go
Fixes issues arising when a user specifies a global `imageRegistry` in their `clusterConfiguration`. We weren't updating the kubeadm configmap and so when we spun up new nodes kubeadm would still pull from the default registry.
Fixes #2805
=> 🐛 KCP should update Kubeadm config map when setting `imageRepository`

controlplane/kubeadm/internal/etcd/fake/client.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, controlplane/kubeadm/internal/workload_cluster_etcd.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go, controlplane/kubeadm/internal/workload_cluster_test.go
This PR backfills unit tests for KCP/workload_cluster components
Ref https://github.com/kubernetes-sigs/cluster-api/issues/2753
https://github.com/kubernetes-sigs/cluster-api/issues/2779
=> 🏃Add workload cluster unit tests in KCP

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types_test.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/suite_test.go, controlplane/kubeadm/controllers/upgrade_test.go
This PR increases KCP test coverage by adding integration and unit tests.
Related issue: https://github.com/kubernetes-sigs/cluster-api/issues/2779
=> 🏃[KCP] Add integration and unit tests

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
This log line appears on any machine, including MachineSet or MachineDeployment owned machines while waiting for the cluster to be initialized. It's misleading 80% of the time, so this PR removes it
=> :running: Remove misleading log line in CABPK

cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/cert_manager_test.go, docs/book/src/clusterctl/configuration.md
- cert-manager-timeout can be set in config file
- default of 10 minutes if no value is set
**Which issue(s) this PR fixes
Fixes #2822
=> ✨ Make clusterctl cert-manager timeout configurable

controllers/remote/cluster_test.go
CenturyLink's DNS servers helpfully suggest that `test-cluster-api` lives on their "web helper" servers, and so instead of seeing a "no such host" error, I see a timeout trying to connect to a `https://` endpoint that couldn't exist.
They're willing to resolve this domain as `NXDOMAIN`, which both speeds up the test and makes it pass.
Fixes #
=> :running: Work around DNS interception

cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/inventory.go, cmd/clusterctl/client/cluster/proxy.go, cmd/clusterctl/internal/test/fake_proxy.go
This PR adds clusterctl Kubernetes server validation.
Fixes #2837
=> 🐛 Add kubernetes server validation on clusterctl

controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
=> :bug: Correctly sets DNS imageRepository when custom repositories are used

controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/etcd_client_generator.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go
We will now connect directly to the etcd leader node when removing nodes from the cluster and when we are changing the current etcd leader.
Previously when removing nodes we would just connect to any node other than the node for removal. When we were changing the current leader we would connect to both the current leader and the "candidate" leader, so this is a simplification of that code.
Fixes #2789
=> ✨ Connect to the etcd leader when possible

cmd/clusterctl/client/repository/repository_github.go, cmd/clusterctl/client/repository/repository_github_test.go
As per https://github.com/kubernetes-sigs/cluster-api/issues/2450#issuecomment-607854874 this PR implements caching for GitHub API calls, thus reducing the number or call for `clusterctl init` from 20 to 8
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2450
=> 🏃clusterctl: cache GitHub API calls

cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_test.go
fixes a problem in clusterctl replace variable when the value contains $
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/2857
=> 🐛clusterctl: fix replace variables

docs/book/src/user/quick-start.md
Adds step to export AKS subscription ID env var, since `export AZURE_SUBSCRIPTION_ID_B64="$(echo -n "$AZURE_SUBSCRIPTION_ID" | base64 | tr -d '\n')"` won't work without it
Fixes #
=> Add subscription id to azure quickstart

test/framework/discovery/discovery.go, test/framework/management_cluster.go
This PR extends the e2e framework by adding the possibility to discover Cluster API objects existing in a management cluster.
This feature allows to:
- implement pipelines that can work with any provider (discover installed providers)
- implement pipelines that can work with cluster-templates that changes across providers (discover  Cluster API objects created by the templates)
The PR also includes a utility for waiting for a controller deployment to get ready
xref #2753
xref #2637
xref #2636
/cc @wfernandes
/cc @gab-satchi
=> 🏃[e2e] clusterctl e2e discovery

cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/cmd/config_cluster.go, cmd/clusterctl/test/e2e/helpers.go
Replica counts set by the user through ENV vars or config file isn't being used as the flag options take precedence. The flags for control and worker counts default to 1 and 0 respectively and were overriding any values set as ENV vars. 
Fixes #2560
=> 🐛 Fixes default control, worker machine counts overriding user specified values

controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster_test.go
Just adding some more tests
Ref https://github.com/kubernetes-sigs/cluster-api/issues/2779
=> 🏃Improve unit test coverage for KCP

test/framework/clusterctl/clusterctl_config.go, test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go
This PR extends the e2e framework by adding support for a configuration file designed for e2e tests based on clusterctl/ready to run on different infrastructure providers.
The PR includes also a utility for creating a local clusterctl repository that contains the providers defined in the e2e configuration and a clusterctl config file to make clusterctl to use this repository.
Most notably:
- The format support list of images to be added to the kind image (same a current config)
- The list of components of the current config is replaced by a list of providers, and it is not required to add cert-manager anymore
- For each provider 
- it is possible to specify more than one version to be included in the test (for testing provider upgrades)
- it is …
=> 🏃 [e2e] clusterctl e2e config

test/framework/clusterctl/management_cluster.go, test/framework/interfaces.go
This PR adds log streaming to clusterctl e2e by using the same log streaming function as[ CAPA e2e.](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/test/e2e/e2e_suite_test.go)
Fixes #2860
Open question: Do we want to get logs from CAPI webhook controllers?
=> 🏃[clusterctl e2e] Add log streaming to clusterctl e2e

docs/book/src/user/quick-start.md
**What this PR does / why we need it**:  See https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/504
Fixes #
=> 📖 Add Azure tab for deploy Calico CNI step in quickstart

cmd/clusterctl/client/config/imagemeta_client.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_coredns.go, util/container/image.go, util/container/image_test.go, util/util.go, util/util_test.go
- Library to parse image name. and other information  
- Function will split the name of the repository in a seperate field
Fixes #2850
=> ✨Add a library to parse container image name and other fields

test/framework/convenience.go, test/framework/discovery/discovery.go, test/framework/dump_resources.go
This PR extends the discovery framework with methods to get all the cluster API resources in a namespace and methods to dump all those resources on files.
Existing methods for dumping resources are deprecated
xref #2753
xref #2637
xref #2636
=> 🏃[e2e]: dump all resources

test/framework/management_cluster.go
This PR introduces utilities to the E2E framework to be used for running each test spec in a dedicated namespace on the management cluster:
- create namespace
- stream namespace events to a log file
- delete namespace
xref #2753
xref #2637
xref #2636
=> 🏃[e2e]: add namespace utils to the test framework

test/framework/exec/kubectl.go, test/framework/interfaces.go, test/framework/management/kind/mgmt.go, test/infrastructure/docker/e2e/custom_management.go
This PR introduces small improvements to the management cluster interface, so all the internal properties are now accessible without casting the interface back to the underlying implementation, like e.g.
https://github.com/kubernetes-sigs/cluster-api/blob/efe6b709f680f26c1ebe474492ebbd98d4328c0c/test/infrastructure/docker/e2e/docker_suite_test.go#L109-L110
xref #2753
xref #2637
xref #2636
=> 🏃[e2e]: improve management cluster interface

docs/book/src/user/quick-start.md
This PR adds a required version for your management cluster if a user chooses to bring their own. 
The guidance is v1.16+ for your k8s management cluster.
=> 📖 Mgmt cluster version req

cmd/clusterctl/client/config/reader_viper.go, cmd/clusterctl/client/config/reader_viper_test.go
See issue details but essentially we are returning an error if clusterctl cannot find the specified config file.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2897
=> 🐛 Return error if clusterctl config doesn't exist

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go
This PR introduces a temporary workaround in KCP making the controller to continuously re-queue until the Ready state is reached
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2906
The issue will be closed when there will be the final solution in place
=> 🏃[KCP]: Re-queue until Ready

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd.go, test/infrastructure/docker/e2e/docker_test.go, test/infrastructure/docker/e2e/docker_upgrade_test.go
This PR adds KCP logic to recover from a manual machine deletion. When an ETCD member with missing machine is detected, delete it from the ETCD members and from Kubeadm configmap.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2818
=> 🏃[KCP] Recover from a manual machine deletion

api/v1alpha3/machineset_types.go, config/crd/bases/cluster.x-k8s.io_machinesets.yaml, controllers/machineset_controller.go
Removes some somewhat crufty logic around falling back to using `Update` when `Patch` fails on MachineSets due to validations. It seems that the patch that is constructed will never contain `replicas: 0`, so it fails validation because it was a required field.
By marking it as optional and omitempty it won't be submitted to the server, we can just rely on it having a default of 0 by virtue of being a Go value type.
Fixes #1945
=> 🏃 Remove MachineSet controller Update fallback

docs/book/src/roadmap.md
=> :book: Update Roadmap with focus on v1alpha3+ (v0.3.x)

docs/proposals/20200330-spot-instances.md
Based off of the [google doc](https://docs.google.com/document/d/1naxBVVlI_O-u6TchvQyZFbIaKrwU9qAzYD4akyV68nQ) proposal that was shared at the end of February, I have created this proposal doc based off of the template explaining how Spot instances should be implemented across the three cloud providers; AWS, Azure, GCP.
Note, this proposal does not change anything within the cluster-api repository itself, but is hosted here so that the implementation of spot support across the cloud providers can be tracked centrally and implemented in a similar manner across each provider. The goal of this project is that support should feel the same in each of the providers.
I think I've included all the people who I discussed this with and gave feedback in the …
=>  📖 Add intial Spot instances proposal

docs/book/src/tasks/healthcheck.md
This adds a note to the top of the MHC documentation highlighting that MHC currently only supports Machines owned by a MachineSet. This has tripped a few people up so this is an effort to try and make the limitations more obvious to users.
Fixes #2861
=>  📖 Add note to top of MHC docs

test/infrastructure/docker/e2e/docker_suite_test.go
Ensure that we always delete the kind cluster created by the e2e suite. The problem is that `InitManagementCluster` doesn't return errors, it uses Gomega assertions, so if an error occurs after the cluster is created it will immediately return from the `BeforeSuite` before `mgmt` is assigned.
Because of the `NewManagementClusterFn` feature I was able to abuse variable scoping a little bit to work around this, but otherwise would have to change framework.InitManagementCluster and maybe add another method to the interface. It definitely isn't the cleanest solution right now.
This also aggregates the log errors so that if one errors it doesn't prevent the rest from still attempting. Worst case they all fail but we still get one error.
**Which issue(s) …
=> 🐛 Ensure that capd tests always clean up the kind cluster

cmd/clusterctl/client/alias.go, cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/proxy.go, cmd/clusterctl/client/cluster/proxy_test.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/delete.go, cmd/clusterctl/client/delete_test.go, cmd/clusterctl/client/init.go, cmd/clusterctl/client/init_test.go, cmd/clusterctl/client/move.go, cmd/clusterctl/client/move_test.go, cmd/clusterctl/client/upgrade.go, cmd/clusterctl/client/upgrade_test.go, cmd/clusterctl/cmd/config_cluster.go, cmd/clusterctl/cmd/delete.go, cmd/clusterctl/cmd/init.go, cmd/clusterctl/cmd/move.go, cmd/clusterctl/cmd/upgrade_apply.go, cmd/clusterctl/cmd/upgrade_plan.go, cmd/clusterctl/internal/test/fake_proxy.go, test/framework/clusterctl/client.go
This PR adds support to specify the context within a kubeconfig file. It affects all the commands that provide `--kubeconfig` flag.
Fixes #2659 
Fixes #2854
**Release Notes:**
- 🐛  Fixes bug in `proxy.CurrentNamespace` to return error if it cannot find
context in the kubeconfig.
- ➕ Adds GetConfig to Proxy interface
- ➕ Adds alias client.Kubeconfig to cluster.Kubeconfig to continue separation
of concerns between client libraries.
- ➕ ClusterClientFactory takes a new input called client.Kubeconfig
which contains kubeconfig Path and Context.
- ⚠️ Replaces KubeconfigPath() method on cluster.Client …
=> ✨Support specific kubeconfig context in clusterctl

docs/book/src/user/quick-start.md
PR adds Docker and Kind as a pre-req for the CAPI Book quickstart, since most first time users use kind rather than an existing management cluster.
=>  📖 adding docker/kind prereq

cmd/clusterctl/cmd/config_repositories.go, cmd/clusterctl/cmd/config_repositories_test.go, cmd/clusterctl/cmd/init.go
- URL column points to the latest release for the provider.
- FILE column specifies the file within the release.
- Changes var io to initOpts to avoid pkg io conflict
This PR fixes the output of `clusterctl config repositories`.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2830
=> 🐛Modify the output of config repositories

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/controllers/upgrade_test.go, controlplane/kubeadm/internal/control_plane.go
Removes use of annotations in upgrade logic. We were duplicating the logic of selecting the machine in the scale down code, and it also causes bugs like #2430 where the cached state stored in the annotation gets out of sync with the world.
This logic working is dependent on the fact that `scaleUp` / `TargetClusterControlPlaneIsHealthy` ensures there's a 1:1 correspondence of nodes and machines so we don't continue scaling up while new machines are still joining the cluster.
Fixes #2702
=> 🏃Remove annotations on upgradeControlPlane

cmd/clusterctl/test/e2e/go.sum, hack/tools/go.mod, hack/tools/tools.go, scripts/ci-e2e.sh, test/e2e/Makefile, test/e2e/common.go, test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml, test/e2e/data/cni/kindnet/kindnet.yaml, test/e2e/data/infrastructure-aws/cluster-template.yaml, test/e2e/data/infrastructure-docker/cluster-template-ci.yaml, test/e2e/data/infrastructure-docker/cluster-template.yaml, test/e2e/data/infrastructure-docker/metadata.yaml, test/e2e/e2e_suite_test.go, test/e2e/kcp_upgrade.go, test/e2e/kcp_upgrade_test.go, test/e2e/quick_start.go, test/e2e/quick_start_test.go, test/e2e/self_hosted.go, test/e2e/self_hosted_test.go, test/framework/cluster_helpers.go, test/framework/clusterctl/client.go, test/framework/clusterctl/clusterctl_helpers.go, test/framework/clusterctl/e2e_config.go, test/framework/controlpane_helpers.go, test/framework/deployment_helpers.go, test/framework/machinedeployment_helpers.go, test/framework/namespace_helpers.go, test/infrastructure/docker/go.sum
This PR introduces an E2e folder that introduces clusterctl based E2E test for quick-start. self-hosted, KCP upgrade.
Most notably:
- Such test can be executed with *any* infrastructure provider (not only CAPD)
- Test spec are exposed as a library so they can be reused by other projects
xref #2753
xref #2637
xref #2636
=> ✨introduce test E2E

cmd/clusterctl/client/alias.go, cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/upgrader.go, cmd/clusterctl/client/common.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/init.go, cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_client.go, cmd/clusterctl/client/repository/components_client_test.go, cmd/clusterctl/cmd/config_provider.go
- the clusterctl config provider now can show the configuration without any env vars being set
- change the code path so we don't have to replace variables as part of this informational command 
Fixes #2876 
**Release Notes:**
- ⚠️ ComponentsClient.Get method definition changed from `func(string, string, string) (Components, error)` to `func(ComponentsOptions) (Components, error)`
- ⚠️ NewComponents method definition changed from `func(sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Provider, string, []byte, sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Client, string, string) (*components, error)` to `func(sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Provider, …
=> 🐛 clusterctl to show config provider without setting env vars

test/e2e/config/docker-ci.yaml
tuning test e2e timeouts to reduce flakes
/assign @sedefsavas 
/area testing
=> 🏃increase test e2e timeout

cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_test.go, cmd/clusterctl/client/repository/template.go, cmd/clusterctl/cmd/config_provider.go
this PR is a follow up of the https://github.com/kubernetes-sigs/cluster-api/pull/2905#discussion_r410313987
Also, the PR contains a second commits to support "if variables are available use them, but tolerate missing variables" as discussed in https://github.com/kubernetes-sigs/cluster-api/issues/2876#issuecomment-613909426
/assign @nader-ziada 
=> 🏃Clusterctl config small improvements

controllers/machineset_delete_policy.go, controllers/machineset_delete_policy_test.go
This PR adds another annotation called `DeleteMachineAnnotation=cluster.x-k8s.io/delete-machine` to the MachineSet Delete Policy because that annotation is the one that is documented.
Fixes #2912 
**Release Notes**
- ➕ Add `controllers.DeleteMachineAnnotation` with value `cluster.x-k8s.io/delete-machine`. Please use this annotation moving forward as the other annotation `DeleteNodeAnnotation` is planned for removal in the next CAPI release.
=>  🐛Add DeleteMachineAnnotation for MachineSet Delete Policy

test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
This PR fixes two timeouts in the test/e2e configuration files
/area testing
/assing @sedefsavas
=> 🏃fix e2e test timeout

util/secret/certificates.go
If a user uses an external etcd configuration but didn't supply the certificates as secrets, the lookup previously would skip them and we would encounter a NPE when rendering the nil certificates as files.
Fixes #2886
=> 🐛 Fix NPE on external etcd with undefined secrets

cmd/clusterctl/cmd/config_provider.go
Split the file name from the URL.
Remove the version from the URL since we already have a separate field
for it.
This PR keeps the output of `clusterctl config provider -i aws` for example, similar to the output of `clusterctl config repositories`.
Ref https://github.com/kubernetes-sigs/cluster-api/issues/2830
Fixes #2171
=> 🐛Fix output of clusterctl config provider

cmd/clusterctl/client/config/reader_viper.go, cmd/clusterctl/client/config/reader_viper_test.go
If clusterctl default config under $HOME/.cluster-api/clusterctl.yaml
doesn't exist, commands like clusterctl init should still work. 
However, it should still return errors if the contents of the config file is unparsable.
Fixes #2947
=> 🐛 Don't return error if cannot find default config

config/rbac/role.yaml, exp/controllers/machinepool_controller.go
This grants CAPI access to `exp.infrastructure.cluster.x-k8s.io` api group. The `exp.infrastructure.cluster.x-k8s.io` api group corresponds to experimental features in the infrastructure provider and was patterned after `exp.cluster.x-k8s.io`. This will be useful for supporting `MachinePool` and other experimental implementations in infra providers.
Related:
- [AzureMangedCluster](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/482)
- [AzureMachinePool](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/483)
=> ✨ grant rbac access to experimental infra api group

docs/proposals/20191030-machine-health-checking.md
Updates the MHC proposal with a new strategy so that MHC can support machines managed by KCP.
Related to #2836
@enxebre @vincepri @JoelSpeed 
/kind proposal
=> ✨ Update MHC proposal with new annotation strategy

test/e2e/common.go, test/framework/cluster_helpers.go
As per comment https://github.com/kubernetes-sigs/cluster-api/issues/2955#issuecomment-618916750 adding a workaround for high-level helpers panicking without returning values.
xref https://github.com/kubernetes-sigs/cluster-api/issues/2955
=> 🐛[e2e] add workaround for panic in high level helpers

docs/book/src/developer/guide.md
Although the `clusterctl` deploys the cert-manager for us. But in view of the current documentation structure, this change is required if someone is trying to set up a management cluster manually.
Fixes #2956
=> 📖 Improvements in Developer Guide

controllers/machine_controller.go, controllers/machine_controller_test.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/scale.go, test/e2e/kcp_upgrade.go
This PR fixes two different issues I observe during  KCP single control plane upgrade.
1. machine_controller was not allowing machine deletion thinking that it is the last control plane machine.
2. Not having a check for machines that are in deletion process during MachinesNeedingUpgrade() was causing a second machine with the new version to come up. It was creating a machine with new version, adding a DeletionTimestamp for the old node, and at this point when it comes to reconcile, it thinks there is still 1 machine to be upgraded (the one with the deletion timestamp) and it scales up one more time. 
Besides of creating a second machine, this was causing ForwardLeaderElection to panic from time to time. 
**Which issue(s) this PR fixes** *(optional, …
=> :bug: KCP should check if it has machines being deleted before proceeding with scale up/down

cmd/clusterctl/client/config/reader_viper.go, cmd/clusterctl/client/config/reader_viper_test.go
This PR fixes https://github.com/kubernetes-sigs/cluster-api/issues/2982 and most specifically
1. makes clusterctl to configure rules for reading env variables no matter if the config file exists or not
2. fixes an error in checkDefaultConfig 
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2982
=> 🐛Fix clusterctl error when reading default config file

OWNERS_ALIASES
add @fabriziopandini to the owner aliases file under leads.
for matching:
https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#leadership
also as @detiber commented here:
https://github.com/kubernetes-sigs/cluster-api/pull/2498#discussion_r386487064
/assign @detiber @vincepri 
we have the responsibility to self-`/hold` and not `/approve` without agreement, etc..
=> OWNERS_ALIASES: add fabriziopandini to leads

.github/ISSUE_TEMPLATE/bug_report.md
Add area label to the issue template
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2201
=> 🏃Add area label to the issue template

docs/book/src/developer/tilt.md
Fixes "The developer guide for using tilt has extra_args under the tilt-provider.json section rather than tilt-settings.json section where it belongs".
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2973
=> 📖 Move `extra_args` for Tilt before the run section

cmd/clusterctl/client/cluster/objectgraph.go, cmd/clusterctl/client/cluster/objectgraph_test.go, util/secret/consts.go, util/secret/secret.go, util/secret/secret_test.go
This PR fixes an issue in clusterctl when moving clusters with a hyphen in the name and user provider cluster secrets
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2964
/assign @wfernandes 
/cc @Arvinderpal
=> 🐛fix a clusterctl error when moving cluster with user provided certs

bootstrap/kubeadm/docs/external-etcd.md
This PR updates the documentation on using external etcd with CAPI workload clusters so as to provide clearer instructions on how users might use this functionality.
Fixes #2941
=> 📖 Update book section regarding external etcd

controllers/machine_controller_test.go, exp/controllers/machinepool_controller_test.go
Remove use of metav1.FinalizerDeleteDependents from tests
Fixes #2969
=> 🏃 Remove use of metav1.FinalizerDeleteDependents from tests

controllers/remote/cluster.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/upgrade_test.go, controlplane/kubeadm/internal/cluster.go, util/kubeconfig/kubeconfig.go, util/secret/secret.go
This PR adds an uncached client to the KCP reconciler that can be used to talk to the management cluster directly bypassing the internal controller cache.  This additional check is only done if the `initializeControlPlane` method.
In addition to the changes above, this PR also cleans some functions that were accepting `client.Client` instead of the smaller `client.Reader` while only doing read operations. This is a backward-compatible change given that the interface is smaller.
Fixes #3001
=> :bug: KCP should bypass the controller cache when initializing

controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_healthcheck_test.go, controllers/remote/cluster_cache_reconciler_test.go, controllers/remote/cluster_cache_tracker_test.go, controllers/remote/suite_test.go
Add a remote cluster cache manager that owns the full lifecycle of
caches against workload clusters. Controllers that need to watch
resources in workload clusters should use this functionality.
This is the foundation for #2414 and #2577.
It does not currently check for connectivity failures to workload clusters. It only stops the workload cluster caches if there is an error retrieving the Cluster from the management cluster. If desired, I could add something that does a minimal "ping" to each workload cluster periodically, removing any caches that have connectivity issues. Or we could do that in a follow-up.
I have not updated MachineHealthCheck to use this. I could do that in this PR, or a follow-up.
I have not added anything for …
=> ✨ Add remote cluster cache manager

controllers/cluster_controller_test.go, controllers/machine_controller_phases_test.go, controllers/machinedeployment_controller_test.go, controllers/machinehealthcheck_controller_test.go, controllers/machineset_controller_test.go, controllers/suite_test.go, controllers/suite_util_test.go, test/helpers/envtest.go, util/kubeconfig/testing.go
Trying to make envtest it a simpler API, less copypasta. I think we should be able to keep it up to date with the full set of our CRDs.
I only updated the `controllers` package tests, but others can be updated as needed.
Split out from #2975
=> Add helper wrapping envtest

api/v1alpha2/conversion.go
We were previously only converting MachineDeployment annotations from v1alpha2 to their v1alpha3 version, we need to do the same for MachineSet, given that the MachineDeployment controller is the one that annotates MachineSets.
/milestone v0.3.6
/assign @ncdc
=> 🐛 Convert MachineSet annotations from v1alpha2

controllers/mdutil/util.go, util/conversion/conversion.go
This PR fixes an issue that was causing controller to fight with each other when a management cluster had both v1alpha2 and v1alpha3 running.
The MachineDeployment controller has has logic to sync annotations from a MachineDeployment to its linked MachineSets as seen in: https://github.com/kubernetes-sigs/cluster-api/blob/a799265e225b8f0e47b4642c8211a9213d0aea9a/controllers/machinedeployment_sync.go#L112
The `SetNewMachineSetAnnotations` (regardless of what the names says) actually syncs up annotations on a new MachineSet or an existing one, in particular when this function is called https://github.com/kubernetes-sigs/cluster-api/blob/a799265e225b8f0e47b4642c8211a9213d0aea9a/controllers/mdutil/util. …
=> :bug: [0.2] Exclude conversion-data annotation when MD reconciles

hack/ensure-kind.sh, scripts/ci-integration.sh, test/integration/cluster/cluster_test.go
Update kind binary to v0.7.0 for CI. That's the version required by CAPD, and used by the e2e test framework.
Fixes #
=> :running: Update kind to v0.7.0 in integration tests

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
This PR skips the creation of boostrap data secret for KubeadmConfig if it already exists.
Fixes #2970
=> :bug: fix error from duplicate bootstrap data secret

scripts/ci-e2e.sh
To get e2e test run faster
/area testing
/hold
While checking results with few runs
=> 🏃increase parallelism for e2e tests 

CONTRIBUTING.md
- Add additional context/clarification around lifecycle, admission, and promotion process for experimental types/features
=> :book: Add additional context around experiment lifecycle

cmd/clusterctl/cmd/root.go, docs/book/src/clusterctl/configuration.md
add a `CLUSTERCTL_LOG_LEVEL` environment variable to be used instead of the `-v`.
if `CLUSTERCTL_LOG_LEVEL` is set it will override the flag `-v`
example, I did not have any running cluster, then I added some log output to make the example.
UPDATED with the new behavior
```
$ export CLUSTERCTL_LOG_LEVEL=5
$  ./bin/clusterctl config cluster my -v3
Info
info level 0
info level 1
info level 2
info level 3
Error: failed to identify the default infrastructure provider. Please specify an infrastructure provider: unsupported management cluster server version: v1.14.6 - minimum required version is v1.16.0
$ export CLUSTERCTL_LOG_LEVEL=5
$  ./bin/clusterctl config cluster my
Info
info level 0
info level 1
info level 2
info level 3
info level 4
info level 5 …
```
=> ✨clusterctl: add CLUSTERCTL_LOG_LEVEL environment variable

test/e2e/config/docker-ci.yaml
After observing some failures both in periodic and pre pull jobs when starting an HA control plane, I'm increasing an e2e timeout  
/area testing
=> 🏃[e2e] increase timeout for HA upgrade test

test/framework/config.go
This PR deprecates e2e framework.config. New config to be used is clusterctl.E2EConfig.
=> 🏃[e2e] Add deprecated tag to e2e framework.config

test/framework/machinedeployment_helpers.go
This PR adds scale helper for machine deployment.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3015
=> 🏃[e2e] Add machine deployment scaling helper function

test/e2e/config/docker-ci.yaml, test/e2e/data/infrastructure-docker/cluster-template-ci.yaml, test/e2e/data/infrastructure-docker/cluster-template.yaml, test/e2e/mhc_remediations.go, test/e2e/mhc_remediations_test.go, test/framework/machine_helpers.go, test/framework/machinehealthcheck_helpers.go
This PR adds machine health check e2e tests.
=> 🏃[e2e] add mhc test

test/framework/clusterctl/e2e_config.go
e2e config can specify providers both local and remote. When providing a remote provider with type set to URL, the e2e config still tries to determine an `absolute` path to the remote URL. This change omits url based providers from  being modified into absolute paths.
=> 🐛 Removes abs path for url providers

cmd/clusterctl/client/cluster/proxy.go, cmd/clusterctl/client/cluster/proxy_test.go
As described in the issue, this PR provides support for reading kubeconfig files as specified in the `KUBECONFIG` env var. 
Fixes #3012
=>  🐛Support KUBECONFIG env var file paths

api/v1alpha3/machinehealthcheck_webhook.go, api/v1alpha3/machinehealthcheck_webhook_test.go
=> :warning: MachineHealthCheck Spec.Selector field cannot be empty

test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/machine.go
This PR makes CAPD recover from conditions when the docker provider creates a container for a machine, but for some reason, the container is not fully operational/does not completes all the provisioning steps.
More specifically, given that the CAPD provisioning time is small, the PR cleanups containers with provisioning errors and re-provision from scratch
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2999
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2341
/assing @vincepri 
/assing @sedefsavas
=> 🏃CAPD automatically re-create a machine if there is an error during provisioning

Makefile, cmd/example-provider/Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile
Use GOPROXY environment variable if set when building the docker images.
Sometimes, using a custom GOPROXY can speed up the build.
Fixes #
=> 🏃 Use GOPROXY environment variable if set when building the docker images

cmd/clusterctl/client/repository/template_client.go
This is some cleanup. I noticed we had this struct but it wasn't being used anywhere in the code base. Everything builds and all tests pass.
N/A
=> 🏃Remove unused TemplateOptions struct

test/framework/machine_helpers.go
This PR adds a machine status check helper.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3016
=> [e2e] add machine helper for status check.

docs/book/src/SUMMARY.md, docs/book/src/developer/e2e.md, test/framework/README.md
this PR documents how to write E2E tests that
- Use the Cluster API test framework.
- Reflects real user workflow, e.g. Cluster API quick start using clusterctl
- Can run with different infrastructure providers.
The PR is WIP because some of the described steps is still beinf developed
xref #2753
xref #2637
xref #2636
/cc @wfernandes
/cc @gab-satchi
=> 📖 developing e2e tests

cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/init.go, cmd/clusterctl/client/init_test.go, cmd/clusterctl/client/repository/components.go
This PR allows commands like `clusterctl init --list-images` to work without having to define variables values in the clusterctl config or environment. However, `clusterctl init` will still require variables to be defined.
I've broken the work up into separate commits which I will squash after review.
Fixes #2516
=> 🐛 Init images skip variables

docs/proposals/20200423-etcd-data-disk.md
This PR brings the CAEP for implementing disk setup and mounts in CABPK.
Comments on the [Google doc](https://docs.google.com/document/d/12eYcQrlZdkojHY3atUCCIS9YGPQ1LSQvT4gdg6JWroc/edit?usp=sharing) are addressed.
Moving here for getting feedback from a broader audience.
Relates to #2994
=> 📖 Etcd on data disk CAEP

cmd/clusterctl/client/common.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go
The cluster-name parameter is used for object names and labels, so it should accept valid DNS1123 subdomains values including the dot character
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3049
=> 🐛[clusterctl] accept cluster names with dots

Makefile, docs/book/src/developer/testing.md, test/e2e/config/docker-dev.yaml
This PR adds targets for the new e2e to the main Makefile and updates the book e2e section.
/hold until https://github.com/kubernetes-sigs/cluster-api/pull/2839 is merged
=> 🏃[e2e] add e2e target to Makefile and update book

test/e2e/internal/log/log.go, test/e2e/self_hosted.go, test/framework/bootstrap/kind_provider.go, test/framework/bootstrap/kind_util.go, test/framework/cluster_helpers.go, test/framework/cluster_proxy.go, test/framework/clusterctl/client.go, test/framework/clusterctl/clusterctl_helpers.go, test/framework/controlpane_helpers.go, test/framework/deployment_helpers.go, test/framework/deprecated.go, test/framework/internal/log/log.go, test/framework/machine_helpers.go, test/framework/machinedeployment_helpers.go, test/framework/namespace_helpers.go, test/framework/pod_helpers.go
replace fmt.Println with writes to ginko's writer
Let me know if this is what you want :)
- Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/2514
/cc @chuckha
=> 🏃 e2e: replace fmt.Println with writes to ginko's writer

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/internal/workload_cluster_coredns.go
We're seeing a lot of these log lines in our cluster(s):
```
E0506 19:19:39.493104       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"1.6.2\" must be greater than fromVersion \"1.6.2\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"md1a","Name":"md1a-controlplane"}
```
It looks like CoreDNS is being reconciled even though we haven't set up any of the DNS properties to opt in to that behavior.
=> 🏃‍♂️ Provide a way in KCP to disable CoreDNS management via annotations

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/internal/cluster.go
KCP tries to update the status of the `KubeadmControlPlane` object after each reconcile. However, part of that information is retrieved from the workload cluster, which may not always be available. This just changes the logging behavior to reduce the severity of these logs so that users aren't confused by the failures.
Fixes #3021
=> ✨ Treat failing to connect to the workload cluster as a transient error

docs/book/src/user/quick-start.md
This removes the second mention of needing to install `clusterawsadm` for a step where `clusterawsadm` is not relevant.
It's likely just a copy and paste artifact from the earlier step, when `clusterawsadm` is required for generating the CloudFormation IAM assets.
=> 📖 Remove extra mention of clusterawsadm in context where it is not needed

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Allows to modify preKubeadmCommands, postKubeadmCommands and files in KCP
Fixes #3014
=> ✨ Allowing mutability for the PreKubeadmCommands, PostKubeadmCommands and Files

controllers/machineset_controller.go
This PR removes the WaitGroup for MachineSet controller deletion requests.
It was added around v1alpha1 timeframe because Delete at that time was blocking.
Today, these Delete calls can be done sequentially because they return right
away and don't have to wait for the delete to finish.
Fixes #2989
=> 🏃 Remove WaitGroup for MachineSet controller deletion requests

controllers/machineset_controller.go, util/util.go
Just a minor cleanup to the MachineSet internal code.
Fixes #2989 
/assign @detiber 
/milestone v0.3.7
=> 🏃 Cleanup some internal MachineSet bits

docs/proposals/20200330-spot-instances.md
Update the Spot instances proposal to clarify that the Azure types should use string instead of float as originally noted.
It was noticed during implementation (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/559/files#r424579944) that floats are not allowed by the controller-tools crd generator tool
Ref: https://github.com/kubernetes-sigs/controller-tools/issues/245
The alternative to this is to use a `resource.Quantity` which is allowed, but I'm not sure if that adds much benefit over using a string
CC @CecileRobertMichon
=>  📖 Update Azure spot types to use string instead of float

docs/proposals/20200220-cluster-resource-set.md
This PR adds CAEP for implementing Cluster Resource Set that was discussed in [Design Doc](https://docs.google.com/document/d/1lWLGN66roMjXL49gKO6Dhwe7yzCnvgrCtjR9mu4rvPc/edit?ts=5eb07925#heading=h.p6uvc6v59u6n).
Moving here for getting feedback from a broader audience.
=>  📖CAEP: Cluster Resource Set

docs/proposals/20191030-machine-health-checking.md
We realized during the review of #2975 that using annotations would amount to a privilege escalation for users who had `machine.edit` access but not `machine.delete`.
So instead we're proposing that we use conditions (#3017) because that has the benefit of being a part of the status, which requires a higher level of privilege that is not commonly held by users.
That CAEP is still pending so this is effectively blocked on that proposal being merged first.
/hold
xref #2836, #2920
=> ✨ Update MHC proposal to use conditions instead of annotations

bootstrap/kubeadm/api/v1alpha2/conversion.go, bootstrap/kubeadm/api/v1alpha2/conversion_test.go, bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types_test.go, bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go, go.mod
Follow up from https://github.com/kubernetes-sigs/cluster-api/pull/3083
=>  ⚒️ fix CAPBK file conversion, add validating webhook

util/conditions/patch.go, util/conditions/patch_test.go, util/conditions/unstructured.go, util/conditions/unstructured_test.go
This PR implements a set of utils for handling patching of conditions, mostly designed for supporting the handling of concurrent changes to the same list of conditions
/cc @benmoss 
/cc @detiber
=> ✨ Add conditions patch utils

util/conditions/patch.go, util/conditions/unstructured.go
=> :running: Follow-up to condition patch utils

util/conditions/getter.go, util/conditions/getter_test.go, util/conditions/merge.go, util/conditions/merge_strategies.go, util/conditions/merge_strategies_test.go, util/conditions/merge_test.go, util/conditions/setter.go
This PR implements a utils for handling conditions according to the design patterns introduced by the [condition CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200506-conditions.md) (Mirror, Aggregate, Summarize)
/cc @gab-satchi
=> ✨ add condition merge utils

docs/book/src/SUMMARY.md, docs/book/src/tasks/change-machine-template.md, docs/book/src/tasks/kubeadm-control-plane.md
This PR adds documentation regarding the immutability of machine templates, and provides information on the recommended process for modifying a machine template. This PR adds a new page, a link to the sidebar, and modifies the Tasks/KCP page to reference the new page.
Fixes #2557
=> 📖 Document the immutability of machine templates

api/v1alpha2/conversion.go, api/v1alpha2/zz_generated.conversion.go, api/v1alpha3/cluster_types.go, api/v1alpha3/machine_types.go, api/v1alpha3/machinehealthcheck_types.go, bootstrap/kubeadm/api/v1alpha2/conversion.go, bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go, bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, config/crd/bases/cluster.x-k8s.io_clusters.yaml, config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml, config/crd/bases/cluster.x-k8s.io_machines.yaml, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Adds an `ObservedGeneration` field to all objects that have a Status. My understanding of the semantics of `ObservedGeneration` is that it's only supposed to be updated when reconciliation is *complete* for the given version.
Fixes #3078
=> ✨ Add observed generation to all relevant objects

docs/book/src/developer/architecture/controllers/bootstrap.md, docs/book/src/reference/providers.md, test/infrastructure/docker/README.md
Changes all instances of https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm
to the new location, https://github.com/kubernetes-sigs/cluster-api/tree/master/bootstrap/kubeadm in
the documentation.
This corresponds to the deprecation described in https://github.com/kubernetes-sigs/cluster-api/pull/1634
=> 📖 Update references to proper CAPBK location

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/cmd/config_repositories_test.go
Signed-off-by: Avi Deitcher <avi@deitcher.net>
Adds Packet's cluster-api provider (CAPP) to the default supported repositories
Packet just completed a run of converting its v1alpha1 provider to v1alpha3, and is ready to incorporate it.
Follow-on PR will add it to the book where the default ones are listed.
Packet decided - in discussion with some of the cluster-api folks on a call last week (and slack with @timothysc ) to donate its cluster-api provider to Kubernetes-sigs, so it could live under https://github.com/kubernetes-sigs/cluster-api-provider-packet . That is a separate process which we will go through to prepare it, and raise in a future cluster-api meeting.
cc @gianarb
=> Add packet to list of default providers ✨

cmd/clusterctl/client/repository/components_client.go, cmd/clusterctl/log/logger.go
This lets us log warnings like when overrides are being used without interfering with the ability to pipe to `kubectl`.
Before you'd get:
```
clusterctl config cluster bmo --kubernetes-version v1.17.3 --control-plane-machine-count=1 -v 5  | k apply -f-
error: error parsing STDIN: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
```
Now you get:
```
bin/clusterctl config cluster bmo --kubernetes-version v1.17.3 --control-plane-machine-count=1 -v 5  | k apply -f-
No default config file available
Fetching File="cluster-template.yaml" Provider="infrastructure-aws" Version="v0.5.3"
cluster.cluster.x-k8s.io/bmo created
awscluster.infrastructure.cluster.x-k8s.io/bmo created …
```
=> 🏃‍♂️ Switch clusterctl logging to stderr

bootstrap/kubeadm/api/v1alpha2/conversion.go, bootstrap/kubeadm/api/v1alpha2/conversion_test.go, util/conversion/conversion.go
One more follow up to https://github.com/kubernetes-sigs/cluster-api/pull/3100
Fixes a bug in the conversion logic @CecileRobertMichon caught as we were working on capz conversions.
Adds pretty printing for object diffs in conversion utils. The current output is dense and not very human readable.
/assign @vincepri @CecileRobertMichon
=> 🐛 fix CAPBK conversion bug

docs/book/src/clusterctl/provider-contract.md, docs/book/src/user/quick-start.md, docs/book/theme/css/general.css
The Packet provider was missed from a small number of pages in the
documentation.
/cc. @deitch
=> 📖  added packet where needed across the cluster-api

controlplane/kubeadm/config/default/kustomization.yaml, controlplane/kubeadm/config/default/manager_role_aggregation_patch.yaml, controlplane/kubeadm/config/rbac/aggregated_role.yaml, controlplane/kubeadm/config/rbac/kustomization.yaml
**What this PR does / why we need it**: In a similar way to https://github.com/kubernetes-sigs/cluster-api/pull/1980 this PR adds an aggregation label to the kubeadm control plane manager role to ease integration with non-SIG sponsored infrastructure providers.
Not too sure if there's a good place for some documentation - I'm not sure what the minimal permissions are, but I believe the following would be enough for any foo infrastructure provider:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: capi-kubeadm-control-plane-foo
labels:
kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"
rules:
- apiGroups:
- infrastructure.foo.com
resources:
- foomachines
- foomachinetemplates
verbs:
- create
- delete
- get
- list
- patch
- update
- watch
```
=> ✨Add kubeadm control plane manager role aggregation label

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_reconciler_test.go, controllers/suite_test.go, main.go
This PR sets up a ClusterCacheTracker and reconciler in the main and passes the tracker to the MHC so that it can use that to track remote Nodes rather than doing it itself
I've also added a test which is meant to check the remote tracking functionality, but I hit a bump, with the normal timeout, it passes whether the tracker is there or not because we do a full resync every second. So I've set it with a very short timeout (500ms), I'm concerned this may flake in CI. 
Does anyone happen to know why the tests set up this way so that there's a full sync every second? What are the implications of possible extending that?
=> 🌱 Integrate shared remote cluster watching into MHC

docs/book/src/user/quick-start.md
This PR updates [Quick Start Required configuration for common providers](https://cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers) about OpenStack to more quickly start.
Fixes #
=> 📖 Update quick start about OpenStack

bootstrap/kubeadm/api/v1alpha2/conversion.go, bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go, bootstrap/kubeadm/api/v1alpha3/condition_consts.go, bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go, bootstrap/kubeadm/api/v1alpha3/zz_generated.deepcopy.go, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, test/helpers/client.go
This PR adds conditions to the KubeadmConfig object
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3110
=> 🌱 Add conditions to the KubeadmConfig object

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_targets_test.go
This PR removes the need to create new envtest environments in multiple tests (this should be discouraged in general). Envtest is meant to be used globally at a package level, and shouldn't generally be created in each individual test.
The affected tests in this PR are testing private methods, for this the fake client is a better choice. 
This PR also removes the need for cluster-name index on MHC, which isn't needed because a label is already present to filter objects that way.
=> 🌱  MHC mapper tests shouldn't create new test environments

api/v1alpha3/machine_webhook.go, api/v1alpha3/machine_webhook_test.go, controllers/machinedeployment_controller_test.go, controllers/machineset_controller_test.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types_test.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml, test/e2e/common.go
**What this PR does / why we need it**: Makes MachineSpec Version validation consistent with [KCP version validation](https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go#L45). For both KCP and Machine Spec.Version, the version will be defaulted to have a `"v` prefix if the user doesn't pass it in with the prefix to avoid this being a breaking change. 
⚠️ The `v` prefix is now required for `MachineSpec.Version` and will be defaulted if not provided.
Fixes #3128
=> 🐛 Make MachineSpec Version validation consistent with KCP

Dockerfile, Makefile, Tiltfile, cmd/example-provider/Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev
Bumps golang version to 1.13.12
Fixes #3161
=> bump golang version to 1.13.12

config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml, exp/api/v1alpha3/machinepool_types.go
**What this PR does / why we need it**: Enables the "/scale" subresource on MachinePools. Note that this does not define a `selectorpath` as `MachinePool` replicas are not represented by individual objects and instead map directly to the infrastructure set replica count.
Fixes #3158
=> ✨ Enable kubectl scale on MachinePool

util/patch/patch.go, util/patch/utils.go
This PR improves the logic when we're patching conditions. In more details:
- Remove un-needed copies.
- Always get the latest version of the object and apply the condition diff, this is required because we always patch metadata/spec/status before patching conditions, in 80% of the cases we were issuing a re-queue.
/assign @detiber @fabriziopandini 
/milestone v0.3.7
=> 🌱 Improve patch helper condition logic

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, controllers/machine_controller.go, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go, util/conditions/getter.go, util/conditions/getter_test.go, util/conditions/merge_strategies.go
This PR 
1. Makes it possible to specify a list of conditions to be used for generating a summary, so we can control how the semantic for the Ready conditions change over time (before it was automatically changing whenever a new condition was added)
2. Makes the step x of y notation to use the above list of conditions to determine the y value
3. Makes it possible to use the step x of y notation during the provisioning of a machine, but then it switches backs to the default notation when other conditions appear (e.g MHC conditions)
All the existing summary conditions are then updated to use the new merge options.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3151
=> 🌱 Improve conditions summary

controlplane/kubeadm/controllers/helpers.go, docs/book/src/developer/architecture/controllers/control-plane.md, docs/book/src/tasks/kubeadm-control-plane.md, util/certs/consts.go, util/kubeconfig/kubeconfig.go, util/kubeconfig/kubeconfig_test.go
KCP will now automatically regenerate the Kubeconfig secret during cluster reconciliation. It will do so when the client certificate in it reaches it's half-life of 180 days.
Fixes #3113
Side note: I'd like to propose deprecating `kubeconfig.New` as part of this, any thoughts? It's kind of confusing now where `New` is essentially a private method that only gets called by `generateKubeconfig`. Previously the only usage was from `CreateSecretWithOwner`.
/assign @nader-ziada @sedefsavas
=> ✨ KCP regenerates kubeconfigs before client certs expire

Tiltfile, docs/book/src/clusterctl/developers.md, test/infrastructure/docker/Makefile, test/infrastructure/docker/config/manager/manager_image_patch.yaml
This PR fixes failures in post-cluster-api-push-images due to CAPD trying to post images in the old repository.
Fixed #3182
=> 🐛 fix push images for CAPD

api/v1alpha3/cluster_types.go, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, bootstrap/kubeadm/types/v1beta1/types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Fixes support for dual-stack network ranges. Users can provide more than one pod and/or service CIDR block on their [ClusterSpec's ClusterNetwork struct](https://github.com/benmoss/cluster-api/blob/2aeb53299285a86cc9ccaa13365ca58d0b61c8ac/api/v1alpha3/cluster_types.go#L65-L84) which then is used to populate the [KubeadmConfig Networking struct](https://github.com/benmoss/cluster-api/blob/2aeb53299285a86cc9ccaa13365ca58d0b61c8ac/bootstrap/kubeadm/types/v1beta1/types.go#L232-L247).
Fixes #3149
=> 🐛 Fix support for dual-stack network ranges

util/conditions/patch.go, util/conditions/patch_test.go, util/conditions/setter.go, util/conditions/setter_test.go, util/patch/patch_test.go
This PR fixes a nasty bug when applying a condition patch with and add operation with the path happening on a different second than the one where the condition was set on the target object.
The PR also align the variable names used for the objects involved in the three-way merge with the one used by the patch helper (before, after, latest), so there will be less confusion were looking at the code
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3178
=> 🐛 Apply conditions patch should preserve LastTransitionTime

controllers/machine_controller.go, controllers/machine_controller_noderef.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_targets.go, controllers/machinehealthcheck_targets_test.go, controllers/machineset_controller.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_healthcheck_test.go, controllers/remote/cluster_cache_reconciler_test.go, controllers/remote/cluster_cache_tracker_test.go, controllers/suite_test.go, main.go, util/patch/patch_test.go
This PR's main goal is to improve the re-usability of the remote clusters caches, and exposing a method to get a new delegating client from it.
After an afternoon debugging test flakes in CI and locally, I've tracked down the main slowdown in tests to the `remote.NewClusterClient` function. This function creates a new client backed by a new cache every time is called, which is a heavy-weight and highly unoptimized way to get a client to a workload cluster. Moreover, the client it creates, although backed by a cache, isn't a delegating one.
With this PR, we're finally able to share not only the cache between different controllers but also the underlying delegating client, initializing it only once. …
=>  ⚠️  Use cache tracker to get a client for remote clusters

docs/book/src/clusterctl/developers.md, docs/book/src/user/quick-start.md
…netes-sigs/cluster-api/issues/3013
Signed-off-by: Andrea Spagnolo <aspagnolo@vmware.com>
kind v0.8.0+uses a different default network named "kind" causing the timeout described in the issue #3013. The doc now shows the variable to use to assign the bridge used by the control panel container.
=> 📖 Add instructions for kind v0.8.x

docs/book/src/developer/architecture/controllers/bootstrap.md, docs/book/src/tasks/certs/using-custom-certificates.md
Fix typos, by replacing CAPBK with CABPK, `Cluster API Bootstrap Provider Kubeadm`.
=> 📖 Fix typos for CABPK

Dockerfile, Makefile, cmd/example-provider/Dockerfile, docs/Dockerfile, hack/boilerplate/boilerplate.Dockerfile.txt, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Makefile
This is an experiment on using docker build kit to reuse the same go cache across different docker builds, thus speeding up build time
NB. this requires docker 19.03, and I'm not sure what we have currently on CI...
/cc @randomvariable @vincepri @detiber
=> 🌱 Use docker build kit to reuse go cache

Dockerfile, docs/book/src/clusterctl/developers.md, docs/book/src/developer/guide.md, docs/book/src/developer/tilt.md, test/infrastructure/docker/Dockerfile
As per https://github.com/kubernetes-sigs/cluster-api/pull/3210#issuecomment-646053557, documenting docker version requirements and the usage of `--mount=type=cache,target=/root/.cache/go-build`
=> 🌱 Document docker version requirements

CONTRIBUTING.md
This PR is a starting point to better document our review process and what we expect from reviewers.
=> 📖 Update CONTRIBUTING.md with high-level review guidelines

controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_tracker_test.go
The cluster cache tracker tries to deduplicate watch requests by matching the watchinput kind, watcher and eventhandler to the watches that it has already started.
However, this comparison was failing for real world event handlers because Go was not matching the inputs. Switching to reflect.DeepEqual helps with the equality of the watcher and kind, but still fails for eventHandlers because they will embed functions and DeepEqual will always return false for non-nil functions.
As a solution/workaround, we replace the eventHandler with a string representation of itself which will identify the struct type and should give pointers to the functions embedded within it. I'm hoping this should be sufficiently unique to identify a particular codepath calling …
=>  🐛  Fix for watch info matching in cluster cache tracker

cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/mover_test.go
#2252 requires a test for `ensureNamespaces`. This PR includes a test for `ensureNamespace` (which is called inside `ensureNamespaces`) and also I think a bug fix regarding the scope of an `err`.
In writing new tests for `ensureNamespaces`, I've found some odd behavior there which needs addressing. A test for that function is not in this PR.
Edit: this is in relation to my previous PR https://github.com/kubernetes-sigs/cluster-api/pull/2984
=> 🌱 Add tests for ensureNamespace

CONTRIBUTING.md, REVIEWING.md
The Cluster API community is vibrant and often new people start sending PRs, or existing contributors starts to review other's PRs.
So, in order to help everyone, I started this document as a collection of review tips/useful infos, so both developers and reviewers can start sharing a common knowledge base about what is important to get properly addressed in a Cluster API PR.
/assign @vincepri @detiber @ncdc @CecileRobertMichon
=> 📖 Add reviewing tips

docs/book/src/roadmap.md
This PR starts adding more structure to our roadmap document. In this iteration the main goal was to move things around and remove any unspecified or deferred item from the document.
=> 📖  Add more structure and details to roadmap document

api/v1alpha3/condition_consts.go, controllers/cluster_controller.go, controllers/cluster_controller_phases.go
This PR adds conditions to the Cluster object.
Cluster mirrors conditions from the infrastructure cluster object and from the control plane ref object.
/assign @vincepri @detiber
=> 🌱 Add conditions to cluster object

controllers/machinehealthcheck_controller_test.go
This PR rewrites the MHC tests to be consistent with the rest of the codebase, it makes sure that we don't reuse any objects between specs. The code can be improved, for example the generation of the fake and nodes could take a struct instead of arguments; but we can tackle this later. The main goal is to get rid of the flakes and clean this up.
Fixes #3197
=> 🌱  Rewrite MHC tests to be consistent with rest of codebase

cmd/clusterctl/client/cluster/mover_test.go
Following my recent work on fixing a small bug and writing tests for
`ensureNamespace` in #3217 in order to close #2252 
A few test cases have been added to ensure namespaces are created on a target before other objects are moved across.
Fixes #2252
This was closed I think in some confusion with my previous test which was `ensureNamespace` (no S).
=> 🌱 Adds a test for ensureNamespaces (plural)

controlplane/kubeadm/internal/workload_cluster.go, util/certs/certs.go, util/certs/certs_test.go, util/certs/types.go, util/kubeconfig/kubeconfig.go
This PR adds support for PKCS8 formatted CA private key, to prevent failure when a user provides his own CA key using the commands from the CAPI book : https://cluster-api.sigs.k8s.io/tasks/certs/using-custom-certificates.html 
A setup with those commands would otherwise fail.
Fixes #3173
=> 🌱 Add support for PKCS8 private keys in CA certs

docs/book/src/user/quick-start.md
-  This `AZURE_ENVIRONMENT` env var specifies the Azure cloud to use. 
Fixes #
will hold for the PR in capz adding this feature to merge https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/649 
/hold
=> 📖  Add AZURE_ENVIRONMENT env var to azure instructions in quick start guide

controllers/machineset_delete_policy.go, controllers/machineset_delete_policy_test.go
This PR prioritizes machines without node references to be deleted.
Fixes #3193
=> 🐛 Prioritize deleting machine without NodeRef

controllers/machinehealthcheck_controller_test.go
Timing sometimes makes the test fail, let's use patch instead.
=> :seedling: Use patch in tests instead of update

api/v1alpha3/common_types.go, controllers/external/util.go, controllers/external/util_test.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/helpers_test.go, controlplane/kubeadm/controllers/scale_test.go, test/helpers/envtest.go
This PR adds infrastructure template that is cloned to create a machine as annotation to the machine object.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3020
=> 🌱Add infraref annotation to KCP machines

api/v1alpha3/machinehealthcheck_webhook.go, api/v1alpha3/machinehealthcheck_webhook_test.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_targets.go, controllers/machinehealthcheck_targets_test.go
Fix MHC so that it will only target machines that have the label marking them as being a part of the cluster specified by the MHC's `ClusterName`.
Fixes #3202
I fixed the `errors.Errorf` call since I noticed it was logging memory addresses rather than machine names, but not really related to this PR.
=> 🐛 Scope MHC machines to the cluster matching their clusterName

docs/book/src/user/quick-start.md
/hold
Updates quick start docs to match https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1734
To be merged after CAPA v0.5.5 is released.
Fixes #
=> 📖 Update quickstart for clusterawsadm v2

Makefile, cloudbuild.yaml
this is a tentative to fix image build in CI
/assing @detiber 
/assing @vincepri
=> 🌱 Image builds should prepull experimental docker buildkit deps

Makefile
=> :seedling: Make release-staging should pre-pull required images

Makefile
=> :seedling: Use full path for golang images

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, docs/book/src/tasks/kubeadm-control-plane.md
Cluster-scoped secrets in v1alpha2 were generated an owner ref that lacked the "controller=true" property.
That means that checking for a controller reference will fail to adopt any v1a2 secrets, and cause the cluster to enter a broken state on adoption post-upgrade.
Fixes #3144
=> :bug: Properly adopt cluster secrets on upgrade

test/infrastructure/docker/Makefile
Follow-up fix from #3239 for CAPD
=> :seedling: Pull images when building capd as well

controllers/external/testing.go, controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go, controllers/machinehealthcheck_controller_test.go, controllers/machineset_controller_test.go, controllers/suite_test.go, controllers/suite_util_test.go
This PR makes sure that machines created during MHC tests
have proper node references, infrastructure refs, and status fields.
In the future, we need to make all of these fake utilities available
in a separate package for folks to use, given that they're really
important for integration tests.
/assign @gab-satchi
=> 🐛 Test suites should create proper machines

cmd/clusterctl/cmd/delete.go, docs/book/src/clusterctl/commands/delete.md
This PR adds a documentation warning for the `clusterctl delete` section in the CAPI book to surface the bug #3119.
Ref https://github.com/kubernetes-sigs/cluster-api/issues/3119
=> 📖 Add known bug warning for clusterctl delete

util/patch/patch.go, util/patch/patch_test.go
This PR adds ability to add options when invoking `Patch`, this PR is related to an issue reported by @detiber that wouldn't allow us to only patch observed generation when needed.
Related to #3256
=> :seedling: Allow Patch to specify options as well

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/cmd/config_repositories_test.go, docs/book/src/reference/providers.md, docs/book/src/user/quick-start.md
Now that
[kubernetes/org/issues/1934](https://github.com/kubernetes/org/issues/1934)
is closed we are officially part of the kubernetes-sigs family!
Thank you for having us!
=> 🌱 Packet provider is now part of kubernetes-sigs

test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml, test/framework/clusterctl/clusterctl_helpers.go, test/framework/deployment_helpers.go
As part of investigating https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1764, found it useful to collect metrics during an e2e test. PR'ing the bits that I've used.
Fixes #
=> test framework: Enable metrics collection

cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/init_test.go
As per the issue #2871 some test coverage was missing from Client InitImages. This PR adds more testing coverage of the functionality of this method.
This PR also changes the `fakeClusterClient` to enable the injection of a `fakeCertManagerClient`
Fixes #2871
=> 🌱 Adds tests for InitImages

Tiltfile
make the kustomization substitution explicitly fail before trying to encode an empty data structure .... makes tilt workflow idiot proof :)   https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1768
=> 🌱 Add an error message if missing substitutions for kustomization

util/conditions/patch.go, util/conditions/patch_test.go, util/patch/options.go, util/patch/patch.go, util/patch/patch_test.go
This PR allows incremental condition patching within the same controller.
In order to do so, in the final defer patch, it is required to declare the list of conditions the controller owns, and for which, a conflict between after and latest value of the condition should not generate errors (after value should always be used instead)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3260
/assign @gab-satchi
=> 🌱 Allow incremental condition patch

controllers/machine_controller_phases.go, controllers/machine_controller_phases_test.go, controllers/suite_test.go, util/util.go, util/util_test.go
Checks if any existing machines have the MachineSet controllers as the owner and removes them in the reconcile phase since the Machine controller should be the owner
Fixes #3145
=> 🐛 Removes MachineSet Controller owner for existing Machines

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/machine_controller.go, controllers/machine_controller_test.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controlplane/kubeadm/controllers/controller.go
This PR adds the observedGeneration object in the status
Fixes #3078
=> 🌱 Controllers should now populate `status.observedGeneration`

config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml, exp/api/v1alpha3/machinepool_types.go, exp/controllers/machinepool_controller.go, exp/controllers/machinepool_controller_test.go
Add the status ObserverGeneration into the machinepool controller
Fixes #3078
=> 🌱 MachinePool now has `status.observedGeneration`

cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_test.go
This PR updates clusterctl so it is possible to have ClusterRole/RoleBindings for webhooks service accounts
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/3264
/assing @yastij 
/assing @vincepri
=> 🌱 Clusterctl supports ClusterRole/RoleBindings for webhooks

bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, bootstrap/kubeadm/types/v1beta1/types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Change reference from "spec.kubernetesVersion" to "spec.Version" for the Machine object.
Fixes #3257
=> :book: Fix references to spec.kubernetesVersion for the Machine object to spec.Version

api/v1alpha3/common_types.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/controllers/helpers_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/controllers/upgrade_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go
KCP upgrade was being initiated when new fields are added to KubeadmConfig due to hash comparison logic. This PR introduces a new upgrade logic that checks version, infrastructure reference, and kubeadmconfig individually instead of using hash.
Fixes #3170
=> 🐛 KubeadmControlPlane shouldn't rely on hashing to determine if a Machine is outdated

controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
As per #3234 (comment) there is room for cleaning up the machinesNeedingRollout func in KCP
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3276
=> 🌱 Cleanup machinesNeedingRollout in KCP

controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/util_test.go
As per https://github.com/kubernetes-sigs/cluster-api/issues/3278 we are splitting the MatchesKubeadmBootstrapConfig func in KCP in logical components (init/join/cluster configuration, etc) and adding uni tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3278
=> 🌱 Cleanup MatchesKubeadmBootstrapConfig and add unit tests

cmd/clusterctl/log/log.go
While investigating some e2e test failures I noticed that all the clusterctl logs subsequent to the first one are empty.
This change tries to force a reset of the controller-runtime log library
=> ⚠️ clusterctl: log.Log is now exposed correctly as logr.Logger

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/controllers/helpers_test.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/status.go, controlplane/kubeadm/internal/cluster_labels.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
This is a follow-up PR to #3234, removes the use of the hash label when creating Machines or bootstrap/infrastructure objects. It also removes helper methods related to the hash.
/assign @ncdc @detiber @fabriziopandini 
/milestone v0.3.7
=> 🌱 Remove hash label from KCP machines

cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph.go, cmd/clusterctl/client/cluster/objectgraph_test.go, cmd/clusterctl/internal/scheme/scheme.go, cmd/clusterctl/internal/test/fake_objects.go, cmd/clusterctl/internal/test/fake_proxy.go
This PR extends clusterctl move so it will manage to move the ClusterResourceSet objects defined in a namespace.
TL;DR of the changes: during the discovery phase that is executed before Move, we are identifying ClusterResourceSet and their descendants; those objects will be included in the move scope.
NB. 
this PR will remain WIP until https://github.com/kubernetes-sigs/cluster-api/pull/3107 merges
=> 🌱  clusterctl move ClusterResourceSets

docs/book/src/developer/providers/implementers-guide/generate_crds.md
This PR updates the provider implementers guide documenting that it is required to apply the contract version label and some other customizations to the scaffolding generated by kubebuilder
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3039
=> 📖 Improve implementers guide

controllers/cluster_controller.go
This PR makes sure`listDescendents` function fetches MachinePools object too. This enables MachinePools to be deleted as well when cluster is deleted.
Fixes #2952
=> 🐛 listDescendents fetch MachinePools

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
For air-gapped systems that cannot pull container images, the rolling
update of add-ons needs to be coordinated in a more particular fashion.
This allows users of the KCP to opt out of kube-proxy management with a
similar mechanism to how they would opt out of CoreDNS management (#3023)
Similarly to #3023 we also see error messages when parsing the kube-proxy image name (`"vmware/kube-proxy:v1.16.7_vmware.1"`):
```
E0709 13:17:09.235042       1 controller.go:346] controllers/KubeadmControlPlane "msg"="failed to update kube-proxy daemonset" "error"="failed to parse image name: couldn't parse image name: repository name must be canonical" "cluster"="tkc3" "kubeadmControlPlane"="tkc3-control-plane" "namespace"="default"
```
**Which issue(s) this PR …
=> ✨ Provide a way to disable kube-proxy management in KCP via annotations

Makefile
An old version of `Golint-cli` is being used which causes lint errors when run as `fast=true` mode. It exits with non success code but no error. Running `lint-full` solves this problem.
Removing the `lint` target.
Fixes #3304
=> 🐛 Removing lint fast=true target as its failing to lint

cmd/clusterctl/client/yamlprocessor/simple_processor.go, cmd/clusterctl/client/yamlprocessor/simple_processor_test.go, docs/book/src/clusterctl/provider-contract.md, go.mod, go.sum, test/infrastructure/docker/go.sum
This PR introduces support for default variables in the SimpleProcessor. It leverages the library https://github.com/drone/envsubst to parse and evaluate the yaml.
Since the library by default doesn't support `${ VAR}, ${ VAR }, ${VAR }, ${VA$R}`, we've added backward compatibility for the first three, **however we've dropped support for `${VA$R}`**.
Fixes #3189
=> ✨ Template defaults with envsubst

config/ci/manager/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/manager/manager_auth_proxy_patch.yaml, config/webhook/manager_webhook_patch.yaml, test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
This PR is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/3270#issuecomment-656349748
It introduces two optional variables in core-components.yaml that can be used to toggle CAPI feature gates for experimental features.
/cc @sedefsavas
=> 🌱 Add variables for featuregates

bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, bootstrap/kubeadm/types/v1beta1/types.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Opens up the KCP validating webhook to allow for mutation to `.spec.kubeadmConfigSpec.initConfiguration.nodeRegistration` and `.spec.kubeadmConfigSpec.joinConfiguration.nodeRegistration`
Fixes #3323
=> ✨Allow KCP users to mutate node registration options

docs/book/src/tasks/healthcheck.md
Document to not create HealthCheck with overlapping selectors
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3058
=> 📖 Improve HealthCheck docs

test/infrastructure/docker/config/manager/manager.yaml
Adds a toleration to the CAPD manager deployment so that it can run on control plane nodes. I was trying to self-host a cluster with CAPD and was surprised to see that this deployment's pods were unable to be scheduled because it doesn't tolerate running on the control plane nodes.
=> 🌱  Add CAPD control plane toleration

Tiltfile
As a developer I want to be able to define multiple Tilt providers per repository.
This is useful for developing CAPI providers that include multiple operators.
**Anything else you would like to add:**
My CAPI `tilt-settings.json` looks like this:
```
{
"default_registry": "localhost:5000",
"provider_repos": ["../cluster-api-provider-aws"],
"enable_providers": ["aws", "eks-bootstrap"],
"kustomize_substitutions": {
"AWS_B64ENCODED_CREDENTIALS": "<REDACTED>",
"EXP_MACHINE_POOL:=false": "false",
"EXP_CLUSTER_RESOURCE_SET:=false": "false"
}
}
```
And I tested two different CAPA `tilt-settings.json`:
```
{
"name": "aws",
"config": {
"image": "gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller",
"live_reload_deps": [
"main.go", "go.mod", …
```
=> ✨ Support a list of maps in tilt-settings

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Following up on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/653, we need to update the quickstart to include the new secret var.
/hold until CAPZ v0.4.6 release
Fixes #
=> 📖 Update CAPZ quickstart variables to include new AZURE_JSON_B64 secret

bootstrap/kubeadm/config/manager/manager.yaml, bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml, bootstrap/kubeadm/config/webhook/manager_webhook_patch.yaml
**What this PR does / why we need it**: Follow up on #3325, this adds the MachinePool feature gate var to the Kubeadm bootstrap provider as well since it is needed to enable exp feature MachinePool.
Fixes #
=> 🌱 Add MachinePool feature gate defaults to CABPK

Makefile, Tiltfile, docs/book/src/developer/tilt.md, hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go, test/infrastructure/docker/hack/tools/go.sum
Signed-off-by: Alexander Eldeib <alexeldeib@gmail.com>
Make tilt work with envsubst
Fixes #3326
=> 🌱 fix tilt with envsubst

docs/book/src/clusterctl/provider-contract.md
This PR updates clusterctl move documentation aligning it to changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/3243
=>  📖 improve clusterctl move doc

controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/util_test.go
Fix a problem that arises when KCP does not have a clusterConfiguration set, because we do a comparison of a cached version of the clusterConfiguration stored in a Machine annotation with the current clusterConfiguration. 
In this case the Machine has "null" as the value of the annotation, since the clusterConfiguration was nil. When this gets unmarshaled and compared with nil it returns false :-(
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3353
=> 🐛 KCP: fix problem in rollout detection logic when ClusterConfiguration is nil

Dockerfile, Makefile
Adds build variables to the `docker-build-x` make targets, so that images created through those will have correct version information.
Fixes #3368
=> 🌱 Add version ldflags to docker-build make targets

Tiltfile
Copy kustomize_substitutions into os.environ before calling kustomize +
envsubst to ensure the values are available to envsubst.
Fixes #3375
=> 🐛 Fix kustomize_substitutions

util/conditions/patch.go
Follow-up to #3377, it now prints the comparison between the latest version and the latest version.
/milestone v0.3.8
/assign @gab-satchi @ncdc
=> :seedling: Fix logging comparison between conditions patch

controllers/machinehealthcheck_controller.go
Right now MHC logs almost nothing on the `-v=0` log level. This adds a new message when a machine fails a health check and we are marking it for remediation. We [store information](https://github.com/benmoss/cluster-api/blob/c510161e2c2639a4c5e8a1683c34a016a1d236ac/controllers/machinehealthcheck_targets.go#L94-L158) about why the health check fails on the condition, so we can use that to surface the failure now. 
Also removes the "patching machine" log line from healthy machines, this is almost always useless in my experience.
=> 🌱  Log when and why a machine is marked for remediation

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go
While looking for RequeueAfterError usage, to see how we can deprecate
in a few places, stumbled upon this usage in KCP which is incorrect.
Returning a RequeueAfterError here has no effect because the caller does
not look at the error result, but instead reconciliation will go in
a backoff loop.
/assign @ncdc @detiber
=> :bug: KCP reconcileDelete should not use RequeueAfterError

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/upgrade_test.go
Related to #3370 and #3336, this PR removes the need for the now-deprecated RequeueAfterError from KCP's `reconcileHealth` method.
/milestone v0.3.8
/assign @ncdc @detiber 
/cc @Arvinderpal
=> 🌱 Remove RequeueAfterError usage from reconcileHealth

exp/addons/controllers/clusterresourceset_controller_test.go, exp/addons/controllers/clusterresourcesetbinding_controller.go, exp/addons/controllers/suite_test.go, main.go
This PR deletes ClusterResourceSetBinding when the owner cluster is deleted.
This is not garbage collected because both Cluster and ClusterResourceSet are the owners of ClusterResourceSetBinding but when any of them is deleted, ClusterResourceSetBinding should also be deleted.
Fixes #3357
=> 🐛 Delete ClusterResourceSetBinding when cluster is deleted.

errors/controllers.go
Related to the effort outlined in #3370, this PR adds a deprecation notice for the struct and helper functions.
/milestone v0.3.8
/assign @ncdc @detiber
=> :seedling: Add deprecation notice for RequeueAfterError

test/framework/clusterresourceset_helpers.go
Attempts to fix a race condition in the test framework related to ClusterResourceSetBindings
=> :seedling: [e2e framework] Fix race condition when testing ClusterResourceSetBinding

hack/verify-shellcheck.sh
Updates hack/verify-shellcheck.sh to install shellcheck from the new URL. See https://github.com/koalaman/shellcheck/issues/1871 for more info.
=> 🌱  Fix shellcheck install script

cmd/clusterctl/client/repository/repository_local.go
This PR wraps the error from `os.Stat` when trying to read a file locally. This can be used to improve debugging and troubleshooting. We do this a few lines below for `ioutil.ReadFile`
N/A
=> 🐛 Wrap error so as to not lose context

cmd/clusterctl/client/repository/metadata_client.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
**What this PR does / why we need it**: This PR bumps the embedded metadata of CAPV to include 0.7
Fixes #
=> :seedling: add v0.7 to the embedded metadata

Dockerfile, Makefile, Tiltfile, cmd/example-provider/Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile
There have been bug and CVE fixed in the latest versions. Let's update the Go version before we release v0.3.8.
/milestone v0.3.8
/assign @ncdc @wfernandes
=> :seedling: Update to Go 1.13.14

cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/cmd/generate.go, cmd/clusterctl/cmd/generate_yaml.go, cmd/clusterctl/cmd/generate_yaml_test.go, docs/book/src/SUMMARY.md, docs/book/src/clusterctl/commands/commands.md, docs/book/src/clusterctl/commands/generate-yaml.md, docs/book/src/clusterctl/overview.md
Currently, this only works with --from flag since that is the most generic and can be used for any template.
It also provides the --list-variables flag to list variables present in the template
This PR adds the `generate yaml` subcommand. It works as follows:
```bash
clusterctl generate yaml --from <file-path>
clusterctl generate yaml --from <file-path> --list-variables
```
Fixes #3379
=> 🌱 Add generate yaml subcommand to clusterctl

exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourceset_controller_test.go, exp/addons/controllers/predicates/resource_predicates.go
This PR adds watch on ClusterResourceSet resources (ConfigMaps/Secrets), so that for the resources that is missing during `Apply` will be reconciled on creation or update of resources.
One down side of this is everytime a resource is created/updated, all CRS objects in the same namespace will be reconciled. Although CRS is added as owner of the resources during CRS creation since newly created resources were not there, they will not have owner refs and we cannot use owner references to get only the CRSs that has the created resource.
Fixes …
=> 🌱Add watch for ClusterResourceSet resources

docs/book/src/clusterctl/provider-contract.md
This PR documents the side-effect of only updating the embedded metadata in clusterctl without providing a metadata.yaml in the provider release.
Fixes #3418
=> 📖 Add ux note for using embedded metadata in cluserctl

go.mod, go.sum, test/infrastructure/docker/go.mod, test/infrastructure/docker/go.sum
Seems this replace was removed upstream, so removing it here as well.
=> :seedling: Remove json-patch library replace

docs/book/src/clusterctl/commands/generate-yaml.md
Fixes broken link to envsubst in docs
Related to us disabling link checking in https://github.com/kubernetes-sigs/cluster-api/issues/2703
=> 🌱 Fix broken link

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go
Right now the MHC controller only checks if the MHC object itself or the Cluster is paused. It seems reasonable users would expect that pausing a machine would also pause remediation on it.
Fixes #3421
In #3108 I unintentionally changed the logic here to return when we encounter an error patching one of the machines, instead of the prior behavior of continuing to try to remediate all of the machines before returning an error collection. This also brings back that logic.
=> 🌱 MHC should not remediate paused machines

docs/proposals/20200602-machine-deletion-phase-hooks.md
Defines a set of annotations that can be applied to a machine which affect the
linear progress of a machine’s lifecycle after a machine has been marked for
deletion.  These annotations are optional and may be applied during machine
creation, sometime after machine creation by a user, or sometime after machine
creation by another controller or application.
=> 📖 CAEP: machine deletion phase hooks

cmd/clusterctl/internal/test/fake_objects.go
This PR fixes some flakes we are observing in ClusterResourceSet move tests, see e.g. https://github.com/kubernetes-sigs/cluster-api/pull/3337#issuecomment-669173651
=> 🐛 Fix CRS move test flakes

CONTRIBUTING.md, REVIEWING.md, docs/book/src/REVIEWING.md, docs/book/src/SUMMARY.md, docs/book/src/developer/testing.md
Cluster API maintainers would like to improve consistency and maintainability of tests, in order to support the future growth of the project, avoid regressions and improve the developer experience and the overall quality of the code base.
This PR kick off this work following discussion on https://github.com/kubernetes-sigs/cluster-api/issues/3287 with the goal to reach an agreement at the community level about the direction we want to take for improving tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3287
=> 📖 Define testing guidelines and standards

cmd/clusterctl/client/cluster/upgrader.go, cmd/clusterctl/client/config/provider.go, cmd/clusterctl/client/upgrade.go, cmd/clusterctl/client/upgrade_test.go
This PR ensures that the Watching Namespace for a provider is preserved when upgrading that provider via a custom plan. That is, if we do something like `clusterctl upgrade apply --management-group=foo/cluster-api --infrastructure foo/aws:v0.5.5`. 
Fixes #3413
=> 🐛 Include watching namespace for custom provider upgrades

docs/book/src/clusterctl/commands/upgrade.md
This PR improves the clusterctl upgrade docs by documenting how to upgrade a multi-tenant cluster where each provider instance was installed with different env variables
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2997
/cc @MaxRink
=> 📖 Document how to upgrade a multi-tenant cluster

cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/cluster/workload_cluster.go, cmd/clusterctl/client/cluster/workload_cluster_test.go, cmd/clusterctl/client/get_kubeconfig.go, cmd/clusterctl/client/get_kubeconfig_test.go, cmd/clusterctl/cmd/get.go, cmd/clusterctl/cmd/get_kubeconfig.go, cmd/clusterctl/internal/test/fake_proxy.go, docs/book/src/clusterctl/developers.md, docs/book/src/user/quick-start.md
This PR adds onto https://github.com/kubernetes-sigs/cluster-api/pull/3293. It adds on some tests and other feedback provided on the original PR.
I squashed Prankul's commits into one.
Fixes #2542
=> ✨ Add `get kubeconfig` clusterctl sub-command

test/framework/alltypes_helpers.go, test/framework/deployment_helpers.go
Pretty-prints the JSON representation of a deployment when `WaitForDeploymentsAvailable` fails an e2e test.
We use these framework methods downstream in CAPZ and could use more context when debugging e2e failures. I'd like to follow on by also printing relevant Kubernetes events in `DescribeFailedDeployment`, but wanted to keep this simple.
N/A, but see kubernetes-sigs/cluster-api-provider-azure#807
=> 🌱 [e2e] add debug output for deployment failures

cmd/clusterctl/client/cluster/upgrader_info.go, cmd/clusterctl/client/cluster/upgrader_test.go, cmd/clusterctl/client/repository/repository_github.go, cmd/clusterctl/client/repository/repository_github_test.go, cmd/clusterctl/client/repository/repository_local.go, cmd/clusterctl/client/repository/repository_local_test.go, cmd/clusterctl/internal/test/fake_github.go, docs/book/src/clusterctl/commands/init.md, docs/book/src/clusterctl/commands/upgrade.md
This PR skips pre-releases during a `clusterctl init` and during `clusterctl upgrade <plan|apply>`. That is, we ignore pre-releases except if explicitly declared.
Fixes #3435
=> 🌱 Clusterctl init ignore pre releases

util/predicates/cluster_predicates.go
The log entry for `ClusterCreateNotPaused` predicate when the cluster is paused reads that it is "not paused, blocking further processing". This PR simply removes the not.
=> 🐛 fix cluster create not paused when paused log entry

exp/api/v1alpha3/machinepool_webhook.go, exp/api/v1alpha3/machinepool_webhook_test.go
**What this PR does / why we need it**: These two fields are [documented as being defaulted](https://github.com/kubernetes-sigs/cluster-api/blob/master/exp/api/v1alpha3/machinepool_types.go#L39) but in reality, there were no defaults in place. Note: the default values match the machine deployment ones.
Fixes #
=> 🐛  Default MachinePool replicas and MinReadySeconds

docs/book/src/user/quick-start.md
Fixes the packet quickstart tab to work better with the default Calico Pod CIDR configuration
=> :book: Update Packet quickstart to better work with Calico CNI

Tiltfile
This PR updates the version of cert-manager used in the Tilfile to v0.16.0 (same installed by clusterctl after https://github.com/kubernetes-sigs/cluster-api/pull/3313 merged)
Additionally, the cert-manager version is now a variable that can be set in the `tilt-settings.yaml` file, so,  no code change are required to test older versions if required (tested with v0.11.0).
Finally, the code that verifies if cert-manager is properly working is now aligned to https://cert-manager.io/docs/installation/kubernetes/#verifying-the-installation (same used in clusterctl)
=> 🌱 Add hack to upgrade cert-manager in Tiltfile

docs/book/src/developer/architecture/controllers/control-plane.md
The Control Plane provider docs should list creation/management of the kubeconfig secret as a requirement for a ControlPlane provider implementation.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2778
=> 📖  Control Plane provider doc lists management of kubeconfig secret as a requirement

exp/api/v1alpha3/machinepool_types.go, exp/controllers/machinepool_controller_noderef.go, exp/controllers/machinepool_controller_phases.go, exp/controllers/machinepool_controller_phases_test.go, exp/controllers/machinepool_controller_test.go
**What this PR does / why we need it**: Adds a `ScalingUp` and a `ScalingDown` phase for MachinePool, to indicate when the MachinePool replica count is being increased and when it is being decreased. 
Eg:
```
$ k get mp                                       
NAME         REPLICAS   PHASE
vmss2-mp-0   2          Running
$ k scale mp vmss2-mp-0 --replicas 4        
machinepool.exp.cluster.x-k8s.io/vmss2-mp-0 scaled
$ k get mp   
NAME         REPLICAS   PHASE
vmss2-mp-0   2          ScalingUp
$ k scale mp vmss2-mp-0 --replicas 1
machinepool.exp.cluster.x-k8s.io/vmss2-mp-0 scaled
$ k get mp
NAME         REPLICAS   PHASE
vmss2-mp-0   2          ScalingDown
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> ✨  Set MachinePool phase to scaling when infra is scaling

docs/book/src/reference/versions.md
This PR documents version support for clusterctl
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3090
=> 📖  Document clusterctl version support

controllers/cluster_controller.go, controllers/cluster_controller_phases.go, controllers/cluster_controller_phases_test.go, controllers/cluster_controller_test.go, controllers/external/types.go, util/util.go
This PR further cleans the use of RequeueAfterError from our controllers.
Related to #3370
=> 🌱 Remove RequeueAfterError from cluster controller

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
we write the certificate files twice into cloud init, once as writeFiles and again as additionalFiles which get written back to writeFiles.
we also mutate the kubeadm config spec in place when converting contentFrom -> content. avoid doing that.
/hold
for some tests
=> 🐛 avoid in-place capbk mutation, duplicate files

exp/controllers/machinepool_controller.go, exp/controllers/machinepool_controller_noderef.go, exp/controllers/machinepool_controller_phases.go, exp/controllers/machinepool_controller_phases_test.go
**What this PR does / why we need it**: This PR cleans the use of RequeueAfterError from the MachinePool controller.
Depends on #3445 
/hold
Related to #3370
=> 🌱 Remove RequeueAfterError from machine pool controller

cmd/clusterctl/client/repository/repository_local.go
Authored-by: Gene Hynson <ghynson@vmware.com>
- This PR removes the `url.EscapedPath()` step from Windows local repositories. On Windows 10 versions >= 1803, Windows will no longer decode file paths. This causes a failure when clusterctl tries to read the providers if your Windows username has a space in it (e.g. `C:\Users\Gene Hynson\...`):
Fixes #3487 
**Testing**
I'm not exactly sure what's the best way to add automated tests for this change, since it would require setting `runtime.GOOS`. If anyone has suggestions, I'm all ears!
In terms of manual tests, I tested this on the latest version of Windows and on Mac - it works fine.
=> 🐛  Fixes issue with Windows, paths can't be escaped

cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/cert_manager_test.go, cmd/clusterctl/client/cluster/upgrader.go, cmd/clusterctl/client/upgrade.go, docs/book/src/clusterctl/commands/upgrade.md
This PR extends `clusterctl upgrade` in order to manage cert-manager upgrades before upgrading providers
This PR builds on top of https://github.com/kubernetes-sigs/cluster-api/pull/3313, which is not yet merged. In the meantime, please consider the latest commit only
=> 🌱 clusterctl upgrade cert manager before upgrading providers

test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml, test/infrastructure/docker/examples/simple-cluster.yaml
This PR updates the existing two CAPD examples to use `MachineDeployment` instead of individual `Machine` and bumps the K8S version in those examples from v1.14.2 to v1.18.6. 
Using `MachineDeployment` is generally recommended as of today and there are also people asking for `MachineDeployment` examples in #cluster-api channel. So it would be nice we could have our existing examples up to date.
=> 🌱 Update CAPD examples to use MachineDeployment

docs/book/src/user/quick-start.md
This PR documents how to use kubectl to get a kubeconfig file
Fixes #3509
=> 📖  document clusterctl get kubeconfig

cmd/clusterctl/client/repository/repository_github.go, cmd/clusterctl/client/repository/repository_github_test.go, cmd/clusterctl/client/repository/repository_local.go, cmd/clusterctl/client/repository/repository_local_test.go
This PR fixes a bug in clusterctl where, if a provider repo didn't have
*any* stable releases published, all releases were ignored and the init
failed. We now fall back to accepting prereleases if no stables are
found.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
Fixes #3496
=> :bug: [clusterctl] accept prereleases when no releases published

exp/addons/api/v1alpha3/clusterresourceset_types.go, exp/addons/api/v1alpha3/clusterresourcesetbinding_types.go, exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourceset_controller_test.go
This PR removes CRS from the CRSBinding `bindings` after CRS is deleted.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3453
=> 🐛Remove ClusterResourceSet from bindings on deletion

docs/proposals/20191030-machine-health-checking.md
The Cluster API includes an optional Machine Healthcheck Controller component that implements automated health checking capability, however it doesn’t offer any other remediation than replacing the underlying infrastructures. 
Environments consisting of hardware based clusters are significantly slower to (re)provision unhealthy machines, so they have a need for a remediation flow that includes at least one attempt at power-cycling unhealthy nodes.
Other environments and vendors also have specific remediation requirements, such as KCP, so there is a need to provide a generic mechanism for implementing custom remediation logic.
Fixes #2846
=> 📖 External Remediation Proposal

api/v1alpha3/machinedeployment_types.go, config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Reconcile the fields printed between these two types to keep a
consistent user experience between machines and control plane.
**before**
```
kubectl get kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
NAME                READY   INITIALIZED   REPLICAS   READY REPLICAS   UPDATED REPLICAS   UNAVAILABLE REPLICAS
ivy-control-plane   true    true          1          1                1
```
**after**
```
NAME                INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE
ivy-control-plane   true          true                   1          1       1
```
**before**
```
kubectl get machinedeployments.cluster.x-k8s.io
NAME       PHASE     REPLICAS   AVAILABLE   READY
ivy-md-0   Running   3          3           3
```
**after** …
=> 🌱, Align print columns between machinedeployment and kubeadmcontrolplanes

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/control_plane.go, util/secret/certificates.go, util/secret/certificates_test.go
This PR makes KCP supporting external etcd. While investigating this issue I discovered that the CAPBK support for external etcd is broken for joining control-planes ([original PR](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/260)) because we are not managing a flexible list of certificates [here](https://github.com/kubernetes-sigs/cluster-api/blob/5f0a49e0fcf2a1cb90b54553e7836600e571aae6/util/secret/certificates.go#L115-L138).
Now this should be fixed, but in order to get this working we are preserving the ClusterConfiguration in all the KubeadmConfig generated by KCP, and this is a kind of duplicate of the machine annotation recently added.
I'm opening an issue to sort out a common approach. 
**Which issue(s) this …
=> 🐛 Make KCP supporting external etcd

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
This PR is needed to disallow users from downgrading the control plane versions as well as skipping minor versions during upgrades.
Fixes #2578
=> 🐛 Performs KCP version check on control plane update

controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/suite_test.go, test/helpers/envtest.go, util/certs/certs.go, util/certs/certs_test.go
This PR adds a test for GetWorkloadCluster method. It uses **envtest** since we are trying to move away from using `fakeClient`.
Fixes #3525
=> 🌱 Add get workload cluster test

controllers/machinehealthcheck_controller.go
This PR adds some cleanup in machinehealthcheck controller, to help better seeing the test issues.
It is useful for webhooks tests in this issue [3209](https://github.com/kubernetes-sigs/cluster-api/pull/3209)
=> :seedling: mhc: Ensure log output when returning errors to controller runtime

Makefile, api/v1alpha3/machinehealthcheck_webhook.go, controllers/cluster_controller_test.go, controllers/machinedeployment_controller_test.go, controllers/machinehealthcheck_controller_test.go, controllers/suite_test.go, exp/addons/controllers/clusterresourceset_controller_test.go, go.mod, go.sum, test/helpers/envtest.go, test/infrastructure/docker/go.sum, util/patch/patch_test.go
This PR is to enable webhooks in envtest 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2788
=> Enable webhooks in envtest

docs/book/src/user/quick-start.md
Fixes the link to the docker provider install instructions in the quick start guide. Looks like this was broken in https://github.com/kubernetes-sigs/cluster-api/pull/3003.
=> 🌱 Fix link to docker-provider

api/v1alpha3/machine_types.go, controllers/machine_controller.go, docs/proposals/20200602-machine-deletion-phase-hooks.md, util/annotations/helpers.go
Implements Deletion Lifecycle Hooks: https://github.com/kubernetes-sigs/cluster-api/pull/3132
=> ✨ Implement deletion lifecycle hooks

cmd/clusterctl/cmd/root.go, cmd/clusterctl/cmd/version_checker.go, cmd/clusterctl/cmd/version_checker_test.go
This PR allows clusterctl to prompt the user if it detects that the version being used is different from the latest available release. If the clusterctl version being used is either older or a dev release compared to the latest available release, it will print out a message to the terminal via os.Stderr. The version check happens on any sub-command of clusterctl.
An example of the output printed is:
```shell
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.8-50-352a3a9d8b5430-dirty", GitCommit:"352a3a9d8b543078d194d80a34a2268652b314a0", GitTreeState:"dirty", BuildDate:"2020-08-13T20:01:57Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"darwin/amd64"}
Using configuration …
```
=> ✨ Clusterctl version check

controlplane/kubeadm/internal/etcd/fake/client.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go
This PR builds on top of the work done in https://github.com/kubernetes-sigs/cluster-api/pull/3350. It adds tests for ReconcileEtcdMembers using envtest. 
**PR #3350 should be merged in before this one.**
Look at the last commit of this PR.
Fixes #3526
=> 🌱 Add test reconcile etcd members

api/v1alpha3/condition_consts.go, controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machine_controller_test.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/status.go, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go, util/conditions/getter.go, util/conditions/getter_test.go, util/conditions/merge_strategies.go, util/conditions/merge_strategies_test.go
This PR adds conditions for providing evidence of the delete workflow for CAPI* and CAPD
*experimental objects are not included in this PR
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3383
=> 🌱 Add conditions for deletion workflows

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
Something I noticed in https://github.com/kubernetes-sigs/cluster-api/pull/3543, the error message from the library isn't being reported, this fixes that issue.
/assign @CecileRobertMichon
=> :seedling: Expose CoreDNS errors to users when validation fails

api/v1alpha3/cluster_types.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, controllers/cluster_controller_phases.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go
Current Endpoint.IsZero() check will allow empty Host with non-empty Port to pass the check (vice versa). This will cause issue if Infra provider have partial endpoint information with either of them is empty. The specific case we saw is with CAPV when user need to manually configure endpoint for kube-vip based HA.  
Add IsValid() when both host and port are non-zero. Change controllers to use IsValid() to decide whether to proceed or keep waiting.
=> 🐛 add APIEndpoint IsValid() when both host and port are non-zero value

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/scale_test.go
The initial error returned for an etcd health check gets overwritten and is never logged.
=> 🐛 Ensure that etcd health check errors are logged in KCP

test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
This PR updates the Kubernetes version used in e2e tests from 1.18.2 to 1.19.0. Also updates etcd and CoreDNS versions.
Fixes #
=> 🌱Update e2e Kubernetes versions

OWNERS
Adds a comment to OWNERS file that points folks to OWNERS_ALIASES file for a list of members names. Aims to provides more clarity to folks looking through the owner's file and how to find out members of an alias.
=> 📖 point users to owners_aliases file

scripts/ci-e2e.sh, test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
Bump CI scripts and config to cert-manager v0.16.1
=> 🌱 Bump cert-manager version on CI

test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
We recently upgraded e2e tests Kubernetes version to 1.19.0 but due to some changes in that version of Kubernetes, tests were failing. 
Before upgrading tests, a fix should go in, copying the discussion on slack (https://kubernetes.slack.com/archives/C8TSNPY4T/p1598899864038100):
```
ncdc  1 hour ago
In Kubernetes 1.19.0, the certificates API (which does CertificateSigningRequests for node bootstrapping, among other things) introduced version v1. The kube-controller-manager switched to only speaking v1 of this API.
If you have a control plane with a load balancer in front, it is possible/likely that during an upgrade from 1.18 to 1.19, the 1.18 kube-controller-manager will be removed (as part of deleting one of the old machines), and the 1.19 …
```
=> 🌱[e2e] Revert e2e test Kubernetes version to 1.18.2

api/v1alpha3/machine_types.go, config/crd/bases/cluster.x-k8s.io_machines.yaml, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
This PR adds `Version` as print column on Machines and KCP, which was useful today during debugging.
=> :seedling: Add Version print column to Machine and KCP

scripts/ci-e2e.sh
pre-pull the two kind images we are using in CI so we can remove another variable (docker hub speed) out of the GINKO run
=> 🌱 pre-pull kind images on CI

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
See https://kubernetes.slack.com/archives/C8TSNPY4T/p1598899864038100 for more information, Cluster API v0.3.9 won't support upgrading directly to v1.19.0
=> :warning: Disallow KubeadmControlPlane upgrades to v1.19.0

api/v1alpha3/condition_consts.go
This PR adds the `DeletingFailedReason` that can be useful for providers implementing conditions for the delete workflow.
=> 🌱 Add deleting failure reason

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
This has been useful today during debugging.
=> :seedling: Enable KCP kubeadmConfigSpec.verbosity modifications

scripts/ci-e2e.sh
Align to changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/3563
=> 🌱 Pre-pull e2e images on CI (revert to v1.17/v1.18)

Makefile, Tiltfile
Fixes an issue where Tilt would use whatever Kustomize version was
available in the user's PATH. Given that there have been breaking
changes in kustomize itself, we now instead build and use our own
version that's provided in hack/tools.
/assign @CecileRobertMichon @fabriziopandini @ncdc
=> :bug: Tilt should use a supported kustomize version

cmd/clusterctl/cmd/version_checker.go, cmd/clusterctl/cmd/version_checker_test.go
This PR fixes a bug that fails to write the version state file. Since v0.3.9, clusterctl has added the ability to check for the latest version, but an error occurs because the directory where the version state file will be created does not exist.
Fixes #3573
=> 🐛 Fix a bug that fails to write the version state file

cmd/clusterctl/README.md, exp/README.md, test/README.md
This PR is meant to document the *current development practices* that we've either agreed to in the past, or have been practicing. In an effort to be more explicit and openly document when and where breaking changes are allowed, and when we should be required to give notice to our users.
/assign @CecileRobertMichon @ncdc
=> :book: Document our compatibility notices for sub-folders

test/e2e/quick_start_test.go
Adding [PR-Blocking] label to Quick-Start e2e test which will be run in pre-submit tests.
cc @fabriziopandini @wfernandes
=> 🌱[e2e] Add PR-Blocking label to Quick-Start test

scripts/ci-e2e.sh
Delete GINKGO_FOCUS from ci-e2e.sh to avoid overriding it in prow scripts (https://github.com/kubernetes/test-infra/pull/19092).
=> 🌱[e2e] Delete GINKGO_FOCUS from ci-e2e.sh

cmd/clusterctl/client/alias.go, cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/cert_manager_test.go, cmd/clusterctl/client/upgrade.go, cmd/clusterctl/client/upgrade_test.go, cmd/clusterctl/cmd/upgrade_plan.go
When using 'clusterctl upgrade plan', we now notify the user if the
cert-manager version will be upgraded as part of 'clusterctl upgrade
apply'.
**Sample output**
```shell
$ clusterctl upgrade plan --config ~/.cluster-api/dev-repository/config.yaml
Checking cert-manager version...
Cert-Manager will be upgraded from "v0.11.0" to "v0.16.1"
Checking new release availability...
Management group: capi-system/cluster-api, latest release available for the v1alpha3 API Version of Cluster API (contract):
NAME                    NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm       capi-kubeadm-bootstrap-system       BootstrapProvider        v0.3.8            Already up to date …
```
=> ✨ Print upgrade notice for cert-manager

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Following the [CAPZ v0.4.8](https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v0.4.8) release, updating the quickstart to make the Azure instructions a bit slimmer, namely:
1) removes the SSH key var command which is now optional
2) removes cluster name to match other providers
3) removes extra information that is duplicated in the doc
Fixes #
=> 📖  Simplify Azure quickstart and remove optional variables

config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml, exp/api/v1alpha3/machinepool_types.go
This PR adds version print column for MachinePool
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3561
=> Add version print column for MachinePool

test/framework/clusterctl/clusterctl_helpers.go
Parity with Cluster API 0.3.8
Fixes #3607
=> clusterctl test framework: Restore CNIManifestPath to struct for API compat

cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/common.go, cmd/clusterctl/client/config.go, cmd/clusterctl/client/delete.go, cmd/clusterctl/client/get_kubeconfig.go, cmd/clusterctl/client/init.go, cmd/clusterctl/client/move.go, cmd/clusterctl/client/upgrade.go
:bug:
Allows to inject custom repository interfaces for providers by making fields in RepositoryClientFactoryInput and ClusterClientFactoryInput public.
This will allow external libraries read the inputs and pass them further to create a client or implement custom based clients. Please see related issue for more details.
Fixes #3584
=> Allow custom providers in clusterctl client

test/framework/bootstrap/kind_util.go
This PR displays the path of the kubeconfig file for the bootstrap cluster for E2e tests. It makes it easier to debug provider controllers if it fails to initialize the bootstrap cluster.
```
STEP: Setting up the bootstrap cluster
INFO: Creating a kind cluster with name "test-6lnn2w"
INFO: The kubeconfig file for the kind cluster is /var/folders/d3/lsp0h4wx7wsd4_yrymm9nnm80000gn/T/e2e-kind675530722
STEP: Initializing the bootstrap cluster
```
Fixes #
=> 🌱 e2e: Display path of the kubeconfig file for the bootstrap cluster

test/infrastructure/docker/docker/util.go
This PR fixes `\"sethostname: invalid argument\""` when the generated container name is too long
It does so by avoiding to repeat the cluster name if it is already included in the machine name
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3599
=> 🌱 Fix the E2E MHC remediation errors

cmd/clusterctl/client/cluster/objectgraph.go
it's hard to know what secret is ignored when the `clusterctl move` move objects from original cluster to target cluster.. add this log to indicate what happen
Fixes #
=> Add log to indicate the secret is ignored

Tiltfile, docs/book/src/developer/tilt.md
This comes from a need in Metal3. The CAPM3 provider contains for now three controllers, each of them in a separate repository. Only the main repository (the CAPM3 controller) contains a ./config folder that should be applied, and that includes the the two other controllers. It is currently possible to develop CAPM3 using CAPI tiltfile but that limits us to working with CAPM3 only, as the two other controllers repositories are not considered. If the Tiltfile was not trying to build the ./config folder of all providers, those two other repositories could be given as additional providers to allow development there too. In addition, when the provider is not built using Kubebuilder, but an old version of operator-sdk for example, the main.go file is not …
=> 🌱 Tiltfile: Parameterize kustomize and main.go for providers

cmd/clusterctl/client/config.go
Looks like the message got copy-pasted from about ten lines down, resulting in a confusing report to the user.
=> 🌱 Fix message for clusterctl EnsureCustomResourceDefinitions failure

controlplane/kubeadm/controllers/controller.go
Before this change the log line says `err={}`.
Probably the logging implementation should be changed to fix this more generically: if someone points out where that code lives I could take a look.
=> 🐛 Improve logging for workload connection error

util/util.go
Eliminate an unnecessary DeepCopy for CRDs - we only ever read them, and
they're already deep copied as part of the List() call from the cached
reader.
Part of #3609 
Fixes #
=> 🌱 Eliminate extra DeepCopy for CRDs

util/predicates/cluster_predicates.go, util/predicates/generic_predicates.go
Move log declarations inside function definitions to try to minimize
them escaping to the heap.
Part of #3609 
Fixes #
=> 🌱 Predicates: move log delcarations inside closures

cmd/clusterctl/client/config/reader_viper.go, cmd/clusterctl/client/config/reader_viper_test.go, cmd/clusterctl/cmd/root.go, cmd/clusterctl/cmd/version_checker.go
Add option to use the clusterctl configuration from a remote location like stored in some github/gitlab repo.
usage:
```
$ clusterctl init --infrastructure aws --config https://raw.githubusercontent.com/cpanato/testing-ghactions/master/clusterctl.yaml
$ clusterctl config cluster test --kubernetes-version 1.18.9 --config  https://raw.githubusercontent.com/cpanato/testing-ghactions/master/clusterctl.yaml 
```
/hold Will add tests for that.
Opening to get feedback
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3099
/cc @vincepri @wfernandes
=> ✨  clusterctl: add option to use configuration file in remote locations

cmd/clusterctl/hack/create-local-repository.py
The original code doesn't work under Python 3, and it seems reasonable to write text (yaml) files in the native format of the system you are running on.
Fixes #3601
=> 🌱Have hack/create-local-repository.py write yaml files in native text format

controllers/cluster_controller.go, controllers/cluster_controller_phases.go, controllers/external/testing.go, controllers/machine_controller.go, controllers/machine_controller_phases.go, controllers/machinedeployment_controller.go, controllers/machineset_controller.go, go.mod, go.sum, test/infrastructure/docker/go.sum, util/conversion/conversion.go, util/util.go
=> ⚠️ Use metadata-only client when retrieving CRDs

controllers/remote/cluster_cache.go
This PR switches the RESTMapper used in remote cluster caches to use a more efficient delegating cached one. By default `NewDynamicRESTMapper` calls https://github.com/kubernetes-sigs/controller-runtime/blob/d6829e9c4db802eb4d5703d22c6cd87e8bbf91da/pkg/client/apiutil/dynamicrestmapper.go#L109-L114
which creates a new RESTMapper with the group resources discovered from the client immediately.
Given that for remote clients we don't need to know all the resources available on every client before using them, using a deferred cached client seems the most straightforward way to reduce the amount of memory pressure seen in #3609 
/assign @ncdc @fabriziopandini
=> 🌱 Reuse the same RESTMapper for cache and client 

util/patch/patch.go, util/patch/utils.go, util/patch/utils_test.go
When using the patch helper to patch objects, we perform lots of
DeepCopy for safety purposes. After giving a closer look, it seems we
can definitely save one deep copy when the patch helper is created and
when Patch() is invoked by checking if the incoming object is
unstructured or not.
The deep copy was previously performed because the unstructured coverter
in the runtime package returns the inner map of an unstructured object
instead of making it a copy (this isn't a bug, it's how it's meant to be
used).
=> :seedling: Save a DeepCopy when patching typed objects

cmd/clusterctl/client/delete.go, cmd/clusterctl/client/delete_test.go, cmd/clusterctl/cmd/delete.go
Clusterctl delete currently would break out of loop after finding one provider to delete and only delete that provider. The cli has grown to provide flags for core, bootstrap and controlplane providers along with infrastructure. With these changes, any combination of those providers can be deleted. 
Fixes #3558
=> 🌱 Allows delelting multiple providers at once

util/util.go, util/util_test.go
Fixes an issue where a v1alpha2 MachineSet that has an owner reference with an older API version, after being reconciled with a v1alpha3 controller, thinks it doesn't have an owner.
/assign @ncdc
=> :bug: util.HasOwner should not compare with the API version

controllers/machine_controller.go
This PR adds DrainingSucceededCondition to the list of conditions owned by the machine controller, so we avoid conditions config due to stale reads
=> 🐛 Machine controller should have DrainingSucceededCondition as owned condition

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/cmd/config_repositories_test.go, docs/book/src/reference/providers.md
There's a new EKS bootstrap provider in CAPA and it should be a pre defined provider in `clusterctl`
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.6.0
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3620
=> :sparkles: new EKS bootstrap provider in clusterctl

test/e2e/kcp_adoption.go
This PR fixes a flake on kcp-adoption e2e test due to the code querying for object aggressively after apply
=> 🌱 e2e: Resolve flake: Wait for controlplane to be available on management cluster

cmd/clusterctl/cmd/completion.go, docs/book/src/SUMMARY.md, docs/book/src/clusterctl/commands/commands.md, docs/book/src/clusterctl/commands/completion.md
This PR implements the `clusterctl completion` command that outputs bash/zsh completion code. The `clusterctl completion command` implemented by this PR provides auto completion for subcommands and flags. The next PR will provide dynamic auto completion for arguments of `--kubeconfig-context`, etc.
You can use auto completion for the clusterctl command as follows:
```
brew install bash-completion
printf "\n# Bash completion support\nsource $(brew --prefix)/etc/bash_completion\n" >> $HOME/.bash_profile
source $HOME/.bash_profile
source <(clusterctl completion bash)
source <(clusterctl completion zsh)
```
This code is based on the `kubectl completion` and` kubeadm completion` commands.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> ✨ Implement "clusterctl completion" command

test/e2e/self_hosted.go
This PR aims to fix self-hosted flakes by ensuring that mhc is not run during this test and by adding two delay in order to avoid doing move too aggressively.
In order to make this happen the entire management of cluster templates was re-architected so:
- cluster templates for tests are now generated from a set composable bases
- MHC-remediation has a new dedicated template
- all the other templates are without MHC
- also, in order to simplify things, this PR drops the distinction between CI and DEV test config
On top of that, this PR includes, a set of nits for improving test logs (mostly uppercase)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3589
=> 🌱 Fix self-hosted flakes in E2E tests

docs/book/src/reference/providers.md
This docs PR adds a reference to the [AzureStackHCI infrastructure provider](https://github.com/microsoft/cluster-api-provider-azurestackhci) to the list of providers in the CAPI book.
Fixes #
=> :book: added AzureStackHCI infrastructure provider to list of providers in the CAPI book

docs/book/src/SUMMARY.md, docs/book/src/clusterctl/commands/commands.md, docs/book/src/clusterctl/commands/get-kubeconfig.md, docs/book/src/clusterctl/overview.md, docs/book/src/user/quick-start.md
:book:
**What this PR does / why we need it**: Adds documentation clusterctl get kubeconfig command
Fixes #3535
/cc @prankul88 @fabriziopandini  @wfernandes
=> Issue 3535: clusterctl get kubeconfig docs added

controllers/machinehealthcheck_controller.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_healthcheck_test.go, controllers/remote/cluster_cache_reconciler.go, controllers/remote/cluster_cache_reconciler_test.go, controllers/remote/cluster_cache_tracker_test.go, controllers/remote/stoppable_cache.go
Switch to a single lock in ClusterCacheTracker to eliminate possible
deadlocks when simultaneously deleted & recreating a client/cache for
the same cluster.
Note, with this change, ClusterCacheTracker's WatchInput has a new required field - Name.
=> ⚠️ Eliminate possible deadlocks in ClusterCacheTracker

util/patch/patch.go, util/patch/patch_test.go, util/patch/utils.go, util/patch/utils_test.go
This PR reshuffles the code in a way that avoids copying the
unstructured objects first and then removing un-needed parameters from
the final object.
With these changes we opt to operate a shallow copy of the unstructured
objects with only the keys that are of interest, and then covert these
back to the actual object.
=> :seedling: Save a DeepCopy when calculating patches in Patch helper

test/e2e/config/docker.yaml
Still trying to get rid of e2e failures in the self-hosted test...
=> 🌱 Increase timeout to fix self-hosting flakes

cmd/clusterctl/hack/create-local-repository.py
This PR fixes a file write issue in create-local-repository.py which is detected during component upgrade using clusterctl.
```
Traceback (most recent call last):
File "cmd/clusterctl/hack/create-local-repository.py", line 130, in write_local_repository
f.write(components_yaml)
TypeError: write() argument must be str, not bytes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "cmd/clusterctl/hack/create-local-repository.py", line 241, in
repos = list(create_local_repositories())
File "cmd/clusterctl/hack/create-local-repository.py", line 162, in create_local_repositories
components_path = write_local_repository(provider, next_version, components_file, …
```
=> 🌱 Fix yaml file write issue in create-local-repository.py

docs/book/util-embed.sh, docs/book/util-releaselink.sh, docs/book/util-tabulate.sh
Attempts to fix the book build
Fixes #3658
=> :book: default GOPROXY if not set when building mdbook preprocessors

test/e2e/data/infrastructure-docker/bases/cluster-with-kcp.yaml
This PR fixes a flake in self-hosting failing when CAPD controller gets scheduler on the control-plane nodes.
Those nodes were is missing the mounts for the docker socket, so CAPD was falling to reconcile existing machines after move.
=> 🐛 Fix E2E self-hosting E2E test by adding docker mount to control-plane nodes

docs/proposals/20191017-kubeadm-based-control-plane.md
This PR updates the KCP document by introducing support for automatic remediation of unhealthy control-plane machines.
Kudos and credits to @benmoss who kicked off this effort and laid the ground for this PR with https://docs.google.com/document/d/1hJza3X-XbVV_yczB5N6vXbl_97D0bOVQ0OwGovcnth0/edit
Rif https://github.com/kubernetes-sigs/cluster-api/issues/2976
=> 📖 KCP remediation proposal

controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_targets.go, controllers/machinehealthcheck_targets_test.go, controllers/remote/suite_test.go, controllers/suite_test.go, test/helpers/envtest.go
This PR refactors some flaky MHC tests. It is moving us away from Ginkgo to vanilla Go test with envtest.
Fixes #3539 
**NOTES**
- There are currently three tests that have been marked with `t.Skip`. As of now, they seem to be the most flaky (on my machine). Also there is an opportunity to refactor them using conditions. See #3026 for more info. The refactor of these tests can be done in separate PRs if not part of the work for #3026.
- There are still Ginkgo tests in the `controllers` package. We should refactor those tests as well, so that we can have more consistent tests. This can be done in …
=> 🌱  Refactor MHC tests

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
Removes the step counter from the ready condition summary of KubeadmConfig 
Fixes #3679
=> ✨ Removes step counter from kubeadmconfig ready condition

cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/objectgraph.go
add a virtual node checker , so that we can remove the TODO in mover function
Fixes #
=> 🌱 Clusterctl now logs when objects aren't moved

util/conditions/patch.go, util/patch/options.go, util/patch/patch.go, util/patch/patch_test.go
This PR adds support for an option in the patch helper that allows controllers to force-overwrite conditions in case of a conflict.
This option should only be used in owning controllers, for example the Machine controller can set it when patching machines. While nothing will stop a different controller from using this option on non-owned objects, this is true as well if folks aren't using our patch helper.
/assign @ncdc @fabriziopandini
=> :seedling: Support patch ForceOverwriteConditions option

test/e2e/self_hosted.go, test/framework/bootstrap/kind_util.go
Right now if the e2e's fail while setting up the kind cluster, it gets orphaned on my machine. I didn't know why I was always failing to run the e2es using the CAPD config, but today was the day I decided to track it down. It was because of a missing Docker image, so I added in better error handling for surfacing Docker CLI output on `LoadImage`.
@fabriziopandini
=> ⚠️  Cleanup kind cluster if it fails during e2e setup

docs/book/Makefile, docs/book/book.toml
Fixes https://master.cluster-api.sigs.k8s.io/
=> :book: Ensure correct make targets in order to build book

docs/book/src/user/quick-start.md
Fixes the link to CAPA prerequisites. It was broken in the shift in docs structure from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1947
Still trying to figure out why the `GITHUB_TOKEN` doesn't seem to prevent us from being rate-limited in  https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api#periodic%20docs%20link%20verification, but it is at least running now.
=> 🌱 Update broken link to CAPA prerequisites

controllers/machine_controller.go, controllers/machine_controller_test.go, docs/book/src/developer/architecture/controllers/control-plane.md, util/util.go, util/util_test.go
This PR allows the Machine controller to drain and delete Nodes when running under managed control planes.
Fixes #3631
=> 🐛 Fix node deletion under managed control planes

Makefile
/assign @fabriziopandini @ncdc 
This is a bug, I had to generate the development manifests manually because it wasn't referencing the correct makefile target
=> :bug: Fix Makefile target to clean-release-git

controllers/machine_controller.go, controllers/machine_controller_test.go
This patch switches the condition order for summary condition generation so that the InfrastructureReady gets precedence over BootstrapReady Condition.
Fixes #3678
=> ✨ Changes priority of infrastructure failures in machine summary condition

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/client/config_test.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/cmd/config_repositories_test.go
This adds the eks control plane provider to clusterctl. This is to enable users to install the provider using `clusterctl init`. The EKS Control Plane has been split into its own provider and will be avaiyable in the 0.6.1 release of CAPA.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1970
=> 🌱 feat: add EKS controlplane provider

util/conditions/getter.go, util/conditions/getter_test.go
Fix conditions counter in case of mismatching order of conditions between WithConditions and WithStepCounterIfOnly
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3739
=> Fix conditions counter in case of mismatching order of conditions between WithConditions and WithStepCounterIfOnly

cmd/clusterctl/hack/create-local-repository.py
The script `local-overrides.py` was renamed to `create-local-repository.py` in https://github.com/kubernetes-sigs/cluster-api/pull/3514 but its documentation still references the old name. This PR updates the references to avoid confusion.
=> 📖 Fix create-local-repository.py documentation

Dockerfile, Makefile, Tiltfile, go.mod, hack/ensure-go.sh, hack/tools/go.mod, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile, test/infrastructure/docker/go.mod, test/infrastructure/docker/hack/tools/go.mod
update to use go 1.15, K/k is already using go 1.15.2, so starting this PR to switch to use the same go version.
Please let me know if we need to update the jobs as well
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3322
=> ✨ go: update to use go 1.15

Tiltfile, docs/book/src/developer/tilt.md, hack/ensure-kubectl.sh, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev
Updates the kubectl version used and required to 1.19
=> :seedling: Update kubectl version to 1.19

bootstrap/kubeadm/main.go, controlplane/kubeadm/main.go
Removes the duplicated private newClientFunc that were dangling around
in multiple places, which were completely identical. Moves to
util.ManagerDelegatingClientFunc, which is a function that was
introduced a while ago and it has the same effect.
=> :seedling: Use util.ManagerDelegatingClientFunc in all managers

bootstrap/kubeadm/config/rbac/leader_election_role.yaml, config/ci/rbac/leader_election_role.yaml, config/rbac/leader_election_role.yaml, controlplane/kubeadm/config/rbac/leader_election_role.yaml, test/infrastructure/docker/config/rbac/leader_election_role.yaml
This change is in preparation for controller runtime new default leader
election in v0.7.x which uses configmapleases instead of plain
configmap.
=> :warning: Add required coordination/leases RBAC for v0.7 leader election

test/infrastructure/docker/config/webhook/manager_webhook_patch.yaml, test/infrastructure/docker/config/webhook/service.yaml, test/infrastructure/docker/main.go
Another change that came up during controller runtime v0.7
investigation, the port that the CAPD container was listening on was 443
instead of the widely used 9443 (all our controllers use this value).
Changes the container ports and hardcodes the port in the manager. If we
want to expose a flag we can do it separately.
=> :seedling: CAPD webhooks should use 9443 as port

util/patch/patch_test.go
This came up after updating to controller runtime v0.7, now tests
properly fail. I assume before the tests weren't failing because the
namespace got auto-created, although this isn't true anymore. Switch
everything to use the default namespace.
=> :bug: util/patch tests shouldn't use a non-existent namespace

controlplane/kubeadm/controllers/controller.go
This changes the client used to get the machines in a cluster, instead
of using a cached client which could lag behind when the cluster is
under stress or when there are network issues, it uses a live client
reader which causes the request to go directly to the API server.
/assign @sedefsavas @fabriziopandini 
/milestone v0.3.11
=> :bug: KubeadmControlPlane should use a live client when listing machines

controllers/machine_controller.go, controllers/machine_controller_noderef.go, controllers/machine_controller_phases.go, controllers/machine_controller_phases_test.go
This PR cleans the use of RequeueAfterError from Machine controllers.
Related to #3370
=> 🌱Remove RequeueAfterError from machine controller

docs/book/src/roadmap.md
Moves the roadmap item for the autoscaler scale from zero integration into the 0.4.0 section. It also updates the title to be more descriptive.
=> :book: move autoscaler scale from zero to 0.4.0 roadmap

CONTRIBUTING.md
/assign @ncdc @timothysc @fabriziopandini @neolit123 @CecileRobertMichon @detiber
=> 📖 Add release guidelines and policies to contributing guide

controllers/machine_controller.go, controllers/machine_controller_noderef.go, controllers/machine_controller_phases.go, controllers/machine_controller_phases_test.go, controlplane/kubeadm/controllers/controller.go, util/conditions/getter.go, util/conditions/getter_test.go
/assign @fabriziopandini @sedefsavas 
/milestone v0.3.11
=> :seedling: [0.3] Backport 3740, 3759, and 3723

.github/workflows/verify.yml
This PR adds a github action workflow that @DirectXMan12 introduced a week or so ago in controller-runtime and other repositories.
The bot checks that PR titles have an emoji, in line with our contributing guidelines and that the description has content
=> 🌱 Add github action to check PR contents

controllers/machine_controller.go, controllers/machine_controller_test.go
This patch adds the machine health check conditions while computing the machine ready condition summary
Fixes #3677
=> ✨ Adds machine health check conditions to Machine Ready condition

test/framework/kubernetesversions/template.go
=> :seedling: kubernetesversions: Add option to inject CI artifacts into a KubeadmConfig for a MachinePool

cmd/clusterctl/cmd/init.go
This PR updates `clusterctl init --help` which referenced command `config providers` which wasn't valid. Instead replaced it with `config repositories` command.
Fixes #3784
=> 🐛 Update `clusterctl init --help` command

controllers/machine_controller.go, controllers/machine_controller_test.go
This patch adds the MHC conditions while computing the machine ready condition summary. This was merged to the main branch, this is about backporting the fix to the v0.3 release series.
Fixes #3677
=>  ✨ Adds machine health check conditions to Machine Ready condition

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/cmd/config_repositories_test.go
This PR rename digitalocean infrastructure provider name from `do` to `digitalocean` to be matched with cluster-api-provider-digitalocean [manifests labels](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/e3dff364f06ad952e27d4c548eee998d18d49af7/config/kustomization.yaml#L3-L4) and [clusterctl-settings.json](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/master/clusterctl-settings.json)
Fixes #
/cc @kubernetes-sigs/cluster-api-provider-digitalocean-maintainers
=> :warning: infrastructure provider DigitaloOcean was renamed to digitalocean (previously do)

Tiltfile, tilt_modules/cert_manager/README.md, tilt_modules/cert_manager/Tiltfile, tilt_modules/extensions.json
:seedling: 
Updated Tiltfile to use cert manager extension to deploy cert manager
Linked to issue#3765
Uses https://github.com/tilt-dev/tilt-extensions/pull/90 to load and deploy cert manager
Fixes #3765
=> Use tilt cert_manager extension

api/v1alpha3/common_types.go, controllers/machine_controller.go, controllers/machine_controller_test.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go
This PR adds a watch on Node in Machine controller so that when a node changes, Machine reconcile is triggered.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3729
=> 🌱Add Node watch to Machine controller

cmd/clusterctl/client/config/providers_client.go, cmd/clusterctl/cmd/config_repositories_test.go
=> :warning: Infrastructure provider DigitalOcean was renamed to digitalocean (previously do)

test/infrastructure/docker/config/webhook/manager_webhook_patch.yaml, test/infrastructure/docker/config/webhook/service.yaml, test/infrastructure/docker/main.go
Backport of #3758
I am running into a problem since this landed that using `tilt up` from master ends up clashing with the deployment created by `clusterctl init --infrastructure docker`:
```
The Deployment "capd-controller-manager" is invalid: spec.template.spec.containers[1].ports[1].name: Duplicate value: "webhook-server"
```
This will just be a creature comfort to have consistency between clusterctl and tilt, at least when 0.3.11 comes out with this fix.
=> 🌱  0.3 Backport: CAPD webhooks should use 9443 as port

docs/proposals/20200804-windows-support.md
Add proposal for Windows support in CAPI and providers. Related to #2218
Fixes #
=> 📖 Windows Support CAEP

docs/book/src/user/quick-start.md
Removing the single quote from the copy/paste configuration. This works on bash, but with zsh requires the user to enable interactive comments (set -k). Without interactivecomments enabled, the terminal is waiting for the closing single quote and the paste fails.
=> 📖 remove single quote allows copy / paste to work with zsh

docs/book/src/user/quick-start.md
Adds required environment variables for Metal3 provider in quick-start page.
These required vars can be found in cluster-api-provider-metal3 getting-started [page](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/getting-started.md#environment-variables) and also mentioned in the [release note](https://github.com/metal3-io/cluster-api-provider-metal3/releases).
=> 📖 Update required configurations for Metal³ provider

api/v1alpha3/common_types.go, controllers/machine_controller.go, controllers/machine_controller_test.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go
=> 🌱 Add Node watch to Machine controller

test/infrastructure/docker/docker/util.go
Right now if you encounter an error from CAPD running `docker list` you just get an unhelpful error like:
> failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=bmo --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1
This fixes the error to print the combined stdout/stderr from Docker as well so we get
> failed to list containers: failed to list nodes. Output: [Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster …
=> 🌱 Include docker output in error when we receive a non-zero exit code

docs/proposals/YYYYMMDD-template.md
This updates the proposal doc to properly link back to itself which broke when they became nested under `/docs/` and renamed to not include `proposal` in the name.
Fixes #3840
Signed-off-by: Chris Hein <me@chrishein.com>
=> 🐛 fixes link to proposal root to /docs/proposals/

docs/proposals/YYYYMMDD-template.md
Cherry picks doc updates for docs/proposal template links. _See references._
Ref #3840
Ref #3841
Signed-off-by: Chris Hein <me@chrishein.com>
=>  🐛 CHERRY PICK release-0.3 - fixes link to proposal root to /docs/proposals/

CONTRIBUTING.md, docs/proposals/YYYYMMDD-template.md
This change tries to define some basic rules and guidelines on how we
usually handle the proposal process and how it all connects to
pre-defined releases.
=> 📖 Define proposal guidelines and policies

Dockerfile, Makefile, Tiltfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile
Updated GO version from 1.15.2 to 1.15.3
Updates GO minor version to 1.15.3 (latest). 
Fixes #3849
=> :seedling: Update Go to 1.15.3

go.mod, go.sum, test/infrastructure/docker/go.sum
Upgrade corefile migration to v1.0.11 from v1.0.10
Fixes #3851
=> 🌱Upgrade corefile migration to v1.0.11

api/v1alpha3/condition_consts.go, bootstrap/kubeadm/api/v1alpha3/condition_consts.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/controllers/dockermachine_controller_test.go
Adds DockerMachine condition to report for the cluster control plane to be ready
Fixes #3683
=> ✨ Modifies DockerMachine condition status to report for control plane to be ready

go.mod, go.sum, test/infrastructure/docker/go.sum
(cherry picked from commit 205e25fc2d2a04ed6eb91a35b2917d386cd1d095)
Cherry picks "upgrade corefile migration to v1.0.11"
Ref #3853
=> 🌱CHERRY PICK release-0.3 - upgrade corefile migration to v1.0.11

api/v1alpha3/condition_consts.go, api/v1alpha3/machinehealthcheck_types.go, config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_status_matcher.go, util/conditions/matcher.go, util/conditions/matcher_test.go
Adds a new field to the MHC status called `remediationsAllowed` as proposed in #3371 
Fixes #3371
=> ✨  Add `remediationsAllowed` field to MHC status

test/e2e/e2e_suite_test.go, test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go
This PR makes the E2E framework to resolve CNI_RESOURCES without using env variables, thus avoiding problems when the CNI manifest is too long.
As a consequence of this change the call to `SetCNIEnvVar` should be now replaced by one (or more) calls to `createRepositoryInput.RegisterClusterResourceSetConfigMapTransformation`
Fixes #3797 
/hold
=> :warning: E2E test now resolve CNI_RESOURCES without using env variables

api/v1alpha3/condition_consts.go, controllers/machine_controller.go, controllers/machine_controller_noderef.go, controllers/machine_controller_noderef_test.go, controllers/machine_controller_phases_test.go, controllers/machine_controller_test.go, controllers/remote/cluster_cache.go
This PR adds a condition for Node health to Machine conditions that will be managed by Machine controller.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/3138
=> 🌱 Add Node related condition to Machine conditions

docs/proposals/20200330-spot-instances.md
This PR updates spot instances proposal with an interruptible label setting.
https://github.com/kubernetes-sigs/cluster-api/issues/3504
=> 📖Update spot instances proposal with interruptible label setting

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/remote/cluster_cache.go
With this change, MachineHealtchCheck tries to patch all unhealthy Machines and return at the end if there is error.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3712
=> 🌱 Avoid MachineHealthCheck to return early on patch errors

api/v1alpha4/condition_consts.go, bootstrap/kubeadm/api/v1alpha4/condition_consts.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/controllers/dockermachine_controller_test.go
Adds DockerMachine condition to report for the cluster control plane to be ready
Fixes #3859
=> ✨ Forward-port modifies DockerMachine condition status to report for control plane to be ready

util/conversion/conversion.go
Fuzz test was only testing hub-spoke-hub conversion.
This PR adds the reverse direction.
This test is expected to catch problems like this: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2059
Fixes #
=> 🌱 Add reverse conversion fuzz test

cmd/clusterctl/client/repository/components_client.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/client/repository/template_client.go
Changes the log lines printed by `clusterctl` to be more helpful when trying to create config overrides.
I was head-scratching why my CAPI override was working but my CAPBK wasn't:
```yaml
providers:
- name: "cluster-api"
url: "https://github.com/benmoss/cluster-api/releases/latest/core-components.yaml"
type: "CoreProvider"
- name: "bootstrap-kubeadm"
url: "https://github.com/benmoss/cluster-api/releases/latest/bootstrap-components.yaml"
type: "BootstrapProvider"
```
```
Fetching File="metadata.yaml" Provider="cluster-api" Version="v0.4.0-rc.1"
Fetching File="metadata.yaml" Provider="bootstrap-kubeadm" Version="v0.3.10"
```
I inferred from the log lines that the correct "name" for CAPBK would be `bootstrap-kubeadm`, since `cluster-api` was the right …
=> 🌱 Print provider type and name to match config file naming

Makefile, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, cmd/clusterctl/client/cluster/cert_manager_test.go, cmd/clusterctl/client/cluster/inventory.go, controllers/machine_controller_test.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, controlplane/kubeadm/internal/workload_cluster_rbac.go, exp/addons/controllers/clusterresourceset_controller.go, exp/controllers/machinepool_controller_test.go, go.mod, go.sum, test/framework/deployment_helpers.go, test/infrastructure/docker/Makefile, test/infrastructure/docker/go.mod, test/infrastructure/docker/go.sum, util/patch/patch.go
Pulls in some of the latest changes, including the metadata only watches, in preparation to reduce the amount of objects we cache.
/assign @ncdc
=> :seedling: Update controller-runtime to latest main version v0.7.0-alpha.5

Makefile, test/infrastructure/docker/Makefile
Fixes an issue that was discovered yesterday in #3893 when building our containers.
Fixes #
/milestone v0.3.11
=> :bug: Fix Makefile docker targets by prepulling required images

docs/book/src/clusterctl/commands/config-cluster.md
The leading colon was breaking the flag
The colon was breaking the `--infrastructure` flag
=> 📖 Remove leading colon between --infrastructure flag and provider

controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_reconciler_test.go
This PR adds supports for `GetLiveClient()` which users might want to use if they don't want to cache objects or if they need the most up to date information by querying the API Server directly.
Fixes #3891 
/assign @ncdc @fabriziopandini 
=> :sparkles: Add GetLiveClient() to ClusterCacheTracker

test/e2e/e2e_suite_test.go, test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go
Forward Ports #3846 
Fixes #3874
=> ⚠️ E2E framework resolves CNI_RESOURCES without using env vars

third_party/kubernetes-drain/drain.go
=>  🐛 Backport of high cpu usage during kubectl drain

api/v1alpha3/condition_consts.go, controllers/machine_controller.go, controllers/machinehealthcheck_controller.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/remediation.go, controlplane/kubeadm/controllers/remediation_test.go, controlplane/kubeadm/controllers/suite_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd.go
This PR adds to KCP support for remediating unhealthy machines according to KCP proposal changes defined by https://github.com/kubernetes-sigs/cluster-api/pull/3676
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2976
=> ✨ KCP remediates unhealthy machines

third_party/kubernetes-drain/drain.go
This is fix for #3911 for 0.3 release
Fixes #
/cc @vincepri
=> 🐛 Backport of high cpu usage during kubectl drain

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/internal/workload_cluster_etcd.go
This PR prevents `reconcileEtcdMember` to remove etcd members when etcd starts slowly.
A slow etcd member start, which happens when then the number of etcd members in the cluster grows, determine a longer time between member Add and the actual start of the etcd pod; If during this time `reconcileEtcdMember` was executed, the member got removed, because the member name for a member added but not yet started is empty and thus not matching any node.
This PR prevents this problem by ignoring etcd members without a name in `reconcileEtcdMember`; additional, as a further safeguard, `reconcileEtcdMember` is now a no-op in case there are machines still provisioning (without a noderef).
=> 🐛 Prevents reconcileEtcdMember to remove etcd members when etcd starts slowly

cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/cluster/cert_manager.go, cmd/clusterctl/client/cluster/cert_manager_test.go, cmd/clusterctl/client/cluster/client.go, cmd/clusterctl/client/init.go, cmd/clusterctl/client/upgrade.go
⚠️Fixes #3505
(*clusterClient).CertManager: changed from func() CertManagerClient to func() (CertManagerClient, error)
Client.CertManager: changed from func() CertManagerClient to func() (CertManagerClient, error)
=> ⚠️Remove hard code manifest version and hash

api/v1alpha3/condition_consts.go, api/v1alpha3/machinehealthcheck_types.go, api/v1alpha3/zz_generated.conversion.go, api/v1alpha4/condition_consts.go, api/v1alpha4/machinehealthcheck_types.go, config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_status_matcher_test.go, util/conditions/matcher.go, util/conditions/matcher_test.go
Adds a new field to the MHC status called remediationsAllowed as proposed in #3371
Forward porting the feature from the release-0.3 branch (#3372)
/cc @wfernandes @CecileRobertMichon
=> ✨ Add `remediationsAllowed` field to MHC status

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
**What this PR does / why we need it**: This PR relaxes validation and allows rotating ssh keys as part of a machine rollout
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3926
=> 🐛 Relax update validation to allow rotating ssh keys for KCP

test/infrastructure/docker/templates/cluster-template-development.yaml
This PR update the docker cluster template resources to v1alpha4 from v1alpha3 so that when users follow the [developer instructions](https://cluster-api.sigs.k8s.io/clusterctl/developers.html) to setup a CAPD environment, they don't get borked with errors such as 
```
root@master-1:~# kubectl apply -f capi-quickstart.yaml
dockercluster.infrastructure.cluster.x-k8s.io/capi-quickstart created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-control-plane created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-md-0 created
Error from server (InternalError): error when creating "capi-quickstart.yaml": Internal error occurred: conversion webhook for cluster.x-k8s.io/v1alpha3, Kind=Cluster failed: the server …
```
=> 🐛 Update the docker cluster template to reference v1alpha4 resources

util/patch/options.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #3935
=>  ✨ Un-deprecate OwnedConditions and WithOwnedConditions

docs/book/src/clusterctl/developers.md
This PR updates CAPD documentation to inform users that the k8s version they intend to use for their workload clusters needs to have a kindest/node docker image available.
Fixes #3795
=> 📖  Add note about k8s version when using CAPD

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/remote/cluster_cache.go
Forward ports #3713 
Fixes #3873
=> 🌱Avoid MachineHealtchCheck to return early on patch errors

bootstrap/kubeadm/config/manager/manager.yaml, bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml, bootstrap/kubeadm/config/webhook/manager_webhook_patch.yaml, bootstrap/kubeadm/main.go, config/ci/manager/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/manager/manager_auth_proxy_patch.yaml, config/webhook/manager_webhook_patch.yaml, controlplane/kubeadm/config/manager/manager.yaml, controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml, controlplane/kubeadm/config/webhook/manager_webhook_patch.yaml, controlplane/kubeadm/main.go, docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md, docs/book/src/reference/ports.md, docs/book/src/tasks/experimental-features/experimental-features.md, main.go, test/e2e/config/docker.yaml, test/framework/deployment_helpers.go, test/infrastructure/docker/config/manager/manager.yaml, test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml, test/infrastructure/docker/main.go
Changes the names of the flags to align with the k8s components
Below are the flags that have been altered: 
- `--metrics-addr` ==> `--metrics-bind-addr`
- `--leader-election` ==> `--leader-elect` (multiple flags beginning with the same prefix based around leader election)
Fixes #3924
=> ⚠️ Align flag names with upstream Kubernetes components

docs/book/src/user/quick-start.md
CAPO variables are updated due to [CAPO v0.3.3 release](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.3.3).
Fixes #
=> 📖 Update CAPO variables in Quick Start

docs/book/src/clusterctl/commands/generate-yaml.md
Fixes a small typo in clusterctl generate YAML command documentation.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
n/a
=> 🌱 Fix small typo in clusterctl command docs

cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/client/repository/metadata_client_test.go
This PR adds embedded metadata for v1alpha4 on CAPI, KCP, CAPBK, CAPD.
(spin-off of https://github.com/kubernetes-sigs/cluster-api/pull/3708)
=> 🌱 Add embedded metadata for v1alpha4 in clusterctl

scripts/fetch_ext_bins.sh
$ make test
$ ls -l /tmp/ | grep kubebuilder-tools
-rw-r--r--  1 root root 52352311 Nov 26 10:33 kubebuilder-tools-1.19.2-linux-amd64.tar.gz
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
Fixes #
=> 🐛 fetch_ext_bins should cleanup the temp file after downloading it

docs/book/src/tasks/healthcheck.md
Machines is meant to be plural in this context.
Fixes a typo in the book. It's not a critical fix as the meaning is probably clear without this.
=> :book: Fix a typo in the Healthcheck book.

bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml, cmd/clusterctl/client/init_test.go, cmd/clusterctl/internal/util/objs_test.go, config/ci/manager/manager_auth_proxy_patch.yaml, config/manager/manager_auth_proxy_patch.yaml, controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml, test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
Start using kube-rbac-proxy v0.5.0
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3743
=> ⚠️ Upgrade to kube-rbac-proxy:v0.5.0

controllers/machineset_delete_policy.go, controllers/machineset_delete_policy_test.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Remove deprecated DeleteNodeAnnotation annotation in v1alpha4
Fixes #3954
=> ⚠️ Remove deprecated DeleteNodeAnnotation annotation

api/v1alpha3/condition_consts.go, api/v1alpha4/condition_consts.go, controllers/machine_controller.go, controllers/machinehealthcheck_controller.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/remediation.go, controlplane/kubeadm/controllers/remediation_test.go, controlplane/kubeadm/controllers/suite_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/machinefilters/machine_filters.go, controlplane/kubeadm/internal/machinefilters/machine_filters_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd.go
This is a forward port of https://github.com/kubernetes-sigs/cluster-api/pull/3830
This PR adds to KCP support for remediating unhealthy machines according to KCP proposal changes defined by #3676
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3914
=> ✨ KCP remediation

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, bootstrap/kubeadm/controllers/token.go, bootstrap/util/configowner.go
**What this PR does / why we need it**: Each MachinePool has one KubeadmConfig which means all instances of a MachinePool share the same bootstrap data. Currently, new MachinePool replicas are unable to join the cluster after the initial bootstrap token has expired (token TTL is 15 minutes). 
This PR implements to behavior that was described in https://github.com/kubernetes-sigs/cluster-api/issues/3359#issuecomment-660154973, that is: When a KubeadmConfig is owned by a MachinePool, we create a new token if the current one is expiring in less than TTL/2 (7.5 minutes), and update the MachinePool's bootstrap data secret. If the token is not ready to be rotated, we requeue after TTL/3 (5 minutes), to ensure that we get to rotate before it expires. 
This means MachinePools will always have a …
=> 🐛 Rotate MachinePool bootstrap token

util/conversion/conversion.go
Skips spoke-hub-spoke conversion fuzz tests. 
Fixes #3923
=>  🐛 Skip spoke-hub-spoke conversion fuzz tests

controllers/machine_controller.go
The machine controller deleteNode method is wrapping the error before
returning, we're feeding the wrapped error to `apierrors.IsNotFound`
which returns false even if the Node has been already deleted.
/label cherry-pick-approved
=> :bug: Node deletion should check the cause of the error

api/v1alpha4/common_types.go, controllers/machine_controller.go, controllers/machine_controller_node_labels.go, controllers/machine_controller_node_labels_test.go
Transfer machine labels to the node. The use-case is described here https://github.com/kubernetes-sigs/cluster-api/issues/3504. 
The transfer of machine labels to the node is similar to setting `Noderef`. Important thing to mention is that only labels with `"cluster.x-k8s.io"` prefix are transferred.
This PR should help with implementing the termination handler for spot instances - https://github.com/kubernetes-sigs/cluster-api/pull/3528
Happy to hear what others think about this change.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3504
=> ✨ Label interruptible nodes

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/internal/etcd_client_generator.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_conditions.go, controlplane/kubeadm/internal/workload_cluster_conditions_test.go, controlplane/kubeadm/internal/workload_cluster_etcd.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go
These changes bring more safety when we reconcile the etcd members for
the given workload cluster.
To perform these changes, some modifications to the internal structs and
interfaces were needed. The etcd client generator now accepts node names
(as []string) instead of corev1.Node(s). This allows us to be more
flexible in how we pass in the list of nodes that we expect the etcd
member list to have.
The reconcileEtcdMembers method already waits for all machines to have
NodeRefs set before proceeding. While we check for that, now we also
collect all the names in a slice before passing it in to the inner
Workload struct method.
A NodeRef is assigned by the Machine controller as soon as that
Machine's …
=> :bug: KCP reconcileEtcdMembers should use its own NodeRefs

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, cmd/clusterctl/client/cluster/cert_manager.go, controllers/cluster_controller_phases.go, controllers/machine_controller.go, controllers/machinehealthcheck_targets.go, controlplane/kubeadm/controllers/helpers.go, exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourcesetbinding_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go, util/kubeconfig/kubeconfig.go
And when not using the client directly.
This PR targets only `release-0.3` because the underlying issue has been fixed in k/k upstream.
/milestone v0.3.12
=> :bug: Properly check errors.Cause when checking with apierrors

Dockerfile, Makefile, cmd/example-provider/Dockerfile, docs/Dockerfile, hack/boilerplate/boilerplate.Dockerfile.txt, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Makefile
**What this PR does / why we need it**: port some improvements made in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1061, namely:
- specify the dockerfile experimental image version to avoid being impacted by potential future breaking changes
- cache go/pkg/mod
Fixes #
=> 🌱 Use 1.1 experimental dockerfile image and cache go/pkg/mod

CONTRIBUTING.md
This change relaxes and defines a bit more what can be backported and
how. After this change is merged, we'll allow both bug fixes and minor
(non-breaking) features to be backported if at least one or more
maintainers approves the cherry pick.
With these changes we aim to be more welcoming of changes to the current
stable branch instead of stopping the world until the next releases.
The only caveat is that backports that I'd like to highlight is that
backporting is an expensive operation. More often that not,
a cherry-picked commit requires another full review because changes are
usually not compatible.
Going forward, we won't allow PRs to target a release branch directly,
we'll always require changes to go in the main branch first, and only
after they've been merged, to backport them. …
=> :book: Relax our backporting guidelines and policies

controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go
If the KCP controller crashes (likely in a self managed scenario) while
other operations were in progress, at the next reconciliation loop the
scale down operation would be blocked if for example we were in the
middle of deleting etcd (which would also crash the api server)
Fixes #3978
/assign @ncdc 
We need to backport as well.
=> :bug: Scale down checks excludes machine about to be deleted

controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go
If the KCP controller crashes (likely in a self managed scenario) while
other operations were in progress, at the next reconciliation loop the
scale down operation would be blocked if for example we were in the
middle of deleting etcd (which would also crash the api server)
(cherry picked from commit a284134baba582cd8d7263b325e8e00e0594394a)
Backport of #3977
Fixes #
=> :bug: [0.3] Scale down checks excludes machine about to be deleted

.golangci.yml, bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go, bootstrap/kubeadm/main.go, bootstrap/util/configowner_test.go, cmd/clusterctl/internal/test/fake_proxy.go, controllers/cluster_controller_phases_test.go, controllers/machine_controller_noderef_test.go, controllers/machinedeployment_controller_test.go, controllers/machinehealthcheck_targets_test.go, controllers/machineset_controller_test.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_fake.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go, controlplane/kubeadm/internal/workload_cluster_test.go, controlplane/kubeadm/main.go, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, exp/addons/controllers/clusterresourceset_helpers_test.go, exp/controllers/machinepool_controller_noderef_test.go, go.mod, go.sum, main.go, test/helpers/client.go, test/helpers/envtest.go, test/infrastructure/docker/controllers/dockermachine_controller_test.go, test/infrastructure/docker/go.mod, test/infrastructure/docker/go.sum, util/util.go, util/util_test.go
Updates controller runtime to the latest alpha version
=> :seedling: Update Controller Runtime to v0.7.0-alpha.8

api/v1alpha4/common_types.go, controllers/machineset_delete_policy.go, controllers/machineset_delete_policy_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/machine_collection.go, docs/proposals/20191017-kubeadm-based-control-plane.md
Adds a possibility to mark a specific control plane Machine to be deleted by a KCP when one or multiple machines are annotated by `delete-machine`  annotation.
**This PR:**
1. makes sure the oldest machine is deleted first when there is one or more machine is marked for deletion. It implements the prioritization logic in descending order with respect to rollout policies, while selecting machine for scale  down in the following order:
- _outdatedMachines with the delete annotation_
- _machines with the delete annotation_
- _outdated machines_
- _all machines_
2. adds a unit test.
3. updates the KCP proposal with a note describing the behavior for scale down with annotation.
Fixes #3910
=> ✨ Mark specific KCP machines with delete annotation for scaling down

controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/etcd_client_generator.go, controlplane/kubeadm/internal/etcd_client_generator_test.go, controlplane/kubeadm/internal/workload_cluster_conditions.go, controlplane/kubeadm/internal/workload_cluster_etcd.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go
This pr fixes the bug where `etcdClientGenerator.forNodes` failed even when some(not all) etcd members were up. It also does some refactoring for writing unit tests. There are 2 commits:
1. 3417409 - Refacoring and unit tests
2. fbfdf6e2ce8be3f31ff20330508af3e707c4b7c9 - `etcdClientGenerator.forNodes` fix
Fixes #3839
=> 🐛 Generate etcd client if at least one member is healthy

util/kubeconfig/kubeconfig.go, util/kubeconfig/kubeconfig_test.go, util/secret/certificates.go
This patch includes setting the **Type** field for CAPI secrets generated by the util functions. 
resolves #2478
=> 🌱 Update util functions for secret generation

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_status_matcher.go
The array of Machines passed to MachineHealthCheck is not ordered, which cause MHC.Status.Targets not ordered, then MHC.Status keep changing. 
Add sort to fix the targets in order.
Fixes #
=> 🐛 MHC sort mhc status targets to avoid status keep changing

docs/book/src/developer/guide.md
Add envsubst as prerequisite in Chapter 'Developer Guide' of the book and update corresponding instructions using envsubst.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #4012
=> 📖 Add envsubst as prerequisite in developer guide

docs/book/src/developer/testing.md, docs/book/src/user/quick-start.md, scripts/ci-e2e.sh, test/infrastructure/docker/docker/kind_manager.go
This will remove the need to set `KIND_EXPERIMENTAL_DOCKER_NETWORK` to `bridge` when running local clusters or E2E tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3832
=> ⚠️ Use Kind's default network in CAPD

controllers/machineset_controller.go, controllers/machineset_controller_test.go, controllers/mdutil/util.go, controllers/mdutil/util_test.go
This PR fix the issue that MachineDeployment RollingUpdate may launch machines more than (MD.Spec.Replicas + maxSurge). It include machines in deleting status when calculate MachineSet status replicas. 
Fixes #3417
=> 🐛 Include machines in deleting status when calculate machineset replicas

controlplane/kubeadm/api/v1alpha4/condition_consts.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/controllers/helpers_test.go, controlplane/kubeadm/controllers/status.go, controlplane/kubeadm/controllers/status_test.go, util/conditions/getter_test.go, util/conditions/matchers.go, util/conditions/merge_test.go, util/conditions/setter_test.go
Adds a new condition (~~ControlPlaneInitialized~~ MachinesCreatedCondition) to indicate failures during control plane initialization, specifically during:
1. Infrastructure reference resource creation
2. Bootstrap config resource creation
3. Machine resource creation
Fixes #3540
=>  🐛 Indicate in KCP conditions, when template cloning fails

test/e2e/config/docker.yaml, test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml, test/e2e/data/kubetest/conformance-fast.yaml, test/e2e/data/kubetest/conformance.yaml, test/e2e/e2e_suite_test.go, test/e2e/k8s_conformance.go, test/e2e/k8s_conformance_test.go
This PR adds an E2E running Kubernetes conformance on CAPD provisioned machines
Rif https://github.com/kubernetes-sigs/cluster-api/issues/3693
=> 🌱 Add Kubernetes conformance E2E test

test/e2e/Makefile, test/e2e/config/docker.yaml, test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/cluster-with-kcp.yaml, test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/kustomization.yaml, test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/md.yaml, test/e2e/node_drain_timeout.go, test/e2e/node_drain_timeout_test.go, test/framework/clusterresourceset_helpers.go, test/framework/control_plane.go, test/framework/controlplane_helpers.go, test/framework/deployment_helpers.go, test/framework/machinedeployment_helpers.go, test/framework/machinehealthcheck_helpers.go
This is an e2e test for the node drain timeout feature implemented in PR #3662 
This test aims to make sure that all machines can be removed after a specific amount of time even when they have workloads running inside that block the draining process. 
The test scenario is as follows:
- Create a management cluster with one control plane and one worker machine.
- Update the `NodeDrainTImeout` field of the `MachineDeployment`, and wait until all worker machines to be updated.
- Add some workloads that cannot be evicted during the node draining process (using pod deployment and `podDisruptionBudget`)
- Make sure that all worker nodes can still be deleted after a specific amount of time.
- Untaint the control plane so they can run workloads.
- Update the …
=> 🌱 Add e2e test for node drain timeout feature

test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml, test/framework/kubetest/run.go
This PR fixes the e2e conformance test for working with CAPD after this has been changed to use the kind network
It also fixes v1alpha4 test running locally on mac os.
=> 🐛 E2E conformance tests now use kind network

bootstrap/kubeadm/main.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_fake.go, controllers/remote/cluster_cache_reconciler_test.go, controlplane/kubeadm/main.go, exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/suite_test.go, go.mod, go.sum, main.go, test/framework/convenience.go, test/infrastructure/docker/go.mod, test/infrastructure/docker/go.sum
These changes allow the current stable Cluster API release to reduce its
memory footprint by a large margin.
Currently, we have multiple controllers that are either watching (like
ClusterResourceSet) or querying (get/list) corev1.Secret and
corev1.ConfigMap resources.
When these kinds go through the case, all of the objects in the cluster
end up being cached, not just the ones we're interested in.
In production environments, there might be a large number of ConfigMap
or Secret resources that we end up caching and watching for little gain.
Fixes …
=>  ✨ Use uncached client and partial metadata for secret and configmaps

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/helpers.go, controlplane/kubeadm/controllers/helpers_test.go
This PR ensures kubeconfig secrets created by v1alpha2 controllers are adopted by KCP, thus allowing periodic kubeconfig secrete re-generation preventing the expiration of the embedded client certificate.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4011
=> 🐛 KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets

Tiltfile, test/framework/machinepool_helpers.go, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/loadbalancer.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/exp/controllers/dockermachinepool_controller.go, test/infrastructure/docker/exp/docker/nodepool.go
This PR makes DockerMachinePool, and most specifically the Docker NodePool construct, not use `Status.instances` from previous reconciliation in order to determine which machine to delete.
The previous implementation, relying on `Status.instances` and the ordering of elements in this struct, was found as a root cause for test failures in https://github.com/kubernetes-sigs/cluster-api/pull/3916
Instead, we are using the list of machines/containers as a source of truth for the current state, with the only exception that info on `status.instances` are used to determine if a machine is already bootstrapped or not (this information is not available elsewhere).
=> 🌱 DockerMachinePool should not use Status.instances from previous reconciliation

api/v1alpha3/cluster_types.go, api/v1alpha4/cluster_types.go
**What this PR does / why we need it**: Currently the `cluster-api` fails to connect to an IPv6 cluster because of improper parsing of the IPv6 address and port combination. This PR fixes that.
=> 🐛  Fix APIEndpoint for IPv6

controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
This PR enables mutation for the following fields in KubeadmControlPlane Spec: 
Fixes #2083
=> ✨ Make KubeadmControlPlane Spec mutable

OWNERS, OWNERS_ALIASES
long.
I have not contributed for too long, so it makes sense to give someone else the opportunity to have a more official role. FWIW I intend to focus on other Cluster Lifecycle operators for the time being. Hope to see everyone at the next KubeCon.
Fixes #
N/A
=> 🌱 Move davidewatson to emeritus since he has not contributed for too

docs/proposals/20191017-kubeadm-based-control-plane.md
Currently, KCP scale out during the upgrade, and no other method is available. However, this is a very restrictive implementation in environments where the amount of resources is limited and scale out might not be possible. The main motivation for this KCP proposal update is to be able to add scale in feature to KCP implementation when this PR is approved. 
This proposal is discussed in [google doc](https://docs.google.com/document/d/1HWHTL6g45HrrBppGWgDi_1VkWRMA0Ue3IRBONcqKFKE/edit#) and in [issue 3512](https://github.com/kubernetes-sigs/cluster-api/issues/3512)
=> 📖 Update KCP proposal with scale in

api/v1alpha4/common_types.go, controllers/machine_controller_noderef.go, exp/controllers/machinepool_controller_noderef.go, util/annotations/helpers.go, util/annotations/helpers_test.go
**What this PR does / why we need it**: Adds basic cluster info to nodes as annotations to allow users to know if the node was created using cluster api and which cluster/namespace/machine or machine pool it belongs to.
Tested using release-0.3 branch:
```
k --kubeconfig ./kubeconfig describe node capz-cluster-7-md-0-5f9fq
Name:               capz-cluster-7-md-0-5f9fq
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
beta.kubernetes.io/instance-type=Standard_D2s_v3
beta.kubernetes.io/os=linux
failure-domain.beta.kubernetes.io/region=southcentralus
failure-domain.beta.kubernetes.io/zone=0
kubernetes.io/arch=amd64
kubernetes.io/hostname=capz-cluster-7-md-0-5f9fq
kubernetes.io/os=linux
node.kubernetes.io/instance-type=Standard_D2s_v3 …
```
=> 🌱 Annotate nodes with cluster info

controlplane/kubeadm/main.go
To improve a self-managed cluster resilience to temporary errors related
to etcd leadership, this change increases the duration for all the lease
times.
The following are the most important values for leader election, we
increase the amount the non-leader candidates wait (1m now) and we
increase the renew deadline to 40s instead of 10, which should give
enough time for etcd connectivity to be established again.
- Lease duration is now 1 minute instead of 15s
- Renew deadline has been increased to 40 seconds instead of 10
In addition:
- Retry period has been increased to 5 seconds instead of 2
- Avoid overloading the API Server / etcd with lease retry requests …
=> :seedling: Increase leader election lease values for KCP

cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/describe.go, cmd/clusterctl/client/tree/annotations.go, cmd/clusterctl/client/tree/discovery.go, cmd/clusterctl/client/tree/discovery_test.go, cmd/clusterctl/client/tree/doc.go, cmd/clusterctl/client/tree/options.go, cmd/clusterctl/client/tree/tree.go, cmd/clusterctl/client/tree/tree_test.go, cmd/clusterctl/client/tree/util.go, cmd/clusterctl/cmd/describe.go, cmd/clusterctl/cmd/describe_cluster.go, cmd/clusterctl/cmd/describe_cluster_test.go, go.mod, go.sum, test/infrastructure/docker/go.sum
This PR adds a new package to the clusterctl library supporting the generation of an "at glance" view of conditions in my cluster for quickly understanding if there are problems and where.
Rif https://github.com/kubernetes-sigs/cluster-api/issues/3802
=> 🌱 Add clusterctl describe cluster command

controllers/remote/cluster_cache.go
While investigating some unit test flakes I have found the cluster cache logging "msg"="Error health checking cluster" "error"="timed out waiting for the condition" while doing the MHC unit tests.
This isn't a real flake, it is just a log entry, however, it generates a lot of noise and makes it difficult to spot the real problems.
This PR is fixing this by making to log the entry only when necessary (and not when the cluster cache is intentionally stopped)
/cc @vincepri
=> 🐛 Avoid reporting health check error when the cache is stopped

exp/addons/controllers/clusterresourceset_controller_test.go
Increases timeout in clusterresourceset controller unit tests
Fixes #4075
=> 🐛 Increase timeout in clusterresourceset controller unit tests

test/e2e/data/kubetest/conformance.yaml
Adds `ginkgo.skip` to E2E Conformance tests labeled as Serial.
Fixes #4077
=> 🐛 Skip E2E Conformance tests labeled as Serial

scripts/ci-e2e-lib.sh, scripts/ci-e2e.sh, test/e2e/config/docker.yaml, test/e2e/kcp_upgrade_test.go, test/e2e/machine_pool_test.go, test/e2e/md_upgrades_test.go, test/e2e/quick_start_test.go, test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go, test/framework/daemonset_helpers.go, test/framework/machinepool_helpers.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/exp/docker/nodepool.go
This PR lays the ground for testing workload clusters with Kubernetes from ci/latest
Rif https://github.com/kubernetes-sigs/cluster-api/issues/3569
=> 🌱 Add e2e tests for workload cluster with Kubernetes from ci/latest

test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/errors.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/docker/types/node.go, test/infrastructure/docker/docker/util.go
This pr checks returns an error and prevent reconciliation loop if a stopped container is being patched. 
It does NOT handle when two clusters are created with the same name.
Fixes #3973
=> 🐛 Handle stopped containers in capd

controllers/machineset_controller.go
This patch refactors the implementation of the machinset controller to follow the new conventions and patterns.
Fixes #1689
=> 🌱 Move MachineSet patching to a defer call

test/framework/kubetest/run.go
This adds an optional parameter for using `KUBE_TEST_REPO_LIST`.  More info on this `KUBE_TEST_REPO_LIST` is here: https://github.com/kubernetes/kubernetes/blob/master/test/images/README.md#testing-the-new-image
This currently required to be able to run the upstream tests for windows: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/README.md#notes-to-run-sig-windows-tests. 
Fixes #
=> 🌱 Add optional parameter for using repolist to the kubetest library 

bootstrap/kubeadm/controllers/suite_test.go, controllers/remote/cluster_cache_healthcheck_test.go, controllers/remote/cluster_cache_reconciler_test.go, controllers/remote/cluster_cache_tracker_test.go, controllers/remote/suite_test.go, controllers/suite_test.go, controlplane/kubeadm/controllers/suite_test.go, controlplane/kubeadm/internal/suite_test.go, docs/book/src/developer/testing.md, exp/addons/controllers/suite_test.go, exp/controllers/suite_test.go, util/patch/suite_test.go
This PR adds a one liner in BeforeSuite, and all the other places where we start a Manager that properly waits for the manager to be elected (and therefore for the cache to sync) before running any sort of test.
Fixes #4068 
=> :bug: Test environments should wait for manager before running tests

docs/book/src/SUMMARY.md, docs/book/src/clusterctl/commands/init.md, docs/book/src/clusterctl/commands/upgrade.md, docs/book/src/clusterctl/provider-contract.md, docs/book/src/developer/architecture/controllers/multi-tenancy.md, docs/book/src/developer/architecture/controllers/support-multiple-instances.md, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, docs/book/src/reference/glossary.md
As per discussion on January 13th office hour meeting, this PR updates the cluster API book by:
1.  Removing outdated definitions/related paragraphs in the clusterctl documentation
2. Documenting the new definition of multi tenancy, as per https://github.com/kubernetes-sigs/cluster-api/issues/3042, and the  impact of such definition on the contract (including e.g. and https://github.com/kubernetes-sigs/cluster-api/issues/3822)
3. Documenting the lesson learned in running multiple instances of the same providers in v1alpha3, and the intent to preserve the possibility to go down this path if someone wants (make it possible)
Please note that the last point most probably does not represent yet the final state and it should be intended as a hook for the …
=> 📖 Document multi-tenancy contract

Dockerfile, bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml, cmd/clusterctl/client/init_test.go, cmd/clusterctl/internal/util/objs_test.go, config/ci/manager/manager_auth_proxy_patch.yaml, config/manager/manager_auth_proxy_patch.yaml, controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
This pr updates the non root user from `nobody` to `nonroot` (with id). This is needed when pod security policies are enabled in the cluster to prevent containers from running as root.
Fixes #4046
=> 🐛 Use nonroot user with id

docs/proposals/20191017-kubeadm-based-control-plane.md
In the KCP proposal we are using the term health with two different meanings:
1. healthy machine, referring to the status of a set of configurable node conditions (inherited from MachineHealthCheck)
2. healthy control plane or healthy etcd, referred to a set of preflight checks that KCP executes to ensure the control plane is stable before moving on with the next action (scale up, scale down, roll out)
This PR aligns the KCP proposal to the changes introduced by #3900 in the code for disambiguating the usage of healthy; As a consequence now we using health check is used only for 1, while we are using preflight check for 2.
While fixing this, I also added a sentence to document changes recently introduced by …
=> 📖 Update kcp proposal disambiguating healthcheck

test/framework/kubetest/run.go
Cherry-pick of: https://github.com/kubernetes-sigs/cluster-api/pull/4069
Enables providers using release-3.0 use this library to do testing using repolist (required for Windows)
Being used in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1119
Fixes #
=> 🌱 Cherry-pick: Add optional parameter for using repolist

exp/addons/controllers/clusterresourceset_controller_test.go
Fix ClusterResultSet test flakes by ensuring that each test case uses a different CRS object name (instead of reusing always the same name).
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4075
=> 🐛 Use a different object name for each ClusterResultSet test case

bootstrap/kubeadm/internal/cloudinit/cloudinit.go, bootstrap/kubeadm/internal/cloudinit/controlplane_init.go, bootstrap/kubeadm/internal/cloudinit/controlplane_join.go, bootstrap/kubeadm/internal/cloudinit/node.go, docs/book/src/developer/providers/bootstrap.md, test/infrastructure/docker/api/v1alpha4/condition_consts.go, test/infrastructure/docker/cloudinit/runcmd.go, test/infrastructure/docker/cloudinit/runcmd_test.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/exp/docker/nodepool.go
**What this PR does / why we need it**: This PR does three things:
1. Add the presence of `/run/cluster-api/bootstrap-success.complete` to signal successful completion of bootstrapping to the Bootstrap Provider contract.
2. Adds commands to write the sentinel file when kubeadm init and kubeadm join succeed to CABPK. This is done in a way that works for both Linux and Windows machines.
3. Implements the bootstrap file check and condition for the Docker provider
Fixes #3716
=> ✨  Add sentinel file to signal successful bootstrapping

hack/tools/release/notes.go
This has been unused for a while, removing it now to avoid confusion.
Fixes #
=> :seedling: Remove the image placeholder in release notes

docs/book/Makefile
See https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html for more details.
Thanks!
📖
=> 📖 Update mdbook to 0.4.5 to fix CVE-2020-26297

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, controllers/machine_controller.go, controllers/remote/cluster.go, controllers/remote/cluster_cache.go, controllers/remote/cluster_test.go, controllers/remote/fake/cluster.go, controllers/remote/restconfig.go, controlplane/kubeadm/internal/cluster.go, exp/controllers/machinepool_controller.go, exp/controllers/machinepool_controller_noderef.go
- set a UserAgent and Timeout for remote cluster client
Fixes #2993
=> ⚠️ Set user agent and timeout for remote cluster client

test/e2e/common.go, test/e2e/k8s_conformance.go, test/e2e/kcp_upgrade.go, test/e2e/machine_pool.go, test/e2e/md_upgrades.go, test/e2e/mhc_remediations.go, test/e2e/node_drain_timeout.go, test/e2e/quick_start.go, test/e2e/self_hosted.go, test/framework/clusterctl/clusterctl_helpers.go
`clusterctl.ApplyClusterTemplateAndWait` in the case of failure when building a cluster during e2e tests, the function will not return. This makes it tough for callers to interrogate / debug a cluster if it never successfully provisions. It would be useful to either return an error up the stack, add a ptr parameter to fill progressively, or provide hooks to cluster provisioning lifecycle. Rebuilding the test framework to return errors up the stack would be a huge undertaking. Adding hooks is not super ergonomic as evidenced by #4111. By providing a ptr result parameter the caller is able to pass a variable and use it later in the test suite.
Notes:
- Unlike #4111 this is a breaking change
- A caller must understand the result may not be filled. This …
=> ⚠️ add result parameter to ApplyClusterTemplateAndWait

exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourceset_controller_test.go
After using live client for ConfigMap and Secrets, when doing get on the resources, `TypeMeta` is returned nil.
Using a different conversion fills `apiVersion` and `kind` fields.
Fixes  https://github.com/kubernetes-sigs/cluster-api/issues/4115
=> 🐛Fix ClusterResourceSet not getting Secret/Configmap TypeMeta

Dockerfile, Makefile, Tiltfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile
Maintenance update for our Go version used to build binaries.
Fixes #
/assign @fabriziopandini @CecileRobertMichon
=> 🌱  Update Go to v1.15.7

cmd/clusterctl/client/alpha/rollout.go, cmd/clusterctl/client/alpha/rollout_pauser.go, cmd/clusterctl/client/alpha/rollout_pauser_test.go, cmd/clusterctl/client/alpha/rollout_restarter.go, cmd/clusterctl/client/alpha/rollout_resumer.go, cmd/clusterctl/client/alpha/rollout_resumer_test.go, cmd/clusterctl/client/client.go, cmd/clusterctl/client/client_test.go, cmd/clusterctl/client/rollout.go, cmd/clusterctl/client/rollout_test.go, cmd/clusterctl/cmd/rollout.go, cmd/clusterctl/cmd/rollout/pause.go, cmd/clusterctl/cmd/rollout/restart.go, cmd/clusterctl/cmd/rollout/resume.go
Adds command and client for the `clusterctl alpha rollout pause/resume`. 
Tracking Issue: 
https://github.com/kubernetes-sigs/cluster-api/issues/3439
=> ✨ clusterctl alpha rollout pause/resume for MachineDeployments

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/main.go
Uses ` remote.ClusterCacheTracker ` to get a client for KCP to be used for the workload cluster, instead of creating one.
Fixes #3457
=> 🌱 Switch KCP to use ClusterCacheTracker.GetClient for the workload cluster

test/infrastructure/docker/Dockerfile
This change bring the CAPD deployed container in line with the other
build containers, using golang 1.15.3, which is based off debian.
=> :seedling: Use debian-based container for CAPD

bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml, bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml, bootstrap/kubeadm/types/v1beta1/types.go, bootstrap/kubeadm/types/v1beta2/types.go, controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml, test/framework/kubetest/run.go
Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-ci-images
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4103
=> 🌱 Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-staging-ci-images

Makefile, cloudbuild-nightly.yaml, test/infrastructure/docker/Makefile
This PR adds a Makefile target that tags the latest staging images built from master branch with nightly tag and push manifests to the staging bucket. It will be called by a periodic daily GCB job (https://github.com/kubernetes/test-infra/pull/20587).
Daily images will look like this in staging registry: 
`gcr.io/k8s-staging-cluster-api/cluster-api-controller:nightly_master_20210121`
And manifest locations are: 
`https://storage.googleapis.com/artifacts.k8s-staging-cluster-api.appspot.com/components/nightly_master_20210121/bootstrap-components.yaml`
Fixes …
=> 🌱 Release daily builds and manifests to staging bucket

exp/addons/controllers/clusterresourceset_controller.go
This log line was logged every time the function ApplyClusterResourceSet
was called. This function is called every time CRS reconciles, even if
it doesn't have any more work to do, causing a lot of similar error
lines to be printed to users.
This change removes the log line for quieter logs.
=> :seedling: Remove verbose log line from CRS controller

cmd/clusterctl/cmd/completion.go, docs/book/src/clusterctl/commands/completion.md, go.sum
ref/ #4090 
Due to this change, we will not able to load the zsh completion code
with the following method:
```
source <(clusterctl completion zsh)
```
Instead, we execute the following command once:
```
clusterctl completion zsh >"${fpath[1]}/_clusterctl"
```
Then we need to start a new shell for this setup to take effect.
---
In addition, github.com/spf13/cobra is updated to v1.1.1 in order to use
native zsh completion feature.
Closes #4090
=> ⚠️  clusterctl completion zsh: Use native zsh completion

docs/book/src/SUMMARY.md, docs/book/src/tasks/cluster-autoscaler.md
This change adds a new task page named "Using the Cluster Autoscaler"
which primarily imports the README.md from the cluster autoscaler capi
instructions, with a little extra text to indicate the linkage.
Partial #4139
=> 📖 add a cluster autoscaler page to the book

api/v1alpha4/common_types.go, controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machinehealthcheck_controller.go, controllers/machineset_controller.go, docs/book/src/developer/architecture/controllers/support-multiple-instances.md, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourcesetbinding_controller.go, exp/controllers/machinepool_controller.go, main.go, util/labels/helpers.go, util/labels/helpers_test.go, util/predicates/generic_predicates.go
This PR adds a flag which defines which CRs will be processed depending on a given label.
Fixes #4004
=> ⚠️ Add watch label to allow multiple manager instances

test/infrastructure/docker/Dockerfile
This is a backport of #4140 
/approve
=> :seedling: Use a debian based container for CAPD

go.mod, go.sum, test/infrastructure/docker/go.mod, test/infrastructure/docker/go.sum
This PR updates controller runtime dependency, which brings in a few nice bug fixes https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.8.2
Fixes #
/assign @CecileRobertMichon @fabriziopandini
=> :seedling: Update controller runtime to v0.8.2

cmd/clusterctl/cmd/completion.go
Enabling completion with `clusterctl completion zsh` only supports putting a completion file to `fpath`. This is a breaking change for users currently using sourcing.
This change allows users to continue to enable completion via sourcing.
ref/ https://github.com/kubernetes-sigs/cluster-api/pull/4113
cc/ @wfernandes 
Fixes #
=> 🌱 Make clusterctl completion zsh work with sourcing

Makefile, cmd/clusterctl/hack/create-local-repository.py, metadata.yaml
Since we removed the embedded metadata, we are going to include the metadata.yaml in the CAPI release assets.
Fixes #4156
=> 🌱  Include metadata for the CAPI releases

controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Fixes a webhook panic caused by a nil pointer dereference
Fixes #
Didn't open an issue, fixed it right away.
=> 🐛 Fix nil pointer dereference

api/v1alpha4/machinedeployment_types.go, api/v1alpha4/machinedeployment_webhook.go, api/v1alpha4/machinedeployment_webhook_test.go, api/v1alpha4/machineset_types.go, api/v1alpha4/machineset_webhook.go, api/v1alpha4/machineset_webhook_test.go, config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml, config/crd/bases/cluster.x-k8s.io_machinesets.yaml, controllers/schema_test.go
Use openAPI scheme for defaulting machineset and machinedeployment replicas. This is a trivial validation that can be without usage of webhooks and it doesn't need to be unit tested.
=> 🌱 Use openAPI scheme for defaulting replicas

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, controlplane/kubeadm/controllers/fakes_test.go, controlplane/kubeadm/controllers/remediation_test.go, controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/scale_test.go, controlplane/kubeadm/controllers/status.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/controllers/upgrade_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/filters.go, controlplane/kubeadm/internal/filters_test.go, controlplane/kubeadm/internal/workload_cluster_conditions.go, controlplane/kubeadm/internal/workload_cluster_conditions_test.go, util/collections/machine_collection.go, util/collections/machine_collection_test.go, util/collections/machine_filters.go, util/collections/machine_filters_test.go, util/failuredomains/failure_domains.go, util/failuredomains/failure_domains_test.go
**What**: In preparation for #3358, this PR moves the failure domains business logic out of `controlplane/kubeadm/internal` into `util/`. There should be no behavior changes as a result of this PR.
**Why**: Nothing in `failure_domains.go`, `machine_filters.go` and `machine_collection.go` is kubeadm or control plane specific. The logic should be available for reuse for other packages outside the KCP implementation.
**How**:
- controlplane/kubeadm/internal/failure_domain.go → util/failuredomains/failure_domains.go  
- controlplane/kubeadm/internal/machine_collection.go → util/collections/machine_collection.go  
- controlplane/kubeadm/internal/machinefilters/machine_filters.go → util/collections/machine_filters.go  
- moved the global internal Log var …
=> 🌱  refactor failure domains logic out of controlplane internal package

docs/book/src/user/quick-start.md
changes documentation to refer to clusterctl instead of kubectl under cluster installation intructions 
Fixes #
=> 📖 docs: change to clusterctl instead of kubectl

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Update quickstart documentation based on some feedback I got from a first time user:
- bump k8s version to latest patch
- show clusterctl describe command
- add note on choosing an Azure location / vm size 
- update kcp output to latest
Fixes #
=> :book: update quickstart doc

api/v1alpha4/common_types.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_targets.go, controllers/machinehealthcheck_targets_test.go, docs/book/src/tasks/healthcheck.md, util/annotations/helpers.go
- Skips remediation for paused machines
- Adds a new annotation to mark machines for skipping remediation
Fixes #4032
=> ✨ Add support to skip Machine remediation, and respect paused Machines in MHC

bootstrap/kubeadm/main.go, controlplane/kubeadm/main.go, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, main.go, test/infrastructure/docker/main.go
Allows to specify webhook cert dir for being able to use anything else then default controller-runtime one.
Useful for debugging purposes and potentially in environments with different certificate management flow.
#4165
=> 🌱 add possibility to specify webhook cert dir

controllers/external/tracker.go, controllers/external/tracker_test.go
When ObjectTracker.Watch is called, the object's GroupKind is stored in a cache, so that duplicate
registration is avoided. But if some reason the watch registration errored out, the
cache doesn't clear out the object as the wrong key was passed. This fix allows the
Watch to be retried correctly in the case of failures with the registration.
=> 🐛  Fix ObjectTracker to allow retry on error

bootstrap/kubeadm/types/v1beta2/groupversion_info.go, bootstrap/kubeadm/types/v1beta2/types.go
This PR adds to the copy of kubedm types for v1beta2  the same improvements to serialization output already applied to the copy of kubedm types for v1beta1 (mostly `+optional`/`omitempty` fixes).
NB the copy of the types for v1beta2 is not used now, so this change does not have any side effect.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4203
=> 🌱 Align kubeadm types

util/patch/patch.go, util/patch/patch_test.go
The following changes add more validation to the patch helper to avoid
possible issues by patching different objects by mistake. Part of this
change is also checking that users don't pass in nil objects to the
Patch() method.
Fixes #3269 
/assign @CecileRobertMichon
=> ⚠️ Add GVK object validation to patch helper

Makefile, scripts/ci-test.sh, test/infrastructure/docker/Makefile
`make test` now has very concise output when run in local development, making it easier to spot actual failures. There is an additional target called `make test-verbose` which is used in CI to continue to have the full verbose output.
Fixes #4182
=> 🌱 Remove verbose flag from make test

docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
During implementation of CAPO v1alpha4 I found some minor issues in the v1alpha4 migration documentation. 
I'm not entirely sure that those fixes are accurate, but I think they are based on the current main branch of cluster-api.
=> 📖 some minor fixes for the v1alpha4 migration doc

docs/book/src/tasks/healthcheck.md
This PR updates the MachineHealthCheck (MHC) documentation to include support for control plane nodes via KCP and an example of creating an MHC for KCP nodes.
Fixes #4138
=> 📖 Update MHC documentation

docs/book/src/tasks/healthcheck.md
This PR backports the MHC documentation updates from #4228 and backports them to the `release-0.3` branch.
Related to #4318
=> 📖 Backport MHC documentation to release-0.3

hack/ensure-kind.sh
`ensure-kind.sh` should compare semantic versions correctly, instead of checking for the exact number.
Otherwise it could fail even when the local kind version is `v0.10.0`, which is obviously greater than the minimum version `v0.9.0`.
So let's follow mostly the way how other ensure scripts are implemented:
read the kind version, run version sort with the minimum version, and compare it to the minimum version.
**Release note:**
```
NONE
```
=> 🐛 hack: fix semver comparison in ensure-kind

cmd/clusterctl/client/cluster/installer.go, cmd/clusterctl/client/cluster/installer_test.go, cmd/clusterctl/client/init_test.go, cmd/clusterctl/internal/test/contracts.go, test/e2e/config/docker.yaml, test/e2e/data/shared/v1alpha4/metadata.yaml
As a consequence, clusterctl version v1alpha4 should not be allowed to install v1alpha3 providers
NB: While doing the change, also clusterctl version v1alpha4 should not be allowed to install v1alpha5 providers was implemented, and tests are now refactored in order to make changes for supporting the next contract less invasive.
This will also ensure easier backport
Rif #4191
=> 🌱  clusterctl v1alpha4 should not install v1alpha3 providers

controllers/machineset_controller.go, controllers/machineset_controller_test.go
Add check for empty maps in machineset controller, similar to what is done in machine deployment controller.
=> 🐛Add check for empty maps in machineset controller

controlplane/kubeadm/controllers/remediation.go, controlplane/kubeadm/controllers/remediation_test.go
This PR fixes a problem in KCP remediation not properly computing the targetCluster when node Name & etcd member Name != machine Name (e.g. AWS)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4239
=> 🐛 Fix KCP remediation when node Name & etcd member Name != machine Name

.golangci.yml
As mentioned in #4243, golang lint documentation suggests using `disable-all/enable` instead of `enable-all/disable`(it is deprecated and will be removed soon). So we should implement `disable-all: true / enable: [...]`.
Fixes #4243
=> 🌱 update golangci-lint config to use disable-all/enable

docs/book/src/tasks/kubeadm-control-plane.md
Document current behaviour for workloads on KCP controlled machines
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2064
=> 📖 Document policy for workloads on KCP controlled machines

util/conversion/conversion.go
Adds more context to error message about not being able to find versions matching contract - we burnt a few cycles with this error message, so I reckoned it'd be helpful to add a pointer for the next person :D
=> 🌱 Updates conversion error message with reasoning

exp/operator/config/certmanager/certificate.yaml, exp/operator/config/certmanager/kustomization.yaml, exp/operator/config/certmanager/kustomizeconfig.yaml
Aligning the cert-manager config with master. 
towards https://github.com/kubernetes-sigs/cluster-api/issues/4246
=> 🌱 Update operator to use certmanager v1 resources

cmd/clusterctl/client/cluster/upgrader.go, cmd/clusterctl/client/cluster/upgrader_info.go, cmd/clusterctl/client/cluster/upgrader_info_test.go, cmd/clusterctl/client/cluster/upgrader_test.go, cmd/clusterctl/client/upgrade.go, cmd/clusterctl/client/upgrade_test.go, cmd/clusterctl/cmd/upgrade_apply.go, cmd/clusterctl/cmd/upgrade_plan.go, cmd/clusterctl/internal/test/contracts.go
As a consequence, clusterctl version v1alpha4 should not be allowed to upgrade to v1alpha3 clusters
NB: While doing the change, also clusterctl version v1alpha4 should not be allowed to upgrade to v1alpha5 clusters was implemented, and tests are now refactored in order to make changes for supporting the next contract less invasive.
This will also ensure easier backport
Rif #4191
=> ⚠️ clusterctl v1alpha4 should not upgrade to v1alpha3 contract

controllers/machinehealthcheck_controller.go
:bug:, patch and bugfixes
fix bug
obj, err := r.getExternalRemediationRequest(ctx, m, t.Machine.Name) 
when obj is nil will cause panic
obj.GetDeletionTimestamp()
Fixes #
=> 🐛 Fix a panic when getExternalRemediationRequest returns nil

docs/book/src/tasks/kubeadm-control-plane.md
This PR is a backport to the documentation on 0.3 branch.
Fixes #4261
=>  📖 Document policy for workloads on KCP controlled machines - 0.3 branch

tilt_modules/cert_manager/README.md, tilt_modules/cert_manager/Tiltfile
This sets the Tilt cert-manager module to 1.0 for default.
FIY I have opened a [PR](https://github.com/tilt-dev/tilt-extensions/pull/141) on the Tilt module repository too!
I am not so sure about the deletion of the md chapter in this PR, please tell me if am wrong with that!
Fixes #4256
=> 🌱 Update Cert Manager Tilt module to v1.1.0 as default

feature/feature.go
Graduate CRS in v0.4.0 by enabling the functionality by default.
Fixes #3311 
/assign @CecileRobertMichon @sedefsavas
=> :seedling: Enable ClusterResourceSet by default

controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
For Kubernetes >= 1.21, image builder is going to setup containerd for using systemd cgroup.
KCP should take care of adapting the Kubelet-Config map to be consistent with this change.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4099
/hold 
for the change in image builder to be merged, rif https://github.com/kubernetes-sigs/image-builder/issues/471
=> ⚠️ Default Kubelet cgroupDriver to systemd for Kubernetes >= 1.21
