- docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md
As per https://github.com/kubernetes-sigs/cluster-api/issues/2769#issuecomment-656775412
> We should stop exposing the kubeadm v1betax types in our KubeadmConfig/KubeadmControlPlane specs, and instead use our own types. This would allow us to separate what users fill in from which kubeadm API version we end up using in our bootstrap data. 
IMPORTANT! This task is a release blocker for CABPK/v1alpha4. Changes in v1alpha3 are required to support Kubernetes version >= v1.21 (assuming removal of v1beta1 types in kubeadm happens in v1.21)
Rif #2769
> 📖 CAEP: Insulate users from kubeadm API version changes

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
Without this, machinepool descendeants are ignored in descendant count deletion logic and can be orphaned and unable to delete without manually deleting the finalizer.
Fixes #4296
> :bug:  Include machinepools in descendant count

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
Backport of #4295 to `release-0.3` branch.
Without this, machinepool descendants are ignored in deletion logic and can be orphaned and unable to delete without manually deleting the finalizer.
Fixes #
> :bug: Include machinepools in descendant count

- docs/book/src/reference/versions.md
This PR fixes the version support doc by adding Kubernetes v1.20 and updating the CABPK support matrix according to latest changes for kubeadm v1beta1 types removal
Fixes #
> 📖 Fix version support doc

- cmd/clusterctl/client/alpha/rollout.go
- cmd/clusterctl/client/alpha/rollout_pauser.go
- cmd/clusterctl/client/alpha/rollout_pauser_test.go
- cmd/clusterctl/client/alpha/rollout_restarter.go
- cmd/clusterctl/client/alpha/rollout_restarter_test.go
- cmd/clusterctl/client/alpha/rollout_resumer.go
- cmd/clusterctl/client/alpha/rollout_resumer_test.go
- cmd/clusterctl/client/alpha/rollout_rollbacker.go
- cmd/clusterctl/client/alpha/rollout_rollbacker_test.go
- cmd/clusterctl/client/client.go
- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/rollout.go
- cmd/clusterctl/client/rollout_test.go
- cmd/clusterctl/cmd/rollout.go
- cmd/clusterctl/cmd/rollout/undo.go
Adds command and client for the `clusterctl alpha rollout undo` command. 
Example Usage: Rollback to earlier K version after upgrade.
1. Do an K version upgrade so that a new MS is created:
```
kubectl get md -n default test-md-0 -o json | jq '.spec.template.spec.version="v1.19.3"' | kubectl apply -f-
```	
2. You should see a new MS and an old MS. MD will have revision annotation to point to new MS.
3. Perform undo:
```
clusterctl alpha rollout undo machinedeployment/test-md-0 --to-revision=XXX
```
Another example is to rollback to an earlier MachineTemplate. See CAPI book on how to change MachineTemplates. 
Tracking Issue:
#3439
> ✨ Clusterctl alpha rollout undo for MachineDeployments

- bootstrap/kubeadm/api/v1alpha4/condition_consts.go
- controllers/machinehealthcheck_targets.go
- hack/tools/release/notes.go
- test/helpers/envtest.go
- util/kubeconfig/testing.go
- util/secret/certificates.go
- util/secret/certificates_test.go
- util/util.go
Clean up "deprecated" variables/functions in v1alpha4
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4005
**Dear reviewers**
Please take a closer look at this, I could miss something. 
Thank you!
> ⚠️ Clean up "deprecated" variables/functions in v1alpha4

- scripts/ci-build.sh
- scripts/ci-make.sh
- scripts/ci-verify.sh
In order to make CI(https://github.com/kubernetes/test-infra/pull/21182/) work for the operator, some changes are required in scripts.
https://github.com/kubernetes-sigs/cluster-api/issues/4269
/area operator
> 🌱 Make CI scripts work with operator

- Makefile
- cmd/clusterctl/client/yamlprocessor/simple_processor.go
- cmd/clusterctl/client/yamlprocessor/simple_processor_test.go
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- hack/tools/tools.go
- test/infrastructure/docker/go.sum
- test/infrastructure/docker/hack/tools/go.sum
This bumps envsubst to 2.0 which only escapes values inside the variable expansions. This fixes issues for mapping in Windows named pipes.  See https://github.com/drone/envsubst/pull/27 for details on change
This could be a breaking change where relying on escapes.
Fixes #4016
> ⚠️ 🐛 Update envsubst to 2.0 to fix escaping of namedpipes

- docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Fix link 404 in 20190610-machine-states-preboot-bootstrapping.md
Fixes #
> 📖  Fix link 404 in 20190610-machine-states-preboot-bootstrapping.md

- test/framework/clusterctl/repository.go
This PR make `RegisterClusterResourceSetConfigMapTransformation` clusterctl e2e framework to be general. In the case infrastructure provider can use this function for installing an external Cloud Controller Manager via CRS in their e2e test
Actually, the functionality already working, this PR just changes `CNI` with `manifests` in the ginkgo message.
None
> 🌱 Make RegisterClusterResourceSetConfigMapTransformation to be general (not only for CNI)

- exp/operator/main.go
Remove zap and use klogr in the operator. `klogr` is commonly used across other CAPI components, `zap` should be replaced in favor of it.
/area operator
> 🌱Remove zap and use klogr in operator

- test/infrastructure/docker/Dockerfile
Use distroless for CAPD, so the image size shrink down from >1GB to 158MB
Fixes #
> 🌱Use distroless for CAPD

- cmd/clusterctl/client/cluster/installer.go
- cmd/clusterctl/client/cluster/installer_test.go
- cmd/clusterctl/client/init_test.go
- cmd/clusterctl/internal/test/contracts.go
this is a back port of https://github.com/kubernetes-sigs/cluster-api/pull/4200
As a consequence, clusterctl version v1alpha3 should not be allowed to install v1alpha4 providers
NB: While doing the change, also clusterctl version v1alpha3 should not be allowed to install v1alpha2 providers was implemented, and tests are now refactored accordingly.
Rif #4192
> 🌱clusterctl v1alpha3 should not install v1alpha4 providers

- exp/operator/controllers/suite_test.go
Kubebuilder scaffolding initially bootstraps test environment using `envtest`. This PR switches to go test in operator suite test. That way it can be consistent with other CAPI parts.
Fixes #
> ✨Switch to go test in operator suite test

- scripts/ci-verify.sh
Add CI script for running `make verify`. This change is needed for having one common CI job for verifying operator and CAPI.
Currently, the prow job runs `make verify` without this script. See: https://github.com/kubernetes/test-infra/pull/21182/files#diff-acb2ca5ac5bdc0e994bdab32ff57c18d2a3b4d8d51e29773c1bb226f1ee7090aR83
Fixes #
> ✨Add CI script for running make verify

- bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
- bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
- bootstrap/kubeadm/types/v1beta1/utils.go
- bootstrap/kubeadm/types/v1beta1/utils_test.go
- bootstrap/kubeadm/types/v1beta2/groupversion_info.go
- bootstrap/util/configowner.go
- bootstrap/util/configowner_test.go
- controlplane/kubeadm/internal/kubeadm_config_map.go
- controlplane/kubeadm/internal/kubeadm_config_map_test.go
backport of https://github.com/kubernetes-sigs/cluster-api/pull/4227
This PR implements a stop-gap solution for kubeadm types removal explicitly designed for back-porting on the v1alpha3 branch.
The solution implemented is described in the https://github.com/kubernetes-sigs/cluster-api/pull/4170 (and more specifically this is alternative 2 for v1alpha3).
A proper conversion mechanism is going to be implemented in v1alpha4 only (also described in the proposal).
Fixes #
> ✨ [CABPK] Support using kubeadm v1beta2 types internally

- exp/operator/config/rbac/leader_election_role.yaml
Add leases to leader election role in operator. Similar to what is done here https://github.com/kubernetes-sigs/cluster-api/blob/master/config/rbac/leader_election_role.yaml#L34
Fixes #
> 🌱Add leases to leader election role in operator

- api/v1alpha4/condition_consts.go
- exp/controllers/machinepool_controller_phases.go
- exp/controllers/machinepool_controller_test.go
This patch sets the `InfrastructureReadyCondition` as `false` if the external reference set on the MachinePool object is incorrect/does not exist. 
Fixes #4311
> 🌱 Sets InfraReady condition for MachinePool for incorrect external reference

- docs/book/src/tasks/healthcheck.md
The current docs for MHCs still state that only MDs are supported. This updates that
> 📖 update MHC docs to comply with current impl.

- docs/book/src/tasks/upgrading-clusters.md
Add a section that documents `KubeadmControlPlane.Spec.UpgradeAfter` and
how to achieve a similar effect for machines managed by a
`MachineDeployment`.
Fixes #3401
> 📖 Document `UpgradeAfter`

- cmd/clusterctl/client/cluster/inventory.go
- cmd/clusterctl/client/cluster/inventory_test.go
- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/delete.go
- cmd/clusterctl/client/delete_test.go
- cmd/clusterctl/client/describe.go
- cmd/clusterctl/client/get_kubeconfig.go
- cmd/clusterctl/client/get_kubeconfig_test.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/client/move.go
- cmd/clusterctl/client/move_test.go
- cmd/clusterctl/client/repository/metadata_client_test.go
- cmd/clusterctl/client/upgrade.go
- cmd/clusterctl/client/upgrade_test.go
- cmd/clusterctl/internal/test/contracts.go
- cmd/clusterctl/internal/test/fake_proxy.go
This is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/4199
As a consequence, clusterctl version v1alpha3 should not be allowed to run on v1alpha4 clusters
NB: While doing the change, also clusterctl version v1alpha3 should not be allowed to run on v1alpha2 clusters was implemented (this is not technically possible, but we are getting this for free while backporting), and tests are now refactored in order to make changes for supporting the next contract less invasive.
Rif https://github.com/kubernetes-sigs/cluster-api/issues/4192
/hold 
for …
> ⚠️ Clustectl v1alpha3 should block on v1alpha4 clusters

- cmd/clusterctl/client/cluster/inventory.go
- cmd/clusterctl/client/cluster/inventory_test.go
- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/delete.go
- cmd/clusterctl/client/delete_test.go
- cmd/clusterctl/client/describe.go
- cmd/clusterctl/client/get_kubeconfig.go
- cmd/clusterctl/client/get_kubeconfig_test.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/client/move.go
- cmd/clusterctl/client/move_test.go
- cmd/clusterctl/client/repository/metadata_client_test.go
- cmd/clusterctl/client/upgrade.go
- cmd/clusterctl/client/upgrade_test.go
- cmd/clusterctl/internal/test/fake_proxy.go
As a consequence, clusterctl version v1alpha4 should not be allowed to run on v1alpha3 clusters
NB: While doing the change, also clusterctl version v1alpha4 should not be allowed to run on v1alpha5 clusters was implemented, and tests are now refactored in order to make changes for supporting the next contract less invasive.
This will also ensure easier backport
Rif https://github.com/kubernetes-sigs/cluster-api/issues/4191
> ⚠️ clustectl v1alpha4 should block when used with v1alpha3 management clusters

- test/framework/cluster_proxy.go
- test/framework/clusterctl/clusterctl_helpers.go
- test/framework/exec/kubectl.go
Recently in capz, we were working on integrating gpu-operator with capz's nvidia-gpu flavor [#1254](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1254). As part of it, a CRS is created which refers to a config map that contains the ClusterPolicy CRD (provided by gpu-opertor). But when this config map is applied, it fails with error `The ConfigMap "$cm_name$" is invalid: metadata.annotations: Too long: must have at most 262144 characters`. This is because `kubectl apply` tracks the current version of the resource in `last-applied` annotation thus causing it to exceed the limit.
The solution is to use [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) which requires an extra arg `--server-side` …
>  🌱 E2E test: Allow extra args to be passed during kubectl apply

- Dockerfile
- Makefile
- Tiltfile
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/Dockerfile.dev
- test/infrastructure/docker/Makefile
> 🌱 Update Go to 1.16.2

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/config/webhook/manifests.yaml
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
**What this PR does / why we need it**: This PR registers kcp's scale subresource to validate scaling
**Which issue(s) this PR fixes**: Fixes #4057
/assign @vincepri @CecileRobertMichon
> 🐛 register kcp's scale subresource to validate scaling

- exp/addons/controllers/clusterresourceset_controller_test.go
This PR makes sure that the flaky CRS test we're seeing in lots of PRs spits out the proper error message rather than masking it.
/assign @CecileRobertMichon @sedefsavas @fabriziopandini
> 🐛  Avoid masking possible errors in flaky CRS test

- go.mod
- go.sum
- test/infrastructure/docker/go.mod
- test/infrastructure/docker/go.sum
Maintenance bump to (hopefully) tackle the panic in flaky tests.
/assign @CecileRobertMichon @fabriziopandini 
> :seedling: Update controller-runtime to v0.9.0-alpha.1

- test/e2e/kcp_adoption.go
- test/e2e/kcp_adoption_test.go
Fixes regression introduced by #4354 
Fixes #
>  🐛 Fix clusterproxy interface in e2e: regression

- util/annotations/helpers.go
- util/annotations/helpers_test.go
Previously the `AddAnnotations` func only added the annotations in a local var in case the annotations map in the object has been nil before calling the func. 
As far as I could see this func is used in machine and machinepool controller when adding annotations to node resources. I suppose we didn't hit this bug because in those cases the annotation map is never nil.
Fixes #
> 🐛 Fix annotations.AddAnnotations (if annotations has been nil before)

- docs/book/src/developer/e2e.md
- docs/book/src/developer/testing.md
- hack/tools/go.mod
- hack/tools/go.sum
- test/e2e/Makefile
- test/e2e/cluster_upgrade.go
- test/e2e/cluster_upgrade_test.go
- test/e2e/config/docker.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-upgrades/kustomization.yaml
- test/e2e/k8s_conformance_test.go
- test/e2e/kcp_upgrade_test.go
- test/e2e/md_upgrades_test.go
- test/e2e/quick_start_test.go
- test/infrastructure/docker/hack/tools/go.sum
Adds a new E2E test to upgrade a workload cluster and run conformance tests to verify the upgrade
Fixes #4043
>  🌱  E2E test to upgrade workload cluster

- .github/workflows/golangci-lint.yml
Implements the github action to run golangci-lint. The nice thing about the action is that it caches the go packages between runs.
> :seedling: Add github action to run golangci-lint

- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_targets.go
- controllers/machinehealthcheck_targets_test.go
- the e2e tests for mhc are failing for not being able to get the cluster using the remote client, but we already have the cluster in the calling func 
- 
Fixes #4361
> 🐛  pass the cluster in to the get targets

- controlplane/kubeadm/controllers/upgrade.go
status.Nodes is not the resource status. Method which is populating this field is using the cached client,
which is not ideal when taking decision about scale up or down. This PR change KCP to use list of machines in the controlPlane object for making scaling decision.
Fix issue commented here  [#4293 (comment)](https://github.com/kubernetes-sigs/cluster-api/pull/4293#discussion_r600604240)
>  🐛 Change KCP upgrade to use machinelist for scaling decision

- exp/operator/config/default/manager_auth_proxy_patch.yaml
- exp/operator/main.go
`main.go` in operator is scaffolded with kubebuilder this PR makes it similar to CAPI. That includes: Adding CAPI flags and renaming default ones, setting up health checks and reconcilers in different functions. There is more work to be done like passing context to reconciler and number of resources that be processed concurrently but I'd prefer to keep this PR smaller.
Fixes #
> ✨Make operator main.go and flags similar to CAPI

- docs/book/src/tasks/healthcheck.md
The current docs for MHCs still state that only MDs are supported. This updates that
> 📖  update MHC docs to comply with current implementation

- api/v1alpha3/common_types.go
- controllers/machine_controller_noderef.go
- exp/controllers/machinepool_controller_noderef.go
- util/annotations/helpers.go
- util/annotations/helpers_test.go
**What this PR does / why we need it**: backport of #4048 and #4373 
Fixes #
> 🌱  Annotate nodes with cluster and owner info

- .github/workflows/golangci-lint.yml
By default
(see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request)
github actions are only triggered on opened, syncroize, and reopened.
This PR adds edited to the mix for older PRs.
Fixes #
/assign @fabriziopandini @CecileRobertMichon
> :seedling: Include 'edited' to the list of PR types for golangci action

- docs/book/src/developer/tilt.md
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
The tilt development instructions pointed to a missing section header. Those instructions also instruct to use clusterctl, which is not what we want with tilt created clusters. This updates the instructions to no longer point to the quick start guide and calls out the example configs we have available for creating worker clusters.
This also updates those examples to use the v1alpha4 api version.
> 📖  Update tilt development instructions

- cmd/clusterctl/client/cluster/upgrader.go
- cmd/clusterctl/client/cluster/upgrader_info.go
- cmd/clusterctl/client/cluster/upgrader_info_test.go
- cmd/clusterctl/client/cluster/upgrader_test.go
- cmd/clusterctl/client/upgrade.go
- cmd/clusterctl/client/upgrade_test.go
- cmd/clusterctl/cmd/upgrade_plan.go
This is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/4202
As a consequence, clusterctl version v1alpha3 should not be allowed to upgrade to v1alpha3 clusters
Rif #4192 
/hold 
for https://github.com/kubernetes-sigs/cluster-api/pull/4202 to merge
> ⚠️ Clusterctl v1alpha3 should not upgrade to v1alpha4

- test/e2e/Makefile
- test/e2e/config/docker.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-scale-in/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-scale-in/kustomization.yaml
- test/e2e/kcp_upgrade.go
This PR implements E2E test for KCP scale in rollout. 
Feature is added to master [4073](https://github.com/kubernetes-sigs/cluster-api/pull/4073#pullrequestreview-595150434) and will be part of the v1alpha4 release. 
Related to issue [4282](https://github.com/kubernetes-sigs/cluster-api/issues/4282#event-4450251288)
> ✨ Add E2E for scale in rollout

- docs/book/src/user/quick-start.md
Add installation guide with homebrew for macOS in book. Related to #2389 
Can be merged once Homebrew/homebrew-core/73610 is merged!
> 📖  docs: Add installation guide with homebrew

- test/framework/machinehealthcheck_helpers.go
This PR changes the behaviour of the `WaitForMachineHealthCheckToRemediateUnhealthyNodeCondition` method in the E2E tests in order to fix flakes in our E2E tests.
Now this method handle une MHC at times; additionally it waits for the original number of machines to be restore before checking for the unhealthy conditions to be gone away.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4395
/cc @sbueringer
> ⚠️ Wait for all the machine to exist again after remediation

- scripts/ci-e2e-lib.sh
- scripts/ci-e2e.sh
This PR fixes a problem in our E2E test, where test will fail if the kindest/node image for the requested Kubernetes version is not published yet.
With this PR instead we are changing our prePull sequence, and if a kindest image is not available on gitHub, we build it locally.
As a niece side effect, we are also dropping the BUILD_NODE_IMAGE_TAG env variable for our tests configuration...
/assign @srm09
> 🌱 fallback on build if kindest images are missing

- bootstrap/kubeadm/config/certmanager/certificate.yaml
- bootstrap/kubeadm/config/webhook/kustomization.yaml
- config/certmanager/certificate.yaml
- config/webhook/kustomization.yaml
- controlplane/kubeadm/config/certmanager/certificate.yaml
- controlplane/kubeadm/config/webhook/kustomization.yaml
- test/infrastructure/docker/config/certmanager/certificate.yaml
- test/infrastructure/docker/config/webhook/kustomization.yaml
https://github.com/kubernetes-sigs/cluster-api/pull/4225 made clustectl to deploy cert manager v1.1.0. and updated manifests generation in order to generate Certificate objects using `cert-manager.io/v1` apiVersion.
Unfortunately this is creating a problem for people using old versions of clusterctl for doing `clusterctl init` because e.g.:
- `clusterctl init` with clusterctl v0.3.14 installs cert manager v0.16.1
- `clusterctl init` then installs the latest version of providers, that now is v0.3.15 which creates `cert-manager.io/v1` objects.
This makes init to fail with older version of clusterctl.
This PR fixes this problem by changing our manifests in order to generate Certificate objects using `cert-manager.io/v1alpha2` apiVersion, which can be …
> 🐛 make manifest to use cert-manager.io/v1alpha2

- Makefile
- test/infrastructure/docker/Makefile
A minor cleanup to use the main Makefile targets for CAPD controller-gen and conversion-gen.
Related to #4407
/kind cleanup
> 🌱 Minor CAPD Makefile cleanup

- docs/book/src/tasks/kubeadm-control-plane.md
This PR is to address #4026 
This adds a warning message in the Cluster API Book Section 1.5
Fixes #4026
> 📖 Add a warning that only CoreDNS is supported in KCP

- test/infrastructure/docker/docker/loadbalancer.go
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>
DockerCluster reconciliation tries to lookup IP of the loadbalancer container. In the process, it looks at all containers in the system by running `docker ps -a ` filtering using the name of the cluster. This picks up even those containers that were stopped. The stopped containers will not have any IP addresses associated with them. This results in an error in the DockerCluster controller like
```
[manager] E0329 14:51:58.051663      10 controller.go:302] controller-runtime/manager/controller/dockercluster "msg"="Reconciler error" "error"="DockerCluster.infrastructure.cluster.x-k8s.io \"my-cluster\" is invalid: spec.controlPlaneEndpoint.host: Required value" "name"="my-cluster" …
```
> 🌱 [capd] Ensure Loadbalancer IP is not empty

- scripts/ci-e2e.sh
Gathers more logs and data from Docker and containerd, to be able to fix #4405 mid-term.
Maybe a bit hacky, but I suppose it works, let's see. Should provide a lot more information. The most promising new logs are:
* containerd event logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2e-main/1377189073852043264/artifacts/local/containerd-events.txt
* docker event logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2e-main/1377189073852043264/artifacts/local/docker-events.txt
* docker / containerd logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2 …
> 🌱 gather more Docker and containerd data/logs in ci-e2e.sh

- docs/book/src/clusterctl/commands/alpha-rollout.md
- docs/book/src/clusterctl/commands/commands.md
- docs/book/src/clusterctl/overview.md
Documents the `clusterctl alpha rollout` feature. 
Related Issue:
https://github.com/kubernetes-sigs/cluster-api/issues/3439
> 📖 Add CAPI book section on `clusterctl alpha rollout`

- controlplane/kubeadm/internal/workload_cluster_conditions.go
- controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Not entirely sure that is what was intended by the issue.
Fixes #4234
> 🌱 kcp: include node list error in KCP and control plane machine conditions

- cmd/clusterctl/client/cluster/components.go
- cmd/clusterctl/client/cluster/components_test.go
- cmd/clusterctl/client/cluster/inventory.go
- cmd/clusterctl/client/cluster/inventory_test.go
- cmd/clusterctl/client/cluster/upgrader.go
- cmd/clusterctl/client/cluster/upgrader_test.go
Validations for v1alpha3 -> v1alpha4 upgrade
- Blocks if there are multiple instances of a provider
- Deletes capi-webhook-system namespace
Fixes #4194
> ✨ Extra validations for v1alpha3 -> v1alpha4 upgrade

- cloudbuild-nightly.yaml
- cloudbuild.yaml
- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Upgrades cloudbuild to the newest gcb-docker-gcloud image which uses Go 1.16. I already upgraded the image in CAPO and it worked flawlessly: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/a0467f27b8de8a018e5fbad77d45abbf7581738f 
Fixes #4383
I'm not sure about what the best way is to propagate this change to other providers:
* open PRs in the other provider repos
* add it to the migration doc
* both
Any thoughts?
> 🌱 upgrade cloudbuild to use gcb-docker-gcloud with go 1.16

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/controllers/controller_test.go
Fixes a bug where the observedGenaration is not update correctly when deploying a new generation of KubeadmControlPlane.
Fixes #4341
> 🐛 Fix the observedGeneration update

- exp/operator/Makefile
Add envtest binaries to operator makefile. This should help when someone executes tests from the operator directory.
Fixes #
> 🌱 Add envtest binaries to operator makefile

- cmd/clusterctl/client/cluster/mover.go
- test/infrastructure/docker/docker/machine.go
Adds more debug information in case the container creation does not work. For context, please see https://github.com/kubernetes-sigs/cluster-api/issues/4405#issuecomment-811075444
(supersedes #4416).
Improves observability to debug issues like #4405
> 🌱  capd: print debug infos on container creation error

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Backporting rolloutStrategy to v.0.3.15 caused an issue [4437](https://github.com/kubernetes-sigs/cluster-api/issues/4437). For this issue there is a patch [4438](https://github.com/kubernetes-sigs/cluster-api/pull/4438)
This PR changes all KCP fields under spec.rolloutStrategy mutable in master branch to prevent similar error in future v.0.4.X releases.
>  🐛 Fix KCP spec.rolloutStrategy fields to be mutable

- controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
This PR is fixing issue [4437](https://github.com/kubernetes-sigs/cluster-api/issues/4437). Webhook defaulting in v0.3.15 causing an error during KCP upgrade after upgrading cluster from v0.3.x to v0.3.15. This PR is changing every field under spec.rolloutStrategy mutable.
Fixes #
> 🐛 Fix KCP maxSurge field to be mutable

- api/v1alpha4/cluster_webhook_test.go
- api/v1alpha4/machine_webhook_test.go
- api/v1alpha4/machinedeployment_webhook_test.go
- api/v1alpha4/machinehealthcheck_webhook_test.go
- api/v1alpha4/machineset_webhook_test.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
- exp/addons/api/v1alpha4/clusterresourceset_webhook.go
- exp/addons/api/v1alpha4/clusterresourceset_webhook_test.go
- exp/api/v1alpha4/machinepool_webhook_test.go
- util/defaulting/defaulting.go
Intended to prevent regressions in webhooks when additive changes are made to the API, add generic tests to all of the controllers with defaulting webhooks to ensure that they pass validations.
As a result, found an edge case in CRS on update which is the second commit here (rather than squashing into a single commit).
Fixes #
> 🐛 Add validation testing for defaulting

- api/v1alpha3/cluster_webhook_test.go
- api/v1alpha3/machine_webhook_test.go
- api/v1alpha3/machinedeployment_webhook_test.go
- api/v1alpha3/machinehealthcheck_webhook_test.go
- api/v1alpha3/machineset_webhook_test.go
- controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
- exp/addons/api/v1alpha3/clusterresourceset_webhook.go
- exp/addons/api/v1alpha3/clusterresourceset_webhook_test.go
- exp/api/v1alpha3/machinepool_webhook_test.go
- util/defaulting/defaulting.go
Cherry pick of #4448 on release-0.3.
#4448: Adds a test helper to all mutating webhooks to ensure
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> :bug: Adds a test helper to all mutating webhooks to ensure defaulting passes validation (0.3 backport)

- test/infrastructure/docker/controllers/dockermachine_controller.go
Currently CAPD reconciles machines even when the corresponding cluster is paused. For more details see the linked issue.
Fixes #4426
The corresponding test `capi-e2e.When testing Cluster API working on self-hosted clusters Should pivot the bootstrap cluster to a self-hosted cluster` fails pretty regularly: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main&width=20
(I would say about 5-15%)
> 🐛 capd: do not reconcile machine if cluster or machine is paused

- controlplane/kubeadm/controllers/controller_test.go
This PR temporarily disables KCP's test Observed Generation due to flakes under resource starvation; the fix should be worked in testenv/controller runtime (use the live client, fix https://github.com/kubernetes/kubernetes/issues/80609).
Ref https://github.com/kubernetes-sigs/cluster-api/issues/4461
@davideimola PTAL
> 🐛 Disable test Observed Generation in KCP

- test/framework/deployment_helpers.go
WIP/test PR for now. similar to https://github.com/kubernetes-sigs/cluster-api/pull/4469 just without the kind upgrade
Requires https://github.com/kubernetes/test-infra/pull/21778 *before merge*
Fixes #
> 🌱 Fix upgrade test (CoreDNS verification)

- bootstrap/kubeadm/config/manager/manager.yaml
- bootstrap/kubeadm/main.go
- controlplane/kubeadm/config/manager/manager.yaml
- controlplane/kubeadm/main.go
Add healthprobe for bootstrap provider and controlplane provider.
Fixes #
> ✨ Add healthprobe for bootstrap and controlplane

- cmd/clusterctl/internal/util/objs.go
- cmd/clusterctl/internal/util/objs_test.go
This PR adds deamonsets in list images in clusterctl.
Fixes #4382
> 🌱  include deamonsets in list images in clusterctl

- docs/book/src/tasks/using-kustomize.md
This PR adds documentation on using `kustomize` with Cluster API to provide additional flexibility beyond what `clusterctl config cluster` currently provides.
Fixes #3373
> 📖 Add information on using kustomize with CAPI

- docs/book/src/developer/guide.md
**What this PR does / why we need it**: This PR adds links to some of the videos available online that explain cluster api architecture or include code walkthrough of some components.
> 📖 Link architecture and code walkthrough videos in docs 

- docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Fix figure 1 not found, because `...images/machine-states-preboot/Figure1.png → .../book/src/images/bootstrap-controller.png ` in #1318
Fixes #
> 📖 Fix figure 1 not found

- controlplane/kubeadm/internal/workload_cluster_coredns.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
The upstream image for CoreDNS was renamed from 'k8s.gcr.io/coredns' to `k8s.gcr.io/coredns/coredns`, and this is impacting upgrades of workload clusters from v1.20 to v1.21. 
This PR makes KCP upgrades to account for this change.
Please note that:
- the change applies only to users relying on upstream image repository ('k8s.gcr.io`); users relying on custom repository could continue to use `mrepo.io/coredns` as image name (no changes required).
- starting from CoreDNS 1.8.0, the upstream images requires the `v` prefix on the ImageTag, but this should be taken care by the user when specifying the desired version in KCP.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4463
@sbueringer
> 🐛 Fix CoreDNS upgrade from v1.20 to v1.21

- OWNERS_ALIASES
**What this PR does / why we need it**: Adds @fabriziopandini to cluster-api-maintainers. Fabrizio already has approver rights via his role as sig-cluster-lifecycle-lead and has essentially been acting as a cluster-api maintainer for a while so this makes it explicit.
Also alphabetized the OWNERS_ALIASES file (kept as separate commit).
Fixes #
> 🌱  Add fabriziopandini to cluster-api-maintainers

- api/v1alpha4/machine_types.go
nit: Fixes a typo in comment
n/a
> 🌱 Fixes typo in machine types description

- OWNERS_ALIASES
**What this PR does / why we need it**: @sbueringer has made quality [reviews](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+assignee%3Asbueringer+is%3Aclosed), [contributions](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Asbueringer), and [investigations](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Asbueringer+) to CAPI for past few months. This PR adds him to the reviewers for CAPI. 
Thank you all your contributions so far @sbueringer!
Fixes #
> 🌱  Add sbueringer to cluster-api-reviewers

- controlplane/kubeadm/controllers/controller.go
Condition is always 'true' because 'reterr' is always 'nil'
Fixes #
> 🌱 Fix redundant judgment for reterr==nil

- OWNERS
- OWNERS_ALIASES
- SECURITY_CONTACTS
- Move detiber to emeritus status
- Update security contacts to align with current project leadership
Following up to the thread from slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1618840149091600
> I've been avoiding this for too long, but I'm currently oversubscribed and operating with limited capacity due to the craziness of the past year+ and trying to buckle down and not making progress on the load balancer proposal at the end of last week kind of really drove it home for me.
>
> I'm happy to keep working on it collaboratively with folks for next cycle, including incorporating the things that are potentially blocking for other work, like multiple api endpoints and the etcdadm support work, but I'm not sure that I can guarantee that …
> 📖 Move detiber to emeritus status, update security contacts

- docs/book/src/user/concepts.md
Fix / add links to:
- _control plane_
- _controller_
- `CustomResourceDefinition`
in the main Kubernetes docs.
/kind cleanup
> 📖 Improve links to main Kubernetes docs

- docs/proposals/20210203-externally-managed-cluster-infrastructure.md
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4095
> 📖 CAEP: Add support for infrastructure cluster resources to be managed externally

- controllers/machinedeployment_rolling.go
- controllers/machinedeployment_rolling_test.go
Increase unit test coverage fo machineDeployments rolling upgrades.
First PR related to https://github.com/kubernetes-sigs/cluster-api/issues/4457
> 🌱  Add unit test coverage for machineDeployments. reconcileNewMachineSet

- controllers/machinedeployment_controller.go
Regardless of API UX via default/validation our backend should cover all possible scenarios and error appropriately without panics.
~~I'm also including structural schema defaulting to get feedback on why are we not using it rather than webhooks when possible.~~
Also why are we setting this field as optional? I'd consider any field which prevents the backend from operating successfully to be required, regardless of we choose to default it for UX. Do you agree? @vincepri @CecileRobertMichon @fabriziopandini @JoelSpeed @sbueringer 
Fixes #4509
> 🐛 Check Strategy is not nil to avoid panic

- docs/scope-and-objectives.md
Fix anchor issue in docs/scope-and-objectives.md
Fixes #
> 📖  Fix anchor issue in docs/scope-and-objectives.md

- docs/proposals/20191030-machine-health-checking.md
The proposal originally suggested to add an `ExternalRemediationTemplate`, however the implementation declared `RemediationTemplate`:
https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machinehealthcheck_types.go#L69
This PR modifies the proposal for the sake of being coherent with the code and to avoid confusion for readers.
> 📖 Replace ExternalRemdiationTemplate with RemediationTemplate in MHC proposal

- controlplane/kubeadm/api/v1alpha3/conversion.go
- controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/internal/control_plane.go
- controlplane/kubeadm/internal/filters.go
- docs/book/src/tasks/upgrading-clusters.md
- docs/proposals/20191017-kubeadm-based-control-plane.md
UpgradeAfter is a bit confusing especially now that we have a RolloutStrategy for KCP with maxSurge/maxUnavailable. A rollout doesn't necessarily mean an upgrade is taking place.
Fixes #4534
/kind release-blocking
/area api
> ⚠️ Rename KubeadmControlPlane spec.upgradeAfter to rolloutAfter

- bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
- controlplane/kubeadm/internal/kubeadm_config_map.go
- controlplane/kubeadm/internal/kubeadm_config_map_test.go
Remove unused DNSAddOnType constants from kubeadm/v1alpha4
Fixes #4546
> ⚠️ Remove unused DNSAddOnType constants from kubeadm/v1alpha4

- controlplane/kubeadm/api/v1alpha3/conversion.go
Fixes the conversion added in https://github.com/kubernetes-sigs/cluster-api/pull/4535
Fixes #
> 🐛 Fix KubeadmControlPlane conversion upgradeAfter <=> rolloutAfter

- docs/book/src/developer/guide.md
- docs/book/src/developer/tilt.md
- docs/book/src/reference/ports.md
- docs/proposals/20181121-machine-api.md
- docs/proposals/20200511-clusterctl-extensible-template-processing.md
- docs/proposals/20200602-machine-deletion-phase-hooks.md
- docs/proposals/20201020-capi-provider-operator.md
- docs/proposals/20210203-externally-managed-cluster-infrastructure.md
Fix misspelling in some docs files
Fixes #
> 📖  Fix misspelling in some docs files

- docs/book/src/developer/architecture/controllers/control-plane.md
- docs/book/src/developer/architecture/controllers/support-multiple-instances.md
The table shows one more column in developer/architecture/controllers/control-plane.md 
Fixes #
>  📖 Fix html tag issue in  developer/architecture/controllers/control-plane.md

- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
This PR fix a version check too much restrictive preventing to run `clusterctl config cluster --from` on an empty cluster.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4552
> 🐛 Allow clusterctl config cluster --from on empty clusters

- api/v1alpha4/machinedeployment_webhook.go
- api/v1alpha4/machinedeployment_webhook_test.go
- api/v1alpha4/machinehealthcheck_webhook.go
- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_controller_test.go
- controllers/mdutil/util.go
- controllers/mdutil/util_test.go
- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
- docs/book/src/tasks/upgrading-clusters.md
Because we rely on [1] in this func [2] a string such as "2" would be treated as a percentage for this fields.
[1] https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L164-L168
[2] https://github.com/kubernetes-sigs/cluster-api/blob/3bc596eea96cb27e23c8f2d6c758f6bd56db67b1/controllers/mdutil/util.go#L595-L600
Fixes #4531
> ⚠️ Drop usage of GetValueFromIntOrPercent in favour of GetScaledValueFromIntOrPercent

- docs/book/src/introduction.md
- New title, “Kubernetes Cluster API”, for https://cluster-api.sigs.k8s.io/
- hyperlink to [SIG Cluster Lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#readme) in the introduction
I suggested the new title because although CAPI _is_ a project, the book is about the outcome of the project more than it is about the work to deliver that outcome.
> 📖  Revise CAPI book introduction

- api/v1alpha3/webhook_suite_test.go
- api/v1alpha3/webhook_test.go
- bootstrap/kubeadm/api/v1alpha3/webhook_suite_test.go
- bootstrap/kubeadm/api/v1alpha3/webhook_test.go
- bootstrap/kubeadm/main.go
- controlplane/kubeadm/api/v1alpha3/webhook_suite_test.go
- controlplane/kubeadm/api/v1alpha3/webhook_test.go
- controlplane/kubeadm/main.go
- exp/addons/api/v1alpha3/webhook_suite_test.go
- exp/addons/api/v1alpha3/webhook_test.go
- exp/api/v1alpha3/webhook_suite_test.go
- exp/api/v1alpha3/webhook_test.go
- main.go
- test/helpers/envtest.go
- test/infrastructure/docker/main.go
This PR fixes v1alpha4 conversion webhook failure.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4401
> 🐛 Fix v1alpha4 conversion webhook failure

- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
this PR backports https://github.com/kubernetes-sigs/cluster-api/pull/4553 to `release-0.3`
Fixes #4556
> 🐛 Release-0.3: Allow clusterctl config cluster --from on empty clusters

- go.mod
- go.sum
- test/infrastructure/docker/go.mod
- test/infrastructure/docker/go.sum
Solves an important issue discovered during testing by @fabriziopandini where the webhooks (if conversion was required) would never start https://github.com/kubernetes-sigs/controller-runtime/pull/1512
Fixes #
> 🌱 Update Controller Runtime to v0.9.0-beta.1

- test/e2e/config/docker.yaml
- test/infrastructure/docker/config/default/manager_image_patch.yaml
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/4515#issuecomment-825147782
Some additional context:
* when running the e2e-test.sh script locally it only builds the CAPD image when it doesn't already exist
* as a side effect the `docker-build` target changes the image pull policy and image patches 
* the e2e tests then rely on the changed image name and image pull policy
When I'm now running the tests either with an already existing CAPD image (which is pretty common locally) or directly via the IDE I have to manually modify the patch files and have to be careful so I don't check in and push this change.
With this PR the test framework takes care of the image and image pull policy. When the test is run via the script (e.g. via Prow) the replacements are no-ops.
**What …
> 🌱  Ease local CAPD e2e test execution

- controllers/machine_controller.go
- controllers/machinedeployment_rolling.go
- controllers/machinedeployment_rolling_test.go
Increase unit test coverage fo machineDeployments rolling upgrades. TestReconcileOldMachineSets.
Follow up PR for https://github.com/kubernetes-sigs/cluster-api/pull/4495 related to #4457
Fixes #
> 🌱 Add unit test coverage for machineDeployments. reconcileOldMachineSets

- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
This PR fixes a clusterctl regression preventing to use the clusterctl library for clusterctl config cluster before the management cluster is created or when the management cluster is not yet initialised. 
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4569
> 🐛 fix clusterctl config cluster regression

- controllers/machinedeployment_sync.go
- controllers/machinedeployment_sync_test.go
This drops the presumably unncessary split between scaleMachineSet and scaleMachineSetOperation and cover scaleMachineSet with unit tests.
Follow up for https://github.com/kubernetes-sigs/cluster-api/pull/4495, https://github.com/kubernetes-sigs/cluster-api/pull/4505, https://github.com/kubernetes-sigs/cluster-api/pull/4498. Related to #4457
Fixes #
> 🌱 Refactor MachineSet scaling code and add more tests

- controlplane/kubeadm/controllers/remediation.go
- controlplane/kubeadm/controllers/remediation_test.go
This fix makes it possible for KCP to remediate machines when the etcd member being remediated is missing, might be due to problem during join or due to problem during a previous remediation operation (see attached issues).
Please note that technically this enables remediations when the etcd cluster has two members.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4365
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4472
> 🐛 Allow KCP remediation when the etcd member being remediated is missing

- docs/book/src/SUMMARY.md
- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Noticed it was missing.
/assign @fabriziopandini @sbueringer
> :book: Add v1alpha3 to v1alpha4 migration guide to the book summary

- controlplane/kubeadm/controllers/remediation.go
- controlplane/kubeadm/controllers/remediation_test.go
- docs/proposals/20191017-kubeadm-based-control-plane.md
After merging #4591, there is an improved rule for computing the target quorum for KCP remediation, and this rule already manages properly remediation for etcd clusters with less than 3 members.
This makes it possible to relax some of the existing constraint to enable usage of KCP remediation to fix upgrade errors on dev/CI cluster and/or on production use cases where 3 CP are not an option for any reason.
Example: remediate errors during rollout of single machines control planes
This is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/4594
/assign @yastij
> 🌱 Update KCP remediation docs and message to support > 1 replicas

- util/collections/machine_collection_test.go
Refactors the tests in util/collections/machine_collection_test.go to use plain Go testing instead of ginkgo. The other tests in this package were already there.
Refs #4588
> 🌱 Refactor tests to plain go in util/collections

- docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Fix anchor err and  remove the TOC from the document metadata (L3-L72) in 20190610-machine-states-preboot-bootstrapping.md
Fixes #
> 📖 Fix anchor err in 20190610-machine-states-preboot-bootstrapping.md

- cmd/clusterctl/client/cluster/components.go
- cmd/clusterctl/hack/create-local-repository.py
- test/e2e/clusterctl_upgrade.go
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/docker.yaml
- test/framework/clusterctl/client.go
- test/framework/clusterctl/clusterctl_helpers.go
- test/framework/clusterctl/e2e_config.go
- test/framework/controller_helpers.go
- test/framework/convenience.go
- test/framework/interfaces.go
- test/infrastructure/docker/config/webhook/service.yaml
This PR implements a new E2E test providing a signal on clusterctl upgrades
- init a management cluster with providers in version X
- create a workload cluster
- upgrade providers to version Y using clusterctl upgrade
- check everything works fine (e.g. add a machine to the workload cluster)
- cleanup
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3690
> 🌱 Implement e2e test for clusterctl upgrade

- util/patch/patch_test.go
- util/patch/suite_test.go
Refactors the tests in the util/patch package to use plain Go testing instead of ginkgo.
Refs #4588
> 🌱 Refactor tests to plain go in util/patch

- bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
- bootstrap/kubeadm/controllers/suite_test.go
Refactors the tests in the bootstrap/kubeadm/controllers package to use plain Go testing instead of ginkgo.
Refs #4588
> 🌱 Refactor tests to plain go in bootstrap/kubeadm/controllers

- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Remove redundant judgment condition in controlplane/kubeadm/internal/workload_cluster_coredns_test.go
```go
if err == nil || (err != nil && !apierrors.IsNotFound(err)) {
return false
}
```
if `err == nil`, the conditions after `||` will be not executed, so `err != nil` is redundant.
Fixes #
> 🌱 Remove redundant judgment condition in controlplane/kubeadm/internal/workload_cluster_coredns_test.go

- exp/addons/controllers/clusterresourceset_controller_test.go
- exp/addons/controllers/suite_test.go
Refactors the tests in the exp/addons/controllers package to use plain Go testing instead of ginkgo.
Refs #4588
> 🌱 Refactor tests to plain go in exp/addons/controllers

- controllers/external/util.go
- controllers/external/util_test.go
- controllers/machineset_controller.go
- controllers/machineset_controller_test.go
This PR adds support for annotations to the `util.CloneTemplate` and `util.GenerateTemplate` functions. This is used to pass down annotations from `MachineDeployments`/`MachineSets` to the infrastructure machine resources.
It also extends the tests of the MachineSet controller to verify that labels and annotations are passed down correctly.
Fixes #4543
> ✨ Add annotation support to util.CloneTemplate to pass them down from templates to machines

- test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1alpha3/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/bases/mp.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
- test/infrastructure/docker/templates/cluster-template-development.yaml
Starting with kind v0.11, kind images will have cgroup-root=/kubelet
hard-coded to fix an issue with nested cgroup hierarchies. The hierarchy
below /kubelet is not compatible with systemd cgroupfs (in contrast to
/).
Starting with kubeadm v1.21, kubeadm will default to cgroupDriver
systemd.
Thus, the combination of images from kind >=v0.11 and kubeadm >=v1.21 are
not compatible. To solve this problem we will pin cgroupDriver to cgroupfs
until kind supports the systemd hierarchy with the /kubelet cgroup-root.
Preparation to be compatible with the upcoming newly published kind images. Somewhat related to: https://github.com/kubernetes-sigs/cluster-api/pull/4469
xref:
* more context in https://github.com/kubernetes-sigs/cluster-api/issues/4503#issue-863 …
> 🌱 test/e2e: pin cgroupDriver to cgroupfs

- controllers/remote/cluster_cache_healthcheck_test.go
- controllers/remote/cluster_cache_reconciler_test.go
- controllers/remote/cluster_cache_tracker_test.go
- controllers/remote/suite_test.go
Refactors the tests in the controllers/remote package to use plain Go testing instead of ginkgo.
Refs #4588
> 🌱 Refactor tests to plain go in controllers/remote

- api/v1alpha3/webhook_suite_test.go
- bootstrap/kubeadm/api/v1alpha3/webhook_suite_test.go
- bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types_test.go
- controlplane/kubeadm/api/v1alpha3/webhook_suite_test.go
- controlplane/kubeadm/controllers/suite_test.go
- exp/addons/api/v1alpha3/webhook_suite_test.go
- exp/api/v1alpha3/webhook_suite_test.go
Refactors the tests in the controlplane/kubeadm/controllers package to use plain Go testing instead of ginkgo. There were no ginkgo tests here, so `TestAPIs` was a no-op as far as I can tell.
Also removes dangling comments about "these tests use Ginkgo," because no, they don't. Just the ones under `test/`.
Refs #4588
**Notes**:
With the other two open PRs, this should complete #4588 ("Refactor tests using plain go tests + envtest instead of Ginkgo").
Also in case anyone cares, I quite like `ginkgo` and have used it successfully in several Go projects. Ginkgo 2.0 looks like it makes some nice improvements and I'm excited to use it, just not in these tests. ☮️
> 🌱 Refactor tests to plain go in controlplane/kubeadm/controllers

- api/v1alpha4/cluster_types.go
- api/v1alpha4/cluster_types_test.go
- test/e2e/Makefile
- test/e2e/common.go
- test/e2e/config/docker.yaml
- test/e2e/data/cni/kindnet/kindnet.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-ipv6/kcp-ipv6.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-ipv6/kustomization.yaml
- test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-ipv6/md-ipv6.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/quick_start.go
- test/framework/bootstrap/kind_provider.go
- test/framework/bootstrap/kind_util.go
- test/infrastructure/docker/controllers/dockercluster_controller.go
- test/infrastructure/docker/controllers/dockermachine_controller.go
- test/infrastructure/docker/docker/kind_manager.go
- test/infrastructure/docker/docker/loadbalancer.go
- test/infrastructure/docker/docker/machine.go
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/exp/docker/nodepool.go
quickstart e2e test can be run with:
```
IP_FAMILY=IPv6 \
DOCKER_SERVICE_CIDRS="fd00:100:64::/108" \
DOCKER_POD_CIDRS="fd00:100:96::/48" \
make test-e2e
```
Note: `POD_SUBNET` in kindnet.yaml is now set automatically based on `DOCKER_POD_CIDRS`
`IPFamily()` method on `Cluster` determines the ip family based on the service CIDRs and pod CIDRs. This is used by the docker provider to configure the docker machines accordingly.
Related feature request: https://github.com/kubernetes-sigs/cluster-api/issues/4557
cc @christianang
> ✨ Add ipv6 support to capd

- controllers/machine_controller.go
- controllers/machine_controller_test.go
This is a best effort to filter machines by clusterName and namespace when reconciling from a node event.
Fixes #3831
> 🐛 Add ability for nodeToMachines to filter by clusterName and namespace

- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_controller_test.go
Tidy: changed empty slice declaration, modified var name that collides with pkg name, fixed typo and removed unused func variable
Signed-off-by: Michael Shitrit <mshitrit@redhat.com>
**Not much just a bit of tidy up fixing couple of minor cosmetic stuff**:
> ⚠️ Unexport MachineHealthCheck `patchUnhealthyTargets` method

- .golangci.yml
- test/framework/alltypes_helpers.go
- test/framework/bootstrap/kind_util.go
- test/framework/deployment_helpers.go
- test/framework/kubetest/setup.go
- test/framework/namespace_helpers.go
- test/infrastructure/docker/docker/machine.go
There are a set of lint checks that are disabled by default with
golangci-lint. This enables them by setting exclude-use-default to
false.
This by itself triggers a set of lint failures due to these additional
checks. To by systematic about addressing these potential issues, this
adds those checks back as individual exclusions so they can be addressed
on by one.
This eliminates one of those individual checks by addressing cases of
"Potential file inclusion via variable" where passed in variables are
used in os.OpenFile calls.
Related #4622
> 🌱 Enable excluded lint checks

- controllers/cluster_controller_test.go
- controllers/machine_controller_phases_test.go
- controllers/machinedeployment_controller_test.go
- controllers/machineset_controller_test.go
- controllers/suite_test.go
- controllers/suite_util_test.go
Refactors the tests in the controllers package to use plain Go testing instead of ginkgo.
Fixes #4588
**Notes**:
This is a big PR, although I think the changes fall into obvious patterns. But please let me know if I should break it up to make reviewing easier.
> 🌱 Refactor tests to plain go in controllers

- docs/book/src/user/troubleshooting.md
Adds some guidance how node bootstrap failures can be debugged.
xref: https://github.com/kubernetes-sigs/cluster-api/issues/4583#issuecomment-838825225
Fixes -
> 📖 doc: add node bootstrap troubleshooting doc

- controlplane/kubeadm/internal/etcd/etcd.go
- controlplane/kubeadm/internal/workload_cluster_conditions.go
- util/record/recorder.go
Fix comment issue in controlplane/kubeadm/internal/etcd/etcd.go
Fixes #
> 🌱 Fix comment issue in controlplane/kubeadm/internal/etcd/etcd.go

- bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go
The variable `MissingFileSourceMsg` is not used in bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go.
If `file.Content` and `file.ContentFrom` are allowed to be `nil` at the same time, the `MissingFileSourceMsg` variable is redundant. Otherwise, we should verify that `file.Content` cannot be `nil` when `file.ContentFrom` is `nil`
Fixes #
> 🌱 Cleanup unused variable in bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go

- api/v1alpha4/common_types.go
- api/v1alpha4/machinehealthcheck_types.go
- api/v1alpha4/machinehealthcheck_webhook.go
- api/v1alpha4/machinehealthcheck_webhook_test.go
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_targets.go
- controllers/machinehealthcheck_targets_test.go
- docs/book/src/tasks/healthcheck.md
This add a new explicit 0 second option for the MHC NodeStartupTimeout which allows users to disable the functionality provided by NodeStartupTimeout. This will allow use cases where customers want to explicitly just have MHC with condition based health checks.
Fixes #4468
> ✨  Allow users to disable MHC NodeStartupTimeout

- go.mod
- go.sum
- test/infrastructure/docker/go.mod
- test/infrastructure/docker/go.sum
This change fixes a bug where the conversion webhooks were not actually
being registered and running with envtest.
Related CR PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1532
> :seedling: Update controller runtime to v0.9.0-beta.5

- bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml
- cmd/clusterctl/client/init_test.go
- cmd/clusterctl/internal/util/objs_test.go
- config/ci/manager/manager_auth_proxy_patch.yaml
- config/manager/manager_auth_proxy_patch.yaml
- controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml
- test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
This PR will update kube-rbac-proxy for the release-0.3 branch. This
helps ensure that the CAPI v0.3.x series can be deployed multi-arch. It is a
straight backport from the commit mentioned below with the exception of
fixing merge conflicts around docs.
(cherry picked from commit aa51850504544661eead1685479341bccf9dd39e)
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
> :seedling: upgrade kube-rbac-proxy to v0.8.0

- bootstrap/kubeadm/internal/cloudinit/node.go
- bootstrap/kubeadm/internal/cloudinit/node_test.go
When adding worker nodes the `files` inside cloudinit added each file in `AddtionalFiles` twice.
* by calling `input.prepare` in https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/internal/cloudinit/node.go#L52
* which added the files in `https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/internal/cloudinit/cloudinit.go#L62`
* and second at https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/internal/cloudinit/node.go#L56
The duplicated files are an issue if the maximum size for cloudinit is reached afterwards, when creating a machine.
I propose removing the duplicate in `bootstrap/kubeadm/internal/cloudinit/node.go`'s `NewNode`, because joining a control-plane node also …
> 🐛 prevent duplicated files in cloudinit for cloudinit.NewNode

- cmd/clusterctl/cmd/config.go
- cmd/clusterctl/cmd/config_cluster.go
- cmd/clusterctl/cmd/config_provider.go
- cmd/clusterctl/cmd/generate_cluster.go
- cmd/clusterctl/cmd/generate_provider.go
- cmd/clusterctl/cmd/util.go
This pr refactors `clusterct config cluster` and `cluster config provider` to `clusterctl generate cluster` and `clusterctl generate provider` respectively. Some changes to be noted:
- `clusterctl generate provider` -> generates a yaml template of the provider, this is equivalent to `clusterctl config provider -o yaml`
- `clusterctl generate provider --describe` -> displays information about the provider in text, this is equivalent to `clusterctl config provider`
Fixes #3360 
** There was an earlier [PR](#4467) that aimed to fix the same issue. Based on the …
> ✨ Refactor clusterctl config to clusterctl generate

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/controllers/controller_test.go
- controlplane/kubeadm/controllers/fakes_test.go
- controlplane/kubeadm/internal/cluster.go
**What this PR does / why we need it**: As per https://github.com/kubernetes-sigs/cluster-api/pull/3863#discussion_r512991884 when doing when "Waiting for worker nodes to be deleted first" inside reconcileDelete, KCP should wait for MachinePools to be deleted as well.
Fixes #3880
> 🐛  Wait for MachinePools to be deleted before deleting KCP Machines

- test/e2e/common.go
- test/framework/cluster_proxy.go
- test/framework/docker_logcollector.go
- test/framework/machinepool_helpers.go
**What this PR does / why we need it**:  Currently, framework only looks for Machines when collecting node logs. This PR adds MachinePools and implements `CollectMachinePoolLog` for the Docker provider.
It also fixes the MachinePool upgrade test according to [this comment](https://github.com/kubernetes-sigs/cluster-api/pull/4575#issuecomment-844550606).
Fixes partly https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1352
> ⚠️  Add MachinePool to e2e framework log collector

- test/framework/kubetest/run.go
Signed-off-by: Wilson E. Husin <wilson@husin.dev>
This change is necessary due to kubernetes/kubernetes#99178 where the
conformance image now defines ENTRYPOINT (previously only CMD) which
refers to conformance runner.
Since this test would like to invoke ginkgo directly, overriding
entrypoint is necessary to preserve existing behavior.
Fixes #4660
> 🐛 Invoke ginkgo in kubetest through entrypoint

- docs/book/src/user/quick-start.md
Fix quick-start.md link err
Fixes #
> 📖  Fix quick-start link err

- docs/book/src/developer/testing.md
This PR adds documentation on how to run e2e tests locally. This will help new contributors to avoid the somewhat cumbersome feedback loop via Prow when debugging broken e2e tests or developing new e2e tests.
Fixes #4555
> 📖 doc: add local e2e test execution documentation

- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/infrastructure/docker/docker/machine.go
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
This PR upgrade to the latest Kubernetes patch versions. Those images are built with kind v0.11.0 (or a kind version very close to the release). Goal is to finally only uses images with the new entrypoint script without the PIPEFAIL issue.
For more context please see https://github.com/kubernetes-sigs/cluster-api/issues/4405#issuecomment-847571154
Fixes (hopefully) #4405
> 🐛 test/e2e: upgrade 1.18/1.19 kindest/node images to latest patch version

- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_etcd_test.go
- controlplane/kubeadm/internal/workload_cluster_test.go
This PR makes it possible for CAPI 0.4.x to work with Kubernetes/kubeadm v1.22.0, where the ClusterStatus field inside the Kubeadm-config has been dropped.
Fixes #4423
> ⚠️ KCP: Stop updating and using Kubeadm's ClusterStatus with Kubernetes v1.22

- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/4657. Adds a hint about new linters we added and the bugfix which is at least relevant to CAPA/CAPG/CAPO and probably a few other providers.
Some more context:
* https://github.com/kubernetes-sigs/cluster-api/pull/4649#issuecomment-847142876
* https://kubernetes.slack.com/archives/C8TSNPY4T/p1621871864043200
Related issues:
* CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2414
* CAPO: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/878
* CAPG: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/368
* CAPDO: https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/258
* CAPN: …
> 📖 doc: add linter fix hint to migration doc

- cmd/clusterctl/client/delete.go
- cmd/clusterctl/client/delete_test.go
- cmd/clusterctl/cmd/delete.go
- docs/book/src/clusterctl/commands/delete.md
This PR removes the --namespace flag from clusterctl delete, not necessary anymore given that having many instances of a provider into a management cluster is not supported anymore. 
Please note that more cleanup should follow, as described in https://github.com/kubernetes-sigs/cluster-api/issues/4056#issuecomment-796752547, but I'm breaking down the change in smaller PRs in order to make review easier
Rif #4056
> ⚠️ remove clusterctl delete --namespace flag

- controlplane/kubeadm/internal/cluster_test.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
- controlplane/kubeadm/internal/workload_cluster_etcd_test.go
- test/helpers/envtest.go
CAPI unit test are being flaky lately and one of the errors is 
```
=== Failed
=== FAIL: controlplane/kubeadm/internal TestReconcileEtcdMembers/successfully_removes_the_etcd_member_without_a_node_for_Kubernetes_version_>=_1.22.0 (0.02s)
workload_cluster_etcd_test.go:559: 
Expected success, but got an error:
<*errors.StatusError | 0xc00083dae0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
skipped 16 lines unfold_more
},
Code: 404,
},
}
ConfigMap "kubeadm-config" not found
--- FAIL: TestReconcileEtcdMembers/successfully_removes_the_etcd_member_without_a_node_for_Kubernetes_version_>=_1.22.0 (0.02s)
=== FAIL: controlplane/kubeadm/internal TestReconcileEtcdMembers (0.20s)
```
This PR attempts to fix this error by providing new testenv …
> 🐛 fix TestReconcileEtcdMembers flakes

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/controllers/fakes_test.go
- controlplane/kubeadm/controllers/remediation.go
- controlplane/kubeadm/controllers/remediation_test.go
- controlplane/kubeadm/controllers/scale.go
- controlplane/kubeadm/controllers/scale_test.go
- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_etcd.go
- controlplane/kubeadm/internal/workload_cluster_etcd_test.go
- controlplane/kubeadm/internal/workload_cluster_test.go
This PR makes it possible for CAPI 0.3.x to work with Kubernetes/kubeadm v1.22.0, where the `ClusterStatus` field inside the Kubeadm-config map will be dropped.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4423
> ⚠️ KCP: Stop updating and using Kubeadm's ClusterStatus with Kuberntes v1.22

- hack/boilerplate/boilerplate.py
- hack/verify-shellcheck.sh
- tilt_modules/cert_manager/README.md
- tilt_modules/cert_manager/Tiltfile
- tilt_modules/cert_manager/test/Tiltfile
- tilt_modules/cert_manager/test/test.sh
- tilt_modules/extensions.json
Updates the pinned reference to the [cert_manager](https://github.com/tilt-dev/tilt-extensions/tree/master/cert_manager) tilt extension to include a fix for a startup error (see tilt-dev/tilt-extensions#178). It also hides the cached files in `tilt_modules` from the boilerplate checker and the shellcheck linter.
Fixes #4559
> 🐛 Update cert_manager tilt extension to fix startup bug

- util/conversion/conversion.go
- util/conversion/conversion_test.go
During a rewrite of the tests for the conversion util codebase which
sets and resets the annotation to retain data when doing conversion,
opted to use unstructured objects with a generic old "Machine" type
instead of importing multiple API packages.
The switch to unstructured showed that we weren't setting annotation
properly by calling SetAnnotations, but rather we opted to change the
map coming from GetAnnotations() directly in some cases.
Fixes #4632
/kind release-blocking
> :bug: Use unstructured for conversion utils tests, and fix how we set annotations

- cmd/clusterctl/client/repository/template.go
- cmd/clusterctl/client/yamlprocessor/processor.go
- cmd/clusterctl/client/yamlprocessor/simple_processor.go
- cmd/clusterctl/client/yamlprocessor/simple_processor_test.go
- cmd/clusterctl/cmd/generate_cluster.go
- cmd/clusterctl/cmd/util.go
- cmd/clusterctl/internal/test/fake_processor.go
Makes the output of `clusterctl generate cluster <name> --list-variables` more informative:
Before:
```shell
% clusterctl generate cluster testcluster1 --list-variables
Variables:
- AZURE_CONTROL_PLANE_MACHINE_TYPE
- AZURE_LOCATION
- AZURE_NODE_MACHINE_TYPE
- AZURE_RESOURCE_GROUP
- AZURE_SSH_PUBLIC_KEY_B64
- AZURE_SUBSCRIPTION_ID
- AZURE_VNET_NAME
- CLUSTER_NAME
- CONTROL_PLANE_MACHINE_COUNT
- KUBERNETES_VERSION
- WORKER_MACHINE_COUNT
```
After:
```shell
% clusterctl generate cluster testcluster1 --list-variables
Required Variables:
- AZURE_CONTROL_PLANE_MACHINE_TYPE
- AZURE_LOCATION
- AZURE_NODE_MACHINE_TYPE
- AZURE_SUBSCRIPTION_ID
Optional Variables:
- AZURE_RESOURCE_GROUP         (defaults to "${CLUSTER_NAME}")
- AZURE_SSH_PUBLIC_KEY_B64 …
```
> ✨ Show required and defaults in "clusterctl generate cluster <name> --list-variables"

- test/e2e/kcp_upgrade.go
- test/e2e/kcp_upgrade_test.go
Separate KCP scale in rollout test to improve test parallelization.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4672
> 🌱 Divide KCPUpgrade E2E test suite

- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/cluster/installer_test.go
- cmd/clusterctl/client/cluster/inventory_test.go
- cmd/clusterctl/client/cluster/mover.go
- cmd/clusterctl/client/cluster/mover_test.go
- cmd/clusterctl/client/cluster/upgrader.go
- cmd/clusterctl/client/cluster/upgrader_info_test.go
- cmd/clusterctl/client/cluster/upgrader_test.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/delete_test.go
- cmd/clusterctl/client/init_test.go
- cmd/clusterctl/client/move_test.go
- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/rollout_test.go
- cmd/clusterctl/client/upgrade_test.go
- cmd/clusterctl/internal/test/fake_proxy.go
This PR is a follow up of #4666; it removes watching namespace from fakeObjects & tests.
It includes also two leftover cleanups from the above PR
> 🌱 Follow-up on the removal of clusterctl watching namespace

- Dockerfile
- Makefile
- Tiltfile
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/Dockerfile.dev
- test/infrastructure/docker/Makefile
Maintenance update for our Go toolchain.
Fixes #
> 🌱 Update Go to 1.16.4

- test/e2e/md_scale.go
- test/e2e/md_scale_test.go
- test/e2e/node_drain_timeout.go
- test/framework/machinedeployment_helpers.go
This PR adds a new E2E test to validate MachineDeployment scale scenarios.
Fixes #
> 🌱 add MachineDeployment scale test

- cmd/clusterctl/api/v1alpha3/provider_type.go
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
- cmd/clusterctl/config/manifest/clusterctl-api.yaml
This PR is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/4666; It deprecates the `WatchedNamespace` field in the Provider object which is not required anymore given that clusterctl v1alpha4 does not support multiple instances of a provider.
> ⚠️ Deprecate Provider.WatchedNamespace

- cmd/clusterctl/client/cluster/mover.go
- cmd/clusterctl/client/cluster/objectgraph.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/internal/test/fake_objects.go
- docs/book/src/clusterctl/provider-contract.md
This PR implements the first of a set of changes meant to allow clusterctl move to deal properly with the new model for managing credentials being implemented by providers in v1alpha4.
More specifically this PR makes clusterctl move to consider Secrets from the infrastructure provider's namespace (in addition to secrets from the namespace being moved).
Fixes: #3042
/assign @randomvariable 
/assign @yastij
> 🌱 clusterctl move should consider Secrets from provider's namespace

- cmd/clusterctl/cmd/generate_cluster.go
- cmd/clusterctl/cmd/util.go
https://github.com/kubernetes-sigs/cluster-api/pull/4645 recently introduced the visualisation of default values for template variables.
This PR slightly improves this by ensuring that for well know variables:
- if the template defines defaults, those are considered
- if variables are provided with env vars, those are considered
- if a default value is provided (no matter if in the template or by other means), the variable is listed a optional; otherwise the variable is listed as required.
/cc @mboersma
> 🌱 improve clusterctl generate cluster --list-variables

- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- docs/proposals/20200220-cluster-resource-set.md
- exp/addons/api/v1alpha4/clusterresourceset_types.go
Updated CRS API and documentation that label selector can not be empty.
Fixes #4635
> :book: CRS API does not allow empty selectors

- .golangci.yml
- cmd/clusterctl/client/cluster/cert_manager.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/client/config/providers_client.go
- cmd/clusterctl/cmd/version_checker.go
- cmd/clusterctl/internal/test/fake_reader.go
- cmd/clusterctl/internal/util/cmd.go
- controllers/cluster_controller.go
- controllers/external/tracker.go
- controllers/machine_controller.go
- controllers/machine_controller_noderef.go
- controllers/machine_controller_phases.go
- controllers/machinedeployment_rolling.go
- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_targets.go
- controllers/suite_test.go
- exp/addons/controllers/clusterresourceset_controller.go
- test/e2e/custom_assertions.go
- test/framework/kubetest/setup.go
- test/infrastructure/docker/exp/docker/nodepool.go
- util/secret/certificates.go
Part of our ongoing effort to enable more linters to take the human equation out of enforcing and catching minor issues.
This enables the [exportloopref](https://github.com/kyoh86/exportloopref), [ifshort](https://github.com/esimonov/ifshort), and [nilerr](https://github.com/gostaticanalysis/nilerr) linters.
- exportloopref - no issues found
- ifshort - no issues found
- nilerr - identified a few cases, most which appear to be intentional
Related #4622
> 🌱  Enable exportloopref, ifshort, and nilerr linters

- test/e2e/cluster_upgrade_test.go
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/k8s_conformance_test.go
- test/e2e/kcp_adoption.go
- test/e2e/kcp_adoption_test.go
- test/e2e/kcp_upgrade_test.go
- test/e2e/machine_pool_test.go
- test/e2e/md_scale_test.go
- test/e2e/md_upgrades_test.go
- test/e2e/mhc_remediations_test.go
- test/e2e/node_drain_timeout.go
- test/e2e/node_drain_timeout_test.go
- test/e2e/quick_start_test.go
- test/e2e/self_hosted_test.go
This PR fixes E2E test so we are using a single context object that gets passed down the chain
> 🌱 fix e2e tests using a single context object

- docs/book/src/developer/tilt.md
- docs/book/src/user/quick-start.md
- docs/book/src/user/troubleshooting.md
Adds minor improvements to the cluster api docs based on my recent onboarding
1. Add a troubleshooting section for CAPD when docker runs out of space and has hanging containers
2. Document that `kubectl apply -f capi-quickstart.yaml` might have issues when deleting a cluster
3. Adds a note in Tilt documentation for creating kind with docker settings (required for CAPD)
> 📖 🌱  Minor improvements to Cluster Api book  

- controllers/remote/cluster_cache.go
- controllers/remote/cluster_cache_healthcheck_test.go
- controllers/remote/cluster_cache_reconciler_test.go
- controllers/remote/cluster_cache_tracker_test.go
- controllers/suite_test.go
- controlplane/kubeadm/internal/cluster_test.go
- controlplane/kubeadm/main.go
- exp/addons/controllers/suite_test.go
- main.go
This PR add an new optional `options` argument to the `NewClusterCacheTracker` function.
This new options argument can be used to control the objects that the client should not cache. Defaults to:
```
corev1.ConfigMap{}
corev1.Secret{}
```
It can also be used to pass a desired logger. Defaults to `ctrl.Log.WithName("remote").WithName("ClusterCacheTracker")`
Fixes #4146
> ⚠️ Accept options in remote.NewClusterCacheTracker

- test/infrastructure/docker/cloudinit/writefiles.go
Prevents kube-proxy from modifying sysctls which are now read-only in a recent Linux kernel security update as of May 2021.
Fixes #4712
Requesting that this change is backported as it will affect CAPD in all cases as OS updates are rolled out, including to Docker Machine on MacOS.
>  :bug: Fix for kube-proxy to account for Linux security update

- test/infrastructure/docker/cloudinit/writefiles.go
Cherry pick of #4717 on release-0.3.
#4717: Fix for Linux security update
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> :bug: CAPD: Fix for Linux security update to not set conntrack sysctls

- exp/addons/controllers/clusterresourceset_controller.go
- exp/addons/controllers/clusterresourceset_controller_test.go
- exp/addons/controllers/predicates/resource_predicates.go
When only metadata is cached for secrets, CRS predicates do not have the `type` info and hence does not trigger reconcile when a Secret with CRS secret type (`addons.cluster.x-k8s.io/resource-set`) is created.
This PR caches full Secret object in CRS.
Fixes #4218
> ⚠️  ClusterResourceSet should not use a predicate on secret Type with metadata objects

- bootstrap/kubeadm/config/default/manager_webhook_patch.yaml
- config/default/manager_webhook_patch.yaml
- controlplane/kubeadm/config/default/manager_webhook_patch.yaml
- test/infrastructure/docker/config/default/manager_webhook_patch.yaml
Using dec to set permissions is not intuitive. 420 dec is equivalent to 0644 octal which is already the default.
Fixes #
> 🌱 Drop 420 dec default for secrets

- cmd/clusterctl/client/cluster/cert_manager.go
- cmd/clusterctl/client/config/imagemeta_client.go
- cmd/clusterctl/client/config/imagemeta_client_test.go
Introduce a const for the component to be user for configuring cert-manager image overrides
> 🌱 Introduce const for CertManagerImageComponent value

- .github/dependabot.yml
Disable automatic PRs from dependabot for gomod as it doesn't work well across modules in the same repo. Maintainers will continue to be able to read the log at https://github.com/kubernetes-sigs/cluster-api/network/updates/ 
Fixes #
> :seedling: dependabot: Disable automatic PRs for gomod

- test/e2e/e2e_suite_test.go
- test/framework/cluster_proxy.go
Capture machine logs for the bootstrap cluster in E2E tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3640
> 🌱 Collect bootstrap cluster logs in E2E tests

- test/framework/kubetest/run.go
> :seedling: kubetest: Remove usage of Viper, converting config files to kubetest arguments

- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
**What this PR does / why we need it**: Follow up from #4713. When providers import CAPI test, they need to add this replace statement to avoid getting an error `go: sigs.k8s.io/cluster-api/test@v0.0.0-20210607195256-55f064d1b9fc requires
sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`. Since the replace statement in https://github.com/kubernetes-sigs/cluster-api/blob/55f064d1b9fcf3f0a7b1a32e43559bdff4d3c2cb/test/go.mod#L5 only applies locally, the solution is to add a replace statement in the provider's `go.mod`.
See also discussion in [this slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1623167323286000).
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> 📖 Add replace instructions to v1alpha4 provider doc

- test/framework/kubetest/run.go
Backport of #4761 and #4662
Fixes #
> :seedling: Backport of conformance updates for Kubernetes 1.22

- bootstrap/kubeadm/main.go
- controlplane/kubeadm/main.go
- main.go
- test/infrastructure/docker/main.go
Sets the user agent for the managers.
Fixes #
This is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/4257
Closes #4257
This PR cherry-picks the original authors commit and adds a commit to address the review comments on the PR.
> 🌱 Set UserAgent field in all controller managers

- exp/addons/controllers/clusterresourceset_controller_test.go
- exp/addons/controllers/suite_test.go
- internal/envtest/environment.go
CRS test became flaky after https://github.com/kubernetes-sigs/cluster-api/pull/4723 most probably because I reduced the timeout in the test. 
When an update happens to `ClusterResourceSetBinding`, looks like it does not picked up within the time limit, reading from cache may be causing this much delay.
To solve this, we read `ClusterResourceSetBinding` from a live client now.
Fixes #
> 🐛 CRS test fix: get ClusterResourceSetBinding with live client

- controllers/remote/cluster_cache.go
Align naming on (client)UncachedObjects for ClusterCacheTrackerOptions, ClusterCacheTracker and NewDelegatingClientInput
Fixes #
> 🌱 Use ClientUncachedObjects name consistently

- go.mod
Fixes https://github.com/kubernetes-sigs/cluster-api/pull/4769#discussion_r647720262
> :seedling: go.mod: Add comment about etcd versioning

- api/v1alpha4/common_types.go
- controllers/machine_controller.go
- controllers/machine_controller_test.go
- controllers/machinehealthcheck_controller.go
- controllers/noderefutil/indexer.go
- controllers/noderefutil/indexer_test.go
- controllers/noderefutil/machine.go
- controllers/suite_test.go
- exp/addons/controllers/suite_test.go
- exp/controllers/suite_test.go
- main.go
Moves the logic to register the field indexes out of the controller and into the api package. The indexes are api specific and make more sense in the api package.  
The main block now calls a `setupIndexes` to register the indexes.
Fixes #3778
> 🌱 Move registering field indexes to the `noderefutil` package

- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
As per https://github.com/kubernetes-sigs/cluster-api/pull/4640#issuecomment-857156352 this PR updates instruction for kube-rbac-proxy removal by restoring the original content under  "## Required kustomize changes to have a single manager watching all namespaces and answer to webhook calls"and adding a new dedicated paragraph "## Required kustomize changes to remove Kubeadm-rbac-proxy"
> 📖 update instructions for rbac-proxy removal

- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/repository/components_client_test.go
- cmd/clusterctl/cmd/config_provider.go
- cmd/clusterctl/cmd/generate_provider.go
All the credits for this PR to @aayushrangwala who started this work in https://github.com/kubernetes-sigs/cluster-api/pull/4705
Add --raw flag for the `clusterctl generate provider` subcommand for returning the unprocessed yaml
While doing this change the field `SkipVariables` in the clusterctl library has been renamed into `SkipTemplateProcess` to better reflect what is really doing.
Fixes #4650
> ⚠️ Add --raw flag for clusterctl generate provider subcommand

- cmd/clusterctl/client/init.go
- docs/book/src/SUMMARY.md
- docs/book/src/clusterctl/commands/commands.md
- docs/book/src/clusterctl/commands/generate-cluster.md
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/clusterctl/commands/move.md
- docs/book/src/clusterctl/configuration.md
- docs/book/src/clusterctl/developers.md
- docs/book/src/clusterctl/overview.md
- docs/book/src/clusterctl/provider-contract.md
- docs/book/src/developer/e2e.md
- docs/book/src/tasks/using-kustomize.md
- docs/book/src/user/quick-start.md
This PR Update the book and user messages to use `clusterctl generate cluster` instead of the deprecated `clusterctl config cluster`
> 📖 update book for using clusterctl generate cluster

- test/framework/kubetest/run.go
Cherry pick of #4774 on release-0.3.
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> :bug: unmarshal data to a pointer when parsing kubetest config

- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
During the CAPO `v0.4.0-beta.0` release I verified the migration documentation again and those are some minor adjustments I would suggest.
Fixes #
> 📖 update v1alpha4 migration documentation

- docs/book/src/clusterctl/provider-contract.md
- docs/book/src/reference/glossary.md
- docs/book/src/reference/providers.md
This adds `cluster-api-provider-nested` to the glossary and provider constructs.
Signed-off-by: Chris Hein <me@chrishein.com>
> ✨ Add CAPN to glossary & clusterctl provider

- .golangci.yml
Deduplicates linter list (and I took the chance to sort it a bit more). Moves excludes to exclude-rules. Reasoning behind this is to reduce the "blast radius" of the regex matches.
Partially implements #4622
> 🌱 deduplicate linters, move exclude to exclude-rules

- OWNERS
- OWNERS_ALIASES
- cmd/clusterctl/OWNERS
- controlplane/kubeadm/OWNERS
- docs/book/OWNERS
- test/infrastructure/docker/OWNERS
Spring cleaning for our owners files.
Fixes #
/hold
/assign @CecileRobertMichon @fabriziopandini
> :seedling: Update OWNER files to be more up-to-date

- controllers/machine_controller_phases.go
- controllers/machine_controller_phases_test.go
We're currently in a situation where the "provisioned" phase would never
show up given the sequence of events between the controllers. The
proposal expects "provisioned" to be set whenever a Machine has
a spec.providerID field populated, the infrastructure provider is
reporting ready, and there is no Node associated with the Machine.
Fixes #4779 
/assign @fabriziopandini @CecileRobertMichon 
/cc @onesolpark
> ⚠️ Machine status.phase should be `provisioned` when there is a ProviderID and no Node yet

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Allows mutation of NTP settings in KubeadmControlPlane webhook 
Fixes #4232
> ✨ Make NTP settings mutable in  KubeadmControlPlane webhook validations

- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
- controlplane/kubeadm/internal/workload_cluster_etcd_test.go
- controlplane/kubeadm/internal/workload_cluster_test.go
- test/go.sum
- util/yaml/yaml.go
- util/yaml/yaml_test.go
/kind cleanup
Used yaml.Raw() for better readability of multi line yaml string const
Fixes #4676
> 🌱  Refactor multiline yaml const

- cmd/clusterctl/client/alpha/machinedeployment.go
- cmd/clusterctl/client/cluster/mover.go
Some minor changes to logs to get more information, related to #4816
> :seedling: Provide more information in clusterctl move logs

- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/cluster/template.go
- cmd/clusterctl/client/cluster/template_test.go
- cmd/clusterctl/client/config.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/repository/template.go
- cmd/clusterctl/client/repository/template_client.go
- cmd/clusterctl/client/repository/template_client_test.go
- cmd/clusterctl/client/repository/template_test.go
- cmd/clusterctl/cmd/generate_yaml.go
- As the part of adding --raw flag to clusterctl, the requirements to rename these flags which allows skipping the processing of template using variables
- renamed the variable ListVariableOnly to SkipTemplateProcess in all the files using it including test files and comments
Signed-off-by: Ayush Rangwala <arangwala@vmware.com>
Fixes #4784
> 🌱 Rename ListVariableOnly flag in TemplateInput

- test/e2e/config/docker.yaml
- test/e2e/node_drain_timeout.go
**What this PR does / why we need it**: Previously, we were adding 2 minutes to the nodeDrainTimeout for each node that needed to get deleted in order to come up with the interval timeout in the nodeDrainTimeout test. 2 minutes is not flexible enough for all infrastructure and providers, it should be a configurable timeout.
Now, we take a `node-drain/wait-machine-deleted` interval in the e2e config and calculate the appropriate machine deployment and control plane scale down timeout by adding the provided machine deletion timeout with the nodeDrainTimeout and multiply it by the number of machines.
_There is no behavior change for the existing docker infra node drain test (timeouts stay the same for MD and KCP)_ 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …
> 🌱 Make node drain delete timeout configurable in e2e framework

- .github/dependabot.yml
- .github/workflows/dependabot.yml
For some reason, attempts to turn off dependabot automatic PRs have failed, so instead, here we configure it.
Also adds a Github action that Cluster API Provider AWS is using such that all of the generated code is updated.
Finally, attempt to limit to a single PR at a time...
Fixes #
> :seedling: Dependabot: Change to weekly, enable auto commit of generated code

- test/framework/clusterctl/e2e_config.go
We are developing a new provider,  and we would like to use CAPD and our provider together in the E2E tests while our provider is still Work in Progress. 
We reuse the Cluster API e2e tests in our code so as to avoid duplication. 
Fixes #4790
> 🌱 Allow e2e tests to install more than one infra provider

- controlplane/kubeadm/internal/filters.go
`Machineconfig.spec.joinconfiguration` may be `nil`
Fixes #
> 🐛  Fix potential nil pointer issue

- controlplane/kubeadm/controllers/upgrade.go
`||` should be used in the following condition judgment:
```go
if kcp.Spec.RolloutStrategy == nil && kcp.Spec.RolloutStrategy.RollingUpdate == nil {
return ctrl.Result{}, errors.New("rolloutStrategy is not set")
}
```
Fixes #
> 🐛  Fix conditional judgment issue in upgradeControlPlane

- cmd/clusterctl/api/v1alpha3/metadata_type.go
- cmd/clusterctl/client/cluster/installer.go
- cmd/clusterctl/client/repository/metadata_client.go
- cmd/clusterctl/client/repository/repository_github.go
- cmd/clusterctl/client/repository/repository_github_test.go
- cmd/clusterctl/client/repository/repository_local.go
**What this PR does / why we need it**: Currently clusterctl init gets the latest release by default for each provider and then validates the provider contract using the metadata.yaml file. However, this causes `init` to fail when using an older clusterctl version (eg. v0.3.19) and a newer version is available with a different contract (eg. v0.4.0). This fix will get the latest patch release of the contract release when it does not match the latest release.
This PR targets the main branch, will open a separate cherry pick PR to release-0.3 to fix clusterctl v0.3.x.
Fixes #4856
> 🐛 Use metadata.yaml in github repo to fetch latest release for older contracts

- metadata.yaml
**What this PR does / why we need it**: Adds the v1alpha4 info to the metadata.yaml for clusterctl in release-0.3. Without this change, any new v0.3.x release will be detected as the "latest" Github release which will cause clusterctl v0.4.x to fetch its artifacts and then fail to find the right release series to use as the metadata doesn't contain useful information about the release series for the v1alpha4 contract.
Related to #4856
> 🌱  Add v1alpha4 to metadata.yaml

- bootstrap/kubeadm/config/manager/manager.yaml
- config/manager/manager.yaml
- controlplane/kubeadm/config/manager/manager.yaml
- test/e2e/config/docker.yaml
- test/infrastructure/docker/config/manager/manager.yaml
During the removal of kube-rbac-proxy the e2e test metric collection
broke. The easiest way to fix it is to set the default value of the
metrics-bind-addr in our manager.yaml files and then replace it via our
e2e test framework.
See linked issue
Fixes #4794
> 🐛 fix metric collection in e2e test

- docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Changed the clusterctl version to v0.4 in the quickstart (by changing version:"0.3.x" to version:"0.4.x") and added a warning that says if you are you using an infrastructure provider that hasn't released v1alpha4 yet, use https://release-0-3.cluster-api.sigs.k8s.io/user/quick-start.html
Fixes #4888
> 📖  Update quickstart clusterctl install instructions to v0.4

- controllers/machine_controller.go
I just set up my local environment on mac and got the following error:
```bash
controllers/machine_controller.go:276:36: directive `// nolint:ifshort` is unused for linter "ifshort" (nolintlint)
isDeleteNodeAllowed := err == nil // nolint:ifshort
```
When I remove the `nolint` I get a finding of the `ifshort` linter, so we definitely need the `nolint`. I'm not sure why we don't get the error in CI but apparently all our other `nolint`'s don't have a space between `//` and `nolint`.
Fixes #
> 🐛  fix golangci-lint nolint:ifshort

- test/framework/cluster_proxy.go
I guess this got lost during the refactoring. We have to calculate the lb container name based on the cluster name by appending `-lb`. This only affected certain e2e tests on MacOS.
Fixes #
/cc @stmcginnis (just fyi)
> 🐛 e2e tests: fix fix-kubeconfig for mac

- cmd/clusterctl/api/v1alpha3/metadata_type.go
- cmd/clusterctl/api/v1alpha3/metadata_type_test.go
- cmd/clusterctl/client/repository/repository_github_test.go
Backport https://github.com/kubernetes-sigs/cluster-api/pull/4912 to release-0.3
Fixes #4889
> 🐛 clusterctl: use newest release series of same contract

- cmd/clusterctl/api/v1alpha3/metadata_type.go
- cmd/clusterctl/api/v1alpha3/metadata_type_test.go
- cmd/clusterctl/client/repository/repository_github_test.go
Some providers have multiple releases with the same
contract. clusterctl should default to using release
for the given contract.
Used the latest release series of a provider if multiple releases use the same contract.
Fixes #4889
> 🐛  clusterctl: use newest release series of same contract

- docs/book/src/user/quick-start.md
**What this PR does / why we need it**: #4921 removed the base64 encoded variables earlier but there is an issue which causes the azure.json to not be generated properly when those are not set. Adding back for now until we figure out a better solution.
Fixes #
> :book: Add back base64 encoded CAPZ quickstart variables for creds

- util/defaulting/defaulting.go
fix DefaultValidateTest ensuring that defauting web hooks are consistent with validation web hooks.
In order to do so, the func takes an object and passes it to the defaulting and validation web hooks; for the upgrade web hook the object is used both as current and old value, however old value is not defaulted (as it will happen in the real system).
This PR fixes this ensuring that both  current and old value are defaulted before calling the validate upgrade webhook
Fixes #
> 🐛 fix DefaultValidateTest ensuring old object gets defaulted too

- test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
- test/framework/kubernetesversions/data/kustomization.yaml
- test/framework/kubernetesversions/template.go
This PR changes the way we patch the `ci-artifacts.sh` script. Up until now we used strategic merge patch. This overwrote the `files` and `preKubeadmCommands` arrays. That was the reason this functionality could not be reused in CAPO and CAPZ (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1018#discussion_r515363781). The new version is implemented with JSON patch and just appends the script to the arrays. Because we append the script, it's also possible to run some provider-specific scripts before.
Further improvements:
* only download control plane images on control plane nodes
* use wget to download artifacts instead of gsutil so save a few minutes because we don't have to install gsutil
Some more details on the linked issue. …
> 🌱 test/framework: improve the way we inject the ci-artifacts script

- docs/book/src/user/quick-start.md
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/framework/machine_helpers.go
- test/infrastructure/container/docker.go
- test/infrastructure/docker/docker/machine.go
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
> I'm +1 to jump to a newer releases in the quick-start and in the e2e; ideally we should stay in lockstep with K8s.
If we are going for 1.21 let's jump to the .2 path release, because it contains the fix for CoreDNS image and for etcd ephemeral storage.
> https://github.com/kubernetes-sigs/cluster-api/pull/4898#discussion_r666776466
Fixes #
>  🌱  Upgrade quickstart and e2e tests to Kubernetes v1.21.2

- cmd/clusterctl/client/client.go
- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/cluster/mover.go
- cmd/clusterctl/client/cluster/mover_test.go
- cmd/clusterctl/client/cluster/objectgraph.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/client/move.go
- cmd/clusterctl/client/move_test.go
- cmd/clusterctl/cmd/backup.go
- cmd/clusterctl/cmd/restore.go
Implements the Backup and Restore methods on the objectMover
Backup will iterate objects in a given namespace, building the object graph, to then save them to a provided directory as a set of json files. These files will appear as:
```
{configured-directory}/object-kind_object-name_object-namespace.yaml
```
Restore will iterate object files using a given glob in a configured directory to re-build an object graph. Once all files are iterated and the object graph is created, re-applies those objects to a given management / bootstrap cluster with provided client.
These methods can then be used to create a "backup / restore" cycle where a clusters objects are saved and restored latter.
Fixes #3441
This PR supersedes #4786 which was based on the 0.3 branching. Hope to get this into the 0.4.0 …
> ✨ Implements Backup and Restore for objectMover

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
Adjusts ClusterClass proposal to make clear that we also set the `.spec.infrastructureRef` on the `Cluster` resources.
(sorry I know almost not worth the PR)
Fixes #
> 📖  Add detail about ClusterClass reconciliation in ClusterClass proposal

- api/v1alpha4/cluster_webhook.go
- api/v1alpha4/machine_webhook.go
- api/v1alpha4/machinedeployment_webhook.go
- api/v1alpha4/machinehealthcheck_webhook.go
- api/v1alpha4/machineset_webhook.go
- bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go
- bootstrap/kubeadm/config/webhook/manifests.yaml
- config/webhook/manifests.yaml
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/config/webhook/manifests.yaml
- exp/addons/api/v1alpha4/clusterresourceset_webhook.go
- exp/api/v1alpha4/machinepool_webhook.go
- test/infrastructure/docker/api/v1alpha4/dockermachinetemplate_webhook.go
- test/infrastructure/docker/config/webhook/manifests.yaml
Admission Review was previously set to only accept v1beta1 objects given
that Controller Runtime didn't support v1 (even though the two revisions
are effectively the same). This change adds support for both within our
manifests.
Fixes #
> :bug: Webhook registration should accept both v1 and v1beta1 admissions

- api/v1alpha4/machinehealthcheck_webhook.go
- api/v1alpha4/machinehealthcheck_webhook_test.go
Extends the validation webhook of MachineHealthCheck to ensure that the namespace of the MHC and its RemediationWebhook are identical.
It also defaults the namespace of the RemediationWebhook to the namespace of the MHC so it can be omitted (same as a lot of other resources).
The namespace set in the reference [is ignored](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinehealthcheck_controller.go#L370), that's why it shouldn't be allowed to be different from the MHC's namespace.
Fixes #4943
> 🐛 validate namespace of MHC remediation template

- .golangci.yml
- cmd/clusterctl/client/config/reader_viper_test.go
- cmd/clusterctl/cmd/config_provider.go
- cmd/clusterctl/cmd/config_repositories.go
- cmd/clusterctl/cmd/generate_yaml_test.go
- cmd/clusterctl/cmd/upgrade_plan.go
- cmd/clusterctl/cmd/util.go
- cmd/clusterctl/cmd/version_checker_test.go
- controllers/machinedeployment_sync.go
- controllers/mdutil/util.go
- controllers/remote/cluster_cache_healthcheck_test.go
- internal/envtest/environment.go
I think it makes sense to either handle errors or ignore them explicitly
Implements a part of #4622
> 🐛  fix unhandled errors

- controlplane/kubeadm/config/default/kustomization.yaml
See details in the issue.
Diff in the generated manifests:
Fixes #4935
> 🐛 fix KCP ClusterRole aggregation

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
nit: Fixes the diagram link in the ClusterClass proposal. Due to the incorrect markdown, the sequence diagrams are not correctly displayed on the page.
Fixes # n/a
> 📖 Fixes incorrect diagram links for CC proposal

- docs/book/src/developer/providers/implementers-guide/overview.md
- hack/ensure-kubectl.sh
- scripts/ci-e2e-lib.sh
- test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
- test/framework/kubernetesversions/versions.go
- test/infrastructure/docker/Dockerfile
Sort of a follow-on to https://github.com/kubernetes-sigs/cluster-api/pull/4420
The only time a kubernetes GCS bucket name should be showing up in a
hardcoded URI is if gsutil is being used (e.g. gsutil cp gs://foo/bar .)
Otherwise, for tools like curl or wget, dl.k8s.io is much nicer for us
as a project, since we can transparently change where that redirects to
without having to change code everywhere
These changes will mean no changes will be necessary to accommodate a
gs://kubernetes-release -> gs://k8s-release migration equivalent of the
CI migration we're going through right now
(https://github.com/kubernetes/k8s.io/issues/2318)
EDIT: this also catches one last mention of `kubernetes-release-dev` which I've called out in a review comment below …
> 🌱 Use dl.k8s.io instead of hardcoded GCS URIs

- test/infrastructure/docker/third_party/forked/loadbalancer/const.go
Alpine has several challenges, so there's a long running effort in
upstream kubernetes to switch to distroless/debian based images.
Kind recently moved to a non-alpine image, so let us please switch to
the same as well:
https://github.com/kubernetes-sigs/kind/pull/2373
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
Fixes #
> ✨ Switch to non-alpine kindest/haproxy version

- bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
- bootstrap/kubeadm/main.go
- controllers/remote/cluster_cache_reconciler.go
- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/main.go
- main.go
[In this PR](https://github.com/kubernetes-sigs/cluster-api/pull/4119) we added the watch label to be able to run multiple manager instances, but we missed some controllers. This PR fixes that.
> 🐛 Missing watch label to allow multiple manager instances

- controllers/machine_controller_noderef.go
- controllers/machine_controller_noderef_test.go
- controllers/noderefutil/indexer.go
- controllers/noderefutil/providerid.go
- controllers/remote/cluster_cache.go
- controllers/remote/cluster_cache_healthcheck_test.go
- controllers/remote/cluster_cache_tracker_test.go
- controllers/suite_test.go
- controlplane/kubeadm/internal/cluster_test.go
- controlplane/kubeadm/main.go
- main.go
Add a providerID index to get nodes rather than requiring looping over all of them every time.
Fixes #4518
> 🌱 Add providerID index to get nodes

- test/infrastructure/docker/third_party/forked/loadbalancer/const.go
Alpine has several challenges, so there's a long running effort in upstream kubernetes to switch to distroless/debian based images.
Kind recently moved to a non-alpine image, so let us please switch to the same as well:
github.com/kubernetes-sigs/kind/pull/2373/commits/8f293e11855e6545789ed81dd3507fc6c8359ce8
This is a cherry pick of https://github.com/kubernetes-sigs/cluster-api/pull/4964
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
Fixes #
> 🌱 Switch to non-alpine kindest/haproxy version

- controllers/cluster_controller.go
This patch makes the cluster controller tolerant to the missing control plane and infrastructure references in the case of a cluster with `spec.Topology != nil` (cluster with topology definition)
The existing behavior would continue if the topology definition is absent.
Fixes #4909
> 🌱 Adds topology check to cluster controller

- docs/book/src/developer/guide.md
- docs/book/src/developer/providers/implementers-guide/overview.md
- docs/book/src/developer/tilt.md
The installation instructions for kustomize have moved. This updates
references to that documentation to point to the new home.
> 📖 Update links for kustomize installation

- Tiltfile
- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/clusterctl/commands/upgrade.md
- docs/book/src/clusterctl/configuration.md
- docs/book/src/developer/guide.md
- docs/book/src/user/quick-start.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
cert-manager v1.1.0 does not work on Kubernetes v1.22.
Note: 
* cert-manager >= v1.2.0 does not work on Kubernetes < v1.16.0 (https://github.com/jetstack/cert-manager/releases/tag/v1.2.0) (but we don't support management clusters on Kubernetes < v1.16.0 with CAPI v0.4.x anyway)
* they are using client-go v1.21.0 now, there was no other mention of a Kubernetes version requirement in release notes
xref release notes:
* https://github.com/jetstack/cert-manager/releases/tag/v1.2.0
* https://github.com/jetstack/cert-manager/releases/tag/v1.3.0
* https://github.com/jetstack/cert-manager/releases/tag/v1.4.0
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> ✨ upgrade cert-manager to v1.4.0

- test/e2e/config/docker.yaml
This PR updates the clusterctl version we use for our clusterctl upgrade e2e test. I assume we want to use more or less the latest version.
Fixes #
> 🌱 upgrade clusterctl used for e2e test upgrade tests to v0.3.22

- Makefile
- docs/developer/releasing.md
> :book: Update how we generate release notes

- config/rbac/role.yaml
- controllers/clustertopology_controller.go
- controllers/clustertopology_controller_compute.go
- controllers/clustertopology_controller_sync.go
- main.go
This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 
This PR creates the scaffolding for the `ClusterTopologyContoller`.
As defined in the linked issue, it introduces a new UnstructuredCachingClient, set up watches, object tracker and creates the skeleton for the reconcile loop that will be completed by follow up PRs
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4933
> ✨Add ClusterTopologyController scaffolding

- api/v1alpha4/common_types.go
- controllers/machine_controller.go
- controllers/machine_controller_noderef.go
- controllers/noderefutil/indexer.go
- controllers/noderefutil/indexer_test.go
- controllers/suite_test.go
- exp/addons/controllers/suite_test.go
- exp/controllers/suite_test.go
- main.go
Problem:
There's a lag between the nodes coming up and the machine nodeRef being set.
Causes:
The aggressive requeue=true whe a node is not found [1] results in exponential backoff for the controller.
The nodeToMachine function relies on the nodeRef [2] resulting in a chicken-egg issue.
Solution:
Stop aggressive requeue=true.
Let nodeToMachine find machines to nodes by providerID.
Result:
When the node shows up, it triggers a an event.
machineToNode maps the Node to a Machine.
The nodeRef is set immediately after the Node shows up.
[1] https://github.com/kubernetes-sigs/cluster-api/blob/70e959802aa7722efefe69158e868d7ff3eec4be/controllers/machine_controller_noderef.go#L74
[2] https://github.com/kubernetes-sigs/cluster-api/blob/37c862b5c9256d7ae65cd8e …
> 🐛 Drop aggressive requeue=true and find machines to nodes by providerID

- controlplane/kubeadm/internal/workload_cluster_conditions.go
- controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Surfaces an error when the etcd node check in KCP fails, which helps with troubleshooting.
> 🐛 Surface etcd node check error in KCP

- bootstrap/kubeadm/main.go
- controlplane/kubeadm/main.go
- main.go
- test/infrastructure/docker/main.go
Currently the readiness of our controller deployments does not include the webhook server. I.e., the deployment is already ready even when the webhooks are not up.
So when we implement a wait for deployments ready in #4934 the current PR will help that the wait for readiness will also include the webhook server. This is crucial because otherwise there's a chance that clusterctl immediately fails when we try to deploy resources.
Note: This controller-runtime health check is only available since v0.9.3 (https://github.com/kubernetes-sigs/controller-runtime/pull/1598)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> ✨ add webhook readiness and health check

- controllers/clustertopology_controller_compute.go
- controllers/clustertopology_controller_compute_test.go
This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 
This PR add a first set of test utils/utils that will simplify the work for https://github.com/kubernetes-sigs/cluster-api/issues/4970 and https://github.com/kubernetes-sigs/cluster-api/issues/4971 (and also subsequent PRs)
@killianmuldoon
> 🌱 Add test utils for cluster class

- docs/book/src/developer/architecture/controllers/control-plane.md
This PR ensures the control plane contract documents fields that will be used by the ClusterClass for handling
- the Kubernetes version for control plane machines
- control plane machines metadata
- control plane infrastructure templates.
NOTE: This field is a requirement for ClusterClass compatibility and doesn't necessarily apply to current provider offerings.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4948
> 🌱  Extend the ControlPlane contract defining version and infrastructure machine fields for ClusterClass compat

- test/infrastructure/container/docker.go
If the docker engine is restarted, either through a service restart or a
full system reboot, the containers created by CAPD are left in a stopped
state.
This adds the restartPolicy setting to the Docker container creation so
that containers will be automatically restarted on service restart
unless the user has explicitly stopped the container prior to the
restart.
Fixes #5020
> ✨ CAPD: set container restartPolicy to unless-stopped

- .golangci.yml
- test/framework/clusterctl/client.go
- test/framework/docker_logcollector.go
- test/framework/kubernetesversions/template.go
Let's rather ignore the individual cases of this finding in our tests then the whole finding.
For details, please see: https://github.com/kubernetes-sigs/cluster-api/issues/4622#issuecomment-876262757
Fixes #4622
> 🌱  explicitly ignore command injection (in tests)

- controlplane/kubeadm/controllers/controller_test.go
- controlplane/kubeadm/controllers/helpers_test.go
- controlplane/kubeadm/controllers/remediation_test.go
- controlplane/kubeadm/controllers/scale_test.go
- controlplane/kubeadm/controllers/status_test.go
- controlplane/kubeadm/controllers/upgrade_test.go
- controlplane/kubeadm/internal/cluster_test.go
Partly solves #4629.
Updates namespace generation in controlplane pkg tests.
> 🌱 Randomly generated namespace in controlplane pkg tests

- bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types_test.go
- bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
- bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
- bootstrap/util/configowner_test.go
Partly solves #4629. 
Updates namespace generation in bootstrap pkg tests.
> 🌱 Randomly generated namespace in bootstrap pkg tests

- util/patch/patch_test.go
- util/util_test.go
Partly solves #4629.
Updates namespace generation in util pkg tests.
> 🌱 Randomly generated namespace in util pkg tests

- cmd/clusterctl/client/cluster/client.go
- cmd/clusterctl/client/cluster/proxy.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/client/move.go
- cmd/clusterctl/internal/test/fake_proxy.go
See issue for details.
Partially implements #4966 (1., only clusterctl in this PR)
> ✨ v0.3.x: block clusterctl init and move on Kubernetes v1.22

- docs/book/src/reference/versions.md
See issue.
I think we should only try to keep the supported versions of the current book up-to-date (it's hard enough). So I wouldn't fix the old 0.3 book. Or at least as we're currently referencing the current and the last release series in our matrix and I wouldn't maintain it in both books.
Fixes #4988
> 📖 update supported Kubernetes versions

- controlplane/kubeadm/main.go
This PR configures the KCP ClusterCacheTracker to stop caching: ConfigMaps, Secrets, Pods, Deployments and DaemonSets of workload clusters.
> It might make more sense for KCP to always use a live client to read the status of a Cluster during reconciliation. Caching all these kind of objects increases memory usage of our controllers by a large factor, especially with management clusters that are in charge of a high number of workload clusters.
> Vince in https://github.com/kubernetes-sigs/cluster-api/pull/5033#issuecomment-889214342
Originally the plan was to implement it as a follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/4104#discussion_r566180107. But I guess we lost track of …
> 🌱 KCP: stop caching ConfigMap, Secret, Pod, Deployment and DaemonSet of workload clusters

- controlplane/kubeadm/controllers/upgrade.go
- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_test.go
See linked issue
Partially implements #4966
> ✨ v0.3.x: KCP: block mgmt cluster updates to v1.22.0

- controllers/cluster_controller_test.go
- controllers/external/util_test.go
- controllers/machine_controller_node_labels_test.go
- controllers/machine_controller_phases_test.go
- controllers/machine_controller_test.go
- controllers/machinedeployment_controller_test.go
- controllers/machinehealthcheck_controller_test.go
- controllers/machineset_controller_test.go
- controllers/mdutil/util_test.go
- controllers/remote/cluster_cache_healthcheck_test.go
- controllers/remote/cluster_cache_reconciler_test.go
- controllers/remote/cluster_cache_tracker_test.go
- controllers/remote/cluster_test.go
- controllers/suite_test.go
Partly solves https://github.com/kubernetes-sigs/cluster-api/issues/4629. Only `controllers` pkg is updated.
Use of randomly generated namespaces was started in https://github.com/kubernetes-sigs/cluster-api/pull/4698. This PR continues it's work in the same manner. `env.CreateNamespace` is used everywhere internal `envtest` package is used for testing. And everywhere else(for example tests that use `fake.Client` from `controller-runtime`) it replaces `"default"` and `"test"` namespace names with constant `metav1.NamespaceDefault`.
> 🌱 Randomly generated namespace in controllers pkg tests

- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/repository/components_test.go
- cmd/clusterctl/client/repository/template.go
Currently when you deploy to a single namespace the webhooks do not have the correct namespaces specified. 
This PR fixes all the references.
Fixes #5010
> 🐛 Fix webhook service references when the namespace is changed

- docs/book/src/clusterctl/overview.md
**What this PR does / why we need it**:  In `Overview of clusterctl` page the reference to `use clusterctl generate cluster to spec out workload clusters` goes to https://cluster-api.sigs.k8s.io/clusterctl/commands/config-cluster.html which returns `Document not found (404)`
> 📖 update generate cluster link 

- api/v1alpha4/condition_consts.go
- controllers/machine_controller.go
Pod deletion and volume detach happen asynchronously, so pod could be deleted before volume detached from the node
When deleting a machine, this could cause issues for some storage provisioner, for example, vsphere-volume this is problematic because if the node deleted before volume detaching success, then the underline VMDK will be deleted together with the Machine
This PR added a fix to wait for volume detach from the node after node draining. 
Fixes #4707
> 🐛 Wait for volume detach after node drain

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
This PR improves the ClusterClass proposal could be improved in explaining impact for the control plane providers, detailing 
- impacts on different control plane flavours:
- conventions for implementing new template types 
- expected behaviour for template <-> object reconciliation
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5018
> 📖 Clarify template conventions and template reconciliation rules in the ClusterClass proposal

- controllers/clustertopology_controller_mergepatch.go
- controllers/clustertopology_controller_mergepatch_test.go
This pr implements a twoWaysPatchHelper for ClusterClass reconciliation ensuring that
- enforces that all the fields in the desired object for which a value is defined are reflected in the current object.
- all the other values in the current object are preserved
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5032
> 🌱 Implement twoWayPatchHelper for ClusterClass reconciliation

- internal/envtest/environment.go
Update the host argument in the envtest Environment to listen
on 'localhost' explicitly instead of defaulting to the local IP.
This change fixes firewall issues with unit tests seen on recent
(11.5.X+) versions of MacOS.
Fixes #5047
> 🐛  Update envtest listen address to localhost

- test/e2e/cluster_upgrade.go
- test/e2e/kcp_upgrade.go
- test/e2e/machine_pool.go
- test/e2e/md_rollout.go
- test/e2e/md_rollout_test.go
**What this PR does / why we need it**: Originally in our E2E test we implemented upgrade tests for single CAPI resources:
- KCPUpgradeSpec
- MachineDeploymentUpgradesSpec
- MachinePoolSpec
This is now superseded by ClusterUpgradeConformanceSpec, which upgrades all the resources, makes sure CP is upgraded before nodes (thus being compliant with K8s recommendations) and runs conformance on the resulting test.
This PR refactors the legacy test to remove partial upgrade as described in the issue:
- KCPUpgradeSpec might still have sense, because it tries different topologies of control plane vs what we usually have in KCPUpgradeSpec
- MachineDeploymentUpgradesSpec should be re-focused to test rollout when the infrastructure template changes.
- MachinePoolSpec should be re-focused on test …
> 🌱 Deprecate partial upgrade tests

- cmd/clusterctl/client/cluster/mover.go
Without this change clusterctl backup panics because of an uneven amount of key-value arguments. The unit test didn't catch this as it's using the `NullLogger`
Fixes #
> 🐛 fix panic in clusterctl backup

- docs/book/src/SUMMARY.md
- docs/book/src/tasks/updating-machine-templates.md
- docs/book/src/tasks/upgrading-clusters.md
Adds the missing documentation on how to update bootstrap templates we identified in: https://github.com/kubernetes-sigs/cluster-api/issues/4910#issuecomment-888483580
Fixes #
> 📖 doc: add update bootstrap template doc

- api/v1alpha4/clusterclass_webhook.go
- api/v1alpha4/clusterclass_webhook_test.go
- api/v1alpha4/common_types.go
- controllers/external/util.go
- controllers/machinehealthcheck_controller.go
- controllers/machineset_controller.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/controllers/helpers.go
This PR adds additional validation to the ClusterClass type.
Fixes #4940
> 🌱  add additional validations for clusterclass type

- test/framework/clusterctl/clusterctl_helpers.go
Currently, the `DisableMetricsCollection` also disables watching logs of all deployments except the first one. I assume that's not intended.
Note: this field is not used by any of our e2e tests in the `cluster-api` repo
Fixes #
> 🌱  test/framework: disable metrics collection should not disable watching deployment logs

- test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_webhook.go
- test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_webhook_test.go
Prevent DockerClusterTemplate to be used if ClusterTopology feature flag is false.
This PR is part of [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md) implementation.
Fixes #5066
> 🌱 gate DockerClusterTemplate usage with ClusterTopology feature gate

- controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_webhook_test.go
Prevent KubeadmControlPlaneTemplate to be used if ClusterTopology feature flag is false. 
This PR is part of [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md) implementation.
Fixes #5065
> 🌱 gate KubeadmControlPlaneTemplate usage with ClusterTopology feature gate

- api/v1alpha3/suite_test.go
- bootstrap/kubeadm/api/v1alpha3/suite_test.go
- bootstrap/kubeadm/controllers/suite_test.go
- bootstrap/util/suite_test.go
- controllers/remote/suite_test.go
- controllers/suite_test.go
- controlplane/kubeadm/api/v1alpha3/suite_test.go
- controlplane/kubeadm/controllers/suite_test.go
- controlplane/kubeadm/internal/suite_test.go
- exp/addons/api/v1alpha3/suite_test.go
- exp/addons/controllers/suite_test.go
- exp/api/v1alpha3/suite_test.go
- exp/controllers/suite_test.go
- internal/envtest/environment.go
- util/collections/suite_test.go
- util/patch/suite_test.go
> 🌱 Migrate envtest setup to envtest.Run, add CAPI_DISABLE_TEST_ENV option

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/controllers/upgrade.go
- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_etcd.go
- controlplane/kubeadm/internal/workload_cluster_etcd_test.go
This PR makes local etcd's extra args in KCP mutable.
Closes https://github.com/kubernetes-sigs/cluster-api/issues/5043
> ✨ Make local etcd's extra args in KCP mutable

- api/v1alpha4/index/cluster.go
- api/v1alpha4/index/cluster_test.go
- api/v1alpha4/index/index.go
This PR adds an index for the `cluster.spec.topology.class`. 
This is to enable efficiently finding clusters that are stamped from a given ClusterClass.
Fixes #4931
> ✨  create index for cluster.spec.topology.class

- controllers/topology/cluster_class_test.go
- controllers/topology/object_builders_test.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 
This PR is about implementing reconcile current and desired state for the infrastructureCluster object in a managed topology.
NOTE: this PR will wait for https://github.com/kubernetes-sigs/cluster-api/issues/5038 to be implemented first
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5036
> 🌱 Reconcile infrastructure cluster for managed topologies

- docs/book/src/user/quick-start.md
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/docker/machine.go
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
Regular update to the latest stable Kubernetes release
Fixes #
> 🌱  Upgrade quickstart and e2e tests to Kubernetes v1.22.0

- api/v1alpha4/common_types.go
- controllers/topology/cluster_class.go
- controllers/topology/controller.go
- controllers/topology/current_state.go
- controllers/topology/current_state_test.go
- controllers/topology/object_builders_test.go
- controllers/topology/types.go
- controllers/topology/util.go
- controllers/topology/util_test.go
Implementation for reading the current state of a cluster managed
by a ClusterClass to the cluster topology controller. This will
allow the controller to see the observed state of a managed
cluster and use the information during reconcilliation.
Fixes #4971
> ✨ Implement getClusterState for topology controller

- controlplane/kubeadm/config/manager/manager.yaml
- controlplane/kubeadm/main.go
- test/infrastructure/docker/config/manager/manager.yaml
Pass the ClusterTopology feature flag to CAPD and KCP, used for allowing creation of new template types
> 🌱 Pass the ClusterTopology feature flag to CAPD and KCP

- controllers/topology/controller.go
Implements the `ClusterReconciler.clusterClassToCluster` function.
Fixes #5076
> ✨ implement ClusterReconciler.clusterClassToCluster function

- OWNERS_ALIASES
- controllers/topology/OWNERS
@ykakarap has made quality [contributions](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Aykakarap) to CAPI so far. This PR adds him to the reviewers for the CAPI controllers/topology package.
Thank you all your contributions so far @ykakarap!
Fixes #
> 🌱 Add ykakarap to cluster-api-topology-reviewers

- cmd/clusterctl/client/cluster/installer.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/cmd/init.go
- cmd/clusterctl/internal/util/objs.go
- cmd/clusterctl/internal/util/objs_test.go
`clusterctl init` should wait for the cluster to be 'ready' before exiting.
This includes:
Fixes #4474
> ⚠️   clusterctl init: wait for deployments to be ready

- test/e2e/cluster_upgrade.go
- test/framework/clusterctl/clusterctl_helpers.go
Enables providers to use ClusterUpgradeConformanceSpec even if they do not implement MachinePools.
> :sparkles: [e2e framework] Allow cluster upgrade spec to work without MachinePools

- scripts/ci-e2e-lib.sh
- test/e2e/common.go
- test/e2e/config/docker.yaml
- test/e2e/e2e_suite_test.go
- test/framework/bootstrap/kind_provider.go
- test/framework/bootstrap/kind_util.go
> 🌱  e2e tests: make the management cluster Kubernetes version configurable

- test/e2e/clusterctl_upgrade.go
Allows a provider to specify pre and post upgrade actions to take when running ClusterctlUpgradeSpec
Also enable better cleanup in clusterctl upgrade spec when management
cluster hasn't been upgraded yet.
> :sparkles: [e2e framework] Add ability to run pre and post actions during clusterctl upgrade spec

- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/repository/components_test.go
- cmd/clusterctl/internal/scheme/scheme.go
Currently, clusterctl only overwrites the target namespace of v1 CRDs and WebhookConfigurations. This PR adjusts clusterctl to also handle the v1beta1 versions.
Note: this has to be supported because v1alpha4 providers are not required to use the v1 versions of those resources.
After this fix clusterctl also returns better errors when used together with v1alpha3 provider versions, i.e.
```
Error: current version of clusterctl is only compatible with v1alpha4 providers, detected v1alpha3 for provider infrastructure-aws
```
instead of:
```
Fetching providers
Error: failed to get provider components for the "aws" provider: failed to set the TargetNamespace on the components: converting …
```
> 🐛 clusterctl: fix target namespace in v1beta1 CRDs and WebhookConfigurations

- .golangci.yml
As we decided in https://github.com/kubernetes-sigs/cluster-api/issues/4586 we want to ignore this finding, this PR adjusts the golangci-lint config to make clear we ignore this finding intentionally (and we don't want to fix it).
P.S. Feel free to retitle. That's the best title I could come up with :/
Fixes #4586
> 🌱 Intentionally ignore Deferring unsafe method Close on type *os.File

- docs/book/src/tasks/using-kustomize.md
- docs/book/src/user/quick-start.md
Updates links to follow the iminent renaming of the cluster-api-provider-azure main branch,,
Refs kubernetes-sigs/cluster-api-provider-azure#749
cc: @CecileRobertMichon
> 📖 doc: update Azure provider links to reference main branch

- controllers/topology/desired_state.go
This PR fixes a panic error in topology/ClusterReconciler if there are no workers in a topology.
It also contain a small change to remove info automatically assigned by the API server when cloning templates
> 🐛 Fix panic in cluster class reconcile

- controllers/topology/controller.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
- controllers/topology/util.go
Implement the Control Plane reconcilition logic for the ClusterClass controller. This is built on top of #5072 right now, so only the final commit is relevant to the PR.
Fixes #5049
> 🌱 Reconcile control plane resources in ClusterClass

- docs/book/src/user/quick-start.md
Adds a link to the `darwin-arm64` (not `-amd64`) download for `clusterctl`, which is preferable on M1-based Macs.
See #4861.
N/A
> 📖 doc: mention clusterctl download for darwin-arm64

- controllers/topology/cluster_class.go
- controllers/topology/cluster_class_test.go
- controllers/topology/controller.go
- controllers/topology/current_state.go
- controllers/topology/current_state_test.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
- controllers/topology/types.go
This changeset cleans up the current codebase under controller/topology
which is related with the ClusterClass proposal and work that's been
ongoing. It adds more comments throughout the codebase, and uses
pointers which avoids copying structs around.
Fixes #
> :seedling: Cleanup controllers/topology code, add more comments

- test/e2e/clusterctl_upgrade.go
- test/e2e/config/docker.yaml
Since changing the "default" `KUBERNETES_VERSION` to v1.22 our clusterctl upgrade test was broken. This PR adds a new environment variable to be able to specify a separate Kubernetes version for the clusterctl upgrade test.
This PR also bumps the v0.3 provider versions to "0.3-latest".
Fixes #5099
> 🌱 Fix clusterctl upgrade e2e test

- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/internal/mergepatch/mergepatch_test.go
- controllers/topology/reconcile_state.go
This PR moves controllers/topology/mergepatch* to an internal package, so the main topology folder is now cleaner
> 🌱 Move topology/mergepatch helper to an internal package

- docs/book/src/user/quick-start.md
The [Quick Start](https://release-0-3.cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers) page lists environment variables needed to configure a cluster for all the providers but GCP. To configure a GCP infrastructure, the user has to currently look into the GCP Provider's documentation or run the `--list-variables` command to find out the variables for the configuration. This can be improved with this PR.
Fixes #
> :book:  Update Quick Start doc to include GCP env variables.

- controllers/topology/internal/mergepatch/doc.go
- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/internal/mergepatch/mergepatch_test.go
- controllers/topology/internal/mergepatch/options.go
- controllers/topology/reconcile_state.go
While testing ClusterClass, I discovered that the controller was overriding `spec.controlPlaneEndpoint` in the infrastructure Cluster.
This is because the `spec.controlPlaneEndpoint` fields (host and port) are defined as mandatory and as a consequence defaulted to "" and 0 in the template, and then enforced in the managed object.
This PR adds to the merge helper an option that allows us to specify fields to be ignored when computing diff; this can be used to solve the above issue given that `spec.controlPlaneEndpoint` is a field defined in the contract and we know that this field will be set by the controller.
Similar change should be applied for other spec fields defined in the contract in follow up PRs.
> 🌱 add mergehelper IgnorePath option

- api/v1alpha4/clusterclass_webhook.go
Currently the ObjectReference is a pointer and thus can be nil. In this case we would get a nil pointer dereference.
Note:
* Not sure if it should be pointer
Fixes #
> 🌱  fix nil pointer in ClusterClass webhook ref validation

- Tiltfile
- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/clusterctl/commands/upgrade.md
- docs/book/src/clusterctl/configuration.md
- docs/book/src/developer/guide.md
- docs/book/src/user/quick-start.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
This PR upgrades cert-manager to 1.5.0. 
According to  [Cert Manager docs](https://cert-manager.io/docs/installation/supported-releases/)  cert-manager 1.4.0 doesn't support k8s 1.22.
> ⚠️ Upgrade cert-manager to 1.5.0

- internal/envtest/environment.go
I think we forgot adding the webhook to envtest. When we don't add it we're not able to create ClusterClass resources in envtest's
Fixes #
> 🌱 envtest: enable ClusterClass webhook

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Admission webhooks only run on create/update, our codebase requires these fields to be set when the upgrade code runs.
Consider the following scenario:
- Management cluster on an older version of Cluster API (< v0.3.15)
- Starts upgrade
- Upgrade management cluster to a newer version (>= v0.3.15)
- KCP fails because there is no rolloutStrategy set
Fixes #5136
> :bug: KubeadmControlPlane rolloutstrategy should be defaulted in openapi

- test/e2e/config/docker.yaml
Let's use the latest CAPI v0.3 release (released yesterday)
Fixes #
> 🌱 bump clusterctl upgrade test to CAPI v0.3.23

- controllers/topology/current_state.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/contract/controlplane.go
- controllers/topology/internal/contract/controlplane_template.go
- controllers/topology/internal/contract/controlplane_template_test.go
- controllers/topology/internal/contract/controlplane_test.go
- controllers/topology/internal/contract/doc.go
- controllers/topology/internal/contract/infrastructure_cluster.go
- controllers/topology/internal/contract/infrastructure_cluster_test.go
- controllers/topology/internal/contract/references.go
- controllers/topology/internal/contract/references_test.go
- controllers/topology/internal/contract/types.go
- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/internal/mergepatch/mergepatch_test.go
- controllers/topology/internal/mergepatch/options.go
- controllers/topology/object_builders_test.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
- controllers/topology/util.go
- controllers/topology/util_test.go
This PR creates and internal/contract package for ClusterClass thus centralising in a single point all the knowledge about how to deal with Unstructured objects according to the Cluster API contract.
**Anything else you would like to add:**
This package is potentially usable in the entire Cluster API codebase, but for this first iteration we are intentionally keeping it scoped to ClusterClass.
> 🌱 create internal/contract package for ClusterClass

- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
KCP should allow to mutate the apiVersion of the reference
Fixes #5130
> :bug: KubeadmControlPlane should allow to change the machineTemplate's apiVersion

- hack/setup-envtest-with-kind.sh
- internal/envtest/environment.go
- internal/envtest/webhooks.go
This PR makes it possible to run our unit tests with a local kind cluster (on Mac and on Linux). It also includes a shell script which can be run to get detailed instructions on how to do that.
Note:
* after we have consensus about the implementation I would adjust our testing documentation accordingly (also regarding `CAPI_DISABLE_TEST_ENV`)
Fixes #5029
> 🌱  Enable envtest with kind

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
Additional validation rules added to define checks for moving a Cluster from
a ClusterClass to a different ClusterClass, by name change or by update.
Signed-off-by: Killian Muldoon <kmuldoon@vmware.com>
Co-authored-by: Stefan Büringer <buringerst@vmware.com>
> 📖 Add validation for ClusterClass compatibility

- util/predicates/cluster_predicates.go
- util/predicates/generic_predicates.go
Currently in Cluster API, when log is >=4, predicates start reporting several logs entries reporting:
1. When an object reconciliation is blocked by predicates
2. When an object reconciliation is allowed by predicates
3. How predicates combines via Any or All
This is really chatty given that we are using predicates in many places, and it makes reading Cluster API log hard/difficult to use log levels  >=4.
This PR implement a solution for this problem by moving logs of category 2 and 3 to v6, while instead "object reconciliation being blocked by predicates" will continue to be logger at v4.
> 🌱 Move Predicates allow logs to V6

- cmd/clusterctl/client/cluster/mover.go
Allows the use of the restore function, as it is right now broken.
Fixes #
> :bug: log in restore cmd causing crashes

- api/v1alpha4/cluster_types.go
- api/v1alpha4/clusterclass_types.go
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- controllers/topology/current_state.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/contract/controlplane.go
- controllers/topology/internal/contract/controlplane_template.go
- controllers/topology/internal/contract/controlplane_test.go
- controllers/topology/internal/contract/metadata.go
- controllers/topology/object_builders_test.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/controllers/helpers.go
Co-authored-by: fabriziopandini <fpandini@vmware.com>
WIth this PR metadata is propagated to control plane and MachineDeployment machines.
There were also two bugs in KCP:
* the webhook didn't allow changes to metadata
* KCP didn't propagate annotations
Fixes #5168
> 🐛 ClusterClass : fix propagate metadata to machines, KCP fix propagate annotations

- controllers/remote/cluster_cache.go
- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/reconcile_state.go
- controllers/topology/util.go
- util/predicates/cluster_predicates.go
This PR Cleanup logs for topology/ClusterReconciler following [sig-instrumentation guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md).
More specifically
At log level 0. (always visible) we are logging:
- A log entry signalling the reconciler is processing
```
I0820 18:26:01.101336      35 reconcile_state.go:41] controller-runtime/manager/controller/cluster "msg"="Reconciling state for topology owned objects" ...
```
- A log entry for each object actually modified by the reconciler, e.g.
```
I0820 18:26:01.101400      35 reconcile_state.go:303] controller-runtime/manager/controller/cluster "msg"="Creating infrastructure.cluster.x-k8s.io/v1alpha4, Kind=DockerCluster/my-cluster1-rl4sf"... …
```
> 🌱 Cleanup topology reconcile logs

- test/framework/controlplane_helpers.go
KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration is not a required field, avoid assuming it is set in the e2e framework.
> :bug: [e2e framework] Avoid NPE when KCP does not specify ClusterConfiguration

- controlplane/kubeadm/controllers/helpers.go
- controlplane/kubeadm/controllers/helpers_test.go
- controlplane/kubeadm/internal/cluster_labels.go
The intention of the KCP code is to propagate the ObjectMeta from `kcp.Spec.MachineTemplate.ObjectMeta` to the control plane machines. 
During the machine generation we add a few additional labels/annotations. Unfortunately, we used *same* map from KCP to add the labels/annotations. So while we wanted to calculate labels/annotations for a new machine we also modified the in-memory ObjectMeta of `kcp.Spec.MachineTemplate.ObjectMeta`. Later on KCP was automatically patched a few layers above in the call stack. 
This PR makes sure we copy the labels/annotations into a new map.
Note: 
* this bug only occurred when `kcp.Spec.MachineTemplate.ObjectMeta.{labels,annotations}` was set. It then lead to an …
> 🐛  KCP: stop reconciling ObjectMeta into the KCP machine template

- OWNERS_ALIASES
Add stmcginnis as a reviewer.
- PRs: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Astmcginnis
- Reviews: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+stmcginnis
- Issues: https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Astmcginnis
cc @CecileRobertMichon @vincepri @sbueringer @fabriziopandini
> 🌱 Add stmcginnis as a reviewer

- cmd/clusterctl/client/cluster/mover.go
More details found in slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1630421115076500
The move function is not idempotent because currently the Kubernetes apiserver returns a ServerTimoutError for those objects whose metadata has the generateName flag. This can be verified by creating a resource with this flag, and then trying to `create -f` the file again with the same name in place. 
This is a known Kubernetes issue https://github.com/kubernetes/kubernetes/issues/32220
Until a fix is in place, we propose this solution which would allow the move function to be idempotent and handle these kind of objects without tossing an unexpected error.  
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> :bug:  Allow move cmd idempotent by making it tolerant to a known kubernetes issue

- .github/workflows/release.yml
- .gitignore
- Makefile
- docs/developer/releasing.md
- test/infrastructure/docker/Makefile
**What this PR does / why we need it**: This is part 1 of automating our release process. It adds a GH action for creating the draft release with release notes and generated artifacts on GitHub when a tag is pushed.
Tested on my fork: https://github.com/CecileRobertMichon/cluster-api/actions/runs/1192045111
Resulting draft release: https://github.com/CecileRobertMichon/cluster-api/releases/tag/untagged-88e1db0cbb70a7f9fe19
Fixes #
> 🌱 Add GitHub Action to automate creating a release

- Tiltfile
> :seedling: Tilt should reload CABPK and KCP on go.mod changes

- api/v1alpha4/machine_types.go
- api/v1alpha4/machinedeployment_types.go
- api/v1alpha4/machinehealthcheck_types.go
- api/v1alpha4/machineset_types.go
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
This changeset adds a printer column to be used with kubectl that
exposes the spec.clusterName on object when listing.
Fixes #
> 🌱 Add Cluster name as printer column on core types

- cmd/clusterctl/client/cluster/proxy.go
- controllers/remote/cluster_cache_reconciler.go
- exp/addons/controllers/clusterresourcesetbinding_controller.go
- using Complete() instead of Build() when there is no need to return a controller
- fix small typo
Fixes #
> 🌱cleanup: using Complete() instead of Build() when there is no need to return a controller

- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
This PR will add the topology/cluster labels also to:
* controlPlane.machineTemplate.metadata.labels
* MD.spec.template.labels
Thus all topology owned MachineSets and Machines will also have the respective labels.
Fixes #
> 🌱 Propagate topology labels to MachineSets and Machines

- api/v1alpha4/cluster_types.go
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
Let’s say you want to create a Cluster with the following topology:
```
spec:
topology:
class: my-cluster-class
version: v1.22.0
```
This won’t work with kubectl, because according to the OpenAPI Schema topology.controlPlane is mandatory. When you disable the client-side OpenAPI schema validation with --validate=false it will work. Why?
* kubectl client-side does not block with validate==false
* somehow the server-side validation does not fail. I guess it’s because controlPlane is not a pointer
* The resulting Cluster looks like this:
```
spec:
topology:
class: my-cluster-class
version: v1.22.0
controlPlane:
metadata: {}
```
This can be fixed by making the field optional, which kind of makes sense …
> 🌱 Make Cluster topology controlPlane optional

- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
Adding `ClusterTopologyMachineDeploymentLabelName` to the generated
`Bootstrap` and `Infrastructure Machine` templates
`ClusterTopologyMachineDeploymentLabelName` has to be added on the generated MachineDeployment objects to track the name of the MD topology it represents. Bootstrap and InfrastructureMachine templates are also generated as part of `computeMachineDeployment`. Hence, adding the label on these templates as well.
Fixes #5193
> 🌱 Add ClusterTopologyMachineDeploymentLabelName to MachineDeployment templates

- util/patch/patch_test.go
This PR fixes the two flaky test cases in `TestPatchHelper` (which are two of the most frequent ones we have right now). 
The test assumes that the condition we have in the local object is exactly the same compared to the condition after the patch on the server-side. This is not true, because the patch helper re-calculates the `LastTransitionTime` during the patch func. In theory there are a few more test cases which should be affected. According to testgrid only those two are flaky.
Q:
* Should I also adjust other test cases in the same test accordingly? (I could introduce a func which compares conditions while ignoring `LastTransitionTime`)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> 🐛  fix flaky TestPatchHelper test

- api/v1alpha4/clusterclass_webhook.go
- api/v1alpha4/clusterclass_webhook_test.go
- controllers/topology/reconcile_state.go
- docs/proposals/202105256-cluster-class-and-managed-topologies.md
This PR allows compatible changes on ClusterClass, namely metadata, and template rotation.
Please note that those checks now applies to all ClusterClasses, while in a future iteration we can improve UX by not applying compatibility rules if a ClusterClass is actually not used by a Cluster.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5192
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5197
> 🌱 Allow cluster class compatible changes

- controllers/topology/blueprint.go
- controllers/topology/current_state.go
- controllers/topology/desired_state.go
- controllers/topology/internal/log/doc.go
- controllers/topology/internal/log/log.go
- controllers/topology/reconcile_state.go
- controllers/topology/util.go
- controllers/topology/util_test.go
> 🌱  controllers/topology: cleanup error handling and templateNamer

- controlplane/kubeadm/internal/cluster_test.go
Test frequently fails in CI: [testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-main&exclude-non-failed-tests=50&sort-by-failures=)
Fixes #
> 🐛  Fix flaky TestGetWorkloadCluster test

- api/v1alpha4/machinedeployment_types.go
- api/v1alpha4/machineset_types.go
- config/rbac/role.yaml
- controllers/external/util.go
- controllers/machinedeployment_sync.go
- controllers/topology/cluster_controller.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/log/log.go
- controllers/topology/machinedeployment_controller.go
- controllers/topology/machinedeployment_controller_test.go
- controllers/topology/machineset_controller.go
- controllers/topology/machineset_controller_test.go
- controllers/topology/reconcile_state.go
- controllers/topology/util.go
- controllers/topology/util_test.go
- internal/testtypes/builders.go
- main.go
- util/labels/helpers.go
- util/predicates/generic_predicates.go
- util/util.go
Before this PR, our topology code:
* deleted "old" templates after template rotation of MachineDeployments immediately
* thus reconciliation of the old MachineSets was immediately broken as the MachineSet controller requires the templates
* didn't delete corresponding templates when deleting MachineDeployments
This PR aims to solve this problem. The high-level concept is:
* topology code doesn't delete templates in "successful" reconciles (template rotation without errors / MachineDeployment deletions)
* Note: we will have to introduce another separate mechanism which cleans up templates when the template rotation fails (e.g. new templates were never referenced in any MachineDeployment or …
> 🐛  Implement template deletion for topology-owned MD and MS

- api/v1alpha4/clusterclass_webhook.go
- bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go
Using `.Index` func instead of `fmt` package to subscript array indexes
Fixes #5216
> 🌱 Use .Index func when building field.Paths

- api/v1alpha4/cluster_webhook.go
- api/v1alpha4/cluster_webhook_test.go
- controllers/topology/current_state.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/contract/controlplane.go
- controllers/topology/internal/contract/controlplane_test.go
- controllers/topology/internal/contract/types.go
- controllers/topology/internal/scope/scope.go
- controllers/topology/internal/scope/state.go
- controllers/topology/internal/scope/upgradetracker.go
- internal/testtypes/builders.go
- util/version/version.go
This PR adds upgrade support to managed topologies.
Upgrading the control plane follows these rules:
* Upgrade only if the control plane and none of the machine deployments are upgrading
* Do not allow downgrades
Upgrading the machine deployment follows these rules:
* Upgrade only one machine deployment at a time
* Upgrade only if none of the machine deployments and the control plane are upgrading.
* Do not upgrade if the control plane is about to upgrade i.e., the control plane is stable for now but its version is about to change.
* Do not allow downgrades
Some of the assumptions made for the initial implementation :
* No additional changes are made to the cluster or the clusterclass when dealing with the version change.
The upgrade flow was …
> ✨ Upgrade support for managed topologies

- controllers/topology/cluster_controller.go
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5194
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5194
> 🐛 Add watches for infras and control plane in topology controller

- controllers/topology/internal/contract/controlplane.go
This PR adds proper error handling to `IsScaling` function. Control planes might not have `readyReplicas` when they are in the middle of scaling/upgrading. This is to make sure this case is error is properly handled. 
This PR should only be merged after https://github.com/kubernetes-sigs/cluster-api/pull/5221 or else the upgrade flow will behave as expected.
Fixes #
> 🐛  IsScaling error handling in control plane contract

- api/v1alpha3/common_types.go
- api/v1alpha3/condition_consts.go
Implements https://github.com/kubernetes-sigs/cluster-api/issues/5236#issuecomment-919825042
Looks like we missed a few constants we have on our release-0.3 branch. This breaks API consumers when trying to migrate from v1alpha3 to v1alpha4. (of course only when they are used in API consumer code)
Fixes #
> 🌱 Add missing constants to v1alpha3 package from release-0.3

- controllers/mdutil/util.go
This was first added here #143 and it's never been used.
Fixes #
> 🌱 Deprecate unused MachineDeployment constants

- controllers/external/util.go
This PR catches an error in clusterctl triggered by a cluster with nil infrastructure or other references. This issue was introduced by the clusterClass flow where these references are initially set to nil. This fix checks if object references are nil before running an external client Get.
Fixes #5226
> 🐛 Fix panic in clusterctl describe from nil reference

- test/infrastructure/docker/Dockerfile
With this PR the kubectl download is cached even when CAPD has to be recompiled
Fixes #
> 🌱 CAPD: improve image build caching

- cmd/clusterctl/client/cluster/client.go
- cmd/clusterctl/client/cluster/proxy.go
- cmd/clusterctl/cmd/completion.go
- cmd/clusterctl/cmd/root.go
- cmd/clusterctl/cmd/util.go
- cmd/clusterctl/internal/test/fake_proxy.go
This PR adds dynamic completion support for context in kubeconfig and namespace.
- `--kubeconfig-context` flag
- `clusterctl move --to-kubeconfig-context` flag
- `--namespace` flag
- `--target-namespace` flag
- `--from-config-map-namespace` flag
ref/ #4089
> ✨ Add dynamic completion support for context in kubeconfig and namespace

- controllers/topology/blueprint_test.go
- controllers/topology/current_state.go
- controllers/topology/current_state_test.go
Small cleanups on ClusterClass tests for improving maintainabilty
> 🌱 Small cleanups to ClusterClass tests

- cmd/clusterctl/cmd/completion.go
- cmd/clusterctl/cmd/root.go
If `--kubeconfig-context` is specified, completion suggestions for`--namespace` needs to provide namespaces of the cluster specified with`--kubeconfig-context`.
However, it currently uses the current context even if`--kubeconfig-context` is specified.
**Before**
```shell
$ kind create cluster --name test
$ kubectl create ns kind-test --context kind-test
namespace/kind-test created
$ kind create cluster
$ clusterctl get kubeconfig --namespace <tab>
default             kube-node-lease     kube-public         kube-system         local-path-storage
$ clusterctl get kubeconfig --kubeconfig-context kind-test --namespace <tab>
default             kube-node-lease     kube-public         kube-system         local-path-storage
```
**After**
```shell
$ …
```
> 🐛 Fix a bug that completion suggestions for --namespace are not updated

- cmd/clusterctl/client/config/reader_memory.go
- cmd/clusterctl/client/config/reader_memory_test.go
The operator needs to be able to read configuration (normally in files locally) from a secret into a Reader.
see https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20201020-capi-provider-operator.md
This can be easily done by the operator reading in the secret and Setting the variables on new MemoryReader.
Note that the secret is to not be writable so we don't need to push the ability to write the secret into the Reader.
This has been split out of https://github.com/kubernetes-sigs/cluster-api/pull/4926 for ease of reviewing.
/cc @fabriziopandini @alexander-demichev 
This is how it is used: https://github.com/kubernetes-sigs/cluster-api/pull/4926/files#diff-c580f31a2ccfe402ca2335b20daeeaf9b4862b22662a49e5bffff938295d36acR109 …
> ✨ Add a MemoryReader for the operator to place config from a secret

- cmd/clusterctl/cmd/completion.go
- cmd/clusterctl/cmd/describe_cluster.go
- cmd/clusterctl/cmd/get_kubeconfig.go
- cmd/clusterctl/cmd/root.go
This PR adds completion support for cluster resource:
- `clusterctl get kubeconfig <cluster>`
- `clusterctl describe cluster <cluster>`
ref/ https://github.com/kubernetes-sigs/cluster-api/issues/4089
> ✨ clusterctl: Add completion support for cluster resource

- docs/book/src/user/quick-start.md
Bumps the version of Calico used in the CAPI quickstart guide.
> 🌱  Update calico version in quickstart guide

- docs/book/src/SUMMARY.md
- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
- docs/book/src/developer/providers/v1alpha4-to-v1beta1.md
This PR adds the initial version of the upgrade doc.
Fixes #5262
> 📖 Add v1alpha4 to v1beta1 upgrade doc 

- test/infrastructure/docker/api/v1alpha3/conversion_test.go
- test/infrastructure/docker/api/v1alpha4/conversion_test.go
This PR adds the missing conversion tests to CAPD v1alpha3 and v1alpha4 types.
Fixes #5256
> 🌱 CAPD: add conversion tests for v1alpha3 and v1alpha4

- controllers/topology/cluster_controller.go
- controllers/topology/current_state.go
- controllers/topology/current_state_test.go
- main.go
This PR updates the get current state logic in topology controllers to use a live client when listing MachineDeployments. This is to avoid having and race conditions that could be caused due to outdated cache. 
An example issue that was observed a few times is: When creating a topology with 2 MachineDeployments we sometimes observe 3 MachineDeployments being created. This could be happening because the topology controller re-runs before the case is updated with the second MachineDeployment. 
Fixes #
> 🌱 clusterclass: use live client to list MachineDeployments

- Tiltfile
- docs/book/src/developer/tilt.md
This PR plays on a feature recently added in tilt that allows us to to group resources in the tilt dashboard see https://blog.tilt.dev/2021/08/09/resource-grouping.html.
I'm currently providing two different grouping strategies:
- by controllers and local binaries
- by provider
~~ The tricky part is that in order to get this to work nicely, we should change current default provider names, and this requires a small change to `tilt_settings.json` on the developer side ~~ (fixed)
I also have to investigate if this works with older releases...
@CecileRobertMichon @vincepri @sbueringer opinions?
> 🌱 Group resources in tilt

- cmd/clusterctl/client/cluster/inventory.go
- cmd/clusterctl/client/cluster/inventory_test.go
- cmd/clusterctl/client/cluster/upgrader_test.go
- cmd/clusterctl/client/upgrade.go
- test/e2e/clusterctl_upgrade.go
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/docker.yaml
- test/e2e/data/shared/v1alpha3/metadata.yaml
- test/framework/clusterctl/e2e_config.go
This PR add support for v1alpha3 to v1beta1 upgrades in clusterctl, under the assumption v1alpha4 and v1beta1 contract are the same.
It also add support for testing both v1alpha3 --> v1beta1 and v1alpha4 --> v1beta1 upgrades (this will require a PR in test infra as soon as this PR will be merged)
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5269
> ✨ Clusterctl: add support for v1alpha3 to v1beta1 upgrades

- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_clusterresourcesetbindings.yaml
- config/crd/patches/cainjection_in_clusterresourcesets.yaml
- config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
- config/crd/patches/webhook_in_clusterresourcesets.yaml
- exp/addons/api/v1alpha3/conversion.go
- exp/addons/api/v1alpha3/conversion_test.go
- exp/addons/api/v1alpha4/conversion.go
- exp/addons/api/v1alpha4/conversion_test.go
- exp/addons/api/v1beta1/conversion.go
This adds the conversion functions and configs to create conversion webhooks for both the ClusterResourceSet and the ClusterResourceSetBinding types.
Fixes #5253
> 🌱  Add conversions for ClusterResourceSet and ClusterResourceSetBinding

- Makefile
- hack/ensure-golangci-lint.sh
- scripts/ci-e2e-lib.sh
- test/infrastructure/docker/Makefile
**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api/issues/3280
this should be merged right after the actual branch rename
/hold
Fixes #
> 🌱  Rename default branch to main in scripts

- api/v1beta1/condition_types.go
- controllers/external/util.go
- docs/proposals/20200506-conditions.md
Removing +required marked from our codebase, because it is not relevant for controller-gen and it also used in some cases outsides of the APIs.
> 🌱 Remove +required marker

- api/v1alpha4/machinedeployment_types.go
- cmd/clusterctl/client/alpha/machinedeployment.go
- cmd/clusterctl/client/alpha/rollout_rollbacker.go
- controllers/internal/mdutil/doc.go
- controllers/internal/mdutil/util.go
- controllers/internal/mdutil/util_test.go
- controllers/machinedeployment_rolling.go
- controllers/machinedeployment_rolling_test.go
- controllers/machinedeployment_rollout_ondelete.go
- controllers/machinedeployment_sync.go
- controllers/machinedeployment_sync_test.go
- controllers/topology/internal/scope/state.go
Creates controllers/internal/machinedeployment
Deprecate all exported funcs and consts in controllers/mdutil
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5244
Ports https://github.com/kubernetes-sigs/cluster-api/pull/5297
Fixes #
> 🌱 Deprecate controllers/mdutil package, moving to internal

- api/v1alpha4/machinedeployment_types.go
- api/v1beta1/machinedeployment_types.go
- cmd/clusterctl/client/alpha/machinedeployment.go
- cmd/clusterctl/client/alpha/rollout_rollbacker.go
- controllers/internal/mdutil/doc.go
- controllers/internal/mdutil/util.go
- controllers/internal/mdutil/util_test.go
- controllers/machinedeployment_rolling.go
- controllers/machinedeployment_rolling_test.go
- controllers/machinedeployment_rollout_ondelete.go
- controllers/machinedeployment_sync.go
- controllers/machinedeployment_sync_test.go
- controllers/topology/internal/scope/state.go
Creates controllers/internal/machinedeployment
Deprecate all exported funcs and consts in controllers/mdutil
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5244
Fixes #
>  ⚠️ Move mdutil into an internal package

- api/v1beta1/condition_types.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- docs/proposals/20200506-conditions.md
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
The condition.lastTransitionTime is wrongly tagged with omitempty and this makes to optional from an OpenAPI PoV.
This PR makes this field mandatory.
Please note that this is a breaking change, however it should not create problem to the users given that our utilities for working with conditions are always setting this field.
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/5233
> ⚠️ Make condition.lastTransitionTime required

- Makefile
- hack/kind-install-for-capd.sh
This change adds a script that creates a Kind cluster with a local container registry and the correct mounts for using CAPD. This script is mainly a copy of the kind_with_local_registry.sh script made available by the Kind team at https://kind.sigs.k8s.io/docs/user/local-registry/.
This PR is in response to a comment on our current Tilt workflow at #5204 
> 🌱 Add script to install Kind for testing with CAPD

- Makefile
- hack/tools/conversion-verifier/doc.go
- hack/tools/conversion-verifier/main.go
- hack/tools/go.mod
- hack/tools/go.sum
This change adds a sort-of-custom linter to the hack/tools folder which
does basic verification of our types. The linter isn't generic and it's
customized to the Cluster API's codebase needs and structure. It can be
improved and made better in the future and we should be able to further
generalize it with time.
The conversion-verifier is needed given that conversion information has
been missed in the past causing types to remain unconvertible.
Fixes #5287
> :seedling: Add conversion-verifier to always verify conversion code

- scripts/ci-e2e-lib.sh
e2e test is currently broken: 
>  echo '+ checkout main branch'
> + checkout main branch
> + git checkout main
> error: pathspec 'main' did not match any file(s) known to git
> https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-22-latest-main/1440962048518262784
Fixes #
> 🐛 Fix 1.22=>latest upgrade e2e test

- api/v1beta1/cluster_types.go
- api/v1beta1/clusterclass_types.go
- api/v1beta1/machinedeployment_types.go
- api/v1beta1/machinehealthcheck_types.go
- api/v1beta1/machineset_types.go
- bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
- exp/addons/api/v1beta1/clusterresourceset_types.go
- exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
- exp/api/v1beta1/machinepool_types.go
In an attempt to keep `optional` and `omitempty` tags consistent throughout
the code, adding `+optional` tag to fields that have the `omitempty` tag.
Co-authored-by: Stefan Bueringer <buringerst@vmware.com>
> 🌱 Add missing optional tag to omitempty fields

- .github/workflows/golangci-lint.yml
- OWNERS
- bootstrap/kubeadm/config/default/manager_image_patch.yaml
- cmd/clusterctl/client/cluster/template_test.go
- cmd/clusterctl/client/repository/repository_github_test.go
- cmd/clusterctl/client/tree/doc.go
- cmd/clusterctl/cmd/generate_cluster.go
- cmd/clusterctl/cmd/generate_yaml.go
- cmd/clusterctl/internal/util/objs_test.go
- config/default/manager_image_patch.yaml
- controlplane/kubeadm/config/default/manager_image_patch.yaml
- controlplane/kubeadm/controllers/remediation.go
- docs/book/src/developer/e2e.md
- docs/book/src/reference/providers.md
- docs/proposals/20191017-kubeadm-based-control-plane.md
- docs/proposals/20200511-clusterctl-extensible-template-processing.md
- test/infrastructure/docker/config/default/manager_image_patch.yaml
- test/infrastructure/docker/third_party/forked/rerun-process-wrapper/README.md
**What this PR does / why we need it**: #3280
Just found a broken e2e test (will be fixed in #5313), so I thought I also cleanup some other occurrences.
Fixes #
> 🌱 Change a few more references from master branch to main branch

- errors/doc.go
Small update to the errors package doc to reflect the actual usage of the package and explain why it contains many unused functions and constants.
> 🌱 Update errors pkg doc to reflect intended usage

- cmd/clusterctl/client/cluster/installer.go
- cmd/clusterctl/client/cluster/upgrader.go
This PR enforce clusterctl to install or upgrade providers in a predictable order.
This should prevent flakiness in case providers gets updates before CAPI types of a given version are installed
> 🐛 Clusterctl enforce provider order during init and upgrade

- test/framework/clusterctl/client.go
Makes it easier to debug the clusterctl upgrade e2e test because the output of clusterctl init/upgrade will be visible in the log (only if the call fails)
Fixes #
> 🌱 e2e-test: improve error logging for clusterctl init/upgrade with binary

- Tiltfile
- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/clusterctl/commands/upgrade.md
- docs/book/src/clusterctl/configuration.md
- docs/book/src/developer/guide.md
- docs/book/src/user/quick-start.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
This PR upgrades cert-manager to 1.5.3
> 🌱 Upgrade cert-manager to 1.5.3

- CONTRIBUTING.md
This PR adds API conventions to establish a standard for our APIs going forward. The main focus is optional fields.
Related PRs:
* #5302: Drops `+required` annotations, because they are not handled by controller-tools
* #5303 Drops `omitempty` for `LastTransitionTime ` which makes the field required in OpenAPI Schema as intended
* #5301 Adds `+optional` to all optional fields which currently only have `omitempty`. This doesn't have any consequences as those fields already have been optional in the OpenAPI schema before (because of the `omitempty`)
* #5305 
* Adds `omitempty` to some of our `+optional` fields
* Removes `omitempty` from our object lifecycle boolean status fields and our replica counter status fields so they are always visible (e.g. …
> 📖  Add API conventions

- config/rbac/role.yaml
- controllers/topology/cluster_controller.go
This PRs adds permission for changing ClusterClass to topology controller
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5342
> 🐛 Add permission for changing ClusterClass to topology controller

- controlplane/kubeadm/api/v1beta1/condition_consts.go
This PR removes Condition suffix from EtcdClusterHealthyCondition name
> ⚠️ Remove Condition suffix from EtcdClusterHealthyCondition name

- controlplane/kubeadm/internal/control_plane.go
This change makes sure that the UpToDateMachines method always returns
a filter based on real data. Instead of looking at
(Machines - MachinesThatNeedRollout), which excludes all machines being
deleted as well, looks at all machines that match the expected
configuration and aren't scheduled for a rollout.
Fixes #
> 🐛 KubeadmControlPlane status.updated should be calculated appropriately

- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- exp/api/v1beta1/machinepool_types.go
- test/infrastructure/docker/api/v1beta1/dockercluster_types.go
- test/infrastructure/docker/api/v1beta1/dockermachine_types.go
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
This PR will add clusterName as printer column on non core types
Fixes #5208
> 🌱 Add cluster name on printer column on non core types

- test/infrastructure/docker/api/v1alpha3/conversion.go
We should use the v1beta1 type to unmarshal the data we wrote with v1beta1. I don't think it led to problems as the v1alpha4/v1beta1 DockerClusters are the same. Nonetheless it's not correct.
Thx @shivi28 for finding this issue
Note: I checked the conversions in other API folders and they are correct.
Fixes #
> 🐛 Fix CAPD v1alpha3=>v1beta1 conversion

- docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Update docs to include some changes made to the ControlPlane contract to support ClusterClass.
Fixes #5282
> 📖  Add clusterclass contract changes to v1alpha3-v1alpha4 conversion guide

- docs/book/src/developer/providers/implementers-guide/overview.md
Fix Kustomize bash installation documentation and redirect stable.txt download
Fixes #
> :book: Redirect on curl k8s stable version and kustomize install

- bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
- controllers/machine_controller.go
- controllers/machinedeployment_controller.go
- controllers/machinehealthcheck_controller.go
- controllers/machineset_controller.go
- exp/controllers/machinepool_controller.go
Some of the reconcilers keep reconciling resources that don't have the watch filter label.
> 🐛 Use the watch filter label when watching resources

- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/repository/components_test.go
I think it's a bad way to fix the bug, as it depends on a specific dnsName format. Unfortunately, I don't have a better idea. Suggestions for other solutions welcome.
Fixes #5369
> 🐛 clusterctl: fix Certificate target namespace

- cmd/clusterctl/cmd/upgrade_apply.go
Currently clusterctl upgrade fails to late in case none of the --contract or provider flags is set:
```bash
clusterctl-e25f0e3 upgrade apply --config ~/.cluster-api/dev-repository/config.yaml
Checking cert-manager version...
Deleting cert-manager Version="v1.1.0"
Installing cert-manager Version="v1.5.3"
Waiting for cert-manager to be available...
Error: current version of clusterctl could only upgrade to v1beta1 contract, requested
```
Fixes #
> 🌱 clusterctl upgrade: enforce that --contract or provider flags have to be set

- docs/book/src/clusterctl/developers.md
Just something I found when testing the latest commit locally.
Fixes #
> 📖 Fix make commands in clusterctl for developers doc

- test/e2e/clusterctl_upgrade.go
I would like to run both v1alpha4 -> v1beta1 and v1alpha3 -> v1beta1 tests in the same job, so expanding the clusterctl upgrade spec to allow different provider contracts to be tested.
Fixes #
/assign @sbueringer 
/area testing
> 🌱 Allow passing in provider contract and clusterctl binary in the clusterctl upgrade spec

- docs/book/src/SUMMARY.md
- docs/book/src/tasks/experimental-features/cluster-classes.md
- docs/book/src/tasks/experimental-features/experimental-features.md
- docs/book/src/tasks/experimental-features/yamls/clusterclass-quickstart.yaml
- docs/book/src/tasks/experimental-features/yamls/clusterclass.yaml
- docs/book/src/tasks/experimental-features/yamls/kindnet-clusterresourceset.yaml
Add a simple quick start guide to the CAPI book under experimental features. The guide shows how to create and then update a CAPD cluster from Kind install through to deletion using ClusterClass and Managed Topologies.
Fixes #5368 
Signed-off-by: killianmuldoon **<kmuldoon@vmware.com>**
> 📖 Add clusterclass quickstart guide

- bootstrap/kubeadm/config/certmanager/certificate.yaml
- config/certmanager/certificate.yaml
- controlplane/kubeadm/config/certmanager/certificate.yaml
- docs/book/src/developer/providers/v1alpha4-to-v1beta1.md
- test/infrastructure/docker/config/certmanager/certificate.yaml
Adds organizations to certificates to remove the following errors that are observed during `tilt up`.
```
[K8s EVENT: CertificateRequest capi-kubeadm-bootstrap-serving-cert-rr6c4 (ns: capi-kubeadm-bootstrap-system)] Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients
[K8s EVENT: CertificateRequest capi-serving-cert-n2fh6 (ns: capi-system)] Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients
[K8s EVENT: CertificateRequest capd-serving-cert-hmjpt (ns: capd-system)] Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients
[K8s EVENT: CertificateRequest …
```
> 🌱 add organizations to certificates

- util/util.go
- util/util_test.go
Extracted from: https://github.com/kubernetes-sigs/cluster-api/pull/5383#discussion_r722547894
Let's make this breaking change now (before v1.0.0), so we can avoid it after the release.
Fixes #
> ⚠️ ClusterToObjectsMapper: replace runtime.Object parameter with client.ObjectList

- test/e2e/clusterctl_upgrade.go
Adding code comments on how to use the Clusterctl Upgrade spec, for the benefit of the other infrastructure providers.
cc @sonasingh46 and @gab-satchi 
let me know if that's useful
Fixes #
> 🌱 Clusterctl Upgrade Spec: Add details on how to use it

- test/framework/machinepool_helpers.go
**What this PR does / why we need it**:  Removing a log line that was causing a lot of noise in the cluster upgrade test as it prints in a loop a bunch of times until the machine pool is done upgrading.
Fixes #
> 🌱  Remove noisy log in machine pool upgrade test

- test/e2e/clusterctl_upgrade.go
**What this PR does / why we need it**: Backports #5521
Fixes #5520
>  🌱 Add pre init hook to clusterctl upgrade test (release-1.0)

- docs/book/src/tasks/experimental-features/experimental-features.md
While developing with Tilt, found that ClusterTopology feature gate needs to be enabled to create a Cluster with ClusterClass.
This PR adds instructions how to enable ClusterTopology feature for Tilt and e2e tests to the doc.
> 📖  Add instructions to enable ClusterTopology feature for Tilt and e2e tests

- controllers/topology/internal/contract/controlplane.go
- controllers/topology/internal/contract/controlplane_test.go
- controllers/topology/internal/contract/types.go
This PR adds new methods to handle `.spec.machineTemplate.nodeDrainTimeout` to the ControlPlane in the contracts package.
Note: This will be required for the ClusterClass patch implementation.
Fixes #
> 🌱 Add nodeDrainTimeout to contract package

- OWNERS_ALIASES
**What this PR does / why we need it**: This PR moves @enxebre from reviewers to maintainers. @enxebre has been involved with the project and helped it evolve since its early stage. He was involved in discussions about Aggregated API vs CRDs, bootstrapping decoupling, cluster vs machine management, composability, project gradual adoption, etc. that influenced the v1alpha3 redesign. He drove the design and led the team which contributed autoscaling support, Machine health checking, externally managed infrastructure support, and spot instances.
Proposals: https://github.com/kubernetes-sigs/cluster-api/search?q=enxebre
PRs: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Aenxebre
Reviews: https://github.com/kubernetes-sigs/cluster-api/pulls?page=1&q=is%3Apr+ …
> 🌱  Promote enxebre to maintainer

- Makefile
- Tiltfile
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
- hack/ensure-kustomize.sh
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/framework/clusterctl/e2e_config.go
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/Makefile
make Cluster API dev tooling to work on arm64
> 🌱 make Cluster API dev tooling to work on arm64

- Tiltfile
This PR removes a left over usage of the manager_name variable, which is not required anymore
> 🌱 cleanup manager name from Tiltfile

- controllers/topology/reconcile_state.go
This PR removes template cleanup func, that was the first, partial, attempt to handle orphaned templates in topology controller.
A more comprehensive solution to the problem is being implemented in https://github.com/kubernetes-sigs/cluster-api/pull/5523 (or #5430, depending on which one we prefer)
Rif #5307
> 🌱 Remove template cleanup func in Topology controller

- controllers/machinedeployment_controller.go
Let's also log successful MachineSet adoptions to make debugging easier (e.g. in cases like: https://github.com/kubernetes-sigs/cluster-api/issues/3770)
Fixes #
> 🌱 MachineDeploymentReconciler: log successful MachineSet adoption

- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/contract/metadata.go
- controllers/topology/internal/contract/metadata_test.go
While testing ClusterClass handling of metadata I have found that under certain conditions the generated patch has an empty map, something like {"metadata":{"annotations":{}}}. This leads to topology reconcile assuming that the patch is not empty, and thus trying to patch an object indefinitely.
This change ensures that in case there are no labels/annotations, we are not generating empty maps in our objects, thus preventing empty patch for metadata being generated.
> 🐛 topology should not generate empty patch for metadata

- internal/matchers/matchers.go
- internal/matchers/matchers_test.go
This PR changes the logic inside the matchers to ensure that any difference in fields between the actual and original object - in either direction - is considered significant for establishing whether the objects are Equal. Previously the matcher did no consider fields in the original object that are not present in the modified object when matching.
This PR also adds unit tests to show the intended usage of the matcher in these, and other cases.
Note: This change significantly modifies the behaviour of the matcher library compared to the mergepatch library used in topology/internal. These changes make #5316 more difficult and less desirable.
Fixes #5563 
/area testing
> 🐛  Fix Matchers bug on ignored paths and add tests

- api/v1beta1/cluster_webhook.go
- api/v1beta1/cluster_webhook_test.go
- cmd/clusterctl/client/cluster/objectgraph.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/internal/test/fake_objects.go
- controllers/topology/blueprint_test.go
- controllers/topology/cluster_controller_test.go
- controllers/topology/clusterclass_controller_test.go
- controllers/topology/current_state.go
- controllers/topology/current_state_test.go
- controllers/topology/desired_state_test.go
- internal/builder/builders.go
This PRs add ClusterClass support to `clusterctl move` command.
Fixes #5445
> ✨ Clusterctl move with clusterclass

- controllers/topology/internal/log/log.go
This PR makes sure we log the log lines of the caller and not the one of the Info func.
Fixes #
> 🌱 topologyReconcileLogger: print the correct log lines

- OWNERS_ALIASES
This PR adds myself to cluster-api-controlplane-provider-kubeadm-maintainers.
I was one of the co-authors of the original spec for KCP (#1899), wrote the pod proxy that KCP uses to conduct healthchecks (#2030) across the board, and the initial etcd client taken to completion by @chuckha in #2237 . 
I'm also working upstream in etcd (https://github.com/etcd-io/etcd/issues/13340) to improve health check endpoints that we ultimately consume to improve reliability long term.
Fixes #
> :seedling: Promote randomvariable to KCP maintainer

- OWNERS_ALIASES
This PR adds @sbueringer (myself ;)) to cluster-api-test-maintainers.
I think I've been (helping) maintaining our test framework, e2e tests and CAPD for a while now. Mostly keeping testgrid green, tracking down and fixing broken or flaky tests, maintaining ProwJob configurations and of course also reviewing PRs in those areas, etc. .
I don't think we have the data quality to filter down for those specific areas so I'll just list all CAPI contributions:
PRs: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Asbueringer
Reviews: https://github.com/kubernetes-sigs/cluster-api/pulls?page=1&q=is%3Apr+sbueringer
Issues: …
> 🌱 Promote sbueringer to cluster-api-test maintainer

- Tiltfile
Otherwise local returns an error that it cannot be used on not allowed
context.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
> 🐛Tiltfile: use local_output after allow_k8s_contexts

- webhooks/cluster.go
- webhooks/cluster_test.go
- webhooks/clusterclass.go
- webhooks/clusterclass_test.go
Move the implementations of validation checks from the internal API package to the webhooks package. The webhooks package was previously calling the public methods in the API package which are deprecated and due to be removed in a future release.
Some details of the internal methods of the validation methods were changed in order to make this move.
Fixes #5594
> 🌱 Move Cluster and ClusterClass webhook implementation to top level package

- cmd/clusterctl/client/cluster/mover.go
- cmd/clusterctl/client/cluster/mover_test.go
While restore is pretty much works like move, the difference is the the object graph being constructed in move shows the uidToNode objects with the tenants set correctly (as does the backup command). However, with restore, since a new object graph is created, the tenant is not being set at on the restored object after reading the object from the backup directory. This leads restore to only restore the cluster object. I think the restore function is missing the o.setTenants call
Since the `Test_objectMover_restore` test uses `getObjectGraph` instead of creating a new graph like the actual restore does, I'm not sure if I need to add a test [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/cluster/mover_test.go#L874). …
> :bug: restore - set tenants on the new object graph constructed from files in the backup directory

- api/v1beta1/cluster_webhook.go
- api/v1beta1/clusterclass_webhook.go
Add additional comments in the API package to communicate to users that the Cluster and ClusterClass webhook implementations in that package will be deprecated and pointing them to the new locations of the public method implementations. 
Addresses: https://github.com/kubernetes-sigs/cluster-api/pull/5596#pullrequestreview-800283879
> 🌱 Update deprecation comments for Cluster and ClusterClass webhooks

- .golangci.yml
- api/v1alpha3/condition_consts.go
- api/v1alpha4/condition_consts.go
- api/v1beta1/condition_consts.go
- api/v1beta1/index/index.go
- bootstrap/kubeadm/api/v1alpha3/condition_consts.go
- bootstrap/kubeadm/api/v1alpha4/condition_consts.go
- bootstrap/kubeadm/api/v1beta1/condition_consts.go
- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
- controlplane/kubeadm/api/v1alpha3/condition_consts.go
- controlplane/kubeadm/api/v1alpha4/condition_consts.go
- controlplane/kubeadm/api/v1beta1/condition_consts.go
- controlplane/kubeadm/controllers/controller_test.go
- controlplane/kubeadm/internal/etcd/etcd.go
- exp/addons/api/v1alpha3/condition_consts.go
- exp/addons/api/v1alpha4/condition_consts.go
- exp/addons/api/v1beta1/condition_consts.go
- exp/api/v1alpha3/condition_consts.go
- exp/api/v1alpha4/condition_consts.go
- exp/api/v1beta1/condition_consts.go
- internal/matchers/doc.go
- test/framework/interfaces.go
- test/infrastructure/docker/api/v1alpha3/condition_consts.go
- test/infrastructure/docker/api/v1alpha4/condition_consts.go
- test/infrastructure/docker/api/v1beta1/condition_consts.go
- util/collections/machine_collection_test.go
Goal of the PR in its current state is to discuss if we want to enable godot also on toplevel comments (default is declarations).
Fixes #
> 🌱 enable godot on top-level comments

- .gitignore
- Tiltfile
- docs/book/src/developer/tilt.md
- hack/observability/grafana/values.yaml
- hack/observability/kustomization.yaml
- hack/observability/loki/values.yaml
- hack/observability/namespace.yaml
- hack/observability/promtail/values.yaml
This PR adds to our Tiltfile the capability to install some observability tool to a local test environments (promtail, loki, grafana) when doing `tilt up`.
In order to get those this working, it is required to:
- install helm CLI locally (which is a new, optional requirement for CAPI developers 😅 )
- add `"deploy_observability": true` to your tilt-settings.json
NOTES: 
- this PR mimics what is already present in CAPZ with the difference that we are not forking helm charts, but we are relying on helm charts hosted somewhere else to install tools in our local test environments when required.
- we are relying on Tilt port forwarding for making grafana accessible from outside the local test environment (which is much simpler than installing an egress …
> ✨ Add observability tools to Tiltfile

- test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
- test/e2e/self_hosted.go
- test/e2e/self_hosted_test.go
This PR add another self-hosted E2E test (tests `clusterctl move`) to also work with ClusterClass based clusters.
Fixes #
> 🌱 e2e: self-hosted (clusterctl move) with clusterclass

- controllers/topology/cluster_controller_test.go
- internal/envtest/environment.go
- main.go
- webhooks/cluster.go
- webhooks/cluster_test.go
This change adds an additional check to the Cluster Webhook to ensure that a ClusterClass referenced by a cluster exists. If the ClusterClass does not exist the Cluster creation or update is rejected. 
This check introduces an expected ordering in the creation and update of the ClusterClass and Cluster objects, and it adds a client to the webhook that is used to fetch the referenced ClusterClass from the API server on Cluster creation and update.
Related to  #5537
> 🌱 Add a check to the Cluster webhook to ensure ClusterClass exists

- controllers/topology/internal/log/log.go
Current implementation of topology reconcile logger always mutate the current logger when calling WithObject/WithRef/WithMachineDeployment in addition to returning a new one.
This could lead to values leaking in while we are doing multiple calls to those methods with different objects, e.g. in 
https://github.com/kubernetes-sigs/cluster-api/blob/87be2ec7eb52d459ddd34e4dacd1ea654128ea63/controllers/topology/reconcile_state.go#L175
This PR removes the side effect, thus making the logger behaviour consistent to the original logr.Logger.
> 🐛 fix topologyReconcileLogger

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
For now we won't implement builtin labels/annotations variables. So let's update the ClusterClass proposal to reflect that to avoid confusing users.
Depending on the outcome of the discussion https://github.com/kubernetes-sigs/cluster-api/issues/5577 we can potentially introduce the labels/annotations variables later and add them to the proposal again.
This PR also syncs the other labels with the latest results from #5534.
Fixes #
> 📖 ClusterClass proposal: remove builtin labels & annotations variables, add new

- docs/book/src/clusterctl/provider-contract.md
This PR update the clusterctl provider contract for providers to opt into cluster class support.
Fixes #
> 📖 update clusterctl provider contract for clusterclass support

- Makefile
- Tiltfile
This PR fixes the Tiltfile so it can start after running `make clean-bin`
It also add `make yq` so the users now can build all the required tools with dedicate make targets
> 🐛 fix Tiltfile from clean-bin

- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/internal/mergepatch/mergepatch_test.go
This PR fixes authoritative mergepatch so it can proper handle the existence of changes on the authoritative or in the two way map
> 🐛 fix authoritative mergepatch

- config/rbac/role.yaml
- controllers/topology/cluster_controller.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/scope/scope.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
This PR solves the same issue of https://github.com/kubernetes-sigs/cluster-api/pull/5430 but with a different solution that is re-entrant
In case the topology reconciler fails in the middle of a reconciliation there could be a case a objects has been created but it is not yet used by the owning object e.g-
- InfrastructureCluster created, error before upgrading the Cluster to use the InfrastructureCluster
- InfrastructureMachine created, error before creating/upgrading the MachineDeployment to use the InfrastructureMachine
The new solution uses a mix of approaches:
- Templates are created with a ownerReference to the cluster, so they will be garbage collected when the cluster is deleted
- InfrastructureCluster and ControlPlane object can use the …
> 🌱 Topology reconciler collects orphan templates in case of errors - version2

- cmd/clusterctl/client/cluster/mover.go
- cmd/clusterctl/client/cluster/mover_test.go
- cmd/clusterctl/client/cluster/objectgraph.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/internal/test/fake_objects.go
This PR fixes the clusterctl move order so that any ClusterClass that are in use are moved to the target cluster before the Clusters that used them are moved.
Fixes #5620
> 🐛 clusterctl: update move to support new cluster validations

- docs/book/src/user/quick-start.md
From release [v0.5.0](https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v0.5.0) of Cluster-api-provider-metal3, the following
environment variables don't need to be exported because Baremetal
Operator is now decoupled from CAPM3. Instead, they need to be
exported when installing Baremetal Operator manually (not via
clusterctl).
> 📖 Update prerequisites for installing Metal3 provider

- test/infrastructure/docker/controllers/alias.go
Fixes the lint error due to package comment not present in test/infrastructure/docker/controllers/alias.go
https://github.com/kubernetes-sigs/cluster-api/runs/4192204922?check_suite_focus=true
Fixes #
> 🌱 fix lint error

- controllers/cluster_controller_phases.go
- controllers/cluster_controller_phases_test.go
reset cluster failuredomain before syncing from infrastructure cluster
Fixes #5478
> :bug: Cluster FailureDomains should always be fully synced rather than additive

- exp/addons/controllers/doc.go
Apparently golangci-lint does not detect the missing package doc on the "move" PRs, but afterwards :/
Fixes #
> 📖 Add exp/addons package documentation

- Dockerfile
- Makefile
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/Makefile
- chore: add trimpath flag to make build more reproducible 
- feature: add windows amd64 target for clusterctl 
I don't have a windows machine, but I spun one in the cloud and did a quick test and worked fine
Fixes #
> ✨ Add windows amd64 target to clusterctl

- cmd/clusterctl/internal/test/fake_objects.go
- controllers/topology/blueprint_test.go
- controllers/topology/cluster_controller_test.go
- controllers/topology/clusterclass_controller_test.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/extensions/patches/engine_test.go
- internal/builder/builders.go
- webhooks/cluster.go
- webhooks/cluster_test.go
- webhooks/clusterclass_test.go
This updates the unit tests in the webhooks folder to use our test builders instead of raw structs. This will make it easier to create new tests for compatibility and variables in the webhooks package.
Fixes #5621
> 🌱 Use internal/builders in tests for webhook package

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Make the nodeDrainTimeout mutable. Should have been mutable before, but the path was wrong.
Fixes #
> 🐛 Make KCP nodeDrainTimeout mutable

- .golangci.yml
- cmd/clusterctl/client/config/reader_memory.go
- cmd/clusterctl/client/repository/repository_versions.go
- cmd/clusterctl/cmd/version_checker.go
- cmd/clusterctl/internal/test/fake_proxy.go
- cmd/clusterctl/internal/test/fake_reader.go
- controllers/cluster_controller.go
- controllers/machine_controller.go
- controllers/machine_controller_phases.go
- controllers/suite_test.go
- internal/envtest/environment.go
- internal/envtest/webhooks.go
- test/e2e/custom_assertions.go
- test/infrastructure/docker/exp/docker/nodepool.go
- util/yaml/yaml.go
This PR:
* enforce `//nolint` vs `// nolint`
* `//nolint` must now contain the linter name
* ignores the ifshort flake for `isDeleteNodeAllowed` in a way that it's not a problem if the ifshort linter does not report that finding
I've opened an issue in the ifshort repo: https://github.com/esimonov/ifshort/issues/23
Fixes #5652
> 🐛 Improve nolint linter config, fix ifshort flake

- docs/proposals/20201020-capi-provider-operator.md
During the last community call, we agreed that operator development can continue in a separate repository. 
This PR updates the operator proposal with information about postponing `clusterctl` refactoring work. cc @asalkeld 
Fixes #
> ✨ Update operator proposal

- docs/book/src/developer/providers/v1.0-to-v1.1.md
This PR adds the latest changes to our migration docs.
Let's wait until the following PRs are merged:
* https://github.com/kubernetes-sigs/cluster-api/pull/5639
* https://github.com/kubernetes-sigs/cluster-api/pull/5595
/hold
Fixes #
> 📖 Update migration doc with latest changes

- util/predicates/generic_predicates.go
This PR fixes the logs in our predicates to log with:
```go
predicate: <predicate-name>, eventType: <eventType>
```
instead of
```go
predicate: <eventType>
```
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/5665#discussion_r750018201
> 🐛 Fix predicate log key/values

- controllers/topology/reconcile_state.go
- internal/topology/check/compatibility.go
- internal/topology/check/compatibility_test.go
- webhooks/clusterclass.go
Add Template compatibility check functions to the Topology/checks package so they can be reused.
> 🌱  Add Template compatibility checks to topology/checks package

- test/e2e/cluster_upgrade.go
- test/e2e/kcp_upgrade.go
- test/framework/controlplane_helpers.go
This PR changes the `UpgradeControlPlaneAndWaitForUpgrade` func so that the right waitfor fields are used to wait for kube-proxy and CoreDNS.
(Just noticed it when copy&pasting for the ClusterClass upgrade test)
Fixes #
> 🐛 test/framework: fix WaitFor parameters for UpgradeControlPlaneAndWaitForUpgrade

- docs/book/src/reference/jobs.md
- test/e2e/config/docker.yaml
In https://github.com/kubernetes/test-infra/pull/24372 we will rename our test jobs and create a new one for v1.0=>main.
The idea behind that is to gain some coverage for v1.0=>main, but still have the most problematic case (upgrade between contract versions) in e2e-full-main.
This PR updates the documentation accordingly.
xref for more context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1637061303045500
Fixes #
> 📖 doc: add clusterctl upgrade job, add new job

- controlplane/kubeadm/config/rbac/role.yaml
- controlplane/kubeadm/controllers/controller.go
`capi-kubeadm-control-plane-manager-role` is missing the `watch` verb for watching CRDs. This PR adds it.
Fixes #5672
>  🐛 Add proper rbac rule in KCP controller for CRD

- util/defaulting/defaulting.go
🌱 
Spelling of webhook in defaulting.go file is wrong, it is webook.
Updated it to webhook.
Fixes # Webhook is misspelt in defaulting.go file #5682
> 🌱 resolved Spelling of webhook in defaulting.go

- internal/envtest/environment.go
Changes the name of the private function 'new' in environment.go so it no longer shadows a builtin.
> 🌱  change function name to prevent shadowing

- cmd/clusterctl/hack/create-local-repository.py
- test/e2e/config/docker.yaml
- test/e2e/data/shared/v1beta1/metadata.yaml
- test/framework/clusterctl/client.go
The recently added clusterctl upgrade test v1-0 to main is currently broken: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-upgrade-v1-0-to-main
This PR adds the configuration to make it work.
Fixes #
> 🐛 Fix clusterctl upgrade test (v1-0 => main)

- docs/book/src/developer/testing.md
Fixes an invalid trailing comma in inlined json in testing.md
> 🐛  Fix invalid json in testing.md

- controllers/topology/cluster_controller.go
- util/predicates/cluster_predicates.go
This will add a predicate in topology/ClusterReconciler for skipping clusters without topology, thus entirely avoiding to trigger reconcile.
Fixes #5120
> 🌱 Add a predicate for skipping clusters without topology

- Makefile
- bootstrap/kubeadm/config/rbac/role.yaml
- test/infrastructure/docker/Makefile
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/5651#discussion_r751407239
> 🐛 Fix CABPK, addons and CAPD manifest generation

- controllers/topology/internal/extensions/patches/api/interface.go
- controllers/topology/internal/extensions/patches/engine.go
- controllers/topology/internal/extensions/patches/inline/json_patch_generator.go
- controllers/topology/internal/extensions/patches/inline/json_patch_generator_test.go
- controllers/topology/internal/extensions/patches/template.go
- controllers/topology/internal/extensions/patches/variables/variables.go
- controllers/topology/internal/extensions/patches/variables/variables_test.go
- go.mod
- go.sum
- test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
- test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
- test/go.sum
This PR builds on top of https://github.com/kubernetes-sigs/cluster-api/pull/5534 and adds the inline JSON patch generation. 
**This PR is now ready for review :)**
Fixes #
> ✨ ClusterClass json patches

- controllers/external/tracker.go
- controllers/topology/cluster_controller.go
Currently the e2e tests are broken (https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main) this PR fixes it.
The test is broken because the capi-controller panics.
Previously:
* we were watching on:
* Clusters, MachineDeployments, ClusterClasses
* after a reconcile we were also watching on
* ControlPlanes, InfrastructureClusters
We had a filter predicate in place and it:
* filtered Clusters correctly
* discarded MachineDeployment and ClusterClass events
* it was not applied on the ControlPlane and InfrastructureCluster watches we create during reconcile
* => this means we were also reconciling non-managed Clusters triggered by events on their ControlPlanes and …
> 🐛 Ensure we're not trying to reconcile the topology of non-managed clusters

- docs/book/src/developer/providers/v1.0-to-v1.1.md
- test/infrastructure/docker/Makefile
- test/infrastructure/docker/exp/controllers/alias.go
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/main.go
Move Docker  Machin Pool controller package to internal and create alias.go for exposing Reconcile
Fixes #
Ref: #5455
> 🌱 Move dockermachinepool controller to internal

- docs/scope-and-objectives.md
Fix broken formatting in the scope and objectives doc that was causing the raw doctoc text to appear in github.
> 🐛 fix contents table  and header in scope and objectives

- cmd/clusterctl/client/cluster/proxy.go
While managing components (for cert-manager or providers) clusterctl implements a discovery function to seek for all the objects part of the component.
This PR makes this code to ignore resources for a provider (e.g Cluster for CAPI, AWSCluster for CAPA, Certificates for cert-manager) given that those resources are not part of the component itself.
This will make operations like upgrade plan or apply and delete resilient to actual state of cert-manager web hooks; in fact, those operations can now work when web-hooks are not functioning (due to provider's deployment already deleted, to provider scaled down to 0, to other errors)
> 🐛clusterctl discovery should ignore provider's resources

- CONTRIBUTING.md
- docs/book/src/reference/glossary.md
- docs/book/src/tasks/kubeadm-control-plane.md
- docs/staging-use-cases.md
Fixes for a number of links in our MD docs which were either outdated or not working properly for some other reason.
> 🐛 fixed a number of broken markdown links

- util/predicates/cluster_predicates.go
The objects in predicates don't have TypeMeta set, so the predicates logged an empty type before.
Now they log the go type, which is more precise anyway as the log is essentially an error message of a type cast.
Fixes #
> 🐛 util/predicates: log correct object type in cluster predicates

- controlplane/kubeadm/internal/etcd_client_generator.go
- controlplane/kubeadm/internal/etcd_client_generator_test.go
This PR fixes etcd client generator panicking when etcd reports a leader members, but the corresponding node does not exists in Kubernetes.
It introduces also a safeguard for another corner cases (func called without any node)
Note: this is candidate for back porting up to release 0.3
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4537
> :bug: ensure etc client generators never return nil without an error

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
Fix header formatting and a number of markdown links in the clusterclass proposal doc.
> 🐛 fix formatting and links for clusterclass proposal

- docs/book/src/developer/architecture/controllers/cluster.md
- docs/book/src/developer/architecture/controllers/control-plane.md
Add Relationship to other Cluster API types for cluster controller
Fixes #
> 📖 Docs cluster controller

- controllers/topology/blueprint_test.go
- controllers/topology/cluster_controller_test.go
- internal/builder/builders.go
- internal/topology/check/compatibility.go
- internal/topology/check/compatibility_test.go
- webhooks/cluster.go
- webhooks/cluster_test.go
- webhooks/clusterclass.go
- webhooks/clusterclass_test.go
This change removes a check in the Cluster Webhook which ensure a cluster can't be moved from one ClusterClass to another. Additional compatibility checks have been added to ensure that the resulting update to the Cluster is protected from some unreconcilable changes as outlined in  the clusterClass proposal  #4985 
Fixes #5318
> ✨ Enable ClusterClass rebase operation

- test/e2e/clusterclass_changes.go
- test/e2e/clusterclass_changes_test.go
- test/framework/cluster_helpers.go
- test/framework/cluster_topology_helpers.go
- test/framework/clusterctl/clusterctl_helpers.go
This PR adds an e2e test which verifies that changes to the ClusterClass and ClusterClass rebases are rolled out correctly.
Fixes #
> ✨ Add ClusterClass changes e2e test

- controlplane/kubeadm/internal/etcd_client_generator.go
- controlplane/kubeadm/internal/etcd_client_generator_test.go
This PR is a backport to release 1-0 branch of https://github.com/kubernetes-sigs/cluster-api/pull/5710
Comment from original PR
> This PR fixes etcd client generator panicking when etcd reports a leader-member, but the corresponding node does not exist in Kubernetes.
> It introduces also a safeguard for another corner case (func called without any node)
> 🐛 ensure etc client generators never return nil without an error

- internal/builder/builders.go
- internal/envtest/environment.go
- internal/topology/check/compatibility.go
- internal/topology/check/compatibility_test.go
- internal/webhooks/cluster_test.go
- internal/webhooks/clusterclass.go
- internal/webhooks/clusterclass_test.go
- main.go
- webhooks/alias.go
Add cluster aware checks to the clusterClass webhook that:
1) Disallow clusterClass deletion if any clusters using the clusterClass still exist
2) Allow removing a MachineDeploymentClass from a Cluster as long as the MachineDeploymentClass is not in use by an existing MachineDeployment does not exist.
Previously:
- any clusterclass would be deleted even if it was in use. 
- MachineDeploymentClasses were not ever allowed to be removed from an existing clusterClass.
Note this is built on top of #5318 and should not be merged until after that PR is merged. Changes introduced in this PR are in the second commit.
Fixes: #5498
> ✨ Make Clusterclass webhook Cluster-aware

- cmd/clusterctl/client/cluster/client.go
- cmd/clusterctl/client/cluster/proxy.go
This patch was originally introduced in PR #5684.
Original name: "clusterctl discovery should ignore provider's resources"
Original commit id: db5b183
Original description:
While managing components (for cert-manager or providers) clusterctl
implements a discovery function to seek for all the objects
part of the component.
This commit makes this code to ignore resources for a provider
(e.g Cluster for CAPI, AWSCluster for CAPA, Certificates for cert-manager)
given that those resources are not part of the component itself.
This will make operations like upgrade plan or apply and delete resilient to actual
state of cert-manager web hooks; in fact, those operations can now work when
web-hooks are not functioning (due to provider's deployment already deleted,
to provider scaled down to 0, to …
> :bug: Backport clusterctl discovery fix to branch release-1.0

- cmd/clusterctl/client/cluster/client.go
- cmd/clusterctl/client/cluster/proxy.go
This patch was originally introduced in PR #5684.
Original name: "clusterctl discovery should ignore provider's resources"
Original commit id: db5b183
Original description:
While managing components (for cert-manager or providers) clusterctl
implements a discovery function to seek for all the objects
part of the component.
This commit makes this code to ignore resources for a provider
(e.g Cluster for CAPI, AWSCluster for CAPA, Certificates for cert-manager)
given that those resources are not part of the component itself.
This will make operations like upgrade plan or apply and delete resilient to actual
state of cert-manager web hooks; in fact, those operations can now work when
web-hooks are not functioning (due to provider's deployment already deleted,
to provider scaled down to 0, to …
> 🐛 Backport clusterctl discovery fix to branch release-0.4

- controllers/topology/clusterclass_controller_test.go
Fix an error string starting with a capital letter.
> 🐛  fix capitalization of error string

- docs/book/src/developer/testing.md
- docs/book/src/developer/tilt.md
This PR documents recent improvements in the way we can run e2e tests locally:
* https://github.com/kubernetes-sigs/cluster-api/pull/5712
* https://github.com/kubernetes-sigs/cluster-api/pull/5707
Fixes #
> 📖  doc: speed up local e2e test execution

- cmd/clusterctl/client/client.go
- cmd/clusterctl/client/config/providers_client.go
- cmd/clusterctl/client/init.go
- cmd/clusterctl/client/repository/client.go
- cmd/clusterctl/client/repository/components.go
- cmd/clusterctl/client/repository/components_client.go
- cmd/clusterctl/client/repository/repository_github.go
- cmd/clusterctl/client/yamlprocessor/processor.go
Fix a number of comments on exported types that were not of the correct format.
> 🐛  fix a number of exported comments

- config/webhook/manifests.yaml
- internal/webhooks/cluster.go
- internal/webhooks/clusterclass.go
This PR adds the correct kubebuilder tags so that ValidateDelete is called on deletion for both Cluster and ClusterClass types. Previously these webhooks had no delete methods enabled and did not require validation on delete.
> 🐛  Add delete webhook kubebuilder config for cluster and clusterclass

- .github/workflows/golangci-lint.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/verify.yml
**What this PR does / why we need it**: Run github actions for lint on all PRs, regardless of branch (including release branches). ref https://github.com/kubernetes-sigs/cluster-api/pull/5718#discussion_r755092085
Fixes #
> 🌱  Run GitHub workflows on all pull requests

- api/v1beta1/machinedeployment_webhook.go
- api/v1beta1/machineset_webhook.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
The labels we apply to the MD changed slightly from v1.0 to main (in the cluster topology reconciler). As we were only patching the metadata.labels but not the selector authoritatively the topology reconciler wasn't able to patch the labels (because the webhook enforces that the metadata.labels match the selector)
Slightly more context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1637763270197700?thread_ts=1637762697.197400&cid=C8TSNPY4T
Verified locally in addition to the unit test by:
* deploying the quickstart e2e test stuff on top of a tilt managed management cluster
* added a label to selector and metadata.labels
* verified that topology reconciler does (and is able to) drop the …
> 🐛 ClusterClass: patch MachineDeployment selector authoritatively

- cmd/clusterctl/client/cluster/installer.go
> 🐛 clusterctl init should report the correct namespace when detecting a provider is already intalled

- Tiltfile
Makes it easier to debug controllers with tilt as we don't have to deal with controller shutdowns because the leader election times out after a few seconds/minutes.
Fixes #
> 🌱 tilt: disable leader election when debugging is enabled

- controllers/topology/desired_state.go
- controllers/topology/internal/extensions/patches/api/interface.go
- controllers/topology/internal/extensions/patches/engine.go
- controllers/topology/internal/extensions/patches/patch.go
> 🌱 ClusterClass: improve logging

- api/v1beta1/cluster_types.go
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- internal/topology/variables/cluster_variable_defaulting_test.go
- internal/topology/variables/cluster_variable_validation.go
- internal/topology/variables/cluster_variable_validation_test.go
Before this PR it was not possible to actually use nullable variables by setting them to `null` (in the YAML).
This PR makes the `Value` field nullable and makes sure the variable validation can handle it
Fixes #
> 🐛 ClusterClass: fix nullable variables

- controlplane/kubeadm/internal/etcd_client_generator.go
This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/5710 to the release 0.3 branch.
Note. Code in this branch was slightly different than o main; unfortunately, this version is not unit-testable given that it is not possible to inject a replacement for NewClient.
> 🐛 ensure etc client generators never return nil

- controllers/topology/internal/extensions/patches/variables/variables.go
- internal/topology/check/compatibility.go
- internal/topology/check/compatibility_test.go
- internal/topology/variables/cluster_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation.go
- internal/webhooks/cluster.go
- internal/webhooks/cluster_test.go
- internal/webhooks/clusterclass.go
- internal/webhooks/clusterclass_test.go
This PR contains a set of small improvements to ClusterClass validation messages.
While working on this, I also made consistent how we are calling validation func in unit tests.
> 🌱 Small improvements to ClusterClass validation messages

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
* Added new unit test to cover this case, original this test case will fail.
Original paths will use appended list directly, this works fine when there is fewer recursion, or there is only one for loop for the diff, but if there are multiple loop, second loop would override the first added array.
Thus I'm creating a new tmp array to do a deepcopy, then add this appended value into allPaths.
> 🐛 Fix adding appended list directly causing changing previous value

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
- internal/builder/builders.go
- internal/webhooks/clusterclass.go
- internal/webhooks/patch_validation.go
- internal/webhooks/patch_validation_test.go
This adds validation rules for patches defined in the clusterClass to the webhook. 
This is ready to review in principle, though a couple of needed validations are missing and marked with a TODO.
Fixes #5613
> 🌱  add patch validation to clusterclass webhook

- Makefile
Some context: Without this fix in case of a diff the error reported by the verify job recommends to run `make generate` which includes conversion gen which is kind of slow :/.
(xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/5735/pull-cluster-api-verify-main/1466009289960198144)
Fixes #
> 🌱 Extend verify modules to detect changes in the test module

- cmd/clusterctl/client/repository/clusterclass_client_test.go
- cmd/clusterctl/client/repository/template_client_test.go
- controllers/external/util_test.go
- controlplane/kubeadm/controllers/scale_test.go
- controlplane/kubeadm/internal/control_plane_test.go
- controlplane/kubeadm/main.go
- test/e2e/custom_assertions.go
Fixes a number of unnecessary redundant parentheses (and one nolint directive) across the CAPI codebase.
> 🌱  remove redundant parantheses across codebase

- controllers/cluster_controller.go
- controllers/cluster_controller_phases.go
- controllers/machine_controller.go
- controllers/machine_controller_phases.go
- controllers/machine_controller_test.go
- controllers/machinedeployment_controller.go
- controllers/machineset_controller.go
- controllers/suite_test.go
- controllers/topology/clusterclass_controller.go
- controllers/topology/suite_test.go
- controllers/topology/util.go
- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/controllers/controller_test.go
- controlplane/kubeadm/controllers/helpers.go
- controlplane/kubeadm/controllers/scale_test.go
- controlplane/kubeadm/controllers/upgrade_test.go
- controlplane/kubeadm/main.go
- main.go
- util/conversion/conversion.go
- util/util.go
Implements first part of https://github.com/kubernetes-sigs/cluster-api/issues/5686
> ⚠️ Update references with an APIReader as fallback

- cmd/clusterctl/client/delete.go
- cmd/clusterctl/client/delete_test.go
Fixes #5661 
Also made the following changes:
- Fixed a minor bug by passing a different namespace for the kubeadm control plan provider as it was sharing same namespace with infra provider and deleting when selected infra provider
- Made version as const variable and used across different providers
> 🐛 Fix clusterctl delete

- internal/topology/variables/cluster_variable_defaulting.go
- internal/topology/variables/cluster_variable_defaulting_test.go
This PR changes our defaulting code so it's also able to default nullable variables.
Split out of https://github.com/kubernetes-sigs/cluster-api/pull/5764/files
Fixes #
> 🐛 ClusterClass: Fix defaulting of nullable variables

- internal/topology/variables/cluster_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation_test.go
- internal/topology/variables/schema_test.go
This PR improves the validation of our enum/default JSON fields in the variable schema and adds a unit test which test that the schema conversion also converts enum/default correctly.
Note: Split out of: https://github.com/kubernetes-sigs/cluster-api/pull/5764
Fixes #
> 🌱 ClusterClass: validate default and enum JSON, extend schema conversion test

- controllers/machineset_delete_policy_test.go
- test/framework/clusterctl/repository.go
This change updates a couple of places in the code place where 'new' was declared as a variable. 'new' is a reserved word in golang and should not be used to declare variables.
Note: There's still a number of instances (especially in webhooks) where new is passed in as a parameter but that's separate to the `new := VAR` instances.
> 🌱 remove usage of reserved word new in codebase

- docs/book/src/reference/providers.md
- docs/book/src/user/quick-start.md
* Packet was acquired by Equinix in 2020 <https://www.equinix.com/newsroom/press-releases/2020/01/equinix-to-acquire-bare-metal-leader-packet>
* The services offered by Packet are now offered as Equinix Metal, since Oct 2020 <https://www.equinix.com/newsroom/press-releases/2020/10/equinix-unveils-fully-automated-and-interconnected-bare-metal-service>
The Packet API (api.packet.net) continues to be supported and is fully integrated with the Equinix Metal experience, so CAPP continues to be a viable provider for existing Packet users and new Equinix Metal users.
This PR avoids confusion by retitling "Packet" to "Equinix Metal" in the documentation. 
⚠️  **Note** The "Packet" tabs have been renamed to "Equinix Metal".  If the space creates problems we …
> 📖  Rename Packet to Equinix Metal (in title only)

- api/v1beta1/cluster_types.go
- api/v1beta1/clusterclass_types.go
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- docs/proposals/202105256-cluster-class-and-managed-topologies.md
- internal/topology/variables/cluster_variable_defaulting.go
- internal/topology/variables/cluster_variable_defaulting_test.go
- internal/topology/variables/cluster_variable_validation_test.go
- internal/topology/variables/clusterclass_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation_test.go
- internal/topology/variables/schema.go
- internal/topology/variables/schema_test.go
More context on the issue.
Fixes #5776
> 🐛 ClusterClass: drop support for nullable

- cmd/clusterctl/client/describe.go
- cmd/clusterctl/client/tree/discovery.go
- cmd/clusterctl/client/tree/discovery_test.go
- cmd/clusterctl/client/tree/tree.go
- cmd/clusterctl/client/tree/tree_test.go
- cmd/clusterctl/cmd/describe_cluster.go
:seedling:
**What this PR does / why we need it**: This deprecates the ``` disable-grouping(false)``` option in the clusterctl describe and uses the ```grouping(true)``` option as per the issue
Fixes #5346 (working on)
Comments in the files haven't been updated yet , wanted to know if I am taking the right approach for this
> :seedling: Replace disable-grouping with grouping option in clusterctl describe command 

- cmd/clusterctl/cmd/describe_cluster.go
Errcheck linter was flagging this for me locally. I'm not sure if we want to explicitly ignore this error or instead fail during init if this error happens. This method fails with an Error if :
```
if flag == nil {
return fmt.Errorf("flag %q does not exist", name)
}
if usageMessage == "" {
return fmt.Errorf("deprecated message for flag %q must be set", name)
}
```
We know these aren't true unless someone actually changes the method call.
> 🐛 explicitly ignore error in flag deprecation

- docs/book/src/tasks/kubeadm-bootstrap.md
There is a broken link to kubeadm certificate management (ttps instead of https as protocol)
Fixes #
> 📖  fix broken link to kubeadm-certs

- controllers/topology/cluster_controller.go
- controllers/topology/internal/mergepatch/mergepatch.go
- controllers/topology/reconcile_state.go
- controllers/topology/reconcile_state_test.go
This PR improves the topology controller so events will be generated for each change applied to the managed objects
> 🌱 Generate events for topology changes

- Makefile
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/config/webhook/manifests.yaml
- controlplane/kubeadm/main.go
- controlplane/kubeadm/webhooks/doc.go
- controlplane/kubeadm/webhooks/scale.go
- controlplane/kubeadm/webhooks/scale_test.go
Signed-off-by: Dharmjit Singh <sdharmjit@vmware.com>
This PR introduces a `Controller-Runtime` validating webhook for `kubeadmControlPlane` scale subresource.
Fixes #5466
> :seedling: Added C-R validating webhook for KCP scale subresource

- api/v1beta1/condition_consts.go
- controllers/topology/cluster_controller.go
- controllers/topology/cluster_controller_test.go
- controllers/topology/conditions.go
- controllers/topology/conditions_test.go
- controllers/topology/desired_state.go
- controllers/topology/desired_state_test.go
- controllers/topology/internal/contract/controlplane.go
- controllers/topology/internal/scope/state.go
- controllers/topology/internal/scope/upgradetracker.go
This PR adds `TopologyReconciled` condition to classy-clusters. 
Fixes #
> ✨ add topology conditions

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/internal/cluster.go
- controlplane/kubeadm/internal/etcd/etcd.go
- controlplane/kubeadm/internal/etcd_client_generator.go
- controlplane/kubeadm/internal/etcd_client_generator_test.go
- controlplane/kubeadm/main.go
Adds a new flag to allow overriding the default etcd dial timeout of now 10 seconds to an arbitrary value.
Fixes #5586
> ✨ Support customizing the etcd dial timeout, increase default to 10s

- api/v1beta1/machinedeployment_webhook.go
- api/v1beta1/machineset_webhook.go
- bootstrap/kubeadm/types/utils.go
- exp/addons/api/v1alpha3/conversion.go
- exp/addons/api/v1alpha4/conversion.go
- exp/addons/api/v1beta1/clusterresourceset_webhook.go
- exp/api/v1alpha4/conversion.go
- exp/api/v1beta1/machinepool_webhook.go
- test/infrastructure/docker/api/v1beta1/dockermachinetemplate_webhook.go
Removes a number of instances of incorrect usage of an import alias across the codebase.
>  🐛 remove redundant alias across the codebase

- cmd/clusterctl/client/cluster/template.go
- cmd/clusterctl/client/repository/repository_github.go
This PR fixes a typo in the GitHub rate limit text.
> 🌱 clusterctl: fix typo for GitHub rate limit error

- internal/builder/builders.go
- internal/topology/variables/cluster_variable_validation.go
- internal/topology/variables/cluster_variable_validation_test.go
- internal/topology/variables/clusterclass_variable_validation_test.go
- internal/webhooks/cluster_test.go
- internal/webhooks/clusterclass.go
- internal/webhooks/clusterclass_test.go
- internal/webhooks/patch_validation.go
This PR adds a check to ensure variables which are currently in use by clusters are not invalidated when a clusterClass is updated.
Fixes: #5461
> 🌱 add check to ensure ClusterClass change doesn't invalidate existing cluster variables

- internal/webhooks/clusterclass.go
- internal/webhooks/clusterclass_test.go
This fixes an issue where non-variable related updates on ClusterClasses are rejected due to incorrect initialisation of an array for checking variables.
/cc @sbueringer
> 🐛 Fix incorrect array initalization causing incorrect webhook failures

- CONTRIBUTING.md
- docs/book/src/reference/jobs.md
- docs/book/src/reference/versions.md
- docs/book/src/user/quick-start.md
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
- test/infrastructure/docker/internal/docker/machine.go
Partially implements #5793
Related: https://github.com/kubernetes/test-infra/pull/24554
> 🌱 Use Kubernetes 1.23 in: quickstart, CAPD, e2e tests + update doc

- cmd/clusterctl/client/describe.go
- cmd/clusterctl/client/tree/discovery.go
- cmd/clusterctl/client/tree/discovery_test.go
- cmd/clusterctl/client/tree/tree.go
- cmd/clusterctl/client/tree/tree_test.go
- cmd/clusterctl/cmd/describe_cluster.go
🌱 
This is a continuation of the issue which modifies clusterctl describe command . This works on replacing the ```--disable-no-echo(false)``` to ```echo(false)`` command.
Fixes #5346
> 🌱   Replace disable-echo option with echo option in clusterctl describe 

- .golangci.yml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
- test/infrastructure/docker/exp/api/v1alpha3/dockermachinepool_types.go
- test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go
- test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
- test/infrastructure/docker/internal/docker/kind_manager.go
- test/infrastructure/docker/internal/docker/machine.go
- test/infrastructure/docker/internal/docker/types/node.go
This updates a filter in our golangci-lint configuration to start
enforcing the presence of godoc comments on any functions or variables
that are exported in the `infrastructure/docker` path.
This aligns with most of the rest of the codebase and
makes it so there is (somewhat) useful documentation for anything that
can be accessed externally from a package.
> 🌱 Enforce godoc comments for exported functions

- metadata.yaml
This PR adds the upcoming v1.1 release series to the `metadata.yaml`
I tried to deploy providers via the local repository (generated via `cmd/clusterctl/hack/create-local-repository.py` which is using the top-level `./metadata.yaml`)
and it failed because the release series was missing:
```bash
./bin/clusterctl init --core cluster-api:v1.1.99 --bootstrap kubeadm:v1.1.99 --control-plane kubeadm:v1.1.99 --infrastructure docker:v1.1.99 --config ~/.cluster-api/dev-repository/config.yaml
Fetching providers
Error: invalid provider metadata: version v1.1.99 for the provider capi-system/cluster-api does not match any release series
```
I think we have to add it before the release anyway.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> 🌱 Add v1.1 to metadata.yaml

- docs/book/src/clusterctl/developers.md
- test/infrastructure/docker/templates/cluster-template-development.yaml
- test/infrastructure/docker/templates/cluster-template-topology.yaml
- test/infrastructure/docker/templates/clusterclass-quick-start.yaml
More context in the issue.
Tested manually against a tilt-managed cluster (envsubst'ed cluster-template manually + kubectl apply)
Note: The KCPTemplate is only valid after https://github.com/kubernetes-sigs/cluster-api/pull/5788 has been merged.
Fixes #5730
> 🌱 CAPD: add ClusterClass cluster-template

- controllers/topology/cluster_controller_test.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Co-authored-by: killianmuldoon <kmuldoon@vmware.com>
Co-authored-by: Yuvaraj Kakaraparthi <kakaraparthy@vmware.com>
Fixes #
> 🐛 Fix cluster topology and UpdateCoreDNS test flakes

- docs/book/src/developer/providers/v1.0-to-v1.1.md
- test/framework/bootstrap/kind_util.go
- test/framework/cluster_proxy.go
- test/framework/docker_logcollector.go
- test/framework/kubetest/run.go
- test/infrastructure/container/docker.go
- test/infrastructure/container/fake.go
- test/infrastructure/container/interface.go
- test/infrastructure/container/interface_test.go
- test/infrastructure/docker/controllers/alias.go
- test/infrastructure/docker/exp/controllers/alias.go
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/exp/internal/docker/nodepool.go
- test/infrastructure/docker/internal/controllers/dockercluster_controller.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
- test/infrastructure/docker/internal/docker/kind_manager.go
- test/infrastructure/docker/internal/docker/kind_manager_test.go
- test/infrastructure/docker/internal/docker/loadbalancer.go
- test/infrastructure/docker/internal/docker/machine.go
- test/infrastructure/docker/internal/docker/types/node.go
- test/infrastructure/docker/internal/docker/types/node_test.go
- test/infrastructure/docker/internal/docker/util.go
- test/infrastructure/docker/main.go
This builds on the CAPD changes to use the docker API instead of calling
out to the CLI. With those changes, it is now possible to insert a
testing fake and perform unit testing for the code that would normally
call out to Docker.
The test coverage introduced by this change is not extensive, but it
does add coverage where we previously had none at all. With this basic
coverage in place, it should now be easier to add new tests if we find
specific scenarios that we want to reproduce and validate for any new
bug reports.
Fixes #4380
> 🌱 Add test coverage for container runtime calls

- api/v1beta1/clusterclass_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- internal/topology/variables/cluster_variable_validation_test.go
> 🌱 ClusterClass: clarify that enum works with all types

- internal/webhooks/test/clusterclass_test.go
- internal/webhooks/test/doc.go
- internal/webhooks/test/suite_test.go
This PR adds basic integration tests for the ClusterClass webhook assessing whether Create, Delete and Update validations work as expected with a real API server.
> 🌱  add basic integration tests for ClusterClass webhook

- test/e2e/config/docker.yaml
- test/e2e/data/infrastructure-docker/v1beta1/cluster-template-ipv6/cluster-ipv6.yaml
- test/e2e/data/infrastructure-docker/v1beta1/cluster-template-ipv6/kustomization.yaml
- test/e2e/quick_start.go
- test/e2e/quick_start_test.go
Turns out the IPv6 test requires an IPv6 management cluster. And from an IPv6 management cluster we're not able to create IPv4 clusters. => we have to separate IPv4 and IPv6 tests in separate jobs.
The following changes should be made to our test jobs:
* `pull-cluster-api-e2e-full-main` & `periodic-cluster-api-e2e-main` & `periodic-cluster-api-e2e-mink8s-main`: 
* `GINKGO_SKIP`: add `[IPv6]`
* `pull-cluster-api-e2e-informing-main`: (to be created)
* `GINKGO_SKIP` `[IPv6]`
* `GINKGO_FOCUS`: `[PR-Informing]`
* `pull-cluster-api-e2e-informing-ipv6-main`: (previously `pull-cluster-api-e2e-ipv6-main`) (TBD?)
* Drop `DOCKER_SERVICE_CIDRS` & `DOCKER_POD_CIDRS`
* `GINKGO_FOCUS`: `[IPv6][PR-Informing]`
**Which issue(s) this PR fixes** *(optional, in `fixes …
> 🌱 test/e2e: Implement release informing jobs with CC & IPv6

- controllers/topology/internal/extensions/patches/engine.go
- controllers/topology/internal/extensions/patches/inline/json_patch_generator.go
- controllers/topology/internal/extensions/patches/inline/json_patch_generator_test.go
Previously remove patch generation failed because there was no value. Now it doesn't calculate a value for remove patches.
Fixes #
> 🐛 ClusterClass: fix remove patches

- test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
- test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Add variable examples and description and patch descriptions to the files used in the ClusterClass quickstart end to end tests and the clusterclass-quick-start.yaml docker template.
> 🌱 added variable example and description to clusterclass yamls

- cmd/clusterctl/client/cluster/mover.go
Co-authored-by: Stefan Büringer buringerst@vmware.com
Previously errors thrown by os.Stat were not handled if they were not nil. This may may be relate to some failures seen in the Test_objectMover_backupTargetObject test.
>  🐛 Fix/backup restore error handling.

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
This PR updates the proposal based on recent developments.
Fixes #
> 📖 Update ClusterClass proposal

- api/v1beta1/machineset_types.go
- controllers/machineset_delete_policy.go
- controllers/machineset_delete_policy_test.go
I would like to add priority condition to the machineset's delete policy.
It makes sense for unhealthy machines to have a higher deletion priority than healthy machines.
Fixes #
> ⚠️ MachineSet on scale down now takes into account NodeHealthy condition

- CONTRIBUTING.md
> 📖 API conventions: add note about when struct fields should be pointer

- .golangci.yml
- internal/webhooks/cluster.go
- internal/webhooks/clusterclass.go
Enable the predeclared linter and remove instances where go keywords were used as variable names in the codebase.
> 🌱 enable predeclared linter and fix problems

- internal/topology/variables/cluster_variable_defaulting.go
- internal/topology/variables/cluster_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation.go
- internal/topology/variables/clusterclass_variable_validation_test.go
- internal/topology/variables/schema.go
- internal/topology/variables/schema_test.go
This PR adds schema validation for values defined for default, enum and example in a ClusterClass variable. 
e.g. 
If a user defines a schema with an integer and minimum value 1 a default, example or enum member of -100 will be found to be invalid and the ClusterClass will be rejected on creation or update.
It also removes the Kubernetes CRD default validation that was part of the code previously.
Fixes #5831
> 🌱 add validation for default, enum and example definitions in variables

- bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
- bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
This fix adds logic to the Kubeadm bootstrapper that allows it to release the lock on reconciliation of control plane machines if the machine currently holding the lock can not be found. 
Previously if the machine to get the lock was deleted for any reason the cluster control plane was stuck indefinitely in 'Initializing'. 
Fixes #5814 (speculatively)
> 🐛  Add unlock mechanism to the kubeadm bootstrap provider

- docs/book/src/clusterctl/provider-contract.md
This changes add the `CAPG:  cluster.x-k8s.io/provider=infrastructure-gcp` in the `docs/book/src/clusterctl/provider-contract.md` of line number 202
Fixes #5852
> 📖 Add CAPG to provider contract book page

- bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
- bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
This fix adds logic to the Kubeadm bootstrapper that allows it to release the lock on reconciliation of control plane machines if the machine currently holding the lock can not be found.
Previously if the machine to get the lock was deleted for any reason the cluster control plane was stuck indefinitely in 'Initializing'.
Backport of https://github.com/kubernetes-sigs/cluster-api/pull/5824
Rif: #5814
> 🐛 Add unlock if bootstrap machine holding lock does not exist

- bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
- bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
Manual fix for automated PR cherry pick failure in  #5857
Fixes: #5814
> Add unlock if bootstrap machine holding lock does not exist

- api/v1beta1/condition_consts.go
- controllers/machine_controller.go
- controllers/machine_controller_test.go
- controllers/machinehealthcheck_controller.go
- controllers/machinehealthcheck_controller_test.go
- controllers/machinehealthcheck_targets.go
- controlplane/kubeadm/controllers/remediation.go
- controlplane/kubeadm/controllers/remediation_test.go
- controlplane/kubeadm/internal/control_plane_test.go
- util/collections/machine_filters.go
- util/collections/machine_filters_test.go
Fix typo of the `HealthCheckSucceded` condition
N/A
> 🌱 Deprecate the HealthCheckSucceded condition for typo

- controllers/machinehealthcheck_targets.go
- controllers/topology/clusterclass_controller.go
- util/annotations/helpers.go
- util/predicates/generic_predicates.go
Thank you for opportunity and guidance.
Fixes #5539
> ⚠️ Updated function name  HasPausedAnnotation to HasPaused and HasSkipRemediationAnnotation to HasSkipRemediation

- controlplane/kubeadm/internal/etcd_client_generator.go
- controlplane/kubeadm/internal/etcd_client_generator_test.go
The etcd connection was deferred-close inside a loop which causes ~all but the last loop iteration to leak connections~ the connections to be held longer than necessary (i.e., until the entire loop completes). Address the issue by moving the logic into a dedicated method that is invoked once per each iteration.
> 🌱  Address in-loop deferred-close in etcd client generator

- test/framework/controlplane_helpers.go
**What this PR does / why we need it**: The control plane upgrade helper in the test framework was overriding Etcd/DNS config by setting the whole struct instead of just updating the image tag. This was causing validation errors when values were previously set and getting removed as these fields are immutable, eg:
```
admission webhook "validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io" denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io "k8s-upgrade-and-conformance-orktd6-control-plane" is invalid: spec.kubeadmConfigSpec.clusterConfiguration.etcd.local.dataDir: Forbidden: cannot be modified[0m
```
Fixes …
> 🐛  Fix control plane upgrade test etcd and dns image upgrade

- controllers/machinehealthcheck_controller.go
return delete remediation object error triger next reconcile
Fixes #
> 🐛 Return an error if we can't delete the external remediation object

- controllers/machineset_controller.go
- controllers/machineset_controller_test.go
This PR prevents CAPI to leave orphaned InfrestructureMachines when a MachineSet creates a machine that gets deleted before the controllers setting ownerRef to the corresponding InfrastructureMachines.
This is achieved by setting an additional ownerRef to the MachineSet, thus triggering  InfrestructureMachines cleanup when the MS gets deleted.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5483
> 🐛 Prevent orphaned InfrastructureMachines

- docs/book/src/tasks/certs/generate-kubeconfig.md
As described in https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles, group "system:masters" is the super-user, so we should set subject "/O=system:masters" rather than "/CN=system:masters".
Fixes #
> :book: fix docs about generate kubeconfig use CA

- Makefile
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
1. Standardised target names for all the components.
2. Consistent documentation across all the targets.
3. Added dedicated targets for missing verify and hack/tools components.
4. Re-shuffled order, grouped targets for easy reading, understanding and maintenance.
Fixes #5574
> :sparkles: refactor and update Makefile

- hack/kind-install-for-capd.sh
- hack/tools/tilt-prepare/main.go
🌱 
Replaces code to pickup kind cluster alternate from env variables instead of hardcoding it to capi-test. If env variable is not present the default value of capi-test cluster name is taken.
Fixes #5820
> 🌱 replace hardcoded kind cluster name to pickup env values

- test/framework/controlplane_helpers.go
In e2e test, when deploying a workload cluster,  after applying the template of KCP, if the KCP object doesn't exist yet, then the test will fail. It can be a bit problematic when the test runs in a system with high latency, and KCP object needs more time to be created. 
This PR moves the KCP object existence check into an Eventually assertion, so the test will retry to get the KCP object if it fails to do it in the first times.
> 🌱 Add timeout to check if KCP object exists

- controllers/noderefutil/providerid.go
🌱 
This modifies the String method which implements the Stringer interface to receive value instead of pointers  
Fixes #5755 (working on)
If this seems correct would like to modify the other ones as well
> 🌱  modify providerid struct string method to receive value

- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
So we do not produce format key in bootstrap data with empty value.
Fixes #5823
NOTE: I only unit-tested this. Let me know if I should write more automated tests for it somewhere.
> ✨Set default KubeadmConfig format to cloud-config✨

- test/framework/bootstrap/kind_provider.go
> 🌱 test/e2e/framework: log kind output during cluster creation

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
- test/e2e/clusterctl_upgrade.go
Currently the KubeadmConfig format in KCP is immutable. This means that KCP objects created with older versions of CAPI cannot be adopted (because any update on KCP would automatically try to set the format to "cloud-config" which is then blocked because a mutation from "" to "cloud-config" is forbidden).
Thus this PR suggests to make the format mutable. I think it's fine to do that as I don't see a reason why it shouldn't be possible to change the format.
Note: also includes a minor improvement to the e2e test logs which was done when debugging this issue.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …
> 🐛 kcp: make KubeadmConfig format mutable

- OWNERS_ALIASES
Regret to inform that I'm stepping away from Cluster API so will not be able to review PRs. I wasn't in the owners file long enough to justify moving to emeritus either.
Fixes #
> :seedling: OWNERS: Remove randomvariable (Naadir Jeewa)

- docs/book/src/user/quick-start.md
AZURE_RESOURCE_GROUP is an optional variable. However, if it is
not mentioned here, developers may be confused where the cluster
goes.
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
It improves quick start doc of capz.
Fixes #
> 📖 Update quick start doc for CAPZ

- .golangci.yml
- Makefile
- controllers/alias.go
- controllers/machinedeployment_sync_test.go
- controllers/machinehealthcheck_controller.go
- controllers/machineset_controller.go
- docs/book/src/developer/providers/v1.0-to-v1.1.md
- go.mod
- internal/controllers/cluster/cluster_controller.go
- internal/controllers/cluster/cluster_controller_phases.go
- internal/controllers/cluster/cluster_controller_phases_test.go
- internal/controllers/cluster/cluster_controller_test.go
- internal/controllers/cluster/doc.go
- internal/controllers/cluster/suite_test.go
- internal/controllers/machine/doc.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machine/machine_controller_node_labels.go
- internal/controllers/machine/machine_controller_node_labels_test.go
- internal/controllers/machine/machine_controller_noderef.go
- internal/controllers/machine/machine_controller_noderef_test.go
- internal/controllers/machine/machine_controller_phases.go
- internal/controllers/machine/machine_controller_phases_test.go
- internal/controllers/machine/machine_controller_test.go
- internal/controllers/machine/machine_helpers.go
- internal/controllers/machine/machine_helpers_test.go
- internal/controllers/machine/suite_test.go
This PR moves a first group of controllers from /controllers to internal/controllers
Rif https://github.com/kubernetes-sigs/cluster-api/issues/5455
> 🌱 Move controllers to internal - part1

- test/framework/bootstrap/kind_provider.go
This PR improves logging, so that RunErrors occurring when bootstrap cluster creation fails are readable.
This makes it possible to read not only the errors on the triage PR, but also the ones occurring in our periodics.
Fixes #
> 🌱 test/framework: improve logging of RunErrors occurring when bootstrap cluster creation fails

- controllers/topology/internal/extensions/patches/engine.go
This PR makes it possible to patch ControlPlane.spec.machineTemplate.nodeDrainTimeout via ClusterClass patches.
Fixes #
> 🌱 ClusterClass: make ControlPlane.spec.machineTemplate.nodeDrainTimeout patchable

- docs/book/src/developer/providers/v1.0-to-v1.1.md
- test/e2e/e2e_suite_test.go
- test/framework/bootstrap/kind_provider.go
- test/framework/bootstrap/kind_util.go
This PR improves the E2E test framework by collecting kind logs in case creating the bootstrap cluster fails for any reason
> 🌱 Collect kind logs when e2e bootstrap fails

- internal/controllers/topology/cluster/mergepatch/managed_paths.go
- internal/controllers/topology/cluster/mergepatch/managed_paths_test.go
- internal/controllers/topology/cluster/mergepatch/mergepatch.go
- internal/controllers/topology/cluster/mergepatch/mergepatch_test.go
This PR improves the managed field annotation recently introduced for Topology managed objects by reducing the annotation length by about 60% in the case of real KCP objects.
Note: the value is not human readable, but it can be easily converted by `pbcopy | base64 -d | gunzip` (pbcopy can be replaced by echo or other means to get the annotation content)
Fixes #
> 🌱 Improve managed field annotation encoding

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
This PR adds information to the ClusterClass proposal describing how MachineHealthChecks can be added to the API so that clusters stamped from a particular ClusterClass have MachineHealthChecks generated for them from  a common spec.
This proposal also introduces full defaulting for a MachineHealthChecks generated from a ClusterClass meaning that the check itself needs only be added as an empty struct to the ClusterClass in order to get a standard MHC configuration generated.
C/F #5125
> 📖  Add MHCClass spec and details to proposal

- test/e2e/cluster_upgrade.go
- test/framework/cluster_topology_helpers.go
Currently, the cluster upgrade test fails when the worker count is 0 (https://github.com/kubernetes-sigs/cluster-api/issues/4896#issuecomment-1010523122). This PR makes sure we skip the upgrade of MachineDeployments and MachinePools in that case.
Fixes #
> 🐛 test/e2e/cluster-upgrade: skip worker upgrades if worker count is 0

- cmd/clusterctl/client/cluster/cert_manager.go
- cmd/clusterctl/client/cluster/cert_manager_test.go
- internal/contract/controlplane.go
- util/version/version.go
- util/version/version_test.go
As an operator, I would like to upgrade `cert-manager` using `clusterctl` even when the version hasn't changed. For example, if I created a new build due to a change in a downstream dependency (imagine security updates in a base image) but I'm still using the same upstream code.
In order to work around this, I could artificially bump the version, but that, aside from being confusing, could be problematic if in the future I need to upgrade to the real version.
The pre-release section could also be used for to work around this, but I find it confusing as well since these are not necessarily pre-release builds, they are production ready.
I propose to use the build metadata in the semver (which fits very well this usecase) to detect such changes. This …
> 🌱 Check for build metadata in cert-manager version 

- internal/webhooks/patch_validation.go
- internal/webhooks/patch_validation_test.go
With this PR it's now possible to access nested fields of complex variables (objects and arrays) via `.valueFrom.variable`. This was already implemented in the JSON patch generator, but blocked by the webhook. 
I think complex variables and the Patch validation were implemented at the same time so we missed it.
Fixes #
> 🐛 ClusterClass: allow accessing nestedFields via valueFrom.variable

- internal/controllers/topology/cluster/mergepatch/managed_paths.go
- internal/controllers/topology/cluster/mergepatch/managed_paths_test.go
- internal/controllers/topology/cluster/mergepatch/mergepatch.go
- internal/controllers/topology/cluster/mergepatch/mergepatch_test.go
- internal/controllers/topology/cluster/reconcile_state_test.go
This PR adds a test which runs multiple reconciles and thus validates if a sequence of reconciles behave as expected. The most important behavior we're verifying that way is the handling of `managed-field-paths`.
Fixes #
> 🌱 ClusterClass: Add reconcile repeatedly test

- CONTRIBUTING.md
- README.md
Looks like our Kubernetes discuss forum is gone: https://discuss.kubernetes.io/c/contributors/cluster-api
At the moment all our PRs are blocked from merge, because the link checker fails.
Fixes #
> 🐛 Drop links to Kubernetes discuss forum.

- docs/book/src/tasks/experimental-features/cluster-class/upgrade-cluster.md
- internal/webhooks/cluster.go
- internal/webhooks/cluster_test.go
This PR blocks +2 minor version upgrade of kubernetes version in clusters with managed topologies.
Fixes #5853
> 🌱 block +2 minor version upgrade in cluster topology

- internal/controllers/topology/cluster/reconcile_state.go
Make the Topology/Cluster controller authoritative over the failuredomain path in a machineDeployment spec.template.spec during reconciliation.
Authoritative control by the Controller mean a user change to remove it from the Cluster.spec.topology.machineDeploymentTopology is reflected in the updated object.
> 🐛  Make Topology controller authoritative on MachineDeployment failuredomain

- internal/topology/check/compatibility.go
- internal/topology/check/compatibility_test.go
- internal/webhooks/cluster.go
Setting the MD topology name to an empty string leads to errors during reconcile, so this PR now
validates that it is not empty.
Fixes #
> 🌱 ClusterClass: validate MachineDeployment topology name not empty

- docs/book/src/user/troubleshooting.md
This PR adds steps to set inotify limits inside the VM running as part of Docker Desktop. In Docker's 4.3 update a number of errors with the message "too many open files" prevented more than a single digit number of containers being run on a host. 
Changing the inotify limits as described here in the Docker VM will resolve the issue. I don't think we should close the issue with this change as it would be better to find out if Docker can have these limits set by default.
Addresses #5940 
> 📖  Add steps to resolve Docker Desktop inotify limit issues

- cmd/clusterctl/client/client.go
- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/cluster/assets/topology-test/existing-clusterclass-and-cluster.yaml
- cmd/clusterctl/client/cluster/assets/topology-test/modified-cluster.yaml
- cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
- cmd/clusterctl/client/cluster/client.go
- cmd/clusterctl/client/cluster/internal/dryrun/client.go
- cmd/clusterctl/client/cluster/internal/dryrun/doc.go
- cmd/clusterctl/client/cluster/proxy.go
- cmd/clusterctl/client/cluster/topology.go
- cmd/clusterctl/client/cluster/topology_test.go
- cmd/clusterctl/client/topology.go
- cmd/clusterctl/cmd/topology.go
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- internal/controllers/topology/cluster/cluster_controller.go
- test/go.mod
- test/go.sum
This PR implements a alpha new command: `clusterctl alpha topology-dryrun`.
This command can be used to dry run ClusterClass and/or Cluster changes.
The command expects as input a file that includes the new or modified objects. Example: the file can contain a modified Cluster or a modified ClusterClass. The output lists all the Clusters and ClusterClasses that will be affected. 
The following example shows the output when dry-running to create a Cluster that uses a pre-installed ClusterClass.
Special thanks to @fabriziopandini for providing guidance for this feature. 🙂
Fixes #5319
> ✨ clusterctl alpha topology-dryrun

- internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
This change adds formatting to a condition and event in the machineHealthCheck controller that handles the percentage sign included in the message.
Previously this message would print as: 
` Remediation is not allowed, the number of not started or unhealthy machines exceeds maxUnhealthy (total: 1, unhealthy: 0, maxUnhealthy: 45%!)(MISSING)
`
Due to the percentage sign being included in the unhealthyRange string. There's an example here: https://go.dev/play/p/mX6DG6oRzKW
> 🐛  Fix to improper formatting of UnhealthyRange

- internal/controllers/topology/cluster/desired_state.go
- internal/controllers/topology/cluster/desired_state_test.go
- internal/controllers/topology/cluster/reconcile_state.go
- internal/controllers/topology/cluster/reconcile_state_test.go
> 🐛  Make MHC ClusterClass authoritative on paths

- docs/book/src/developer/guide.md
> 🌱 book: add API conversion code walkthrough video

- Makefile
This PR improve make release-notes target to generate a specific message for pre-releases.
> 🌱 make release-notes for pre-releases

- OWNERS
please see [kubernetes/community#6334](https://github.com/kubernetes/community/issues/6334)
What type of PR is this?   
/kind cleanup
Which issue(s) this PR fixes: 
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?  
```
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
```
> 🌱 Validate OWNERS files - remove sections about emeritus reviewers.

- .golangci.yml
- cmd/clusterctl/client/config/reader_viper.go
- cmd/clusterctl/client/repository/repository_github.go
- hack/tools/mdbook/embed/embed.go
- hack/tools/mdbook/releaselink/releaselink.go
- test/e2e/clusterctl_upgrade.go
- test/framework/clusterctl/repository.go
- test/framework/kubernetesversions/versions.go
- test/infrastructure/container/docker.go
This PR proposes to enable two new linters:
* unused: Checks Go code for unused constants, variables, functions and types
* noctx: finds sending http request without context.Context
Fixes #
> 🌱 linter: enable noctx and unused

- controlplane/kubeadm/internal/controllers/remediation.go
- controlplane/kubeadm/internal/controllers/remediation_test.go
Got a warning message while provisioning a cluster.
NAME          READY  SEVERITY  REASON                                                   SINCE  MESSAGE                                                         
/wla              False  Warning   WaitingForRemediation @ Machine/wla-control-plane-jtqgv  3h42m  KCP can't remediate if current replicas are less or equal then 1
"then" should be "than".
But to align with line 114, propose to use "equal to".
> 🌱 Fix a typo in remediation.go

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
This PR updates the proposal according to latest changes in https://github.com/kubernetes-sigs/cluster-api/pull/5928
Fixes #
> 🌱 ClusterClass: add MD variables to the ClusterClass proposal

- docs/book/src/developer/providers/v1.0-to-v1.1.md
Updates v1.0-v1.1 migration doc with deprecation notice of  `HasPausedAnnotation` and `HasSkipRemediationAnnotation` functions that was missed to be added in #5545
> 📖 Add HasPausedAnnotation and HasSkipRemediationAnnotation func deprecation notes to v1.0-v1.1 migration doc

- exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
In case of a backup, the CRS Binding does have a Cluster set in the `ownerRef`. This leads to a nil pointer exception. 
This PR adds a check around the presence of this `ownerRef`. 
Fixes #5961
> 🐛 handle error in case ownerRef is not set on crs binding

- docs/proposals/202105256-cluster-class-and-managed-topologies.md
I'm aware that we can't keep those YAMLs up-to-date forever, but I almost used the wrong YAML (deployments => machineDeployments) based on the proposal.
I fixed that issue and also upgraded to v1beta1 (machineHealthCheck only exists there) to avoid confusion for readers.
(Intellij at least now doesn't report any issues in those YAMLs anymore)
Fixes #
> 📖 ClusterClass: fix YAMLs in proposal

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
This change allows KCP to perform an upgrade when the version of CoreDNS is not increased. This will allow older branches to stay on the same CoreDNS version when performing upgrade e2e tests for later versions of Kubernetes.
Fixes #5952
> 🐛  Allow KCP to Update when CoreDNS version doesn't change

- CONTRIBUTING.md
- docs/book/src/user/quick-start.md
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/infrastructure/docker/Dockerfile
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
- test/infrastructure/docker/internal/docker/machine.go
Upgrade to Kubernetes 1.23.3 in Quickstart and CI
Partially implements  #5995
> :sparkles: Upgrade to Kubernetes 1.23.3 in Quickstart and CI

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
This change allows KCP to perform an upgrade when the version of CoreDNS is not increased. This will allow older branches to stay on the same CoreDNS version when performing upgrade e2e tests for later versions of Kubernetes.
Cherry pick of #5986
Fixes #5952
> 🐛 Allow KCP to Update when CoreDNS version doesn't change

- docs/book/src/clusterctl/commands/alpha-topology-plan.md
Adds documentation for the new `clusterctl alpha topology plan` command.
Fixes #
> 📖 documentation for `clusterctl alpha topology plan`

- docs/book/src/developer/providers/implementers-guide/generate_crds.md
Update some links broken in a recent PR.  This change points those links to the older version of the book where the links aren't broken.
This is a quick fix for the CI and we shouldn't close the underlying issue. 
Alternative better fixes could be:
1. Document the contract label and other information somewhere else
2. Rewrite the implementers guide for a more up to date version of Cluster API
References #6027
> 🐛 Point broken links to older book version

- .github/workflows/golangci-lint.yml
- .golangci.yml
- cmd/clusterctl/client/alpha/rollout_pauser.go
- cmd/clusterctl/client/alpha/rollout_restarter.go
- cmd/clusterctl/client/alpha/rollout_resumer.go
- cmd/clusterctl/client/client_test.go
- cmd/clusterctl/client/cluster/mover_test.go
- cmd/clusterctl/client/common.go
- cmd/clusterctl/client/config/providers_client.go
- cmd/clusterctl/client/config/reader_viper.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/delete.go
- cmd/clusterctl/cmd/config_repositories.go
- controlplane/kubeadm/internal/workload_cluster_conditions.go
- controlplane/kubeadm/internal/workload_cluster_etcd.go
- internal/webhooks/cluster.go
- internal/webhooks/cluster_test.go
- internal/webhooks/clusterclass_test.go
- test/framework/clusterctl/logger/log_file.go
- test/framework/docker_logcollector.go
- test/framework/ginkgoextensions/output.go
- test/framework/kubetest/setup.go
- test/infrastructure/container/docker.go
- test/infrastructure/docker/api/v1beta1/dockercluster_webhook.go
- test/infrastructure/docker/internal/docker/machine.go
This PR upgrades golangci-lint to v1.44 and adds the new `containedctx` linter (for context, see: # https://go.dev/blog/context-and-structs)
I also looked at the other new linters in the release notes, but I don't think we should add one of them:
* decorder: Sounds too opinionated
* errchkjson: If I got it right, it would allow ignoring errors on e.g. json.Marshal if it's safe. Not sure if we need/want that.
* maintidx: Checks for maintainability (similar to gocyclo). Based on their doc it's an "an experimental value". It would currently only complains about our ClusterctlUpgradeSpec test. I think let's just continue using gocyclo for now.
* grouper: Can enforce grouping. I think we have a few …
> 🌱 Upgrade to golangci-lint v1.44 and fix findings

- docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
Improving documentation on how to change a ClusterClass
Rif https://github.com/kubernetes-sigs/cluster-api/issues/5953
> 📖 Document how to change a ClusterClass

- docs/book/src/developer/providers/implementers-guide/generate_crds.md
> 📖 book: Use relative links in generate CRDs doc

- bootstrap/kubeadm/config/manager/manager.yaml
- config/manager/manager.yaml
- controlplane/kubeadm/config/manager/manager.yaml
- controlplane/kubeadm/internal/controllers/controller_test.go
- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_conditions_test.go
- controlplane/kubeadm/internal/workload_cluster_test.go
- docs/book/src/user/troubleshooting.md
- test/framework/deployment_helpers.go
- test/infrastructure/docker/config/manager/manager.yaml
This PR is required to be compatible with the latest changes in Kubernetes 1.24.
In Kubernetes 1.24 on control plane nodes kubeadm now:
* sets both `node-role.kubernetes.io/control-plane` and `node-role.kubernetes.io/master` taints
* doesn't set the `node-role.kubernetes.io/master` label anymore (only `node-role.kubernetes.io/control-plane`)
Thus:
* the toleration `node-role.kubernetes.io/control-plane` is additionally added so our controllers can also run on 1.24 control-plane nodes.
* KCP now considers nodes with the old or the new (or both) label(s) as control plane nodes. This way KCP now supports:
* v1.19: where only the old label is set
* v1.20-v1.23: where both labels are set
* v1.24: where …
> 🌱 Support new control plane label and taint

- docs/book/src/reference/versions.md
Add a section to the Versions page in the book explaining which versions of Kubernetes may be obstructed as an upgrade target by its associated CoreDNS version when using specific versions of Cluster API.
Addresses #5952
> 📖 Add section on CoreDNS version support to the CAPI book

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Adds an example to showcase how to make refs configurable via variables.
Fixes #
> 📖 book: Writing a ClusterClass: add ref example

- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/user/troubleshooting.md
Signed-off-by: killianmuldoon kmuldoon@vmware.com
Update cert manger URL and add a troubleshooting section for older versions of CAPI. This PR fixes an issue where a change in the location of the cert manager repo prevented clusterctl init from working.
Fixes: #6051
> 🐛 Fix cert manager repo and add troubleshooting guide

- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/user/troubleshooting.md
Update cert manger URL and add a troubleshooting section for older versions of CAPI. This PR fixes an issue where a change in the location of the cert manager repo prevented clusterctl init from working.
Fixes: #6051
> 🐛  Fix cert manager repo and add troubleshooting guide

- docs/book/src/developer/e2e.md
- docs/book/src/developer/guide.md
- docs/book/src/developer/providers/implementers-guide/generate_crds.md
- docs/book/src/developer/providers/implementers-guide/naming.md
- docs/book/src/developer/providers/implementers-guide/overview.md
- docs/book/src/developer/providers/v1.0-to-v1.1.md
- docs/book/src/developer/testing.md
- docs/book/src/developer/tilt.md
Remove the remaining links to the web version of the book from the book text. This ensure that older versions of the book should continue to work by linking to their own versions of pages even when those pages are removed from the book in later versions.
Relates to  #6028
> 📖  Docs/remove self links

- test/e2e/config/docker.yaml
Update the `clusterctl` version used by upgrade e2e tests to a newer patch version. The older patch versions will cause e3e test failures. More details in the liked issue.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6056
> 🐛 update clusterctl version in e2e to latest patch

- cmd/clusterctl/hack/create-local-repository.py
- hack/tools/tilt-prepare/main.go
- metadata.yaml
- test/e2e/config/docker.yaml
- test/e2e/data/shared/v1beta1/metadata.yaml
Add v1.2 to metadata.yaml since there is already release-1.1 branch.
Fixes #6020
> 🌱 Bump versions for v1.2

- cmd/clusterctl/client/cluster/mover_test.go
Based on the Slack discussion (https://kubernetes.slack.com/archives/C8TSNPY4T/p1643414553424199) increasing the timeout has a chance to solve the flake. Let's try it.
Thx @Jont828 !
Fixes #5938
> 🐛 Fix flaky Test_objectMover

- test/infrastructure/docker/internal/controllers/dockercluster_controller.go
- util/util.go
- util/util_test.go
The map func needs to check if the infrastructure is managed externally
and if so avoid creating a reconcile.Request.
There is already code for this in capa, but it is needed for all
providers:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/cf6fea721385d490b570b4cf119defea705b3320/controllers/awscluster_controller.go#L331-L377
Fixes #
/assign @CecileRobertMichon
> :bug: ClusterToInfrastructureMapFunc: Exclude externally managed infrastructures

- CONTRIBUTING.md
According to our contributor's guide, 1.0 branch is now EOL.
I will raise the point to the next office hours as well.
/cc @vincepri @CecileRobertMichon @enxebre
> 🌱 add EOS Notice for the v1.0 branch

- docs/book/src/tasks/experimental-features/cluster-class/index.md
Add a note to the quick start guide for those linking to it from the ClusterClass index page, pointing more clearly to the ClusterClass creation commands.
Addresses #5953
> 📖  Add note on where to find ClusterClass specific Cluster creation commands

- docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
Add the following sections to the Operating a Managed Cluster page of the book:
* Scale a MachineDeployment
* Scale a ControlPlane
* Add a MachineDeployment
* Rebase a Cluster to a different ClusterClass
* Use variables in a Cluster
Addresses #5953
> 📖  Extend Operating a Managed Cluster doc

- api/v1beta1/cluster_types.go
- test/infrastructure/docker/internal/docker/types/node.go
**What this PR does / why we need it**: This is a continuation to implement fmt.Stringer interface with value receiver in the required methods as noted in the below mentioned issue
Fixes #5755
> 🌱 modify and implement fmt.Stringer with value receiver 

- hack/observability/kustomization.yaml
Current kustomize version does not use releaseNamespace (maybe anymore). Because of that our observability tools are deployed into the `default` namespace, instead of `observability`.
I have a PR open in kustomize to fix that: https://github.com/kubernetes-sigs/kustomize/pull/4460.
But there is also a new format to configure helm charts in kustomize, which is `helmCharts` instead of `helmChartInflationGenerator`. `helmCharts` uses release namespace correctly. 
Fixes #
> 🐛 tilt: deploy observability tools in correct namespace

- test/e2e/cluster_upgrade.go
- test/e2e/common.go
- test/framework/controlplane_helpers.go
- test/framework/machinedeployment_helpers.go
This PR introduces an option to change the infra template in the test spec during the cluster upgrade tests. 
Please refer to [this](https://kubernetes.slack.com/archives/C8TSNPY4T/p1643061146168200) slack conversation for more context
cc: @sbueringer @srm09
> ✨ allow provider specific infra machine template for upgrade tests

- Tiltfile
This PR forces a rebuild of the tilt-prepare binary when running `tilt up` in order to incorporate code changes. Recent example: The cert-manager repo moved to another location but this change did not reflect in tilt-prepare when it was already built beforehand.
Fixes #6077
Signed-off-by: Johannes Frey <johannes.frey@daimler.com>
<sub>Johannes Frey <[johannes.frey@daimler.com](mailto:johannes.frey@daimler.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>
> :sparkles: Force rebuild of tilt-prepare

- CONTRIBUTING.md
In the CONTRIBUTING file, there is a section on the *Contributors
Ladder* that lists the sub areas with the cluster-api project. These
link out to the source for each area.
When viewing the `CONTRIBUTING.md` file via GitHub, these links work great
because they are relative to that file. But this file also gets pulled
in to the published [Cluster-API book](https://cluster-api.sigs.k8s.io/contributing#contributors-ladder). When viewed from this
location, these links will try to go to relative paths within the book,
which do not exist.
To address this, this changes the link targets to the full GitHub URL to
the source code so that it works as expected in both the GitHub and book
rendering of the content.
> 📖 Use full URL for contrib source paths

- docs/book/src/developer/providers/v1.1-to-v1.2.md
- test/infrastructure/docker/internal/controllers/dockercluster_controller.go
- util/util.go
- util/util_test.go
This makes the ClusterToInfrastructureMapFunc handler check if the
cluster is externally managed by adding what was in
ClusterToInfrastructureMapFuncWithExternallyManagedCheck to it.
Users of ClusterToInfrastructureMapFuncWithExternallyManagedCheck need
to switch to ClusterToInfrastructureMapFunc.
Addresses https://github.com/kubernetes-sigs/cluster-api/pull/6039#issuecomment-1029258405
Fixes #
> :warning: Make ClusterToInfrastructureMapFunc check if the cluster is externally managed

- controlplane/kubeadm/internal/filters.go
- controlplane/kubeadm/internal/filters_test.go
In v1.1.0 after upgrade a KCP rollout is triggered. The problem is that the format is defaulted to `cloud-config` and KCP rolls out the machines because a change is detected.
**Notes**
* This PR is targeted at release-1.1 to fix the issue in the easiest possible way. We will follow-up with another PR against main to move the defaulting into webhooks/ a Default func which can then be used across the codebase (instead of creating the implicit dependency between KubeadmConfig defaulting and KCP rollout behaviour)
* This is not an issue with MachineDeployments as changes like this in KubeadmConfig and KubeadmConfigTemplate do not trigger rollouts.
**Which issue(s) this PR fixes** *(optional, in `fixes …
> 🐛 KCP: don't rollout machines when format is defaulted

- controllers/external/util.go
The Get function only uses methods defined in client.Reader.
The Delete function only uses methods defined in client.Writer.
Therefore they can accept client.Reader and client.Writer, instead
of client.Client, which combines both client.Reader and client.Writer.
This change allows callers that can only pass in a client.Reader
or client.Writer.
Fixes #
> :seedling: [controllers/external] Accept narrower interfaces

- docs/book/src/SUMMARY.md
- docs/book/src/reference/api_reference.md
I don't have strong opinions on how exactly we link the API references, but I think we should do it.
Just adding links to specialized websites seems to be a low-maintenance way to provide this kind of information to our users (which might not know pages like doc.crds.dev). Also we can profit from improvements in those pages or swap them out easily if we find better ones.
*Notes*:
* It's non-trivial/maybe impossible to add an external link to the mdbook sidebar, but I think it's good to have a separate book page anyway, given that we have multiple APIs and there will be more with RuntimeExtensions.
* An alternative would be to integrate the API references in the currently almost empty `reference.md`. I don't have a strong opinion about that.
* For …
> 📖 book: Add API reference page

- docs/book/src/developer/tilt.md
Updated:
* to make clear that kustomize and envsubst have to be provided via the make targets
* to add helm
Fixes #
> 📖 book/tilt: update prerequisites

- docs/book/src/user/troubleshooting.md
Adds information to point users to a Docker Desktop upgrade when they encounter the 'too many files' issue on Docker Desktop for Mac / CAPD.
Fixes #5940
> 📖  Add new fix for Docker inotify troubleshooting

- util/util.go
Removes some debugging output I accidentally left before.
Fixes #
/cc @sbueringer
> :seedling: [release-1.1] ClusterToInfrastructureMapFuncWithExternallyManagedCheck: Remove debugging leftovers

- docs/book/src/user/quick-start.md
You need to export `IMAGE_ID` in order for the `clusterctl generate cluster ...` command to work on GCP.
> :book: Update Quickstart for GCP Image

- cmd/clusterctl/client/config/cert_manager.go
- docs/book/src/clusterctl/configuration.md
- docs/book/src/developer/guide.md
- docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
cert-manager was migrated from the `jetstack` github organisation to a new `cert-manager` github organisation. While we already fixed the bug that this caused in #6050, the documentation was not updated.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: -
> 📖 Update cert-manager links after migration

- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- internal/controllers/machineset/machineset_controller.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
> :seedling: Fix typo in word enqueue

- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
The provided examples for docker don't contain `joinConfigurations` that explicitly set the cgroup-driver to cgroupfs. This isn't a problem as long as the user uses them verbatim (replica count of 1 for the `KubdeadmControlPlane`) . But if a user uses the provided examples as basis for a HA control plane (increasing the replica count to 3) it's easy to miss the fact that there should also be a `joinConfiguration` specified. If not, the other control plane nodes won't come up because then kubelet will default to the `systemd` driver, which currently does not work with kind and Kubernetes images greater than 1.20.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …
> :sparkles: Add joinConfiguration to docker examples

- docs/book/src/clusterctl/commands/init.md
- docs/book/src/clusterctl/configuration.md
- docs/book/src/user/troubleshooting.md
This PR improves documentation about clusterctl version pinning as a follow up of discussion in https://kubernetes.slack.com/archives/C8TSNPY4T/p1644508037638019
> 📖 Improve documentation for clusterctl pinning version

- api/v1alpha4/conversion.go
- bootstrap/kubeadm/api/v1alpha3/conversion.go
- bootstrap/kubeadm/api/v1alpha4/conversion.go
- controlplane/kubeadm/api/v1alpha3/conversion.go
- controlplane/kubeadm/api/v1alpha4/conversion.go
Went through all conversions, that should fix all panics.
I can only guess, but I think our fuzzer didn't hit the case described in the issue where only patches was set because there are so many other fields in that sub-structure. 
Fixes #6142
> 🐛 Fix panics in conversions

- Tiltfile
The tilt Grafana port currently clashes with `make serve-book` so we can't run both at the same time. This change moves the Grafana port to 3001.
> 🌱  Update grafana port forward to prevent clash with 'make serve-book'

- docs/book/src/user/quick-start.md
The old `1.0.x` wasn't matching the new version. Instead of making the
change now for each new minor release this will match all minor and
patch releases.
Related issue: #6136
> 📖 Updated version pattern matching in quick-start

- .gitignore
- Tiltfile
- docs/book/src/developer/tilt.md
During development it can be necessary to switch between different providers. JSON doesn't support comments, so disabling a provider requires to remove it from the file entirely. This is a bit inconvenient.
This PR allows to use yaml for configuration, which supports comments and allows to easily disable providers by commenting it out. It's also just more pleasant to read and write.
It will prefer `./tilt-settings.yaml` over `./tilt-settings.json`. Both files are loaded with `read_yaml` since valid json is also valid yaml. This also allows to use yaml comments (`#`) in the json file.
It also allows to use `./tilt-provider.yaml` in provder repos, it'll prefer yaml here as well.
Finally I've switched the docs to yaml instead of json.
example:
```json …
```
> 🌱 tilt: switch to yaml for configuration

- docs/book/src/reference/versions.md
Improving version support matrix to better surface the practices we are following.
TL;DR; we try to go over and behind Kubernetes support matrix to meet the users where they are, but at the same time there should be boundaries to what we can reasonably support/validate with our CI signal. 
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4444
/cc @CecileRobertMichon @vincepri @enxebre @sbueringer
> 📖 Improve version support documentation

- bootstrap/kubeadm/main.go
- controlplane/kubeadm/main.go
- go.mod
- main.go
- test/go.mod
- test/go.sum
- test/infrastructure/docker/main.go
This PR starts using components-base/logs. Through that we get the following changes:
* some klog flags are deprecated (like in core Kubernetes components: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#removed-klog-flags)
* k/k is planning to drop them in their components in 1.26
* *Note*: those flags are not deprecated in klog, only in Kubernetes through component-base/logs (more details in the KEP)
* there are new flags to enable JSON logging, e.g. `--logging-format` (default: text, can also be set to JSON)
*  JSON logging is currently alpha: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format
* Additional JSON flags can be …
> ✨ Add JSON log format and deprecate klog flags

- Tiltfile
- docs/book/src/developer/tilt.md
- hack/observability/grafana/values.yaml
- hack/observability/prometheus/kustomization.yaml
- hack/observability/prometheus/values.yaml
- hack/observability/promtail/values.yaml
- hack/tools/tilt-prepare/main.go
This PR adds Prometheus to the observability suite of applications installed by Tilt. It also configures prometheus to scrape the cluster-api providers, based on the `cluster.x-k8s.io/provider` label.
Fixes #5572
> ✨ Tilt: Add prometheus to observability deployment

- docs/book/src/developer/tilt.md
Fixes a typo in the example `tilt-settings.yaml` that caused the `enable_providers` setting to be ignored by tilt.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: /
> 🌱 book: fix typo in tilt-settings.yaml example

- .github/workflows/lint-docs.yaml
This updates the markdown lint checker config to only produce errors.
Fixes #
> :seedling:  Use quiet mode on markdown link checker

- docs/book/src/developer/providers/v1.1-to-v1.2.md
- util/collections/machine_collection.go
- util/util.go
- Copy `util.MachinesByCreationTimestamp` to `util/collections` and make it private over there. 
- Deprecate `util.MachinesByCreationTimestamp` to remove it in a future release.
- Update release notes.
Fixes #5091
> 🌱 Make MachinesByCreationTimestamp private to machine collections

- internal/controllers/clusterclass/clusterclass_controller_test.go
- internal/controllers/clusterclass/suite_test.go
- internal/controllers/topology/cluster/suite_test.go
- internal/webhooks/clusterclass.go
- internal/webhooks/clusterclass_test.go
- internal/webhooks/test/clusterclass_test.go
- internal/webhooks/test/suite_test.go
Add the ClusterClass name index to the client call for getting a ClusterClass in the ClusterClass webhook. 
Certain tests are moved to a new subpackage in order to run them with envtest. This is required as the fakeclient doesn't set up the indexes now in use by the ClusterClass webhook.
Note this PR includes duplicate files from #5803 and should not be merged until that PR is completed.
Fixes #5719
> 🌱 Use ClusterClass name index in ClusterClass webhook

- docs/book/src/reference/jobs.md
Signed-off-by: Rayan Das <rayandas91@gmail.com>
This PR removes `periodic-cluster-api-verify-book-links-main` job from `jobs.md` as it's getting removed from test-infra https://github.com/kubernetes/test-infra/pull/25359
Fixes part 2 of https://github.com/kubernetes-sigs/cluster-api/issues/6141
> 🌱 Remove periodic-cluster-api-verify-book-links-main job from jobs.md

- Makefile
- scripts/ci-apidiff.sh
This PR deduplicates the apidiff "logic". We should use our makefile targets in CI when easily possible.
Fixes #
> 🌱 apidiff: deduplicate apidiff logic

- bootstrap/kubeadm/api/v1alpha3/conversion.go
- bootstrap/kubeadm/api/v1alpha4/conversion.go
- bootstrap/kubeadm/api/v1alpha4/zz_generated.conversion.go
- bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
- bootstrap/kubeadm/api/v1beta1/zz_generated.deepcopy.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- bootstrap/kubeadm/types/upstreamv1beta1/conversion_test.go
- bootstrap/kubeadm/types/upstreamv1beta1/zz_generated.conversion.go
- bootstrap/kubeadm/types/upstreamv1beta2/conversion_test.go
- bootstrap/kubeadm/types/upstreamv1beta2/zz_generated.conversion.go
- bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.conversion.go
- controlplane/kubeadm/api/v1alpha3/conversion.go
- controlplane/kubeadm/api/v1alpha4/conversion.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
In this PR, we enable users to exclude specific phases of their
choice during init/join command execution. This can be helpful in
cases like provisioning a cluster without kube-proxy deployed.
Note: This option takes effect only only on Kubernetes >=1.22.0.
Fixes [#5357](https://github.com/kubernetes-sigs/cluster-api/issues/5357)
> ✨ CABPK: Add support for kubeadm skipPhases field

- test/framework/controlplane_helpers.go
Current output during the node drain test includes:
```
INFO: Scaling controlplane node-drain-luvzog/node-drain-1oqo30-control-plane from 0xc00132465c to 1 replicas
```
This PR fixes the log output to properly show the correct number of replicas before the scaling operation and not display a pointer address
> 🐛 [e2e framework] fix node drain output

- hack/observability/grafana/values.yaml
From time to time tilt starts to consistently reload everything. This was triggered by a random admin password in the Grafana Helm chart. This PR sets the Grafana pw so it's not random
Fixes #
> 🐛 tilt: fix infinite reload issue

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
- internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
- internal/webhooks/patch_validation.go
- test/go.mod
- test/go.sum
This PR adds sprig functions to ClusterClass templates
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6091
> 🌱 Add sprig functions to ClusterClass templates

- internal/controllers/machine/machine_controller.go
Apart from main functions and test code we should never use the global klog logger. 
By using the one from the context we can make sure that the log lines have the right k/v pairs.
Fixes #
> 🌱 log to logger from context during drain

- .golangci.yml
This PR drops the `gocyclo` from the linter list. 
Ref for more details: https://github.com/kubernetes-sigs/cluster-api/pull/6183#discussion_r812134821
Fixes #
> 🌱 drop gocyclo from linter

- docs/book/src/introduction.md
As discussed in https://github.com/kubernetes-sigs/cluster-api/issues/6017#issuecomment-1048492551 we now have  books of all versions available. This PR updates the references to those books accordingly 
Ref:
* main.cluster-api.sigs.k8s.io => main
* cluster-api.sigs.k8s.io => release-1-1
* release-1-1.cluster-api.sigs.k8s.io => release-1-1
* release-1-0.cluster-api.sigs.k8s.io => release-1-0
* release-0-4.cluster-api.sigs.k8s.io => release-0-4
* release-0-3.cluster-api.sigs.k8s.io => release-0.3
This PR only changes the book on main and is not meant to be backported as is to older branches. But I would also open PRs for release-1.1 and release-1.0 to update the books similarly.
P.S. I add a …
> 📖 book: update refs to older books

- internal/controllers/machine/machine_controller.go
e2e tests are currently broken on main. This PR should fix it.
Found this panic in our test logs: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1496705192203128832/artifacts/clusters/bootstrap/controllers/capi-controller-manager/capi-controller-manager-5ddddd567d-fmdpj/manager.log
Fixes #
> 🐛 Fix panic in node drain

- bootstrap/kubeadm/main.go
- controlplane/kubeadm/main.go
- main.go
- test/infrastructure/docker/main.go
Please see the discussion on the klog issue: https://github.com/kubernetes/klog/issues/302#issuecomment-1048500462
My summary: We shouldn't use the "old" serialize klog format because:
* it doesn't render k/v correctly
* we can use the klog klog format for JSON/text which makes it more consistent
Fixes #
> 🌱 logging: set correct klog format

- docs/book/src/developer/providers/v1.1-to-v1.2.md
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/6072
Fixes #
> 📖 book: document component-base/logs change in migration doc

- Makefile
- docs/book/Makefile
- scripts/ci-build.sh
This PR refactors our book verification/build as described in #6141.
The `verify-book-links` target never really verified book links in the sense of checking for broken links.
After this PR we have `make book-build` target which is run on PRs as part of the build job.
Implements part of #6141
> 🌱 book: refactor verification

- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_rbac.go
- controlplane/kubeadm/internal/workload_cluster_rbac_test.go
- controlplane/kubeadm/internal/workload_cluster_test.go
This PR makes KCP handle the kubelet ConfigMap as expected by kubeadm >= 1.24
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5921
> 🌱 handle kubeadm 1.24 kubelet ConfigMap name change

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>
This PR fixes the dependabot alert - "OCI Manifest Type Confusion Issue" by upgrading the version of the module `github.com/docker/distribution` to `2.8.0`
> 🐛 Update docker distribution dependency version

- Tiltfile
- docs/book/src/developer/tilt.md
`preload_images_for_kind` and `kind_cluster_name` are not used anymore (probably since a while).
Right now we're always preloading cert-manager images based on `CAPI_KIND_CLUSTER_NAME`.
I think if there is demand to run tilt with a non-kind cluster we can reconsider our current handling 
and maybe just auto-discover if the current cluster is a kind cluster and act accordingly.
The last few months since we had this hard dependency to kind nobody complained.
Fixes #
> 🌱 tilt: remove unused options

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/proposals/202105256-cluster-class-and-managed-topologies.md
- internal/controllers/topology/cluster/patches/engine.go
- internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
- internal/controllers/topology/cluster/patches/variables/variables.go
- internal/controllers/topology/cluster/patches/variables/variables_test.go
- internal/webhooks/patch_validation.go
While writing ClusterClasses for CAPZ, we discovered that additional builtin variables are needed.
CAPZ has a controller which generates secrets which are eventually used for Machines. These secrets then have to be configured in KCP.spec..kubeadmConfigSpec and in KubeadmConfigTemplates.
The secrets are generated with the names of the corresponding current AzureMachineTemplates. So essentially CAPZ has to be able to take the name of the currently referenced AzureMachineTemplate of KCP/MD and then patch KCP / the KubeadmConfigTemplate accordingly.
To make this possible we introduce builtin variables for all references in KCP / MD.
We additionally add `builtin.controlPlane.name` because it seems to …
> 🌱 ClusterClass: add ref and controlPlane name builtin variables

- test/e2e/e2e_suite_test.go
Just to make it a bit clearer in the logs if a new or an existing cluster is used.
Fixes #
> 🌱 test/e2e: log if a new cluster is created or an existing is used

- README.md
This PR drops the Prow build badge from our top-level README.
I think we should drop it because:
* I think the postsubmit image push job is not a good proxy to show the overall build/CI status of CAPI. We have literally dozens of jobs today which can be seen in testgrid: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api
* The badge is "grey" if the job didn't run in the last 24h (which means it's just grey from Saturday to Monday). Not sure which message that sends to our users :)
* If the job actually fails, it has usually nothing to do with the "health" of our CI/CD jobs. In all cases that I saw it was an issue with [GCR](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-ap …
> 📖 doc: drop Prow build badge

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/proposals/202105256-cluster-class-and-managed-topologies.md
- internal/controllers/topology/cluster/patches/engine_test.go
- internal/controllers/topology/cluster/patches/variables/variables.go
- internal/controllers/topology/cluster/patches/variables/variables_test.go
- internal/webhooks/patch_validation.go
This PR adds a new set of builtin variables from the Cluster's `.spec.clusterNetwork` field. 
Fixes #5578
> :seedling: Add network builtins to topology controller

- test/framework/clusterctl/repository.go
Signed-off-by: DiptoChakrabarty <diptochuck123@gmail.com>
Makes use of an KUSTOMIZE_PATH env variable to use in package clusterctl in test. If env variable is not present it takes default value. This helps in overriding kustomize path in call to ```clusterctl.CreateRepository```
Fixes #6173
> 🌱   use env value to set kustomize path in test

- docs/book/src/developer/testing.md
- docs/book/src/developer/tilt.md
I had an issue running e2e tests locally using tilt because I didn't enable all feature flags. A [discussion on Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1646140199311849) clarified this. This documentation change should ensure future contributors don't stumble upon the same issue.
> :book: document setting feature flags for tilt dev env

- docs/book/src/clusterctl/configuration.md
Duplicated ```yaml at cert-manager-configuration
Fix yaml code section in docs
None
> 📖 Docs fix, duplicated ```yaml

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Cleans up the existing example on `.builtin` variables to use `semverCompare` which was introduced in #6131
I am currently implementing ClusterClass for our internal usage and had a usecase where I wanted to activate a specific feature flag for Kubernetes 1.22+ (as it was introduced then). This specific usecase was missing from the docs, and I stumbled upon some issues when I tried to patch both the `KubeadmConfigTemplate` for my machine deployment, as well as the `KubeadmControlPlane` in one patch with one `enabledIf` based on the example provided here, because `.builtin.controlPlane.version` was only defined for half of the definitions.
By using `semverCompare` to enable only on 1.22+ and `coalesce` to select the appropriate kubernetes version …
> 📖 Use semverCompare to enable patches based on k8s version

- Makefile
When I run `make test` on my M1 Mac, I get:
```shell
% make test
unable to fetch checksum for requested version: unable fetch metadata for kubebuilder-tools-1.23.3-darwin-arm64.tar.gz -- got status "404 Not Found" from GCS
KUBEBUILDER_ASSETS="" go test ./...
<numerous test failures of course>
```
Overriding with the equivalent of `GOARCH=amd64` works fine.
N/A
> 🐛 Work around lack of kubebuilder-tools for darwin/arm64

- test/e2e/cluster_upgrade.go
- test/e2e/common.go
- add option to configure both control-plane and workers machine template for k8s upgrade tests
/assign @fabriziopandini @sbueringer 
Follow up of https://github.com/kubernetes-sigs/cluster-api/pull/6075#issuecomment-1038854798
> 🌱 e2e: add option to configure both control-plane and workers machine template for k8s upgrade tests

- Tiltfile
- hack/tools/go.mod
- hack/tools/tilt-prepare/main.go
Move the calculation of command and args of the manager deployment image to tilt-prepare and clean up the Tiltfile accordingly. This solves the issue that some extra_args given by the user won't be respected in the current solution. See: https://github.com/kubernetes-sigs/cluster-api/issues/6202
Fixes #6202
Signed-off-by: Johannes Frey <johannes.frey@daimler.com>
<sub>Johannes Frey <[johannes.frey@daimler.com](mailto:johannes.frey@daimler.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>
> :seedling: Move command and arg handling of manager.yaml to tilt-prepare

- docs/book/src/developer/providers/v1.1-to-v1.2.md
- test/e2e/cluster_upgrade.go
- test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
- test/e2e/data/infrastructure-docker/v1beta1/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1beta1/bases/mp.yaml
- test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
- test/framework/controlplane_helpers.go
- test/framework/machinedeployment_helpers.go
- test/framework/machinepool_helpers.go
- test/infrastructure/docker/api/v1beta1/dockercluster_types.go
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/exp/internal/docker/nodepool.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
- test/infrastructure/docker/internal/docker/kind_manager.go
- test/infrastructure/docker/internal/docker/machine.go
- test/infrastructure/docker/internal/docker/util.go
This PR adds support for failure domains to CAPD and improves the E2E test framework to check all the machines are placed in a valid failure domain.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2895
> ✨ CAPD and E2E framework tests failure domains

- cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
- cmd/clusterctl/client/cluster/topology.go
Adds support for `Namespace` objects in `clusterctl alpha topology plan` input. Previously it would have counted as another unique namespace, but now we just add the `metadata.name` of the `Namespace` into the set of unique namespaces.
Fixes #6236
> ✨ clusterctl: allow Namespace objects in topology plan input

- Tiltfile
- docs/book/src/developer/tilt.md
Currently in order to override the default kind cluster name used by tilt, you must override the CAPI_KIND_CLUSTER_NAME env variable, this PR re-introduces the `kind_cluster_name` setting to the tilt settings and makes it so that the kind cluster name can be configured either through the env variable or through the settings.
> 🐛 [Tilt] Support using kind cluster from tilt settings automatically

- cmd/clusterctl/cmd/generate_provider.go
- cmd/clusterctl/cmd/init.go
- cmd/clusterctl/cmd/rollout/pause.go
- cmd/clusterctl/cmd/rollout/restart.go
- cmd/clusterctl/cmd/rollout/resume.go
- cmd/clusterctl/cmd/rollout/undo.go
Consistently use `-n` as the shorthand for `--[target-]namespace`. The shorthand is a default in the kubernetes ecosystem, and many of the clusterctl cmds were already using it.
> 🌱 clusterctl: always use -n as the shorthand for --[target-]namespace

- docs/proposals/20200330-spot-instances.md
“to reduce costs **were** possible” seems to be syntactically incorrect; this pull request replaces `were` with `were`
> 🌱  Fix typo on proposals/20200330-spot-instances

- cmd/clusterctl/client/cluster/proxy.go
This PR makes the `listObjByGVK` function resilient to temporary network problems. This function is used during the upgrade flow and the upgrade can potentially break because of this.
Fixes #6261
> 🐛 make `listObjByGVK` resilient

- cmd/clusterctl/client/cluster/components.go
This PR makes the clusterctl upgrade operation more resilient to temporary network problems. During upgrade delete operations are performed and temporary network failure can cause this operation to fail in turn leading to failure of the upgrade operation.
This PR wraps that delete operation in a retry block.
Fixes #
> 🐛 retry delete during clusterctl upgrade

- test/e2e/clusterctl_upgrade.go
Check for unexpected rollouts in the clusterctl upgrade e2e test.
TODO:
Fixes #
> 🌱 [e2e] Checks unexpected rollouts during clusterctl upgrade

- exp/internal/controllers/machinepool_controller_noderef.go
- exp/internal/controllers/machinepool_controller_phases.go
- exp/internal/controllers/machinepool_controller_phases_test.go
- test/e2e/machine_pool.go
- test/framework/machinepool_helpers.go
to enable scaling a MachinePool to zero, an empty or not set
providerIDList should be considered valid.
additionally, Replicas 0 of the infrastructure MachinePool should also
be considered valid.
Fixes #6210
This issue is required for kubernetes-sigs/cluster-api-provider-aws#3242 to be fixable.
> :bug: permit empty/not set providerIDList

- .gitignore
- CONTRIBUTING.md
- docs/book/src/developer/architecture/controllers/cluster-topology.md
- docs/book/src/developer/providers/implementers-guide/configure.md
- docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
- docs/book/src/tasks/experimental-features/cluster-class/index.md
Just syncing the dates from main to release-1.1
Fixes #
> 📖 book: add support dates

- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
- bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_webhook.go
While investigating #6113 I found out that our KCP validation has a few issues:
* field paths in KubeadmConfigSpec.Validate weren't correct in all cases (prefix)
* semantic version validation of CoreDNS image tag was only done on update, not on create
* errors in semantic version parsing weren't propagated in some cases
* KubeadmConfigSpec was not validated on KubeadmControlPlaneTemplate create
Overall I think that should make especially ClusterClass/KubeadmControlPlaneTemplate safer to use as the errors are already returned on creation of KubeadmControlPlaneTemplate. Not during topology reconcile when KubeadmControlPlane cannot be created.
**Which issue(s) this PR fixes** *(optional, in `fixes …
> 🌱 KCP: improve validation webhooks

- api/v1beta1/machinedeployment_types.go
- api/v1beta1/machineset_types.go
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- exp/api/v1beta1/machinepool_types.go
I want to look the desired replicas number of KCP's machines when `kubectl get kcp`.
So I added print column desired replicas of `KubeadmControlPlane`.
Fixes #6165
> 🌱 Add desired number column to KCP, MD, MS, MachinePool

- api/v1beta1/machineset_types.go
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- exp/api/v1beta1/machinepool_types.go
It's fine for me if we want to hide the new desired column, but I think we should use the same order for replica columns across CRDs.
I think it's otherwise confusing if you run `k get md,ms,kcp -o wide` and you have to look per-CRD if the first/second replica column are desired/replicas or the other way around.
(I would like to avoid spending time after the next release to discuss how we can change column order and if it's a breaking change or not)
Fixes #
> 🌱 order replica columns in a consistent order

- docs/book/src/user/quick-start.md
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6161
> 📖 Docs: Installing clusterctl on windows section added

- internal/controllers/topology/cluster/cluster_controller.go
We currently only set the kind and not the apiVersion. We're then updating the cluster resource during reconcile to add kind and apiVersion at some point.
Then we end up with a diff in the apiVersion between before/after in the patchHelper. This is not really a problem yet as we don't try to patch apiVersion of a resource (which is impossible anyway). But if we start logging if there are changes in the patch helper we would always get a diff.
I think it's only consequential to set both apiVersion and kind and not only kind, but we can also talk about an additional more holistic change in the patchHelper, e.g. to ignore kind and apiVersion entirely.
**Which issue(s) this PR fixes** *(optional, in …
> 🐛 topology: set apiVersion to avoid diff in patchHelper

- internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
> 🐛 MHC: use .spec.clusterName instead of .metadata.clusterName for external remediation request
