kubernetes-sigs/cluster-api

- docs/book/src/clusterctl/developers.md
- docs/book/src/user/quick-start.md
Just went through the quickstart documentation and I have some suggestions to improve them a bit. See my comments below.
Fixes #
> 📖 improve quickstart documentation

- docs/book/src/user/quick-start.md
- add instructions to create secret for identity password
- remove AzureEnvironment field as its now moved to AzureCluster and defaulted
Fixes #
/cc @CecileRobertMichon
> 📖  Add capz identity instructions to quick start

- CONTRIBUTING.md
- docs/book/src/SUMMARY.md
- docs/book/src/reference/jobs.md
> 📖 Document test matrix in the book

- docs/proposals/20200220-cluster-resource-set.md
There is an incorrect indent in proposals.
Fixes #
> 📖 Fix incorrect indents

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/internal/workload_cluster_coredns.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
- test/infrastructure/container/docker.go
- test/infrastructure/container/interface.go
See issue for details
Fixes #4927
> 🐛  update CoreDNS ClusterRole for Kubernetes >= 1.22 and CoreDNS >= 1.8.1

- controlplane/kubeadm/controllers/controller.go
- controlplane/kubeadm/controllers/controller_test.go
- controlplane/kubeadm/internal/workload_cluster.go
- controlplane/kubeadm/internal/workload_cluster_coredns.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
- util/version/version.go
- util/version/version_test.go
> 🐛   cherry-pick: update CoreDNS ClusterRole (Kubernetes>=1.22,CoreDNS >= 1.8.1)

- test/e2e/data/infrastructure-docker/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/bases/md.yaml
- test/e2e/data/infrastructure-docker/bases/mp.yaml
- test/e2e/data/infrastructure-docker/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
- test/infrastructure/docker/templates/cluster-template-development.yaml
For more details see:
* the explanation in the issue #5003
* the original PR: #4614 
Fixes #5003
> 🐛  cherry pick  pin cgroupDriver to cgroupfs in CAPD

- docs/book/Makefile
Maintenance upgrade for our book generator.
Fixes #
> 🌱 Upgrade mdbook to v0.4.11

- exp/addons/controllers/clusterresourceset_controller_test.go
- exp/addons/controllers/clusterresourceset_helpers_test.go
- exp/controllers/machinepool_controller_phases_test.go
- exp/controllers/machinepool_controller_test.go
Partly solves #4629.
Updates namespace generation in exp pkg tests.
> 🌱 Randomly generated namespace in exp pkg tests

- controllers/clustertopology_controller_compute.go
- controllers/clustertopology_controller_compute_test.go
- controllers/suite_test.go
See referenced issue.
Fixes #4970
Note:
* ~~This PR contains cherry-picks from #4986 and #5000. So they have to be merged first~~ > rebased
> 🌱 cluster topology controller: read clusterclass

- api/v1alpha4/common_types.go
- api/v1alpha4/index/index.go
- api/v1alpha4/index/machine.go
- api/v1alpha4/index/machine_test.go
- api/v1alpha4/index/node.go
- api/v1alpha4/index/node_test.go
- controllers/machine_controller.go
- controllers/machine_controller_noderef.go
- controllers/machine_controller_noderef_test.go
- controllers/machinehealthcheck_controller.go
- controllers/noderefutil/indexer.go
- controllers/noderefutil/machine.go
- controllers/remote/cluster_cache.go
- controllers/remote/cluster_cache_healthcheck_test.go
- controllers/remote/cluster_cache_tracker_test.go
- controllers/remote/index.go
- controllers/suite_test.go
- controlplane/kubeadm/internal/cluster_test.go
- controlplane/kubeadm/main.go
- exp/addons/controllers/suite_test.go
- exp/controllers/suite_test.go
- main.go
Add a new `api/v1alpha4/index` package and move all index related functions to this new package.
For more details ref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1626975994414800
Fixes #
> ✨ add api/v1alpha4/index package

- controllers/remote/cluster_cache_healthcheck_test.go
> 🐛 Increase polling interval and timeout in ClusterCacheHealthCheck

- docs/book/src/reference/providers.md
Add MAAS to infra provider list. 
This is a baremetal provider build on top of Canonical MAAS. 
Fixes #
>  📖 add maas to infra provider list

- docs/book/src/user/quick-start.md
The term "latest release" does not seem relevant anymore and is redundant as the latest release now is v0.4.1.
Fixes #
> :book:  Remove "latest release"

- docs/book/src/reference/jobs.md
Fixes #5078 (last step of #5078)
> 📖 Update job overview in CAPI book

- api/v1alpha4/clusterclass_webhook.go
- api/v1alpha4/clusterclass_webhook_test.go
> 🌱 Add namespace defaulting for ClusterClass ControlPlane MachineInfrastructure

- controllers/topology/mergepatch.go
- controllers/topology/mergepatch_test.go
This PR makes the MergePatchHelper skip metadata fields computed by the system and status, thus avoiding to reconcile changes for differences that are not derived from the computed topology
> 🌱 Make the MergePatchHelper skip metadata fields computed by the system and status

- docs/book/src/developer/testing.md
> 📖 Added documentation for setting up vs code debugger

- docs/book/src/developer/testing.md
Remove deprecated `test/helpers` instructions and replace with new steps using `internal/envtest`.
Fixes #
> 📖 Update testing docs

- docs/book/src/clusterctl/commands/generate-cluster.md
> 📖  Fix typo in `clusterctl generate cluster` book docs 

- controllers/topology/reconcile_state.go
> 🌱 Fix mistaken comment

- Makefile
- Tiltfile
- test/infrastructure/docker/Makefile
Fixes #
/assign @fabriziopandini @CecileRobertMichon
> :seedling: Update Go to 1.16.8

- bootstrap/kubeadm/types/upstreamv1beta1/conversion.go
- util/conversion/conversion.go
Remove a couple of duplicate import statements found by using staticcheck.
> 🐛 Remove duplicated import statements

- CONTRIBUTING.md
- REVIEWING.md
- VERSIONING.md
- docs/book/src/clusterctl/commands/config-cluster.md
- docs/book/src/clusterctl/commands/generate-cluster.md
- docs/book/src/clusterctl/commands/generate-yaml.md
- docs/book/src/developer/architecture/controllers/bootstrap.md
- docs/book/src/developer/e2e.md
- docs/book/src/developer/guide.md
- docs/book/src/developer/testing.md
- docs/book/src/developer/tilt.md
- docs/book/src/introduction.md
- docs/book/src/reference/glossary.md
- docs/book/src/reference/providers.md
- docs/book/src/tasks/experimental-features/cluster-resource-set.md
- docs/book/src/tasks/experimental-features/machine-pools.md
- docs/book/src/tasks/healthcheck.md
- docs/book/src/tasks/kubeadm-bootstrap.md
- docs/book/src/tasks/kubeadm-control-plane.md
- docs/book/src/user/troubleshooting.md
- docs/proposals/20190919-machinepool-api.md
- docs/proposals/20191017-kubeadm-based-control-plane.md
- docs/proposals/20201020-capi-provider-operator.md
- test/infrastructure/docker/README.md
**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api/issues/3280
/hold
this should merge after the branch rename is done.
Fixes #
> 🌱  Change all references to master branch in docs to main branch

- api/v1beta1/cluster_types.go
- api/v1beta1/machine_types.go
- api/v1beta1/machinedeployment_types.go
- api/v1beta1/machinehealthcheck_types.go
- api/v1beta1/machineset_types.go
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- exp/api/v1beta1/machinepool_types.go
> 🌱 Ensure CRD columns and their order are consistent

- docs/book/src/developer/tilt.md
The CAPI book is updated here to reference the script added in  #5232 in the CAPI book to simplify Tilt setup.
Fixes #5204
> 📖  Update book to use Kind script for Tilt setup

- docs/book/src/reference/jobs.md
This PR updates jobs documentation according to changes in flight
> 📖 Update jobs documentation

- docs/book/src/introduction.md
https://github.com/kubernetes-sigs/cluster-api/pull/5276 accidentally changed the branch of the [kubernetes/community](https://github.com/kubernetes/community)
Fixes #
> 📖 docs: fix the broken link in introduction

- netlify.toml
**What this PR does / why we need it**: #3280
Fixes #
> 🌱  Update netlify config after default branch rename

- CONTRIBUTING.md
**What this PR does / why we need it**: https://github.com/kubernetes/k8s.io/pull/2834#issuecomment-928183604
Fixes #
> 🌱  Update main branch book link

- CONTRIBUTING.md
Add required/default case to API conventions.
Fixes #5333
> 🌱Add required/default case to API conventions

- controllers/machineset_controller.go
- controllers/machineset_controller_test.go
> 🐛  Propagate MS.spec.template.annotations to bootstrap config

- controlplane/kubeadm/controllers/remediation.go
- controlplane/kubeadm/controllers/remediation_test.go
This PR allows KCP to properly cleanup OwnerRemediated condition if the machine goes back to healthy and remediation did not happened for any reason
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5169
> 🐛 KCP should cleanup OwnerRemediated condition if the machine goes back to healthy

- docs/book/src/user/quick-start.md
To avoid confusion in following the quick start document
Fixes #5522
> 📖Update section made a bit clear

- controllers/topology/internal/mergepatch/mergepatch_test.go
mergepatch is at the heart of topology reconcile, so adding some unit test for preventing regressions on private functions used for merge patch options
> 🌱 add tests for merge patch private func

- controllers/topology/internal/mergepatch/mergepatch.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- go.mod
- go.sum
- internal/matchers/matchers.go
- test/go.sum
Let's use a v5.x version instead of v4.x. There shouldn't be any major changes.
Fixes #
> 🌱 Use evanphx/json-patch v5.6.0

- controllers/topology/cluster_controller.go
moving setup watch into a separated func so we can keep the main topology reconcile as simple as possible.
> 🌱 move setup watch into separate func

- test/framework/controlplane_helpers.go
Current error message for WaitForControlPlaneToBeReady function doesn't give enough information for framework consumers when test fails.
```
Expected
<bool>: false
to be true
/root/go/pkg/mod/sigs.k8s.io/cluster-api/test@v0.4.3/framework/controlplane_helpers.go:167
```
This PR improves the error message and provides more info. See an example output with the change.
```
{
"kind": "KubeadmControlPlane",
"metadata": {
"name": "test-kcp",
"creationTimestamp": null
},
"spec": {
"version": "1.21",
"machineTemplate": {
"metadata": {},
"infrastructureRef": {}
},
"kubeadmConfigSpec": {}
},
"status": {
"replicas": 0,
"updatedReplicas": 0,
"readyReplicas": 0,
"unavailableReplicas": 0,
"initialized": false,
"ready": false,
"failureReason": "something happened!" …
```
> 🐛 Provide a better error message for WaitForControlPlaneToBeReady function

- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Clusterctl move resets all status fields including the status.Address
field. After move, docker machine controller checks if the providerID
field is set on spec, and then sets the machine.Status.Ready field to
true and does not reconcile the machine further. Due to this the address
field never gets reconciled on a dockerMachine after move. This commit
sets the machine address if the corresponding container exists.
Fixes #
> :bug: Reconcile dockermachine.status.address after move

- test/infrastructure/docker/main.go
This PR adds a `profile-address` flag to CAPD. I was just playing around with tilt and the debug settings, and CAPD wasn't coming up anymore when I tried to enable the profiler.
Fixes #
> ✨ CAPD: Add profiler-address flag

- docs/book/src/developer/testing.md
Fix a broken link in testing.md to point to the correct file section.
> 🐛  fix broken link in testing.md

- controlplane/kubeadm/controllers/scale.go
Log only the machine name instead of the complete object. Otherwise, a big log line will be printed which impairs the readability of the log itself.
Fixes #
> 🐛 Log only machine name instead of object

- test/e2e/e2e_suite_test.go
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5677
> 🌱 test/e2e: Implement clusterctl-config flag

- Tiltfile
> 🌱 tilt up: deploy provider CRDs and CRs

- cmd/clusterctl/log/logger.go
- cmd/clusterctl/log/logger_test.go
> 🐛 Fix log level

- test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
> 🌱 test/e2e: Default variable in ClusterClass quickstart test

- .github/workflows/golangci-lint.yml
- .github/workflows/verify.yml
cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/5723
Fixes #
> 🌱 Run GitHub workflows on all pull requests

- controllers/topology/cluster_controller_test.go
Adds a deletion integration test to ensure the behaviour is being properly enforced by the clusterClass webhook (and possibly the reconciler in future). 
This test was added to prevent a regression of behaviour like #5737 and tests for the behaviour outlined in #5196
> 🌱 add deletion integration test for clusterclass

- docs/book/src/user/quick-start.md
This PR makes tab order in quick start consistent (alphabetical order)
> 🌱 fix tab order in quickstart

- test/infrastructure/docker/main.go
> 🐛 capd: fix MachinePool reconciler

- api/v1alpha3/condition_consts.go
- api/v1alpha4/condition_consts.go
- api/v1beta1/condition_consts.go
- cmd/clusterctl/client/cluster/upgrader.go
- cmd/clusterctl/client/cluster/upgrader_info.go
> 🌱 Fix some typos

- docs/book/src/user/quick-start.md
This patch updates the quick start docs for CAPV.
n/a
> 📖 Updates quick start docs for CAPV

- docs/book/src/user/quick-start.md
fixing https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1099
Fixes #
> 📖 Add OPENSTACK_EXTERNAL_NETWORK_ID for openstack

- README.md
Saves two clicks when navigating from browser to notes.
N/A
> 📖 Update link to community meeting notes

- test/infrastructure/docker/internal/docker/machine.go
> 🐛 capd: fix logContainerDebugInfo

- test/e2e/clusterctl_upgrade.go
> 🌱 test/clusterctl-upgrade: also cleanup v1alpha4 clusters

- cmd/clusterctl/config/manifest/clusterctl-api.yaml
- hack/ensure-kustomize.sh
- hack/observability/.gitignore
- hack/observability/kustomization.yaml
- hack/tools/tilt-prepare/main.go
- test/e2e/Makefile
Upgrade to the latest kustomize version.
I also tested `tilt up` locally with the new kustomize version and a recompiled tilt-prepare binary.
Fixes #5570
> 🌱 Upgrade to kustomize v4.4.1

- docs/book/src/reference/providers.md
This PR adds KubeVirt to the providers list.
Fixes #5918
> 📖Added KubeVirt to the providers list

- internal/controllers/machinedeployment/machinedeployment_rolling_test.go
I was curious whether whether the following scenario was possible: 
During a rolling update, after the MachineDeployment reconciler has decremented the old MachineSet Spec.Replicas, but before the Machine has been fully destroyed, the next loop of reconciliation scales up the new MachineSet. 
If this were possible, a rolling update could temporarily consume more resources in the MachineDeployment than Replicas + MaxSurge.
A comment on `TotalMachineSetsReplicaSum` suggests this is guaranteed not to happen: 
https://github.com/kubernetes-sigs/cluster-api/blob/1e13f448ed5823e26bc98bd48d77f1037e0d443b/internal/controllers/machinedeployment/mdutil/util.go#L456
Therefore, I've added a test covering the case where the old MachineSet has been scaled down, …
> 🌱 Test rolling update scale-in doesn't race machine deletion

- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
- Updating the docker go dep to the latest available version
Fixes #
> 🌱  Update Docker and containerd dependencies

- cmd/clusterctl/client/cluster/cert_manager.go
- cmd/clusterctl/client/config.go
Fix a couple of spelling errors similar to those in #5974
> 🐛  Fix spelling errors

- docs/book/src/developer/guide.md
> 🌱 book: add TGIK ClusterClass video

- docs/book/src/reference/versions.md
Fixes #5990
/cherry-pick release-1.1
> 📖 book: Add note about Kubernetes v1.23.{0-2} CRD issue and ClusterClass

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
> 📖 book: add Writing a ClusterClass doc

- test/e2e/config/docker.yaml
This is a non-automated cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/6057
Fixes #
> 🐛 update clusterctl version in e2e to latest patch

- docs/book/src/developer/guide.md
> 📖 book: Add "Let's chat about ..." to the video section

- Tiltfile
> 🌱 tilt: update kubectl used for CAPD

- Makefile
- hack/verify-starlark.sh
Just a small refinement of the current Makefile structure (as follow-up to the last Let's chat about session)
Fixes #
> 🌱 Restructure makefile

- OWNERS_ALIASES
@sbueringer has been doing an incredible job in this project and would like to nominate for promotion as project maintainer.
/hold for consensus and community meeting
Fixes #
> 🌱 Promote sbueringer to Cluster API maintainer

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
- internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
- internal/webhooks/patch_validation.go
- test/go.mod
- test/go.sum
> 🌱 Add sprig functions to ClusterClass templates 

- docs/book/src/introduction.md
~ same as https://github.com/kubernetes-sigs/cluster-api/pull/6192 just for release-1.0
Fixes #
> 📖 book: update refs to older books

- README.md
This PR adds a join slack badge in CAPI repo for k8s cluster-api channel.
Now we can see <img src="https://img.shields.io/badge/join%20slack-%23cluster--api-brightgreen">  badge in CAPI repository.
Fixes #
> :seedling: Added a join slack badge in CAPI repo for k8s cluster-api channel

- docs/book/src/developer/providers/implementers-guide/configure.md
Fixes broken link, this currently blocks all PRs.
Fixes #
> 📖 book: fix broken link to kustomize

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/proposals/202105256-cluster-class-and-managed-topologies.md
- internal/controllers/topology/cluster/patches/engine_test.go
- internal/controllers/topology/cluster/patches/variables/variables.go
- internal/controllers/topology/cluster/patches/variables/variables_test.go
- internal/webhooks/patch_validation.go
This is a manual cherry pick of #6171
> 🌱 Add network builtins to topology controller

- docs/book/src/developer/tilt.md
- docs/book/src/tasks/experimental-features/experimental-features.md
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/issues/6202
Fixes #
> 📖 doc: improve tilt doc

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
> 📖 book: clarify usage of builtin variables in enabledIf

- README.md
Fixes a critical bug in the Readme file that can cause developers using Dark Mode to lose their eyesight.
> 📖 replace image in readme with svg

- OWNERS_ALIASES
PR to add myself as a reviewer on PRs in the /docs and /bootstrap owners aliases :smile:
> :seedling:  Add killianmuldoon to bootstrap + docs reviewers

- hack/ensure-kind.sh
- hack/tools/go.sum
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/go.mod
- test/go.sum
**What this PR does / why we need it**: This updates to make use of latest kind v0.12.0 version 
Fixes #6264
> 🌱   Upgrade to use latest Kind version

- internal/webhooks/cluster.go
Update the Cluster webhook to use fieldPath.Child where appropriate instead of redefining paths for each error.
Related to #6249
> :seedling:  Add field.Path aggregation for Cluster webhook

- api/v1beta1/common_types.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- internal/test/builder/builders.go
- internal/test/builder/zz_generated.deepcopy.go
- internal/webhooks/cluster.go
- internal/webhooks/cluster_test.go
This PR relaxes webhook for adoption experiment
Fixes #6284
> :sparkles: Relax webhook for adoption experiment

- .github/workflows/golangci-lint.yml
- Makefile
Note this is a test and should not be merged or reviewed.
> :seedling:  Update golangci-lint action to v3

- .github/workflows/golangci-lint.yml
- Makefile
Update golangci-lint action. Mirrors #6356
> :seedling: Update golangci-lint action

- test/framework/cluster_proxy.go
This PR adds simple retry tolerance to the controller-runtime client operation during E2E in response to an observed flake.
Reference flake:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1516871720609255424
Fixes #
> 🌱 test: retry controller-runtime client instantiation

- cmd/clusterctl/client/repository/repository_github.go
- cmd/clusterctl/client/repository/repository_github_test.go
This is a manual cherry-pick of #6430
Fixes #
> 🐛 clusterctl: retry github i/o operations

- internal/controllers/topology/cluster/reconcile_state_test.go
- internal/test/builder/builders.go
This improves the testing for the topology controller by using a real API Server instead of the fakeClient.
* Separates tests by randomised namespaces.
* Improves output of some tests by moving `g` inside `t.Run`.
* Uses names generated by Topology controller inside the tests.
* Tests depending on `OwnerReferences` also include UID now.
Fixes #
> 🌱  internal/topology migrate reconcile_state tests to envtest

- docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
- docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/book/src/user/troubleshooting.md
Improving ClusterClass docs after some recent discussion/feedback and also adding a note about https://github.com/kubernetes-sigs/cluster-api/issues/6320 in our troubleshooting guide.
> 📖 Improve ClusterClass docs

- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook_test.go
- bootstrap/kubeadm/internal/ignition/clc/clc.go
- bootstrap/kubeadm/internal/ignition/clc/clc_test.go
This is an omnibus PR containing various fixes related to Ignition support in CABPK. See commit messages for details.
Fixes #6403
Fixes #6469
Fixes #6470
> 🐛 CABPK: Add Ignition base64 and file ownership support, reject gzipped content and fix unit tests

- docs/book/src/reference/versions.md
Update documentation for max CoreDNS version, A new line for v1.2 (v1beta1) | v1.9.2 must be added on the last table on the paragraph.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<6527>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6527
> 📖  Update documentation for max CoreDNS version

- docs/book/src/user/quick-start.md
Adds VPC environment varibales for IBM Cloud provider in quick start.
Fixes #
> 📖 Add IBM VPC environment variables

- internal/test/envtest/environment.go
This patch introduces the `PatchAndWait` helper function which could get used as replacement for the `CreateAndWait` helper. 
It uses Server-Side apply instead of client-go's `Create` and allows properly passing the `FieldOwner` used for managed-fields.
This method is required for test cases when Server-Side apply gets introduced for #6320.
Part of #6320
> ✨ envtest: add PatchAndWait helper function for server-side apply

- docs/book/src/reference/jobs.md
> 📖 Update job documentation

- docs/proposals/20220414-runtime-hooks.md
Now that the proposal is merged we can use the swagger file from main.
Fixes #
> 📖 proposals: fix swagger links in runtime hooks proposal

- test/framework/alltypes_helpers.go
- test/framework/cluster_helpers.go
- test/framework/cluster_proxy.go
- test/framework/clusterresourceset_helpers.go
- test/framework/controller_helpers.go
- test/framework/controlplane_helpers.go
- test/framework/deployment_helpers.go
- test/framework/machine_helpers.go
- test/framework/machinedeployment_helpers.go
- test/framework/machinehealthcheck_helpers.go
- test/framework/machinepool_helpers.go
- test/framework/machines.go
This PR follows after #6485 and wraps more retryable errors (these PRs are the result of a manual audit so there may be a couple more as I continue to test).
Fixes #
> 🌱 more retryable errors in test/framework

- cloudbuild-nightly.yaml
- cloudbuild.yaml
Wrong syntax was introduced in #6443 (sorry for that)
Fixes broken cloudbuild runs.
> 🐛 Fix cloudbuild definitions due to invalid syntax

- cloudbuild-nightly.yaml
- cloudbuild.yaml
> 🐛 Add entrypoint to cloudbuild again

- Tiltfile
I tired to use a new Tilt version and when setting an empty registry without this fix I got a validation error.
Fixes #
> 🐛 Fix Tiltfile for newer tilt versions

- exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
- internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
- internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
- internal/controllers/topology/cluster/patches/variables/merge.go
- internal/controllers/topology/cluster/patches/variables/merge_test.go
- internal/controllers/topology/cluster/patches/variables/variables.go
- test/e2e/cluster_upgrade_runtimesdk.go
- test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
- test/extension/handlers/topologymutation/handler.go
- test/extension/handlers/topologymutation/lib.go
- test/extension/main.go
- test/extension/server/server.go
- test/go.mod
Extends the test extension by a first implementation of the server lib and a test topology mutation hook implementation
Fixes #6549
> 🌱 test/extension: add first version of server lib & topology mutation

- internal/runtime/client/client.go
> 🌱 RuntimeSDK: improve discovery error message

- internal/controllers/topology/cluster/patches/template.go
This PR switches to using the kubernetes decoder instead of the standard yaml library to Unmarshal.
Without this change we get additional updates with SSA. 
The problem is that the Go unmarshaller decodes `1` into a float64, while the Kubernetes decoder decodes it into an int64. 
Fixes #6667
> 🐛 use the kubernetes decoder in the patch engine

- docs/book/src/introduction.md
Now that we have a release-1.2 branch this PR adds the release-1.2 book link to the list of books.
Fixes #
Part of #6615
> 📖  Add release 1.2 book link

- docs/book/src/SUMMARY.md
- docs/book/src/developer/providers/v1.2-to-v1.3.md
This PRs adds `v1.2` => `v1.3` migration doc.
Fixes #
Part of #6615
> 📖  add v1.2 -> v1.3 migration doc

- docs/book/src/reference/versions.md
Update the CoreDNS version supported in release 1.1.
> 🌱 Update CoreDNS version for release v1.1

- docs/book/src/tasks/experimental-features/runtime-sdk.md
Fixes #
/cherry-pick release-1.2
> 📖 fix link to RuntimeSDK CAEP

- internal/controllers/machine/machine_controller.go
> 🐛 Improve to get error stack trace for machine reconcile

- api/v1beta1/clusterclass_types.go
- api/v1beta1/zz_generated.openapi.go
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
- exp/runtime/api/v1alpha1/extensionconfig_types.go
- exp/runtime/hooks/api/v1alpha1/common_types.go
- exp/runtime/hooks/api/v1alpha1/discovery_types.go
- exp/runtime/hooks/api/v1alpha1/groupversion_info.go
- exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
- exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
- exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
- exp/runtime/internal/controllers/extensionconfig_controller.go
- exp/runtime/internal/controllers/warmup.go
- internal/controllers/topology/cluster/cluster_controller.go
- internal/controllers/topology/cluster/desired_state.go
- internal/controllers/topology/cluster/reconcile_state.go
- internal/hooks/tracking.go
- internal/runtime/catalog/builder.go
- internal/runtime/catalog/catalog.go
- internal/runtime/catalog/openapi.go
- internal/runtime/client/client.go
- internal/runtime/client/client_test.go
- internal/runtime/client/fake/fake_client.go
- internal/runtime/registry/registry.go
- internal/runtime/test/v1alpha1/fake_types.go
- internal/runtime/test/v1alpha1/groupversion_info.go
- internal/runtime/test/v1alpha2/fake_types.go
- internal/runtime/test/v1alpha2/groupversion_info.go
- internal/webhooks/runtime/extensionconfig_webhook.go
WIP => WIP (only done with some of the packages)
Fixes #
> 🌱 RuntimeSDK: improve error wrapping and godoc

- controlplane/kubeadm/internal/workload_cluster_coredns.go
- controlplane/kubeadm/internal/workload_cluster_coredns_test.go
… was already updated
Adjusts the core DNS update logic to always ensure the correct ClusterRole.
Following scenario:
* A cluster gets provisioned with kubernetes v1.21 and CoreDNS >= v1.8.1
* The CoreDNS ClusterRole will not contain EndpointSlices (because kubeadm won't add them and neither the KCP controller for kubernetes <= v1.21, which is expected)
* The cluster then gets updated to v1.22 referencing the same CoreDNS version
* The old logic won't update the CoreDNS ClusterRole to contain EndpointSlices because the version does not get updated.
* CoreDNS will not be ready anymore because it tries to access EndpointSlices but is not allowed to by RBAC.
This scenario could happen when using ClusterClass and e.g.:
* A `BeforeControlPlane` hook …
> 🐛 Ensure controlplane coredns update deploys the ClusterRole if CoreDNS was already updated

- docs/proposals/20210222-kubelet-authentication.md
Copy of #6211
Thanks @sw33tr0ll!
> 📖  Fix typo in the kubelet authentication proposal

- .github/PULL_REQUEST_TEMPLATE.md
VERSIONING.md no longer exists . This PR is to update to the correct link to avoid confusion to new contributors.
Fixes #
> :seedling: Update stale link in PULL_REQUEST_TEMPLATE.md

- docs/book/src/developer/repository-layout.md
- Adds missing folders in repository layout docs.
- Changed file tree root name projectapi -> cluster-api
> 📖 Update repository-layout with missing folders

- .github/workflows/dependabot.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/lint-docs.yaml
- .github/workflows/release.yml
- .github/workflows/verify.yml
This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/6818
/assign @sbueringer
> [release-1.1] 🌱 Restrict permissions of GitHub actions

- docs/book/src/developer/guide.md
Signed-off-by: Naman <namanlakhwani@gmail.com>
`manager_image_patch.yaml` files are moved to a new location, updating their paths in the docs.
> :book: Update config paths in docs

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
> ✨ Bump to controller-runtime v0.12.3

- Makefile
> 🌱 Bump kpromo to 3.4.4

- cmd/clusterctl/hack/create-local-repository.py
- hack/tools/tilt-prepare/main.go
- metadata.yaml
- test/e2e/config/docker.yaml
- test/e2e/data/shared/v1beta1/metadata.yaml
This PR bumps the versions in the main branch for v1.3 developemt.
Fixes #6833
> 🌱 Bump versions to v1.3

- internal/controllers/machineset/machineset_controller.go
Fix old comment about filteredMachines
Fixes #
> 🌱 Fix old comment about filteredMachines

- .github/workflows/lint-docs-pr.yaml
Looks like https://github.com/kubernetes-sigs/cluster-api/pull/6853 broke the check: https://github.com/kubernetes-sigs/cluster-api/runs/7245805212?check_suite_focus=true
Fixes #
> 📖 Set linkchecker base branch to main

- docs/book/src/reference/versions.md
This PR updates the supported versions matrix for v1.3.x releases.
Fixes #
Part of #6615
> 📖 update supported versions for v1.3

- internal/contract/infrastructure_cluster.go
- internal/contract/infrastructure_cluster_test.go
- internal/contract/types.go
- internal/controllers/topology/cluster/reconcile_state.go
fields
This is a manual cherry-pick of #6673
Fixes #
> 🐛 ClusterClass: reconcile InfrastructureCluster controlPlaneEndpoint fields

- internal/controllers/machine/machine_controller.go
- internal/controllers/machine/machine_controller_phases.go
- internal/controllers/topology/cluster/desired_state.go
- internal/test/builder/bootstrap.go
- test/e2e/self_hosted.go
> :bug: fix: bootstrap typos

- internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
> 🌱 SSA: improve comment about metadata.uid

- internal/controllers/topology/cluster/reconcile_state.go
Co-authored-by: fabriziopandini <fpandini@vmware.com>
Fixes #
> 🐛 SSA: create cluster-shim with regular client, use ignorePaths on create

- docs/developer/releasing.md
This PR adds instruction on the required actions to be performed on Netlify when we have a new release branch.
Fixes #
> 📖 add Netlify instructions to releasing doc

- cmd/clusterctl/client/cluster/mover_test.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/internal/test/fake_objects.go
- test/e2e/cluster_upgrade_runtimesdk.go
- test/e2e/clusterclass_changes.go
- test/e2e/clusterctl_upgrade.go
- test/e2e/common.go
- test/e2e/self_hosted.go
- test/extension/handlers/lifecycle/handlers.go
- test/framework/alltypes_helpers.go
- test/framework/cluster_helpers.go
- test/framework/cluster_proxy.go
- test/framework/cluster_topology_helpers.go
- test/framework/clusterresourceset_helpers.go
- test/framework/control_plane.go
- test/framework/controlplane_helpers.go
- test/framework/deployment_helpers.go
- test/framework/machine_helpers.go
- test/framework/machinedeployment_helpers.go
- test/framework/machinehealthcheck_helpers.go
- test/framework/machinepool_helpers.go
- test/framework/machines.go
- test/framework/namespace_helpers.go
- test/infrastructure/docker/exp/internal/docker/nodepool.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
**What this PR does / why we need it**: Improve E2E error logging throughout the test framework and e2e specs.
Fixes #
> 🌱  Add error messages for all e2e Ginkgo expects

- docs/book/src/introduction.md
- docs/book/src/tasks/certs/using-custom-certificates.md
- docs/book/src/user/quick-start.md
- docs/book/src/user/troubleshooting.md
The Quick Start with CAPD didn't work on my machine and now I've figured out why. To help others that might run into the same problem I've added some troubleshooting advice to the Quick Start. I also sneaked in some minor corrections.  
Fixes #
> 📖  Add troubleshooting advice when running Quick Start with CAPD

- cmd/clusterctl/cmd/topology_plan.go
Creates a diff based on the yaml output instead of go struct output.
Prior to this change it did make use of the cmp package which did create diffs on go object level.
Old output:
```
  &unstructured.Unstructured{
        Object: map[string]any{
                "apiVersion": string("cluster.x-k8s.io/v1beta1"),
                "kind":       string("MachineDeployment"),
                "metadata": map[string]any{
                        ... // 6 identical entries
                        "namespace":       string("default"),
                        "ownerReferences": []any{map[string]any{"apiVersion": string("cluster.x-k8s.io/v1beta1"), "kind": string("Cluster"), "name": string("development-8403"), "uid": …
```
> 🌱 Create unified yaml diff in clusterctl alpha topology plan for having a human readable output

- test/e2e/clusterctl_upgrade.go
- test/e2e/self_hosted.go
This is a manual cherry-pick of #6926 into release-1.2.
Fixes #
> [release-1.2] :sparkles: self hosted tests should check for rollouts

- cmd/clusterctl/config/embedded_manifest.go
- docs/book/src/tasks/automated-machine-management/healthchecking.md
**What this PR does / why we need it**: Fixed typo
> 📖 Fix 'clustrctl' typo

- internal/controllers/cluster/cluster_controller_phases_test.go
This PR refactors and adds some tests to the failure domain tests in cluster reconciler.
Changed the InfrastructureObjects to be `GenericInfrastrucutreCluster` objects so that they are more inline with what happens in a real case. In a real worlds case the failure domains are read and updated in the Cluster from InfrastructureCluster Objects and not InfrastructureMachine objects.
Fixes #
/area testing
> 🌱 update failuredomain tests in cluster reconciler

- Tiltfile
- hack/tools/tilt-prepare/main.go
It allows previous flag parameters to be directly used from within a tilt settings file in tilt-prepare
The json/yaml keys added are as follows -> (deploy_cert_manager,kustomize_build,providers,tools,allowed_contexts) , these have been added to the tiltSettings  struct 
Fixes #6246
> :seedling:  Read Flag Information directly from tilt settings file in tilt prepare

- Makefile
Update conversion-gen version  (v0.23.1 -> v0.25.0).
Part of #6661
> 🌱 Update conversion-gen version (v0.23.1 -> v0.25.0)

- internal/controllers/topology/cluster/reconcile_state.go
- internal/controllers/topology/cluster/reconcile_state_test.go
Ensure we always remove the name of the reconciled object from the resulting error message. The current function works for MachineTemplates, but not for e.g. KubeadmControl plane and can result in infinite reconciles as a result. This is related to the change made in https://github.com/kubernetes-sigs/cluster-api/pull/5971 and solves the same issue, but for a wider range of objects and error messages.
> 🐛  Strip control plane creation error of unique name

- controlplane/kubeadm/internal/controllers/remediation.go
- exp/runtime/internal/controllers/warmup.go
- exp/util/util.go
- internal/controllers/cluster/cluster_controller_phases.go
- internal/controllers/machine/machine_controller_node_labels.go
- internal/controllers/machine/machine_controller_phases.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machinedeployment/machinedeployment_sync.go
- internal/controllers/machineset/machineset_controller.go
Bring more of our logs into line with the logging guidelines by capitalising the Kinds in the key/value pairs.
/kind cleanup
> 🌱  Logs/update type casing

- Makefile
Fixes Makefile mistake `.PHONE` -> `.PHONY`
Fixes #
> 🐛 Fix Makefile target

- internal/controllers/machine/machine_controller.go
:bug:
correct a typo in a code comment
Fixes #
> 🌱 Fix typo in godoc

- hack/observability/grafana/values.yaml
> 🌱 hack/observability: disable PSP for Grafana to support Kubernetes v1.25

- docs/book/src/developer/tilt.md
Update the book, For information: https://github.com/kubernetes-sigs/cluster-api/issues/7201#issuecomment-1241832641
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/7201
> :bug: Update book to properly set label in tilt file

- docs/book/src/user/quick-start.md
I was unsure what DR means, and I guess it means "disaster recovery".
Let's make it explicit, so that nobody needs to look it up.
> 📖 🌱 DR --> disaster recovery

- docs/book/src/user/quick-start.md
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
**What this PR does / why we need it**: Updates the Equinix Metal quick start tab to fix some old and incorrect examples of the required environment variables for using CAPP.
> 📖 Update Equinix Metal quick start tab.

- test/infrastructure/docker/api/v1beta1/dockermachine_types.go
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
> 🌱 CAPD: add columns to DockerMachine CRD

- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
- bootstrap/kubeadm/internal/ignition/clc/clc.go
- bootstrap/kubeadm/internal/ignition/clc/clc_test.go
- docs/book/src/tasks/experimental-features/ignition.md
- go.mod
- go.sum
- hack/tools/go.sum
- test/go.mod
- test/go.sum
- test/infrastructure/docker/internal/provisioning/ignition/kindadapter.go
**What this PR does / why we need it**: Cherry-pick of #7200.
None
cc @sbueringer
> [release-1.2] 🌱 Update references following Flatcar GitHub org rename

- Makefile
- scripts/ci-test.sh
Add Makefile targets for testing the test extension.
> 🌱  Add makefile test targets for test extension

- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
> 📖 Fix link for complex variable types

- docs/book/src/developer/providers/contracts.md
- docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
- docs/book/src/developer/providers/implementers-guide/configure.md
- docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
- docs/book/src/developer/providers/implementers-guide/generate_crds.md
- docs/book/src/developer/providers/implementers-guide/naming.md
- docs/book/src/developer/tilt.md
- hack/tools/tilt-prepare/main.go
- util/conversion/conversion.go
Manual cherry-pick of #7162
Fixes #
> [release-1.2] 📖🌱 Collection of fixes and improvements for provider implementer's guide and Tilt workflow

- cmd/clusterctl/client/config/cert_manager.go
Fix typo. (Test for Stefan Bührigner :-))
There are some test from @sbueringer supported by this PR.
Fixes #
<sub>Michael Grote <michael.grote@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>
> 🌱 Update typo in cert_manager.go

- api/v1alpha3/machineset_types.go
- api/v1alpha4/machineset_types.go
- api/v1beta1/machineset_types.go
- api/v1beta1/zz_generated.openapi.go
- bootstrap/kubeadm/api/v1alpha3/condition_consts.go
- bootstrap/kubeadm/api/v1alpha4/condition_consts.go
- bootstrap/kubeadm/api/v1beta1/condition_consts.go
- cmd/clusterctl/api/v1alpha3/provider_type.go
- cmd/clusterctl/client/cluster/cert_manager.go
- cmd/clusterctl/client/cluster/proxy.go
- cmd/clusterctl/client/config/client.go
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
- cmd/clusterctl/config/manifest/clusterctl-api.yaml
- cmd/clusterctl/log/doc.go
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- controlplane/kubeadm/api/v1alpha3/condition_consts.go
- controlplane/kubeadm/api/v1alpha4/condition_consts.go
- controlplane/kubeadm/api/v1beta1/condition_consts.go
- docs/book/src/clusterctl/developers.md
- hack/ensure-golangci-lint.sh
- test/e2e/config/docker.yaml
- test/framework/clusterctl/e2e_config.go
- util/conditions/unstructured.go
After the "the the" fix I've been experimenting with some regex to find more duplicate words. Here are the findings that I've currently found.
> 🌱 grammar: remove duplicate words

- internal/webhooks/patch_validation.go
- internal/webhooks/patch_validation_test.go
> 🌱 ClusterClass: make patch selector validation more robust

- CONTRIBUTING.md
- docs/proposals/YYYYMMDD-template.md
I noticed `enhancement` was misspelled and fixed it everywhere where I found the same mistake.
> 📖 Fix spelling of enhancement

- docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
- docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
Adds document in the context of #7231
/hold until #7231 is merged
> 📖 book: add doc about Cluster API updates with ClusterClass

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.18.7

- internal/controllers/machine/machine_controller.go
This PR adds logging for machine node watcher. I was experimenting with the machine controller and tried to use it on a cluster where we want to manage only worker machines with CAPI so it wasn't obvious to find out why node watcher doesn't work.
Fixes #
> ✨Add logging for machine node watcher

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.19.2

- cloudbuild-nightly.yaml
- cloudbuild.yaml
Thx @chrischdi for the work on https://github.com/kubernetes/test-infra/pull/27378
Fixes #7165
> 🐛 Bump gcb-docker-gcloud image to fix nightly image/manifest push

- Makefile
- cloudbuild-nightly.yaml
- cloudbuild.yaml
- docs/book/src/clusterctl/developers.md
- docs/book/src/developer/guide.md
- docs/book/src/reference/jobs.md
- scripts/ci-e2e-lib.sh
- scripts/ci-test.sh
- test/infrastructure/docker/README.md
This PR simplifies some make targets inherited from the CAPD makefile
> 🌱 Simplify Makefile targets

- test/e2e/clusterctl_upgrade.go
- test/framework/clusterctl/client.go
- test/framework/clusterctl/clusterctl_helpers.go
Manual cherrypick of https://github.com/kubernetes-sigs/cluster-api/pull/7341
Fixes #
> [release-1.2] 🌱 Add custom upgrade option to e2e

- internal/controllers/topology/cluster/current_state.go
- internal/controllers/topology/cluster/current_state_test.go
Manual cherry-pick of #7403
Fixes #
> [release-1.2] 🐛 ClusterClass: fix reconciliation of MD delete

- test/e2e/clusterclass_changes.go
Add a delete MachineDeploymentTopology test to the ClusterClass changes end to end test. This test should prevent regressions in this bug: https://github.com/kubernetes-sigs/cluster-api/pull/7403
#7404
> :seedling:  Add deleting MachineDeploymentTopology to ClusterClass changes test

- .github/PULL_REQUEST_TEMPLATE.md
Fixes a mistake in the pull request instructions.
Fixes #
>  🌱 Fix grammar in pull request instructions

- docs/book/src/clusterctl/commands/move.md
Documenting somethings that pops up frequently in slack threads
> 📖 Clarify clusterctl move supported use case and limitations

- docs/developer/release-cycle.md
Adds release cycle leads and shadow names for v1.4.0 release cycle
Fixes #
> 📖Release cycle leads & shadow name added

- Makefile
- Tiltfile
xref: https://twitter.com/golang/status/1587490110152773632?s=20&t=ZENmyH45XHtMmiEY9lEHFQ
Fixes #
> 🌱 Bump to Go 1.19.3

- Makefile
- Tiltfile
xref: https://twitter.com/golang/status/1587490110152773632?s=20&t=ZENmyH45XHtMmiEY9lEHFQ
Fixes #
> 🌱 Bump to Go 1.18.8

- docs/book/src/developer/providers/v1.2-to-v1.3.md
> 📖 migration-doc: clarify instructions to use new registry in published components yaml

- Makefile
- docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/developer/releasing.md
Manual cherry-pick of the most important part of #7410 (using the new registry in our published manifests)
Fixes #
> [release-1.2] 🌱 Use new registry in published manifests

- internal/controllers/machine/machine_controller_phases.go
This changes the order in which the bootstrap reconciliation is done in the Machine controller to ensure the ownerReference, and other changes, are set before the dataSecretName is checked. This is designed to help in backup and restore use cases, or any other case where the ownerReference is removed.
In the previous code once the dataSecretName is set the KubeadmConfigTemplate never has its ownerReferences and labels reconciled. This change makes the reconcile loop always attempt to make changes to the bootstrap object, even if the secret name has previously been set.
#6980
> :bug: Ensure Kubeadmconfig is reconciled after datasecretname is set

- cmd/clusterctl/api/v1alpha3/annotations.go
- cmd/clusterctl/client/cluster/installer.go
- cmd/clusterctl/client/cluster/installer_test.go
- cmd/clusterctl/client/init.go
- docs/book/src/developer/providers/v1.2-to-v1.3.md
- docs/book/src/reference/labels_and_annotations.md
WIP:
* unit tests, missing just looking for early feedback
Part of #5686
> 🌱 clusterctl: implement CRD name precheck

- OWNERS_ALIASES
> 🌱 Add Jont828 to clusterctl reviewers

- hack/tools/tilt-prepare/main.go
This PR adds clusterctl label to providers deployed with tilt, so commands like clusterctl move can work as expected
> 🌱 add clusterctl label to providers deployed with tilt

- test/e2e/clusterclass_changes.go
> 🐛 test/e2e: fix ClusterClass changes flake

- internal/controllers/topology/cluster/scope/hookresponsetracker.go
- internal/runtime/client/client.go
- util/util.go
Fix https://github.com/kubernetes-sigs/cluster-api/issues/6945
Fixes #6945
> ✨  Move lowestNonZeroRetryAfterSeconds to util

- docs/book/src/developer/guide.md
Adds relevant videos (that I found!) from KubeCon to the CAPI book. 
Fixes #
> 📖 Add KubeCon Detroit 2022 videos to CAPI book

- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
> :bug: Fix bug in kubeadmconfig adoption

- docs/book/src/developer/tilt.md
Adds kustomize substitutions for tilt development with vSphere.
Fixes n/a
> 📖 Adds kustomize substitutions for vSphere

- api/v1beta1/machine_types.go
- controlplane/kubeadm/internal/cluster_labels.go
- controlplane/kubeadm/internal/controllers/controller.go
- controlplane/kubeadm/internal/controllers/helpers.go
- controlplane/kubeadm/internal/controllers/helpers_test.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller_test.go
- internal/controllers/machinedeployment/machinedeployment_sync.go
- internal/controllers/machinedeployment/mdutil/util.go
- internal/controllers/machineset/machineset_controller.go
This is a manual cherry-pick of #7591 (conflict was just in a comment)
Should be fine now....
Some more text for the verify action
> [release-1.2] 🐛 Fix Machine adoption for KCP/MachineSet-owned Machines 

- .github/ISSUE_TEMPLATE/kubernetes_bump.md
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/7621#issuecomment-1329004395
> 📖 doc: Add note about kind images to Kubernetes bump issue

- controlplane/kubeadm/internal/controllers/controller_test.go
> :bug: Remove inaccurate comment on KCP test

- docs/book/src/user/quick-start.md
Update clusterctl links to version to v1.3.x in quick start.
Fixes #
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/7527
> 📖 update clusterctl version to v1.3.x in quickstart

- .gitignore
- Makefile
- cmd/clusterctl/hack/create-local-repository.py
- hack/tools/tilt-prepare/main.go
- metadata.yaml
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/docker.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/bases/cluster-with-topology.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/bases/crs.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/cluster-template-topology/kustomization.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/cluster-template/kustomization.yaml
- test/e2e/data/infrastructure-docker/v1beta1/v1.3/clusterclass-quick-start.yaml
- test/e2e/data/shared/v1beta1/v1.3/metadata.yaml
This PR prepares the main branch for development.
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7672
> 🌱 prepare main branch for v1.4 development

- docs/book/src/SUMMARY.md
- docs/book/src/developer/providers/v1.3-to-v1.4.md
This PR adds v1.3 -> v1.4 migration doc
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7672
> 📖 add v1.3 -> v1.4 migration doc

- docs/book/src/developer/providers/version-migration.md
A small change to add the migration to 1.4 link to the `version-migration.md` file.
No open issues
> 📖 Add missing version migration link

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7780
Fixes #
> [release-1.3] 🌱 Bump golang.or/x/netto v0.4.0

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7780
Fixes #
> [release-1.2] 🌱 update golang.org//x/net to v0.4.0

- Makefile
- Tiltfile
Bumps to Go 1.19.4
xref: https://groups.google.com/g/golang-dev/c/G9Jj4cO4Gpk
Fixes #
> 🌱 Bump to Go 1.19.4

- Makefile
- Tiltfile
Bumps to Go 1.18.9
xref: https://groups.google.com/g/golang-dev/c/G9Jj4cO4Gpk
Fixes #
> 🌱 Bump to Go 1.18.9

- test/infrastructure/docker/api/v1beta1/dockerclustertemplate_types.go
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
> 🌱 Add category to DockerClusterTemplate

- docs/book/src/user/quick-start.md
Manual cherry-pick of #7767 resolving the merge conflict.
Fixes #
> [release-1.3] 📖 Add download links for all clusterctl architectures to quick start

- docs/book/src/reference/providers.md
This change aims to make it easier to read and understand the provider list by writing out the abbreviations for OCI, EKS, BYOH and GCP. 
Fixes #
> 📖 docs: write out abbreviations in providers implementations

- .github/workflows/scan.yml
- Makefile
- docs/book/src/reference/jobs.md
- hack/verify-container-images.sh
Manual cherry-pick of #7604
Fixes #
> [release-1.2] ✨ Adds a verify script that run trivy scanner on container images

- Makefile
> 🌱 Update conversion-gen version (v0.25.0 -> v0.26.0)

- docs/book/src/reference/versions.md
> [release-1.3] 🌱 Update versions doc adding Kubernetes 1.26

- docs/book/src/reference/versions.md
> [release-1.2] 🌱 Update versions doc adding Kubernetes 1.26

- Makefile
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
- cmd/clusterctl/config/manifest/clusterctl-api.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
- config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
- docs/book/src/developer/providers/v1.3-to-v1.4.md
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
> 🌱 Bump controller-tools 0.10.0=>0.11.1

- hack/observability/visualizer/kustomization.yaml
> 🌱 Update visualizer chart to v1.1.0

- CONTRIBUTING.md
- README.md
- REVIEWING.md
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
As I was reading the cluster-api documentation, I found changes that would increase readability and hopefully help the community
> 📖 optimize partial descriptions in the document

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.19.5

- Makefile
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
- cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
- cmd/clusterctl/config/manifest/clusterctl-api.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
- config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
> 🌱 Bump to controller-tools v0.11.2

- docs/book/src/developer/providers/v1.3-to-v1.4.md
**What this PR does / why we need it**:  Updated the release notes to inculcate the changes done in PR #7618 
**Which issue(s) this PR fixes** : Fixes #7611
> :book: Add provider notes for API constants renaming

- internal/controllers/topology/cluster/patches/engine.go
> 🌱 ClusterClass: catch panics when applying patches

- .golangci.yml
- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
- cmd/clusterctl/client/cluster/components_test.go
- cmd/clusterctl/client/cluster/objectgraph_test.go
- cmd/clusterctl/client/cluster/topology_test.go
- cmd/clusterctl/client/config_test.go
- cmd/clusterctl/client/repository/template_test.go
- cmd/clusterctl/internal/util/obj_refs_test.go
- controllers/remote/keyedmutex_test.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
- controlplane/kubeadm/internal/controllers/scale_test.go
- controlplane/kubeadm/internal/etcd/etcd_test.go
- exp/addons/internal/controllers/clusterresourceset_helpers_test.go
- exp/internal/controllers/machinepool_controller_noderef_test.go
- exp/internal/controllers/machinepool_controller_test.go
- exp/runtime/internal/controllers/extensionconfig_controller_test.go
- exp/runtime/internal/controllers/warmup_test.go
- internal/controllers/machine/machine_controller_phases_test.go
- internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
- internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
- internal/controllers/topology/cluster/desired_state_test.go
- internal/controllers/topology/cluster/reconcile_state_test.go
- internal/controllers/topology/machineset/util_test.go
- internal/runtime/registry/registry_test.go
- test/e2e/clusterclass_changes.go
- test/infrastructure/docker/internal/provisioning/cloudinit/unknown_test.go
- util/conversion/conversion_test.go
- util/resource/resource_test.go
- util/yaml/yaml_test.go
Enable ginkgolinter len assertion check and fix findings. 
A minor improvement imo, but that still an improvement. 
Partof #8050
> 🌱 Enable ginkgolinter len assertion check and fix findings

- test/e2e/clusterctl_upgrade.go
> 🌱 test/e2e: disable rollout check for ClusterClass-based cluster in clusterctl upgrade test

- hack/tools/log-push/main.go
- util/yaml/yaml.go
Comparing with `==` will fail on wrapped errors. Use errors.Is to check for a specific error is better.
Fixes #
> 🌱  Use errors.Is to check for a specific error

- docs/release/release-cycle.md
- docs/release/releases/release-1.5.md
This PR adds the tentative release dates for the v1.5.0 release cycle.
Thanks to @sbueringer for coming up with the dates 🙏🏼.
Fixes #
> 📖 Preliminary release dates for v1.5

- docs/book/src/introduction.md
We want a way to call out some upcoming breaking changes for new versions. This adds a note style callout in the
`ClusterAPI documentation versions` section.
Ref #8038
> :book: Add breaking changes section to introduction.md

- controlplane/kubeadm/internal/workload_cluster_conditions.go
- controlplane/kubeadm/internal/workload_cluster_conditions_test.go
This is a manual cherry-pick of #8132 into release-1.3.
Credit to @wm775825 for the fix!
> [release-1.3] 🐛 bugfix function aggregateFromMachinesToKCP

- Makefile
- docs/book/src/developer/providers/v1.3-to-v1.4.md
> 🌱 Bump apidiff to v0.6.0

- docs/book/src/clusterctl/developers.md
- docs/book/src/clusterctl/provider-contract.md
- docs/book/src/developer/architecture/controllers/cluster-topology.md
- docs/book/src/developer/architecture/controllers/control-plane.md
- docs/book/src/developer/architecture/controllers/machine-pool.md
- docs/book/src/developer/architecture/controllers/machine.md
- docs/book/src/developer/e2e.md
- docs/book/src/developer/logging.md
- docs/book/src/developer/providers/contracts.md
- docs/book/src/developer/providers/v0.3-to-v0.4.md
- docs/book/src/developer/providers/v1.0-to-v1.1.md
- docs/book/src/developer/providers/v1.2-to-v1.3.md
- docs/book/src/developer/repository-layout.md
- docs/book/src/developer/testing.md
- docs/book/src/developer/tilt.md
- docs/book/src/reference/glossary.md
- docs/book/src/security/pod-security-standards.md
- docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
- docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
- docs/book/src/tasks/multiple-providers.md
- docs/book/src/user/quick-start.md
- docs/book/src/user/troubleshooting.md
Fixing some typos and incorrect links in the CAPI book.
>  📖 Clean up some typos and links in CAPI book

- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- controlplane/kubeadm/internal/controllers/controller.go
- exp/internal/controllers/machinepool_controller.go
- internal/controllers/cluster/cluster_controller.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
- internal/controllers/machineset/machineset_controller.go
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/internal/controllers/dockercluster_controller.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
> 🌱 all: setup controller in a consistent way

- internal/controllers/topology/cluster/desired_state.go
- internal/controllers/topology/cluster/desired_state_test.go
> 🌱 ClusterClass: don't propagate MD upgrade annotations

- .github/workflows/golangci-lint.yml
- .github/workflows/scan.yml
> 🌱 ci: set fail-fast false for all GH actions using matrix

- CONTRIBUTING.md
Add kubernetes contributor course in contributing. md
Fixes #8061
> 📖 docs: link Kubernetes contributor guide in CONTRIBUTING.md

- controllers/remote/cluster_cache_healthcheck_test.go
This PR adds a unit test that checks if the health check is requeued properly if we're in the middle of the creation of a new cluster accessor. In order to simulate the creation, the test case deletes the existing accessor and locks the cluster. If the health check is requeued properly, the health check should be cancelled by the timeout of the context and not by returning. Additionally, the done channel should be closed.
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/8176
> :seedling: Add unit test for health check during creation of a new cluster accessor

- Makefile
We probably need this to properly generate our promotion PR for the new registry folder
xref: https://github.com/kubernetes/k8s.io/pull/4954#issuecomment-1472996956
cc @kubernetes-sigs/cluster-api-release-team 
cc @fabriziopandini @killianmuldoon 
Fixes #
> 🌱 Bump kpromo to v3.5.1

- Makefile
> [release-1.2] 🌱 Bump kpromo to v3.5.1 

- .github/workflows/golangci-lint.yml
- test/framework/kubetest/setup.go
> 🌱 Bump golangci-lint to v1.51.2

- docs/book/src/introduction.md
Adding to our main page a PSA that can be really useful for our users and help the community in the effort of migrating to registry.k8s.io
> 📖 Add note for registry.k8s.io migration

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
- docs/book/src/tasks/automated-machine-management/healthchecking.md
Add documentation about KCP remediation to the book
> 📖 Add documentation about KCP remediation

- docs/book/src/introduction.md
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8363
Fixes #
> [release-1.3] 📖  Release 1.3 add registry.io notice

- .github/workflows/lint-docs-weekly.yml
- .github/workflows/scan.yml
- .github/workflows/test-release-weekly.yml
Update versions in the github actions matrices for the new release.
/area testings
> :seedling: Update version matrix for github workflows

- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Follow up cherry-pick PR for https://github.com/kubernetes-sigs/cluster-api/pull/8339
Fixes #8242
> :bug: Enable updates from CloudInit (mostly ubuntu) based KCPs to Ignition (flatcar) based KCPs

- test/e2e/config/docker.yaml
Add a link to the file format, so that people new to it understand the file format.
> :seedling: :book: Added link to the file format

- docs/book/src/developer/testing.md
controller-runtime uses main, not master.
> 📖 Use main for controller-runtime URLs

- README.md
**Safe to merge PR**:
Added latest stable release status badge to readme, as per documentation best practices:
> 📖 Add latest stable release status badge

- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/developer/guide.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
Update cert manager to version v1.11.1.
Fixes #8515 
> :seedling: Update cert manager to v1.11.1

- Makefile
- Update conversion-gen version (v0.26.0 -> v0.27.1)
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8459
Fixes #
> :seedling:Update conversion-gen version (v0.26.0 -> v0.27.1)

- docs/book/src/developer/e2e.md
> 📖 book: drop unused link in developing e2e tests doc

- docs/release/release-tasks.md
- hack/tools/release/notes.go
While going through a release some context was missing in docs.
The comms team updates the `Fun stats` to `Overview` manually,  this will make the job a bit more automated.
No open issue
> 📖  updates to release task docs and notes tool

- docs/release/release-tasks.md
xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1683029484982839
> 📖 Improve cutting release notes steps in release-tasks 

- docs/book/src/developer/testing.md
Documents a variant of using `jq` to inspect the json logs of tests.
Fixes #
> 📖 testing: add jq variant for inspecting json logs

- .github/workflows/verify.yml
> 🐛 verifier: use pull_request instead of pull_request_target

- .github/workflows/verify.yml
> 🌱 verifier: change back to pull_request_target to make it work again

- docs/book/src/tasks/experimental-features/ignition.md
**What this PR does / why we need it**: Removed the TODO and changed the link to the one specified int issue #8745 
Fixes #8745
> 📖 Changed the link and removed TODO

- test/framework/machinepool_helpers.go
(cherry picked from commit a26fe0e3766edad124ad6fc04758c69ecec49558)
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8739
> :bug: [release-1.3] Adjust machinepool helper e2e timeout

- test/framework/machinepool_helpers.go
Signed-off-by: killianmuldoon [kmuldoon@vmware.com](mailto:kmuldoon@vmware.com)
(cherry picked from commit https://github.com/kubernetes-sigs/cluster-api/commit/a26fe0e3766edad124ad6fc04758c69ecec49558)
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8739
> :bug: [release-1.4] Adjust machinepool helper e2e timeout

- docs/book/src/reference/jobs.md
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8224
Related to: https://github.com/kubernetes/test-infra/pull/29621
Edit: Updates the jobs list and it's variables according to the latest changes from https://github.com/kubernetes/test-infra/pull/29621
> 📖 Document new and missing jobs

- test/e2e/clusterclass_rollout.go
Improve the `without` function in the ClusterClass rollout test to take a gomega handler and fail when the key doesn't exist in the map. 
This improves on the change made in https://github.com/kubernetes-sigs/cluster-api/pull/8761
> :seedling: Improve gomega fail handling in clusterClass rollout

- controlplane/kubeadm/internal/controllers/status.go
- docs/book/src/developer/logging.md
- test/e2e/common.go
- test/framework/alltypes_helpers.go
Related to https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1578688758
> 🌱 test/e2e: also dump workload cluster kube-system pods

- docs/book/src/reference/providers.md
Adds the in-cluster IPAM and Helm addon providers to the list in the book.
> :book: add in-cluster ipam and helm addon providers

- hack/observability/grafana/dashboards/cluster-api.json
- hack/observability/grafana/dashboards/controller-runtime.json
> 🌱 hack/observability: improve Grafana dashboards

- test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
- test/e2e/scale_test.go
- test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml
This PR modifies the scale E2E test defaults.
Fixes #
> 🌱 modify scale e2e test defaults

- docs/release/releases/release-1.6.md
Starting the process of setting up the v1.6 release documentation
Fixes #
> 📖  add release-1.6 schedule document

- Tiltfile
- docs/book/src/developer/tilt.md
- hack/observability/grafana/chart/values.yaml
- hack/observability/grafana/dashboards/cluster-api.json
- hack/observability/grafana/dashboards/controller-runtime.json
- hack/observability/prometheus/values.yaml
- hack/observability/tempo/kustomization.yaml
- hack/observability/tempo/values.yaml
> 🌱 hack/observability: add tempo (for traces)

- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- bootstrap/util/configowner.go
- bootstrap/util/configowner_test.go
- docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
- exp/internal/controllers/machinepool_controller.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machineset/machineset_controller.go
- main.go
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
- test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
- util/util.go
- util/util_test.go
Related https://github.com/kubernetes-sigs/cluster-api/issues/8814
> 🌱 util: cache list calls in cluster to objects mapper

- docs/release/releases/release-1.5.md
Pushing the release date by one day since July 4th is a US holiday and most of the release team will be off.
Fixes #
> 📖  Update 1.5.0-beta.x release date

- hack/observability/kube-state-metrics/chart/kustomization.yaml
- hack/observability/kube-state-metrics/chart/values.yaml
Bumps kube-state-metrics chart to get updated version v2.9.2
Partially solves #8951
Verified that the metrics stay the same.
> ✨ hack/observability bump kube-state-metrics chart to get version v2.9.2

- docs/release/release-tasks.md
- This PR add metal-3 to the list of CAPI providers in release-tasks.md.
> :book: Add Metal3 to list for beta release notification

- cmd/clusterctl/client/cluster/template.go
- cmd/clusterctl/client/cluster/template_test.go
- cmd/clusterctl/client/repository/repository_github.go
- cmd/clusterctl/client/repository/repository_github_test.go
- cmd/clusterctl/cmd/version_checker.go
- cmd/clusterctl/internal/test/fake_github.go
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
- 🌱 bump go-github dependency to version v53
/assign @sbueringer @fabriziopandini 
Fixes #
> 🌱 bump go-github dependency to version v53

- hack/tools/release/notes.go
**What this PR does / why we need it**: Implemented sorting function to alphabetically sort release tool output irrespective of whether the first letter is capital or small as stated in #9010 
Fixes #9010
> 🐛 Alphabetically sorting release tool output

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.20.7

- Makefile
- Tiltfile
> [release-1.5] 🌱 Bump to Go 1.20.7

- docs/proposals/20210526-cluster-class-and-managed-topologies.md
> [release-1.5] :bug: Fix link to v1.1-v1.2 provider migration guide

- docs/release/release-tasks.md
This seems to not be needed anymore now we have automated the release note generation.
/area release
> :book: Remove unnecessary task from release tasks doc

- Makefile
Forgot to add this in my previous PR
Fixes #
> 🌱 Add .PHONY for doctoc target

- .github/workflows/weekly-security-scan.yaml
- Makefile
- hack/verify-container-images.sh
Manual cherry-pick of #9144
/area ci
> [release-1.4] 🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action

- docs/book/src/reference/jobs.md
- docs/book/src/reference/versions.md
Manual cherry-pick of #9161
Part of #8708
> [release-1.5] 📖 book: Update versions doc adding Kubernetes 1.28 + prowjob documentation

- docs/release/release-tasks.md
Part of #9216 
- Add documentaion for public release session
Fixes #
> :book: Documentation improvements: public release session

- Makefile
Bump kpromo from v3.6.0 to v4.0.4.
> :seedling: Bump kpromo to v4.0.4

- CHANGELOG/v1.5.1.md
> 🌱 Release v1.5.1

- test/e2e/autoscaler_test.go
> 🌱 Bump autoscaler to v1.28.0

- Makefile
- Tiltfile
> [release-1.4]🌱 Bump to Go 1.19.13

- CHANGELOG/v1.4.7.md
> 🌱 Release v1.4.7

- CHANGELOG/v1.5.2.md
> 🌱 Release v1.5.2

- hack/tools/release/notes.go
Another area that needs extra formatting, found during last patch release
/area release
> 🌱 Format MachineHealthCheck area in release notes

- docs/book/src/developer/providers/bootstrap.md
If you are new to the topic an example can help to understand the topic.
> :book: bootstrap: Provide an example.

- CHANGELOG/v1.5.3.md
> 🌱 Release v1.5.3

- Makefile
> 🌱 Ensure we generate all webhook manifests.yaml

- docs/release/release-tasks.md
Tries to better define Information/communication channels/stakeholders and remove TBDs'. Any suggestions to better define the above points are welcome
Part of: #9104
Fixes: #9638 
/area release
> 📖 Define details of "Communicate key dates to the community" 

- hack/tools/release/notes.go
> 🌱 Format Community meeting area in release notes

- .github/workflows/pr-verify.yaml
This should allow us to use 🚀
/area release
> 🌱 Bump PR title checker github action to v0.4.1

- OWNERS_ALIASES
Uncommenting myself in release team because now I am member Kubernetes-sigs
> 🌱 Add adilGhaffarDev to release-team owner alias

- .golangci.yml
- exp/ipam/api/v1alpha1/conversion.go
- exp/ipam/api/v1alpha1/conversion_test.go
> 🌱 Enforce IPAM import alias

- internal/topology/variables/cluster_variable_defaulting_test.go
> 🌱 Add additional test cases for nested variable defaulting

- cmd/clusterctl/cmd/topology_plan.go
- test/framework/cluster_proxy.go
- test/framework/clusterctl/client.go
- test/framework/exec/kubectl.go
> [release-1.5] 🌱 Improve output of exec.KubectlApply

- docs/book/src/tasks/bootstrap/microk8s-bootstrap.md
> :book: typo fix in microk8s-bootstrap.md

- docs/book/src/developer/architecture/controllers/machine-set.md
this PR fix machineset In-place propagation inaccuracy problem
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/9793
> 📖 Fix field paths in MachineSet in-place propagation docs

- Tiltfile
Fix two variable names in the Tiltfile (nit)
/area devtools
> 🌱 fix variables names in Tiltfile

- CHANGELOG/v1.5.4.md
> 🌱 Release v1.5.4

- docs/book/src/user/quick-start.md
> 📖 Update clusterctl version to v1.6.x in quick start

- test/framework/clusterctl/e2e_config.go
> 🌱 Fix typo in test framework

- Tiltfile
- docs/book/src/developer/tilt.md
- docs/book/src/reference/versions.md
- docs/book/src/user/quick-start.md
- test/e2e/config/docker.yaml
- test/e2e/quick_start_test.go
- test/framework/bootstrap/kind_provider.go
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
- test/infrastructure/kind/mapper.go
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9872
Fixes #
/area testing
> ✨ [release-1.6] v1.29: Prepare quickstart, capd and tests for the new release including kind bump

- docs/book/src/developer/providers/version-migration.md
- docs/book/src/reference/jobs.md
- docs/book/src/reference/versions.md
* Update supported versions in versions.md
* Update job documentation in jobs.md
part of #9578
> 📖 book: Update versions doc adding Kubernetes 1.29 and prowjob documentation

- docs/book/src/reference/providers.md
Add [k0smotron](https://github.com/k0sproject/k0smotron/) to list of providers.
> :book: Add k0smotron to providers list

- test/e2e/scale_test.go
> 🌱 [release-1.6] e2e: drop duplicated scale test

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
Manual cherry-pick of #10001
Fixes #
> 🌱 [release-1.6] go.mod: bump github.com/cloudflare/circl to v1.3.7

- docs/book/src/reference/glossary.md
This PR adds the ffficial abbreviation for Cluster API Operator - `CAPIO`.
Related issue: https://github.com/kubernetes-sigs/cluster-api-operator/issues/357
Fixes #
> 📖 Add Cluster API Operator (CAPIO) to the glossary

- Makefile
/assign sbueringer 
Part of #9578
/area ci
> 🌱 Bump conversion-gen to v0.29.0

- CHANGELOG/v1.6.1.md
> 🌱 Release v1.6.1

- CHANGELOG/v1.5.5.md
> 🌱 Release v1.5.5

- OWNERS_ALIASES
Manual cherry-pick of #9997
/area community-meeting
/assign sbueringer 
/cherry-pick release-1.5
> 🌱 [release-1.6] Promote chrischdi to Cluster API maintainer

- docs/proposals/20220725-managed-kubernetes.md
> 🐛 fix: markdown broken links

- Makefile
> 🌱 Bump kpromo to v4.0.5

- .golangci.yml
- Makefile
- Tiltfile
- hack/ensure-go.sh
> [release-1.6] 🌱 Bump Go to 1.21.5

- test/framework/deployment_helpers.go
This API was deprecated in v1.21 and completely removed in v1.25. We can safely remove its support in the test framework.
Fixes #
/area testing
> 🌱 Drop policy v1beta1 API support in the testing framework

- Makefile
> :seedling: fix Make target generate-go-openapi

- CHANGELOG/v1.5.6.md
> 🌱 Release v1.5.6

- CHANGELOG/v1.6.2.md
> 🌱 Release v1.6.2

- test/framework/ownerreference_helpers.go
> [release-1.5] 🐛 test: retry GetOwnerGraph when having certificate issues

- test/framework/ownerreference_helpers.go
- #10201 
Addresses flaky tests in: https://github.com/kubernetes-sigs/cluster-api/issues/9688
> [release-1.4] 🐛 test: retry GetOwnerGraph when having certificate issues

- Makefile
cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9990
/area release
> [release-1.5] 🌱 read in dockerfiles from stdin

- Makefile
- Tiltfile
bumps go version to v1.21.8 to incorporate CVE fixes
> 🌱 bump go version to 1.21.8

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
manual backport of: https://github.com/kubernetes-sigs/cluster-api/pull/10248
> [release-1.5] 🌱 bump protobuf to v1.33.0 to address CVEs

- docs/proposals/20200511-clusterctl-extensible-template-processing.md
> 📖 Remove non existing doc links

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
Update versions in the github actions matrices for the new release.
/area testings
> 🌱 Update version matrix for github workflows for release-1.7

- docs/book/src/tasks/diagnostics.md
> 🌱 Add docs on how to get goroutine dump

- Makefile
- hack/verify-go-directive.sh
fixes https://github.com/kubernetes-sigs/cluster-api/pull/10261#issuecomment-2020273138
> [release-1.5] 🌱 Added go directive test

- Makefile
- hack/verify-go-directive.sh
fixes https://github.com/kubernetes-sigs/cluster-api/pull/10261#issuecomment-2020273138
> [release-1.6] 🌱 Added go directive test

- test/infrastructure/inmemory/README.md
> 📖 Document how to connect to InMemoryClusters

- Makefile
- Tiltfile
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
xref: https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M
Fixes #
> 🌱 Bump golang to v1.21.9 and golang.org/x/net to mitigate CVE-2023-45288

- hack/observability/visualizer/kustomization.yaml
**What this PR does / why we need it**: Bump Cluster API Visualizer to v1.3.0
Fixes #
> 🌱 Bump Cluster API Visualizer to v1.3.0

- docs/release/releases/release-1.8.md
Adds preliminary schedule for `v1.8` minor release
Fixes #9978
/area release
> 📖 add Cluster API release-1.8 timeline document 

- .github/workflows/pr-golangci-lint.yaml
- exp/runtime/hooks/api/v1alpha1/discovery_types.go
- exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
> 🌱 bump golangci-lint to v1.57.2

- hack/tools/prowjob-gen/generator.go
Required for CAPV templates improvements
> 🌱 Add more templating func to prowjob-gen

- CHANGELOG/v1.6.4.md
> 🌱  Release v1.6.4

- CONTRIBUTING.md
- docs/book/src/reference/versions.md
update docs for v1.7 based off of release cutting doc steps: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release
> 📖 update coredns + contributing for v1.7.0

- docs/book/src/user/quick-start.md
> 📖  Update clusterctl version to v1.7.x in quick start

- docs/book/src/reference/versions.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
> [release-1.7] 🌱 Bump Kubernetes in tests to v1.30.0 and claim support for v1.30

- docs/proposals/20210222-kubelet-authentication.md
> 📖 Add disclaimer to Kubelet Authentication proposal

- test/e2e/autoscaler_test.go
> 🌱 Bump autoscaler to v1.30.0

- internal/util/ssa/patch_test.go
This is just a first step to incrementally improve this test. There is more to come because we probably found an issue in apiserver, but I"ll open a separate issue for that.
Fixes #
> 🌱 Improve SSA patch test

- docs/book/src/SUMMARY.md
- docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
- This PR adds a migration doc for `v1.7` to `v1.8`.
Fixes Task: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers
> 📖 Add v1.7 to v1.8 migration guide

- docs/book/src/clusterctl/developers.md
Minor fixed to developer.md
Fixes #
> 📖 Minor fixed to developer.md

- docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
Adds a recommendation for providers in line with https://github.com/kubernetes-sigs/cluster-api/pull/10580.
> 📖 Document terminationMessagePolicy suggestion for providers

- CHANGELOG/v1.7.2.md
> 🚀 Release v1.7.2

- CHANGELOG/v1.6.5.md
> 🚀   Release v1.6.5

- .github/ISSUE_TEMPLATE/kubernetes_bump.md
- .github/dependabot.yaml
- Tiltfile
- docs/book/src/developer/tilt.md
- docs/book/src/user/quick-start.md
- hack/ensure-kind.sh
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/go.mod
- test/go.sum
- test/infrastructure/kind/mapper.go
> 🌱 kind: bump to v0.23.0

- .github/ISSUE_TEMPLATE/kubernetes_bump.md
…
Follow-up from discussions of #10524 
Fixes #
> 📖 github: document to cherry-pick the kind bump to the latest release in issue template

- .github/dependabot.yaml
- Tiltfile
- docs/book/src/developer/tilt.md
- docs/book/src/user/quick-start.md
- hack/ensure-kind.sh
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/go.mod
- test/go.sum
- test/infrastructure/kind/mapper.go
Manual cherry-pick of #10610
Fixes #
> [release-1.7] 🌱 kind: bump to v0.23.0

- bootstrap/kubeadm/config/rbac/role.yaml
- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- config/rbac/role.yaml
- controlplane/kubeadm/config/rbac/role.yaml
- controlplane/kubeadm/internal/controllers/controller.go
- exp/internal/controllers/machinepool_controller.go
- internal/controllers/cluster/cluster_controller.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
- internal/controllers/machineset/machineset_controller.go
Fixup changes from:
* #10552
By grepping through job logs
Fixes #
/area api
> 🐛 re-add patch for events

- exp/runtime/topologymutation/variables.go
- exp/runtime/topologymutation/variables_test.go
> ✨ Fix GetObjectVariableInto util func

- Makefile
- Tiltfile
- netlify.toml
> 🌱 Bump to Go 1.22.4

- Makefile
- Tiltfile
> [release-1.7] 🌱 Bump to Go 1.21.11

- Makefile
- Tiltfile
> [release-1.6] 🌱 Bump to Go 1.21.11

- CHANGELOG/v1.6.6.md
> 🚀  Release v1.6.6

- hack/tools/go.mod
- hack/tools/go.sum
- test/go.mod
- test/go.sum
- test/infrastructure/container/docker.go
Manual bump.
Supersedes: #10773
/assign @sbueringer 
> 🌱 Bump github.com/docker/docker from 26.1.4+incompatible to 27.0.0+incompatible in /test

- hack/observability/visualizer/kustomization.yaml
**What this PR does / why we need it**: Bump Cluster API Visualizer to v1.3.1
Fixes #
> 🌱 Bump Cluster API Visualizer to v1.3.1

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.22.5

- Makefile
- Tiltfile
> [release-1.7] 🌱 Bump to Go 1.22.5

- Makefile
- Tiltfile
> [release-1.6] 🌱 Bump to Go 1.22.5

- CHANGELOG/v1.6.7.md
> 🚀  Release v1.6.7

- docs/book/src/user/quick-start.md
This change updates the Azure parts of the quick start guide to account for the default auth mechanism in templates [changing to Workload Identity](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4765) in CAPZ v1.16 (coming next week). These changes add steps to change back to Service Principal auth to avoid turning this doc into yet-another-Workload-Identity-setup doc and to continue to support CAPZ v1.15.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4921
/area provider/azure
> :book: update Azure quick start for CAPZ v1.16

- docs/book/src/developer/providers/bootstrap.md
> :book: docs/book/src/developer/providers/bootstrap.md: fix typo

- exp/addons/internal/controllers/clusterresourceset_controller.go
- exp/addons/internal/controllers/clusterresourceset_controller_test.go
- exp/addons/internal/controllers/suite_test.go
- internal/test/envtest/environment.go
Manual backport of #10869.
/cc @sbueringer 
> [release-1.7] 🌱 Make ClusterResourceSet controller more predictable

- CHANGELOG/v1.8.0-beta.1.md
> 🚀  Release v1.8.0-beta.1

- exp/internal/controllers/machinepool_controller.go
- exp/internal/controllers/machinepool_controller_noderef.go
- exp/internal/controllers/machinepool_controller_test.go
> 🌱 Improve MP unit test coverage

- CHANGELOG/v1.8.0-rc.0.md
> 🚀  Release v1.8.0-rc.0

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
Update versions in the github actions matrices for new 1.8 branch
/area CI
> 🌱 Update version matrix for github workflows

- .github/workflows/pr-md-link-check.yaml
Update base branch so link checker for release 1.8 branch.
/area ci
> 🌱 [release-1.8] Update base branch for link checker

- docs/book/src/introduction.md
Document that the default documented version is now release-1.8 and provide backlink to release-1.7
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10472
/area release
> 📖 Add release 1.7 book link

- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
> ✨ Bump Kubernetes version used for testing to v1.31.0-rc.0

- bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
- config/crd/patches/webhook_in_clusterclasses.yaml
- config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
- config/crd/patches/webhook_in_clusterresourcesets.yaml
- config/crd/patches/webhook_in_clusters.yaml
- config/crd/patches/webhook_in_machinedeployments.yaml
- config/crd/patches/webhook_in_machinehealthchecks.yaml
- config/crd/patches/webhook_in_machinepools.yaml
- config/crd/patches/webhook_in_machines.yaml
- config/crd/patches/webhook_in_machinesets.yaml
- controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10972
Fixes #
> [release-1.6] 🐛 Drop caBundle from CRDs

- bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
- config/crd/patches/webhook_in_clusterclasses.yaml
- config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
- config/crd/patches/webhook_in_clusterresourcesets.yaml
- config/crd/patches/webhook_in_clusters.yaml
- config/crd/patches/webhook_in_machinedeployments.yaml
- config/crd/patches/webhook_in_machinehealthchecks.yaml
- config/crd/patches/webhook_in_machinepools.yaml
- config/crd/patches/webhook_in_machines.yaml
- config/crd/patches/webhook_in_machinesets.yaml
- controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
- test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
- test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml
Manual cherry-pick of #10972
Fixes #
> [release-1.7] 🐛 Drop caBundle from CRDs

- exp/addons/internal/controllers/clusterresourceset_controller_test.go
Fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1820323066937348096
> 🐛 Fix CRS test flake

- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
Part of:
- https://github.com/kubernetes-sigs/cluster-api/issues/10653
Fixes #
> ✨ Bump Kubernetes to v1.31.0-rc.1

- CHANGELOG/v1.8.0-rc.1.md
- Add release notes for v1.8.0.rc-1
/area release
> 🚀 Release v1.8.0-rc.1

- internal/controllers/machine/machine_controller_test.go
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11032
/area machine
> :seedling: Follow-up PR nits from 11032

- CHANGELOG/v1.7.5.md
> 🚀 Release v1.7.5

- CHANGELOG/v1.6.8.md
> 🚀 Release v1.6.8

- cmd/clusterctl/client/cluster/proxy.go
Looking at this PR (https://github.com/Homebrew/homebrew-core/pull/180957/files), the new error message is not good:
The problem is that on the original PR that changed this in CAPI (https://github.com/kubernetes-sigs/cluster-api/pull/11006/files) the strings.Replace doesn't work because the err from rest.InClusterConfig doesn't contain "invalid configuration".
Let's try to get this into v1.8.1 later this week
Fixes #
> 🌱 Improve clusterctl client config logic & error message

- docs/book/src/user/quick-start.md
- Update clusterctl version to v1.8.x in quick start
/cherry-pick release-1.8
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10472
> 📖 Update clusterctl version to v1.8.x in quick start

- CHANGELOG/v1.8.1.md
> 🚀 Release v1.8.1

- CONTRIBUTING.md
> 📖 Set 1.6 EOL date

- docs/release/release-tasks.md
> 📖 docs: fixup release-tasks, drop resolved issue

- .golangci.yml
> 🌱 Fix exclude for revision management in .golangci.yml

- docs/release/release-team.md
- docs/release/role-handbooks/ci-signal/README.md
- docs/release/role-handbooks/communications/README.md
- docs/release/role-handbooks/release-lead/README.md
Follow-up to:
- #10651
/assign sbueringer
Fixes #
> 📖 Sync back missing changes from original doc

- .github/ISSUE_TEMPLATE/kubernetes_bump.md
- Makefile
Forgot it in the previous CR bump PR
Fixes #
> 🌱 Bump setup-envtest to v0.19

- Tiltfile
- docs/book/src/developer/tilt.md
- docs/book/src/user/quick-start.md
- hack/ensure-kind.sh
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/framework/bootstrap/kind_provider.go
- test/go.mod
- test/go.sum
- test/infrastructure/kind/mapper.go
Manual cherry-pick of #11081
Part of:
- #10653
> 🌱 [release-1.8] Bump kind to v0.24.0

- api/v1beta1/condition_types.go
- api/v1beta1/zz_generated.openapi.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
- config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
- test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
- test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
- test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
According to the kubebuilder annotation, this field is optional. This PR just updates the docs to reflect this.
> 📖 `cluster.status.conditions.reason` may indeed be empty

- .github/ISSUE_TEMPLATE/release_tracking.md
- docs/release/role-handbooks/ci-signal/README.md
- docs/release/role-handbooks/release-lead/README.md
> 📖 update release docs + fix links in issue template

- OWNERS_ALIASES
This PR updates new v1.9 release team members in OWNERS files
/area release
>  🌱 Swap in new 1.9 RT members in OWNERS

- bootstrap/kubeadm/config/rbac/role.yaml
- bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
- config/rbac/role.yaml
- exp/addons/internal/controllers/clusterresourceset_controller.go
- exp/internal/controllers/machinepool_controller.go
- internal/controllers/cluster/cluster_controller.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
- internal/controllers/machineset/machineset_controller.go
- internal/controllers/topology/machinedeployment/machinedeployment_controller.go
- internal/controllers/topology/machineset/machineset_controller.go
- test/infrastructure/docker/config/rbac/role.yaml
- test/infrastructure/docker/exp/controllers/exp.go
- test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
- test/infrastructure/docker/internal/controllers/dockercluster_controller.go
- test/infrastructure/docker/internal/controllers/dockermachine_controller.go
- test/infrastructure/inmemory/config/rbac/role.yaml
- test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
- test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Manual cherry-pick of #11106
/area api
> [release-1.8] 🐛 re-add /finalizers subresource RBAC

- CHANGELOG/v1.8.2.md
> 🚀 Release v1.8.2

- Makefile
- Tiltfile
> 🌱 Bump to Go 1.22.7

- Makefile
- Tiltfile
This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11156
Fixes #
> [release-1.7]  🌱 Bump to Go 1.22.7

- CHANGELOG/v1.7.6.md
- Release note for v1.7.6
/area release
> 🚀 Release v1.7.6

- CHANGELOG/v1.8.3.md
- Release note for v1.8.3
/area release
> 🚀 Release v1.8.3

- .github/workflows/pr-verify.yaml
- hack/verify-pr-title.sh
I replace kubebuilder-release-tools with self-workflow.
Fixes #10925
> 🌱 replace kubebuilder-release-tools with new workflow

- docs/proposals/20210310-opt-in-autoscaling-from-zero.md
this change adds the implementation status section to the proposal with links to the research from september 2024 and meeting links where the research was discussed.
Fixes #
> 📖 update scale-from-zero proposal

- internal/runtime/client/client.go
> [release-1.8] 🌱 Reduce verbosity of logs when calling Runtime Extensions

- .github/PULL_REQUEST_TEMPLATE.md
PR #11208 renamed the developer guide. This PR adjusts sources to changes.
> 📖 Update the developer guide reference

- scripts/ci-e2e.sh
manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/11220
based on conversation here: https://github.com/kubernetes-sigs/cluster-api/issues/11209#issuecomment-2371557610
> [release-1.8] :seedling: test/e2e: decrease concurrency

- controllers/remote/cluster_cache_tracker.go
This PR adds a `CacheSyncPeriod` option to the `ClusterCacheTracker`. This enabled any reconcilers that are watching remote cluster objects to be reconciled periodically. 
Fixes #
/area clustercachetracker
> 🌱 add cacheSyncPeriod option to ClusterCacheTracker

- docs/community/20231018-karpenter-integration.md
This PR updates the details for the Karpenter feature group to be consistent with the current state of discussions and progress.
Fixes #
> :book: update karpenter feature group charter

- CHANGELOG/v1.7.7.md
Release note for v1.7.7
Fixes #
/area release
> 🚀 Release v1.7.7

- CHANGELOG/v1.8.4.md
- Release note for v1.8.4
Fixes #
/area release
> 🚀 Release v1.8.4

- README.md
Update contributor guide with the new mailing list address
> 📖 Update mailing list

- OWNERS
- OWNERS_ALIASES
It's been great - but I haven't had enough time to keep up as a maintainer over the last year since switching roles.
> 🌱 Remove killianmuldoon as maintainer

- Makefile
- Tiltfile
> 🌱 Bump Go to v1.22.8 version

- Makefile
- Tiltfile
Manual cherry pick of https://github.com/kubernetes-sigs/cluster-api/pull/11357
> [release-1.7] 🌱 Uplift Go 1.22.8

- api/v1beta1/cluster_types.go
- api/v1beta1/clusterclass_types.go
- api/v1beta1/machine_types.go
- api/v1beta1/machinedeployment_types.go
- api/v1beta1/machinehealthcheck_types.go
- api/v1beta1/machineset_types.go
- bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
- controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
- exp/addons/api/v1beta1/clusterresourceset_types.go
- exp/api/v1beta1/machinepool_types.go
- test/infrastructure/docker/api/v1beta1/dockercluster_types.go
- test/infrastructure/docker/api/v1beta1/dockermachine_types.go
- test/infrastructure/inmemory/api/v1alpha1/inmemorycluster_types.go
- test/infrastructure/inmemory/api/v1alpha1/inmemorymachine_types.go
- util/test/builder/v1beta2_transition.go
> 🐛 Fix panics in SetV1Beta2Conditions methods

- CHANGELOG/v1.9.0-beta.0.md
Add release notes for v1.9.0-beta.0
Fixes #
/area release
> 🚀 Release v1.9.0-beta.0

- CHANGELOG/v1.7.8.md
Add release notes for v1.7.8
Fixes #
/area release
> 🚀 Release v1.7.8

- controlplane/kubeadm/internal/controllers/status.go
- controlplane/kubeadm/internal/controllers/status_test.go
Improve available condition for KCP so that issues surfaces also when KCP is available
> 🌱 Refine v1beta2 Available condition in KCP

- test/framework/cluster_helpers.go
This PR should make it a lot easier to identify why Cluster deletion times out in e2e tests.
For example for this test case: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-latestk8s-main/1858161362505568256
It would print:
```
waiting for cluster deletion timed out:
condition: Deleting
message: * MachinePools: quick-start-ptw9et-mp-0-wxj56
```
This should also make it a lot easier to separate between MachinePool and other issues in k8s-triage
Fixes #
> 🌱 Improve cluster deletion timeout message in e2e test framework

- controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
- exp/api/v1beta1/v1beta2_condition_consts.go
> 🌱 Drop unused v1beta2 conditions and reasons

- CHANGELOG/v1.9.0-rc.1.md
Adds some commits to the release notes that were missed
> :seedling: Release notes `v1.9.0-rc.1` fix

- Makefile
- Tiltfile
> 🌱 Bump go to v1.22.10

- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
> 🌱 [release-1.9] Bump kubernetes release to v1.32.0-rc.1

- hack/observability/visualizer/kustomization.yaml
> 🌱 Bump CAPI Visualizer to v1.4.0

- CHANGELOG/v1.8.6.md
- Release notes v1.8.6
/area release
> 🚀 Release v1.8.6

- CONTRIBUTING.md
- docs/book/src/reference/versions.md
Part of https://github.com/kubernetes-sigs/cluster-api/issues/11092
> 📖 Set v1.7 EOL date and Update CoreDNS version table

- docs/book/src/reference/versions.md
- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
Requirements 
- k8s v1.32 GA release
Part of #11064
Fixes #
/area testing
> ✨ Bump Kubernetes in tests to v1.32.0 and claim support for v1.32

- internal/controllers/machine/machine_controller.go
Remove TODO comment which was solved in:
- #11490
Fixes #
/area machine
> 🌱 machine: remove solved todo comment

- docs/book/src/reference/versions.md
> 📖 book: fix versions.md for v1.32

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
Part of
- #11092
Fixes #
/area ci
> 🌱 github: update branches for weekly actions

- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump golang.org/x/crypto

- CONTRIBUTING.md
Fixes dead links.
The jobs overview got removed in:
- #11202 
Fixes #
> 📖 CONTRIBUTING.md fix dead links

- hack/observability/grafana/dashboards/runtime-extensions.json
- hack/observability/grafana/kustomization.yaml
> 🌱Add Runtime Extension dashboard

- CHANGELOG/v1.9.1.md
Kick's off release v1.9.1
Fixes #
/area release
> 🚀 Release v1.9.1

- .github/workflows/release.yaml
The current action hits https://github.com/softprops/action-gh-release/issues/556
Fixes #
/area ci
> 🌱 GITHUB: downgrade gh-release action

- CHANGELOG/v1.9.1.md
> 🚀  v1.9.1 trigger release again

- Makefile
This includes a commit which then only checks out only a single commit instead of downloading the whole repository.
This makes the promo process way faster (and even makes it work at all on my bad internet connection)
xref: https://github.com/kubernetes-sigs/promo-tools/pull/1409
I'm also asking upstream for a new release but no traction on that yet :-) (xref: [kubernetes.slack.com/archives/C2C40FMNF/p1734459016016769](https://kubernetes.slack.com/archives/C2C40FMNF/p1734459016016769) )
Fixes #
/area devtools
> 🌱 Bump kpromo to 5ab0dbc74b0228c22a93d240596dff77464aee8f

- CHANGELOG/v1.8.7.md
> 🚀 Release v1.8.7

- CHANGELOG/v1.9.3.md
> 🚀 Release v1.9.3

- CHANGELOG/v1.8.8.md
> 🚀 Release v1.8.8

- docs/proposals/20240916-improve-status-in-CAPI-resources.md
> 📖 Update deprecations in improve status proposal

- internal/controllers/cluster/cluster_controller_status.go
- internal/controllers/cluster/cluster_controller_status_test.go
- util/conditions/v1beta2/merge_strategies_test.go
> 🌱 Fix log messages in Cluster set status code + some minor unit test fixes

- docs/release/role-handbooks/release-lead/README.md
- test/e2e/clusterctl_upgrade_test.go
Follow up to late comments in #11647 
/area release
> 🌱 Follow up of 11647

- exp/topology/scope/hookresponsetracker.go
> 🌱 Fix formatting of blocking lifecycle hook condition message

- Makefile
- Tiltfile
- netlify.toml
Solves some security findings:
https://github.com/kubernetes-sigs/cluster-api/actions/runs/12867580479/job/35882362230
Fixes #
> 🌱 Bump go to v1.23.5

- CONTRIBUTING.md
- docs/book/src/reference/versions.md
- This PR updates the supported versions for the release cycle 1.10
> 📖 Update CAPI support and guarantees for v1.10

- docs/book/src/user/quick-start.md
Add information about dependence on ORC.
Fix whitespace.
Fixes #
> 📖 Update CAPO quick-start docs

- cmd/clusterctl/client/config/cert_manager_client.go
- docs/book/src/clusterctl/commands/init.md
- docs/book/src/developer/guide.md
- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
> [release-1.8] 🌱 Bump cert-manager to v1.16.3

- docs/release/releases/release-1.10.md
Follow up of https://github.com/kubernetes-sigs/cluster-api/pull/11786#pullrequestreview-2595123289
/area release
>  🌱 Align release 1.10 job creation with the new code freeze

- docs/book/src/developer/providers/migrations/v1.9-to-v1.10.md
Documents the changes from https://github.com/kubernetes-sigs/cluster-api/pull/11743
Fixes #
> 📖 docs: document test framework variable function renaming

- docs/book/src/developer/providers/migrations/v1.9-to-v1.10.md
> 📖 docs: document change for clustercache affecting tests

- api/v1beta1/machinedrainrules_types.go
- config/crd/bases/cluster.x-k8s.io_machinedrainrules.yaml
- internal/webhooks/machinedrainrules.go
- internal/webhooks/test/machinedrainrules_test.go
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/11353#discussion_r1827396180
Fixes #
> 🌱 Move MDR unique validations to CEL

- docs/book/src/user/quick-start.md
Update Vultr quick-start documentation
Fixes #
> :book: Update Vultr quick-start docs

- docs/release/role-handbooks/ci-signal/README.md
> 📖 Update CI release docs

- cmd/clusterctl/client/config/providers_client.go
- cmd/clusterctl/cmd/config_repositories_test.go
- docs/book/src/reference/providers.md
- docs/book/src/user/quick-start.md
Backport #11872 to release 1.9
> [release-1.9] 🌱 Change k0smotron repo location

- CONTRIBUTING.md
> 📖 Clarify when we would cut an emergency patch

- hack/ensure-kind.sh
- test/framework/bootstrap/kind_provider.go
- test/go.mod
- test/go.sum
- test/infrastructure/kind/mapper.go
> 🌱  Bump sigs.k8s.io/kind to v0.27.0

- docs/book/book.toml
> 📖 Split 2024 and 2025 agenda docs

- CHANGELOG/v1.8.11.md
- Release notes for v1.8.11
/area release
> 🚀 Release v1.8.11

- CHANGELOG/v1.10.0-beta.0.md
- Release notes for v1.10.0-beta.0
/area release
> 🚀 Release v1.10.0-beta.0

- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/e2e/data/cni/kindnet/kindnet.yaml
- test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.6/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.7/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.8/clusterclass-quick-start.yaml
- test/e2e/self_hosted.go
> [release-1.9] 🌱 e2e: ensure to always preload kindnetd to not hit ImagePullBackoff

- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/e2e/data/cni/kindnet/kindnet.yaml
- test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.6/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.7/clusterclass-quick-start.yaml
- test/e2e/self_hosted.go
> [release-1.8] 🌱 e2e: ensure to always preload kindnetd to not hit ImagePullBackoff

- scripts/ci-e2e-lib.sh
- test/e2e/config/docker.yaml
- test/e2e/data/cni/kindnet/kindnet.yaml
- test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
- test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
- test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
- test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
- test/e2e/data/infrastructure-docker/v1.6/clusterclass-quick-start.yaml
- test/e2e/self_hosted.go
> [release-1.7] 🌱 e2e: ensure to always preload kindnetd to not hit ImagePullBackoff

- docs/book/src/user/troubleshooting.md
rif. https://github.com/kubernetes-sigs/cluster-api/issues/11857
> 📖 Document SSA known issue

- test/infrastructure/docker/templates/cluster-template-in-memory.yaml
- test/infrastructure/docker/templates/clusterclass-in-memory.yaml
Templates just didn't work out of the box
Fixes #
> 🐛 Fix CAPD in-memory templates

- docs/book/src/user/quick-start.md
- test/infrastructure/docker/templates/cluster-template-development-mp.yaml
> 🐛 Fix worker machine count in CAPD template

- controlplane/kubeadm/internal/controllers/helpers.go
- exp/internal/controllers/machinepool_controller_phases.go
- internal/contract/bootstrap.go
- internal/contract/infrastructure_machine.go
- internal/controllers/cluster/cluster_controller_phases.go
- internal/controllers/clusterclass/clusterclass_controller.go
- internal/controllers/machine/machine_controller.go
- internal/controllers/machine/machine_controller_phases.go
- internal/controllers/machine/machine_controller_phases_test.go
- internal/controllers/machine/machine_controller_test.go
- internal/controllers/machinedeployment/machinedeployment_controller.go
- internal/controllers/machineset/machineset_controller.go
- util/conversion/conversion.go
- util/conversion/conversion_test.go
- util/test/builder/crds.go
- util/util.go
> ✨ Implement v1beta2 contract in Machine controller

- .github/workflows/pr-md-link-check.yaml
- docs/release/role-handbooks/ci-signal/README.md
manual cherry-pick of:
- #12034
/area release
> [release-1.10] 🌱 Use github.base_ref in markdown-link-check

- docs/book/src/introduction.md
> 📖 add release 1.9 book link

- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/11642 
Fixes #
> 🌱 Bump Kubernetes version used for testing to v1.33.0-rc.0

- .github/workflows/pr-md-link-check.yaml
- .github/workflows/weekly-md-link-check.yaml
Manual cherry-pick of dependabot bump.
Fixes mdlink to work again.
Fixes #
/area ci
> 🌱 [release-1.10] github: bump md-link check to 1.0.17

- .github/workflows/pr-md-link-check.yaml
- .github/workflows/weekly-md-link-check.yaml
Manual cherry-pick of #12077 
/area ci
> 🌱 [release-1.9] github: bump md-link check to 1.0.17

- .github/workflows/pr-md-link-check.yaml
- .github/workflows/weekly-md-link-check.yaml
Manual cherry-pick of #12077 
/area ci
> 🌱 [release-1.8] github: bump md-link check to 1.0.17

- Makefile
govulncheck is a tool to ensure vulnerability. I think it's important to recognize per CI.
Fixes #
> 🌱  Add govulncheck to ensure vulnerability

- CHANGELOG/v1.10.0.md
- Release notes for v1.10.0
part of: #11656 
/area release
> 🚀 Release v1.10.0

- CHANGELOG/v1.9.7.md
- Release notes for v1.9.7
part of: #11656 
/area release
> 🚀 Release v1.9.7

- test/e2e/config/docker.yaml
> 🌱 Use release artifacts for CAPI v1.10

- docs/book/src/reference/providers.md
Docs: 📖 update providers.md so that people know BYOH isn't actively maintained
N/A
> 📖 update providers.md so people know how providers are supported/maintained

- OWNERS_ALIASES
Hello team, I'd like to nominate myself to Cluster API reviewers. 
I have learned a lot from the Cluster API.
And I'd like to step up and continue contributing more with more responsibility and to learn more.
Fixes #
> 🌱  Add sivchari to Cluster API reviewers

- docs/book/src/user/quick-start.md
> 📖 docs: fix link for metal3 provider

- docs/book/src/introduction.md
I think this was missed somewhere. I think I remember that it's documented
Fixes #
> 📖 Update documentation note in introduction.md

- cmd/clusterctl/client/config/providers_client.go
- cmd/clusterctl/cmd/config_repositories_test.go
- docs/book/src/reference/providers.md
- docs/book/src/user/quick-start.md
following recent changes in the CNCF Sandbox scope for k0s, k0smotron will move together with k0s to Sandbox so it will again be under the same organization. Nothing is broken thanks to GH redirections. Sorry for the noise!
Fixes #
> 🌱 Change k0smotron repo location

- test/infrastructure/inmemory/pkg/server/mux.go
> 🐛 CAPIM: mux: fix error check

- OWNERS_ALIASES
I've been contributing to Cluster API since the beginning of 2020.
Initially I worked on projects like MHC, Spot instances across platforms and the original implemetation of the remote cluster caching.
I've been a reviewer for CAPI since March 2020 and have consistently been a member of the community calls and in-person syncs when possible over the last 5 years.
In recent times, I've been acting as an API reviewer for CAPI, provide guidance on API best practices and pushing projects like removing complex imports (controller-runtime) from the dependencies of our APIs and introducing Kube-API-Linter to the project to smooth the process of API review.
I would like to propose myself as an approver for the project based on my continued contributions to …
> 🌱 Add JoelSpeed to approvers

- .golangci-kal.yml
- hack/tools/.custom-gcl.yaml
> 🌱 Enable duplicatemarkers linter

- CHANGELOG/v1.9.8.md
* Release v1.9.8
part of: #12123
/area release
> 🚀 Release v1.9.8

- docs/release/role-handbooks/release-lead/README.md
When I tried to read through this sectin of the release lead tasks, I got confused due to some version numbers that were typos.  So here I attempt to re-write it to have more consitent version numbering for the steps and hopefully be easier to follow.
/area release
> 📖 Attempt to Clarify Prepare Main Branch section

- api/controlplane/kubeadm/v1beta1/conversion.go
- internal/apis/controlplane/kubeadm/v1alpha3/conversion.go
- internal/apis/controlplane/kubeadm/v1alpha4/conversion.go
> 🐛 KCP: fix nil pointer in conversion

- docs/release/releases/release-1.11.md
> 📖 Move v1.11.1 release date to after v1.34.0 release

- docs/book/src/developer/providers/contracts/clusterctl.md
- docs/book/src/developer/providers/contracts/control-plane.md
- docs/book/src/developer/providers/contracts/infra-cluster.md
- docs/book/src/developer/providers/contracts/infra-machine.md
- docs/book/src/developer/providers/contracts/overview.md
- docs/book/src/reference/providers.md
> 🌱 Small improvements to docs

- Makefile
- Tiltfile
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- netlify.toml
- test/go.mod
- test/go.sum
ref: https://github.com/kubernetes-sigs/cluster-api/actions/runs/15534048305/job/43983792975
Fixes #
> 🌱 Bump to Go v1.24.4, github.com/cloudflare/circl v1.6.1

- Makefile
- Tiltfile
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- netlify.toml
- test/go.mod
- test/go.sum
> [release-1.10] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1

- cmd/clusterctl/client/describe.go
- cmd/clusterctl/client/tree/discovery.go
- cmd/clusterctl/client/tree/tree.go
- cmd/clusterctl/client/tree/tree_test.go
- cmd/clusterctl/cmd/describe_cluster.go
- docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
- internal/util/tree/tree_test.go
- test/framework/cluster_helpers.go
Part of https://github.com/kubernetes-sigs/cluster-api/issues/11947
> ⚠️ Clusterctl describe defaults to v1beta2

- CHANGELOG/v1.10.3.md
- Release notes for v1.10.3
/area release
> 🚀 Release v1.10.3

- CHANGELOG/v1.9.9.md
- Release notes for v1.9.9
/area release
> 🚀 Release v1.9.9

- internal/webhooks/cluster.go
reconciled
Currently the webhook returns the following error (blob:https://prow.k8s.io/1b7bcd45-b05c-4db6-925b-3d276d617d6d)
```
failed to patch Cluster clusterclass-changes-0aeuk5/clusterclass-changes-rhd47s: admission webhook "validation.cluster.cluster.x-k8s.io" denied the request: Cluster.cluster.x-k8s.io "clusterclass-changes-rhd47s" is invalid: []: Invalid value: "": could not compare ClusterClass compatibility: desired ClusterClass must not be nil
```
After this change it returns: (tested with kubectl edit)
```
```
Fixes #
> 🌱 Improve error message if rebase fails because target ClusterClass is not reconciled

- bootstrap/kubeadm/internal/cloudinit/files.go
> 🐛 Fix rendering of .Append = false in CABPK

- CHANGELOG/v1.10.4.md
- Release notes for v1.10.4
/area release
> 🚀 Release v1.10.4

- CHANGELOG/v1.11.0-beta.0.md
- Release notes for v1.11.0-beta.0
/area release
> 🚀 Release v1.11.0-beta.0

- .golangci-kal.yml
- hack/tools/.custom-gcl.yaml
> 🌱 Bump KAL and remove enum exclude

- CHANGELOG/v1.11.0-beta.1.md
- Release notes for v1.11.0-beta.1
/area release
> 🚀 Release v1.11.0-beta.1

- exp/runtime/server/server.go
- internal/runtime/client/client.go
- internal/runtime/client/client_test.go
- main.go
> ✨ Add mTLS support to runtime extension server and client

- docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
Note, it also includes changes from https://github.com/kubernetes-sigs/cluster-api/pull/12506
/area documentaiton
> 📖 Improve migration doc

- internal/topology/upgrade/clusterctl_upgrade_test.go
> 🐛 Fix flakes in TestAPIAndWebhookChanges unit test

- api/addons/v1beta1/clusterresourceset_types.go
- api/addons/v1beta1/clusterresourcesetbinding_types.go
- api/addons/v1beta2/clusterresourceset_types.go
- api/addons/v1beta2/clusterresourcesetbinding_types.go
- api/core/v1beta1/cluster_types.go
- api/core/v1beta1/clusterclass_types.go
- api/core/v1beta1/condition_consts.go
- api/core/v1beta1/condition_types.go
- api/core/v1beta1/machine_types.go
- api/core/v1beta1/machinedeployment_types.go
- api/core/v1beta1/machinehealthcheck_types.go
- api/core/v1beta1/machinepool_types.go
- api/core/v1beta1/machineset_types.go
- api/core/v1beta2/cluster_types.go
- api/core/v1beta2/clusterclass_types.go
- api/core/v1beta2/condition_types.go
- api/core/v1beta2/machine_types.go
- api/core/v1beta2/machinedeployment_types.go
- api/core/v1beta2/machinehealthcheck_types.go
- api/core/v1beta2/machinepool_types.go
- api/core/v1beta2/machineset_types.go
- api/core/v1beta2/v1beta1_condition_consts.go
- api/runtime/v1alpha1/extensionconfig_types.go
- api/runtime/v1beta2/extensionconfig_types.go
> 🌱 Remove unused ANCHOR comments

- api/addons/v1beta2/clusterresourceset_types.go
- api/addons/v1beta2/clusterresourcesetbinding_types.go
- api/bootstrap/kubeadm/v1beta2/kubeadmconfig_types.go
- api/bootstrap/kubeadm/v1beta2/kubeadmconfigtemplate_types.go
- api/controlplane/kubeadm/v1beta2/kubeadm_control_plane_types.go
- api/controlplane/kubeadm/v1beta2/kubeadmcontrolplanetemplate_types.go
- api/core/v1beta2/cluster_types.go
- api/core/v1beta2/clusterclass_types.go
- api/core/v1beta2/machine_types.go
- api/core/v1beta2/machinedeployment_types.go
- api/core/v1beta2/machinehealthcheck_types.go
- api/core/v1beta2/machinepool_types.go
- api/core/v1beta2/machineset_types.go
- api/runtime/v1beta2/extensionconfig_types.go
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
- bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
- config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
- config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- config/crd/bases/cluster.x-k8s.io_clusters.yaml
- config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
- config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- config/crd/bases/cluster.x-k8s.io_machines.yaml
- config/crd/bases/cluster.x-k8s.io_machinesets.yaml
- config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
- controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
- docs/proposals/20240916-improve-status-in-CAPI-resources.md
rif https://github.com/kubernetes-sigs/cluster-api/issues/10852
/area api
> 🌱 Set print columns for v1beta2 types

- controllers/clustercache/cluster_accessor.go
- controllers/clustercache/cluster_accessor_test.go
- controllers/clustercache/cluster_cache.go
- controllers/clustercache/cluster_cache_fake.go
- controllers/clustercache/cluster_cache_test.go
- controlplane/kubeadm/internal/controllers/controller.go
- controlplane/kubeadm/internal/controllers/controller_test.go
- internal/controllers/cluster/cluster_controller.go
- internal/controllers/cluster/cluster_controller_status.go
- internal/controllers/cluster/cluster_controller_status_test.go
- internal/controllers/machine/machine_controller_status.go
- internal/controllers/machine/machine_controller_status_test.go
> 🐛 Fix condition handling during controller start

- docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
/area provider/controlplane-kubeadm
> 📖 Document new certificateValidity fields

- test/e2e/clusterctl_upgrade.go
> 🌱 Add resource version check to clusterctl upgrade tests

- test/framework/resourceversion_helpers.go
This PR prevents E2E test to fail when a token refresh happens for machine pools while ResourceVersion stability is being checked
> 🌱 Fix ResourceVersion flake for MachinePools

- test/extension/handlers/topologymutation/handler.go
- test/extension/handlers/topologymutation/handler_test.go
WIP => Currently contains #12545 
Part of #11947
> 🌱 Set extraArgs in test extension

- .golangci-kal.yml
- hack/tools/.custom-gcl.yaml
> ✨ Add conflicting markers linter

- docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
> 📖 Improve v1.10-to-v1.11 migration doc

- docs/book/src/developer/core/logging.md
This PR is just a follow up on the comment https://github.com/kubernetes-sigs/cluster-api/pull/12572#issuecomment-3149661296
Fixes #
> 📖 Update book to add guidelines for logging Kubernetes resource names

- .github/workflows/pr-golangci-lint.yaml
- .golangci.yml
- bootstrap/kubeadm/types/doc.go
- bootstrap/kubeadm/types/utils.go
- bootstrap/kubeadm/types/utils_test.go
- hack/tools/.custom-gcl.yaml
- hack/tools/internal/tilt-prepare/main.go
- hack/tools/release/notes/github.go
- internal/test/envtest/environment.go
- test/framework/clusterctl/client.go
- test/framework/docker_logcollector.go
- test/framework/kubernetesversions/template.go
- test/framework/suite_helpers.go
- test/infrastructure/inmemory/pkg/server/api/handler.go
- test/infrastructure/inmemory/pkg/server/mux.go
Update golangci-lint to v2.3.0
Fixes #
> 🌱chore: Update golangci-lint to v2.3.0

- docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
Fixes #
/label release-note-none
> 🌱 Fix Typo in v1.10-to-v1.11.md

- test/e2e/data/kubetest/dualstack.yaml
xref: https://kubernetes.slack.com/archives/C7J9RP96G/p1754649416231049?thread_ts=1751991861.631429&cid=C7J9RP96G
Fixes #12449
> 🌱 Enable IPv6 test again

- .golangci-kal.yml
- hack/tools/.custom-gcl.yaml
> 🌱 Bump KAL & drop schemaless excludes

- CHANGELOG/v1.9.11.md
Release notes for v1.9.11
/area release
> 🚀 Release v1.9.11

- CHANGELOG/v1.10.5.md
Release notes for v1.10.5
/area release
> 🚀 Release v1.10.5

- CHANGELOG/v1.11.0.md
- Release notes for v1.11.0
/area release
> 🚀 Release v1.11.0

- test/e2e/config/docker.yaml
- test/infrastructure/docker/examples/machine-pool.yaml
- test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
- test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
- test/infrastructure/docker/examples/simple-cluster.yaml
> ✨ Bump Kubernetes version used for testing to v1.34.0-rc.2

- test/e2e/clusterctl_upgrade.go
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/common.go
- test/e2e/e2e_suite_test.go
> 🌱 Get kind mgmt cluster logs in clusterctl upgrade test

- bootstrap/kubeadm/main.go
- controlplane/kubeadm/main.go
- main.go
- test/extension/main.go
- test/infrastructure/docker/main.go
> 🌱 Log version and git commit on controller start

- .github/ISSUE_TEMPLATE/kubernetes_bump.md
> 📖 Update Kubernetes bump issue template

- CHANGELOG/v1.11.1.md
- Release notes for v1.11.1
/area release
> 🚀 Release v1.11.1

- CHANGELOG/v1.11.2.md
- Release notes of v1.11.2
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/12771
/area release
> 🚀 Release v1.11.2
