docs/book/src/developer/testing.md
hack/tools/log-push/main.go

This PR extends log-push to:
* also parse the controller k/v pair (so we get a button for it in Loki)
* preserve the timestamp as original_ts so we are still able to correlate the logs to certain other events in e2e tests, etc.
Fixes #

🌱 log-push: preserve original timestamp, parse controller too

---

OWNERS_ALIASES

PR to add myself as a reviewer under clusterctl reviewer alias 🙂

🌱 add ykakarap to clusterctl reviewers

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go
docs/book/src/developer/providers/machine-infrastructure.md
docs/book/src/developer/providers/v1.1-to-v1.2.md
test/framework/controlplane_helpers.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Currently the KCP  controller are blocked if the `InfrastructureCluster` is not ready. This leads to cases where if the infrastructure is never ready because of any reason (Example: resource limit reached in AWS) one cannot even delete the cluster - the operation is blocked at deleting KCP. This PR fixes the reconciler so that we no longer blocking in such a case.
This PR also fixes a similar problem with blocking DockerMachine reconciliation if infrastructure is not ready.
Fixes #6006

🐛 prevent blocking of KCP and DockerMachine controllers

---

exp/internal/controllers/machinepool_controller_noderef.go
exp/internal/controllers/machinepool_controller_noderef_test.go

This fixes MachinePool reconciliation when an empty providerIDList is
given. Previously it would always return an error in this case,
preventing the MachinePool readyReplicas etc. to go to 0.
kubernetes-sigs/cluster-api-provider-aws#3253 requires this fix because otherwise the e2e test does not complete.

:bug: fix: no nodeRefs when empty providerIDList is ok

---

util/version/version.go

/kind bug
Rif #4938 
cc @sbueringer

🐛 util/version: Add option to compare without prereleases

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/cmd/config_repositories_test.go
docs/book/src/reference/providers.md

Talos Systems is now Sidero Labs and we just renamed our github org.
This PR updates all of the references to make sure they align with the
new org name. Saw an issue where clusterctl couldn't follow the
redirects to the yaml assets, which appears to also occur when manually
curling (assuming a github bug).
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

:seedling: update talos/sidero references

---

controllers/remote/cluster_cache_reconciler.go
controllers/remote/cluster_cache_reconciler_test.go
controlplane/kubeadm/main.go
internal/controllers/cluster/suite_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/suite_test.go
main.go

As we are always using the logger from context we don't have to set the Log field anymore, so let's drop it.
Note: before this PR the fields was written a few times, but never read.
Fixes #

🌱 ClusterCacheTracker: drop unused Log field

---

exp/api/v1beta1/machinepool_webhook.go
exp/api/v1beta1/machinepool_webhook_test.go

**What this PR does / why we need it**: In the past we've added kube semver validations to KCP, MachineDeployment, Machines, and MachineSets. For some reason we missed MachinePool. This PR adds webhook defaulting to add the "v" prefix when it's missing and validation to make sure MachinePool version is valid, as well as unit tests.
Here's the equivalent changeset for MachineSets: https://github.com/kubernetes-sigs/cluster-api/pull/5406/files
Fixes #

🐛  Ensure MachinePool Version is a valid Kubernetes version

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/client/config_test.go
cmd/clusterctl/cmd/config_repositories_test.go

When CAPA graduated EKS support we combined the the separate EKS
providers into the main AWS infra provider. So this change removed the
separate `aws-eks` controlplane and bootstrap providers from
**clusterctl**.
This is a replacement for #5073 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2656

🌱 chore: removing old aws-eks providers from clusterctl

---

.github/workflows/golangci-lint.yml
internal/webhooks/cluster_test.go
internal/webhooks/clusterclass_test.go
util/container/image.go

Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
- Bump to golangci-lint v1.44.2
- Fix lint findings
- Revert panic workaround
Fixes #6163

:sparkles:Bump to golangci-lint v1.45.2

---

.github/dependabot.yml

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.
Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot
GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
Similar to https://github.com/kubernetes/minikube/pull/13770 …

:seedling: Included githubactions in the dependabot config

---

.github/workflows/dependabot.yml

Fix an issue in the dependabot config where it was using out of date make target. Dependabot was reactivated in #6340 
These targets are not actually really necessary given we're only using dependabot for github actions right now, but I'd prefer to leave them for now as we think about whether to add new directories to dependabot.

:seedling:  update dependabot modules command

---

api/v1beta1/machineset_webhook.go

Signed-off-by: Sachin Kumar Singh <sachinkumarsingh092@gmail.com>
Update the `MachinSet` webhook to use `fieldPath.Child` where appropriate instead of redefining paths for each error.
Realated to #6249

🌱 Add field.Path aggregation for MachineSet webhook

---

util/util.go
util/util_test.go

Fix a nil pointer in the UnstructuredUnmarshalField function which gets thrown if the Object supplied is equal to nil.
Fixes #6333

:bug:  Add nil pointer check in UnstructuredUnmarshalField

---

.github/dependabot.yml

Add seedling commit prefix to dependabot PRs to allow it to pass verify checks.
Examples of this at work in my fork: https://github.com/killianmuldoon/cluster-api/pulls

:seedling: Add seedling commit prefix to dependabot

---

.github/workflows/golangci-lint.yml
Makefile

Add explicit version for the golangci lint go version to the release 1.1 branch. Mirrors changes made in #6356

:seedling:  Update golangci-lint action

---

.github/workflows/golangci-lint.yml
Makefile

Add explicit version for the golangci lint go version to the release 0.4 branch. Mirrors changes made in https://github.com/kubernetes-sigs/cluster-api/pull/6356

:seedling: Update golangci-lint action

---

api/v1alpha4/conversion_test.go
api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
docs/proposals/20210526-cluster-class-and-managed-topologies.md
internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
internal/topology/variables/cluster_variable_defaulting_test.go
internal/topology/variables/cluster_variable_validation_test.go
internal/topology/variables/clusterclass_variable_validation.go
internal/topology/variables/clusterclass_variable_validation_test.go
internal/topology/variables/schema.go
internal/topology/variables/schema_test.go
internal/webhooks/clusterclass_test.go

Adds support for map variables. See #6370 for more details.
Fixes #6370

🌱 ClusterClass: implement map variables

---

.github/workflows/golangci-lint.yml
internal/webhooks/cluster_test.go
internal/webhooks/clusterclass_test.go
util/container/image.go

Downgrade golanglint-ci version to a state where gci linter autofix is in working order. This should be reverted and upgrades should continue as soon as a release with autofix enabled is merged.
Related to #6350 
This should be reverted once there's a working path for the gci linter, or an alternative is implemented.

:bug:  Downgrade golangci-lint to address gci autolint issues

---

api/v1beta1/machine_webhook.go

**What this PR does / why we need it**: Update usage of `field.Path` in Machine webhook as part of an effort to make core webhook validation more consistent.
Fixes #6249

🌱 Add field.Path aggregation for Machine webhook

---

api/v1beta1/machinehealthcheck_webhook.go

**What this PR does / why we need it**: Update usage of `field.Path` in MachineHealthCheck webhook as part of an effort to make core webhook validation more consistent.
Fixes #6249

🌱 Add field.Path aggregation for MachineHealthCheck webhook

---

go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Update CoreDNS corefile migration tool to 1.0.15. 
This version supports updating coreDNS to 1.9.1 and supports a minimum version of 1.3.1.

:seedling: Update coredns corefile migration to 1.0.15

---

api/v1beta1/machinedeployment_webhook.go
exp/api/v1beta1/machinepool_webhook.go

Updates the MachineDeployment and MachinePool Webhooks to use the fieldPath.Child 
Fixes Part of #6249

🌱  Add field.Path for  MachineDeployment and MachinePool Webhooks

---

.github/dependabot.yml

Adds an allow for the coredns corefile to our dependabot config. This change will ensure we get automated updates to this library and is introduced in response to: https://github.com/kubernetes-sigs/cluster-api/issues/2599

:seedling:  Add coredns corefile to dependabot config

---

controlplane/kubeadm/api/v1alpha3/condition_consts.go
controlplane/kubeadm/api/v1alpha4/condition_consts.go
controlplane/kubeadm/api/v1beta1/condition_consts.go

`Whe` -> `When`.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>

:book: Correct a typo in the `MachinesSpecUpToDate` condition comment

---

docs/book/src/developer/architecture/controllers/control-plane.md

Update a v1alpha3 example of a KubeadmControlPlane in the controllers part of the CAPI book

:book: Update controlplane example in book

---

docs/book/src/clusterctl/commands/init.md

This PR update the command used to check for provider expected variables to be more explicit as we need to specify type provider for proper functionality.

📖 Updated command to check provider expected variables

---

docs/book/src/user/quick-start.md

Adding documentation for IBM Cloud provider
Fixes #

 📖  Add IBM Cloud provider quick start

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

This PR bumps the default version of cert-manager used to `v1.7.2` from `v1.5.3`.
Fixes #6055

🌱 update cert-manager to v1.7.2

---

bootstrap/util/configowner_test.go

Fix linting issues that are currently causing test failures in unrelated PRs. Issues were introduced by #6395, but I don't understand why they did not fail the checks back then.

🌱 fix linting

---

docs/book/theme/css/custom.css

The current CSS only supports up to 10 tabs, but we already have some selections with 13 tabs. This adds CSS rules for up to 20 tabs.
This does not really fix the root cause, which is the static css for a limited number of tabs, if anyone knows a better solution, I am happy to close this PR and let someone else implement a proper fix.
Fixes #6434

📖 allow up to 20 tabs in book

---

Makefile

* Fixes regression for make help introduced in #5741
fixes #6444
**What else to add**
Before:
```
$ make
...
clean-release-git                              Restores the git files usually modified during a release
clean-generated-conversions                    Remove files generated by conversion-gen from the mentioned dirs. Example SRC_DIRS="./api/v1alpha4"
hack/tools:
```
After:
```
$ make
...
clean-release-git                              Restores the git files usually modified during a release
clean-generated-conversions                    Remove files generated by conversion-gen from the …
```

🌱 Makefile: re-enable hack/tools on make help

---

test/framework/clusterctl/clusterctl_helpers.go

This PR sets the appropriate wait input configuration during E2E tests when waiting for machine pool provisioning.
Fixes #

🐛 use WaitForMachinePools to configure machine pool test waits

---

.markdownlinkcheck.json
docs/book/src/clusterctl/provider-contract.md

📖 book: fix link to GitHub doc

---

docs/book/src/SUMMARY.md
docs/book/src/security/index.md
docs/book/src/security/pod-security-standards.md
docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
docs/book/src/user/quick-start.md
test/infrastructure/docker/templates/cluster-template-development-topology.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

Adds a [baseline pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline) which gets enforced at cluster level.
Resolves parts of #6329
Open for discussion for me:
Wether or not add it to the default ClusterClass or add a separate ClusterClass e.g. called `capi-quickstart-secure`.
A second ClusterClass would have the con of duplicating the normal quick-start ClusterClass with lots of duplicated content.
If adding the PSS to the default cluster class results into issues we could also work the other way around and add a "insecure" ClusterClass named …

:sparkles: Apply PodSecurityStandard in Secure Cluster Class

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go

In response to a test flake, this PR introduces retry tolerance to GitHub API-dependent operations in clusterctl.
The passing (unchanged) UT should prove functional equivalence between this change and existing (no retry) behavior.
Reference test flake:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-19-1-20-main/1516508031641194496
Fixes #

🐛 clusterctl: retry github i/o operations

---

config/crd/kustomization.yaml

Follow-up PR to the PR which added the CRD to include the CRD in the generated core manifest
Fixes #

🐛 RuntimeSDK: include ExtensionConfig CRD in generated core manifest

---

test/infrastructure/docker/templates/cluster-template-development.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

With our current templates it's not possible to create a cluster on which CAPD can also run on worker nodes.
Found here: https://github.com/kubernetes-sigs/cluster-api/issues/6321#issuecomment-1110540975
Fixes #

🌱 CAPD: Add docker mount to worker nodes

---

Makefile
scripts/go_install.sh

**What this PR does / why we need it**: Updates `kpromo` to the latest release so we can take advantage of 1) filtering by promotion by image to exclude CAPD images and 2) sorting by tag instead of by digest.
https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.4.1
Test PR to promote fake v0.99.99 tag from this branch: https://github.com/kubernetes/k8s.io/pull/3683/files
Fixes #

🌱  Update promote-images to filter by image and sort by tag

---

go.mod
util/record/recorder.go

The strings.Title function is being deprecated in Go 1.18 due to issues
with its handling of certain unicode sets. The recommended replacement
is cases.Title.
We only have one location where this was being used in a utility
function. This updates that instance to use the new recommendations.
https://tip.golang.org/doc/go1.18#minor_library_changes

🌱 Replace deprecated strings.Title with cases.Title

---

test/framework/cluster_proxy.go

This is a follow-up from PR #6431 that actually enables retries when receiving an error establishing a k8s controller-runtime client during E2E tests. Without this change the `wait.PollImmediate` implementation just returns from the first error response, essentially making it a thin wrapper that doesn't add any value.
Fixes #

🌱 test: actually retry controller-runtime client instantiation

---

Makefile
config/rbac/role.yaml
exp/runtime/controllers/alias.go
exp/runtime/controllers/doc.go
exp/runtime/internal/controllers/doc.go
exp/runtime/internal/controllers/extensionconfig_controller.go
main.go

This PR adds a skeleton controller to handle the ExtensionConfig object added in #6383. This controller will eventually be used to handle status updates to the ExtensionConfig CRD.
Note: This PR includes #6383 and should not be merged until that PR is merged. This PR will require a rebase before merging.
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/6330

✨ RuntimeSDK: Add extension config controller skeleton

---

docs/book/src/developer/tilt.md

Adds documentation about Tiltfile syntax highlighting.
Fixes #

📖 book: Add note about Tiltfile syntax highlighting

---

test/infrastructure/docker/templates/cluster-template-development.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

PR #6460 causes the worker nodes to default to docker as container runtime. The `kubeadm join` command fails on the worker node because the kubelet tries to use docker as runtime. Therefore the worker node will never be added to the cluster.
Adding the containerd CRI socket to the join configuration of the worker node will fix this.
Fixes #

🐛 CAPD: Add containerd socket to worker nodes

---

test/framework/pod_helpers.go

This PR removes the error exception in the test helper func `WaitForPodListCondition` that is fired when zero pods are returned from the list. There are two reasons for this:
1. This function tolerates unmet pod list conditions and retries by design. It's possible that the wait can be initiated before a pod is present, and so an empty list is a valid retryable result.
2. Zero pods in the list is in fact a valid condition that may be expressed. In a scenario where pods (or deployments or daemonsets, etc) are deleted, setting up a wait to validate that the pod count reaches zero is a possible use case of this func.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

🌱 test: tolerate zero pods in WaitForPodListCondition

---

internal/controllers/machine/machine_controller.go
util/predicates/cluster_predicates.go
util/predicates/cluster_predicates_test.go

The current implementation for `ClusterUpdateUnpaused` is filtering all
cluster updates except for the case when `spec.paused` is updated from
`true` to `false`.
As all `Cluster` updates do not trigger `Machines` reconcilation,
setting `ControlPlaneInitialized` to `True` does not start workload nodes
watch in `MachinesController`.
That leads to cluster deployment being stuck and hanging for 15 minutes.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>

:bug: Fix cluster reconcilation predicates

---

internal/runtime/catalog/catalog.go
internal/runtime/registry/doc.go
internal/runtime/registry/registry.go
internal/runtime/registry/registry_test.go

Co-authored-by: fabriziopandini <fpandini@vmware.com>
Credits to Fabrizio who did the initial implementation in our POC.
Part of #6330

✨ RuntimeSDK: add registry

---

cmd/clusterctl/cmd/describe_cluster.go
cmd/clusterctl/cmd/describe_cluster_test.go
go.mod
go.sum
hack/tools/go.sum
test/go.sum

github.com/olekukonko/tablewriter is added in PR #5893 so it used to replace github.com/gosuri/uitable in clusterctl describe command. Tests have been changed to accommodate for the same
Fixes #5941 
Have bit of an issue with my system would like to use GitHub tests

🌱  Replace uitable with tablewriter in clusterctl describe cluster command

---

cmd/clusterctl/cmd/root.go
docs/book/src/clusterctl/configuration.md

This PR adds support to disable clusterctl from checking for updates. This is useful when clusterctl is used in a air-gapped environments. 
Usage: To disable the version checking add `DISABLE_VERSIONCHECK: "true"` to `clusterctl.yaml` or set an environment variable `DISABLE_VERSIONCHECK="true"`.
Fixes #6381

🌱 clusterctl: support disable version check

---

.markdownlinkcheck.json
docs/book/src/reference/providers.md

A small docs change to add CAPMVM to the list of providers.
I also increased the timeout on the markdown links checker as it was failing checking some links due to timeout.
Fixes #

 🌱 docs: add capmvm to the providers list

---

exp/addons/internal/controllers/clusterresourceset_helpers.go

Change variable in code to make object created by Cluster Resource Set will follow priority
Fixes #6500

🐛 ClusterResourceSet: apply objects in sorted order

---

internal/webhooks/cluster_test.go
internal/webhooks/clusterclass_test.go
internal/webhooks/runtime/extensionconfig_webhook.go
internal/webhooks/runtime/extensionconfig_webhook_test.go
internal/webhooks/util/util.go

Co-authored-by: Yuvaraj Kakaraparthi <kakaraparthy@vmware.com>
Co-authored-by: Christian Schlotter <schlotterc@vmware.com>
Adds defaulting and advanced validation for Runtime SDK's ExtensionConfig.
Credits to Yuvaraj who did the implementation.
Part of  https://github.com/kubernetes-sigs/cluster-api/issues/6330

✨ webhooks: defaulting and validation for ExtensionConfig

---

go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Update the migration corefile to version 1.0.16 which supports supports Corefile migrations through CoreDNS v1.9.2
c/f #6523

:seedling: Update migration corefile to 1.0.16

---

.github/workflows/golangci-lint.yml

Manual update of the golangci-lint action to version 3.2. The recent dependabot attempts to update this dependency resulted to a change in the OpenAPI definition.
c/f #6522

:seedling:  Update golangci-lint action to 3.2

---

cmd/clusterctl/cmd/generate_provider.go

The describe flag is used to show the provider's available environment variables, clusterctl should not interpolate the config when used.
Fixes #6316

:bug: skip templating step if `describe` flag is used

---

internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go

Delete ControlPlane InfrastructureMachineTemplates on a best effort basis once they have been rotated during a reconciliation loop.
Fixes #6375
@chrischdi @fabriziopandini

:bug: Delete unused ControlPlane InfrastructureMachineTemplates on rotation

---

docs/book/src/developer/providers/machine-infrastructure.md

:seedling: Add docs for conditions in machine infra provider implementer

---

cmd/clusterctl/api/v1alpha3/provider_type.go
cmd/clusterctl/client/init.go
cmd/clusterctl/client/init_test.go

This PR make the `clusterctl init` command idempotent. 
Fixes #6471

🌱 make clusterctl init idempotent

---

test/framework/cluster_helpers.go
test/framework/cluster_proxy.go
test/framework/cluster_topology_helpers.go
test/framework/clusterresourceset_helpers.go
test/framework/controlplane_helpers.go
test/framework/deployment_helpers.go
test/framework/machine_helpers.go
test/framework/machinedeployment_helpers.go
test/framework/machinepool_helpers.go
test/framework/namespace_helpers.go

This PR is the result of an audit of retryable (e.g., network I/O-dependent) errors in the test/framework package. For every retryable error that is currently failing via a ginkgo `Expect` assertion, we replace it with a ginkgo `Eventually` wrapper instead which retries for up to 1 minute (according to a 3 second retry interval after every failure).
This will eliminate flakes during test runs, at the cost of increasing failed test run times by 1 minute.
related to #2955

🌱 retryable errors in test/framework

---

scripts/go_install.sh

Silences the `No such file or directory` message when running `make test` in a new repo or after running `make clean` to reduce noise. 
On my machine:
```shell
make test
(...)
rm: cannot remove '/home/oscar/repo/github/cluster-api/hack/tools/bin/setup-envtest*': No such file or directory
(...)
```

🌱 Silence error in go_install.sh when trying to remove nonexisting files

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

This change is needed as building fails. According to https://github.com/distribution/distribution/releases/tag/v2.8.1,
there are no changes between 2.8.0 and 2.8.1, the sole reason of having
this new version is to fix the go.sum issue.

🐛 Update docker distribution to fix go sum error

---

config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
docs/proposals/20220221-runtime-SDK.md
exp/runtime/api/v1alpha1/extensionconfig_types.go

Update types and runtimeSDK proposal to make the ExtensionConfig Cluster scoped. This was the intention from the design stage, but was never explicit in the proposal, and was incorrectly implemented in the initial version of the type.

:seedling:  Change ExtensionConfig to Cluster scoped

---

CONTRIBUTING.md
docs/book/src/developer/providers/v0.3-to-v0.4.md
docs/book/src/developer/providers/v0.4-to-v1.0.md

Looks like `:warning:` isn't rendered in the Contributing Guidelines document (as shown below) so I suggest replacing it with the ⚠️ emoji. As a small side note: the commit message and diff preview look a little odd since Github seems to always render `:warning:` as  ⚠️.
https://cluster-api.sigs.k8s.io/contributing#codebase-and-go-modules

📖 Replace :warning: with ⚠️  in Contributing Guidelines documentation

---

test/e2e/cluster_upgrade_test.go

The cluster upgrade test didn't detect the Kubernetes version correctly.
The `e2eConfig.Variables` map only contains the values from the e2e config / docker.yaml, while `GetVariable` also takes env variables into account.
Concrete error case:
* ci job v1.24 => v1.25 latest
* Actual KubernetesVersionUpgradeFrom was v1.24.1
* Test detected v1.23.6 from e2e config and ignored env var
* Test chose to use the cgroupfs flavor instead of the regular one
* cgroupfs doesn't work with v1.24.1
* grep for `upgrades-cgroupfs` in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/6543/pull-cluster-api-e2e-workload-upgrade-1-24-latest-main/1530078512034091008/build-log.txt …

🐛 e2e: fix cgroup branching in cluster upgrade test

---

config/rbac/role.yaml
exp/runtime/api/v1alpha1/extensionconfig_types.go
exp/runtime/controllers/alias.go
exp/runtime/internal/controllers/extensionconfig_controller.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/runtime/internal/controllers/suite_test.go
exp/runtime/internal/controllers/warmup.go
exp/runtime/internal/controllers/warmup_test.go
internal/test/envtest/environment.go
main.go

Adds an implementation of the ExtensionConfig controller. This controller is responsible for:
1) Warming up the registry when the controller starts
2) Discovering newly created and updated extensions
3) Removing Deleted extensions from the registry 
4) Adding conditions that surface the outcome of the most recent Discovery call (Succeeded or Failed with some reason)
Part of #6330

 :seedling: integrate controller for ExtensionConfig

---

Makefile

Just fixes a spelling mistake in the Makefile.

🌱 Fix misspelled word in Makefile

---

.golangci.yml
exp/runtime/controllers/alias.go
exp/runtime/hooks/api/v1alpha1/discovery_types.go
exp/runtime/hooks/api/v1alpha1/groupversion_info.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/runtime/internal/controllers/warmup_test.go
hack/tools/runtime-openapi-gen/main.go
internal/runtime/catalog/test/catalog_test.go
internal/runtime/catalog/test/v1alpha1/conversion.go
internal/runtime/catalog/test/v1alpha1/conversion_test.go
internal/runtime/catalog/test/v1alpha1/fake_types.go
internal/runtime/catalog/test/v1alpha2/fake_types.go
internal/runtime/client/client.go
internal/runtime/client/client_test.go
internal/runtime/registry/registry.go
internal/runtime/registry/registry_test.go
internal/test/envtest/environment.go
main.go

This PR standardizes import names for RuntimeSDK packages.
Fixes #

🌱 RuntimeSDK: standardize import names

---

docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/developers.md
docs/book/src/clusterctl/provider-contract.md

Just some minor spelling and grammar fixes in the documentation.

📖 Fix grammar and spelling in clusterctl documentation

---

internal/test/builder/bootstrap.go
internal/test/builder/builders.go
internal/test/builder/controlplane.go
internal/test/builder/crds.go
internal/test/builder/infrastructure.go
internal/test/builder/remediation.go
internal/test/envtest/environment.go

This PR introduces new CRDs which are meant to get used in tests:
* `TestBootstrapConfigTemplate`
* `TestBootstrapConfig `
* `TestControlPlane`
* `TestInfrastructureCluster`
* `TestInfrastructureMachineTemplate`
* `TestInfrastructureMachine`
Compared to their `Generic*` equivalents the `Test*` CRDs are typed (instead of being untyped).
Using typed CRDs in tests instead of untyped ones prevents unexpected behaviour in tests when using Server-Side apply with regards to how managed managed-fields get handled.
part of https://github.com/kubernetes-sigs/cluster-api/issues/6320

✨ Introduce typed CRDs for testing purposes to replace the untyped ones

---

OWNERS_ALIASES

Syncs the OWNER_ALIASES file of release-1.1 with main. I think it makes sense to have them sync as the reviewer/approver rights are CAPI-wide not per-release. 
Note:
* release-1.1 is our only supported release, so I wouldn't backport this further.
Fixes #

🌱 Sync owners alias on release-1.1 with main

---

config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
exp/runtime/api/v1alpha1/extensionconfig_types.go
internal/runtime/registry/registry.go
internal/webhooks/runtime/extensionconfig_webhook.go
internal/webhooks/runtime/extensionconfig_webhook_test.go

We initially chose 8443 (instead of 443 like the admission webhook configuration resources) as a default port as we thought it might be a good idea as 443 is one of the ports below 1024 which cannot be easily used in containers with restricted privileges.
But I missed at that point that we are not referencing the Pod directly but the Service. The standard for the service port is 443 (I would use the same default port for Extensions as we do for provider webhooks).
Fixes #

🌱 RuntimeSDK: change webhook default port to 443

---

docs/book/src/developer/guide.md

📖 book: add videos from KubeCon and Let's chat about sessions

---

docs/book/src/user/quick-start.md

document it clearly that the secret needs to be in `AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE`.

:book: add missing namespace qualifier

---

docs/book/src/reference/versions.md

Update supported versions in the book to include 1.24.
I refactored the table a bit to improve readability + to be able to include v1.24 without adding another two columns.
Part of #5968
Fixes #6155

:book: update supported Kubernetes versions

---

cloudbuild-nightly.yaml
cloudbuild.yaml

Our image push / cloudbuild is broken since 14th May (https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/cluster-api-push-images-nightly). Not sure what happened then but looks like we can't compile kustomize with Go 1.16. This PR tries to fix this issue by bumping to a recent cloud build image which includes Go 1.17.
Notes:
* I can reproduce locally that kustomize can't be build with Go 1.16 but works with Go 1.17
* Just got the alert mail from Prow today, not sure if I/we missed an earlier one or there was an issue with alerting as well
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

🐛 cloudbuild: upgrade to latest cloudbuild image to fix image push

---

docs/book/src/user/quick-start.md

:book:  
This PR adds documentation for how to setup the provider specific binary for cluster api.
It outlines the general steps a developer can take to configure the provider specific binary to avoid messing up their PATH variables or wrong installations.
Fixes #5546

:book:  add documentation for the provider specific setup in quick start docs

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

This PR makes KubeadmControlPlane's patches option mutable.
Closes #6576

✨ Make KCP's patches option mutable 

---

controlplane/kubeadm/internal/etcd/etcd.go

Currently, the `NewClient` method creates an Etcd client that is initialized and a go-routine is spawned off because it uses GPRC in the background. For the most part, CAPI handles closing this connection up in the stack.
However, if the `newEtcdClient` method fails, we will then return a `nil` client, the go-routine that was spawned off will leak and CAPI will not be able to end it.
This commit fixes that by forcing the `newEtcdClient` method to close connections if the client initialization fails.
N/A

🐛 Close etcd leaky connection if client is not initialized properly

---

cmd/clusterctl/client/cluster/client.go
docs/book/src/developer/providers/v1.1-to-v1.2.md
docs/book/src/reference/versions.md
docs/book/src/user/quick-start.md

In order to fix failures on https://github.com/kubernetes-sigs/cluster-api/pull/6495 I discovered that we need a fix for a SSA apply issue that merged in Kubernetes 1.20 (https://github.com/kubernetes/kubernetes/issues/95680), so bumping CAPI mink8s version to 1.20.2
This will allow tests to pass.
We are considering if to add an additional restriction when using CC, to require management cluster >= v1.22 (the version where SSA went GA), but this will be discussed as part of https://github.com/kubernetes-sigs/cluster-api/pull/6495 
/cc @sbueringer

⚠️ Bump mink8s mgmt cluster version to 1.20.2

---

.github/workflows/verify.yml

This will allow PRs with [release-1.1] in the title.
Fixes #

🌱 bump kubebuilder-release-tools GitHub action to v0.2.0

---

Makefile

apidiff started to fail after we bumped the images used for CI to Go 1.18. This PR fixes it.
Fixes #

🐛 Support Go 1.18: Bump apidiff to v0.4.0

---

docs/book/src/developer/testing.md
docs/book/src/reference/jobs.md
test/e2e/cluster_upgrade_test.go
test/e2e/clusterclass_changes_test.go
test/e2e/quick_start_test.go
test/e2e/self_hosted_test.go

Adds the tag `[ClusterClass]` to all e2e tests which use the ClusterClass/topology feature to allow skipping them easily.
Also documents that we skip tests using `ClusterClass`  at the test `periodic-cluster-api-e2e-mink8s-main`.
xref: PR for test-infra: https://github.com/kubernetes/test-infra/pull/26509
The Server-Side apply functionality went to GA in kubernetes v1.22 and did behave differently for older versions (e.g. v1.19 vs v1.20). 
#6495 will introduce Server-Side Apply for the topology controller which will fail to work on management clusters running kubernetes <= v1.20 (v1.21 seems to …

🐛  test/e2e add tag to e2e tests which use ClusterClass

---

docs/book/src/developer/providers/v1.1-to-v1.2.md
docs/book/src/reference/versions.md
go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Manual bump as dependabot make generate is broken (#6599)
Fixes #

🌱 Bump corefile-migration to v1.0.17

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
docs/book/src/developer/providers/v1.1-to-v1.2.md
main.go
test/infrastructure/docker/main.go

This PR updates our log setup code to use klog.Background as suggested here (https://github.com/kubernetes/klog/issues/302#issuecomment-1048555820). The resulting test/JSON logs are exactly the same as before.
Overall it's just a cleanup which is now possible as we're using a current klog version.
Part of #5968

🌱 logging: use klog.Background

---

.dockerignore
Makefile
cmd/clusterctl/Dockerfile

Signed-off-by: Sachin Kumar Singh <sachins2@vmware.com>
Add functionality to release an official container for `clusterctl` along with the released binaries to be used in image-based pipelines.
Fixes #5894 
/cc @killianmuldoon @fabriziopandini @sbueringer

✨ prebuilt container for clusterctl in image based pipelines

---

internal/controllers/topology/cluster/patches/api/interface.go
internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
internal/controllers/topology/cluster/patches/patch.go
internal/controllers/topology/cluster/patches/template.go
internal/controllers/topology/cluster/patches/variables/value.go
internal/controllers/topology/cluster/patches/variables/value_test.go
internal/controllers/topology/cluster/patches/variables/variables.go
internal/controllers/topology/cluster/patches/variables/variables_test.go
test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml

Refactors inline patching to use the same API types as external patches
Part of #6545

✨ Topology Mutation: use API types for inline patching

---

exp/runtime/hooks/api/v1alpha1/discovery_types.go
exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/runtime/internal/controllers/warmup_test.go
internal/runtime/catalog/catalog.go
internal/runtime/client/client.go
internal/runtime/client/client_test.go

Adds some basic validation and defaulting rules to the runtime SDK client on Discovery of Extension Handlers.
Part of #6330

:seedling: Add client defaulting and validation for DiscoveryResponse

---

.github/workflows/dependabot.yml

Implements workaround for #6526 so that the dependabot action works again.
I pushed this fix on the main branch of my fork. This PR proves that the dependabot job now works again (aka doesn't generate a diff via generate-go-openapi):
* PR: https://github.com/sbueringer/cluster-api/pull/47
* Action logs: https://github.com/sbueringer/cluster-api/runs/6779721721?check_suite_focus=true

🐛 dependabot: implement workaround to run generate-go-openapi in GOPATH

---

cloudbuild-nightly.yaml
cloudbuild.yaml
docs/book/src/developer/providers/v1.1-to-v1.2.md

As there is now a gcb-docker-gcloud image with Go 1.18 available (https://github.com/kubernetes/test-infra/pull/26540),
let's use it!
Part of #5968

🌱 cloudbuild: bump to Go 1.18

---

Tiltfile

Update the tiltfile so the Dockerfile uses `go install` instead of `go get`. `go get` no longer works outside a go module starting with go 1.18.

:bug: Change tiltfile to work with go 1.18

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

This PR for updating the docker distribution package, manual cherrypick of https://github.com/kubernetes-sigs/cluster-api/pull/6548
Fixes #

🌱 Update docker distribution

---

CONTRIBUTING.md
docs/book/src/clusterctl/commands/alpha-rollout.md
docs/book/src/clusterctl/commands/alpha-topology-plan.md
docs/book/src/clusterctl/commands/completion.md
docs/book/src/clusterctl/commands/delete.md
docs/book/src/clusterctl/commands/generate-cluster.md
docs/book/src/clusterctl/commands/get-kubeconfig.md
docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/commands/move.md
docs/book/src/clusterctl/commands/upgrade.md
docs/book/src/clusterctl/configuration.md
docs/book/src/clusterctl/developers.md
docs/book/src/clusterctl/provider-contract.md
docs/book/src/developer/guide.md
docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
docs/book/src/developer/providers/implementers-guide/configure.md
docs/book/src/developer/providers/implementers-guide/generate_crds.md
docs/book/src/developer/providers/implementers-guide/overview.md
docs/book/src/developer/tilt.md
docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
docs/book/src/tasks/experimental-features/experimental-features.md
docs/book/src/tasks/experimental-features/ignition.md
docs/book/src/tasks/external-etcd.md
docs/book/src/tasks/using-kustomize.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
docs/proposals/20191016-clusterctl-redesign.md
test/infrastructure/docker/exp/README.md

This PR provides a consistent usage of how we present commands and their output throughout our docs. Based on the [comment](https://github.com/kubernetes-sigs/cluster-api/issues/6073#issuecomment-1120488708) we have decided to use different blocks for out input and output commands 
Fixes #6073

📖 Reformat shell command and output in the book

---

docs/book/src/developer/providers/v1.1-to-v1.2.md

Documents toleration of control plane taints for compatibility with Kubernetes 1.24 control plane nodes. Also documents the need to adjust manager.yaml so providers can work with the new control-plane label introduced by v1.24.
Fixes #6172

📖 Toleration of v1.24 control plane taints

---

.gitignore
Makefile
scripts/ci-e2e-lib.sh
test/e2e/Makefile
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
test/extension/Dockerfile
test/extension/config/certmanager/certificate.yaml
test/extension/config/certmanager/kustomization.yaml
test/extension/config/certmanager/kustomizeconfig.yaml
test/extension/config/default/extension.yaml
test/extension/config/default/extension_image_patch.yaml
test/extension/config/default/extension_pull_policy.yaml
test/extension/config/default/extension_webhook_patch.yaml
test/extension/config/default/kustomization.yaml
test/extension/config/default/kustomizeconfig.yaml
test/extension/config/default/service.yaml
test/extension/main.go
test/framework/convenience.go

✨ RuntimeSDK: Add Test Extension and initial e2e test

---

config/rbac/role.yaml
exp/runtime/internal/controllers/extensionconfig_controller.go
main.go
test/e2e/cluster_upgrade_runtimesdk.go

This PR fixes some bugs which have been introduced by recent PRs:
1. The ExtensionConfig controller need permissions to list namespaces
2. The ExtensionConfig controller requires the client to be set in main.go otherwise we're getting a panic when we try to List namespaces
3. We have to select the namespace via expressions as `/` is not allowed in the label selector
Fixes #

🐛 RuntimeSDK: some bugfixes

---

exp/runtime/api/v1alpha1/extensionconfig_types.go
exp/runtime/internal/controllers/extensionconfig_controller.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/runtime/internal/controllers/warmup.go
exp/runtime/internal/controllers/warmup_test.go
test/e2e/cluster_upgrade_runtimesdk.go

- injects the `ca.crt` data from a secret referred by the annotation `runtime.cluster.x-k8s.io/inject-ca-from-secret ` into `spec.clientConfig.caBundle`
- adds a watch for secrets **but only their metadata, not secret data** to the extension controller to ensure updates to the  secret referred by an ExtensionConfig annotation triggers updates of the caBundle too.
Fixes #6507

✨ RuntimeSDK: Add caBundle injection to Extension controller

---

exp/internal/controllers/machinepool_controller_phases_test.go

Use APIReader in MachinePool scale to zero test. 
This is targeted at fixing a flake in the test noticed on a recent PR: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/6619/pull-cluster-api-test-main/1536370857771798528

:bug: Use APIReader to fix flaky MachinePool test

---

cmd/clusterctl/client/repository/client.go
cmd/clusterctl/client/repository/client_test.go
cmd/clusterctl/client/repository/repository_gitlab.go
cmd/clusterctl/client/repository/repository_gitlab_test.go
docs/book/src/clusterctl/configuration.md
docs/book/src/clusterctl/provider-contract.md

Allow to defined providers from Gitlab:
```yaml
providers:
- name: "my-infra-provider"
url: "https://gitlab.example.com/api/v4/projects/myorg%2Fmyrepo/packages/generic/myrepo/v1.2.3/infrastructure-components.yaml"
type: "InfrastructureProvider"
- name: "cluster-api"
url: "https://gitlab.example.com/api/v4/projects/external-packages%2Fcluster-api/packages/generic/cluster-api/v1.1.3/core-components.yaml"
type: "CoreProvider"
```
**Testing**
I've [uploaded  test files on Gitlab](https://gitlab.com/sathieu/cluster-api-pr6487/-/packages)
Those can be tested with the following `clusterctl.yaml`:
```yaml
providers:
- name: "my-infra-provider"
url: "https://gitlab.com/api/v4/projects/sathieu%2Fcluster-api-pr6487/packages/generic/myrepo/v1.2.3/infrastructure- …
```

✨ Provider repositories on GitLab

---

config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
exp/runtime/api/v1alpha1/extensionconfig_types.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
exp/runtime/internal/controllers/warmup_test.go
internal/runtime/client/client.go
internal/runtime/client/client_test.go
internal/webhooks/runtime/extensionconfig_webhook.go

This PR does:
* adjusts the Runtime SDKs hook client to enforce usage of TLS for calling Hooks
* adjusts the validation for ExtensionConfigs to block an `ExtensionConfig` which defines an url having `http` scheme
* adjusts tests because they now have to use https
Part of:
* #6330
Follow-up of
* #6632

🌱 RuntimeSDK: enforce https for extensions

---

exp/runtime/api/v1alpha1/extensionconfig_types.go
exp/runtime/hooks/api/v1alpha1/common_types.go
exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/controllers/topology/cluster/scope/upgradetracker.go
internal/hooks/tracking.go
internal/hooks/tracking_test.go
internal/runtime/client/fake/fake_client.go

This PR implements the following hooks:
* AfterControlPlaneInitialized
* AfterControlPlaneUpgrade
* AfterClusterUpgrade
Part of #6546
**Important Links**:
* https://github.com/kubernetes-sigs/cluster-api/pull/6181
* https://github.com/kubernetes-sigs/cluster-api/pull/6418
* https://github.com/kubernetes-sigs/cluster-api/issues/6330
* https://github.com/kubernetes-sigs/cluster-api/issues/6546

✨ Implements AfterControlPlaneInitialized, AfterControlPlaneUpgrade and AfterClusterUpgrade hooks

---

internal/controllers/topology/cluster/patches/engine_test.go
internal/controllers/topology/cluster/patches/template.go

Add tests to Apply using an external Patch.
Part of #6545

:seedling: Add tests for external patch apply

---

bootstrap/kubeadm/types/utils.go
bootstrap/kubeadm/types/utils_test.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_coredns.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
controlplane/kubeadm/internal/workload_cluster_test.go

🐛 Fix version comparison for pre release versions

---

internal/runtime/client/client_test.go

I noticed that when running the tests locally I hit the issue that parallel running tests fail because the port is already used.
I assume Go only starts more tests (in this case of the same package) in parallel if the CPU core/thread count is high enough :) 
But of course this also fails if something else is using the port locally which can easily happen with 9090.
Fixes #

🌱 RuntimeSDK/client: use random port for unit test server

---

test/infrastructure/docker/internal/docker/machine.go

The current code-base gave for granted that in a Docker-based CAPI installation, the Control Plane is managed in the same infrastructure. However, this assumption couldn't be entirely correct, and due to this, the reconciliation is blocking the operations required to assign the Provider IDs to the machines.
Fixes #6639

✨ making SetNodeProviderID no more blocking although Control Plane is externally managed

---

internal/contract/infrastructure_cluster.go
internal/contract/infrastructure_cluster_test.go
internal/controllers/topology/cluster/reconcile_state.go

fields
Currently we never reconcile the controlPlaneEndpoint field of InfrastructureClusters. With this PR we always reconcile the fields if they are set to values different than their zero values.
Fixes #

🐛 ClusterClass: reconcile InfrastructureCluster controlPlaneEndpoint

---

Makefile
hack/get-project-maintainers.sh

This PR restores yq targes accidentally removed by #5785
After this PR hack/get-project-maintainers.sh is back to proper functioning 
/cc @CecileRobertMichon

🐛 Restore yq targets accidentally removed in 5785

---

cmd/clusterctl/client/alpha/machinedeployment.go
cmd/clusterctl/client/alpha/rollout_pauser.go
cmd/clusterctl/client/alpha/rollout_restarter.go
cmd/clusterctl/client/alpha/rollout_resumer.go

Fix a typo in the word MachineDeployment in one of the functions in clusterctl.

🐛  fix typo in clusterctl function name

---

docs/book/src/clusterctl/developers.md
docs/book/src/user/quick-start.md

Following the comment of @sbueringer https://github.com/kubernetes-sigs/cluster-api/issues/6595#issuecomment-1150079224 I have updated the documentation regarding an issue when using Docker (Desktop) on macOS, or when using Docker Desktop on Linux (Docker Enginer works fine).
The documentation only mentioned the fix for Mac users, now the more generic explanation targets all the appriopriate users.
**Which issue(s) this PR fixes**:  
The issue is already closed, but resulted from the lack of this information: https://github.com/kubernetes-sigs/cluster-api/issues/6595

:book: More generic explanation about issue getting kubeconfig on certain systems using Docker

---

internal/controllers/topology/cluster/cluster_controller_test.go
internal/test/builder/bootstrap.go
internal/test/builder/builders.go
internal/test/builder/controlplane.go
internal/test/builder/infrastructure.go
internal/test/envtest/environment.go

Migrate more topology tests to Test* CRD which are using a fully defined OpenAPI spec (vs using XPreserveUnknownFields); thus providing better signal now that we are using SSA

🌱 Migrate more topology tests to Test* CRD

---

test/e2e/cluster_upgrade_runtimesdk.go
test/extension/config/default/extension.yaml
test/extension/config/default/kustomization.yaml
test/extension/config/default/role.yaml
test/extension/config/default/rolebinding.yaml
test/extension/config/default/service_account.yaml
test/extension/handlers/lifecycle/handlers.go
test/extension/main.go

Co-authored-by: ykakarap <kakaraparthy@vmware.com>
This PR extends the Cluster upgrade with Runtime SDK end to end test by adding registrations for lifecycle hooks. The handlers record that they've been called to a configMap and the test checks that each of the hooks has been called at least once during the test flow.
Note, BeforeClusterDelete is currently left out pending #6644 , but is simple to add in once that has merged.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/6546

🌱  Initial e2e test for Runtime SDK lifecycle hook

---

.github/workflows/verify.yml

Tested a while on my fork. this seems to be the best way to do it. branches-ignore applies to the target not the source branch
Fixes #

🐛 fix disable verify action for cherry-pick bot

---

cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go
cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go
cmd/clusterctl/cmd/version_checker.go
cmd/clusterctl/internal/test/fake_github.go
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

This pr updates go-github from v33.0.0 to v45.2.0. 
For reference: https://github.com/google/go-github/releases
Related issue #6687

🌱 Update go-github from v33.0.0 to v45.2.0

---

docs/book/src/developer/providers/webhooks.md
docs/book/src/introduction.md

I would like to suggest adding a link to the videos explaining CAPI to the Getting started section. I personally found them very helpful and I think they should be made more visible to help others getting started with the project to find them.

📖 Add link to videos in the Getting started section

---

docs/book/src/reference/versions.md

Signed-off-by: killianmuldoon [kmuldoon@vmware.com](mailto:kmuldoon@vmware.com)
Update the CoreDNS version supported in release 1.1.

🌱 Update CoreDNS version for release v1.1

---

docs/book/src/reference/versions.md
go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Cherry pick of https://github.com/kubernetes-sigs/cluster-api/pull/6600 
With custom changes to docs

🌱 Update CoreDNS migration library to v1.0.17

---

docs/book/src/user/troubleshooting.md

Adds information about the issue described in https://github.com/kubernetes-sigs/cluster-api/issues/6674#issuecomment-1162746050 to the documentation and adds a link to the documentation of Cert Manager.
Part of #6674

:book: add notes about cert-managers CRD storage version deprecation

---

CONTRIBUTING.md

**What this PR does / why we need it**
Adding the requirement and instructions how to squash commits to CONTRIBUTING.md. I was personally unaware of this requirement until it was mentioned, so I assume that there might be other new contributors that are unaware of this requirement.

📖 Add requirement to squash pr commits to CONTRIBUTING.md

---

docs/book/src/clusterctl/configuration.md

Document the fact that overrides only provide file replacements; instead, provider version resolution is based only on the actual repository structure
Fixes #5818

:book: Update document regarding overrides

---

controlplane/kubeadm/internal/workload_cluster_coredns.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go

This is an manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/6695
/assign sbueringer

[release-1.1] 🐛 Ensure controlplane coredns update deploys the ClusterRole if CoreDNS was already updated

---

exp/runtime/catalog/catalog.go

The PR fixes the catalog to ignore the correct path after the catalog has been moved to `exp/runtime/catalog`.
Fixes #

🌱 runtime sdk catalog path fix

---

internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/structuredmerge/options.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go

Reopens #6738 due to accidental close + force push which made it impossible to reopen the old PR 😢 
Prior to this fix, the topology controller added all spec fields of the incoming Cluster object to the intent to patch.
This lead to the capi-topology controller / manager taking ownership of fields it should not have an intention to set / should never set because they are changed by e.g. the user or git ops mechanisms, etc.
This resulted in the topology controller taking co-ownership of the fields (due to server side apply) and results in the following race condition:
* Topology Controller starts reconciling a Cluster
* Gets the current Cluster object (from its cache)
* Meanwhile an external change happens, e.g. changing the replicas of KCP from 3 to …

🐛 Adjust structuredmerge patch helper options to set correct allow list for Cluster objects to prevent co-ownership

---

controllers/remote/cluster_cache_reconciler.go
docs/book/src/developer/providers/v1.2-to-v1.3.md
util/util.go

This PR cleans up the code that is deprecated in v1.2 release.
Fixes #
Part of #6615
/kind cleanup

🌱 Remove code deprecated in v1.2

---

internal/controllers/topology/cluster/reconcile_state_test.go
internal/controllers/topology/cluster/structuredmerge/options.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

This prevents the race condition of running server side apply on an object which got:
* deleted in the meantime
* recreated in the meantime
and the topology controller won't apply using outdated information anymore.
Fixes #6741

🐛 Carry over metadata.uid at ServerSidePatchHelper

---

cmd/clusterctl/cmd/config_repositories.go
cmd/clusterctl/cmd/root.go

Minor spelling and grammar in the clusterctl help text output.

🌱 Fix spelling in clusterctl command help text

---

test/framework/clusterctl/clusterctl_helpers.go

This fixes a flake where Applying the cluster template yaml can fail due to the ClusterClass not being present in the cache when the Cluster is being validated in the webhook. The webhook currently checks that the ClusterClass for a Cluster exists. If it can not find it it rejects the cluster creation.
Example of the error: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-e2e-full-main/1542219933348270080

:bug: Retry Apply workloadClusterTemplate to fix flake

---

cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/crd_migration.go
cmd/clusterctl/client/cluster/crd_migration_test.go
cmd/clusterctl/client/cluster/upgrader.go

Credits to @fabriziopandini for the initial implementation
Fixes #6674
Fixes #6691

✨ clusterctl: migrate CRDs during clusterctl upgrade

---

test/e2e/clusterctl_upgrade.go
test/framework/alltypes_helpers.go
test/framework/cluster_helpers.go
test/framework/clusterctl/repository.go
test/framework/deployment_helpers.go
test/framework/machine_helpers.go
test/framework/machinedeployment_helpers.go

Remove uses of `By(fmt.Sprintf())` across e2e tests and replace the the purpose-made `Byf()` function.

:seedling: Use 'Byf' instead of 'By(fmt.Sprintf())' across e2e tests

---

internal/controllers/topology/cluster/structuredmerge/filterintent.go
internal/controllers/topology/cluster/structuredmerge/filterintent_test.go

FilterIntent is supposed to remove all empty maps including nested maps to get consistent objects for comparison.
Currently it did only remove empty leaf maps which exist due to field removal.
Now it also removes new empty leaf maps which result from removing an empty leaf map.
Example:
* Consider the following input
```go
map[string]interface{}{
"a": map[string]interface{}{
"b": map[string]interface{}{
"c": map[string]interface{}{
"d": "123",
},
},
},
}
```
* Consider FilterIntent to remove the path `a.b.c.d` (due to ignorePath).
* The current implementation would only remove the resulting empty leaf map at `a.b.c` which would result in:
```go
map[string]interface{}{
"a": map[string]interface{}{
"b": map[string]interface{}{
},
},
}
```
* Actually …

🐛 fix structuredmerge filterintent to cleanup nested empty maps

---

test/e2e/cluster_upgrade_runtimesdk.go
test/extension/handlers/lifecycle/handlers.go
test/framework/cluster_topology_helpers.go
test/framework/clusterctl/clusterctl_helpers.go

Add blocking behaviour to the lifecycle hook e2e test introduced in #6664 
Part of #6546 

🌱  Add blocking end-to-end tests for lifecycle hooks

---

exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
exp/runtime/api/v1alpha1/extensionconfig_types.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/hooks/tracking.go
internal/hooks/tracking_test.go

This PR implements the BeforeClusterDelete hook.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/6546
**Important Links:**
* https://github.com/kubernetes-sigs/cluster-api/pull/6181
* https://github.com/kubernetes-sigs/cluster-api/pull/6418
* https://github.com/kubernetes-sigs/cluster-api/issues/6330
* https://github.com/kubernetes-sigs/cluster-api/issues/6546

✨ Implements BeforeClusterDelete hook

---

test/infrastructure/docker/controllers/alias.go
test/infrastructure/docker/exp/controllers/alias.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/exp/internal/docker/nodepool.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/docker/internal/docker/types/node.go
test/infrastructure/docker/main.go

Discussion started [here](https://github.com/kubernetes-sigs/cluster-api/pull/6640#discussion_r897542990).
Rather than using the base `kubectl` command from the command, the patching can be done by the managed cluster client.
Not yet tracked.

🌱 patching Docker-based nodes provider ID using client-runtime

---

internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/reconcile_state.go
internal/hooks/tracking.go

This PR improves the error wrapping for the utility functions used for Runtime Hooks tracking.
This helps with de-duplicating the error wrapping at various call sites.
Fixes #

🌱 Better error handling for tracking utilities

---

cmd/clusterctl/cmd/alpha.go
cmd/clusterctl/cmd/backup.go
cmd/clusterctl/cmd/config.go
cmd/clusterctl/cmd/config_repositories.go
cmd/clusterctl/cmd/delete.go
cmd/clusterctl/cmd/describe.go
cmd/clusterctl/cmd/describe_cluster.go
cmd/clusterctl/cmd/generate.go
cmd/clusterctl/cmd/generate_cluster.go
cmd/clusterctl/cmd/generate_provider.go
cmd/clusterctl/cmd/init.go
cmd/clusterctl/cmd/move.go
cmd/clusterctl/cmd/topology.go
cmd/clusterctl/cmd/topology_plan.go
cmd/clusterctl/cmd/upgrade.go
cmd/clusterctl/cmd/version.go

This pr fixes the inconsistent punctuation in the clusterctl cmd short descriptions. Currently 10 out of 14 descriptions ends with a dot. I chose to remove all dots since that is more in line with how `kubectl` works. 
`clusterctl help` main branch currently:
```
Available Commands:
alpha       Commands for features in alpha.
backup      Backup Cluster API objects and all dependencies from a management cluster.
completion  Output shell completion code for the specified shell (bash or zsh)
config      Display clusterctl configuration.
delete      Delete one or more providers from the management cluster.
describe    Describe workload clusters.
generate    Generate yaml using clusterctl yaml processor.
get         Get info from a management or a …
```

🌱 Use consistent punctuation in the clusterctl cmd short descriptions

---

test/e2e/e2e_suite_test.go

When following https://cluster-api.sigs.k8s.io/developer/testing.html#running-the-end-to-end-tests-locally , the tests fail without exposing the real error:
```sh
git clone https://github.com/kubernetes-sigs/cluster-api.git
cd cluster-api
make docker-build-e2e
make test-e2e
```
```
panic:
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.
But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call
defer GinkgoRecover()
at the top of the goroutine that caused this panic.
goroutine 40 [running]:
testing.tRunner.func1.2({0x1027420c0, 0x102b7ec48})
/opt/homebrew/Cellar/go/1.18.3/libexec/src/testing/testing.go:1389 …
```

🐛 Improve TestE2E error output and create artifacts dir if not exists

---

docs/book/src/reference/providers.md

Removes two seemingly abandoned providers as discussed in issue #6714

📖 Remove Alibaba and Baidu Cloud from providers list

---

.github/workflows/dependabot.yml

Now that #6815 made it possible to run `make generate` outside of GOPATH again, let's revert the workaround in the dependabot action.
Will be verified via: https://github.com/sbueringer/cluster-api/pull/65
Fixes #6526

🌱 Run dependabot action outside of GOPATH again

---

test/framework/bootstrap/kind_util.go
test/infrastructure/container/docker.go
test/infrastructure/container/fake.go
test/infrastructure/container/interface.go

This PR slightly modifies the way we prime our kind bootstrap clusters during E2E testing:
- if any referenced container image does not exist in the local container image cache, we attempt to pull it remotely using the image reference URI before loading it into the kind node
No error outcomes have been changed. If the image doesn't exist locally *and* the image pull fail, we will still evaluate whether or not to proceed based on our `LoadBehavior` configuration (though if we need to pull the image and it fails, that is a pretty good indication that things will fail further along in the E2E flow).
The reason for this change is to remove (IMO) unnecessary warning messages during E2E runs where some of our mgmt cluster image references are actual …

🌱 pull non-existent images when building kind bootstrap cluster

---

test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl

This PR replaces the capz-specific `$CI_VERSION` env var with the capi-standard `$KUBERNETES_VERSION` variable. This was introduced here:
https://github.com/kubernetes-sigs/cluster-api/pull/6711
Folks are seeing such side-effects since the above PR merged:
```
Jul 06 03:40:39 cluster-conformance-98lra3-control-plane-nhfqm cloud-init[611]: [2022-07-06 03:40:15] /usr/local/bin/ci-artifacts.sh: line 103: CI_VERSION: unbound variable
```
Sorry everyone, thanks @sbueringer for triaging!
Fixes #

🐛 ci: use KUBERNETES_VERSION in kubeadm script

---

docs/book/src/clusterctl/commands/alpha-topology-plan.md

Adds a disclaimer that clusterctl topology dryrun doesn't support RuntimeSDK yet.
When using the command with a ClusterClass with external patching the following error is produced:
> ➜ ${CAPI_HOME}/bin/clusterctl alpha topology plan -f docker-cluster.yaml -f docker-clusterclass.yaml --output-directory=/tmp/test
Detected a cluster with Cluster API installed. Will use it to fetch missing objects.
Error: failed defaulting and validation on input objects: failed to run defaulting and validation on ClusterClasses: failed validation of cluster.x-k8s.io/v1beta1, Kind=ClusterClass default/quick-start: ClusterClass.cluster.x-k8s.io "quick-start" is invalid: spec.patches[0].external: Forbidden: patch.external can be used only if the RuntimeSDK feature flag is …

📖 add disclaimer about clusterctl topology dryrun RuntimeSDK support

---

cmd/clusterctl/cmd/generate_cluster.go

Improves the error message of `clusterctl generate cluster` from
```
$ clusterctl generate cluster
Error: accepts 1 arg(s), received 0
```
To the following:
```
$ clusterctl generate cluster
Error: please specify a cluster name
```
As a side note `clusterctl generate cluster --help` describes usage as:
```
Usage:
clusterctl generate cluster [flags]
```
Maybe this should be: 
```
Usage:
clusterctl generate cluster NAME [flags]
```
Since NAME is a required argument.

🌱 Improve clusterctl generate cluster error message

---

.github/workflows/verify.yml

Update the verifier action to ignore PRs made by the cherry-pick robot.

[release-1.1] :seedling:  Update verify action to ignore cherry-picks

---

cmd/clusterctl/cmd/describe_cluster.go

Improves the error message of `clusterctl describe cluster` from
```
clusterctl describe cluster
Error: accepts 1 arg(s), received 0
```
To the following:
```
clusterctl describe cluster
Error: please specify a cluster name
```

🌱 Improve clusterctl describe cluster error message

---

docs/book/src/reference/providers.md

The [Exoscale provider](https://github.com/exoscale/cluster-api-provider-exoscale) is not maintained anymore

:book: Remove Exoscale provider

---

Tiltfile
docs/book/src/developer/tilt.md

**What this PR does / why we need it**: This provides a convenient way for deploying worker clusters. Tilt searches in a designated folder for yamls and runs envsubst + apply to deploy workload clusters. Additionally, by rerunning the same flavor, users can create multiple clusters from the same template with uniquely generated names. Users can also use a button to conveniently delete all workload clusters.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)* :
Fixes #6219

✨ Add support for deploying Cluster templates and ClusterClasses on Tilt

---

test/e2e/cluster_upgrade_runtimesdk.go
test/extension/handlers/lifecycle/handlers.go
test/framework/cluster_helpers.go
test/framework/cluster_topology_helpers.go
test/framework/controlplane_helpers.go

Signed-off-by: killianmuldoon [kmuldoon@vmware.com](mailto:kmuldoon@vmware.com)
This PR updates the blocking e2e tests added in #6761 to use RetryAfterSeconds. This avoids triggering an exponential backoff in the reconciler and may help to resolve some flakes in the current tests.

:seedling: Runtime sdk/flaky e2e fix

---

exp/runtime/catalog/openapi.go

This PR fixes the description of handler name to be consistent with the current expectations of uniqueness. 
Fixes #
Ref: The original issue was discussed here: https://github.com/kubernetes-sigs/cluster-api/pull/6878#discussion_r917606367

🌱 fix in openapi doc

---

test/e2e/cluster_upgrade_runtimesdk.go

Waits for the test extension deployment to be running and streams logs of it for being able to debug issues via test extension logs.
Fixes #

🌱 test/e2e stream runtime SDK extension controller logs to artifacts

---

docs/book/src/clusterctl/commands/commands.md
docs/book/src/clusterctl/overview.md

* Adds link to clusterctl installation in the overview to make it simpler to find. 
* Adds `clusterctl upgrade plan` and `clusterctl upgrade apply` to the commands list. 
* Adds a short description to each command.
As discussed in the issue, it does not remove the commands from the overview.
Fixes #6804

📖 Add short description for each clusterctl command in CAPI book

---

docs/book/src/developer/providers/webhooks.md

Follow up to #6710
Follow-up documentation via discussion at https://github.com/kubernetes-sigs/cluster-api/pull/6710#discussion_r914851610
Fixes #
/cherry-pick release-1.2

📖 add note ClusterClass compatibility info to validating webhooks section

---

Tiltfile
docs/book/src/developer/tilt.md
hack/observability/visualizer/kustomization.yaml
hack/observability/visualizer/values.yaml

**What this PR does / why we need it**: This PR adds the Cluster API Visualizer app to Tilt under the observability section. It can be enabled by adding "cluster-api-visualizer" to the "deploy_observability" array. The Tilt UI looks as follows and the "View visualization" link opens it in the browser.
Fixes #

✨ Add Cluster API Visualizer to Tilt observability

---

internal/runtime/client/client.go

Fixes a small error in formatting in one of our client log lines.

🐛  fix log formatting in runtime client

---

bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
docs/book/src/developer/providers/v1.1-to-v1.2.md

Deprecate the experimentalRetryJoin field in KubeadmConfig, KubeadmConfigTemplate, KubeadmControlPlane and KubeadmControlPlaneTemplate. 
Fixes #5597

🌱  Deprecate experimentalRetryJoin

---

test/e2e/config/docker.yaml

This PR update the clusterctl upgrade test to use the v1.2.0 tag. (Currently using the beta tag)
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/6833
Part of : #6615 
/area testing

🌱 bump to v1.2.0 tag for clusterctl upgrade tests

---

docs/book/src/developer/providers/implementers-guide/overview.md

Signed-off-by: Jirka Kremser <jiri.kremser@oracle.com>
The current install instructions for Kustomize and Kubebuilder for linux are outdated and both do not work so this PR updates it.
For Kustomize it's little bit controversial to do `curl something | bash` (but it's their official [suggested way](https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/) of installing + no sudo here)

📖 docs: update install instructions for kustomize and kubebuilder

---

internal/runtime/client/client.go

Remove the Message returned from the Runtime extension from the error returned by CallExtension and Discovery. This message may be unique and could cause too many reconciliation loops as in #5945
Fixes #6921

:bug: Remove message from Runtime SDK FailureResponses

---

cmd/clusterctl/cmd/describe_cluster.go

Add a new flag `--color` to `clusterctl describe cluster` that forces the color output, even when stdout is not a tty. This can be useful when e.g. using `watch`.
The default from `github.com/fatih/color` is to disable color output when not writing to a terminal, see: https://github.com/fatih/color#disableenable-color
You can try this feature with these commands:
```shell
make clusterctl
watch --color ./bin/clusterctl describe cluster --color my-cluster
watch -c ./bin/clusterctl describe cluster -c my-cluster
```
Fixes #

✨ clusterctl: add flag to force color output on `describe cluster`

---

internal/controllers/topology/cluster/current_state.go
internal/controllers/topology/cluster/current_state_test.go

Adds check for not topology owned md templates so they never reconcile.  
Which issue(s) this PR fixes(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5760

✨ Add checks for not topology owned templates to never reconcile.

---

docs/book/src/developer/testing.md

Add a section on fuzzing to the cluster api testing docs. Include the 2022 Cluster API Fuzzing report in the section related to OSS-Fuzz.

:book: Add section on Fuzzing to testing guide

---

cmd/clusterctl/client/delete.go
cmd/clusterctl/client/init.go
cmd/clusterctl/client/upgrade.go
cmd/clusterctl/cmd/delete.go
cmd/clusterctl/cmd/generate_provider.go
cmd/clusterctl/cmd/init.go
cmd/clusterctl/cmd/upgrade_apply.go
docs/book/src/clusterctl/configuration.md

Update the version of CAPI used in examples across the clusterctl codebase.

🌱  Update example version of core CAPI used in clusterctl

---

docs/book/src/developer/providers/v1.1-to-v1.2.md

Add up to date information on the klog functions used to set up the logger in the 1.1-1.2 migration guide. This was brought up as a point of confusion for migration.

:book: Add klog.Background PR to migration guide

---

docs/book/src/developer/providers/machine-infrastructure.md

🌱 Add providerID workflow clarification

---

Makefile

Fix an issue in make release that resulted in the wrong image tag being applied to the CAPD infrastructure provider in release artifacts.
Fixes #6972

🐛  Update make release process to correctly tag CAPD

---

exp/internal/controllers/machinepool_controller_noderef.go
exp/internal/controllers/machinepool_controller_noderef_test.go

Using `ProviderID.ID()` is not good enough for all providers as some providers like Azure VMSS don't assign a unique instance id to each VM in a scale set and it causes a bug when multiple MachinePools are present where IDs collide and noderefs end up in the wrong MachinePool Status. Using the full provider ID string ensures uniqueness and guarantees that nodes will be matched to the correct MachinePool
More details in this [slack thread](https://kubernetes.slack.com/archives/CEX9HENG7/p1658498393187099).
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4526

🐛 Fix machinepool instance id bug

---

test/e2e/cluster_upgrade.go
test/e2e/clusterclass_changes.go
test/e2e/clusterctl_upgrade.go
test/e2e/k8s_conformance.go
test/e2e/machine_pool.go
test/e2e/md_rollout.go
test/e2e/md_scale.go
test/e2e/mhc_remediations.go
test/e2e/node_drain_timeout.go
test/e2e/quick_start.go
test/e2e/self_hosted.go

**What this PR does / why we need it**: Enable configuring ControlPlaneWaiters for all e2e test specs where it's relevant (all except kcp adoption) to allow infra providers running the CAPI test suite with different Control Plane providers and/or custom waiters to leverage those.
Fixes #

🌱 Add ControlPlaneWaiters to input for e2e specs

---

Dockerfile
Makefile
cmd/clusterctl/Dockerfile
docs/Dockerfile
scripts/ci-lint-dockerfiles.sh
test/extension/Dockerfile
test/infrastructure/docker/Dockerfile

Adds a Dockerfile linter to the make lint target. This is done via a script which finds all files named "Dockerfile" and runs [Hadolint](https://github.com/hadolint/hadolint) on them. I've configured it to only fail on the highest severity. 
The new output is:
```
make lint
(...)
./scripts/ci-lint-dockerfiles.sh
Linting: cmd/clusterctl/Dockerfile
-:20 DL3006 warning: Always tag the version of an image explicitly
Linting: Dockerfile
-:20 DL3006 warning: Always tag the version of an image explicitly
Linting: docs/Dockerfile
-:34 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
-:35 DL3047 info: Avoid use of wget without progress bar. Use `wget --progress=dot:giga …
```

🌱 Add Dockerfile linter

---

CONTRIBUTING.md

Proposing a change to how we perform issue triage and milestone management:
- Stop assigning issues to the current milestone as a signal for "triaged", and start using the triage labels instead
- Start adding issues to milestones only when there is someone who expressed intent to work on it before the deadline
- Drop Milestone Next
/hold 
for community discussion
/cc @CecileRobertMichon @enxebre  @vincepri @sbueringer

🌱 improve how do we perform issue triage and milestone management

---

REVIEWING.md
docs/book/src/SUMMARY.md
docs/book/src/developer/logging.md

This PR documents the logging guidelines we are using in CAPI - pending merge of https://github.com/kubernetes-sigs/cluster-api/pull/6150

🌱 Add logging guidelines

---

test/framework/clusterctl/clusterctl_helpers.go

Cleans up the folder used for controller logs to be in a more generic structure.
Especially with future e2e tests which e.g. include more runtime SDK parts this leads to a more intuitive directory structure
to find artifacts for logging or metrics.
Artifacts structure for logs and metrics prior to this PR:
```txt
artifacts/clusters/<cluster-name>/logs/<namespace>/<deployment>/<pod>/
|- manager.log
|- manager-log-metadata.json
|- metrics.txt
```
Example:
```txt
artifacts/clusters/bootstrap/controllers/capd-controller-manager/capd-controller-manager-f8666db7f-hh8jz/
|- manager.log
|- manager-log-metadata.json
|- metrics.txt
`
Artifacts structure with this PR:
```txt
artifacts/clusters/<cluster-name>/
|- logs/<namespace>/<deployment>/<pod>/
|- …

🌱 e2e: cleanup controller log and metric output path

---

controllers/external/util.go
controllers/external/util_test.go
controlplane/kubeadm/internal/controllers/helpers.go
docs/book/src/developer/providers/v1.2-to-v1.3.md
internal/controllers/machineset/machineset_controller.go

This PR renames [`CloneTemplate`](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/external/util.go#L90) to `CreateFromTemplate` and adds a deprecation notice on `CloneTemplate` function.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6407

🌱 rename CloneTemplate to CreateFromTemplate

---

docs/book/src/user/quick-start.md

Adds a link to the vcluster provider Quick Start in the CAPI Quick Start.

📖  Add vcluster to CAPI book Quick Start

---

test/e2e/clusterctl_upgrade.go
test/e2e/self_hosted.go

This PR add rollouts checks to self hosted e2e tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6925
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6094
/area testing

🌱 self hosted tests should check for rollouts

---

exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
exp/addons/internal/controllers/clusterresourceset_helpers.go

Fix an issue where OwnerReferences were only added to a ClusterResourceSetBinding on Create. This fix will ensure the references are set each time the ClusterResourceSet the Binding is created from from is reconciled.
Fixes #6007

🐛 Add OwnerRef to clusterResourceSetBinding on each reconcile

---

controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go

Fix a possible nil pointer when etcd healthy quorum is available, but no healthy machine is available to become etcd leader. Add a condition to the machine to be remediated surfacing the issue.
Fixes: #7000

🐛 Fix potential nilpointer error in machine remediation

---

Tiltfile
docs/book/src/developer/tilt.md

Small improvements in templates UI in tilt:
- templates show up using provider labels, so things are in order e.g. CAPD, CAPD.clusterclass, CAPD.templates
- add inputs to buttons so it is possible to change substitutions values on the fly

🌱 improve templates ui in tilt

---

controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go

Fix a possible nil pointer when etcd healthy quorum is available, but no healthy machine is available to become etcd leader. Add a condition to the machine to be remediated surfacing the issue.
Cherry Pick of: https://github.com/kubernetes-sigs/cluster-api/pull/7008
Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/7000

🐛  Fix potential nilpointer error in machine remediation

---

internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_phases.go
util/util.go

This PR improve machine provisioning logging based on project's logging guidelines introduced by https://github.com/kubernetes-sigs/cluster-api/pull/6969

🌱 improve logging for the machine provisioning workflow

---

controlplane/kubeadm/internal/control_plane.go

Removes the now unused Logger from the ControlPlane package. This logger was used previous to the changes in #6994 specifically [here](https://github.com/kubernetes-sigs/cluster-api/pull/6150/files#diff-52adeada03991a6272ae7710a3725d8abf89ae5567146d75c61351888d93e3ea)

:seedling: Remove logger from ControlPlane internal

---

docs/book/src/reference/providers.md

[Issue created at the Tencent repo](https://github.com/TencentCloud/cluster-api-provider-tencent/issues/12) over a month ago to determine whether or not it's still maintained was not answered, and the most recent release is from 2018.

📖  Remove unmaintained Tencent provider from docs

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

Allow the Kubeadm Control Plane webhook to accept intOrString types where the base type is a string by comparing using the IntValue() method.

:seedling: KCP webhook - compare maxSurge using IntValue

---

test/framework/exec/kubectl.go

now e2e test framework only support use kubectl of system, sometimes user need a different version of kubectl, this PR enable it by customize kubectl path with `CAPI_KUBECTL_PATH` env var.

✨e2e: Support use customize kubectl

---

cmd/clusterctl/client/client.go
cmd/clusterctl/client/client_test.go
cmd/clusterctl/client/generate_provider.go
cmd/clusterctl/client/repository/client.go
cmd/clusterctl/cmd/generate_provider.go

This PR add version check to `clusterctl generate provider` to make sure that clusterctl does not process and provider incorrect provider components when run against and incompatible version of the provider.
If the command is run with an incompatible version it will throw and error. Example:
```
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha3 for provider "aws"
```
Fixes #5864

✨ add version check to clusterctl generate provider

---

docs/book/src/user/quick-start.md

Fixes clusterctl.exe installation on Windows, first it was missing the -L for the redirect and was returning empty content for the http request. but... curl is sometimes an alias in PowerShell for `Invoke-WebRequest` so the best and most cross compatible way for cmd and powershell I ever found was to just call `curl.exe` explicitly which always ends up being the curl everyone expects.
This is what happens using the docs as they exist today in powershell
```
~ > curl https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/clusterctl-windows-amd64.exe -o clusterctl.exe
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 …
```

:book: fixing clusterctl.exe installation directions for curl.exe

---

Makefile

Fix an issue introduced in https://github.com/kubernetes-sigs/cluster-api/pull/6973 to properly generate CAPD manifests during the nightly release process.

🐛  Fix omitted target in CAPD staging Makefile target

---

util/conditions/patch.go
util/conditions/patch_test.go

Fix a nil pointer discovered through fuzzing. This condition is unlikely or impossible to occur in CAPI code, but is possible for consumers of the code.
Part of the broader issue discussed in https://github.com/kubernetes-sigs/cluster-api/pull/6334#issuecomment-1084602280

🐛  Fix nil pointer in patch Apply

---

internal/contract/controlplane_test.go
internal/contract/types.go
internal/controllers/topology/cluster/desired_state_test.go
test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml

This changes adds setting nodeDrainTimout field to the ControlPlane and MachineDeploymentTopology in our ClusterClass quick start test and adds a fix which unquotes the string before setting it in the patch.
On reviewing #https://github.com/kubernetes-sigs/cluster-api/pull/7031 it looks like we're not able to reconcile NodeDrainTimeout (added in https://github.com/kubernetes-sigs/cluster-api/issues/6278) on the control plane in a topology managed cluster.

 🐛 Fix nodeDrainTimeout for ControlPlane on Topology managed clusters

---

controllers/remote/cluster_cache_tracker.go

`err` is the return from the upper result and returns nil, showing a wrong message in the failure of wait.
Fixes #

🐛Using cacheCtx on WaitForCacheSync error loading

---

Dockerfile
cmd/clusterctl/Dockerfile
test/extension/Dockerfile
test/infrastructure/docker/Dockerfile

References the correct architecture for the distroless base image. Before this commit, docker would have chosen the platform of the docker host.
Current main:
```sh
$ uname -m
arm64
$ ARCH=ppc64le REGISTRY=test make docker-build-core
$ docker inspect docker.io/test/cluster-api-controller-ppc64le:dev | grep Architecture
"Architecture": "arm64",
```
WIth this commit:
```sh
$ uname -m
arm64
$ ARCH=ppc64le REGISTRY=test make docker-build-core
$ docker inspect docker.io/test/cluster-api-controller-ppc64le:dev | grep Architecture
"Architecture": "ppc64le",
```
Note: I had to move the `ARG ARCH` above the first `FROM`, otherwise it is not set/empty in `FROM` lines. …

🐛 Fix Architecture metadata in Dockerfiles for distroless base image references

---

Dockerfile
cmd/clusterctl/Dockerfile
test/extension/Dockerfile
test/infrastructure/docker/Dockerfile

Manual cherry-pick of #7070 
References the correct architecture for the distroless base image. Before this commit, docker would have chosen the platform of the docker host.
Current main:
```sh
$ uname -m
arm64
$ ARCH=ppc64le REGISTRY=test make docker-build-core
$ docker inspect docker.io/test/cluster-api-controller-ppc64le:dev | grep Architecture
"Architecture": "arm64",
```
WIth this commit:
```sh
$ uname -m
arm64
$ ARCH=ppc64le REGISTRY=test make docker-build-core
$ docker inspect docker.io/test/cluster-api-controller-ppc64le:dev | grep Architecture
"Architecture": "ppc64le",
```
Note: I had to move the `ARG ARCH` above the first `FROM`, otherwise it is not set/empty in `FROM` lines.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …

[release-1.2] 🐛 Fix Architecture metadata in Dockerfiles for distroless base image references

---

test/e2e/Makefile
test/e2e/clusterclass_changes_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-topology-changes/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-topology-changes/node-drain-timeout.yaml

Fix a failing e2e test caused by changes made in #7047 which overwrite the changes made in this test.
Add a new template to our e2e test package specifically for the broken test which patches the template to remove the overwriting value i.e. nodeDrainTimeout set in Cluster `.spec.topology.controlPlane`
/kind bug
/area testing

🐛 Add template flavor for topology-changes test

---

.gitattributes

Add a `.gitattributes` file to hide generated CRD yamls in PRs. Our generated go code is already automatically hidden by [github linguist](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github). 
The `.gitattributes` file lets us customize it's config - I'm sure there will be more potential additions to this in future.

🌱  Add .gitattributes file to hide generated diffs

---

Makefile

Just saw that it should be fixed with recent kubebuilder releases
Fixes #

🌱 kubebuilder: switch back to darwin arm64 binaries

---

REVIEWING.md
docs/book/src/developer/logging.md

Add some example queries to show how to use json logging and the Tilt logging suite to filter and correlate logs across Cluster API providers.

📖  Add example queries to developer logging guidelines

---

Dockerfile
Makefile
cmd/clusterctl/Dockerfile
test/extension/Dockerfile
test/infrastructure/docker/Dockerfile

* Adds the `lint-dockerfiles` target to the verify target so it gets run by the verify job.
* Fixes the hadolint finding [DL3029](https://github.com/hadolint/hadolint/wiki/DL3029), introduced in #7070.
Alternative to using the `ARCH` argument in the tag would have been to ignore the hadolint finding (which was invalid in our case) or rename the `ARCH` argument to `BUILDPLATFORM`
xref #7070

🐛 add lint-dockerfiles to verify and fix hadolint finding

---

Dockerfile
cmd/clusterctl/Dockerfile
test/extension/Dockerfile
test/infrastructure/docker/Dockerfile

Manual cherry-pick of #7078.
Skipping the Makefile changes because they depend on the `lint-dockerfiles` target which does not exist on the release-1.2 branch.
Fixes #

[release-1.2] 🐛 fix hadolint finding

---

docs/book/src/developer/logging.md

Remove instances of 'is is' from across the codebase.
Fixes #https://github.com/kubernetes-sigs/cluster-api/pull/7084#issuecomment-1219363682

📖  Remove 'is is' typo in book

---

internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go

Messages for the MachineHasFailureReason contained memory addresses instead of the failure reason text. This lead to hot reconciliation loops, because the message changed with every loop-run.
```
Old: "FailureReason: 0xc000d80d10"
New: "FailureReason: UpdateError"
```
Messages for the UnhealthyNodeConditionReason contained the timeout value as a nested struct.
```
Old: "Node failed to report startup in &Duration{Duration:10m0s,}"
New: "Node failed to report startup in 10m0s"
```

:bug: Fix messages of MachineHealthCheckSucceedCondition

---

util/container/image.go
util/container/image_test.go

I was upgrading the control-plane on a Kubernetes cluster overriding `clusterConfiguration.imageRepository: docker.io/foo` and ran into an error where the `kube-proxy` DS was never updated.
```
E0811 03:44:47.681926       1 controller.go:387] controller/kubeadmcontrolplane "msg"="failed to update kube-proxy daemonset" "error"="failed to parse image name: couldn't parse image name: repository name must be canonical" "cluster"="dkoshkin-upgrade" "name"="dkoshkin-upgrade-control-plane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane"
```
You can also see these error messages in the logs for new clusters if using a `imageRepository: doker.io` `imageRepository`, but its real subtle since it …

🐛 Fix kube-proxy upgrade with docker.io image

---

bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml

The docs to remove the default control plane taints instruct the user to set the value to _an empty slice, i.e. `taints: {}` in the YAML file_ , but an empty slice is equal to an empty yaml array: `taints: []`.
Fixes #

🌱 Fix empty control-plane taints example

---

api/v1beta1/clusterclass_types.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml

This PR adds some of the missing validations in MHC in ClusterClass.
Example: `unhealthyRange` should always be of the form `[1-3]`. If the validation is missing in ClusterClass it can be set to `1-3` and this will lead to failured in topology controller.
Fixes #

:seedling: add missing validations to MHC in ClusterClass

---

cmd/clusterctl/client/init.go
cmd/clusterctl/cmd/init.go

Can be used during clusterctl init to ignore validation errors, most frequently during development of tools that consume clusterctl as a library.
Concretely, it's helping me out during debugging.
Fixes #

🌱 clusterctl: Add --validate option to init

---

docs/book/src/developer/providers/implementers-guide/overview.md

Homebrew has a recipe for Kubebuilder and it's at the latest version, so developers should use that to automatically receive updates.

📖 docs: switch kubebuilder installation instructions on macOS to homebrew

---

Tiltfile
hack/tools/tilt-prepare/main.go

🐛 tilt: Enable deploy cert-manager per default again

---

.golangci.yml
Tiltfile
docs/book/src/developer/repository-layout.md
hack/boilerplate/boilerplate.py
hack/verify-shellcheck.sh

#7108 removed the `third_party' folder from the repo. This change removes a number of references to that directory from across the book, scripts and config.

🌱  Remove references to third_party directory

---

.github/workflows/golangci-lint.yml
.golangci.yml
bootstrap/kubeadm/main.go
cmd/clusterctl/main.go
controlplane/kubeadm/main.go
exp/runtime/server/server.go
hack/tools/conversion-verifier/doc.go
hack/tools/log-push/main.go
hack/tools/mdbook/embed/embed.go
hack/tools/mdbook/releaselink/releaselink.go
hack/tools/mdbook/tabulate/tabulate.go
hack/tools/release/notes.go
hack/tools/runtime-openapi-gen/main.go
hack/tools/tilt-prepare/main.go
internal/controllers/machine/machine_controller_phases.go
main.go
test/extension/main.go
test/infrastructure/docker/main.go

Update golangci-lint to version 1.49. This update re-enables the revive rules that were disabled in v1.48.0

🌱  Update golangci-lint to 1.49.0

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Signed-off-by: willie-yao <williamyao@microsoft.com>
This PR bumps cert-manager to the latest version (v1.9.1) on CAPI.
Fixes #7060

🌱Bump cert-manager to v1.9.1

---

Tiltfile
hack/tools/tilt-prepare/main.go
test/e2e/cluster_upgrade_runtimesdk.go
test/extension/config/certmanager/certificate.yaml
test/extension/config/default/rolebinding.yaml
test/extension/config/tilt/extensionconfig.yaml
test/extension/config/tilt/hookresponses-configmap.yaml
test/extension/handlers/lifecycle/handlers.go

Add a generic deployment mechanism for addons to the tilt file and tilt prepare. This mechanism allows  Runtime SDK extensions to be developed alongside the core controllers using the Tilt development flow. It can also be used to develop arbitrary deployments and addons built using the same workflow in tilt as providers use today.
May be related to #6647 
Fixes #6864

✨ Add generic addon deployment config to tilt

---

test/e2e/data/cni/kindnet/kindnet.yaml

Update kindnetd to the [latest release tag](https://hub.docker.com/r/kindest/kindnetd/tags) - v20220726-ed811e41. This change ensures that references to `PodSecurityPolicies`, which are being removed in Kubernetes 1.25, are no longer in the CAPI repo. 
/kind cleanup

🌱  Update kindnetd to the latest release version

---

docs/proposals/20220725-managed-kubernetes.md

This proposal discusses various options on how managed Kubernetes services could be represented in Cluster API by providers and makes a recommendation for new implementations. One of main goals/motivation of the proposal is to reach a consensus on how `ClusterClass` should be supported for managed Kubernetes by agreeing on the API option.
cc @richardcase 
Fixes #6126

📖 Managed Kubernetes in CAPI proposal

---

test/e2e/clusterclass_changes.go
test/e2e/clusterclass_changes_test.go

This PR extends the ClusterClass changes e2e test to cover InfrastructureMachineTemplate rotation. This makes it easy to test if the webhook change for ClusterClass SSA has been implemented correctly.
xref: https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers (2nd point)
I would like to cherry-pick this in to release-1.2 to make it directly available to providers adopting CAPI v1.2
Fixes #

🌱 test/e2e: Extend ClusterClass changes test to cover InfrastructureMachineTemplate rotation

---

CONTRIBUTING.md
docs/developer/release-team.md

**What this PR does / why we need it**: As discussed in office hours and in https://github.com/kubernetes-sigs/cluster-api/issues/6442, this document introduces the concept of a CAPI release team. Note that this document is intended to be a starting point for the release team. It is not a complete release process document.
Most of this proposal comes from the discussions in https://docs.google.com/document/d/1DQIsu2nLvkPD5x4c0GW7oYZjb1PUINv4mGPzB_PmPws/edit#. Kudos to @LappleApple for starting it.
A lot of this process is inspired from https://github.com/kubernetes/sig-release/blob/master/release-team/README.md, credits go to the Kubernetes release SIG and past release teams for making it a great resource. …

📖 Add release team process

---

.github/workflows/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.golangci.yml
Makefile
Tiltfile
cloudbuild-nightly.yaml
cloudbuild.yaml
docs/book/src/developer/providers/v1.2-to-v1.3.md
hack/ensure-go.sh
netlify.toml

Upgrade golang version 1.18.3 -> 1.19.0 as required by v1.25.0.
Part of #6661

🌱 Upgrade golang version (1.18.3 -> 1.19.0)

---

test/e2e/clusterclass_changes.go
test/e2e/clusterclass_changes_test.go

Manual cherry-pick of #7134
Fixes #

[release-1.2] 🌱 test/e2e: Extend ClusterClass changes test to cover InfrastructureMachineTemplate rotation

---

docs/book/src/developer/repository-layout.md

Fix a link broken by pointing to the main version of a book for a path that is now removed in the main branch of the Cluster API repo.

📖  Fix third_party link to version 1.2

---

Makefile
Tiltfile
docs/book/src/developer/tilt.md
hack/observability/kube-state-metrics/chart/kustomization.yaml
hack/observability/kube-state-metrics/chart/values.yaml
hack/observability/kube-state-metrics/crd-config.yaml
hack/observability/kube-state-metrics/kustomization.yaml
hack/observability/kube-state-metrics/metrics/README.md
hack/observability/kube-state-metrics/metrics/cluster.yaml
hack/observability/kube-state-metrics/metrics/common_metrics.yaml
hack/observability/kube-state-metrics/metrics/header.yaml
hack/observability/kube-state-metrics/metrics/kubeadmcontrolplane.yaml
hack/observability/kube-state-metrics/metrics/machine.yaml
hack/observability/kube-state-metrics/metrics/machinedeployment.yaml
hack/observability/kube-state-metrics/metrics/machinehealthcheck.yaml
hack/observability/kube-state-metrics/metrics/machineset.yaml
hack/observability/kube-state-metrics/metrics/owner_metric.yaml

* Adds `kube-state-metrics` to `hack/observability` which uses the `kube-state-metrics` helm chart and adds configuration for CAPI CRs
* Integrates into tilt
Currently not added metrics:
- `*_labels`
TODOs:
- won't implement for now. Split could be done in future when KSM provides a CR for configuration purposes.
Part of #6458

✨ Integrate kube-state-metrics and CR config into tilt.

---

CONTRIBUTING.md

Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/7110#discussion_r958366116
Fixes #

📖 book: fix broken link in Contributing

---

hack/observability/visualizer/kustomization.yaml
hack/observability/visualizer/values.yaml

**What this PR does / why we need it**: Update Cluster API Visualizer chart to v1.0.0
Fixes #

🌱 Update Cluster API Visualizer chart to v1.0.0

---

hack/observability/promtail/values.yaml

This PR fixes the configuration of the new charts to promtail to work with loki.
Note: Developers might need to clean their copies of local helm charts to make sure the configuration is working with the compatible version of observability tools.
Fixes #

🌱 tilt: fix promtail values.yaml tow work with loki

---

cmd/clusterctl/cmd/init.go
cmd/clusterctl/cmd/init_list_images.go
docs/book/src/clusterctl/commands/additional-commands.md
docs/book/src/clusterctl/commands/commands.md
docs/book/src/developer/providers/v1.2-to-v1.3.md

In clusterctl / init the there is a [todo](https://github.com/kubernetes-sigs/cluster-api/blob/1ec0cd6174f1b860dc466db587241ea7edea0b9f/cmd/clusterctl/cmd/init.go#L112) to convert `clusterctl init --list-images` to a sub-command.
Instead of redeclaring the flags needed by `list-images` I updated some flags in `init` from `initCmd.Flags()` -> `initCmd.PersistentFlags()` to inherit them. Is this an acceptable approach? (Maybe common flags like kube context etc should really be in root?).
The documentation is sparse and more placeholder. Will be replaced later if the general approach is ok.
```shell
$ ./bin/clusterctl init list-images -h
Lists the container images required for initializing the management cluster.
See https://cluster-api.sigs.k8s.io for …
```

✨ Add `clusterctl init list-images` command

---

internal/controllers/topology/cluster/patches/variables/errors.go
internal/controllers/topology/cluster/patches/variables/value.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-cgroupfs.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-default-cgroupfs.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
test/extension/config/tilt/hookresponses-configmap.yaml
test/extension/handlers/topologymutation/handler.go
test/extension/handlers/topologymutation/handler_test.go
test/extension/handlers/topologymutation/lib.go
test/extension/main.go

Work in progress - no need to review
This PR moves patches in the runtime SDK end to end test to the test extension. 
Two patches - for etcd and coredns image tags - have been dropped as they add a complication to the running of the test, causing a double rollout when set on update with a blocking cluster upgrade webhook.
Fixes #6859

:seedling:  Add more patches to test extension

---

util/record/recorder.go

While bumping to CAPI v1.2 in CAPV we noticed that when replacing `strings.Title` with `cases.Title` in core CAPI a while back we accidentally broke the formatting of the event reason.
(thx @johananl & @srm09)
That means:
* strings.Title:  CreateSuccess => CreateSuccess
* cases.Title(language.Und): CreateSuccess => Createsuccess
* cases.Title(language.Und, cases.NoLower): CreateSuccess => CreateSuccess
I would like to cherry-pick this into 1.2.x for folks who might match against the reason in an event.
(The change was after 1.1.x so 1.1.x is not affected)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

🐛 util/record: fix usage of case.Title in util/record

---

hack/observability/kube-state-metrics/crd-config.yaml
hack/observability/kube-state-metrics/metrics/machinedeployment.yaml

Adds missing `capi_machinedeployment_status_replicas_ready` metric to the config for kube-state-metrics.
part of #6458

✨ Add missing status_replicas_ready metric for MachineDeployments at kube-state-metrics

---

Tiltfile
bootstrap/kubeadm/config/rbac/role.yaml
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
docs/book/src/developer/logging.md
docs/book/src/developer/providers/v1.2-to-v1.3.md
exp/internal/controllers/machinepool_controller_phases.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/config/rbac/role.yaml
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
util/log/doc.go
util/log/log.go
util/log/log_test.go

With this PR we're logging all relevant k/v pairs for all our resources.
This PR also contains 1-2 smaller other logging fixes and an improvement to our Tiltfile so the ServiceAccount of Grafana is **always** deployed before the Grafana deployment.
Fixes #

🌱 logging: adjust reconcilers to log object owners 

---

hack/observability/kube-state-metrics/chart/values.yaml

Drops hardcoded kube-state-metrics version tag.
New helm chart release which includes kube-state-metrics v2.6.0 was created via https://github.com/prometheus-community/helm-charts/pull/2422
Fixes #7143

🌱 remove image tag pinning for kube-state-metrics

---

.gitignore
Tiltfile
docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/framework/deployment_helpers.go
test/infrastructure/docker/Dockerfile
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

Updates the Quick Start guide to use Kubernetes 1.25. Now using kind 0.15.0 and Calico 3.24.1. 
Calico was updated due to breakage `error: unable to recognize "https://docs.projectcalico.org/v3.21/manifests/calico.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`.
The updated QS "works on my machine" and all pods in management and worker cluster seem to be running. 
Part of #6661

⚠️ Use Kubernetes 1.25 in Quick Start docs and CAPD.

---

hack/verify-shellcheck.sh

The currently used shellcheck version is a few versions old. Just an update to get the new checks:
https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md

🌱 Update shellcheck version (0.7.0->0.8.0)

---

internal/controllers/machineset/machineset_controller.go

Make logs for the MachineSet scale up/down workflow consistent with the new logging guidelines
Rif https://github.com/kubernetes-sigs/cluster-api/issues/6994

🌱 Improve logging for the MachineSet scale up/down workflow

---

hack/observability/grafana/kustomization.yaml
hack/observability/kube-state-metrics/chart/kustomization.yaml
hack/observability/loki/kustomization.yaml
hack/observability/prometheus/kustomization.yaml
hack/observability/promtail/kustomization.yaml
hack/observability/visualizer/kustomization.yaml

Talked to Fabrizio, with the latest issues we have with the Loki bump (we need fixes in the Loki chart to adopt it) we would propose to pin the Helm charts. This makes it also more predictable when we invest effort into bumping charts and in the meantime it will "just work"
For future bumps I would suggest to just do a basic test that the logs of our controllers show up in Grafana
P.S. @ykakarap you were right! :)
P.S. 2: Verified locally and works for me
Fixes #

🌱 hack/observability: pin charts

---

CONTRIBUTING.md

As discussed in the office hours.
I would take care of the next v1.1.x and v1.2.x release in ~ 2 weeks.
Fixes #

📖 book: set v1.1.x EOL date

---

docs/book/src/reference/glossary.md

This PR adds the definition of `KCP` to the glossary page.
reference: https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#contributors-ladder

:book: Add "KCP" to glossary

---

docs/book/src/developer/providers/version-migration.md
docs/book/src/reference/versions.md

Adds Kubernetes 1.25 to the versions.md doc
Part of #6661

🌱 Update versions doc adding Kubernetes 1.25

---

docs/book/src/reference/jobs.md

Updates jobs.md with the new [test-infra](https://github.com/kubernetes/test-infra/pull/27421/files) jobs
Part of #6661

📖 docs update jobs.md

---

docs/book/src/reference/versions.md

Cherry-pick of #7194 (+ synced the versions.md in general a bit)
Fixes #

[release-1.2] 🌱 Update versions doc adding Kubernetes 1.25

---

.golangci.yml
docs/Dockerfile
test/infrastructure/docker/Dockerfile
util/conditions/matcher.go

Enables some of the "bug" finding linters in golangci-lint that are currently disabled. 
*  asasalint
* bidichk
* durationcheck
* errchkjson
https://golangci-lint.run/usage/linters/
Also fixes some findings (including Hadolint findings).
There are some bug linters that find alot more. But I will add these 1 by 1 since they require more work to review.

✨ Enable linters: asasalint, bidichk, durationcheck, errchkjson. Fix findings

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/kubeadm/internal/ignition/clc/clc.go
bootstrap/kubeadm/internal/ignition/clc/clc_test.go
docs/book/src/tasks/experimental-features/ignition.md
go.mod
go.sum
test/go.mod
test/go.sum
test/infrastructure/docker/internal/provisioning/ignition/kindadapter.go

**What this PR does / why we need it**: The flatcar-linux GitHub organization is being renamed to "flatcar". This PR updates all references accordingly.
Upstream issue: https://github.com/flatcar-linux/Flatcar/issues/836
I'm opening this PR in advance to allow quick merging once the rename occurs. I'll mark it as on hold in the meantime.
None

🌱 Update references following Flatcar GitHub org rename

---

docs/proposals/20220411-cluster-api-state-metrics.md

Syncs the cluster-api-state-metrics proposal to match implementation state.
Implementation was mostly done in #7095
This also removes the `_labels` metric references. There are kube-state-metrics specific flags regarding these metric which won't affect custom resource configuration (allow/deny-list). Exposing all metrics would lead increase the cardinality without being worth it. Use-case specific configuration should be added by the user if required.
Part of #6458

📖  Sync cluster-api-state-metrics proposal to match implementation state.

---

docs/developer/releasing.md

Just to avoid that we're doing this wrong on every release :)
Fixes #

📖 docs/releasing: add note about homebrew PR commit message

---

.golangci.yml
exp/internal/controllers/machinepool_controller.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/framework/bootstrap/kind_provider.go
test/framework/kubetest/run.go
test/infrastructure/docker/exp/internal/docker/nodepool.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Enables additional linters in the gocritic metalinter and fixes findings. 
The groups `diagnostic` and `performance`. The performance rules `rangeValCopy` and `hugeParam` are disabled due to large amount of findings. The fixes are performance types `appendCombine` and `stringXbytes`.
Reference:
https://github.com/go-critic/go-critic/blob/master/docs/overview.md

🌱 Enable more gocritic diagnostic and performance linters

---

Tiltfile

**What this PR does / why we need it**: When we deploy Cluster templates in Tilt, we aren't actually passing the `$NAMESPACE` variable configured in the UI to `clusterctl generate cluster`.

🐛 Fix bug in Tilt where Cluster template namespace is ignored

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/clusterclass.go
cmd/clusterctl/client/repository/client.go
main.go

Found a spelling mistake in the logs and making a separate pr so it can be cherry-picked into older releases.

🌱 Fix spelling in log message (cluter -> cluster)

---

docs/book/src/user/quick-start.md

Update Nutanix section in the quickstart with the link to the new official documentation website

:book: update quickstart with link to the new Nutanix doc website

---

api/v1alpha3/conversion.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha4/conversion.go
api/v1alpha4/zz_generated.conversion.go
api/v1beta1/machine_types.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
controlplane/kubeadm/api/v1alpha3/conversion.go
controlplane/kubeadm/api/v1alpha4/conversion.go
controlplane/kubeadm/api/v1alpha4/zz_generated.conversion.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
controlplane/kubeadm/api/v1beta1/zz_generated.deepcopy.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
docs/book/src/developer/architecture/controllers/control-plane.md
docs/book/src/developer/providers/v1.2-to-v1.3.md
exp/api/v1alpha3/conversion.go
exp/api/v1alpha4/conversion.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

- introduces a new timeout called `nodeVolumeDetachTimeout` to the machine and other CRDs, which can be used to wait for volume detachment to happen within the timeout limit
- introduces a new annotation called `ExcludeWaitForNodeVolumeDetachAnnotation` to be able to skip `shouldWaitForNodeVolumes` check entirely if needed
- moves out `shouldWaitForNodeVolumes` from node drain logic (`isNodeDrainAllowed`) and adds new check only for volume related checks called `isNodeVolumeDetachingAllowed` to  to keep a cleaner separation for API
- adds unit tests
- documents introduced  new timeout  `nodeVolumeDetachTimeout` and annotation `ExcludeWaitForNodeVolumeDetachAnnotation` as a breaking changes in the provider's migration v1.2 to v1.3 document
- …

✨ Add nodeVolumeDetachTimeout property to Machine

---

docs/book/src/reference/glossary.md

Adds Cluster API Provider Metal3 to the [glossary](https://cluster-api.sigs.k8s.io/reference/glossary.html#c) in the book

📖 Add CAPM3 to glossary

---

Tiltfile

Removes a hard-coded `USER` instruction in Tilt's Dockerfile that broke that workflow (at least for me). This was added in #7162. It's not clear to me what this was intended to fix in the first place, but if it's not broken...
Fixes #7263

🐛 Tiltfile: remove USER instruction from Dockerfile

---

docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/configuration.md
docs/book/src/clusterctl/overview.md

It's a doc PR that adds information about GitHub Personal Access Token to avoid rate limiting.
Fixes #7188

📖Add GitHub PAT doc

---

cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go
cmd/clusterctl/cmd/generate_cluster.go
docs/book/src/clusterctl/commands/generate-cluster.md

Support stdin as an input source for the `clusterctl generate cluster` command. See #7227 for reference.
Fixes #7227

:seedling: support clusterctl generate cluster with templates from stdin

---

cmd/clusterctl/client/cluster/template_test.go

This fixes a lint error on main that could block other PRs.
The lint error on main was introduced in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/7228
The lint job on this PR seems to be stuck in a "awaiting approval" stage and was not run on the original PR. Ref: https://github.com/kubernetes-sigs/cluster-api/actions/runs/3082322705
Fixes #

🌱 Fix the lint error on main

---

test/e2e/clusterclass_changes_test.go

While debugging test failures I saw that our test config seems to be invalid. 
The configured mount produces the following errors:
```plain
failed to create worker DockerMachine: error creating container \"clusterclass-changes-cmdpbw-md-0-lkq2j-6944fbd987-tnh24\": Error response from daemon: Duplicate mount point: /tmp","errVerbose":"Error response from daemon: Duplicate mount point: /tmp\nerror creating container
```
* => Verified error doesn't occur in the logs anymore
Fixes #

🐛 test/e2e: fix duplicate mount in CAPD test

---

test/infrastructure/docker/api/v1beta1/dockermachine_types.go
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
test/infrastructure/docker/exp/internal/docker/nodepool.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/docker/internal/docker/machine.go

Makes the machine bootstrap reentrant. Currently we might try to bootstrap a machine again even though it's already successfully bootstrapped.
Found during implementation of #7244
Fixes #

🌱 CAPD: make Machine bootstrap reentrant

---

hack/observability/loki/values.yaml

This PR increases the ingestion limits. When using log-push I noticed that most logs didn't get into Loki because of these errors:
> Push response: status: "429 Too Many Requests", body: "Ingestion rate limit exceeded for user fake (limit:
> 4194304 bytes/sec) while attempting to ingest '1000' lines totaling '755293' bytes, reduce log volume or
> contact your Loki administrator to see if the limit can be increased
Fixes #

🌱 Loki: increase Loki ingestion limits for log-push

---

docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/go.mod
test/go.sum

Just keeping kind up-to-date (v0.16. was release yesterday).
Release notes: https://github.com/kubernetes-sigs/kind/releases
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7279

🌱 Bump kind to v0.16.0

---

docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md

📖 document how to manually test Runtime Extensions

---

api/v1alpha4/conversion.go
api/v1alpha4/zz_generated.conversion.go
api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
internal/contract/controlplane.go
internal/contract/controlplane_test.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/patches/engine.go
test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml

This PR add NodeVolumeDetachTimeout support for Cluster Topology.
NodeVolumeDetachTimeout is introduced in https://github.com/kubernetes-sigs/cluster-api/pull/6413.
Fixes #7233
/hold until https://github.com/kubernetes-sigs/cluster-api/pull/6413 is merged.

✨ add NodeVolumeDetachTimeout support for Cluster Topology

---

docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md

This PR add a link to the kuberentes proxies documentation where we talk about using the kuberentes proxies to manually test runtime extension. 
Ref: https://github.com/kubernetes-sigs/cluster-api/pull/7270#discussion_r979794592
Fixes #

📖 add link to Kubernetes proxies in Runtime Extensions doc

---

CONTRIBUTING.md

As per office hours discussing clarifying backport policy for doc improvements, CI signal improvements, test framework improvements

📖 clarify backport-policy

---

OWNERS_ALIASES

PR to add myself as reviewer for docs. Just to help out with some of the simpler, more straight forward doc prs.

🌱 Add oscr to cluster-api-docs-reviewers

---

docs/book/src/reference/jobs.md

* Updating the jobs.md with the current state (after [#27621](https://github.com/kubernetes/test-infra/pull/27621))
* Adding some info about our test-infra config to reduce the amount of tribal knowledge
Fixes #

📖 book: update job documentation + add test-infra config

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Just noticed we're using an old version while working on #7297
(note: the CRDs of the providers registered in clusterctl are still valid => Pluralize didn't change)
Fixes #

🌱 Bump flect to v0.3.0

---

test/e2e/data/cni/kindnet/kindnet.yaml

Bumps the kindnet cni version used in tests to include 
- https://github.com/kubernetes-sigs/kind/pull/2941
This fixes a bug detected during working at #3728 and described in the kind PR https://github.com/kubernetes-sigs/kind/pull/2941 .
Edit: Workload clusters using kindnet are also affected from this bug and for upgrade tests the bug may cause pod-to-pod networking issues due to wrong ip routes.
Fixes #

🐛 bump kindnetd to v20220927-ce36d7c0 to fix routes on self-hosted upgrades

---

Makefile

Just to keep kpromo up-to-date. There should be nothing critical in the release: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.4.5
Fixes #

🌱 Bump kpromo to v3.4.5

---

docs/book/src/SUMMARY.md
docs/book/src/clusterctl/configuration.md

Documents migrating from a `clusterctl` managed cert-manager to user-managed.
Fixes #7280

📖 document migrating to user-managed cert-manager

---

exp/addons/api/v1beta1/clusterresourcesetbinding_types.go

The ClusterResourceSet owner references were being updated due to a typo. This update was ineffectual, because the ClusterResourceSet object is not patched after the references are updated.
However, due to a separate bug (https://github.com/kubernetes-sigs/cluster-api/pull/7309) in RemoveOwnerRef, the ClusterResourceSetBinding owner references _were_ being updated.
Fixes #

🐛 Update ClusterResourceSetBinding owner references

---

test/e2e/clusterctl_upgrade.go

Adds a `PreWaitForCluster` hook after creating the target management cluster to allow adding any custom resources that might be needed by some providers.
Adds `CNIManifestPath` as an input parameter.
Fixes  #6465

🌱 add preCreateCluster hook and CNIPath to e2e clusterctl upgrade test

---

test/e2e/clusterctl_upgrade.go

Manual cherrypick of https://github.com/kubernetes-sigs/cluster-api/pull/6636
Fixes #

🌱 add PreWaitForCluster hook and CNIPath to e2e clusterctl upgrade test

---

test/e2e/clusterctl_upgrade_test.go

The PR that yesterday introduced a new clustectl upgrade ClusterClass e2e test lead to failures in the e2e-mink8s job: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-mink8s-main
This is because the e2e-mink8s Job is using Kubernetes v1.20 and thus has ClusterTopology/ClusterClass disabled.
Usually this job skips all ClusterClass tests but only when they are tagged correctly. (GINKGO_SKIP: \[Conformance\] \[K8s-Upgrade\]|\[IPv6\]|\[ClusterClass\])
(Open https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main and grep for "[ClusterClass]" to see the other tagged jobs)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

🌱 teste/e2e: tag clusterctl ClusterClass test with [ClusterClass]

---

cmd/clusterctl/client/cluster/topology.go
docs/book/src/developer/architecture/controllers/control-plane.md
docs/book/src/developer/architecture/controllers/machine-pool.md
docs/book/src/developer/providers/bootstrap.md
docs/book/src/developer/providers/cluster-infrastructure.md
docs/book/src/developer/providers/machine-infrastructure.md
internal/test/builder/crds.go
util/contract/contract.go
util/contract/doc.go
util/util.go

For more context see the linked issue.
On a high-level the idea is to enforce a naming convention for CRDs. By doing this we can avoid having to list & cache full CRDs because we're able to just get & cache the `PartialObjectMetadata` of CRDs instead.
(see: https://github.com/kubernetes-sigs/cluster-api/blob/5b8711d471b11aa7b7f936d22c5cca92dee261f2/util/conversion/conversion.go#L64-L94)
All our currently in clusterctl registered providers have valid names. See https://gist.github.com/sbueringer/8178a1eaff59095a7c56c373da0f187e for more details (grep for ERROR). There was only one finding for Metal3, but it's not an issue as it's a CRD which is not covered by any of the contracts, i.e. used by core ClusterAPI. (cc @furkatgofurov7)
This affects the …

⚠️ contract: add CRD naming requirements

---

docs/book/src/reference/glossary.md
docs/book/src/user/concepts.md
docs/proposals/20220221-runtime-SDK.md

This PR updates the definition of provider in the glossary to include all the components that can be deployed and provides a functionality to the Cluster API management Cluster.
This acknowledges the fact that we are already using this term for many things including core provider, infra provider, bootstrap and CP providers, and makes this suitable for including IPAM providers, Cluster add-on providers, Runtime Extension providers (which is a new term being defined in the Runtime SDK proposal).
If this is accepted, this will allow us to benefit of all the clusterctl machinery and provide a consistent UX for the users

📖 Improve provider definition in the glossary

---

.github/dependabot.yml

Felt like unnecessary work to give dependabot "ok-to-test" for each pr. Better to just let it build directly.

🌱 Add ok-to-test label to dependabot prs

---

internal/controllers/topology/cluster/patches/engine.go

Stop returning a unique ID with errors from the patch engine. This ID gets turned into a condition on the object which cause infinite reconciliation of objects avoiding exponential backoff.
Fixes #7337

:bug: Remove unique patch ID from TopologyReconcile conditions

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

Makes KCP diskSetup field mutable. 
Needed if you want to to alter the disk layout for new control-plane nodes.

:seedling: Make KCP diskSetup field mutable

---

controllers/remote/cluster_cache_tracker.go

This fixes unnecessary delays in self-repair when the underlying provider (e.g. the AWS provider) performs periodic kubeconfig refreshes. Without this, the health check is retried 10 times with a 10s interval, meaning that the controller is unable to act for at least 100 seconds, even though it could repair itself immediately.

:bug: Don't retry health check when Unauthorized is returned

---

docs/book/src/developer/providers/v1.2-to-v1.3.md
test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/bases/md.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
test/e2e/self_hosted.go
test/e2e/self_hosted_test.go
test/framework/cluster_proxy.go
test/framework/clusterctl/client.go
test/framework/clusterctl/clusterctl_helpers.go
test/framework/convenience.go

* Adds an cluster upgrade to self-hosted test as additional step
* Allows to configure the number of nodes for testing ha and non-ha self-hosted clusters
Fixes #3728

✨ adjust self-hosted e2e test to also upgrade the cluster

---

cmd/clusterctl/client/config/cert_manager_client.go
cmd/clusterctl/client/config/cert_manager_client_test.go
cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/client/config/providers_client_test.go
cmd/clusterctl/client/repository/overrides.go
cmd/clusterctl/client/repository/overrides_test.go
docs/book/src/clusterctl/configuration.md

Manual cherry-pick of #7343
Fixes #

[release-1.2] 🌱 clusterctl: support envsubst in clusterctl config 

---

docs/book/src/tasks/experimental-features/machine-pools.md

📖 Add side-by-side comparison of MachinePools and MachineDeployments in docs

---

cmd/clusterctl/client/repository/overrides.go
cmd/clusterctl/client/repository/repository_local.go

We have ~ the same code in `newLocalRepository` apparently just never noticed that it's missing for `overridesFolder`
Fixes #

🐛 clusterctl: support Windows paths in overridesFolder

---

cmd/clusterctl/client/clusterclass.go
docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/proposals/20210526-cluster-class-and-managed-topologies.md

Fix a few typos across the code in the word Cluster and the word through.
Fixes #

📖  Fix typos in word Cluster and through

---

docs/book/src/developer/providers/v1.2-to-v1.3.md

Just noticed the ginkgo/gomega versions has been bumped but the release not doesn't reflect this update.
Fixes #

📖 Fix correct ginkgo and gomega verison in release notes

---

docs/book/src/user/quick-start.md

I have added a single-line Linux command (will make the file executable and will move it to the desired location ) . which performed the installation of the clusterctl. After downloading the clusterctl binary file , the User can install it by running this single-line command. Earlier we were doing it by making it executable and then moving it. 
It will be user friendly. 
Install clusterctl
```
sudo install -o root -g root -m 0755 clusterctl /usr/local/bin/clusterctl
```
Fixes #7372

📖  Added a single line linux command in quick-start for installing clusterctl 

---

Makefile
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-topology-single-node-cluster/disable-control-plane-taint-variable.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-topology-single-node-cluster/kustomization.yaml
test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
test/e2e/self_hosted_test.go

Adds an E2E test for Single Node Cluster (1x control-plane, 0x workers) self-hosted scale-out upgrades.
Fixes #7230

🌱 Implement single-node cluster self-hosted upgrade test

---

docs/proposals/20220712-cluster-api-addon-orchestration.md

📖 Cluster API Add-on Orchestration proposal

---

docs/proposals/20200220-cluster-resource-set.md

Adds a new mode to CRS that allows continuous reconciliation of resources defined in a CRS. 
This is useful to update objects managed by a CRS after they have already been created (think upgrades).
Co-authors:
@alejandroEsc
@joejulian 
Related to #4807

:book: Amend CRS proposal to include Reconcile mode

---

docs/book/src/clusterctl/developers.md
docs/book/src/user/quick-start.md

Update the quick start to point Docker provider users to `kind` when retrieving the kubeconfig for their workload cluster. This will avoid users, especially on Windows and MacOS, from having to use the sed script (or Windows alternative) to update the config retrieved by clusterctl.
Related to https://github.com/kubernetes-sigs/cluster-api/issues/5263

:book: Add Docker specific get kubeconfig to quickstart

---

test/e2e/clusterctl_upgrade.go
test/framework/clusterctl/client.go
test/framework/clusterctl/clusterctl_helpers.go

Add custom upgrade option to `UpgradeManagementClusterAndWait`
Fixes # [7311](https://github.com/kubernetes-sigs/cluster-api/issues/7311)

🌱 Add custom upgrade option to e2e

---

api/v1alpha4/conversion.go
api/v1alpha4/zz_generated.conversion.go
api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml

:sparkles: Add topology field for MinReadySeconds

---

cmd/clusterctl/client/repository/overrides.go
docs/book/src/developer/providers/v1.2-to-v1.3.md

Follow-up to #7343
We didn't change this in #7343 because we wanted to cherry-pick #7343 into release-1.2

🌱 clusterctl: adjust Overrider interface so Path can return an error

---

cmd/clusterctl/cmd/describe_cluster.go

Change the behaviour of the color flag in `clusterctl describe cluster`.
Previous behaviour: If true turn color on. If false no-op.
New behaviour: If true turn color on. If false turn color off. If unset no-op.
Related to #7381 

:bug: Fix/clusterctl describe color

---

hack/ensure-kind.sh

**What this PR does / why we need it**: Remove extra slash in hack/ensure-kind script where `chmod +x "${GOPATH_BIN}/kind"` resolves to `<some-path>/go/bin//kind`. I don't think it causes a bug but it's probably unintended.
Fixes #

🐛 Remove extra slash in hack/ensure-kind script

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager from v1.9.1 -> v1.10.0
Fixes #7416

✨ Update cert-manager version (v1.9.1 -> v1.10.0)

---

cmd/clusterctl/client/cluster/crd_migration_test.go
controllers/alias.go
go.mod
hack/tools/go.mod
hack/tools/tilt-prepare/main.go
internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go

Ensures we use the Go SDK context package consistently.
Fixes #

🌱 Use the Go SDK context package consistently

---

docs/book/src/security/pod-security-standards.md
docs/book/src/tasks/control-plane/kubeadm-control-plane.md
docs/book/src/tasks/updating-machine-templates.md

Fix some broken links caused by a reorganisation of the book.

:book: Fix broken book links

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

Before this PR the certificatesExpiryDays field was not mutable. Thus it was not possible to use this feature on pre-existing Clusters (/KCPs)
Verified locally as well, it works now.
Fixes #

🌱 KCP: make rolloutBefore.certificatesExpiryDays mutable

---

docs/proposals/20220927-label-sync-between-machine-and-nodes.md

This Proposal takes over from the work in https://github.com/kubernetes-sigs/cluster-api/pull/6255 and focuses on defining how labels propagate from Machine to node.
With the "divide and conquer" principle in mind following related concerns are going to be addressed in separated, complementary efforts:
- Define how labels propagate from ClusterClass to KCP/MachineDeployments/Machine Pools and down to Machines
- Define how to prevent that label propagation triggers unnecessary rollouts
Rif https://github.com/kubernetes-sigs/cluster-api/issues/493
cc @Arvinderpal @enxebre @sbueringer @vincepri

📖 Label Sync Between Machine and underlying Kubernetes Nodes

---

.golangci.yml
api/v1alpha4/common_types.go
api/v1beta1/common_types.go
api/v1beta1/condition_consts.go
bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
cmd/clusterctl/api/v1alpha3/provider_type.go
cmd/clusterctl/client/client.go
cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/move.go
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
cmd/clusterctl/config/manifest/clusterctl-api.yaml
controllers/external/util.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
test/infrastructure/docker/api/v1beta1/dockermachine_types.go
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go

Update the "Deprecated" comments in CAPI to make them visible to the staticcheck linter.
[staticcheck requires a new paragraph to properly identify a field/function/method/struct as deprecated](https://github.com/golang/go/wiki/Deprecated#examples): 
> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with Deprecated: followed by some information about the deprecation, and a recommendation on what to use instead, if applicable.

:seedling: Update Deprecated comments to correctly trigger staticcheck linter

---

docs/book/src/SUMMARY.md
docs/book/src/tasks/multiple-providers.md

Explicitly highlight in the documentation that CAPI supports running multiple providers on the same management cluster.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7234

📖 Document multiple providers support

---

Makefile

Moves the generate-e2e-templates target into the generate section of the makefile

🌱 Move make target

---

docs/book/src/developer/architecture/controllers/cluster.md
docs/book/src/developer/architecture/controllers/machine.md
docs/book/src/developer/providers/cluster-infrastructure.md
docs/book/src/developer/providers/machine-infrastructure.md

**What this PR does / why we need it**: Update optional fields in docs for Machine and Cluster controllers
Fixes #7300 #7301

📖 Update optional fields in docs for Machine and Cluster controllers

---

.golangci.yml
exp/addons/internal/controllers/clusterresourceset_controller_test.go
internal/controllers/machine/machine_controller_test.go
util/patch/patch_test.go
util/version/version.go

We are currently using the default revive linter checks. However if you explicitly enable an additional rule the default rules are disabled. So by explicitly setting the revive rules we can add additional interesting checks.
I selected to add most of the [recommended rules](https://github.com/mgechev/revive#recommended-configuration) instead of the [default rules](https://github.com/mgechev/revive/blob/master/defaults.toml). I commented out some of the recommended checks because of the large amount of findings. I also added a section for additional checks that we might be interested in.
The code changes are to resolve the following findings by the new revive checks:
```
util/version/version.go:109:10: superfluous-else: if block ends with a continue …
```

✨ golangci-lint enable most recommended revive checks and fix findings

---

Makefile

When running golangci-lint in for example test directory, findings are returned with paths based on where golangci-lint was run. For example when running in `test` you get:
```
framework/clusterctl/logger/logger.go:38:23: unused-parameter: parameter 'info' seems to be unused, consider removing or renaming it as _ (revive)
func (l *logger) Init(info logr.RuntimeInfo) {
^
framework/clusterctl/logger/logger.go:41:26: unused-parameter: parameter 'level' seems to be unused, consider removing or renaming it as _ (revive)
func (l *logger) Enabled(level int) bool {
^
```
Note that the `test` directory is missing from the path `framework/clusterctl/logger/logger.go` 
However by setting setting path-prefix we get the full path. Like this:
``` …
```

🌱 Set golangci-lint path-prefix when linting test and hack/tools

---

Makefile
docs/book/src/developer/providers/v1.2-to-v1.3.md

A simple dependency bump to keep it up to date. Updates go-apidiff version from 0.4.0 -> 0.5.0
Fixes #

✨ Update github.com/joelanford/go-apidiff version (0.4.0 -> 0.5.0)

---

docs/book/src/clusterctl/configuration.md

`kubectl get all -A` doesn't actually return all resources, see https://github.com/kubernetes/kubectl/issues/151. This command should now cover all the CAPI mangaed `cert-manager` resources.

📖 update cert-manager label searching command

---

cmd/clusterctl/client/cluster/mover.go
docs/book/src/clusterctl/commands/delete.md
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
hack/tools/runtime-openapi-gen/vendored_openapi.go

Reading the clusterctl documentation I noticed an extra space before a comma. So I searched for more occurrences and fixed them.
Fixes #

📖 grammar: remove extra space before comma and punctuation

---

docs/book/src/SUMMARY.md
docs/book/src/reference/api_reference.md
docs/book/src/reference/labels_and_annotations.md

I have added all the supported labels and annotation in a single refrence document.  I have added a .md file in refrence section , which contains two tables one for labels and another for annotations. 
Fixes #5394

:book:added supported labels and annotations refrence document

---

api/v1alpha4/conversion.go
api/v1alpha4/zz_generated.conversion.go
api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml

:sparkles: Add Cluster topology field for MachineDeployment Strategy

---

internal/contract/bootstrap.go
internal/contract/bootstrap_test.go
internal/contract/controlplane.go
internal/contract/controlplane_test.go
internal/contract/infrastructure_cluster.go
internal/contract/infrastructure_cluster_test.go
internal/contract/infrastructure_machine.go
internal/contract/infrastructure_machine_test.go
internal/contract/types.go

**What this PR does / why we need it**: As described in #5309, we're going through `internal/contract` package and updating it to match the specifications in the docs.
Fixes #7119 #7120

🌱 Update contract package to match documentation

---

internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
test/infrastructure/docker/internal/docker/machine.go

🌱 MHC: Drop Reconciling log, CAPD: log image name during preload

---

Makefile
hack/ensure-go.sh
hack/ensure-golangci-lint.sh
hack/ensure-kind.sh
hack/ensure-kubectl.sh
hack/get-project-maintainers.sh
hack/kind-install-for-capd.sh
hack/pin-dependency.sh
hack/setup-envtest-with-kind.sh
hack/verify-boilerplate.sh
hack/verify-capi-book-summary.sh
hack/verify-doctoc.sh
hack/verify-shellcheck.sh
hack/verify-starlark.sh
hack/version.sh

This pr adds an environment variable to toggle shell script tracing. This is something I often turn by hand but never considered to automate until I read: https://sharats.me/posts/shell-script-best-practices/ I also added it to the Makefile allowing it to be simply toggled using make.
Case: variable set but disabled 
```
$ TRACE=0 make verify-shellcheck
TRACE=0 ./hack/verify-shellcheck.sh
Running shellcheck...
Cleaning up...
```
Case: no variable set
```
$ make verify-shellcheck
TRACE=0 ./hack/verify-shellcheck.sh
Running shellcheck...
Cleaning up...
```
Case: variable set and enabled
```
$ TRACE=1 make verify-shellcheck
+ version::ldflags
+ version::get_version_vars
++ git rev-parse 'HEAD^{commit}'
+ …
```

✨ Add environment variable to enable tracing for hack/ shell scripts

---

docs/book/src/security/pod-security-standards.md
test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
test/infrastructure/docker/config/default/namespace.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

Enables baseline Pod Security Admission enforcement to ensure compatibility to baseline enforced clusters.
Fixes #7429

🌱 CAPD: enable baseline pod security admission for clusterclass tests

---

controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
test/framework/daemonset_helpers.go

Before this PR we started using the new registry with Kubernetes 1.25.
Given:
* that the new registry is cheaper for the project and
* there's an upstream effort (kubeadm) to backport the registry change back until v1.22 
let's align and already use the new registry for Kubernetes >= v1.22
Fixes #7472

🌱 KCP: use new registry for Kubernetes >= v1.22

---

.github/workflows/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/lint-docs-pr.yaml
.github/workflows/lint-docs-weekly.yml
.github/workflows/release.yml

Pin GitHub actions to commit SHAs to fix https://github.com/kubernetes-sigs/cluster-api/issues/7466
Got all actions commits SHAs from:
- actions/setup-go: https://github.com/actions/setup-go/commits/v3.3.0
- actions/checkout: https://github.com/actions/checkout/commits/v3.0.2
- actions/cache: https://github.com/actions/cache/commits/v3.0.11
- EndBug/add-and-commit: https://github.com/EndBug/add-and-commit/commits/v9.1.0
- golangci/golangci-lint-action: https://github.com/golangci/golangci-lint-action/commits/v3.3.0
- gaurav-nelson/github-action-markdown-link-check: https://github.com/gaurav-nelson/github-action-markdown-link-check/commits/v1
- softprops/action-gh-release: https://github.com/softprops/action-gh-release/commits/v1
**Which issue(s) …

:seedling: Pin GitHub actions to commit SHAs

---

internal/controllers/machine/machine_controller_phases.go

[release-1.2] 🐛 Ensure Kubeadmconfig is reconciled after datasecretname is set

---

api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
internal/topology/variables/cluster_variable_validation.go
internal/topology/variables/cluster_variable_validation_test.go
internal/topology/variables/schema.go

This PR improves the validation of variable values. The validating webhook will now return validation errors if nested fields in variable objects are not defined in the schema.
If users encounter those validation errors they have the following options:
* update the variable schema in the ClusterClass to either add the missing fields or x-kubernetes-preserve-unknown-fields
* update the variable in the Cluster to drop the unknown fields
Fixes #6135

⚠️ ClusterClass: validate unknown fields in variable values

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
main.go
util/flags/tls.go

This patch introduces two new flags to configure TLS options on the managers:
1. --tls-min-version which is used to set the minimum TLS version in use by the webhook server.
2. --tls-cipher-suites which is used to set the TLS cipher suites in use by the webhook server.
The minimum TLS version defaults to 1.2
Fixes #6511

⚠️  Adds TLS options to managers

---

cmd/clusterctl/client/cluster/mover.go

This PR patches the managed fields so that clusterctl does not own all the fields in the object.
Note: The last step of `move` is unpausing the cluster. So clusterctl still ownes the `.spec.paused` field on the Clusters and the `cluster.x-k8s.io/paused` annotation on the ClusterClasses. 
So if someone tries to unpause the cluster using SSA it will throw a conflict. 
```
❯ k --kubeconfig docker-cluster-one.kubeconfig apply -f cluster-unpuase.yaml --server-side=true
error: Apply failed with 1 conflict: conflict with "clusterctl" using cluster.x-k8s.io/v1beta1: .spec.paused
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the …
```

🐛 patch managed fields after `clusterctl move` so that it does not own all fields

---

api/v1beta1/machinehealthcheck_webhook.go
api/v1beta1/machinehealthcheck_webhook_test.go
internal/webhooks/cluster.go
internal/webhooks/clusterclass.go
internal/webhooks/clusterclass_test.go

Add validation for nodeStartupTimeout on cluster creation. Merge MHC validation into a single function in the MHC api definition which can then be used for common validation no matter if the MHC is defined in the Cluster topology, the ClusterClass or an individuation MHC object.

:bug: Improve MHC validation for topology-managed MHC

---

cmd/clusterctl/cmd/describe_cluster.go
cmd/clusterctl/cmd/generate_cluster.go
cmd/clusterctl/cmd/get_kubeconfig.go

For example when running `clusterctl generate cluster --help`, usage is described as:
```
Usage:
clusterctl generate cluster [flags]
```
However, if you attempt to run the given example you will get an error.
```
clusterctl generate cluster
Error: accepts 1 arg(s), received 0
```
Since the command has a required argument, updated the usage to reflect the required arguments. For example:
```
Usage:
clusterctl generate cluster NAME [flags]
```
Similar improvement has been applied in the usage text of `generate cluster`, `describe cluster` and `get kubeconfig` 
Fixes #6867

:seedling: Improved the usage to reflect the required arguments in `generate cluster`, `describe cluster` and `get kubeconfig`

---

docs/book/src/developer/providers/v1.2-to-v1.3.md

This PR adds the webhook TLS configuration info and utility function usage suggestion to the migration docs.
Fixes n/a
Checkout [this comment](https://github.com/kubernetes-sigs/cluster-api/pull/7483#issuecomment-1304090680) for background on this PR

📖 Adds webhook TLS config info to the migration doc

---

controlplane/kubeadm/internal/controllers/controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/patches/engine.go
test/extension/handlers/topologymutation/handler.go

Was debugging ClusterCacheTracker and found log statements with 20 Machines as k/v pairs.
Fixes #

🐛 logging: Avoid adding multiple objects to the same logger in for loops

---

internal/controllers/machine/machine_controller.go
internal/controllers/machineset/machineset_controller.go

This PR prevents adoption for stand-alone objects to add Cluster owner reference for objects generated by MachineDeployments
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7529

🐛 Adoption for stand-alone objects should ignore objects generated by MachineDeployments

---

controllers/remote/cluster_cache_healthcheck_test.go
controllers/remote/cluster_cache_tracker.go
controllers/remote/keyedmutex.go
controllers/remote/keyedmutex_test.go
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Co-authored-by: Florian Gutmann <fgutmann@amazon.com>
This PR builds on top of #6380. All credits to @fgutmann for the initial implementation.
As of today we have a global lock, which means that as soon as the clusterAccessor creation doesn't work quickly all workers of our reconcilers are blocked. This is most problematic with the Machine reconciler as usually the Machines have the highest cardinality. If the apiserver of a cluster is not reachable or slow it can take up to 10 seconds until the global lock is unlocked again. In this time no one else is able to create or retrieve a client for workload clusters.
Let's assume Cluster1 has 250 Machines and is not reachable and Cluster2 has 10 Machines and is reachable.
This leads to the following …

🌱 ClusterCacheTracker: use non-blocking per-cluster locking

---

cmd/clusterctl/client/init.go

- Add ProviderCRDInstalled field in InitOptions
- In setupInstaller check if ProviderCRDInstalled is installed or not
- If yes return normal error
- If not return empty provider list
Fixes #6986

🐛 `clusterctl init --list-images` should not need an initialized cluster

---

cmd/clusterctl/client/config/cert_manager.go
cmd/clusterctl/client/config/cert_manager_client.go
cmd/clusterctl/client/repository/goproxy.go
cmd/clusterctl/client/repository/goproxy_test.go
cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/overview.md
docs/book/src/clusterctl/provider-contract.md

Reduce github api requests in clusterctl
* Removes additional cert-manager latest version detection because it always gets overwritten afterwards anyway.
* Uses goproxy instead of github api for listing repository versions.
Part of #3982

✨ Reduce github api requests in clusterctl by querying go modules

---

controllers/remote/cluster_cache_healthcheck_test.go
controllers/remote/cluster_cache_tracker.go
controllers/remote/keyedmutex.go
controllers/remote/keyedmutex_test.go
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Co-authored-by: Florian Gutmann <fgutmann@amazon.com>
Cherry-pick of: #7537
Fixes #

[release-1.2] 🌱 ClusterCacheTracker: non-blocking per-cluster locking

---

test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml

Update the e2e test config to use components from the v1.2.5 release.

🌱 Update e2e components to v1.2.5

---

docs/book/src/user/quick-start.md

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
This PR add many details for the quickstart guide, to explain how to deploy a guest cluster using the KubeVirt provider.

:book: Add the quickstart details for KubeVirt

---

docs/release/release-cycle.md

As discussed yesterday (9th November) in the office hours.
Fixes #

📖 docs: Add note about dependency bumps to Beta change policy

---

CONTRIBUTING.md

With this PR we prevent suddenly dropping support for the current CAPI minor release when a new one is created 
Note: we are going to support n and n-1 only for the current API version, while for the older API version we are going to support only a minor release

✨ Update support policy

---

docs/book/src/user/quick-start.md

Throughout this document, Linux is typically spelled with an uppercase L. Fix few lowercase spellings for consistency (and better English, I suppose).

📖 quickstart: consistent Linux captialization

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/kubernetes_bump.md
.github/ISSUE_TEMPLATE/release_tracking.md
CONTRIBUTING.md
docs/release/release-1.3.md
docs/release/release-1.4.md
docs/release/release-tasks.md

This PR documents the Kubernetes bump via an issue template and also fixes the links to my fork introduced in #7499.
Examples:
* Create issue: https://github.com/sbueringer/cluster-api/issues/new/choose
* Example issue: https://github.com/sbueringer/cluster-api/issues/83
Fixes #7389

📖 Add issue template for Kubernetes bumps, fix links to fork

---

Makefile
docs/book/src/developer/providers/v1.2-to-v1.3.md

Looks like the last time we bumped ginkgo we forgot to bump the binary used in e2e as well.
Fixes #7577

🌱 test/e2e: bump ginkgo binary to v2.5.0

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/clusterctl/client/repository/goproxy.go

Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
- Introduce additional linters & bump golangci-lint to 1.50.1
Here are the descriptions of the new linters this PR proposes to add:
- decorder: check declaration order and count of types, constants, variables and functions [fast: true, auto-fix: false]
- execinquery: execinquery is a linter about query string checker in Query function which reads your Go src files and warning it finds [fast: false, auto-fix: false]
- nosprintfhostport: Checks for misuse of Sprintf to construct a host with port in a URL. [fast: true, auto-fix: false]
- reassign: Checks that package variables are not reassigned [fast: false, auto-fix: false]
- usestdlibvars: A linter that detect the possibility to use …

:sparkles: Introduce additional linters & bump golangci-lint to 1.50.1

---

Tiltfile
docs/book/src/developer/tilt.md

The PR removes the writing of `os.environment` by passing the `env` parameter in `cmd_button`
A new function called `dictonary_to_list_of_string` is added because the `env` parameter of `cmd_button` requires a list of strings of format `"name=value"`. Eg: ["env1=val1", "env2=val2"]
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7430

:sparkles: Removed the writing of os.environment by passing the 'env' parameter in cmd_button

---

internal/controllers/machinedeployment/machinedeployment_controller_test.go

Extracted from #7591 to make clear that the unit test validation was broken before any prod code changes.
Fixes #

🌱 MD reconciler: improve integration test

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go

Just found a bit of code in KCP that apparently nobody really uses :)
Happy to keep some or all of the funcs if we think there's a good reason for it
Follow-up:
Fixes #

🌱 KCP: remove unused code

---

internal/webhooks/test/clusterclass_test.go

Add a `DeleteAndWait` function to our test package which allows waiting until an object is deleting before moving on.
Fixes flake in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/7587/pull-cluster-api-test-main/1595021734782701568

:bug: Add CleanupAndWait call for flaky ClusterClass test

---

exp/addons/internal/controllers/clusterresourceset_controller.go

Ensure Resources owned by a ClusterResourceSet will be adopted on reconciles where the resource isn't applied.
Part of #7575

:bug: Fix adopting ClusterResourceSet resource by CRS when already applied

---

api/v1beta1/machine_types.go
controlplane/kubeadm/internal/cluster_labels.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machineset/machineset_controller.go

Kudos to @fabriziopandini for the initial 80% of the PR :) 
The expected behavior after this PR is roughly:
* KCP: Machines will now have:
* MachineSet:
* Machine:
(all also manually verified)
Fixes #7529

🐛 Fix Machine adoption for KCP/MachineSet-owned Machines

---

Makefile

Exploring a way to avoid having to hardcode dependency versions in the Makefile that already exist in `go.mod`. 
This would allow having dependabot bump these dependencies automatically to get a) notification of new versions b) knowledge of breakage asap. 
Fixes #

✨ Get Ginkgo version in Makefile from go.mod

---

.github/dependabot.yml

🌱 Automate go dependency bumps (except CR/k8s.io)

---

internal/controllers/machine/machine_controller_phases.go
internal/controllers/machineset/machineset_controller_test.go

Ensure non-Machine controller OwnerReferences are always removed from infrastructure and bootstrap objects that reference those machines.
The direct impact of this is that the KubeadmControlPlane and MachineSet will no longer own infrastructure and bootstrap objects.
This currently includes https://github.com/kubernetes-sigs/cluster-api/pull/7591
Part of #7575

:seedling: Ensure infra and bootstrap objects are owned by Machines

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

Makes KCP skipPhases field mutable, needed in cases like disabling kube-proxy deployment on an existing cluster.
Signed-off-by: Jim Ntosas <ntosas@gmail.com>

:sparkles: [kcp] Make kcp.skipPhases field mutable

---

Makefile

Adds make target `release-manifests-all` to generate all the release manifests independently of `make release`
This PR helps the users and developers as `make release-binaries` takes considerable time.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/6975

:sparkles: Adds a make target to generate all the release manifests

---

test/e2e/clusterctl_upgrade.go

Support specifying the initial versions for providers in the e2e clusterctl upgrade test.
Fixes #7603

🌱 e2e: add init versions for providers

---

docs/book/src/reference/versions.md

Adds Cluster API 1.4 and Kubernetes 1.26 ([released 8DEC](https://www.kubernetes.dev/resources/release/)) to the supported versions page.  
Partof #7672

📖 docs: add Cluster API 1.4 and Kubernetes 1.26 to supported versions page

---

.golangci.yml
cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/proxy.go
hack/tools/mdbook/tabulate/tabulate.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/runtime/client/client.go

Enables the revive `if-return` check and fixes the findings. 
```
internal/controllers/clusterclass/clusterclass_controller_test.go:128:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
if err := referenceExistsWithCorrectKindAndAPIVersion(actualClusterClass.Spec.Infrastructure.Ref,
builder.GenericInfrastructureClusterTemplateKind,
builder.InfrastructureGroupVersion); err != nil {
return err
}
internal/controllers/clusterclass/clusterclass_controller_test.go:227:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
if err := referenceExistsWithCorrectKindAndAPIVersion(mdClass.Template.Bootstrap.Ref,
builder.GenericBootstrapConfigTemplateKind,
builder.BootstrapGroupVersion); err != …
```

🌱 lint: enable revive if-return check and fix findings

---

Makefile

This PR fixes `make promote-images` so that it can also be used if the origin URL is ssh style (`git@github.com:<user-name>/cluster-api.git`). 
Currently this only works if the user uses a `https://` style URL and the user will have to manually set `export USER_FORK=<username>` to bypass this problem otherwise.
Fixes #

🌱 `make promote-images` should also work if the user uses a SSH style URL

---

cmd/clusterctl/client/client.go
cmd/clusterctl/client/upgrade.go
cmd/clusterctl/client/upgrade_test.go
cmd/clusterctl/cmd/upgrade_apply.go
docs/book/src/clusterctl/commands/upgrade.md
docs/book/src/developer/providers/v1.3-to-v1.4.md

Here is the shorted output of a script that creates a quickstart cluster and then performs a `clusterctl upgrade` with the improved syntax.
```
(... a new cluster )
+ ../bin/clusterctl upgrade plan
Checking cert-manager version...
Cert-Manager will be upgraded from "v1.5.3" to "v1.9.1"
Checking new release availability...
Latest release available for the v1beta1 API Version of Cluster API (contract):
NAME                    NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm       capi-kubeadm-bootstrap-system       BootstrapProvider        v1.0.5            v1.2.2
control-plane-kubeadm   capi-kubeadm-control-plane-system   ControlPlaneProvider     v1.0.5            v1.2.2
cluster-api …
```

✨ Improve clusterctl upgrade syntax. Don't require namespace

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Update cert-manger to v1.10.1. 
Fixes #7702

:seedling: Update cert-manager to v1.10.1

---

docs/book/src/developer/providers/v1.2-to-v1.3.md

Update cert manager version in the migration doc. Related to version bump in #7705

:book: Update cert manager version in migration doc

---

docs/book/src/developer/guide.md
docs/proposals/20220414-runtime-hooks.md

Fix two of broken links in the book.

:book: Fix broken links in book

---

docs/book/src/user/quick-start.md
hack/tools/mdbook/releaselink/releaselink.go
internal/goproxy/doc.go
internal/goproxy/goproxy.go
internal/goproxy/goproxy_test.go

* Fixes goproxy for `releaselink` to also list versions > v1
Cherry-picks #7709 for releaselink only
cc @fabriziopandini 
Fixes #

[release-1.2] 🐛 releaselink: fix goproxy to also return versions for major > 1

---

api/v1beta1/machinedeployment_webhook.go
api/v1beta1/machinedeployment_webhook_test.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Add an explicit check to ensure the length of the names for Cluster and MachineDeployment is valid as a label value - i.e. less than or equal to 63 characters. These names are currently used as label values so this is not expected to be a breaking change. 
Part of #7710

:seedling: Add explicit length check for cluster and md names

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go

This PR prevents KCP to reconcile certificate expiration if the control plane is not yet initialized, thus getting rid of some noisy errors in the logs.

🌱 KCP should avoid to reconcile certificates too early

---

go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Manual update of dependeabot PR.
Bumps [github.com/onsi/ginkgo/v2](https://github.com/onsi/ginkgo) from 2.5.1 to 2.6.0.
- [Release notes](https://github.com/onsi/ginkgo/releases)
- [Changelog](https://github.com/onsi/ginkgo/blob/master/CHANGELOG.md)
- [Commits](https://github.com/onsi/ginkgo/compare/v2.5.1...v2.6.0)
---
updated-dependencies:
- dependency-name: github.com/onsi/ginkgo/v2 dependency-type: direct:production update-type: version-update:semver-minor ...
Signed-off-by: dependabot[bot] <support@github.com>
Fixes #

:seedling: Bump github.com/onsi/ginkgo/v2 from 2.5.1 to 2.6.0

---

Makefile
hack/verify-shellcheck.sh

* Updates shellcheck version to latest and greatest (0.8.0 -> 0.9.0)
* Moves the version from the verify-shellcheck script to the Makefile

🌱 Bump shellcheck version (0.8.0 -> 0.9.0)

---

api/v1beta1/machine_types.go
api/v1beta1/machineset_webhook.go
controlplane/kubeadm/internal/cluster_labels.go
controlplane/kubeadm/internal/controllers/controller.go
docs/book/src/reference/labels_and_annotations.md
internal/controllers/machineset/machineset_controller.go
internal/labels/helpers.go
internal/labels/helpers_test.go

[release-1.2] 🐛 Add name hashing for long MS names

---

api/v1beta1/machinedeployment_webhook.go
api/v1beta1/machinedeployment_webhook_test.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7712

[release-1.2] 🌱 Add explicit length check for cluster and md names

---

go.mod
go.sum
hack/tools/go.sum
test/go.mod
test/go.sum

Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7735
Fixes #

[release-1.3] :seedling:  Bump github.com/onsi/ginkgo/v2 from 2.5.0 to 2.6.0

---

.github/workflows/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/lint-docs-pr.yaml
.github/workflows/lint-docs-weekly.yml
.github/workflows/release.yml

Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7733/files

[release-1.2] :seedling: Bump actions/checkout from 3.0 to 3.2

---

hack/ensure-golangci-lint.sh
hack/verify-shellcheck.sh

The verify-shellcheck script exited after grep didn't find any matches. This fix enables the script to continue. 
Also fixes the findings that causes the pr #7749 to fail.
Fixes #

🌱 Fix verify-shellcheck script and fix findings

---

internal/labels/helpers.go
internal/labels/helpers_test.go

Add a deterministic suffix and prefix to the label hash to signal it is a hash value and ensure it always follows validity rules.

:bug: Add deterministic prefix and suffix to label hash

---

docs/book/src/user/quick-start.md

Adds all architectures ([listed in Makefile](https://github.com/kubernetes-sigs/cluster-api/blob/97573c15810fc2ae279d7d44e788139307dc9432/Makefile#L911-L917)) to the Quick Start docs.
Fixes #

📖 book: add download links for all clusterctl architectures to quick start

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

This PR update the golang.org/x/net version to v0.4.0 to address [CVE-2022-41717](https://avd.aquasec.com/nvd/2022/cve-2022-41717/).
Fixes #

🌱 update golang.org//x/net to v0.4.0

---

test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
test/framework/daemonset_helpers.go

Remove setting of the registry in the 1.1 CAPI e2e tests. 
Fixes #7768

[release-1.1] :bug: Remove registry defaulting from e2e tests

---

Makefile
hack/verify-shellcheck.sh

This is a manual cherry-pick of #7737 
Fixes #

[release-1.2] :seedling: Bump shellcheck version (0.7.0 -> 0.9.0) 

---

.gitignore
hack/boilerplate/boilerplate.py
hack/verify-shellcheck.sh

Clean up special handling for the tilt_modules folder as there is no more tilt_modules folder in the project.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7773

:seedling: Cleanup special handling for tilt_modules folder

---

cmd/clusterctl/cmd/alpha.go
cmd/clusterctl/cmd/backup.go
cmd/clusterctl/cmd/completion.go
cmd/clusterctl/cmd/config.go
cmd/clusterctl/cmd/delete.go
cmd/clusterctl/cmd/describe.go
cmd/clusterctl/cmd/generate.go
cmd/clusterctl/cmd/get.go
cmd/clusterctl/cmd/init.go
cmd/clusterctl/cmd/move.go
cmd/clusterctl/cmd/restore.go
cmd/clusterctl/cmd/root.go
cmd/clusterctl/cmd/upgrade.go
cmd/clusterctl/cmd/version.go

Improves the clusterctl command overview by grouping the commands. I opted to create two groups: "Management commands" and "Other commands". **I welcome any feedback regarding the names.**
This feature would also allow the flattening of the command structure in the future. For example the alpha commands could be placed under a "Alpha commands" group and displayed immediately under the help command. 
New clusterctl output:
```
Cluster Management Commands:
delete      Delete one or more providers from the management cluster
generate    Generate yaml using clusterctl yaml processor
get         Get info from a management or workload cluster
init        Initialize a management cluster
move        Move Cluster API objects and all dependencies between …
```

✨ clusterctl: add command groups

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/filters.go

The [MachinesNeedingRollout](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/control_plane.go#L254) and the [UpToDateMachines](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/control_plane.go#L271) functions in `controlplane/kubeadm/internal/` use multiple filters in combination to determine if the machine needs rollout.
[NeedsRollout](https://github.com/dharmicksai/cluster-api/blob/NeedsRollout/controlplane/kubeadm/internal/filters.go#L47) filter contains the list of filters that are used to determine if a machine needs rollout. Now the NeedsRollout filter is used as a single filter in both functions to determine if a machine needs rollout.
**Which issue(s) this PR …

🌱 New Filter NeedsRollout to determine if a machine needs rollout.

---

Tiltfile

this prevents tilt to show templates and cluster classes for providers not currently enabled

🌱 Tilt must show templates for enabled providers only

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
docs/proposals/20210526-cluster-class-and-managed-topologies.md
docs/proposals/images/runtime-hooks/runtime-hooks-openapi.yaml

This PR updates the godoc comment of the MD replicas field in Cluster.spec.topology to reflect hat we are actually defautling to 1 and not 0.
Fixes #

🌱 Cluster topology: fix comment about MD replicas defaulting

---

docs/book/src/developer/tilt.md

Signed-off-by: Benjamin Gentil <benjamin.gentil@infomaniak.com>
**What this PR does / why we need it**: this fixes a duplicate key in the `tilt-provider.yaml` example
Fixes #

:book: docs/tilt: fix duplicate key in tilt-provider.yaml

---

.github/ISSUE_TEMPLATE/failing-test.md
.github/ISSUE_TEMPLATE/flaking-test.md
docs/release/release-tasks.md

While we can still modify existing issue templates when reporting CI related issues, it would be very helpful if we could have issue templates ready while opening `failing/flaking test` issues in the repository (especially handy for relase team CI signal members) similar to the one used in the k8s repo, as  IMO it helps to:
-  gather all the required and additional information needed to tackle the issue regardless of whoever opens it
-  standardize the issues of the same kind in the future   
**Note:**  I am still using the markdown formatted issue templates for new failing/flaking-test templates in this PR but we have a possibility to move all existing templates from markdown format to [GitHub forms for issue templates …

🌱 Add failing/flaking test issue templates to the repository

---

docs/book/src/user/quick-start.md

cluster-api-provider-aws now releases windows binaries for clusterawsadm. This updates the curl links to be v2.0.0+ which has windows binaries in it's releases. Additionally this splits the *nix examples from the windows example and shows how to use `clusterawsadm` in powershell.

📖 Updating clusterawsadm Docs

---

cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go

This PR let's people use raw URL for `clusterctl generate yaml` command
Fixes #6535
/cc @ykakarap @sbueringer

✨ Add support for raw template URL in clusterctl generate yaml

---

.github/workflows/dependabot.yml

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7805
Bumps [actions/cache](https://github.com/actions/cache) from 3.0.11 to 3.2.1.

[release-1.2] 🌱 Bump actions/cache from 3.0.4 to 3.2.1

---

Tiltfile
docs/book/src/developer/tilt.md

This PR adds the support for running tilt with podman
Fixes #

:sparkles: tilt: add podman support

---

test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ipv6/cluster-ipv6.yaml
test/infrastructure/docker/api/v1beta1/dockercluster_types.go
test/infrastructure/docker/api/v1beta1/dockercluster_webhook.go
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/docker/kind_manager_test.go
test/infrastructure/docker/internal/docker/loadbalancer.go

Currently, CAPD exposes the host and port of the control plane endpoint but doesn't leverage them. 
I made 6443 a default port to keep the behavior consistent.
cc @richardcase @belgaied2
Fixes #

✨Make control plane port configurable in CAPD

---

docs/book/src/developer/e2e.md

📖 book: drop outdated note about removed e2e test func

---

.github/workflows/scan.yml
Makefile
docs/book/src/reference/jobs.md
docs/release/release-tasks.md
hack/verify-container-images.sh

Adding a verify script that runs [trivy](https://aquasecurity.github.io/trivy/) scanner on all the container images; the script is very basic for now, and it assumes someone will run it manually.
~~In follow-up iterations, we can think about how to automate this (when to run it, for changes on go.mod files, periodically), if to limit validation only to the image we release on production or not, and how to get a signal from the command output.~~
Also added a GitHub workflow running the same check periodically
For now, it will be great if we can have the release team running it periodically on main / before cutting a patch
@ykakarap @sbueringer @CecileRobertMichon opionis?

✨ Adds a verify script that run trivy scanner on container images

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md

Should be no need to backport as the issue template is only used from the default branch (main)
Fixes #

📖 Kubernetes bump issue template: fix prior art link

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/Dockerfile
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

Updates the Quick Start guide to use Kubernetes 1.26.
Part of #7671

⚠️ Use Kubernetes 1.26 in Quick Start docs and CAPD.

---

cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go
cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go
cmd/clusterctl/cmd/version_checker.go
cmd/clusterctl/internal/test/fake_github.go
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

🌱 go.mod: Update github.com/google/go-github to v48.2.0
Fixes #

🌱 go.mod: Update github.com/google/go-github to v48.2.0

---

bootstrap/kubeadm/internal/controllers/token.go

When the bootstrap token is expired and the respective secret is already cleaned up, MachinePools cannot be scaled up due to missing token.  In order to mitigate this issue, the secret can be rotated if it is missing.
Fixes #6029

🐛 Fix to enable bootstrap secret rotation if the secret itself missing

---

api/v1beta1/condition_consts.go
docs/book/src/developer/providers/v1.3-to-v1.4.md

Cleanup of the deprecated `MachineHealthCheckSuccededCondition` condition in the v1beta1 API.
Should use the MachineHealthCheckSucceededCondition `variable intead.`
There's no changes in the documentation.
Subtask of #7713

⚠️ Removing deprecated healthcheck condition

---

controllers/external/util.go
docs/book/src/developer/providers/v1.3-to-v1.4.md

Removing deprecated CloneTemplate and CloneTemplateInput
Part of #7713

⚠️ Removing CloneTemplate and CloneTemplateInput

---

cmd/clusterctl/cmd/init.go
docs/book/src/developer/providers/v1.3-to-v1.4.md

Removing the deprecated `--list-images` from init command
Part of #7713

⚠️ Removing deprecated --list-images flag on init command

---

test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go

With this PR CAPD only ignores SystemVerification and Swap preflight errors. The goal is to detect other preflight errors which affect other infra providers (e.g. ImagePull).
This should bring the test results of CAPD a bit closer to the ones of other infra providers.
Follow-up to #7833

🌱 CAPD: only ignore necessary kubeadm preflight errors

---

scripts/ci-e2e-lib.sh
test/e2e/data/kubetest/conformance.yaml
test/framework/deployment_helpers.go
test/infrastructure/docker/internal/docker/machine.go

Some misc improvements + fixes the CoreDNS validation. Previously we only checked if either the image is correct or the pods are ready, now both must be true.
Fixes #

🐛 test/e2e: fix CoreDNS readiness validation, misc improvements

---

.golangci.yml
api/v1beta1/common_types.go
docs/book/src/developer/providers/v1.3-to-v1.4.md
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

Removing the deprecated `ClusterTopologyManagedFieldsAnnotation` from v1beta1 API
Part of #7713

⚠️ Drop ClusterTopologyManagedFieldsAnnotation field from v1beta1

---

hack/tools/tilt-prepare/main.go

As of now, tilt live_update feature requires the pod to run as root, see https://github.com/tilt-dev/tilt/issues/3060
This PR removes any securityContext in manager manifests during tilt-prepare.
it allows every providers to add securityContext in manifests (like in https://github.com/kubernetes-sigs/cluster-api/pull/7831)
Fixes #

🌱 tilt: remove securityContext for live_update

---

docs/community/20221115-managed-kubernetes.md

This PR defines a Working Group to codify where formal conversations and progress is being made in Cluster API for standardizing Managed Kubernetes solutions across the provider ecosystem.
Fixes #

📖 Managed Kubernetes Feature Group

---

docs/book/src/reference/glossary.md

Fixes broken markdown links in the glossary page 
https://main.cluster-api.sigs.k8s.io/reference/glossary.html#control-plane-provider
https://main.cluster-api.sigs.k8s.io/reference/glossary.html#infrastructure-provider
https://main.cluster-api.sigs.k8s.io/reference/glossary.html#external-patch-extension
Fixes #

📖 docs: fix links in glossary page

---

bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_coredns.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
internal/util/kubeadm/kubeadm.go
internal/util/kubeadm/kubeadm_test.go
test/framework/daemonset_helpers.go
test/infrastructure/docker/internal/docker/machine.go

This PR results in the following change of behavior:
1. newly triggered upgrades to versions with the old registry will be blocked by the KCP webhook
* Only if imageRepository is not set in KCP and to versions >= v1.22.0 that also have a newer kubeadm patch version with the new registry.
* Goal is to steer folks, that are leaving the imageRepository defaulting to us, towards the new registry
2. pre-existing clusters with versions using the old registry will work again
Because 1. only blocks cases that were broken with v1.3.0 and v1.2.8 I guess this is technically not a breaking change.
Notes:
* #7829 builds on top of this PR and tests upgrades for all relevant combinations (via …

⚠️ KCP: block upgrade to versions with old registry, improve registry handling

---

docs/book/src/user/quick-start.md

Manual cherry-picks of https://github.com/kubernetes-sigs/cluster-api/pull/7814 and https://github.com/kubernetes-sigs/cluster-api/pull/7570/
Just trying to make the quick start cherry-pickable again...
After this PR the quickstart is in sync with main again (+/- the 1.26 change, but that's a separate PR)
Fixes #

[release-1.3] 📖 book: cherry-pick Linux capitalization & clusterawsdm doc updates

---

CONTRIBUTING.md

Following up to some discussion on recent PRs, e.g https://github.com/kubernetes-sigs/cluster-api/pull/7817#issuecomment-1369037272, I'm proposing some small changes to help us in better dealing with supporting multiple cluster API releases at the same time.
@vincepri @sbueringer @CecileRobertMichon @enxebre

🌱 Small improvement to the backport policy

---

test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go

We are reverting this change because by it uncovered a set of other issues on CC upgrades tests, and this is not allowing us to get a clean signal for the upcoming patch release.
The plan is to revert this change on all branches, get the KCP fix (#7856)  merged and backported on all branches, and then look and fix all the new issues in a follow-up.
Fixes #

🐛 Revert: CAPD: only ignore necessary kubeadm preflight errors

---

bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_coredns.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
internal/util/kubeadm/kubeadm.go
internal/util/kubeadm/kubeadm_test.go
test/framework/daemonset_helpers.go
test/infrastructure/docker/internal/docker/machine.go

handling
Manual cherry-pick of #7856
Fixes #

[release-1.2] ⚠️ KCP: block upgrade to versions with old registry, improve registry handling

---

docs/book/src/developer/providers/v1.3-to-v1.4.md
test/framework/clusterctl/clusterctl_helpers.go
test/framework/deployment_helpers.go

Adds WatchDeploymentLogsByLabelSelector function. Now we can call a function in e2e tests to stream logs of deployments, selected by a label selector, for not requiring to know the exact name of the deployment in the test implementation.
Which issue(s) this PR fixes(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6965

🌱Added WatchDeploymentLogsByLabelSelector function

---

bootstrap/kubeadm/config/manager/manager.yaml
config/manager/manager.yaml
controlplane/kubeadm/config/manager/manager.yaml
docs/book/src/developer/providers/v1.3-to-v1.4.md
test/extension/config/default/manager.yaml

Set explicit, secure securityContexts for the controller manager deployment and containers instead of relying on defaults or fallbacks.
Only actual change here is enabling runtimeDefault seccompPolicy, instead of running as Unconfined.
https://kubernetes.io/docs/tutorials/security/seccomp/
Also, reindent poorly indented command block.

✨ add explicit securitycontexts to controllers

---

docs/release/release-tasks.md

Looks like homebrew introduced automation to pickup the new version when available. This PR updates the homebrew section of the release tasks.
Fixes #

📖 update homebrew instructions in release tasks

---

docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/Dockerfile
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

[release-1.2] ⚠️ Use Kubernetes 1.26 in Quick Start docs and CAPD

---

docs/book/src/reference/jobs.md

part of #7671 
Q: Do we have to add a `1-26-latest` after line 126?

📖 docs update jobs.md for 1.26

---

docs/book/src/reference/versions.md

🌱 Update versions doc adding Kubernetes 1.26

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/Dockerfile
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

[release-1.3] ⚠️ Use Kubernetes 1.26 in Quick Start docs and CAPD

---

test/e2e/clusterctl_upgrade_test.go

We should run the clusterctl upgrade v0.4=>main test with the max supported mgmt cluster version of v0.4 (not a higher one).
I'll update the release task doc in https://github.com/kubernetes-sigs/cluster-api/pull/7825#discussion_r1066883380 and open similar PR(s) for other branches
Fixes #

🌱 test/e2e: run clusterctl v0.4=>main test with v1.23.13

---

test/e2e/config/docker.yaml

We should run the clusterctl upgrade v0.4=>main test with the max supported mgmt cluster version of v0.4 (not a higher one).
Fixes #

[release-1.2] 🌱 test/e2e: run clusterctl v0.4=>main test with v1.23.13

---

test/e2e/clusterctl_upgrade_test.go

We should run the clusterctl upgrade v0.4=>main test with the max supported mgmt cluster version of v0.4 (not a higher one).
Fixes #

[release-1.3] 🌱 test/e2e: run clusterctl v0.4=>main test with v1.23.13

---

.github/workflows/verify.yml

🌱 Bump kubebuilder-release-tools to v0.3.0, start running it on cherry-pick PRs

---

.github/workflows/scan.yml
docs/release/release-tasks.md

This PR adds Trivy scanning job to all supported release branches.
By default `on: schedule` jobs only run on the default branch. Copying this workflow to release branches does not trigger the job on the release branches.
Additional notes:
With this we can drop the scan.yaml files from the release branches to avoid confusion as they currently do not do anything. 
`scan.yaml` was added in in the following PRs:
- https://github.com/kubernetes-sigs/cluster-api/pull/7820
- https://github.com/kubernetes-sigs/cluster-api/pull/7821
Fixes #

🌱 setup Trivy scanning for supported release branches

---

docs/book/src/developer/tilt.md
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md

Fixes the sample to comply with the latest cluster-api dependencies.
Cherry-picks fixes of https://github.com/kubernetes-sigs/cluster-api/pull/7211 to the sample.
The dependency to cluster-api resolves to the transitive version of `k8s.io/component-base` (maybe also via controller-runtime) which is not compatible anymore to the documented sample since `v0.25.0`.
Fixes #

📖 Fix Runtime SDK implement extension sample to reflect updated k8s.io/component-base changes

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Signed-off-by: brcox <brcox@redhat.com>
Resolves https://github.com/kubernetes-sigs/cluster-api/issues/7892
Resolves https://github.com/kubernetes-sigs/cluster-api/issues/7892

:seedling: Update cert-manager to v1.11.0

---

Makefile
api/v1beta1/common_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machines.yaml
hack/observability/kube-state-metrics/crd-config.yaml
hack/observability/kube-state-metrics/metrics/cluster.yaml
hack/observability/kube-state-metrics/metrics/machine.yaml
hack/observability/kube-state-metrics/metrics/machinepool.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml

This PR is intentionally split into three commits to make the review more easier for now:
1. add control plane and infra ref labels to cluster
add the following labels from the cluster cr spec to the cluster_info
metric:
* `control_plane_reference_kind`
* `control_plane_reference_name`
* `infrastructure_reference_kind`
* `infrastructure_reference_name`
1. introduce new capi_machine_addresses metric
to represent the different kind of addresses in an own metric.
`containerRuntimeVersion` label got also renamed to
`container_runtime_version`
1. add initial capi_machinepool metrics
Regarding 2.
With the discussion in [this slack thread in #kube-state-metrics](https://kubernetes.slack.com/archives/CJJ529RUY/p1673349221630899) i will change the metric …

🌱 improves the existing capi metrics

---

cmd/clusterctl/cmd/generate_cluster.go
cmd/clusterctl/cmd/generate_provider.go
cmd/clusterctl/cmd/util.go

This PR adds support for an output flag as a convenient way to write yaml output directly to a local file.
Fixes #7612

✨ Add output flag, change printYaml function signature

---

internal/contract/controlplane.go
internal/contract/controlplane_test.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/e2e/clusterctl_upgrade.go
test/e2e/self_hosted.go
test/framework/controlplane_helpers.go

This is a follow-up to #7833. While triaging further we found out that:
* the topology controller was not waiting until KCP was entirely stable before triggering a rollout of the control plane
* the test framework wasn't waiting until KCP was entirely stable
* in the upgrade test this means the upgrade is triggered while KCP is still not stable from the create
Thx @fabriziopandini for collaborating on debugging this stuff! :)
Follow-up to: #7833

🌱 ClusterClass & test/framework: consider replicas for control plane readiness

---

internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
internal/webhooks/patch_validation.go
internal/webhooks/patch_validation_test.go
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

This PR adds a new feature to allow matching all "*" MachineDeploymentClasses.
1. Match all if MachineDeploymentClass.Names is a "*".
```yaml
matchResources:
machineDeploymentClass:
names : [*]
```
2. Match some if explicitly mentioned.
```yaml
matchResources:
machineDeploymentClass:
names: [something, something, something]
```
3. Match some if glob matched.
```yaml
matchResources:
machineDeploymentClass:
names: [something-*]
```
3. Match none if no machineDeploymentClass  is set (should produce a webhook failure)
```yaml
matchResources:
machineDeploymentClass: {}
```
Fixes #5648

:sparkles: ClusterClass patches: Allow matching all MachineDeploymentClasses

---

internal/contract/controlplane.go
internal/contract/controlplane_test.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/e2e/clusterctl_upgrade.go
test/e2e/self_hosted.go
test/framework/controlplane_helpers.go

Manual cherry-pick of #7914
Doesn't contain all changes to the self-hosted test as the self-hosted test didn't contain an upgrade in release-1.2
Fixes #

[release-1.2] 🌱 ClusterClass & test/framework: consider replicas for control plane readiness

---

hack/verify-container-images.sh

This PR ensures we also build all images on release-1.2 to avoid failing because of missing images
(https://github.com/kubernetes-sigs/cluster-api/actions/runs/3930140568/jobs/6719788260)
On newer branches `docker-build` builds all images.
Fixes #

🐛 trivy: also build capd & test-extension images

---

scripts/ci-e2e.sh
test/e2e/self_hosted.go

Currently our self-hosted e2e test doesn't cleanup the cluster at the end.
This means that after the self-hosted tests are completed we still have 4 clusters running, e.g.: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1614904441369006080/artifacts/localhost/docker-ps.txt
This has probably slightly negative impact on test performance and stability.
This PR fixes it
WIP => only added a validation that no containers are running for now. Actual fix will follow
Fixes #

🐛 test/e2e: Fix cluster cleanup in self-hosted test

---

docs/book/src/developer/tilt.md

Update tilt docs to show more clearly how to use tilt with the docker provider, vs how to use a third-party provider like CAPA.
Related to [#7263 
](https://github.com/kubernetes-sigs/cluster-api/issues/7920)

:book: Clarify tilt docs for docker provider

---

.github/workflows/release.yml

Since the release team is taking care of generating the release notes as needed, dropping the step from the github workflow.
Fixes #

🌱 drop the draft release notes step from github workflow

---

cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/template_test.go

Currently, `clusterctl generate cluster`'s `--from` flag only supports yaml files from github code (blob). Trying to get a template asset  from a release tag is failing.
This PR adds the option to use the `--form` also for release assets.
Fixes #7455
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

:bug: Allow using the --from flag to get a template from a github release

---

controlplane/kubeadm/controllers/alias.go
controlplane/kubeadm/internal/cluster.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/etcd/etcd_test.go
controlplane/kubeadm/internal/etcd_client_generator.go
controlplane/kubeadm/internal/etcd_client_generator_test.go
controlplane/kubeadm/main.go

Add configurable call timeouts to the etcd client through context deadlines. This is different than the dial timeout, which is only used to establish the connection from the client to the server.
This avoids a stuck reconciliation loop when there is an unresponsive call to the server.
Fixes #

:seedling: Add configurable etcd call timeout

---

test/framework/kubetest/run.go
test/infrastructure/container/docker.go
test/infrastructure/container/interface.go

Currently the e2e tests which are running the conformance tests are failing.
E.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-18-1-19-release-1-3/1615714183762939904
We introduced a new validation in https://github.com/kubernetes-sigs/cluster-api/pull/7928 which ensures that all containers have been stopped after the e2e test finishes.
This validation discovered that when we run conformance tests the conformance container is still "running" even after the conformance tests are done. This is because after the conformance tests / ginkgo exits Docker will just restart the conformance test container and the conformance tests will run again.
The …

🐛 test/e2e: don't restart the conformance test container after ginkgo exits

---

docs/book/src/clusterctl/commands/generate-cluster.md
docs/book/src/clusterctl/commands/generate-yaml.md

`clusterctl generate yaml` can now use a raw template URL. This is a follow-up PR of the [PR](https://github.com/kubernetes-sigs/cluster-api/pull/7371) documenting the new feature.
Fixes #7904 

📖 Add doc that clusterctl generate yaml can use raw template URL

---

docs/book/src/reference/glossary.md
docs/proposals/20210526-cluster-class-and-managed-topologies.md

As we already did for other proposals, this PR cleaned up the ClusterClass proposal removing outdated/hard-to-maintain implementation details by linking the book's page
This will hopefully make it easier to maintain the document up to date in future
Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/5753

🌱 ClusterClass proposal: Clean up outdated implementation details by linking the book's page

---

internal/hooks/tracking.go
internal/hooks/tracking_test.go

Just noticed that our pending hook annotation always has a leading `,`, e.g. `,AfterClusterUpgrade,AfterControlPlaneUpgrade`.
This PR should get rid of it and remove it on existing clusters.
Fixes #

🐛 ClusterClass: remove empty hook entries from annotation

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
docs/book/src/developer/providers/v1.3-to-v1.4.md
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
main.go
test/extension/main.go
test/infrastructure/docker/main.go

Related: https://github.com/kubernetes-sigs/cluster-api/issues/6069

🌱 logging: add removal note, cleanup no-op code

---

docs/proposals/20220725-managed-kubernetes.md

Broken link due to AKS graduation in CAPZ - caught by the weekly markdown checker. 
We might consider not having links to external repos like this if this is a maintenance burden - especially as line numbers can change pretty regularly, without the link checker understanding the change.

:book: Fix broken link to CAPZ experimental directory

---

api/v1beta1/cluster_types.go
api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.2/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1.2/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml

This PR adds support to apply labels and annotations to the ControlPlane and MachineDeployment objects. 
Credit to @MaxFedotov for doing the initial implementation.
Fixes #
Part of #7731
Related issue: #7006

✨ Managed Cluster should set labels and annotations on ControlPlane and MDs

---

api/v1beta1/machine_types.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/machine_controller_phases_test.go
internal/controllers/machine/machine_controller_test.go

Implements part of https://github.com/kubernetes-sigs/cluster-api/pull/6255. Propagate managed labels from Machines to Nodes.
/hold
Fixes #

✨ Add Node managed labels support

---

docs/book/src/user/quick-start.md

I found out `POD_SECURITY_STANDARD_ENABLED` in CAPI quickstart for CAPD was wrong/outdated. 
I changed it to `ENABLE_POD_SECURITY_STANDARD` which now enables/disables the PodSecurityStandard variable in the manifest generated by `clusterctl` correctly.

:book: Fix outdated enabling PodSecurityStandard env variable in CAPI quickstart

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go

The passed http.DefaultClient already handles redirects inside go-githubs DownloadReleaseAsset.
This PR simplifies the logic for the function `downloadFilesFromRelease` in cmd/clusterctl/client/repository/repository_github.go .
Passing `nil` instead of `http.DefaultClient` in https://github.com/chrischdi/cluster-api/blob/4fee5f49b81e0eee228a4e1968bb00843564eeaa/cmd/clusterctl/client/repository/repository_github.go#L381 would result in returning an error instead of manually resolving the redirect.
However this should only ever be the case if either:
* `http.DefaultClient` changes its behaviour to not follow redirects anymore
* `go-github` changes its behaviour to not follow redirects anymore
* We do not pass a redirects compatible client anymore …

🌱 Remove redirection handling in repository_github client

---

cmd/clusterctl/client/cluster/ownergraph.go
test/e2e/quick_start.go
test/e2e/quick_start_test.go
test/framework/ownerreference_helpers.go

Add a new e2e test and set of helper functions to test that ownerReferences are correctly reconciled by Cluster API.
This test is designed to capture how Cluster API creates ownerReferences with a newly created Topology based Cluster using KCP + KubeadmBooststrap + Docker infrastructure.
It also tests how ownerReferences are reconciled after they've been removed and re-reconciled.
Fixes #7575

:sparkles: e2e Test: Ensure OwnerRefs are consistently reconciled

---

.github/workflows/lint-docs-weekly.yml
docs/release/release-tasks.md

Adds running the weekly markdown link checker against all supported branches to keep links in supported versions of the book up to date.

:seedling: Run weekly markdown check against all supported branches

---

docs/book/src/developer/guide.md

Fix outdated verification steps for cert-manager installation in the developer guide, which are confusing for users, see e.g. https://kubernetes.slack.com/archives/C8TSNPY4T/p1674244667994499

📖 Fix cert manager verification steps in developer guide

---

cmd/clusterctl/client/cluster/ownergraph.go
util/secret/secret.go

Fixes a failure in the ownerReference e2e test for Kubernetes versions below v1.24. This ensures that the secrets considered for the ownerReference test are only those directly associated with the Cluster.

:bug: Fix secret selection logic for ownerRef test

---

test/e2e/quick_start.go

This PR makes the CAPI quick-start test suitable for use cases where there is more than one infrastructure provider in the E2E test config file, like e.g https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/pull/69 
Also, it makes the number of replicas configurable, could make sense when this test spec is used for other provider's pipelines

🌱 Improve quick-start test supporting scenarios with more than one infrastructure provider

---

cmd/clusterctl/cmd/util.go

If this flag is not specified, the return value of filepath.Clean() is "."(dot), but it appears that this was not handled. It now functions as expected.
Fixes #7970

🐛  bugfix write-to flag should only run filepath.Clean when the output file is not "" or -

---

cmd/clusterctl/client/cluster/ownergraph.go
test/framework/ownerreference_helpers.go

This change cleans up the implementation introduced in #7973 using the tenancy concept exposed in the objectGraph returned by the call to discovery.

:bug:  Use tenancy as filter in ownerReference test

---

Makefile
Tiltfile

For context, please see https://github.com/kubernetes-sigs/cluster-api/issues/7974

[release-1.2] 🌱 Bump to Go 1.18.10

---

api/v1beta1/machinedeployment_webhook.go
docs/book/src/developer/providers/v1.3-to-v1.4.md
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/machinedeployment_sync.go

This PR solves two issues:
1. It removes unnecessary defautling. Our goal is exclusively to modify the MD with the changes done by the modifyFunc, we don't want to do any defaulting additionally.
2. The way updateMachineDeployment was implemented before it overwrote the passed in MachineDeployment and thus dropped all changes previously made by the reconciler. For more details, see the explanation in:  https://github.com/kubernetes-sigs/cluster-api/issues/5470#issue-1032657900
xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1674580260891629
Tasks:
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

🌱 Remove PopulateDefaultsMachineDeployment and fix how MD controller set revision

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go

This change ignores errors in Machine reconciliation when the ClusterCacheTracker is not able to provide a client. This allows additional parts of the reconciliation -  setting ownerReferences, reconciling external Bootstrap and Infrastructure objects - to be done before failing when the Machine controller is unable to get a lock on the ClusterAccessor, or the Cluster is uncontactable in some way.

 :seedling:  Allow Machines in unreachable Clusters to do initial reconciliation

---

.github/ISSUE_TEMPLATE/release_tracking.md
CONTRIBUTING.md
docs/release/release-tasks.md

For context, please see https://github.com/kubernetes-sigs/cluster-api/issues/7974

📖 backport policy: Add go version bumps

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/cmd/config_repositories_test.go
docs/book/src/reference/providers.md

We migrate our github repository  cluster-api-provider-outscale  from  organization outscale-dev to outscale.
https://fr.outscale.com/
https://github.com/outscale
Fixes #

:bug: Migration github repository  cluster-api-provider-outscale from organization outscale-dev to outscale

---

docs/developer/release-team.md

Link checker on my fork detected the broken links
(https://github.com/sbueringer/cluster-api/actions/runs/4015108108)
Merged this change into the release-1.2 branch on my fork => Now all green: https://github.com/sbueringer/cluster-api/actions/runs/4015108108/jobs/6896627841
Fixes #

📖  Fix broken links to release docs

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
.github/workflows/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.github/workflows/scan.yml
Makefile

This PR ensures our actions are always running with the right go version. Which is the one we use in our Makefile to compile binaries and images.
Related to #7974

🌱 actions: use go version from Makefile

---

cmd/clusterctl/client/config/providers_client.go
cmd/clusterctl/cmd/config_repositories_test.go
docs/book/src/reference/providers.md

Migration github repository cluster-api-provider-outscale from organization outscale-dev to outscale also in release-1.2 
Backport in release 1.2:
https://github.com/kubernetes-sigs/cluster-api/pull/7998
Fixes #

:bug: [release-1.2]  Migration outscale provider release 1.2

---

docs/community/20230111-alternative-communication-patterns.md

This change adds a doc to cover the new "alternative communication patterns" feature group. This covers the scope and use cases that the group will be focused on.
Relates to #6520

📖 Add alternative communication patterns feature group

---

Makefile

[This PR](https://github.com/kubernetes-sigs/cluster-api/pull/8002) broke our brittle version calculation for golangci-lint 
(make lint is not executed during PR verification)
Fixes #

🐛 Fix version calculation in make lint

---

docs/proposals/20191017-kubeadm-based-control-plane.md

This PR proposes an amendment to KCP remediation so it will be possible to remediate failure happening while provisioning the CP (both first CP and CP machines while current replica < desired replica); 
It also introduces opt-in control of remediation retry behavior.
Rif https://github.com/kubernetes-sigs/cluster-api/issues/7496

📖 Amend KCP proposal with remediation while provisioning the CP

---

api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
internal/controllers/clusterclass/clusterclass_controller.go

Add an observedGeneration field to the ClusterClass `status` so other controllers and agents can ensure they're working with data that has been successfully reconciled by the CC controller.
Part of #7985

:seedling:  Add observedGeneration to ClusterClass status

---

docs/proposals/20191017-kubeadm-based-control-plane.md

follow up of https://github.com/kubernetes-sigs/cluster-api/pull/7855#discussion_r1087061639

🌱 Nit on KCP proposal

---

exp/runtime/topologymutation/walker_test.go

Remove the exact path for the testScheme from the walkTemplates test. This change also renames the test file to correct a typo.

🐛  Remove exact path match from walkTemplate test

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Fix inconsistency in spelling of 'requeuing' across the codebase.
Fixes #

:bug: Fix spelling of requeuing across files

---

hack/ensure-go.sh
hack/ensure-kind.sh
hack/ensure-kubectl.sh
hack/utils.sh

ensure-kind.sh and ensure-kubectl.sh install binaries into $GOPATH/bin, but nowhere it checks that $GOPATH/bin is in user's PATH. In this case, the newly installed binaries won't be found later on.

🌱 make ensure scripts fail if GOPATH/bin not in PATH

---

docs/release/release-tasks.md

xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1675187486636589?thread_ts=1675144698.856589&cid=C8TSNPY4T

 📖 Add notes about IPv6 tests in the release tasks

---

cmd/clusterctl/client/alpha/rollout.go
cmd/clusterctl/client/alpha/rollout_rollbacker.go

KCP is not a valid resource for `clusterctl alpha rollout undo`. This PR fixes that. 
Note that the functionality worked properly. This PR fixes the error message to reflect the correct functionality.
Fixes #

🌱 remove KCP as a valid resource type for rollback

---

OWNERS_ALIASES

The Cluster API community is awesome! Many folks answered the call for action about new maintainers and reviewers!
Kudos and a huge thank you to:
- @killianmuldoon (stepping up as a top-level maintainer 👏)
- @ykakarap (stepping up as a top-level reviewer and clusterctl maintainer 👏)
- @jackfrancis (stepping in as a top-level reviewer 👏)
- @richardcase (stepping in as a top-level reviewer 👏)
- @oscr (stepping up as a doc maintainer 👏)
- @chrischdi (stepping in as a reviewer for topology controller, CAPD, test* 👏)
- @elmiko (stepping in as a reviewer for docs, CAPD, test* 👏)
- @g-gaston (stepping in as a reviewer for CABPK and KCP 👏) 
All of you, please add your lgtm 
cc @CecileRobertMichon @sbueringer @enxebre @vincepri

✨ Add more reviewers and maintainers

---

.github/workflows/golangci-lint.yml
util/container/image.go

Release notes: https://github.com/golangci/golangci-lint/releases/tag/v1.51.0

🌱  Update golangci-lint to v1.51.0

---

api/v1beta1/common_types.go
internal/webhooks/patch_validation.go

Add a validation rule to prevent ClusterClass authors from using \"inline\" as the name of an external patch. This allows using that name as a reserved name to describe variables with inline definitions.
Part of #7985

:seedling:  Make 'inline' a reserved name for patches

---

exp/controllers/alias.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
exp/internal/controllers/machinepool_controller_test.go
main.go

Today the MachinePool controller is our only controller that doesn't automatically bump the apiVersions in references.
This PR makes the controller consistent with our other controllers.
Please note, if infra or bootstrap providers (e.g. CABPK) drop api versions (like v1alpha3/v1alpha4) without this change existing MachinePools might break and manual user intervention is required.
Example:
1. MachinePool has been created with a reference to v1alpha3.KubeadmConfig
2. MachinePool controller doesn't bump the ref
3. Cluster API v1.x drops v1alpha3
4. MachinePool controller breaks as v1alpha3 doesn't exist anymore
5. User has to fix the MachinePool manually by upgrading the apiVersion
A comment about …

🌱 MachinePool: automatically bump apiVersions like in our other controllers

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go

A number of the tests in the kubeadmconfig controller were testing insufficient conditions, and some were not testing what they intended to. 
This PR is a first round of fixing up the test coverage.

:bug: Fix unit test coverage in KubeadmConfig

---

docs/book/src/developer/testing.md
internal/test/envtest/environment.go

This PR adds an env var which allows writing the kubeconfig of envtest to a path to make debugging envtest unit tests easier.
Fixes #

🌱 envtest: add env var to allow writing envtest kubeconfig

---

internal/runtime/client/client.go
internal/runtime/metrics/metrics.go

This PR adds an additional `response_total` metric for RuntimeSDK hook client.
metric example:
```
capi_runtime_sdk_response_total{group="hooks.runtime.cluster.x-k8s.io",hook="Discovery",status="Success",version="v1alpha1"} 3
```
Fixes #7952

:sparkles: add response metrics for RuntimeSDK hook client

---

controllers/remote/cluster_cache_tracker.go

While debugging something else this line panic'ed a few times.
It looks like it was unable to convert input.Kind into a string because some of the timestamps in ObjectMeta of input.Kind were nil. (this happened in the context of `watchClusterNodes`)
Independent of that it seems reasonable to only use the type here instead of trying to log the entire object. Especially as the object is empty. With `%T` it will use e.g. `*v1.Node`.
Fixes #

🐛 ClusterCacheTracker: fix panic in error creation

---

OWNERS_ALIASES

Update Owners file to include changes from main.
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7996

[release-1.2] :sparkles: Update owners file

---

OWNERS_ALIASES

Update Owners file to include changes from main.
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7996

[release-1.3] :sparkles: sparkles Update owners file

---

controllers/remote/cluster_cache_tracker.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8062
Fixes #

[release-1.2] 🐛 ClusterCacheTracker: fix panic in error creation

---

controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go

**What this PR does / why we need it**: Added nodeVolumeDetachTimeout in the  Control-Plane machine spec
Fixes #8065

🐛 Added nodeVolumeDetachTimeout to CP machine

---

test/e2e/e2e_suite_test.go
test/e2e/self_hosted.go
test/framework/cluster_proxy.go
test/framework/clusterctl/clusterctl_helpers.go
test/framework/deployment_helpers.go

Uses an informer to also start streaming the logs of new pods of deployments which e.g. get created because of deletion of a pod, evictions during upgrades.
Fixes #7929

🌱 test/e2e use informer to stream pod logs

---

.github/workflows/golangci-lint.yml
.golangci.yml
bootstrap/util/configowner_test.go
exp/runtime/internal/controllers/extensionconfig_controller_test.go
internal/contract/bootstrap_test.go
internal/contract/controlplane_test.go
internal/contract/infrastructure_cluster_test.go
internal/contract/infrastructure_machine_test.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
util/patch/utils_test.go
util/util_test.go

* Our current golangci-lint version uses a ginkgolinter version that crashes when enabled. This bump allows us to enable ginkgolinter.
* linters-settings is now alphabetized to make it easier to find the correct linter.
* ginkgolinter is partially enabled. Due to the large amount of findings I only enabled a single check to keep this pr a little smaller. 
Fixes #8050

🌱 Bump golangci-lint (v1.51.1) and enable some ginkgolinter checks

---

internal/controllers/topology/cluster/blueprint.go
internal/controllers/topology/cluster/blueprint_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/topology/variables/cluster_variable_defaulting.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Add validation for the ClusterClass elements of topology managed Clusters during Cluster Topology reconciliation. Relax the Cluster webhook so that a Cluster can be created even if it references a non-existent ClusterClass.
Fixes #5623

:seedling: Add clusterclass validation to topology reconciler

---

.golangci.yml
api/v1beta1/machinedeployment_types.go
api/v1beta1/machinedeployment_webhook.go
api/v1beta1/machinedeployment_webhook_test.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
docs/book/src/developer/providers/v1.3-to-v1.4.md
docs/book/src/tasks/automated-machine-management/autoscaling.md
internal/test/builder/builders.go
util/defaulting/defaulting.go

🌱 MD: improve replica defaulting for autoscaler

---

docs/book/src/reference/versions.md

Update CoreDNS supported version for older versions of CAPI from changes in https://github.com/kubernetes-sigs/cluster-api/pull/8078 and https://github.com/kubernetes-sigs/cluster-api/pull/8077

:book: Update coredns version support

---

internal/controllers/topology/cluster/patches/engine.go

Manual cherry-pick of #8067
Fixes #

[release-1.2] 🌱 ClusterClass: catch panics when applying patches 

---

api/v1beta1/clusterclass_types.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.openapi.go
cmd/clusterctl/client/alpha/rollout_pauser.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
controllers/alias.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_test.go
main.go

Add the discoverVariables call to the External patch definition in the ClusterClass and add an implementation of the call in the ClusterClass reconciler.
Part of #7985

✨  Add discoverVariables runtime hook to ClusterClass reconcile loop

---

api/v1beta1/condition_consts.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

Add a check to the Cluster Topology reconciler to stop reconciling if the ClusterClass is not up to date. This check relies on the observedGeneration field added in #7987.
Part of #7985

:seedling: Add ClusterClass generation check to Cluster Topology reconciler

---

.gitignore
Makefile
docs/release/release-tasks.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/README.md
test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/crs.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.0/cluster-template/kustomization.yaml
test/e2e/data/shared/v1.0/metadata.yaml

🌱 test/e2e: Add v1.0=>main clusterctl upgrade test

---

internal/controllers/topology/cluster/conditions_test.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/scope/state.go

🌱 ClusterClass: also consider MD unavailableReplicas for rollout

---

test/infrastructure/docker/internal/controllers/dockermachine_controller.go

🌱 CAPD: reduce noisy error logs during machine reconciliation

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Add a DefinitionFrom field to the ClusterVariable type for use with conflicting VariableDefinitions.
Part of #7985

 :seedling: Add DefinitionFrom field to ClusterVariable

---

internal/controllers/machine/machine_controller.go

Fixes duplicated log output (lines 371 and 385) introduced with #6413 and adds two more outputs when waiting for infrastructure or bootstrap deletion.

🌱 improve logging during Machine deletion

---

Makefile
Tiltfile
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Uplift golang to 1.19.6 and x/net to 0.7.0 due https://osv.dev/vulnerability/GO-2023-1571

🐛 uplift golang and x/net

---

api/v1beta1/condition_consts.go
cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
cmd/clusterctl/client/cluster/topology.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/test/builder/builders.go
internal/test/builder/zz_generated.deepcopy.go
internal/topology/variables/cluster_variable_validation.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go
internal/webhooks/test/clusterclass_test.go
internal/webhooks/test/suite_test.go

Default and validate the variables in the Cluster based on the variable definitions in the ClusterClass status instead of the ClusterClass spec.
Part of #7985

:seedling: Default and Validate Cluster variables based on ClusterClass status

---

docs/book/src/clusterctl/commands/upgrade.md

📖 Add note about clusterctl upgrade test coverage

---

internal/webhooks/cluster.go

Add a check in the webhook to ensure that clusterctl move still works when validating Cluster's based on ClusterClass status.

:seedling: Remove generation check for clusterclass to fix e2e test

---

bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml

For more details see the linked issue
Additional verification that the bug is fixed via: https://github.com/kubernetes-sigs/cluster-api/pull/8120 (I'm running the e2e test 10x in the e2e-main job there)
Fixes #8124

🐛 KCP: fix rollout after upgrade

---

test/e2e/clusterctl_upgrade.go

🌱 test/e2e: disable rollout check for ClusterClass-based cluster in clusterctl ugprade tests II

---

test/framework/clusterctl/clusterctl_helpers.go

This PR ensures ApplyClusterTemplateAndWait always returns a cluster. This is very useful if a test fails early and we need a cluster to dump and cleanup resources via dumpSpecResourcesAndCleanup.
Let's assume `input.ClusterProxy.Apply(ctx, workloadClusterTemplate, input.Args...)` fails because e.g. the Cluster cannot be deployed because of some issues with the ClusterClass. Then the cluster would be nil and dumpSpecResourcesAndCleanup would panic. This change ensures we always return a cluster so we can get resources from the test run, even if the cluster creation didn't actually work.
The same applies when e.g. DiscoveryAndWaitForCluster fails.
**Which issue(s) this PR fixes** *(optional, in …

🌱 test/framework: ensure ApplyClusterTemplateAndWait always returns a cluster

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_phases_test.go
internal/controllers/machine/machine_controller_test.go

🌱 Move machine controller tests to envtest, drop disableNodeLabelSync

---

internal/controllers/machine/machine_controller_noderef_test.go

🌱 Add envtest unit tests for node label sync

---

internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
test/e2e/clusterctl_upgrade.go

🐛 ClusterClass: run dry-run on original and modified object

---

cmd/clusterctl/client/cluster/mover.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

This PR makes the Cluster webhook less strict when dealing with a ClusterClass that has not been successfully reconciled. For defaulting and validation scenarios, a ClusterClass that has not been successfully reconciled is treated in the same way as a ClusterClass which does not exist.
Related to #7985

:seedling: Make Cluster webhook less strict for out of date ClusterClasses

---

CONTRIBUTING.md

📖 docs: document plan to remove v1alpha3 and v1alpha4 apiVersions

---

CONTRIBUTING.md
docs/release/release-tasks.md

📖 docs: document test coverage for release branches

---

internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
internal/util/ssa/managedfields.go
internal/util/ssa/managedfields_test.go
internal/util/ssa/matchers.go

This PR implements the in-place propagation behavior for MachineSets. Changes to in-place propagation fields in MachineSet are synced to the target Machines.
**Follow-up work:**
- https://github.com/kubernetes-sigs/cluster-api/pull/8060)
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7731

⚠️ in-place propagation from MS to Machines

---

docs/proposals/20210310-opt-in-autoscaling-from-zero.md

include the latest changes to the annotation that are proposed in the cluster autoscaler
ref: https://github.com/kubernetes/autoscaler/pull/5382
ref: https://github.com/kubernetes/autoscaler/pull/5416
Fixes #

📖  update autoscaling from zero proposal

---

api/v1beta1/machinedeployment_types.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/machinedeployment_sync_test.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinedeployment/mdutil/util_test.go
internal/util/ssa/managedfields.go
internal/util/ssa/managedfields_test.go
internal/util/ssa/matchers.go

This PR implements the in-place propagation behavior for MachineDeployments.
The PR contains the following features:
- Changes to in-place propagation fields in MachineDeployment will not trigger a MachineSet rollout
- Changes to in-place propagation fields in MachineDeployment are synced to the target MachineSet
- Example: A user can change`md.spec.template.metadata.labels` without triggering a rollout and the changes will be passed down to the target MachineSet.
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7731

⚠️ in-place propagation from MD to MS

---

controllers/remote/cluster_cache_tracker.go

When a cluster accessor is created, the health check is started before the accessor is stored. If the health check hits the `loadAccessor` before the accessor is stored, it returns `true`, leaves the health check and never retries it. Together with expiring kubeconfigs (e.g. EKS), this will lead to a situation where a kubeconfig will never be refreshed and the cluster is basically dead until we restart the controller. This PR uses the `TryLock` to check if the cluster is currently locked which means that we're probably in the middle of the creation of a new cluster accessor and requeues the health check until the creation is done.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

:bug: Requeue health check during the creation of a new cluster accessor

---

docs/book/src/user/concepts.md

Fixes 3 broken link occurrences in the book.
Found them with:
```
$ grep -r "docs/admin" -l
./docs/book/src/user/concepts.md
```
After the fix no occurrences are found:
```
$ grep -r "docs/admin"
$
```
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8160

✨ docs: fix command-line-tools links in book

---

internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/engine_test.go
internal/controllers/topology/cluster/patches/variables/variables.go
internal/controllers/topology/cluster/patches/variables/variables_test.go

This PR adds a filter to the variable creation logic in the patch engine to associate variables with specific patches. This means that variables now have a per-patch definition i.e. inline patches can only use inline variables, while external patches only use variables discovered through a discoverVariablesExtension defined as part of that patch.
Part of #7985

:warning:  Add filter to associate variables with specific patches

---

docs/book/src/reference/versions.md

📖 docs: document new Kubernetes support policy

---

test/infrastructure/container/docker.go
test/infrastructure/docker/internal/docker/kind_manager.go

This PR aligns docker run flags used by CAPD with what is used in the current version of kind

🌱 align CAPD docker run flags with kind

---

.github/workflows/lint-docs-weekly.yml

Currently the weekly lint checker fails if one job, i.e. link checking for one branch, fails. This change should give results from all jobs, with any failure still reporting as a failure for the run.

:seedling: Set fail-fast: false for weekly md link check

---

internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

I think this should fix it.
xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1628652755163811840
Also saw the same failure on a few PRs.
Fixes #

🐛 Fix flaky TestServerSideApplyWithDefaulting test

---

docs/book/src/reference/versions.md

Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/8134#discussion_r1116173172

📖 book: remove old versions from versions.md

---

docs/book/src/reference/jobs.md

Aligns the job documentation to the changes in https://github.com/kubernetes/test-infra/pull/28842
Part of #8040

📖 book: update jobs documentation

---

hack/tools/release/notes.go

This is useful for the comms team when creating the weekly updates for the slack channel. Example invocation and output:
```
$ go run hack/tools/release/notes.go --since 2023-02-06 --until 2023-02-12
Changes since 2023-02-06 - 2023-02-12
---
- Stop supporting CRDs with invalid names (#8041)
- Add discoverVariables runtime hook to ClusterClass reconcile loop (#8006)
- Update coredns corefile migration to v1.0.19 (#8074)
- uplift helm dependency (#8089)
- KCP: Allow unsetting fields if their child fields are mutable (#8037)
- Added nodeVolumeDetachTimeout to CP machine (#8066)
- ClusterCacheTracker: fix panic in error creation (#8062)
- Add ClusterClass generation check to Cluster Topology reconciler (#8023)
- MD: improve replica defaulting for …
```

🌱 hack: add support for date ranges to notes.go script

---

Tiltfile
test/infrastructure/docker/Dockerfile

Drop kubectl from the CAPD image.
(kubectl should not be used anymore since we're setting the providerID of nodes with the regular client)
This will speed up CAPD image builds (also in TIlt :))
Fixes #

🌱 CAPD: drop kubectl from image

---

Makefile
test/extension/config/default/manager_pull_policy.yaml

This PR modifies our push targets to also push the test extension image to the staging repository (just like CAPD).
With this change it will be possible (again) to just run e2e tests locally without having to build the test extension every time.
Fixes #

🌱 test/extension: push to staging registry

---

internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/topology/variables/cluster_variable_defaulting.go
internal/topology/variables/cluster_variable_defaulting_test.go
internal/topology/variables/cluster_variable_validation.go
internal/topology/variables/cluster_variable_validation_test.go
internal/topology/variables/utils.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Add handling for conflicting definitions in variables defined in the ClusterClass and external patches. This change includes:
- Comparing variables and signalling which variables conflict in the ClusterClass status
- Validation and Defaulting of variables based on the appropriate definiton where conflicts exist 
- Validating that Cluster's define a `DefinitionFrom` field when there are conflicting variables
Part of #7985

 :sparkles: Handle variable definition conflicts for external variables

---

Makefile

This change fixes a build error in CAPI for release binaries. 
When trying to cut a tag for CAPI release v1.4.0 we saw the following error:
> cd /workspace; git status --porcelain
> fatal: detected dubious ownership in repository at '/workspace'
> To add an exception for this directory, call:        git config --global --add safe.directory /workspace
> error obtaining VCS status: exit status 128
>         Use -buildvcs=false to disable VCS stamping.
> make: *** [Makefile:919: release-binary] Error 1
This seems to be down to ownership of the directories in the golang container and git being careful about which directories it allows. 
I'm still trying to get to the bottom of this issue, but this change seems low impact and should fix the error in the short term to unblock a release.

:bug: Fix git config in release-binary builds

---

internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

Clarify condition message for a ClusterClass when it is not fully reconciled.
Part of #7985

:seedling: Clarify condition message for unreconciled clusterclass

---

internal/controllers/machineset/machineset_controller_test.go

This PR fixes an incorrect assertion in MachineSet controller tests.
Fixes #

🌱 fix incorrect assertion

---

docs/book/src/clusterctl/commands/move.md
docs/book/src/clusterctl/provider-contract.md

Add a warning to the docs of `move`, that the Status of CRDs gets lost during the move.
Feel free to update the wording completely without asking. I am not good at writing docs. Thank you.

:seedling: :book: move.md: Warning: Status get lost

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md

This PR updates our Kubernetes bump doc to reflect the changes through #8040.
We might need 1-2 Kubernetes bumps to get this 100% right.
Fixes #8040

📖 book: update Kubernetes bump documentation according to the new policy

---

test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/extension/handlers/topologymutation/handler.go
test/extension/handlers/topologymutation/handler_test.go
test/extension/main.go

Add an initial implementation of the DiscoverVariables hook to the test extension.
Part of #7985

 :seedling: Add DiscoverVariables hook implementation for test extension

---

Makefile
dev/vscode-example-configuration/settings.json
dev/vscode-example-configuration/tasks.json
docs/book/src/developer/repository-layout.md
docs/book/src/developer/testing.md

Those of developing cluster-api using vscode need to run envtest-based integration tests. To do this, we must (a) set up envtest manually, and (b) configure vscode to discover the envtest artifacts. Every time the envtest version changes, we have to repeat these steps. These steps are not documented. Developers often resort to `make test`, and lose the features of vscode for running and debugging tests.
This PR creates (a) configures vscode-go to read environment variables from a file, and (b) creates a "vscode task" that runs a make target to set up envtest, and to record the envtest artifact location to the file.
Once the task is run, developers can run integration tests directly from vscode.
Developers can optionally enable the task to …

:sparkles: Make it possible to run envtest-based integration tests from vscode

---

docs/book/src/developer/providers/implementers-guide/overview.md

Fix broken link in the book to the Kubernetes kubectl install page.
Fixes test run https://github.com/kubernetes-sigs/cluster-api/actions/runs/4313798314

:book: Fix broken link to kubectl install

---

Makefile

Make the uid introduced in #8219 match the uid used by the user building the binary.
This should allow the release-binaries target to work on more systems.

:bug: Replace fixed build uid with command

---

Makefile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8223 and https://github.com/kubernetes-sigs/cluster-api/pull/8219
Fixes build issue in 1.3 branch.

[release-1.3] :bug: Replace fixed build uid with command

---

controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

When aggregating from machine conditions to kcp condition, the priority is:
- false conditions with error reason
- false conditions with warning reason
- false conditions with info reason
- true conditions
- unknown conditions
However, when dealing with "false conditions with info conditions", there is a bug in source codes.
In Line 562, having checked warning reasons, we should check info reasons next. That is, to check "kcpMachinesWithInfo" rather than "kcpMachinesWithWarnings". However, there is a duplicate "kcpMachinesWithWarnings" in line 556 and line 662.
Maybe this is not a common scene, so it didn't lead to serious problems and was neglected. 
As a beginner of cluster-api, i found it when i read source codes, so i fix it.
**Which issue(s) …

🐛 bugfix function aggregateFromMachinesToKCP

---

controlplane/kubeadm/internal/workload_cluster_conditions.go
controlplane/kubeadm/internal/workload_cluster_conditions_test.go

This is a manual cherry-pick of #8132 into release-1.2.
Credit to @wm775825 for the fix!

[release-1.2] 🐛 bugfix function aggregateFromMachinesToKCP

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/helpers.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
internal/util/hash/hash.go
internal/util/ssa/cache.go
internal/util/ssa/patch.go
internal/util/ssa/patch_test.go
internal/util/ssa/suite_test.go

In recent weeks we added in-place propagation across a few controllers and we introduced an additional SSA dryrun in our Cluster topology controller. Basically on every reconcile we run SSA against the apiserver.
Now it's time to optimize the amounts of SSA calls to avoid overloading the apiserver.
This PR implements caching for SSA requests. The high-level idea is that once we know for a given original and modified object that the request doesn't lead to any changes, we cache this information for 10 minutes.
SSA will only be executed again once either original or modified objects change or the 10 minutes are over.
Some data:
The first two are ~ quickstart cluster creations with ClusterClass & caching => ~ 148 Patch calls
The last one is the same …

✨ SSA: Implement request caching

---

docs/book/src/user/quick-start.md

**What this PR does / why we need it**: In the upcoming v1.8.0 CAPZ release, the published flavor artifacts will no longer be using the in-tree cloud-provider which means anyone using those templates (including those following the CAPI quickstart) need to take an extra step to install the external cloud-provider. I expect this to become a common need as more providers switch to "external" cloud-provider by default so this adds a new section in the quickstart that others can add to.
Fixes #

📖 Add cloud-provider-azure helm install to quickstart

---

api/v1beta1/common_types.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
docs/book/src/developer/providers/bootstrap.md
exp/internal/controllers/machinepool_controller_noderef.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/suite_test.go
internal/util/taints/taints.go
internal/util/taints/taints_test.go

This PR adds the taint logic solve the delay problem in node label sync.
Does the following
- Add the `node.cluster.x-k8s.io/uninitialized:NoSchedule` taint to node at creation
- Drop the taint after the labels are synced from the Machine to the Node for the first time. 
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/7730

⚠️  apply `node.cluster.x-k8s.io/uninitialized` during machine creation

---

cmd/clusterctl/client/alpha/machinedeployment.go
cmd/clusterctl/client/alpha/rollout_rollbacker.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/mdutil/util.go
internal/controllers/machinedeployment/mdutil/util_test.go

Update MachineDeployment parameter names (`d` -> `md`) to make them more consistent across the codebase.
/kind cleanup
/area code-organization

:seedling: Rename md parameters for consistency

---

.github/workflows/lint-docs-weekly.yml
.github/workflows/release.yml
.github/workflows/scan.yml
.github/workflows/test-release-weekly.yml

Add a weekly action to ensure the release process is working to regularly check the codebase is in a good-enough state to release.
This would catch issues like #8199 which are release-blocking but may not be known ahead of release time.

:seedling:  Add weekly test-release action

---

controlplane/kubeadm/internal/controllers/helpers.go
internal/util/ssa/patch.go
internal/util/ssa/patch_test.go

This PR further improves SSA request caching:
1. caching was not used when writing KubeadmConfig / InfraMachine in KCP
2. caching was not always effective as in some cases we continuously tried to write fields like creationTimestamp. In those cases the resourceVersion was continuously changed and thus the request was not cached.
Fixes #8146

✨ SSA: improve request caching

---

test/framework/cluster_proxy.go

This PR changes the fix kubeconfig logic so that we only adjust the kubeconfig when necessary.
Specifically it only makes sense to fix the kubeconfig when the CAPD cluster is running locally in Docker Desktop.
It is not necessary if the CAPD cluster is running on a remote host. Actually for remote clusters fixing the kubeconfig breaks the kubeconfig as the remote cluster is not available under 127.0.0.1
Fixes #

🌱 test/framework: don't fix kubeconfig for remote CAPD clusters

---

internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go

Emit Kubernetes Events when Cluster `status.Phase`, `status.ControlPlaneReady`, or `status.InfrastructureReady` change and when the Cluster is deleted.
relates to #7424 (but does not resolve it)
Output of events:
```
$> kubectl get cluster
NAME      PHASE          AGE   VERSION
tge-aks   Provisioning   13s   
$> kubectl get events --sort-by=.metadata.creationTimestamp
LAST SEEN   TYPE     REASON         OBJECT            MESSAGE
19s         Normal   Provisioning   cluster/tge-aks   Cluster is Provisioning
$> kubectl get events --sort-by=.metadata.creationTimestamp
LAST SEEN   TYPE     REASON                OBJECT            MESSAGE
52s         Normal   Provisioning          cluster/tge-aks   Cluster is Provisioning …
```

✨ Emit Kubernetes Events when Cluster Phase, ControlPlaneReady, or InfrastructureReady change

---

controlplane/kubeadm/internal/controllers/scale_test.go

This PR fixes the flake in `TestKubeadmControlPlaneReconciler_initializeControlPlane`.
This test flaked a few times over the last few days: https://storage.googleapis.com/k8s-triage/index.html?test=TestKubeadmControlPlaneReconciler_initializeControlPlane
Fixes #

🌱 fix `TestKubeadmControlPlaneReconciler_initializeControlPlane` flake

---

hack/tools/release/notes.go

Automates the fun stats section of the weekly and release notes. 
cc @joekr @sayantani11 @VibhorChinda

🌱 Add release notes pr statistics

---

bootstrap/kubeadm/config/manager/manager.yaml
bootstrap/kubeadm/main.go
config/manager/manager.yaml
controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/config/manager/manager.yaml
controlplane/kubeadm/main.go
docs/book/src/developer/testing.md
docs/book/src/developer/tilt.md
docs/book/src/tasks/experimental-features/experimental-features.md
feature/feature.go
internal/test/envtest/environment.go
main.go
test/e2e/config/docker.yaml
test/infrastructure/docker/main.go

The [feature](https://github.com/kubernetes-sigs/controller-runtime/pull/2116) introduced in controller-runtime 0.14.4+ allows to use a lazy restmapper. The main advantage of this restmapper is that it fetches only required api resources in runtime, which significantly reduces the number of http requests to the api server.

🌱 Use Lazy Restmapper

---

internal/contract/bootstrap_config_template.go
internal/contract/controlplane_template.go
internal/contract/infrastructure_cluster_template.go
internal/contract/infrastructure_machine.go
internal/contract/infrastructure_machine_template.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
test/e2e/clusterclass_changes.go
test/e2e/clusterclass_changes_test.go
test/e2e/clusterclass_rollout.go
test/e2e/clusterclass_rollout_test.go
test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/md_rollout.go
test/framework/machine_helpers.go
test/framework/machinedeployment_helpers.go

Adds test coverage for: #7731, #7730

🌱 test/e2e: Add ClusterClass rollout test, extend MD rollout test

---

exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourceset_controller_test.go
exp/addons/internal/controllers/clusterresourceset_helpers.go
exp/addons/internal/controllers/clusterresourceset_helpers_test.go

kube-apiserver select the first valid IP from ServiceClusterIPRange to use as the GenericAPIServer service IP, if apply ClusterResourceSet before default kubernetes service has beed created, the GenericAPIServer service IP may  assign to other service and it will make default kubernetes service always create failed by service IP conflict.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/7804

🐛: Make sure the Kubernetes API Server service already created on remote cluster before applying ClusterResourceSets

---

bootstrap/kubeadm/api/v1alpha4/kubeadm_types_test.go
bootstrap/kubeadm/api/v1beta1/kubeadm_types_test.go
bootstrap/kubeadm/types/upstreamv1beta1/bootstraptokenstring_test.go
bootstrap/kubeadm/types/upstreamv1beta2/bootstraptokenstring_test.go
bootstrap/kubeadm/types/upstreamv1beta3/bootstraptokenstring_test.go

replacing reflect.deepequal with cmp.Diff to which provides better diff for debugging purposes
Fixes #8186 
This PR is for bootstrap/kubeadm will be following up with more

:seedling:  replace reflect deepequal in bootstrap kubeadm

---

test/e2e/quick_start_test.go

Merge the ownerReference quick start tests with the existing quick start tests. This means we're running fewer total tests, and the ownerReference check doesn't add appreciably to the length of the test run for quick start.
The ownerReference tests have not been flaky so far in the CI.
/area testing

🌱 Merge ownerReference tests with quick start

---

docs/book/src/user/quick-start.md

in quick start there was info for first cluster but second cluster info was missing I have just added that. 
Fixes #8152

📖 book: extend next steps of quick start

---

internal/controllers/machine/machine_controller_node_labels.go

This PR fixes the bug that prevented the `cluster.x-k8s.io/interruptible` label being set on nodes.
Fixes #

🐛 bug fix to set node interruptible label

---

test/infrastructure/docker/config/default/namespace.yaml

Manual cherry-pick of the CAPD change in #7446

[release-1.2] 🌱 CAPD: set privileged PSA policy

---

test/e2e/clusterctl_upgrade_test.go

This should make the v0.3, v0.4 & v1.0 clusterctl upgrades more stable.
Currently they are using the default flavor. But the default flavor is not setting the cgroupDriver to cgroupfs for Kubernetes < 1.24.
Fixes #

🐛 test/e2e: use topology cluster-template for clusterctl upgrade mgmt cluster 

---

test/e2e/clusterctl_upgrade_test.go

[release-1.3] 🐛 test/e2e: use topology cluster-template for clusterctl upgrade mgmt cluster

---

docs/book/src/introduction.md

Adds link to the 1.4 release in CAPI book.
**Should be merged after production branch is updated to 1.4 in Netlfiy**
/hold

📖 docs: add link to release 1.4 in capi book

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go

This PR improves the logic of fetching GitHub releases when looking for versions in provider repositories. The `ListReleases` API call is paginated and returns only the latest 30 releases. So we need to issue multiple calls in series to fetch all releases for a repository.
Fixes #8233 (**NOTE:** This PR handles only GitHub, it doesn't include a GitLab fix.)

🐛 Ensure all GitHub releases are fetched when searching provider versions

---

cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/objectgraph_test.go
cmd/clusterctl/internal/test/fake_objects.go

https://github.com/kubernetes-sigs/cluster-api/pull/7680 removed the owner reference from cluster to ClusterResourceSetBinding, replacing it with a spec.ClusterName field
However, we did not fix the fake objects used for validating clusterctl move accordingly, and thus even if unit tests for move were passing, we are seeking flakiness in CI because there is no more a deterministic order between Cluster and ClusterResourceSetBinding (see details in the attached issue).
This PR fixes this issue by introducing soft ownership from clusters to ClusterResourceSetBinding; It also fixes the softOwnership test that was not really up to date with what the function is currently doing.
Fixes …

🐛 Add soft ownership from clusters to ClusterResourceSetBinding

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8240

[release-1.3] 🐛 Ensure all GitHub releases are fetched when searching provider versions 

---

exp/addons/internal/controllers/clusterresourceset_controller_test.go

I've seen a bunch of flakiness in this test - both locally and in CI. I think the issue is waiting for the APIServer to create the service which sometimes doesn't happen quickly. I've updated the test to just create the service directly.
/area testing

:bug: Fix flaky wait in CRS test

---

cmd/clusterctl/OWNERS

Testing automatic area labels (discussed in #8263) on a limited area to try it out.
Partof #8263

🌱 clusterctl: Add labels to OWNERS file

---

internal/controllers/topology/cluster/cluster_controller.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Move variable validation from the Cluster validation webhook to the Cluster defaulting webhook
This fixes a race condition caused by moving variable definitions from ClusterClass spec to status. That change means there is a chance that the defaulting and validating webhook are working off of different versions of the ClusterClass as each independently retrieves it from the cache.
Fixes #

:bug:  Validate variables in defaulting webhook

---

.github/workflows/golangci-lint.yml
controlplane/kubeadm/internal/controllers/scale_test.go
internal/controllers/machine/machine_controller_phases_test.go
internal/controllers/topology/cluster/conditions.go
test/framework/machinedeployment_helpers.go
test/framework/namespace_helpers.go

While working with release notes I noticed a commit message about bumping golangci-lint to `1.52.0` but it actually bumps to `1.51.2`. This commit bumps to `1.52.1` and fixes the new findings.
New findings:
```
internal/controllers/machine/machine_controller_phases_test.go:397:4: ginkgo-linter: wrong length assertion; consider using `g.Expect(machine.Status.Addresses).To(BeEmpty())` instead (ginkgolinter)
g.Expect(machine.Status.Addresses).To(HaveLen(0))
^
controlplane/kubeadm/internal/controllers/scale_test.go:229:3: ginkgo-linter: wrong length assertion; consider using `g.Expect(controlPlaneMachines.Items).To(BeEmpty())` instead (ginkgolinter)
g.Expect(controlPlaneMachines.Items).To(HaveLen(0))
^ …
```

🌱 Bump golangci-lint to 1.52.1 and fix findings

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

Support updates on existing `KCP`s from CloudInit (Ubuntu) to Ignition (Flatcar)
Fixes #8242

🐛 enable updates from CloudInit (mostly ubuntu) based KCPs to Ignition (flatcar) based KCPs

---

test/framework/machinedeployment_helpers.go

Update the length checking in the machineDeployment helpers. 
Should fix issues with the clusterctl upgrade e2e tests.

:bug: Fix length check in MD helper

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8240

[release-1.2] 🐛 Ensure all GitHub releases are fetched when searching provider versions

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
docs/book/src/developer/providers/bootstrap.md
docs/proposals/20220927-label-sync-between-machine-and-nodes.md

Apply the `node.cluster.x-k8s.io/uninitialized:NoSchedule` only to worker nodes.
Fixes #8357
/hold

🐛 set uninitialized taint only on worker nodes

---

exp/ipam/api/v1alpha1/ipaddressclaim_types.go

Implements the `conditions.Getter` interface on the `IPAddressClaim` object.
Fixes #8373

✨Implements Getter interface for IPAddressClaim object

---

docs/book/src/developer/providers/v1.3-to-v1.4.md

The apiversion deprecations should also be in the migration docs. 
Should be cherry picked into 1.4 branch.
Partof #8038
cc @sbueringer @killianmuldoon @ykakarap

📖 book: add missing apiversion deprecation to migration docs

---

docs/book/src/introduction.md

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8363
Fixes #

[release-1.2] 📖 Add note for registry.k8s.io migration

---

docs/book/src/developer/providers/v1.3-to-v1.4.md

Update a link in the implementers guide to use internal markdown-based linking instead of http based linking. This will make the link more resilient to change in future.

:book: Fix http link in book

---

docs/release/release-tasks.md

- Adds Netlify links related to updating CAPI book, as was provided [here](https://github.com/kubernetes/k8s.io/pull/4939#issuecomment-1473078669). 
- Adds task and clarifications for comms team tasks. 
cc @joekr

📖 docs: update comms team release tasks

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

📖 docs: update CAPI support and guarantees

---

docs/book/src/user/quick-start.md

Updates the Quick Start to use clusterctl 1.4 as described [release tasks](https://github.com/kubernetes-sigs/cluster-api/blob/a45fca79cc5c4e11ce2d2c987a08c8661de06b1c/docs/release/release-tasks.md#update-clusterctl-links-in-the-quickstart)
Needs to wait for the 1.4 to be published. 
/hold 

📖 book: Update CAPI Quick Start to use clusterctl 1.4

---

scripts/ci-e2e.sh

Allow overriding the value of GINKGO_ARGS in the CI test script. This will allow us to disable fail-fast and give us full runs of e2e tests in the CI.
/area testing

:seedling: Allow overriding gingko args in e2e tests

---

internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
util/util.go

Move `mergeMap` in a shared util
Fixes #8276

✨  Move mergeMap to util

---

cmd/clusterctl/hack/create-local-repository.py

Add a kustomize patch to CAPI CRDs to ensure that creationTimestamp is correctly renedered on generated CRDs.
Fixes #8413

:bug: Use local kustomize version in create-local-repository.py 

---

docs/book/src/developer/providers/migrations/v0.4-to-v1.0.md
docs/book/src/developer/providers/migrations/v1.0-to-v1.1.md
docs/book/src/developer/providers/migrations/v1.2-to-v1.3.md
docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md

Fix a number of broken links in the contribution guides.
These link issues were introduced by https://github.com/kubernetes-sigs/cluster-api/pull/8383, but I'm not sure why the link checker didn't catch them at that point.

:book: Fix broken links in migrations guides

---

Makefile

Add a target to generate manifests for the test runtime extension to the release target. 
/area release

:seedling: Add runtime extension components to release

---

CONTRIBUTING.md

Proposing a small amendment to backport policy in order to allow a little bit of more flexibility for experimental features

🌱 Allow backport for experimental features

---

cloudbuild-nightly.yaml
cloudbuild.yaml

n1 machine times are old and e2 are going to be cheaper.
Reference https://github.com/kubernetes/k8s.io/issues/5059

🌱 Switch cloudbuild.yaml to e2 machine type

---

.github/dependabot.yml

Adding area/dependency label for dependabot when it bumps gomod. 
I think it fits and since there are a few prs from dependabot it's nice to catch it asap.
Partof #8263
cc @joekr

🌱 Add area/dependency label for dependabot when bumping gomod

---

exp/internal/controllers/machinepool_controller_noderef.go
exp/internal/controllers/machinepool_controller_noderef_test.go
internal/util/taints/taints_test.go

**What this PR does / why we need it**:  Fixes flake observed in CAPZ testing with CAPI v1.4.0 where MachinePool Nodes `{node.cluster.x-k8s.io/uninitialized: } ` taints don't get removed right away (~15 minute delay). The root cause is that we are escaping the second part of the `if annotations.AddAnnotations(node, desired) || taints.RemoveNodeTaint(node, clusterv1.NodeUninitializedTaint)` when the first part if true (see https://play.golang.com/p/i-6vDeSeeBE). This results in the controller returning no error without having patched the taints. Only after the resyncPeriod does the controller get requeued and Taints finally updated.
Credits to @nawazkh @willie-yao @jackfrancis for helping me find this  …

🐛  Fix MachinePool node taint patching

---

test/e2e/data/cni/kindnet/kindnet.yaml
test/infrastructure/docker/internal/loadbalancer/const.go

Update to the latest released versions of Kind's associated images. This brings in a change to fix a longstanding issue with the loadbalancer used in CAPD.
Fixes #8257

:bug: Update kindnetd and kindest/haproxy

---

api/v1beta1/index/index.go
api/v1beta1/index/machinepool.go
api/v1beta1/index/machinepool_test.go
exp/controllers/alias.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_noderef.go
main.go

**What this PR does / why we need it**: Since CAPI v1.4.0, the MachinePool controller drops the `node.cluster.x-k8s.io/uninitialized` taint from nodes as soon as the providerID gets added to the node by the cloud-controller-manager and CAPI is able to match the node with a MachinePool. However, it is currently not watching Nodes (unlike the Machine controller) which can cause delays in the taint being dropped on MachinePool nodes, which in turn causes the Node to not become schedulable until 10-15 minutes after the node is `Ready`. 
Fixes #8442

🐛 Add node watcher to MachinePool controller

---

Makefile
cmd/clusterctl/hack/create-local-repository.py
docs/release/release-tasks.md
hack/tools/tilt-prepare/main.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/crs.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.4/cluster-template-topology/kustomization.yaml
test/e2e/data/infrastructure-docker/v1.4/cluster-template/kustomization.yaml
test/e2e/data/infrastructure-docker/v1.4/clusterclass-quick-start.yaml
test/e2e/data/shared/main/metadata.yaml
test/e2e/data/shared/v1.4/metadata.yaml

This PR prepares the main branch for development.
Fixes #
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8429

🌱 prepare main branch for v1.5 development

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

This release contains fixes for a number of CVEs - those don't impact Cluster API AFAICT.

🌱  Update docker to v20.10.24

---

docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/go.mod
test/go.sum

Update kind to v0.18.0.
Release notes: https://github.com/kubernetes-sigs/kind/releases/tag/v0.18.0

:seedling: Update kind to v0.18.0

---

internal/controllers/topology/cluster/structuredmerge/drop_diff_test.go
internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
internal/util/ssa/filterintent.go
internal/util/ssa/filterintent_test.go
internal/util/ssa/managedfields.go
internal/util/ssa/matchers.go

Renames `internal/util/ssa` util functions for better naming consistency
Fixes #8396

:seedling: Rename internal/util/ssa util functions for better naming consistency

---

controlplane/kubeadm/internal/controllers/controller.go

Adds  a nil-check when retrieving a Kubeconfig for a machine in KCP. This nil-pointer issue was  likely introduced in #8057
Fixes #8480

:bug: Ensure nil-pointer check in KCP syncMachines

---

controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go

Remove adoption logic for v1alpha2 from the KCP controller. There is currently no direct support for upgrades from v1alpha2 to v1beta1. This code is designed to support that use case so it should be removed. 
Clusters which are reconciled by 0.3.X / 0.4.X controllers before updating to v1beta1 will already have this ownerReference removed. 
Fixes https://github.com/kubernetes-sigs/cluster-api/pull/8256/files#r1141658906

:seedling:  Remove v1alpha2 adoption logic from KCP

---

test/framework/clusterctl/repository.go

Catch failures, i.e. non-200 status codes, when fetching component URLs to build a local repository with clusterctl in the e2e testing framework.
/area testing

:bug: Catch failure when fetching component URLs

---

Makefile

Update kpromo to v3.5.2
Release notes:  https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.5.2

🌱  Update kpromo to v3.5.2

---

docs/book/src/developer/providers/v1.2-to-v1.3.md
docs/book/src/developer/providers/v1.3-to-v1.4.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/go.mod
test/go.sum

Update kind to v0.18.0.
Release notes: https://github.com/kubernetes-sigs/kind/releases/tag/v0.18.0

:seedling: Update kind to v1.18.0

---

docs/release/release-tasks.md

Moves the task to update the branches for github workflows from `Prepare main branch for development of the new release` to `Setup jobs and dashboards for a new release branch`. This task isn't actually doable at the start of a release cycle, and fits more cleanly along with the other CI setup jobs.

:book: Add github workflow branches to CI team tasks

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry pick of https://github.com/kubernetes-sigs/cluster-api/pull/8475
Fixes some CVEs.

:seedling: Update docker to v20.10.24

---

internal/controllers/machine/machine_controller_phases_test.go

Fixes the flaky test.
The test patches the status of the Machine, while the reconciliation may be already happening. This leads to inconsistent state which is not deterministic and into the Machine's status to never reach the targeted state.
Also see: [this dashboard](https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20after%2010&job=.*-cluster-api-.*&test=sigs.k8s.io%2Fcluster-api%2Finternal&xjob=.*-provider-.*)
Fixes #8477

🐛 machine-controller: fix phase tests race condition in tests on lastUpdated field

---

docs/book/src/developer/providers/migrations/v0.3-to-v0.4.md
docs/book/src/tasks/upgrading-cluster-api-versions.md

Fix broken links found in the weekly markdown link scan.

:book: Fix links in 0.3->0.4 migration guide

---

docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md

This PR fixes a documentation error in the v1.3 to v1.4 upgrade docs.
Fixes #8499

📖Fix remediation test doc issue in v1.3 to v1.4 upgrade docs

---

test/framework/machinedeployment_helpers.go

This pull request improves the clarity of error messages during end-to-end validation of the expected node count in MachineDeployments. It does this by wrapping error responses, ensuring that the root cause of the error is displayed in the console output (stdout/stderr).
Fixes #

🌱 assert E2E error responses when waiting for MD nodes

---

hack/tools/go.mod
hack/tools/go.sum

Bump containerd in hack/tools to 1.6.18 to close to two public vulnerabilities in containerd.
https://osv.dev/vulnerability/GHSA-259w-8hf6-59c2
https://osv.dev/vulnerability/GHSA-hmfx-3pcx-653p

🌱 bump containerd to 1.6.18 in hack/tools

---

docs/book/src/reference/jobs.md

Updates jobs doc according to https://github.com/kubernetes/test-infra/pull/29295
Related to: https://github.com/kubernetes/test-infra/pull/29295
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8459
/cc @kubernetes-sigs/cluster-api-release-team

📖 Update jobs.md with new k8s v1.27 jobs notes

---

config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
exp/ipam/api/v1alpha1/ipaddressclaim_types.go

This PR makes the `addressRef` on the IPAddressClaim status optional. This allows us to set the `condition` on the IPAddressClaim status without setting the `addressRef` in the case of failure to allocate an IPAddress.
This is related to #8424.

:seedling: Make IPAddressClaim.Status.AddressRef optional

---

docs/book/src/reference/versions.md

Updates versions.md with new k8s version v1.27.0 notes
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8459

📖 Update versions doc with k8s v1.27 notes

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
Tiltfile
docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
docs/release/release-tasks.md
test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

Bumps k8s version to v1.27.0 in Quickstart docs and CAPD. 
**NOTE**: 
- etcd version is bumped to` 3.5.7-0` following the [kubeadm](https://github.com/kubernetes/kubernetes/blob/release-1.27/cmd/kubeadm/app/constants/constants.go#L311-L312)
-  COREDNS_VERSION is bumped to `v1.10.1` following the [kubeadm](https://github.com/kubernetes/kubernetes/blob/c3e3ff989ac9abfb0dc3b958fcb698fcce952f8c/cmd/kubeadm/app/constants/constants.go#L348)
- new field called: `WorkloadKubernetesVersion` was introduced to `ClusterctlUpgradeSpecInput`
Part of: …

⚠️ Use k8s v1.27.0 in quickstart docs and CAPD

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
Tiltfile
docs/book/src/developer/providers/v1.3-to-v1.4.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
docs/release/release-tasks.md
test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

Manually cherry picks https://github.com/kubernetes-sigs/cluster-api/pull/8518
**NOTE**: 
- etcd version is bumped to` 3.5.7-0` following the [kubeadm](https://github.com/kubernetes/kubernetes/blob/release-1.27/cmd/kubeadm/app/constants/constants.go#L311-L312)
-  COREDNS_VERSION is bumped to `v1.10.1` following the [kubeadm](https://github.com/kubernetes/kubernetes/blob/c3e3ff989ac9abfb0dc3b958fcb698fcce952f8c/cmd/kubeadm/app/constants/constants.go#L348)
- new field called: `WorkloadKubernetesVersion` was introduced to `ClusterctlUpgradeSpecInput`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

[release-1.4] ⚠️ Use k8s v1.27.0 in quickstart docs and CAPD

---

test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml

Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/8311#discussion_r1141596306
To be honest not sure if we need this, but let's clean it up at least for consistency with other tests.
Fixes #

[release-1.4] 🌱 test/e2e: use topology flavor for workload clusters in clusterctl upgrade test

---

.golangci.yml
Makefile
Tiltfile
bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
go.mod
hack/ensure-go.sh
hack/tools/go.mod
main.go
netlify.toml
test/go.mod
test/infrastructure/docker/main.go

- Upgrade golang version (1.19.6 -> 1.20.3)
- Fixing golangci-lint error: rand.Seed has been deprecated since Go 1.20.
Seeding is added by default from 1.20 onwards. More info [here](https://github.com/golang/go/blob/3f8f929d60a90c4e4e2b07c8d1972166c1a783b1/src/math/rand/rand.go#L383)
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8459
Fixes #

:seedling:Upgrade golang version (1.19.6 -> 1.20.3)

---

docs/proposals/20200804-windows-support.md

Improve the signal of the weekly markdown link checker by changing the format of flaky external links.
Fixes #

:book: Fix markdown links to flaky pages

---

cloudbuild-nightly.yaml
cloudbuild.yaml

- Bump gcb-docker-gcloud image
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8459
Fixes #

:seedling:Bump gcb-docker-gcloud image

---

.github/ISSUE_TEMPLATE/release_tracking.md
docs/release/release-tasks.md
docs/release/releases/release-1.5.md

As discussed in https://github.com/kubernetes-sigs/cluster-api/issues/8498#issuecomment-1503860857 we want to inform providers when a new beta.0 has been released. This will help 1) inform the providers of the upcoming release and 2) let them know a new version is ready to test. The beta.0 release should give the providers about a month of testing before the next minor release.
Ref #8498

📖 : Add beta testing tasks to release process

---

config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
exp/ipam/api/v1alpha1/ipaddress_types.go
exp/ipam/internal/webhooks/ipaddress.go
exp/ipam/internal/webhooks/ipaddress_test.go

The validating webhook for IPAddress ensures that `.spec.gateway` is a valid IP address. This check fails if the field is empty, making it a required field. Since it is defined as `omitempty` it should be optional.
This PR wraps it with an is-empty check to allow the field to be empty.
related to telekom/cluster-api-ipam-provider-in-cluster#70
Fixes #8536

🐛 ipam: fix gateway being required for IPAddress

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go

Today KCP produces confusing error messages if it can't scale up the control plane because one of the already existing Machines doesn't have a nodeRef (e.g. because it doesn't have a providerID). This PR improves the error log
Before:
> "events: Waiting for control plane to pass preflight checks to continue reconciliation: [machine capi-quickstart-control-plane-5tgwz does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-5tgwz does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-5tgwz does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-5tgwz does not have EtcdPodHealthy condition, machine …

🌱 KCP: improve error log on scale up when Machine doesn't have a nodeRef

---

.gitignore
bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
main.go
test/infrastructure/docker/main.go

All the controllers have built-in rate limits. They throttle themselves if they hit this limit. So far it has not been possible to configure these limits. This commit adds flags to the controllers for setting both the QPS and the burst for the rate limits. The default remains the same as before (20 QPS, 30 burst).
New flags (for each controller, including CAPD):
--kube-api-qps
--kube-api-burst
Also adds .devcontainer to .gitignore.
Fixes #8052

✨ Add flags for configuring rate limits
