kubernetes-sigs/cluster-api

cloud/google/cmd/gce-machine-controller/Dockerfile, cmd/apiserver/Dockerfile, cmd/controller-manager/Dockerfile
Fix docker image build break for controllers
Fixes #
```release-note
```
=> Fix dockfile to new repository location.

gcp-deployer/CONTRIBUTING.md
**What this PR does / why we need it**: Docs are outdated
Fixes #
```release-note
```
=> Update branch location and image push instructions

gcp-deployer/CONTRIBUTING.md
=> Update gcp readme to remove openssl and fix command indentation

cloud/terraform/machineactuator.go, cloud/terraform/pods.go, cloud/terraform/templates.go, tf-deployer/machines.yaml.template
Upgrade control plane version. Depends on an upcoming change by @krousey.
/hold until his PR is merged, and then I can rebase that on to mine.
**Special notes for your reviewer**: Very much a prototype.
=> vSphere k8s components upgrade prototype

cloud/google/pods.go, cloud/terraform/pods.go, cmd/controller-manager/Makefile
Also catching the terraform controller up to the proper API server.
=> Bumping the controller manager image to pick up Cluster API changes

cloud/google/cmd/gce-machine-controller/Dockerfile, cloud/google/cmd/gce-machine-controller/Makefile, cloud/google/pods.go
Ran
```console
> cd cluster-api/cloud/google/cmd/gce-machine-controller
> make push
```
=> Bumping the GCE controller to add ssh and pick up other changes

tf-deployer/CONTRIBUTING.md, tf-deployer/README.md, tf-deployer/machines.yaml.template
Updates documentation for tf-deployer
Please do not merge yet. I used VM template provided by @karan, but didn't manage to make it work with my own template created according to the guideline. @karan, are there additional steps to prepare VM template for use by TF deployer?
```release-note
NONE
```
/cc @karan
=> Update README for tf-deployer

cloud/terraform/cmd/terraform-machine-controller/Dockerfile, cloud/terraform/cmd/terraform-machine-controller/Makefile, cloud/terraform/machineactuator.go, cloud/terraform/pods.go
This enables the terraform controller to delete nodes.
=> Implement machine and VM deletion in terraform

tools/upgrader/cmd/root.go
Line 65: kubernets->kubernetes
=> Typo fix:kubernets->kubernetes

pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go, pkg/apis/cluster/zz_generated.deepcopy.go, pkg/openapi/openapi_generated.go
=> Update generated code (keeping the manual edits)

cloud/google/cmd/gce-machine-controller/Makefile, cloud/google/pods.go, cloud/terraform/cmd/terraform-machine-controller/Makefile, cloud/terraform/pods.go, cmd/apiserver/Makefile, cmd/controller-manager/Makefile
=> Bump container versions to pick up the recent api changes.

clusterctl/README.md, clusterctl/examples/vsphere/machines.yaml.template
Readme: Fix terrraform -> terraform
Machines: replace tabs with spaces
Cleanup
@jessicaochen
=> Small docs cleanups

clusterctl/examples/vsphere/machines.yaml.template, tf-deployer/machines.yaml.template, vsphere-deployer/machines.yaml.template
Remove control plane version master set label on node in template
Fixes #
```release-note
```
=> Remove control plane version master set label on node in template

cloud/vsphere/README.md
**What this PR does / why we need it**: see the title
Fixes #238
=> Add docs for deleting a vsphere cluster manually

cloud/vsphere/cmd/vsphere-machine-controller/Makefile, cloud/vsphere/deployer.go, cloud/vsphere/machineactuator.go, clusterctl/examples/vsphere/provider-components.yaml.template
**What this PR does / why we need it**: Makes the control plane upgrades work by doing in-place upgrades.
Fixes #287
Even though I have a change for node upgrade, that doesn't work.
=> vSphere master control plane upgrade

pkg/controller/machine/machine_suite_test.go
=> Fix test race.

cloud/vsphere/README.md
**What this PR does / why we need it**: See title
/assign @k4leung4
=> Update vsphere delete docs: no node labels.

clusterctl/examples/vsphere/README.md, clusterctl/examples/vsphere/machines.yaml.template
=> Update vsphere README for machineset

pkg/controller/machine/controller_test.go
=> Fix test race for non-default namespace test case.

clusterctl/clusterdeployer/clusterdeployer.go
A small refactor to make the external cluster cleanup more obvious since it currently causes confusion. (eg. #320 )
No change in actual behavior for users of package (that is why there are no unit tests changes)
```release-note
```
=> Increase clarity around external cluster cleanup

OWNERS_ALIASES
Add me to the owners file so that I can approve PRs
=> Add mkjelland to the cluster-api OWNERs file

clusterctl/README.md
- Add link to minikube drivers page
- Recommend kvm2 instead of kvm as that is what the minikube folks recommend
- doc the "--vm-driver" parameter with an example
Fixes #
```release-note
```
=> Update minikube driver information

OWNERS
Fixes #
```release-note
NONE
```
=> Add reviewers to owners

cloud/google/machineactuator_test.go
=> Fix a copy / paste error with GCEClientComputeServiceMock

Makefile
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
Fixes #
```release-note
NONE
```
=> Add images to "make all" target

clusterctl/cmd/create_cluster.go, clusterctl/testdata/create-cluster-no-args-invalid-flag.golden, clusterctl/testdata/create-cluster-no-args.golden
Indicate in clusterctl that an azure provider is being created and point to the repo it's hosted in.(https://github.com/platform9/azure-provider)
=> indicate azure provider implementation is in progress

clusterctl/clusterdeployer/clusterclient.go
This PR adds more methods to clusterclient to flesh out the things that will be needed for delete. It is submitted separate from delete to make that PR smaller. If it is necessary to see delete in its entirety to reason about this PR, I am happy to open up a complete PR with all of the changes.
Note that this PR copies the style and flow of the existing clusterclient. For example, it adds relevant wait code to to the deletion methods, copying what it is done in existing Create methods like CreateMachineObjects.
You will notice, there is a lot of duplicate waiter code. I did attempt to generalize the wait and then call that generalized function. However, I was unable to come up with anything better than copy & …
=> Add missing Get / List, Create, and Delete methods to clusterclient. Add a wrapper Delete method for Kubectl.

README.md
**What this PR does / why we need it**: Documentation update.
Fixes #
1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
```release-note
NONE
```
=> Updated pointers to repositories where provider-specific work is being done

cmd/apiserver/Makefile, cmd/controller-manager/Makefile
**What this PR does / why we need it**: Bump the image versions to include api changes to remove machine role.
Fixes #
**Special notes for your reviewer**: This PR only changes image versions. 
```release-note
NONE
```
/assign @karan
=> Bump cluster-apiserver from 0.0.5 to 0.0.6 and controller-manager from 0.0.7 to 0.0.8

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, clusterctl/CONTRIBUTING.md, clusterctl/README.md, docs/proposals/machine-api-proposal.md, tools/repair/README.md, tools/upgrader/README.md
**What this PR does / why we need it**: Clean up the docs a bit. 
Fixes #
**Special notes for your reviewer**: _n/a_
```release-note
NONE
```
/assign @dims
=> Update documentation now that the provider specific code has been removed from this repository

cmd/apiserver/main.go, cmd/controller-manager/main.go
Per https://github.com/kubernetes/kubernetes/issues/17162
```release-note
NONE
```
=> Add glog/flag workaround to controller-manager

pkg/apis/cluster/v1alpha1/machine_types.go
=> fix wording

README.md
The only way to discover how to see design documents and calendars is by happening to be in the slack channel when someone mentions it, or by asking. This adds that information to the README.
Fixes #460
```release-note
NONE
```
=> Add the google group info to the README.md

README.md
The official repo for the vsphere provider got created recently. This PR is to update the doc to link the new official repo.
Fixes #
```release-note
```
=> Reference the official git repo for vsphere provider

clusterctl/clusterdeployer/externalclusterprovisioner/externalbootstrapcluster.go, clusterctl/clusterdeployer/externalclusterprovisioner/externalbootstrapcluster_test.go, clusterctl/validation/validate_cluster_api_objects_test.go
**What this PR does / why we need it**: Fixes failures from running make verify.
Fixes #
```release-note
```
=> fixed errors from running: make verify

README.md
Add times for the implementer office hours and link to meeting notes.
Fixes # N/A
```release-note
NONE
```
=> README: Add implementer office hours

pkg/controller/machine/controller.go
For some actuators we may get our expected cloud instance created, but
it will take a little time before we can populate all the status we want
to from it. (i.e. running state, public IP, etc) This results in the machine 
status showing pending until the next resync in ~10 minutes on AWS 
for example.
I investigated simply returning an error, but this results in the max retries of 10 being hit very
quickly with the current generated controller code and exponential
backoff settings. Because this code appears to be auto-generated, 
I'm not sure if we can or want to start editing it to slow down the retries.
This change adds a specific error type actuators can return to request
that the machine be re-synced in some duration.
**Which issue(s) this PR …
=> Add support for actuators requeuing machines after duration.

pkg/controller/machine/controller.go
The queue required was not created when controller Init was called
leading to a nil reference crash when trying to call enqueueAfter.
Changes to grab the worker queue when enqueuing similar to the
machineset controller.
```release-note
```
=> Fix bug in machine controller enqueueAfter.

README.md
**What this PR does / why we need it**: This PR updates README to keep track of the adoption of the cluster-api/machine-api.
Fixes #
```release-note
```
=> Update README to include API adoption

README.md
Adds the [Kubermatic machine-controller](https://github.com/kubermatic/machine-controller/tree/master) to the API adoption section, as it uses the types from the cluster-api and the machineSet/machineDeployment  controllers:
* https://github.com/kubermatic/machine-controller/blob/dbbc29796d291d9329780efeccea6659f11227d3/pkg/controller/machine/machine.go#L58
* https://github.com/kubermatic/machine-controller/blob/dbbc29796d291d9329780efeccea6659f11227d3/cmd/controller/main.go#L359-L366
Fixes #
_Please confirm that if this PR changes any image versions, then …
=> Add Kubermatic machine-controller to API Adoption section

OWNERS_ALIASES
**What this PR does / why we need it**: Clean up the project owners. This PR only removes folks that should no longer be in the ACLs; it does not attempt to add new folks that should be owners (as I think additions should be done in separate PRs). 
Fixes #
```release-note
NONE
```
=> Remove folks that are no longer project owners.

Makefile, config/crds/cluster_v1alpha1_machinedeployment.yaml, pkg/controller/machinedeployment/machinedeployment_controller_suite_test.go, pkg/controller/machinedeployment/machinedeployment_controller_test.go
It fixes the machineDeployment controller tests
Fixes #
```release-note
NONE
```
=> Fix machineDeployment controller tests

cmd/clusterctl/README.md
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
Fixes #
```release-note
NONE
```
=> Invalid directory path in clusterctl README.md (#574)

README.md
Add to README.md the reference to repo of Tencent Cloud provider implementaion.
```release-note
```
=> add ref to tencent cloud provider

Gopkg.lock, cmd/clusterctl/cmd/create_cluster.go, vendor/sigs.k8s.io/yaml/.gitignore, vendor/sigs.k8s.io/yaml/.travis.yml, vendor/sigs.k8s.io/yaml/CONTRIBUTING.md, vendor/sigs.k8s.io/yaml/LICENSE, vendor/sigs.k8s.io/yaml/OWNERS, vendor/sigs.k8s.io/yaml/README.md, vendor/sigs.k8s.io/yaml/RELEASE.md, vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS, vendor/sigs.k8s.io/yaml/code-of-conduct.md, vendor/sigs.k8s.io/yaml/fields.go, vendor/sigs.k8s.io/yaml/yaml.go, vendor/sigs.k8s.io/yaml/yaml_go110.go
Now that the yaml package has been officially forked to sigs.k8s.io, switch our usage over to the sigs.k8s.io fork.
=> Switch yaml package from ghodss repo to sigs.k8s.io fork

config/crds/cluster_v1alpha1_machinedeployment.yaml, config/crds/cluster_v1alpha1_machineset.yaml, config/samples/cluster_v1alpha1_machinedeployment.yaml, config/samples/cluster_v1alpha1_machineset.yaml, pkg/apis/cluster/v1alpha1/machinedeployment_types.go, pkg/apis/cluster/v1alpha1/machineset_types.go
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
Fixes #
```release-note
Implement Scale Subresource for MachineSet
```
=> Implement Scale Subresource for MachineSet and MachineDeployment (#580)

Makefile
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
Fixes #
```release-note
NONE
```
=> Fix the build comment for clusterctl

pkg/controller/node/node.go
We should ensure machine annotation uniqueness by scoping to the api. Tooling setting this annotation would need to be updated
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/592
```release-note
```
=> ensure machine annotation api uniqueness

.gitignore
=> .gitignore: ignore emacs temp files

README.md
Add cluster api implementation reference for Baidu Cloud.
NONE
NONE
```release-note
NONE
```
=> Add cluster api implementation reference for Baidu Cloud.

docs/book/provider_implementations/overview.md, scripts/fetch_ext_bins.sh
Otherwise when e.g. the file is not found we just fail silenty
```release-note
NONE
```
=> Add -f (--fail) arg to all curl commands

cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
=> kubectl apply: warn on unknown errors, not just known errors

hack/update-bazel.sh, hack/verify-bazel.sh
Signed-off-by: Vince Prignano <vince@vincepri.com>
Given that Bazel is being reintroduced in #601, this PR adds update/verify bazel script based on the work on cluster-api-provider-aws and k/k.
```release-note
```
=> Add {update-verify}-bazel.sh scripts for CI

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Signed-off-by: Vince Prignano <vince@vincepri.com>
Adds bug/features templates for github issues.
Fixes #
```release-note
```
=> Add template for GitHub issues

Makefile
Signed-off-by: Vince Prignano <vince@vincepri.com>
This PR improves the Makefile a little by adding a help section and adding a gazelle target.
```
$ make
Usage:
make <target>
help             Display this help
gazelle          Run Bazel Gazelle
test             Run tests
manager          Build manager binary
clusterctl       Build clusterctl binary
run              Run against the configured Kubernetes cluster in ~/.kube/config
deploy           Deploy controller in the configured Kubernetes cluster in ~/.kube/config
manifests        Generate manifests e.g. CRD, RBAC etc.
fmt              Run go fmt against code
vet              Run go vet against code
generate         Generate code
clientset        Generate a typed clientset
docker-build     Build …
```
=> Refactor Makefile with help

config/default/manager_image_patch.yaml
**What this PR does / why we need it**: I'm planning to tag the repo at the commit that this PR creates, so that when folks vendor at the release commit they will automatically run the version of the controllers that is tagged correctly. Once this PR merges I will send a PR to set the value back to latest. 
Fixes #
```release-note
NONE
```
/assign @chaosaffe @detiber
=> Set the image version for the 0.0.0-alpha.4 release.

cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, pkg/apis/cluster/common/consts.go, pkg/apis/cluster/v1alpha1/cluster_types.go, pkg/apis/cluster/v1alpha1/machine_types.go, pkg/apis/cluster/v1alpha1/machineset_types.go, pkg/controller/machinedeployment/sync.go, pkg/controller/machinedeployment/util/util.go, pkg/controller/machineset/controller.go
Experimenting with some typo finding tools, and this is a batch I found in the comments.
```release-note
NONE
```
=> Typo fixes

Gopkg.lock, pkg/controller/machineset/controller_test.go, pkg/controller/machineset/machine.go, pkg/controller/machineset/machine_test.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Increase unit test coverage for machineSet controller
Fixes #
```release-note
```
=> Increase machineSet unit test coverage

WORKSPACE
Signed-off-by: Vince Prignano <vince@vincepri.com>
Fixes #
```release-note
```
=> Update Bazel to Go 1.11.4

pkg/controller/machine/controller.go
polishing machine controller
Fixes #
```release-note
```
=> Polishing machine controller

README.md
=> Update link to azure cluster-api cloud provider

pkg/controller/machineset/controller.go
Fixes #336
```release-note
NONE
```
=> Replace remaining uses of Poll with PollImmediate.

Dockerfile, config/crds/cluster_v1alpha1_cluster.yaml, config/crds/cluster_v1alpha1_machine.yaml, config/crds/cluster_v1alpha1_machineclass.yaml, config/crds/cluster_v1alpha1_machinedeployment.yaml, config/crds/cluster_v1alpha1_machineset.yaml, config/default/manager_image_patch.yaml-e, pkg/controller/machine/BUILD.bazel, pkg/controller/machinedeployment/BUILD.bazel, pkg/controller/machineset/BUILD.bazel, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/BUILD.bazel
This PR switches to `gcr.io/distroless/static:latest` and adds static flag to build the go binary.
Also updates some bazel files and CRDs with description after update to 1.12.
Fixes #671 
Tested on my local environment, docker builds correctly and manager runs.
```release-note
```
=> Switch from debian:latest to gcr.io/distroless/static:latest

docs/book/README.md
Signed-off-by: Alex Yang <yangyang1@zte.com.cn>
Make the text appear in multi lines.
No issue associated
None
=> Fix format of Resources section in book README

README.md
The existing links are incorrect and the primary meeting notes have been achieved...
=> Update meeting notes and zoom links

Makefile, cmd/manager/BUILD.bazel
=> Add Make dep-ensure

CONTRIBUTING.md, Makefile, cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/clusterdeployer/clusterdeployer.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go, cmd/manager/BUILD.bazel, config/crds/cluster_v1alpha1_machine.yaml, config/crds/cluster_v1alpha1_machinedeployment.yaml, config/crds/cluster_v1alpha1_machineset.yaml, docs/book/common_code/cluster_controller.md, docs/book/common_code/machine_controller.md, docs/book/provider_implementations/create_actuators.md, pkg/apis/cluster/v1alpha1/machine_types.go, pkg/controller/config/configuration.go, pkg/util/util.go
Fixes #688
```release-note
```
=> Master -> Control Plane

cmd/clusterctl/clusterdeployer/bootstrap/BUILD.bazel, cmd/clusterctl/clusterdeployer/bootstrap/kind/BUILD.bazel, cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go, cmd/clusterctl/clusterdeployer/bootstrap/kind/kind_test.go, cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go
This PR adds [KIND](sigs.k8s.io/kind) as a cluster bootstrapper.
Fixes #641 
```release-note
```
=> Add KIND as cluster bootstrapper

cmd/clusterctl/clusterdeployer/bootstrap/existing/BUILD.bazel, cmd/clusterctl/clusterdeployer/bootstrap/existing/cluster.go, cmd/clusterctl/clusterdeployer/bootstrap/existing/cluster_test.go, cmd/clusterctl/clusterdeployer/bootstrap/kind/BUILD.bazel, cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go, config/crds/cluster_v1alpha1_machine.yaml, config/crds/cluster_v1alpha1_machinedeployment.yaml, config/crds/cluster_v1alpha1_machineset.yaml
Renames `existing.ExistingCluster` to `existing.Cluster` given the stutter.
Fixes #
```release-note
```
=> Rename existing bootstrapper

docs/book/README.md
Thanks for the great documentation! Doing my part in "making the place better than I found it :)"
=> Fix the GitBook link in the docs

docs/book/README.md, docs/book/common_code/architecture.md, docs/book/common_code/machine_controller.md, docs/book/provider_implementations/building_running_and_testing.md, docs/book/provider_implementations/create_actuators.md
=> Fix some typos and dead links in the documentation

OWNERS_ALIASES
- Graduates @vincepri  to approver :tada: 
- Removes @jessicaochen, @karan, @kris-nova, & @mkjelland :wave: 
from the OWNERS file.
Welcome and congrats new reviewers and approvers! Thanks for all of the contributions from the emeritus approvers, and hopefully we'll see you around again!
```release-note
NONE
```
=> Update project maintainers

Dockerfile, WORKSPACE
Latest Go CVE: https://groups.google.com/forum/m/#!topic/golang-announce/mVeX35iXuSw
=> use latest security patch release of golang

config/BUILD.bazel
Would like access to the CRD files for use elsewhere, independently of the provider components.
Fixes #
```release-note
```
=> Make CRDs public in Bazel

OWNERS
As the title says
```release-note
NONE
```
=> Updated link to OWNERS docs

cmd/clusterctl/clusterdeployer/BUILD.bazel, cmd/clusterctl/clusterdeployer/clusterdeployer.go, pkg/controller/machinedeployment/controller.go, pkg/controller/machineset/controller.go
Fixes #738 
```release-note
```
=> Validate MachineSet and MachineDeployment labels

OWNERS_ALIASES
Adds OWNERS_ALIASES file for prow automation
```release-note
NONE
```
=> Add OWNERS_ALIASES file

pkg/util/util.go, pkg/util/util_test.go
Reworked util.ParseMachineYaml to enforce APIVersion and Kind as requirements to parse a MachineList object.
As this is a breaking change a new message is introduced when parsing a YAML file that uses the old convention, test suite was upgraded with a few cases.
Recommended to move to `UniversialDeserializer` once the API is stabilized and added to `k8s.io/client-go`
Fixes: #717
=> Make APIVersion/Kind mandatory for MachineList

config/BUILD.bazel
=> Fix Bazel after Kustomize2 update

cmd/clusterctl/clusterdeployer/clusterdeployer.go
=> Cleanup ownerRef on Machine upon pivot

pkg/controller/machineset/controller.go, pkg/controller/machineset/controller_test.go
This PR is a general cleanup towards v1alpha1 for MachineSet controller code. It doesn't change any logic or behavior.
Fixes #
```release-note
```
=> Cleanup MachineSet controller

docs/book/provider_implementations/overview.md
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/781
```release-note
Clarify kubebuilder minimal version is 1.0.5.
```
=> Clarify kubebuilder minimal version is 1.0.5.

docs/book/provider_implementations/register_schemes.md
Fix #742 CrashLoopBackOff in sample provider from book due to missing flag in manager
=> Add missing flag to manager in sample provider code

cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go, cmd/clusterctl/cmd/create_cluster.go, cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/create-cluster-no-args.golden
Fixes #
```release-note
NONE
```
=> Deleted cloud providers for clusterctl help.

cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/844
```release-note
Enable setting profile for minikube bootstrap cluster.
```
=> Enable setting profile for minikube bootstrap cluster.

Dockerfile, WORKSPACE, config/rbac/rbac_role.yaml, pkg/controller/machine/controller.go
This PR updates Bazel and Dockerfile to use Go 1.11.6
Fixes #
```release-note
```
=> Update to Go 1.11.6

cmd/clusterctl/README.md
Fixes #
```release-note
Added kind support for clusterctl README.
```
=> Added kind support for README.

docs/book/common_code/machinedeployment_controller.md
Fixes #
```release-note
NONE
```
=> Added more spec for machinedeployment.

docs/book/provider_implementations/register_schemes.md
Update docs about sample provider implementation
Fixes #848
```release-note
Sample provider implementation docs are updated to include klog flags
```
=> Update sample provider implementation

cmd/clusterctl/README.md
Fixes #
```release-note
NONE
```
=> Clarify how to use kubeconfig

README.md
This PR adds a link to the newly created discuss forum dedicated to Cluster API.
Fixes #
```release-note
```
=> Add discuss link to README

cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/clusterdeployer/clusterdeployer.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
Fixes #888 
```release-note
```
=> Backport #878, so it can be used within CAPA project

Gopkg.lock, cmd/clusterctl/main_integration_test.go, cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/create-cluster-no-args.golden, cmd/clusterctl/testdata/create-no-args-invalid-flag.golden, cmd/clusterctl/testdata/create-no-args.golden, cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/delete-cluster-no-args.golden, cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden, cmd/clusterctl/testdata/delete-no-args.golden, cmd/clusterctl/testdata/no-args-invalid-flag.golden, cmd/clusterctl/testdata/no-args.golden, cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden, cmd/clusterctl/testdata/validate-no-args.golden, vendor/k8s.io/klog/.travis.yml, vendor/k8s.io/klog/CONTRIBUTING.md, vendor/k8s.io/klog/OWNERS, vendor/k8s.io/klog/README.md, vendor/k8s.io/klog/SECURITY_CONTACTS, vendor/k8s.io/klog/code-of-conduct.md, vendor/k8s.io/klog/klog.go, vendor/k8s.io/klog/klog_file.go
This PR updates the `klog` dependency to the current revision which solves and issue where verbose flag wouldn't work as expected.
Fixes #
```release-note
```
=> Update klog to 0.3.0

config/rbac/rbac_role.yaml
Fixes the errors below:
_**machinedeployments/status**_
```
E0415 10:02:02.078867       1 controller.go:179] Failed to reconcile MachineDeployment "mv1a/mv1a-nodes": machinedeployments.cluster.k8s.io "mv1a-nodes" is forbidden: User "system:serviceaccount:cluster-api-system:default" cannot update resource "machinedeployments/status" in API group "cluster.k8s.io" in the namespace "mv1a"
```
_**patch events**_
```
'events "mv1a-nodes.15959c14d99b1db9" is forbidden: User "system:serviceaccount:cluster-api-system:default" cannot patch resource "events" in API group "" in the namespace "mv1a"' (will not retry!)
```
_**machinesets/status**_
```
E0415 12:27:01.488955       1 controller.go:161] Failed to reconcile MachineSet "mv1a/mv1a-nodes-84b6c876c": …
```
=> Update manager-role ClusterRole

README.md, docs/scope-and-objectives.md
This PR adds a high level document which is meant to serve as guardrails for what's in scope and what's out of scope. The document is not meant to be final but instead is meant to be updated as new ideas or features come up and are discussed.
/assign @timothysc 
/assign @justinsb
=> Add Cluster API project scope and objectives

pkg/util/util.go
This PR simplifies the logic in `util.ParseMachinesYaml` and removes a now-unused function.
Fixes #
```release-note
```
=> Simplify util.ParseMachinesYaml

README.md
This PR documents the Talos Cluster API provider.
```release-note
```
=> Add Talos to list of providers

docs/staging-use-cases.md
One of the sets of use-cases doesn't have a bullet point. There's only one now, but it should be bulleted list like all the other sections.
```release-note
NONE
```
=> Add missing bullet point to staging-use-cases.md

README.md
Fixes #
```release-note
NONE
```
/cc @detiber @vincepri
=> Added IBM Cloud to Cluster API README.

docs/book/common_code/architecture.md
Addresses #926 
```release-note
NONE
```
=> Update documentation links to published content

README.md
Fixes #
```release-note
NONE
```
/cc @detiber @vincepri
=> Adding Reference Use Cases to README.

Makefile, config/default/manager_image_patch.yaml
=> Release 0.1.1

docs/staging-use-cases.md
Fixes #
Using `doctoc` generated toc is more accurate.
/cc @detiber @vincepri 
```release-note
NONE
```
=> Used doctoc generated toc.

pkg/provider/example/container/Dockerfile, scripts/ci-integration.sh
- Use specific versions of kind and kustomize instead of installing
with `go get`
```release-note
NONE
```
=> Attempt to fix integration tests

README.md
Add Exoscale provider link to `README.md`
Fixes #
Fix nothing
```release-note
Add Exoscale provider to README
```
=> Add Exoscale link to README.md

cmd/clusterctl/clusterdeployer/clusterdeployer.go
Cannot get the machine name there. so just replace with `machine` string.
Signed-off-by: clyang82 <clyang@cn.ibm.com>
=> Cannot retrieve machine name

pkg/controller/cluster/cluster_controller.go
This PR is an attempt to solve #985 by adding the `foregroundDeletion` finalizer to the Cluster object.
Fixes #
```release-note
```
=> Add foregroundDeletion finalizer to Cluster object

Makefile, config/default/manager_image_patch.yaml
=> Release 0.1.2

Makefile, config/default/manager_image_patch.yaml
=> Release 0.1.3

cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go, cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
This PR is for https://github.com/kubernetes-sigs/cluster-api/issues/981
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
=> support random generate cluster name

WORKSPACE
Update some bazel dependencies
```release-note
NONE
```
=> Update some bazel dependencies

scripts/ci-is-vendor-in-sync.sh
This PR makes sure to install `dep` when running `ci-is-vendor-in-sync`. This is needed after the update to the CI images to 1.12 
Fixes #
```release-note
```
=> Update dep check

cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
=> Fix register bootstrap options in alpha phases

hack/boilerplate.go.txt
This PR adds `hack/boilerplate.go.txt` for kubebuilder generated files, fixes the following error:
```
2019/06/25 08:42:17 error scaffolding controller: open hack/boilerplate.go.txt: no such file or directory
```
Fixes #
```release-note
```
=> Add boilerplate.go.txt for kubebuilder

cmd/clusterctl/phases/getkubeconfig.go
Update log message.
Fixes #1076 
No image change.
```release-note
NONE
```
=> correct word

Makefile, config/default/manager_image_patch.yaml, docs/developer/releasing.md
Updates images for v0.1.4
```release-note
NONE
```
=> Release v0.1.4

cmd/clusterctl/validation/BUILD.bazel, cmd/clusterctl/validation/validate_cluster_api_objects_test.go, config/crds/cluster.sigs.k8s.io_machinedeployments.yaml, config/crds/cluster.sigs.k8s.io_machines.yaml, config/crds/cluster.sigs.k8s.io_machinesets.yaml, docs/proposals/20190610-machine-states-preboot-bootstrapping.md, pkg/apis/cluster/v1alpha2/BUILD.bazel, pkg/apis/cluster/v1alpha2/machine_types.go, pkg/apis/cluster/v1alpha2/machine_types_test.go, pkg/apis/cluster/v1alpha2/machinedeployment_types_test.go, pkg/apis/cluster/v1alpha2/machineset_types_test.go, pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go, pkg/controller/error/BUILD.bazel, pkg/controller/error/requeue_error.go, pkg/controller/machine/BUILD.bazel, pkg/controller/machine/machine_controller.go, pkg/controller/machine/machine_controller_phases.go, pkg/controller/machine/machine_controller_phases_test.go, pkg/controller/machine/machine_controller_test.go, pkg/controller/machine/machine_reconciler_test.go, pkg/controller/machinedeployment/BUILD.bazel, pkg/controller/machinedeployment/machinedeployment_reconciler_test.go, pkg/controller/machineset/BUILD.bazel, pkg/controller/machineset/machineset_reconciler_test.go, pkg/controller/noderef/BUILD.bazel, pkg/controller/noderef/noderef_controller_test.go, pkg/util/BUILD.bazel, pkg/util/util.go, vendor/modules.txt
=> v1alpha2 Machine Controller logic

PROJECT
This PR is a follow-up to v1alpha2 and updates the Kubebuilder file to use `sigs.k8s.io` as default domain.
Fixes #
```release-note
```
=> Switch kubebuilder domain to sigs.k8s.io

Dockerfile
This PR updates the base image to Go 1.12.6 and the build flags to use go modules and vendor.
Fixes #
```release-note
```
=> Update Go to 1.12.6 and update build flags in Dockerfile

pkg/controller/external/util.go, pkg/controller/machine/machine_controller.go, pkg/controller/machine/machine_controller_phases.go, pkg/controller/machineset/machineset_controller.go
This PR adds a new package called `external` with the purpose of easing the work with unstructured objects. Specifically the changes move functions from the Machine Controller to a package and it adds a new function called `Clone` that will be used by the Machine Set to clone external references. 
Related to #1036 
```release-note
```
=> Add external package to work with unstructured objects

pkg/controller/cluster/cluster_controller.go
=> Change controllerError to lowercase

OWNERS_ALIASES
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
Fixes #
```release-note
```
=> Match ncdc owner aliases with k/org

docs/book/RELEASE
Documentation changes need to be reviewed before they are deployed and these instructions are platform agnostic unlike the existing ones.
Fixes #1005 
None.
```release-note
```
=> Document Netlify based OS agnostic testing (fixes #1005).

pkg/controller/machine/machine_controller.go, pkg/controller/machine/machine_controller_test.go
This commit moves some logic from the Reconcile() method
into a new function needUpdateFinalizers.  The primary
aim is to reduce complexity of Reconcile() method as
there are too many code paths for linters.
This commit also adds unit tests to validate the
logic of adding missing finalizers.
Fixes #
```release-note
NONE
```
=> [0.1] Reduce Reconcile() complexity with needUpdateFinalizers

BUILD.bazel, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
=> Add gazelle rule for grpc-ecosystem

config/rbac/role.yaml, pkg/controller/cluster/cluster_controller.go, pkg/controller/machine/machine_controller.go, pkg/controller/machinedeployment/machinedeployment_controller.go, pkg/controller/machineset/machineset_controller.go
This PR reverts a change that was originally made in #1051 because the `-` was colliding with the metrics and reporting test failures. It seems this issue has been fixed in a later controller-runtime version.
Fixes #
```release-note
```
=> Rename controller name with - instead of _

README.md, docs/how-to-use-clusterctl.md
This PR adds a doc that explains how to use `clusterctl`.  
The doc provides an overview of all the steps the `clusterctl` performs in creating a k8s cluster.
This doc would help newcomers better understand the flow of how `clusterctl` works and could potentially also help in understanding some nomenclature involved in Cluster API.
Fixes #
```release-note
```
/cc @ncdc 
/cc @vincepri
=> Doc on clusterctl. How to use and how it works.

pkg/controller/noderef/noderef_controller.go
This is backport of #1117 to release-0.1
Fixes #
```release-note
NONE
```
=> [0.1] Don't swallow errors when reconciling noderef

pkg/util/util.go
This PR removes a deprecated function from util package and adds a new helper to work with MachineList.
Fixes #
```release-note
```
=> Add GetControlPlaneMachinesFromList and remove deprecated function

docs/book/npm-shrinkwrap.json, docs/book/package-lock.json
Update lodash to address CVE
Fixes #1168
```release-note
NONE
```
=> Update lodash to address CVE

docs/book/GLOSSARY.md
#1071 
Have added a few missing definitions.
=> Update glossary doc with terminology

pkg/controller/machine/machine_controller.go
=> Always Patch machines on defer, requeue if finalizer cannot be removed

netlify.toml
Update Netlify config for v1alpha1 subdomain
```release-note
NONE
```
=> Update Netlify config for v1alpha1 subdomain

Makefile
Instead of building `manager` binary from local, it's better to build from a container. 
The build command in the changes is consistent with the Dockerfile in the root directory
/cc @figo 
N/A
```release-note
NONE
```
=> Build manager binary inside a container

config/crds/cluster.x-k8s.io_machines.yaml, pkg/apis/cluster/v1alpha2/machine_types.go, pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go, pkg/controller/machine/machine_controller_phases.go, pkg/controller/machine/machine_controller_phases_test.go, pkg/controller/machine/machine_controller_test.go, pkg/util/BUILD.bazel, pkg/util/util.go, vendor/modules.txt
This PR is a follow-up to #1162, adds the needed logic to copy addresses from the infrastructure provider object to the Machine.
Fixes #
```release-note
```
=> Add logic to copy Machine Addresses from InfraRef

cmd/clusterctl/validation/validate_cluster_api_objects_test.go, pkg/apis/cluster/v1alpha2/machine_types_test.go, pkg/apis/cluster/v1alpha2/machinedeployment_types_test.go, pkg/apis/cluster/v1alpha2/machineset_types_test.go, pkg/controller/external/testing.go, pkg/controller/machine/machine_controller_phases_test.go, pkg/controller/machine/machine_controller_test.go, pkg/controller/machine/machine_reconciler_test.go, pkg/controller/machinedeployment/machinedeployment_reconciler_test.go, pkg/controller/machineset/machineset_reconciler_test.go, vendor/modules.txt
=> Use v1alpha2 as version in tests

README.md
Add Packet to the list of cluster-api provider implementations
Many thanks to the team members who helped shepherd this along. Particular note to @ncdc who was extraordinarily patient.
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._ No image changes. Changes only the `README.md`
```release-note
Add Packet cluster-api provider to list.
```
=> Add Packet to cluster-api provider list

OWNERS_ALIASES
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
(cherry picked from commit 61ad9c27607f3e09729ef3a215eade20ac4079ff)
This is a backport of #1087 to release-0.1.
Fixes #
```release-note
```
=> [0.1] Match ncdc owner aliases with k/org (#1087)

pkg/controller/machine/machine_controller.go
This PR fixes an issue where the GVK from controller-runtime is cleared when a Patch/Update is issued.
Fixes #
```release-note
```
=> Fix GVK in Machine Controller

pkg/util/util.go, pkg/util/util_test.go
Add GetOwnerCluster and ClusterToInfrastructureMapFunc to mirror the
helpers we already have for Machines.
Fixes #
```release-note
NONE
```
/assign @detiber 
/milestone v1alpha2
/priority important-soon
=> Add Cluster helper funcs for infra providers to use

docs/book/ABBREVIATIONS.md
Adds another acronym to prevent openstack cluster api provider from being called OSCAP like I did my first time :)
Fixes #
=> Add openstack acronym to gitbook

pkg/util/util.go
=> Return early if InfrastructureRef is nil

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go, vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go, vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go, vendor/sigs.k8s.io/controller-tools/pkg/genall/help/pretty/help.go
=> Update controller-tools to v0.2.0-beta.5

Makefile, config/default/manager_image_patch.yaml
Updates image versions for the v0.1.9 release.
Fixes #
```release-note
NONE
```
=> Release v0.1.9

hack/build-gitbook.sh, hack/pin-dependency.sh, hack/update-vendor.sh, hack/verify-bazel.sh, hack/verify-clientset.sh
This PR fixes some shellcheck-reported issues in hack/ bash scripts.
Fixes #1196
```release-note
```
=> Improve hack files

Makefile, hack/verify-generated-files.sh
Fixes #1172 
```release-note
- add verify-generated-files.sh and accompanying make verify target
```
=> chore: verify-generated-files

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR simplifies the PR template and requires users to add an emoji to the title to generate release notes
Fixes #
```release-note
NONE
```
=> Require PR title to include typed emoji

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go, vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
=> :running: Update controller-{runtime, tools} to v0.2.0-rc.0

Dockerfile, WORKSPACE, cmd/example-provider/Dockerfile
=> 🏃Update Go 1.12.9 / Bazel deps

controllers/machineset_controller.go
Sets up recorder for machineset controller, which fixes some NPEs.
Fixes #
```release-note
```
=> 🐛 chore: set up recorder for machineset controller

api/v1alpha2/cluster_types.go, api/v1alpha2/machine_types.go, api/v1alpha2/machinedeployment_types.go, api/v1alpha2/machineset_types.go, config/crd/bases/cluster.x-k8s.io_clusters.yaml, config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml, config/crd/bases/cluster.x-k8s.io_machines.yaml, config/crd/bases/cluster.x-k8s.io_machinesets.yaml
Add capi categories so that we can do `kubectl get cluster-api`
Fixes #
```release-note
```
=> add cluster-api categories

api/v1alpha2/cluster_types.go, config/crd/bases/cluster.x-k8s.io_clusters.yaml
Adds `Phase` to Cluster's printcolumn
Fixes #
```release-note
```
=> ✨ Add Phase printcolumn to Cluster

cmd/clusterctl/main_integration_test.go, cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/create-cluster-no-args.golden, cmd/clusterctl/testdata/create-no-args-invalid-flag.golden, cmd/clusterctl/testdata/create-no-args.golden, cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/delete-cluster-no-args.golden, cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden, cmd/clusterctl/testdata/delete-no-args.golden, cmd/clusterctl/testdata/no-args-invalid-flag.golden, cmd/clusterctl/testdata/no-args.golden, cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden, cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden, cmd/clusterctl/testdata/validate-no-args.golden, go.mod, go.sum, vendor/k8s.io/klog/.travis.yml, vendor/k8s.io/klog/README.md, vendor/k8s.io/klog/go.mod, vendor/k8s.io/klog/go.sum, vendor/k8s.io/klog/klog.go, vendor/modules.txt
=> Bump klog v0.3.1 to v0.4.0

cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
This PR adds a retry poll when clusterctl acquires a client, this is now needed because controller-runtime returns an error immediately if it can't connect to the cluster.
Fixes #
```release-note
```
=> ✨Add retry poll when acquiring a new clusterctl client

scripts/ci-integration.sh
This PR updates KIND to the latest released version for the ci-integration script.
Fixes #
```release-note
```
=> 🏃Update KIND in CI to 0.5.0

controllers/machine_controller.go, controllers/machine_controller_test.go
Fixes #1297 
```release-note
```
=> 🐛fix: clean up isDeleteReady logic

BUILD.bazel, cmd/example-provider/BUILD.bazel, cmd/example-provider/main.go, controllers/BUILD.bazel, controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machineset_controller.go, controllers/suite_test.go, main.go
Support setting concurrency in all controllers.
Fixes #1304
=> ✨ Support concurrency in all controllers

cmd/example-provider/main.go, controllers/suite_test.go, main.go
=> 🏃Fixup nits from #1312

Dockerfile
=> :running: Allow to provide custom GOPROXY

controllers/external/util.go
This PR allows templated references to have an empty APIVersion and Kind field by copying the values present in the object reference. The Kind value is a special case: the word `Template` is stripped when it's a suffix of the object reference's Kind.
Fixes #
=> ✨ Allow for easier UX when using MS/MD template refs

cmd/clusterctl/cmd/validate_cluster.go, cmd/clusterctl/main.go, cmd/clusterctl/validation/validate_cluster_api_objects.go, cmd/clusterctl/validation/validate_cluster_api_objects_suite_test.go, cmd/clusterctl/validation/validate_cluster_api_objects_test.go, cmd/example-provider/main.go, controllers/cluster_controller_phases.go, controllers/machine_controller_noderef.go, controllers/machine_controller_noderef_test.go, controllers/machine_controller_phases.go, controllers/machine_controller_phases_test.go, controllers/machine_controller_test.go, controllers/machineset_controller_test.go, controllers/machineset_delete_policy.go, controllers/machineset_delete_policy_test.go, controllers/machineset_status.go, controllers/mdutil/util.go, controllers/mdutil/util_test.go, controllers/remote/cluster.go, controllers/remote/cluster_test.go, controllers/suite_test.go, main.go, util/patch/patch_test.go
Trying to keep consistency in how the imports are named across the repository.
Fixes #
=> 🏃‍♂️ Name v1alpha2 imports

hack/tools/release/notes.go
All cosmetic improvements, it always sorts out the order in a preset format, it now cleans up the individual emojis and adds bullet points.
Fixes #
=> 🏃Release notes tool improvements

controllers/machine_controller.go
=> 🐛 Retrieve only non-deleted Machines

controllers/cluster_controller.go
=> 🐛Delete control plane Machines at the end

controllers/cluster_controller_phases.go
This patch updates the behavior of the cluster controller's "reconcileInfrastructure" function so that the API endpoints are always reconciled if they have not been set and the infrastructure is supposed to be otherwise ready.
Fixes #1359
=> :bug: Update API endpoints if missing

Makefile
Make sure we actually push the manifest.
Add variables for staging registry, prod registry, image name.
Fixes #
=> :running: Release target fixes

cmd/clusterctl/clusterdeployer/BUILD.bazel, cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel, cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go, cmd/clusterctl/phases/BUILD.bazel, cmd/clusterctl/phases/pivot.go, cmd/clusterctl/phases/pivot_test.go, config/rbac/rbac_role.yaml, config/rbac/rbac_role_binding.yaml
=> [0.1] Pivot secrets

.gitignore, Makefile
=> 🏃Add release binaries target to Makefile

Makefile, docs/developer/releasing.md
=> 🏃 Update the release docs to reflect the new process

controllers/machinedeployment_controller.go, controllers/machinedeployment_sync.go
=> 🏃 MachineDeploymentReconciler: make Client a proper field

controllers/machineset_controller.go
=> 🏃 MachineSetReconciler: make Client a proper field

controllers/machine_controller.go, controllers/machine_controller_phases.go
=> 🏃 MachineReconciler: make Client a proper field

docs/proposals/20190610-machine-states-preboot-bootstrapping.md, docs/proposals/20190709-cluster-spec-crds.md
This PR only marks the proposals as implemented, there are still some sections to be filled, left for a future revision.
=> 📖 Mark proposals as implemented

Makefile, config/default/manager_image_patch.yaml
=> :running: Prepare for v0.1.10

docs/book/src/user/quick-start.md
=> 📖 Improve quickstart for AWS components installation

docs/book/src/abbreviations.md, docs/book/src/architecture/controllers.md, docs/book/src/architecture/controllers/machine-deployment.md, docs/book/src/architecture/controllers/machine-set.md, docs/book/src/architecture/developer-guide.md, docs/book/src/architecture/repository-layout.md, docs/book/src/tooling/tooling.md
- Add text to indicate that some documentation is still WIP.
- Remove empty duplicate abbreviations doc.
Fixes #
=> :book: Add WIP for various docs

docs/developer/releasing.md
Update a reference to the GCR used to the cluster-api-controller image
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
=> 📖 Updated release docs

Makefile
=>  🏃 Add go mod verification in CI

docs/book/theme/css/general.css
=> :running: Fix table CSS

controllers/cluster_controller_phases.go
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
Remove redundant OwnerReference check in `reconcileExternal`.
Fixes #1389
=> ✨ Removed redundant OwnerReference check

controllers/machinedeployment_sync.go, controllers/mdutil/util.go
=> 🏃Remove unused function `isScalingEvent`

docs/book/src/user/quick-start.md
=> 📖  Embed AWS pre-requisites document

docs/book/src/architecture/controllers/cluster.md
Also fix format of status example
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR improves documentation.
Fixes #1478
=> 📖 Fix link in Cluster controller doc

main.go
=>  🐛 Remove duplicate add to scheme for v1alpha3

docs/book/OWNERS
This PR promotes @randomvariable and @moshloop to be reviewers of our Cluster API book. 
Thank you all for offering your help for documentation efforts!
=> 🏃Promote reviewers for docs/book

Makefile, cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go, cmd/clusterctl/phases/applyclusterapicomponents.go, cmd/clusterctl/phases/pivot.go, cmd/clusterctl/phases/pivot_test.go, config/certmanager/cert-manager.yaml
=> ⚠️ Add cert-manager

controllers/machineset_controller.go, controllers/machineset_controller_test.go
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR patches the machine set object as soon as the owner references are added. This follows the same behavior as the MachineDeployment controller. Since there is no `defer patch` in the machine set.
I created this separate PR as per the request of @vincepri 
NA
=> 🏃Add OwnerReference unit test for machineset

config/default/manager_image_patch.yaml
=> Change the default image in manifests to target release-0.2

api/v1alpha3/cluster_types.go, config/crd/bases/cluster.x-k8s.io_clusters.yaml
Changed APIEndpoint.Port from int to int32
Fixes #1418
=> Changed APIEndpoint.Port from int to int32

controllers/external/util.go, controllers/machineset_controller.go
=> ⚠️ Use context as first parameter for external.CloneTemplate

docs/book/src/tasks/installation.md, docs/book/src/user/quick-start.md
Cherry pick from @dlipovetsky commit
Fixes #1549
=> 📖 Add quick start for the Docker provider [port]

docs/book/src/providers/v1alpha2-to-v1alpha3.md
=> 📖Start documenting v1alpha3 changes for providers

controllers/machineset_controller.go, controllers/machineset_controller_test.go
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR adds some more unit tests to the machine set controller. It also does some minor refactors like passing `ctx` into the `adoptOrphan` function and ~~patches the machine set object as soon as the owner references are added. This follows the same behavior as the MachineDeployment controller.~~
NA
=> 🏃Add unit tests for machineset controller

controllers/cluster_controller.go, controllers/cluster_controller_phases.go, controllers/machine_controller.go, controllers/machine_controller_noderef.go, controllers/machine_controller_phases.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_rolling.go, controllers/machinedeployment_sync.go, controllers/machineset_controller.go, controllers/machineset_controller_test.go, controllers/machineset_status.go, controllers/mdutil/util.go, controllers/mdutil/util_test.go
Fixes #1203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes-sigs/cluster-api/1456)
=> 🏃 Remove raw klog calls in controllers

api/v1alpha3/machine_types.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, bootstrap/kubeadm/internal/cluster/certificates.go, cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go, cmd/clusterctl/phases/pivot_test.go, controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/machine_controller.go, controllers/machine_controller_phases_test.go, controllers/machine_controller_test.go, controllers/machine_helpers.go, controllers/machine_helpers_test.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go, controllers/machineset_controller.go, controllers/machineset_controller_test.go, docs/book/src/providers/v1alpha2-to-v1alpha3.md, util/util.go
=> 🏃 Rename MachineClusterLabelName to ClusterLabelName

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, bootstrap/kubeadm/controllers/token.go
=> 🏃 Use controller-runtime client everywhere in bootstrap/kubeadm

docs/book/src/reference/glossary.md
=> :book: Add CAPIBM (IBMCloud) to the book glossary

controllers/cluster_controller_phases_test.go, util/util.go
=> 🏃 Remove init from util/util.go

cmd/clusterctl/phases/pivot.go
=>  🐛Fixes an issue during clusterctl pivot when resource references are missing namespaces

docs/book/src/reference/glossary.md
Add a definition for a stacked control plane.
=> 📖 Glossary: Add stacked control plane

third_party/kubernetes-drain/drain.go
- Pull in changes from https://github.com/kubernetes/kubernetes/pull/83967
Fixes #1632
=> :running: Update forked kubectl drain library

docs/book/SUMMARY.md, docs/book/src/SUMMARY.md, docs/book/src/architecture/controllers/node.md
**What this PR does / why we need it**: 📖 Remove empty node/noderef controller docs
Fixes #
=> 📖 Remove empty node/noderef controller docs

docs/book/src/user/quick-start.md
=> 🐛Fixes an incorrect IAM role in the Quick Start for AWS

controllers/cluster_controller_test.go
Increase the timeout waiting for the machine to get a finalizer because we've been seeing failures in Prow for this particular block. It looks like it's sometimes taking more than 10 seconds (the value of timeout) for the machine reconciler to add the finalizer and for the change to be persisted to etcd. If we continue to see test timeouts here, that will likely point to something else being the problem, but I've yet to determine any other possibility for the test flakes.
Maybe #1597
=> 🐛 Increase timeout waiting for machine finalizer

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/proposal.md
=> 🏃Add proposal issue template / simplify feature request

docs/book/src/tasks/installation.md, docs/book/src/user/quick-start.md
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
Updates CAPV's quick start guide based on the upcoming v0.5.2 changes. 
Fixes #
=> :book: Updates to vSphere Quick Start based on upcoming v0.5.2 changes

docs/book/src/user/quick-start.md
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
Back porting https://github.com/kubernetes-sigs/cluster-api/pull/1671
Fixes #
=> :book: vSphere quick start fixes

config/manager/manager.yaml
=> :running: Remove limits and request from manager definition

Makefile, docs/developer/releasing.md
Adds `release-notes` to the Makefile and the release document. 
Fixes #1681
=> 📖 Document how to generate release notes

controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go, controllers/machinedeployment_sync.go
=> :bug: Fix MachineDeployment Status.Selector not being populated

Makefile, scripts/ci-test.sh
=> :running: Simplify Makefile test pre-req

Makefile, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, bootstrap/kubeadm/types/v1beta1/utils.go, cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, cmd/clusterctl/validation/validate_pods_test.go
Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>
Fixes #
=> 🏃 Remove some lint exceptions

hack/verify-shellcheck.sh
Updates verify-shellcheck.sh file which allows shellcheck to work as intended. 
Fixes #1693
=> 🐛 Fix shellcheck verification

config/certmanager/kustomizeconfig.yaml
=> :running: Fix a bug in certmanager/customizeconfig

docs/proposals/20191016-e2e-test-framework.md
This PR is the proposal for the test framework. Providers will be able to use this framework to quickly build out an e2e test suite that they will be responsible or running
=> 📖 CAEP: e2e test framework

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, cmd/clusterctl/clusterdeployer/clusterdeployer_test.go, controllers/cluster_controller_test.go, controllers/machine_controller_phases_test.go, controllers/machine_controller_test.go, docs/book/src/providers/v1alpha2-to-v1alpha3.md, util/util.go
=> 🐛 Check existence of MachineControlPlaneLabelName label instead of value

docs/book/src/tasks/installation.md, docs/book/src/user/quick-start.md
Add Azure provider instructions in the cluster api book.
Fixes #
=> 📖 Add Azure tabs to quickstart book

docs/book/src/tasks/installation.md, docs/book/src/user/quick-start.md
**What this PR does / why we need it**: port forward #1562 to master.
Fixes #
=> 📖 Add MacOS instructions for CAPD [port]

docs/book/src/tasks/installation.md, docs/book/src/user/quick-start.md
**What this PR does / why we need it**: port PR #1654 to master.
Fixes #
=> 📖 Add Azure tabs to quickstart book [port]

docs/book/src/reference/providers.md
alibaba cloud v1alpha2  provider    https://github.com/oam-oss/cluster-api-provider-alicloud
=> add alibaba cloud  provider（cluster api v1alpha2）

docs/book/src/reference/glossary.md
As I was reading the definition of Immutability in the glossary (https://cluster-api.sigs.k8s.io/reference/glossary.html), I stumbled upon an invalid sentence and I wanted to fix it.
=> 📖 Fix typo in the definition of "Immutability"

docs/book/src/tasks/installation.md
Fixes #1750 for release-0.2 branch
See also PR #1752
=> 📖 Fix components file link for docker provider

docs/proposals/20191017-kubeadm-based-control-plane.md
Add @amy as an author in the KubeadmControlPlane CAEP as she was involved with the upgrade content.
/kind proposal
/priority important-soon
/assign @detiber @randomvariable @joonas
=> 📖 Add Amy to KubeadmControlPlane CAEP

Makefile, scripts/ci-build.sh
Signed-off-by: Javier Darsie jadarsie@microsoft.com
~~I think the build is broken, this PR fixes it~~
~~Last commit fixes #1772~~
Fixes #1772
=> 🏃 add e2e framework to CI build

docs/book/src/providers/implementers-guide/building_running_and_testing.md, docs/book/src/providers/implementers-guide/create_api.md, docs/book/src/providers/implementers-guide/generate_crds.md
=> 📖 Fixes in infrastructure provider implementor guide

netlify.toml
Reverts kubernetes-sigs/cluster-api#1843
=> Revert ":book: Add automatic redirects for the development docs book to Netlify config"

docs/book/src/tasks/installation.md
=> :book: Update docs to support KIND v0.6.x

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
=> :bug: Handle CABPK secret case where status has been lost

main.go
This PR will add a `--enable-kubeadm-bootstrapper` flag that defaults to true. This
is needed to disable the built-in kubeadm bootstrapper for alternate
bootstrap providers. This is part of ongoing work for truing up #1686.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
=> :sparkles: add flag for disabling kubeadm controllers

docs/book/src/SUMMARY.md, docs/book/src/user/troubleshooting.md
Adds troubleshooting guide to the docs with an initial entry with a tip for the issue #1719
Fixes #1719
=> :book: Add troubleshooting page to the doc

docs/book/src/user/troubleshooting.md
amend the note that was recently added in https://github.com/kubernetes-sigs/cluster-api/pull/1883
NONE
/priority backlog
/assign @detiber  @chuckha
=> book/troubleshooting.md: amend the entry about node-role labels

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
=> :bug: Properly set the cluster label name on bootstrap secrets

Dockerfile, Makefile, cmd/example-provider/Dockerfile, docs/book/src/providers/v1alpha2-to-v1alpha3.md, go.mod, hack/ensure-go.sh, hack/tools/go.mod, test/framework/go.mod, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/go.mod, test/infrastructure/docker/hack/tools/go.mod
=> :running: Update Go 1.13

docs/book/src/SUMMARY.md
Adds the control plane spec to the summary file
=> book: Add control plane controller to sidebar

scripts/ci-capd-e2e.sh
Related to #1921 
After this I can call the script from a prow job
=> 🏃 adds capd e2e ci script

Tiltfile
Use sh to invoke restart.sh when restarting a running container.
Fixes #
=> 🏃 tilt: fix restarting

api/v1alpha3/machinepool_webhook.go, config/webhook/manifests.yaml
Fix machinedeployment webhooks that were accidentally targeting
machinedeployments.
Fixes #
=> 🐛 Fix machinedeployment webhooks

bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
=> :bug: passwd is omitempty because it's optional

bootstrap/kubeadm/docs/external-etcd.md
=>  📖 External etcd doc improvement

controllers/machinedeployment_controller.go
=> :bug: fix NPEs when the user doesn't assign labels to MD

api/v1alpha2/conversion.go, bootstrap/kubeadm/api/v1alpha2/conversion.go, util/conversion/conversion.go, util/conversion/conversion_test.go
=> 🐛Preserve data when performing down-conversions

Makefile
This PR fixes a bug in the Makefile.
=>  🐛 Fix typo in Makefile

bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
This PR makes the init locker log more relevant log lines and removes an error log when it's not really an error.
=> 🏃 Improve logs and fix an outstanding TODO

docs/book/src/reference/glossary.md
Quick addition of WorkloadCluster definition.
=> Add Workload Cluster definition

cmd/clusterctl/pkg/client/alias.go, cmd/clusterctl/pkg/client/client.go, cmd/clusterctl/pkg/client/cluster/client.go, cmd/clusterctl/pkg/client/cluster/components.go, cmd/clusterctl/pkg/client/cluster/installer.go, cmd/clusterctl/pkg/client/cluster/inventory.go, cmd/clusterctl/pkg/client/cluster/proxy.go, cmd/clusterctl/pkg/client/config/client.go, cmd/clusterctl/pkg/client/repository/components.go, cmd/clusterctl/pkg/client/repository/repository_github.go
This PR applies some minor improvements or nits to the clusterctl codebase, to align more with the rest of the repository.
=> :running: Minor improvements to clusterctl codebase

controllers/machineset_controller.go
In machineset_controller, there are several places where we call context.TODO().
The call can be replaced with passing Context as parameter to the corresponding func.
Fixes #
=> 🏃‍♂️Pass Context parameter instead of calling context.TODO()

Tiltfile, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, scripts/ci-capd-e2e.sh, test/framework/control_plane.go, test/infrastructure/docker/Makefile, test/infrastructure/docker/config/default/manager_auth_proxy_patch.yaml, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/e2e/docker_test.go, test/infrastructure/docker/main.go
This PR will actually build images to test instead of simply testing master.
Related to #1732 
Fixes #2036 
Fixes #2034
Fixes #2021
Fixes #1921
/cc @ncdc
=> :bug: Fix race condition and improve capd-e2e to build off actual changes

.golangci.yml, main.go
=> 🐛 Import (and enable) pprof

docs/book/src/user/concepts.md
=> docs(*): typo regulat -> regular

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
=> 🏃Refactor kubeadm control plane reconcile funcs

docs/book/src/architecture/developer-guide.md
Removes broken registry link. 
Fixes #
=> 📖Remove link to broken REGISTRY env var doc

cmd/clusterctl/hack/local-overrides.py, cmd/clusterctl/pkg/client/config/providers_client.go
Small fixes to get clusterctl to work with the docker provider
/assing @vincepri
=> 🐛clusterctl: fix docker provider

docs/book/src/tasks/installation.md
Adds the cert-manager prerequisite to the quick start. 
Fixes #1561
=> 📖 Adding cert-manager prerequisite to the quick start

README.md
Otherwise I can not find the meeting notes.
=> 📖 Update README to point to 2020 meeting notes.

docs/book/src/tasks/installation.md
=> 📖 Add image builder section

controllers/cluster_controller.go
I was seeing intermittent delete failures relating to the control plane. This PR aims to improve logging around deleting clusters as well as fixes a bug with the control plane delete logic. This PR will improve the experience for devs who don't know why a cluster isn't deleting by providing them with a list of descendant names.
Here are some examples of this logging:
```
I0123 18:26:47.891556       1 cluster_controller.go:271] controllers/Cluster "msg"="Cluster still has descendants - need to requeue" "cluster"="test-0" "namespace"="default" "descendants"="Control plane machines: test-0-kvn6l,test-0-wxw6s,test-0-n78fd;Machine deployments: test-0-md;Machine sets: test-0-md-5c6f99b8bf;Worker machines: test-0-md-5c6f99b8bf-hrlvb" "indirect …
```
=> :bug: Fix delete control plane bug

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Cherry pick of https://github.com/kubernetes-sigs/cluster-api/pull/2149 to update book Azure docs.
Fixes #
=> :book: Update Azure quickstart docs for new k8s version

test/infrastructure/docker/config/default/kustomization.yaml
I forgot to update this provider label based on the discussion we had. My bad.
N/A
=> 🏃Fix provider label for docker

controllers/machine_controller_noderef.go
=> :bug: MachineReconciler.getNodeReference use continue token

CONTRIBUTING.md, docs/book/src/developer/guide.md, docs/book/src/developer/providers/bootstrap.md, docs/book/src/reference/ports.md
Add an initial port allocation documentation 
/cc @vincepri
=>  📖 Add port allocation documentation

docs/book/src/user/quick-start.md
one step is missing for OpenStack ,so user might miss this
and lead to potential issue.
Fixes #
=> fix quick start for Openstack

docs/book/src/clusterctl/developers.md
Fixes link and property name
Minor fixes in clusterctl developers doc.
n/a
=> 📖 Fix clusterctl developers doc

docs/book/src/tasks/installation.md
=>  📖 Update docs to support KIND >= v0.6.x

controllers/cluster_controller_phases.go
code is updated but comments not updated yet
Fixes #
=> nit: fix an incorrect comments

test/infrastructure/docker/e2e/docker_test.go
I need to figure out why prow is not returning the same value as my local set up:
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capd%20e2e%20tests
This makes debugging a little bit easier and fixes a nil pointer error that shouldn't be there, but does seem to occur.
=> 🏃 Make the failure domain test easier to debug

docs/book/src/SUMMARY.md
=> :book: Add reference/ports link to the summary

test/infrastructure/docker/docker/machine.go
This issue fixes a common flake in the capd-e2e tests. Please see the issue for more detail.
Fixes #2223
=> 🐛 Fix flake in capd

controllers/machine_controller_phases.go
=> :bug: Enqueue request for the right owner in machine controller

docs/book/src/user/quick-start.md
Documents how to determine if control plane is up.
Fixes #2074
=> 📖Document how to verify control-plane is running

cmd/clusterctl/api/v1alpha3/metadata_type.go, cmd/clusterctl/api/v1alpha3/provider_type.go, cmd/clusterctl/pkg/client/cluster/client.go, cmd/clusterctl/pkg/client/cluster/inventory.go, cmd/clusterctl/pkg/client/cluster/inventory_managementgroup.go, cmd/clusterctl/pkg/client/cluster/inventory_managementgroup_test.go, cmd/clusterctl/pkg/client/cluster/upgrader.go, cmd/clusterctl/pkg/client/cluster/upgrader_info.go, cmd/clusterctl/pkg/client/cluster/upgrader_info_test.go, cmd/clusterctl/pkg/client/cluster/upgrader_test.go, cmd/clusterctl/pkg/internal/test/fake_repository.go, docs/book/src/reference/glossary.md
This PR implements the upgrade plan logic
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, rif #1729
/assign @ncdc
=> ✨clusterctl: add upgrader with the upgrade plan logic

controllers/machinehealthcheck_controller_test.go
Attempt to fix flaking tests as shown in  https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-test/1224722017673023489 https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-test/1224553147750420485
Use randomised test namespaces for each test to avoid conflicts + create/delete namespace for each test
Also sets longer timeout on `Eventually` calls to wait for cache to sync
Fixes #2257
=>  🐛 Fix flaking tests in MachineHealthCheck suite

controlplane/kubeadm/internal/etcd/etcd.go
Addresses feedback left on #2237 
/assign @chuckha @randomvariable
=> :running: Fixes to etcd client

api/v1alpha2/conversion_test.go
Follow-up from #2259 
/assign @ncdc
=> :running: Add other types to FuzzyConversion

api/v1alpha2/conversion.go, api/v1alpha3/machine_types.go
=>  🐛 Update ExcludeNodeDrainingAnnotation

api/v1alpha2/common_types.go, api/v1alpha2/machinedeployment_types.go, api/v1alpha3/common_types.go, api/v1alpha3/machinedeployment_types.go
Signed-off-by: Colin Lodter <clodter@vmware.com>
Fixes #2181
=> :sparkles: Remove protobuf tags

docs/book/src/SUMMARY.md
Add developer/providers/v1alpha2-to-v1alpha3.md to SUMMARY.md
Fixes #2264
=> 📖 add developer/providers/v1alpha2-to-v1alpha3.md to SUMMARY.md

Makefile, scripts/ci-integration.sh
=>  🐛 Remove lint-full dependency

util/conversion/conversion.go
Adds a parameter in FuzzTestFunc allowing to pass custom fuzzing functions if needed. This allows providers to define specific fuzzing behaviours when fuzzing their conversions.
=> ✨ Expand fuzzing framework to allow custom functions

docs/book/src/developer/guide.md
- Add kubebuilder install link to prerequisites in developer's guide
Fixes #2317
=> Add kubebuilder install link to prerequisites in developer's guide

controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go
This PR adds control plane health checks as defined for the kubeadm control plane controller.
Fixes #2243 
/assign @detiber @dlipovetsky @randomvariable
=> ✨ Adds control plane healthcheck for workload clusters

docs/book/src/user/quick-start.md
there is no links to where to do configuration for openstack
,only the template provided. So add a link to provide additional
information.
Fixes #
=> Add how to configure openstack

config/rbac/role.yaml, controllers/cluster_controller.go, controllers/machine_controller.go, main.go
This PR fixes some issue with CRD not being added to the scheme and some RBAC permissions to list the CRDs
Fixes #2346
=> 🐛 Add scheme registration for CustomResourceDefinition and List

test/framework/control_plane.go
[e2e framework] ensure MachinePools are deleted
Fixes #2310
=> 🐛 [e2e framework] ensure MachinePools are deleted

bootstrap/kubeadm/config/crd/kustomization.yaml, bootstrap/kubeadm/config/crd/patches/cainjection_in_kubeadmconfigtemplates.yaml
Adds CA injection for KubeadmConfigTemplate
=> 🐛add ca injection for kubeadmconfigtemplate

hack/tools/mdbook/releaselink/releaselink.go
Fixes an issue where pre-releases would show up in the book.
/assign @ncdc
=> :bug: Fix handling pre-releases in mdbook

cmd/clusterctl/pkg/client/config/providers_client.go, cmd/clusterctl/pkg/client/config_test.go, cmd/clusterctl/pkg/client/repository/metadata_client.go, docs/book/src/clusterctl/overview.md, docs/book/src/clusterctl/provider-contract.md
This PR adds the baremetal infrastructure provider to the clusterctl pre-defined list of providers.
Fixes #2356
=> 🏃Add baremetal provider in clusterctl pre-defined providers list

docs/book/src/developer/tilt.md
=> :book: update tilt docs "Azure kustomize_substitutions Tab"

features/features.go, go.mod, go.sum, main.go, util/featuregate/featuregate.go
Adding feature-gate flag for experimental features (and migrating from go flags to pflags)
**Which issue(s) this PR fixes** *
Fixes #2328
=> ✨Adding feature-gate flag for experimental features (and migrating from go flags to pflags)

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/cluster.go, controlplane/kubeadm/internal/cluster_test.go, controlplane/kubeadm/internal/etcd/util/set.go, controlplane/kubeadm/internal/failure_domain.go, controlplane/kubeadm/internal/failure_domain_test.go, controlplane/kubeadm/internal/machine_filters.go, controlplane/kubeadm/internal/machine_filters_test.go
Does some additional cleanup to the MachineFilters and their usage that were introduced for the KubeadmControlPlane
Related to #2242
=> :running: Cleanup KubeadmControlPlane machine filters

hack/tools/mdbook/releaselink/releaselink.go
Fix handling pre-releases in mdbook
cherry-pick from #2362
Ref #2364
=> 🐛 Fix handling pre-releases in mdbook

README.md
Updates our community blurb based on feedback received.
Backports #2399
=> :book: Update our community blurb

Tiltfile
Watches files inside the internal package for live reload.
=> 🏃tilt: watch internal KCP package

util/util.go
This PR removes a lot of unuse, outdated, and untested functions un `util/util.go`.
=> :warning: Remove unused util functions

cmd/clusterctl/api/v1alpha3/labels.go, cmd/clusterctl/api/v1alpha3/metadata_type.go, cmd/clusterctl/api/v1alpha3/provider_type.go, cmd/clusterctl/cmd/config.go, cmd/clusterctl/cmd/config_cluster.go, cmd/clusterctl/cmd/config_provider.go, cmd/clusterctl/cmd/config_repositories.go, cmd/clusterctl/cmd/delete.go, cmd/clusterctl/cmd/init.go, cmd/clusterctl/cmd/move.go, cmd/clusterctl/cmd/root.go, cmd/clusterctl/cmd/upgrade.go, cmd/clusterctl/cmd/upgrade_apply.go, cmd/clusterctl/cmd/upgrade_plan.go, cmd/clusterctl/cmd/version.go, cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml, cmd/clusterctl/pkg/client/client.go, cmd/clusterctl/pkg/client/config.go, cmd/clusterctl/pkg/client/delete.go, cmd/clusterctl/pkg/client/init.go, cmd/clusterctl/pkg/client/upgrade.go, docs/book/src/clusterctl/overview.md
=> 🏃Minor cleanups to clusterctl commands

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/util/configowner.go, bootstrap/util/configowner_test.go, go.sum
=> 🏃Cleanup and add tests for bootstrap util.GetConfigOwner

controllers/machine_controller.go, controllers/machine_controller_test.go
- as part of the `clusterctl move` command, the cluster is created in the target cluster paused and its reconciliation is not triggered immediately, this watcher will allow the reconcile to happen as soon as the paused status is changed.
Fixes #2283
=> 🐛 add a cluster watcher in the machine controller to reconcile after a cluster is unpaused

controllers/machine_controller.go, controllers/machine_controller_test.go
- address some comments from PR #2432 for cleaner code
=> 🏃cleanup for machine_controller watcher of a cluster (followup to PR 2432)

cmd/clusterctl/cmd/root.go, cmd/clusterctl/testdata/create-no-args.golden, cmd/clusterctl/testdata/delete-cluster-no-args.golden, cmd/clusterctl/testdata/delete-no-args.golden, cmd/clusterctl/testdata/no-args.golden, cmd/clusterctl/testdata/validate-no-args.golden, docs/book/src/tooling/clusterctl.md
=> 📖 Remove deprecation message clusterctl

controlplane/kubeadm/internal/cluster.go
Try all nodes except one being removed when removing etcd member
Fixes #2393
=> ✨ KubeadmControlPlane - Try all nodes except one being removed when removing etcd member

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
/assign @chuckha 
/milestone v0.3.0-rc.3
=> :bug: Fix misleading log when creating bootstrap data secret

scripts/fetch_ext_bins.sh
Improves time taken to run tests locally.
/milestone v0.3.0-rc.3
=> :running: fetch_ext_bins now checks existing version before downloading

Dockerfile, Makefile, Tiltfile, cmd/example-provider/Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev
=> :running: Bump Go to 1.13.8

docs/book/src/developer/architecture/controllers/control-plane.md
Fix a bad link to the KCP diagram.
Fixes #
=> :book: Fix KCP diagram link

docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
This PR documents matchPolicy changes required for all providers.
Fixes #2536
=> 📖Add a section about matchPolicy to "v1alpha2 to v1apha3" doc

test/infrastructure/docker/docker/machine.go
Identifying flakes and documenting them here:
https://docs.google.com/document/d/1bocdzNH_uYXOhNWa1Rd4ip-GkUcqYxubbEJ8NqPJ1B8/edit#
Looking for any ways to improve flakiness. May be a futile task but if we want to keep them around as automatically running they should be more consistent
Fixes #
=> :bug: Fix CAPD flakes

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Fixes a confusing log line
Fixes #2572
=> 🐛 Update misleading logs

controllers/machinehealthcheck_controller_test.go
Adds more e2e style tests to the Machine Health Checking implementation.
Wanted to make sure these aren't flaky so ran them with `ginkgo -v -randomizeAllSpecs -untilItFails ./controllers/...` and it didn't fail on my machine in 10 attempts so I think they're good
Part of #1990
=> ✨ Add e2e style tests for Machine HealthChecking

bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
standardize gomega imports for `bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go` test
/cc @vincepri 
please let me know if this is the correct approach, if yes I will do for other test files as well.
=> 🏃 tests: standardize gomega imports - Follow up

docs/book/src/developer/tilt.md
**What this PR does / why we need it**:  Using older tilt versions results in error `Error: docker_build: for parameter "entrypoint": got list, want string`.
Fixes #
=> :book: Update minimum tilt version

docs/book/src/developer/guide.md, docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
=> Remove links to installation.md/html

docs/proposals/20191017-kubeadm-based-control-plane.md
This PR brings the kubeadm control plane caep closer to reality after implementation details have been updated and hashed out.
/assign @detiber @dlipovetsky @randomvariable
=> 🏃 Update KCP CAEP to reflect implementation changes

cmd/clusterctl/client/repository/client_test.go, cmd/clusterctl/client/repository/components_client_test.go, cmd/clusterctl/client/repository/components_test.go, cmd/clusterctl/client/repository/metadata_client_test.go, cmd/clusterctl/client/repository/repository_github_test.go, cmd/clusterctl/client/repository/repository_local_test.go, cmd/clusterctl/client/repository/template_client_test.go, cmd/clusterctl/client/repository/template_test.go
Follow up of comments in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/2643
/cc @fabianofranz @detiber 
/kind cleanup
=> 🏃 cmd-clusterctl-client/tests: update gomega expect

docs/book/src/developer/testing.md
This PR aims to update the testing documentation as it was woefully under documented.
/assign @sedefsavas 
/cc @sethp-nr 
Fixes #2669
=> 📖 Update testing document

docs/book/src/developer/tilt.md
**What this PR does / why we need it**: the Azure instructions with Tilt were added in an earlier PR but the tab wasn't added to the list of tabs.
Fixes #
=> :book: show Azure tab in Tilt docs

docs/book/src/user/troubleshooting.md
Added an example of a "one liner" to label workers
Sample "one liner" to label nodes to get people "up and running" faster
=> :book: Update troubleshooting.md

controlplane/kubeadm/internal/workload_cluster.go
Currently `ForwardEtcdLeadership` may be trying to connect to an already-removed member. This tries to get around that issue by talking to the leadership candidate instead.
This produced a lot of "failed to create etcd client" messages that, with some [trickery](https://github.com/kubernetes-sigs/cluster-api/blob/5eec3b04c37d6ff749e1da536d3352f2b18e5300/go.mod#L50), turned out to be caused by an `EOF`:
> E0317 22:29:28.112358       8 kubeadm_control_plane_controller.go:544] controllers/KubeadmControlPlane "msg"="failed to move leadership to another machine" "error"="failed to create etcd Client: unable to create etcd client: context deadline exceeded: connection error: desc = \"transport: authentication handshake failed: EOF\"" "cluster"="test" …
=> :bug: forward leadership by talking to new leader

docs/book/src/user/quick-start.md
This PR makes it less likely we will get 404s in our book.
Related to  #2703
=> 📖 Fix the links in the quickstart

docs/book/src/reference/providers.md
**What this PR does / why we need it**: Fix a typo in the providers doc and update providers in bold to v1alpha3.
Fixes #
=> 📖 Update providers list to supported v1alpha3 providers

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Fixes bug raised in issue below :)
Fixes #2723
=> 🐛 Allows dns image tag to be unset

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Remove the `$` characters in the bash commands to facilitate copy/pasting and update the Azure variables to match the docs in the capz v0.4.0 release.
Fixes #
=> 📖 update quickstart Azure variables

controllers/external/util.go
This PR is needed to separate concerns of structs in the KubeadmControlPlane reconciler.
This function that is copied in this PR does too much by requiring a client and actually creating the objects. There is already something that is responsible for communicating with the API server so this function does not need to do that.
This is the code that is being modified: https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/external/util.go#L17
Related to #2702
=> 🏃 Add a modified util function

docs/book/src/user/quick-start.md
This PR adds documentation to the quickstart for AWS cluster initialization. It describes the step of creating a cloud formation stack for IAM policies. 
Fixes #2721
=>  📖Add IAM pre-requisite notes to AWS quickstart

controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go, controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go, controlplane/kubeadm/internal/control_plane.go
This is just piping the object through and replacing a few pieces of code with equivalent methods in the ControlPlane object.
function signatures will clean up significantly as this refactor continues, I just don't want to give anyone a 600 line PR all at once.
Annotations will be removed as this refactor continues.
Related to #2702
=> 🏃 Start using control plane object just a little bit

controllers/machine_controller.go, controllers/machine_controller_test.go
This PR adds some logic to disable removing nodes from kuberentes and drain behavior when deleting the whole Cluster.
/assign @frapposelli @ncdc 
/milestone v0.3.3
=> :bug: Avoid draining nodes when deleting a Cluster

docs/book/src/user/quick-start.md
Fix some shell syntax errors.
Fixes #2748
=> 📖  small fix for quick-start

controlplane/kubeadm/internal/cluster.go
This PR reorder an error check in KCP.
Fixes #2754
=> 🐛KCP: minor fix for err check

docs/book/src/reference/glossary.md
Add an entry explaining the acronym "CAEP"
=> 📖 Add CAEP to glossary

cmd/clusterctl/internal/util/yaml.go, cmd/clusterctl/internal/util/yaml_test.go, util/util.go, util/util_test.go
Improves yaml unmarshal error messaging to focus on the document within a yaml file.
Fixes #2495
=> ✨Improve error message for yaml unmarshal

cmd/clusterctl/client/repository/repository_github_test.go
In the `cmd/clusterctl/client/repository/repository_github_test.go` file was some TODO to implement missing tests, this PR adds those missing tests
Fixes #
=> 🏃tests: add missing tests in repository github

test/infrastructure/docker/e2e/docker_upgrade_test.go
- Adds tests for CoreDNS upgrade
Fixes #2609
=> 🏃 Adds coredns upgrade validations to upgrade e2e tests

controlplane/kubeadm/internal/control_plane_test.go, controlplane/kubeadm/internal/etcd/etcd_test.go, controlplane/kubeadm/internal/etcd/fake/client.go
backfill unit tests for KCP internal area
**Which issue(s) this PR fixes** *
Ref #2753
=> 🏃Add more unit tests to the kubeadmControlPlane area

controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go
This PR backfills some missing tests.
Ref https://github.com/kubernetes-sigs/cluster-api/issues/2779
=> 🏃[KCP] Add unit tests for kubeadm_config_map

Makefile, bootstrap/kubeadm/main.go, controlplane/kubeadm/main.go, main.go
Print controller version in the logs 
Fixes #2801
=> 🏃Add controller version in logs

OWNERS, OWNERS_ALIASES
This project is no longer my focus
=> 🏃 Update OWNERS

test/framework/management_cluster.go
fixes https://github.com/kubernetes-sigs/cluster-api/pull/2820/files/bbf11a9c2620eed1027c0ce56ed8bc27efc68cab#r403148411
/area testing
=> 🏃e2e: fix WaitForDeploymentsAvailable

controlplane/kubeadm/controllers/scale.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/controllers/upgrade_test.go, controlplane/kubeadm/internal/control_plane.go, controlplane/kubeadm/internal/failure_domain.go, controlplane/kubeadm/internal/failure_domain_test.go
This PR fixes the logic around selecting a machine to delete during upgrade.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2831
=> 🐛[KCP] Fix for selecting failure domain logic during upgrade

cmd/clusterctl/client/alias.go
Fixes godoc comment
Fixes #2855
=> 📖 Fix client.UpgradePlan godoc comment

docs/book/src/clusterctl/commands/init.md
Minor fix for an incomplete sentence in the book.
=> 📖 Fix incomplete sentence in docs

test/framework/clusterctl/client.go, test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go
This PR introduces small improvements to the recently added clusterctl e2e framework:
- get templates now support flavors and target namespace
- e2e config now consider the config folder as a base for resolving  relative paths (and so we can now drop the cryptic BasePath parameter)
xref #2753
xref #2637
xref #2636
=> 🏃[e2e]: clusterctl improvements

docs/book/src/user/quick-start.md
Fixes some small grammatical errors in the quick start document.
Fixes #
=> 📖 fix some grammar in the quickstart

OWNERS_ALIASES
Add myself to the CAPI reviewers list
=> 🏃 Add benmoss to cluster-api-reviewers

docs/book/src/introduction.md
As title says
/milestone v0.3.4
=> 📖 Point legacy docs to release-0.2 branch

docs/book/src/clusterctl/developers.md, docs/book/src/user/quick-start.md
Improves the accuracy and completeness of the docs for developers using clusterctl and the docker provider.
=> :book: Fixes for clusterctl developer doc, mostly related to docker provider

controllers/mdutil/util.go
Forward port of #3010 
/milestone v0.3.6
/assign @ncdc
=> 🐛Exclude conversion-data annotation when MD reconciles

cmd/clusterctl/cmd/root.go
remove `// TODO: print error stack if log v>0`
print that stack trace when have any error and `-v`or `CLUSTERCTL_LOG_LEVEL` is set
example:
```
➜ ./bin/clusterctl config cluster my -v5
Error: failed to identify the default infrastructure provider. Please specify an infrastructure provider: unsupported management cluster server version: v1.14.6 - minimum required version is v1.16.0
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).getTemplateFromRepository
/Users/cpanato/go/src/github.com/kubernetes-sigs/cluster-api/cmd/clusterctl/client/config.go:209
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).GetClusterTemplate
/Users/cpanato/go/src/github.com/kubernetes-sigs/cluster-api/cmd/clusterctl/client/config.go:189 …
```
=>  ✨ clusterctl: print stack trace if verbosity is >= 5

docs/book/src/developer/architecture/controllers/machine.md
improve providerID docs
https://github.com/kubernetes-sigs/cluster-api/issues/3007
=> 📖 clarify providerID docs

Tiltfile
This PR adds watches on exp and feature packages to tiltfile.
=>  🏃Add exp and feature directories to tiltfile

test/framework/machine_helpers.go
The `WaitForMachineStatusCheck` was not polling for changes on the machine. This change fixes that. It also moves the intervals out of the input and into the function to align with other helpers. 
cc @fabriziopandini @sedefsavas
=> 🐛 [e2e] Fixes WaitForMachineStatusCheck to poll for updates

cmd/clusterctl/client/config/provider.go, cmd/clusterctl/cmd/config_repositories.go, cmd/clusterctl/cmd/config_repositories_test.go
=> ✨ Add support for -o yaml in `clusterctl config repositories` command

docs/book/src/user/concepts.md
Simplifies and hopefully clarifies some of the content in the Concepts doc.
I had to make changes while trying to grok this content, so I apologize in advance if any of this represents my misunderstanding or is unhelpful.
Fixes #
=> 📖 Update concepts doc

controllers/external/util_test.go
=> 🏃 Test external.Clone annotations in template

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, VERSIONING.md, hack/tools/release/notes.go
Open to suggestions if folks don't like 🌱
=> 🌱 Opt for a more inclusive "other" category for our emoji

test/framework/pod_helpers.go
=> 🐛 Updated "Upgrade" test so that it does not report false-negatives while waiting for conditions

util/util.go, util/util_test.go
OwnerMachine lookup fix while upgrading
Fixes #3143
=> 🌱OwnerMachine lookup fix while upgrade

docs/book/src/tasks/healthcheck.md
This PR fixes typo for "timeout".
Fixes #
=> 📖 Fix typo for "timeout"

test/helpers/client.go
as per https://github.com/kubernetes-sigs/cluster-api/pull/3136#discussion_r436909726, this PR makes sure test/helpers.NewFakeClientWithScheme does not alter input objects.
=> 🌱 fix test/helpers.NewFakeClientWithScheme

controllers/suite_test.go, test/helpers/envtest.go
=> 🐛 Envtest should initialize controller runtime logger

bootstrap/util/configowner.go
The variable **allowdGKs** should initialize out of for range, because it will never been modified in the loop, and doesn't have ref with special loop var.
Fixes #
=> feat(bootstrap): initialize variable out of for range

cloudbuild.yaml
This PR updates the gcloud build images to the latest available
=> 🌱 update gcloud build image

Dockerfile, cmd/example-provider/Dockerfile, docs/Dockerfile, hack/boilerplate/boilerplate.Dockerfile.txt, test/infrastructure/docker/Dockerfile
As per https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md, this PR updates the docker experimental annotation
=> 🌱 fix-docker-experimental-annotation

cloudbuild.yaml
=> :seedling: Update gcloud image for cloudbuild

Makefile, controllers/suite_test.go
=> 🌱 Increase test timeout

Makefile
=> :seedling: Remove build --pull argument

controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_status_matcher.go
Fixes failures caused by #3186 
=> 🐛 Fixes MHC test failures

controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machine_controller_test.go, controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/controllers/controller_test.go, exp/controllers/machinepool_controller.go, exp/controllers/machinepool_controller_test.go, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go
Change controllers to add finalizers at the first reconciliation
Fixes #3205
/kind bug
/priority important-long-term
=> 🐛 change controllers to add finalizers at the first reconciliation

docs/book/src/user/quick-start.md
📖 
Bumped calico version to 3.15
=> Bumped calico version to 3.15

bootstrap/kubeadm/main.go, controllers/machinehealthcheck_targets.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_etcd_test.go, controlplane/kubeadm/internal/workload_cluster_test.go, controlplane/kubeadm/main.go, docs/book/src/user/concepts.md, docs/book/src/user/quick-start.md, main.go, test/framework/cluster_proxy.go
Remove use of `master` word from our codebase
Fixes #3281
=> 🌱 Remove use of 'master' word from our codebase

config/ci/manager/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/manager/manager_auth_proxy_patch.yaml, config/webhook/manager_webhook_patch.yaml, test/e2e/config/docker-ci.yaml, test/e2e/config/docker-dev.yaml
Just a typo fix I found when I hit #3339.
Unfortunately this is in the YAML that was just shipped in 0.3.7
=> 🌱 Fix typo in components flags feature gates (ClusterResourceSet)

OWNERS_ALIASES
@CecileRobertMichon has been very active in both Cluster API repository, and running meetings.
=> 🌱 Promote CecileRobertMichon as maintainer

controlplane/kubeadm/internal/workload_cluster_coredns_test.go
This PR backfills tests for UpdateCoreDNS for KCP.
Ref https://github.com/kubernetes-sigs/cluster-api/issues/3309
=> 🌱 Add test for UpdateCoreDNS

controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
This PR adds tests to specific machine filters
Ref https://github.com/kubernetes-sigs/cluster-api/issues/3309
=> 🌱 Add machine filters tests

CONTRIBUTING.md
As discussed in https://github.com/kubernetes-sigs/cluster-api/issues/3315#issuecomment-658668254, the documentation does not mention about the label, hence creating some confusion on what issues to pick. 
None
=> 📖  Add details about lifecycle/active in the documentation

docs/proposals/YYYYMMDD-template.md
Adds a security model section as well as an optional "requirements" section, which was used in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/proposal/20200506-single-controller-multitenancy.md
Fixes #3062
=> :book: Update CAEP template with requirements and security model

util/util.go, util/util_test.go
**What this PR does / why we need it**: Only look at Group and Kind for GetOwnerCluster
Fixes #
=> 🌱 Only look at Group and Kind for GetOwnerCluster

util/conditions/patch.go
Add some extra logs when a conflict appears, which can be useful for debugging.
=> :seedling: Add cmp.Diff to condition patch conflicts

docs/book/src/introduction.md
This PR updates content on the home page of the cluster api docs site. The goal is to add more context around what cluster api is and why it was built to help new users understand the project better. Additionally, this PR includes some minor adjustments to the home page layout.
**Questions**:
* I have some other suggestions for the Community section on this page, which its included from thee README.md:Community file. Should I add those to this PR?
=> 📖  Update site home page

exp/util/util.go
Adds some helpers that all MachinePool providers will need. 
Fixes #3391
=> 🌱 Add exp/util MachinePool helpers

exp/addons/controllers/clusterresourceset_controller.go
This is a short term fix until we have #3400 or some other similar solution.
=> 🌱 CRS should return errors when trying to apply custom resources

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Escape double quotes in AZURE_JSON_B64 variable instructions for Azure quick start (not escaping the quotes results in the quotes not being present in the var).
/cc @ncdc 
Fixes #
=> 📖  Escape quotes in AZURE_JSON_B64

docs/book/src/user/quick-start.md
- add note about cluster name validation for azure
Fixes #
/hold 
for https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/828
=> 📖 add note about cluster name validation for azure

README.md
**What this PR does / why we need it**: Remove meetings that are no longer happening and add welcome message in community section of README.
Fixed #2391
=>  📖 Update community section of readme

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Removes another use of RequeueAfterError from our codebase
Related to #3370
/assign @ncdc
=> 🌱 Remove RequeueAfterError from CABPK reconcile discovery

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/802 removed the need for the user to define the azure.json manually 🎉 
/hold for capz release v0.4.7
Fixes #
=> 📖  Remove azure.json variable from quick start

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Co-Authored-By: Ace Eldeib <alexeldeib@gmail.com>
**What this PR does / why we need it**: Currently, KubeadmConfigs that belong to a MachinePool do not get a reconciliation request when Cluster Infrastructure becomes ready because the `ClusterToKubeadmConfigs` func only looks for `Machines`. This PR also gets `MachinePool` kubeadmConfigs so the watch on cluster will requeue the KubeadmConfig controller when the cluster is ready.
/cc @alexeldeib 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/656
=> 🐛 Fix ClusterToKubeadmConfigs to include MachinePools

api/v1alpha3/condition_consts.go, controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_targets.go
This PR fixes the name of some conditions const for MHC by adding the `Reason` prefix where missing
=> 🌱 Fix MHC conditions const

cmd/clusterctl/client/repository/repository_github.go, cmd/clusterctl/client/repository/repository_github_test.go
This PR will address some flaky test behavior we discovered while adding
tests to the github repository section of clusterctl. The global cache
variables weren't being reset between tests.
We also need to support injecting the test github client at
`newGithubRepository` call time, so this also adds that functionality as
well. The need for this went unspotted because of the caches mentioned above.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
=> 🐛 fix github repository testing

cmd/clusterctl/client/cluster/proxy.go
This PR adds a retry logic to list out the resources via discovery API. This was done because we would see intermittent errors like `
unable to retrieve the complete list of server APIs: bootstrap.cluster.x-k8s.io/v1alpha2: the server could not find the requested resource, bootstrap.cluster.x-k8s.io/v1alpha3: the server could not find the requested resource
`
when doing `clusterctl delete --all --include-crds --include-namespace`. 
See issue for details.
Fixes #2483
=> 🐛  Retry getting list resources via discovery API

docs/proposals/20200220-cluster-resource-set.md
This PR update CRS CAEP content according to the latest implementation.
Fixes #3398
=> 📖 Update ClusterResourceSet CAEP

docs/book/src/reference/providers.md
Update the misleading sentences in providers documentation. And unmark providers that are abiding by the v1alpha3 contract in bold since the list will eventually go out of date and become misleading. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: #3492 
Fixes #3492
=> 📖  Update the misleading sentences in providers documentation.

test/infrastructure/docker/docker/machine.go
Improves CAPD error logging in case of bootstrap failures
=> 🌱 improve CAPD error logging

test/e2e/Makefile
Adding quotes to accept special characters in the e2e Ginkgo focus.
/assign @vincepri @fabriziopandini
=> 🌱[e2e] Add quotes to GINKGO_FOCUS

controllers/remote/cluster_cache.go, controllers/remote/cluster_cache_healthcheck_test.go
Fix a bug in the cluster cache tracker healthcheck code that was failing
to decode the response from the apiserver (it was trying to deserialize
it as a runtime object, and the / repsonse is missing TypeMeta). Switch
to using a pure HTTP client.
Part of a series of fixes for #3609 
Fixes #3610 
/hold
pending additional verifications
=> 🐛 Fix cluster cache tracker healthchecks

Tiltfile
Fix regression in Tiltfile introduced by https://github.com/kubernetes-sigs/cluster-api/pull/3604
=> 🐛 Fix regression in Tiltfile

Dockerfile, Makefile, Tiltfile, cmd/example-provider/Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev, test/infrastructure/docker/Makefile
=> :seedling: Update Go 1.13.15

docs/book/src/user/quick-start.md
Adds a clean up section to CAPI Quick Start guide
Fixes #3523
=> :book: Add CAPI Clean Up section to Quick Start

docs/proposals/20191017-kubeadm-based-control-plane.md
This PR updates the KCP proposal document with latest changes, so then it will be possible to extend this proposal with the considerations for implementing automatic remediating of unhealthy control plane machines
=> 📖 update KCP proposal with latest changes

test/e2e/kcp_adoption.go, test/e2e/self_hosted.go, test/framework/cluster_helpers.go, test/framework/control_plane.go, test/framework/controlplane_helpers.go, test/framework/daemonset_helpers.go, test/framework/deployment_helpers.go, test/framework/deprecated.go, test/framework/machine_helpers.go, test/framework/machinedeployment_helpers.go, test/framework/machines.go, test/framework/pod_helpers.go, test/infrastructure/docker/docker/machine.go
This PR fixes a couple of E2E logs with wrong capitalization & other small improvements
=> 🌱 Fix some typos and grammar in e2e logs

docs/book/install-and-build.sh
This PR updates mdbook, which is currently using a really old version.
Fixes #3658 
/assign @fabriziopandini @ncdc
=> :seedling: Update mdbook to v0.4.3

cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph.go, cmd/clusterctl/client/cluster/objectgraph_test.go, cmd/clusterctl/internal/test/fake_objects.go
=> Add force move support for secret

cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/move.go, cmd/clusterctl/client/move_test.go, cmd/clusterctl/cmd/move.go, docs/book/src/clusterctl/commands/move.md
Fixes #3574 
```release-note
ObjectMover interface function has been updated to `Move(namespace string, toCluster Client, dryRun bool) error`
from `Move(namespace string, toCluster Client) error`
```
=> Support mover dry run

docs/book/src/clusterctl/provider-contract.md
add openstack into provider contact list
Fixes #
=> Add CAPO into contract list

docs/book/src/developer/e2e.md, docs/book/src/developer/testing.md
external link test reported error about it ...
Fixes #
=> Fix e2e link

test/framework/docker_logcollector.go
Fixes a regression in theE2E log collector error introduced by https://github.com/kubernetes-sigs/cluster-api/pull/3600 😅 
`Failed to get logs for machine quick-start-6fnlyv-md-0-7b8b4fc4d5-hl89q, cluster quick-start-e7nyih/quick-start-6fnlyv: [command "docker exec --privileged quick-start-6fnlyv-md-0-7b8b4fc4d5-hl89q journalctl --no-pager --output=short-precise -u kubelet.service" failed with error: exit status 1, command "docker exec --privileged quick-start-6fnlyv-md-0-7b8b4fc4d5-hl89q journalctl --no-pager --output=short-precise -u containerd.service" failed with error: exit status 1, command "docker exec --privileged quick-start-6fnlyv-md-0-7b8b4fc4d5-hl89q journalctl --no-pager --output=short-precise" failed with error: exit status 1, command "docker exec --privileged …
=> :seedling: Fix E2E log collector regression by aligning to the container naming rules used in CAPD

Makefile
Fixes an issue where the development manifests weren't being properly generated, because the tree would be dirty by the time we get to call `make release` under capd.
=> 🐛 Makefile release target should properly clean the git tree

test/framework/bootstrap/kind_provider.go
This PR makes the ee framework to allow choosing the node image for the bootstrap cluster.
Also, the default image is now v1.19.1, no matter the version of Kind we are using.
=> 🌱 e2e framework allows choosing the node image for the bootstrap cluster

test/infrastructure/docker/controllers/dockermachine_controller.go
This PR is to remove machine deletion feature enabled for CAPD.
This was previously added to handle flakes, but it can mask errors.
Fixes #3581
=> Remove CAPD's machine deletion

bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
Token should be secret and not logged
Fixes #3771
=> 🐛 CABPK should not log the token upon renewal

docs/book/src/user/quick-start.md
=> 📖 Fix a typo in quick-start

bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go, cmd/clusterctl/client/cluster/inventory_managementgroup_test.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph_test.go, cmd/clusterctl/internal/test/fake_objects.go, controllers/cluster_controller_test.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
#3735 marked with Skip some test because they started to fail and further investigation were required.
This PR fixes the skipped tests
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3766
=> 🌱 Rework skipped test

test/infrastructure/docker/README.md
Makefile doesn't have test-e2e, only test cmd
Fixes #
N/A
=> Reword docker readme

docs/book/src/clusterctl/provider-contract.md, docs/book/src/developer/tilt.md, docs/book/src/reference/glossary.md, docs/book/src/user/quick-start.md
This PR adds Cluster API Provider DigitalOcean Quick Start in CAPI book
/cc @kubernetes-sigs/cluster-api-provider-digitalocean-maintainers
=> 📖 Add CAPDO quickstart in CAPI book

docs/book/src/roadmap.md
Good morning / evening / afternoon 😄, as promised this PR starts documenting the items the community is planning on working on for v1alpha4. Work has already started on the main branch and we're focusing on getting the busy work out of the way to focus more on designs and proposals soon.
This list isn't complete, feel free to add comments or call out any items that I might have missed.
=> 📖 Update the roadmap for v1alpha4

controllers/machine_controller.go, controllers/machine_controller_test.go
When the KCP object has a non-zero deletionTimestamp, skips the node draining.
Fixes #2756
=> 🌱 Avoid draining when KCP object is being deleted

controlplane/kubeadm/internal/workload_cluster_coredns_test.go
This patch fixes the test flakes seen while running the workload cluster coredns tests in CI 
n/a
=> 🐛  Addresses workload coredns test flakes

cmd/clusterctl/client/repository/client_test.go
Fix a typo in clusterctl client test
Fixes #
=> 🌱 Fix typo in clusterctl client test

util/patch/options.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #3935
=>  ✨ Un-deprecate WithOwnedConditions and OwnedConditions

docs/book/src/user/quick-start.md
This is backport of #3943 
Fixes #
=> 📖 Backport of updating CAPO variables in Quick Start 

controlplane/kubeadm/controllers/controller.go, controlplane/kubeadm/internal/workload_cluster_etcd.go
Forward port of #3919
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #3957
/assign @CecileRobertMichon @ncdc 
=> 🐛 Prevent reconcileEtcdMember to remove etcd members when etcd starts slowly

cmd/clusterctl/client/cluster/components.go, cmd/clusterctl/client/cluster/components_test.go, cmd/clusterctl/client/cluster/inventory_managementgroup_test.go, cmd/clusterctl/client/cluster/mover.go, cmd/clusterctl/client/cluster/mover_test.go, cmd/clusterctl/client/cluster/objectgraph.go, cmd/clusterctl/client/cluster/objectgraph_test.go, cmd/clusterctl/client/cluster/template_test.go, cmd/clusterctl/client/cluster/workload_cluster_test.go, cmd/clusterctl/client/repository/components.go, cmd/clusterctl/client/repository/components_client_test.go, cmd/clusterctl/client/repository/components_test.go, cmd/clusterctl/client/upgrade_test.go, cmd/clusterctl/internal/scheme/scheme.go, cmd/clusterctl/internal/test/fake_objects.go, cmd/clusterctl/internal/test/fake_proxy.go, cmd/clusterctl/internal/test/providers/bootstrap/groupversion_info.go, cmd/clusterctl/internal/test/providers/controlplane/groupversion_info.go, cmd/clusterctl/internal/test/providers/external/groupversion_info.go, cmd/clusterctl/internal/test/providers/infrastructure/groupversion_info.go
This PR makes clusterctl codebase to use the Cluster API v1alpha4 API version.
=> ⚠️ make clusterctl use v1alpha4 api

OWNERS_ALIASES
I'm not able to keep up with this project anymore and it's filling up my GitHub notifications 😸
Fixes #
=> 🌱 Remove myself from reviewers

controllers/machinehealthcheck_controller.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_status_matcher_test.go
cherry-pick #3998 to master
Fixes #3997
=> 🐛 MHC sort mhc status targets to avoid status keep changing

OWNERS, OWNERS_ALIASES
Move myself to emeritus status.
CAPD had only me listed as a maintainer, so I am nominating Fabrizio to
take over.
Fixes #
=> 🌱 Move ncdc to emeritus

README.md
=> :book: Update notes link due to VMware GSuite migration

.golangci.yml, controllers/cluster_controller_phases_test.go, controllers/cluster_controller_test.go, controllers/external/util_test.go, controllers/machine_controller_noderef_test.go, controllers/machine_controller_phases_test.go, controllers/machine_helpers_test.go, controllers/machinehealthcheck_controller_test.go, controllers/machinehealthcheck_targets_test.go, controllers/machineset_controller_test.go, controllers/remote/cluster_test.go, exp/controllers/machinepool_controller_noderef_test.go, exp/controllers/machinepool_controller_phases_test.go, util/kubeconfig/kubeconfig_test.go, util/util_test.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #3987
=> 🌱Remove deprecated fake.NewFakeClient and fake.NewFakeClientWithScheme

test/framework/docker_logcollector.go
Collect pods logs from workload clusters in E2E tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3641
=> 🌱 Collect pods logs from workload clusters in E2E tests

README.md
Otherwise it takes two extra clicks to get to the meeting notes (one to open the current document, and other to close the old one).
Fixes #
N/A
=> 📖 Update README to point to new agenda document.

api/v1alpha3/cluster_types.go
=> 🐛 Fix APIEndpoint for IPv6

cmd/clusterctl/cmd/rollout/restart.go
**What this PR does / why we need it**: This PR fixes a typo for "cluster".
Fixes #
=> 🐛 Fix typo for "cluster"

docs/book/src/developer/testing.md
Reading through docs, found a few nits that need to be updated.
Fixes #
=> 📖 Update testing.md

controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go, controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go, controlplane/kubeadm/controllers/upgrade.go, controlplane/kubeadm/internal/kubeadm_config_map.go, controlplane/kubeadm/internal/kubeadm_config_map_test.go, controlplane/kubeadm/internal/workload_cluster.go, controlplane/kubeadm/internal/workload_cluster_test.go
=> ✨ KCP spec mutation for ApiServer, ControllerManager, and Scheduler

docs/book/src/developer/guide.md
Fix cert-manager version in the developer's guide
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4110
=> 📖 Fix cert-manager version in the developer's guide

exp/addons/controllers/clusterresourceset_controller.go, exp/addons/controllers/clusterresourceset_controller_test.go
Backports  #4129
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4115
=> 🐛 Fix ClusterResourceSet not getting Secret/Configmap TypeMeta

docs/book/Makefile
https://github.com/kubernetes-sigs/cluster-api/pull/4127 onto release-0.3
Fixes #
=> 📖 Update mdbook to 0.4.5 to fix CVE-2020-26297

api/v1alpha3/conversion_test.go, bootstrap/kubeadm/api/v1alpha3/conversion_test.go, util/conversion/conversion.go
This Pr restore fuzzer test for v1alpha3 <-> v1alpha4 conversions
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4210
=> 🌱 Restore Fuzzer tests

Makefile, cmd/clusterctl/client/init_test.go, docs/Makefile, docs/developer/releasing.md, test/framework/kubetest/run.go
=> 🌱 Switch published artifacts to k8s.gcr.io

test/infrastructure/docker/exp/docker/nodepool.go
This PR fixes a status patch issue introduced during changing *v1alpha3.DockerMachinPoolStatus to v1alpha4.DockerMachinPoolStatus in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/4109
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4205
=> 🐛 Fix docker machine pool status update

bootstrap/kubeadm/config/manager/manager.yaml, bootstrap/kubeadm/config/rbac/auth_proxy_role_binding.yaml, bootstrap/kubeadm/config/rbac/kustomization.yaml, bootstrap/kubeadm/config/rbac/leader_election_role_binding.yaml, bootstrap/kubeadm/config/rbac/role_binding.yaml, bootstrap/kubeadm/config/rbac/service_account.yaml, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, controlplane/kubeadm/config/manager/manager.yaml, controlplane/kubeadm/config/rbac/auth_proxy_role_binding.yaml, controlplane/kubeadm/config/rbac/kustomization.yaml, controlplane/kubeadm/config/rbac/leader_election_role_binding.yaml, controlplane/kubeadm/config/rbac/role_binding.yaml, controlplane/kubeadm/config/rbac/service_account.yaml, docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md, test/infrastructure/docker/config/manager/manager.yaml, test/infrastructure/docker/config/rbac/auth_proxy_role_binding.yaml, test/infrastructure/docker/config/rbac/kustomization.yaml, test/infrastructure/docker/config/rbac/leader_election_role_binding.yaml, test/infrastructure/docker/config/rbac/role_binding.yaml, test/infrastructure/docker/config/rbac/service_account.yaml
Using individual, custom service accounts is a common best practice.
Fixes #4015
=> ⚠️ Use individual service accounts

controllers/cluster_controller_test.go
Test case for MachinePools
Fixes #3294
=> 🌱 Add test for listDescendents fetch MachinePools

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: backport of #4188 
Fixes #
=> 📖 update quickstart doc

exp/operator/config/samples/operator_v1alpha4_bootstrapprovider.yaml, exp/operator/config/samples/operator_v1alpha4_controlplaneprovider.yaml, exp/operator/config/samples/operator_v1alpha4_coreprovider.yaml, exp/operator/config/samples/operator_v1alpha4_infrastructureprovider.yaml
Delete samples from operator repo for better consistency with other CAPI components.
/area operator
=> 🌱 Delete samples from operator repo

bootstrap/kubeadm/internal/cloudinit/cloudinit.go
=> :seedling: fix the typo in error message

exp/operator/config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml, exp/operator/config/rbac/role.yaml
Generate operator manifests
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4271
/area operator
=> ✨Generate operator manifests

Makefile
I noticed these minor inconsistencies while going through the makefile and decided to fix them.
=> 🌱 Use variables in Makefile consistently

docs/book/src/user/quick-start.md
The PR for the same has been pushed in #4189 
This is backport to the 0.3 branch.
Fixes #
=> 📖 Quickstart doc update

bootstrap/kubeadm/main.go, controlplane/kubeadm/main.go, main.go, test/infrastructure/docker/go.mod, test/infrastructure/docker/main.go
This PR will normalize the flags from `_` to `-`.
Fixes #4309
=> 🌱 Normalizing flags from _ to -

test/framework/clusterctl/e2e_config.go, test/framework/clusterctl/repository.go
Fixes #4275
Adds support for `file` scheme with absolute paths in component source.
In mentioned issue following example of component source is given:
```
versions:
- name: v0.3.0
type: url
value: "file://relative/path/to/components.yaml"
```
It still wouldn't work, because it uses relative path. I think it should be left that way, because [RFC8089 states](https://tools.ietf.org/html/rfc8089#section-2) that only `path-absolute` should be permitted for`file` scheme.
=> 🐛 E2E framework: support 'file' scheme in component source

Makefile
This change is aimed to save some time (albeit very little) when running
make generate targets. It also cleans up the Makefile a bit to reduce
some verbosity.
Fixes #
/assign @fabriziopandini @invidian @CecileRobertMichon
=> 🌱 Reorganize Make generate targets

exp/addons/controllers/clusterresourceset_controller_test.go
The frequent flakiness we observe in CRS test is due to the timeout value set in this test.
Locally this is unreproducible as 10 seconds is enough for ClusterResourceSetBinding creation, but maybe test infra became slower and we are hitting this limit. Increased timeout value, we should observe this less frequent.
Fixes #
=> 🐛 Flaky ClusterResourceSet test fix

Dockerfile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Dockerfile.dev
In Dockerfile notes, `--build_arg ` should be `--build-arg`
=> 🌱 Fix typo

cmd/clusterctl/client/alpha/client.go, cmd/clusterctl/client/alpha/machinedeployment.go, cmd/clusterctl/client/alpha/rollout.go, cmd/clusterctl/client/alpha/rollout_pauser.go, cmd/clusterctl/client/alpha/rollout_pauser_test.go, cmd/clusterctl/client/alpha/rollout_restarter.go, cmd/clusterctl/client/alpha/rollout_restarter_test.go, cmd/clusterctl/client/alpha/rollout_resumer.go, cmd/clusterctl/client/alpha/rollout_resumer_test.go, cmd/clusterctl/client/alpha/rollout_rollbacker.go, cmd/clusterctl/client/alpha/rollout_rollbacker_test.go, cmd/clusterctl/client/rollout.go, cmd/clusterctl/internal/util/obj_refs.go, cmd/clusterctl/internal/util/obj_refs_test.go
* Switched from use of tuple to object refs
* Now using global context
* Moved MD specific code to a separate file.
Fixes #
https://github.com/kubernetes-sigs/cluster-api/issues/4266
=> 🐛 Cleanup recent work with `clusterctl alpha rollout` command

cmd/clusterctl/cmd/upgrade_plan.go
Removes  duplicate `upgrade` word 
Fixes #4422
=> 🌱 Remove duplicate upgrade word

controlplane/kubeadm/controllers/controller_test.go
Accordingly, with the cluster-api code policies, I have removed Ginkgo from the Kubeadm Controller integrations tests.
=> 🌱 Removing ginkgo from Kubeadm Controller tests

README.md
`what to get the latest project news` --> `want to get the latest project news`
Just noticed this in the cluster API book and decided to submit this minor correction :slightly_smiling_face:
=> 📖 Improve project news docs statement

bootstrap/kubeadm/types/v1beta2/doc.go
Canonical import paths err in  `bootstrap/kubeadm/types/v1beta2/doc.go`
Fixes #
=> 🐛 Fix Canonical import paths err

exp/operator/api/v1alpha4/bootstrapprovider_types.go, exp/operator/api/v1alpha4/controlplaneprovider_types.go, exp/operator/api/v1alpha4/coreprovider_types.go, exp/operator/api/v1alpha4/groupversion_info.go, exp/operator/api/v1alpha4/infrastructureprovider_types.go, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml, exp/operator/config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml, exp/operator/controllers/coreprovider_controller.go, exp/operator/main.go
Run `make lint-fix` and `make generate` in the operator.
Fixes #
=> 🌱Fix linting issues for operator

exp/operator/config/rbac/role.yaml, exp/operator/controllers/boostrapprovider_controller.go, exp/operator/controllers/controlplaneprovider_controller.go, exp/operator/controllers/infastructureprovider_controller.go, exp/operator/main.go
Setup controllers and generate roles for all operator objects.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4270
/area operator
=> ✨ Setup controllers and roles for operator objects

docs/book/src/clusterctl/commands/upgrade.md
📖 fix a typo (upgrade.md)
Fixes #
=> 📖 correct a word

controlplane/kubeadm/internal/workload_cluster_coredns.go, controlplane/kubeadm/internal/workload_cluster_coredns_test.go
This PR is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/4476
The upstream image for CoreDNS was renamed from 'k8s.gcr.io/coredns' to `k8s.gcr.io/coredns/coredns`, and this is impacting upgrades of workload clusters from v1.20 to v1.21. 
This PR makes KCP upgrades to account for this change.
Please note that:
- the change applies only to users relying on upstream image repository (`k8s.gcr.io`); users relying on custom repository could continue to use `myrepo.io/coredns` as image name (no changes required).
- starting from CoreDNS 1.8.0, the upstream images requires the `v` prefix on the ImageTag, but this should be taken care by the user when specifying the desired version in KCP.
Rif …
=> 🐛 Fix CoreDNS upgrade from v1.20 to v1.21

docs/book/src/reference/providers.md, docs/book/src/user/quick-start.md
Slight cleanup for AWS docs, and some more links back to the CAPA book.
Fixes #
=> 📖 Docs improvement for AWS

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: Getting started doc was moved to the capz book,
Fixes #
=> 📖 Update Azure Provider Prerequisites link in quick start

controllers/machinedeployment_sync.go, controllers/machinedeployment_sync_test.go
Rename unit test to TestCalculateStatus to be consistent with unit test conventions.
Fixes #
=> 🌱 Rename unit test to TestCalculateStatus

docs/book/src/clusterctl/configuration.md
When I copied these lines on the page and executed it, I found some file name not correct, "-" and "_" are confused.
=> 🌱correct filenames

controlplane/kubeadm/internal/workload_cluster.go
`UpdateImageRepositoryInKubeadmConfigMap`  method comment error.
Fixes #
=> 🌱 Fix comment for UpdateImageRepositoryInKubeadmConfigMap

docs/proposals/20191017-kubeadm-based-control-plane.md
Fix typo in ` docs/proposals/20191017-kubeadm-based-control-plane.md`
Fixes #
=> 📖 Fix typo in docs/proposals/20191017-kubeadm-based-control-plane.md

test/e2e/cluster_upgrade.go, test/e2e/config/docker.yaml, test/framework/daemonset_helpers.go, test/framework/node_helpers.go
Improves flaky upgrade test stability, see: #4502
Fixes #
=> 🌱 Fix flaky upgrade e2e test

docs/book/src/user/quick-start.md
**What this PR does / why we need it**: backport #4504 to CAPI book.
Fixes #
=> Update Azure Provider Prerequisites link in quick start

controllers/machinedeployment_controller.go
Fix comment issue of  `MachineSetToDeployments`  method in `controllers/machinedeployment_controller.go`
Fixes #
=> 🌱 Fix comment issue in method `MachineSetToDeployments`

util/conversion/conversion.go
Currently, when metav1.Time is a pointer it never gets fuzzed by the
meta functions. After a further look, it seems like the Creation or
Deletion timestamps on ObjectMeta are fuzzed in this way as well.
This patch adds custom logic to fuzz the metav1.Time objects when it's
not nil.
/assign @sbueringer
=> :seedling: Add a fuzzer function for *metav1.Time

docs/book/src/user/quick-start.md
Otherwise CAPD quickstart failed on my Mac.
=> :book: :seedling: Note macOS may need more memory.

docs/proposals/20181121-machine-api.md, docs/proposals/20191016-clusterctl-redesign.md, docs/proposals/20191017-kubeadm-based-control-plane.md, docs/proposals/20191030-machine-health-checking.md, docs/proposals/20200330-spot-instances.md, docs/proposals/20200423-etcd-data-disk.md, docs/proposals/20200506-conditions.md, docs/proposals/20200511-clusterctl-extensible-template-processing.md, docs/proposals/20200602-machine-deletion-phase-hooks.md, docs/proposals/20210203-externally-managed-cluster-infrastructure.md, docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md
Fix typo in docs/proposals
Fixes #
=> 📖 Fix typo in docs/proposals

controlplane/kubeadm/controllers/remediation.go, controlplane/kubeadm/controllers/remediation_test.go
This fix makes it possible for KCP to remediate machines when the etcd member being remediated is missing, might be due to problem during join or due to problem during a previous remediation operation.
This PR is a backport of https://github.com/kubernetes-sigs/cluster-api/pull/4561
=> 🐛 Allow KCP remediation when the etcd member being remediated is missing

exp/controllers/machinepool_controller_phases_test.go, exp/controllers/suite_test.go
Refactors the tests in the exp/controllers package to use plain Go testing instead of ginkgo.
Refs #4588
=> 🌱 Refactor tests to plain go in exp/controllers

controlplane/kubeadm/internal/workload_cluster.go
The etcd tests have been flaking a lot lately with:
```
=== RUN   TestReconcileEtcdMembers/successfully_removes_the_etcd_member_without_a_node_and_removes_the_node_from_kubeadm_config
workload_cluster_etcd_test.go:550: 
Unexpected error:
<errors.aggregate | len:1, cap:1>: [
<*errors.withStack | 0xc000b4ea68>{
error: <*errors.withMessage | 0xc000e515a0>{
cause: <*errors.StatusError | 0xc0002e0320>{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on configmaps \"kubeadm-config\": the object has been modified; please apply your changes to the latest …
```
=> :seedling: KCP should use some backoff when updating kubeadm configmap

test/infrastructure/docker/docker/kind_manager.go
When using the Btrfs or ZFS storage drivers for docker it is necessary to mount `/dev/mapper` into the container when trying to run kubelet. Otherwise cAdvisor will fail to fetch partition information when the host system is using Btrfs or ZFS, which is a fatal error in kubelet.
Kind ran into the same issue, this PR ports the fix to CAPD: https://github.com/kubernetes-sigs/kind/pull/1464
Issue with more info: https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-606514724
It probably makes sense to hold off on merging this until #4413 is done, as this currently calls the docker cli.
=> 🌱 capd: add support for btrfs and zfs

api/v1alpha4/machinedeployment_webhook.go, api/v1alpha4/machinedeployment_webhook_test.go
This PR normalizes the MachineDeployment Kubernetes version validation flows to always include a "v" prefix, yielding a consistent value that matches the pattern `v.<major>.<minor>.<patch>`.
This approach matches what we're doing for Machine resource admission here:
- https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machine_webhook.go#L125-L129
- https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machine_webhook.go#L58
In fact, doing this in MachineDeployment fixes a bug that results from Machine and MachineDeployment showing a different version, for example "v1.19.10" and "1.19.10", respectively.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
=> 🐛 normalize MachineDeployment version validation

OWNERS_ALIASES
Add Alberto as reviewer.
Proposals: https://github.com/kubernetes-sigs/cluster-api/search?q=enxebre
PRs: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Aenxebre
Reviews: https://github.com/kubernetes-sigs/cluster-api/pulls?page=1&q=is%3Apr+enxebre
Issues: https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Aenxebre+
cc @fabriziopandini @CecileRobertMichon @vincepri @JoelSpeed @sbueringer 
Fixes #
=> 🌱 Add enxebre as reviewer

controlplane/kubeadm/controllers/remediation_test.go
Wraps the assertion in an eventually, and adds a check for `nil` conditions
=> 🐛 Assertion of Machine condition should be in an Eventually

docs/book/src/SUMMARY.md, docs/book/src/tasks/kubeadm-bootstrap.md
Add a REDME to the bootstrap/kubeadm folder. The readme covers topics likes how CABPK works, bootstrap orchestration, certificate management, etc.
Fixes #4151
=> 📖 Add page for the bootstrap kubeadm provider

test/e2e/clusterctl_upgrade.go, test/framework/clusterctl/clusterctl_helpers.go
**What this PR does / why we need it**: Fix logs printing pointers in e2e framework.
Fixes #
=> 🌱  Fix E2E log statements printing pointers

bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
Improves unit test coverage of `bootstrap/kubeadm/internal/cloudinit`
Fixes #4634 
New test coverage:
```shell
❯ go test ./... -coverprofile cover.out && go tool cover -func cover.out
ok      sigs.k8s.io/cluster-api/bootstrap/kubeadm/internal/cloudinit    0.485s  coverage: 75.0% of statements
sigs.k8s.io/cluster-api/bootstrap/kubeadm/internal/cloudinit/cloudinit.go:60:           prepare                 90.9%
sigs.k8s.io/cluster-api/bootstrap/kubeadm/internal/cloudinit/cloudinit.go:76:           generate                59.1%
sigs.k8s.io/cluster-api/bootstrap/kubeadm/internal/cloudinit/cloudinit.go …
```
=> 🌱 add unit tests to NewJoinControlPlane

controlplane/kubeadm/internal/workload_cluster_coredns_test.go
This PR attempts to remove flakes from the TestUpdateCoreDNS unit test by wrapping assertions in an Eventually loop
=> 🌱 fix TestUpdateCoreDNS flakes

.github/dependabot.yml
Adds dependabot configuration for automated dependency updates. 
You can see what's happening in CAPA here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+label%3Adependencies 
Fixes #
=> :seedling: Add dependabot configuration

.github/dependabot.yml
=> 🌱 Add dependabot prefix to commits and PRs

test/framework/clusterctl/clusterctl_helpers.go
In e2e test framework's `ApplyClusterTemplateAndWait`, the logic for control plane is tightly coupled with kubeadmControlPlane implementation. This is not suitable when we want to test clusters where the control plane is not kubeadm. Eg. In capz, for [testing AKS clusters](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/611) where the control plane is an `AzureManagedControlPlane`. In CAPA this is fixed by not using `ApplyClusterTemplateAndWait` and calling the individual functions like `DiscoveryAndWaitForCluster`. But, this will result in duplicate code. This PR tries to address this concern by decoupling control plane status check logic, and providing the ability to inject custom checks for control plane if needed.
**Which …
=>  🌱 E2E: Decouple control plane status check logic

README.md
Spring cleaning 🎉 , adds a bit more color to our home page and welcomes all folks! It also fixes some badges
=> 📖 Update our README for more friendliness 🤗 

Dockerfile, Makefile, test/infrastructure/docker/Dockerfile, test/infrastructure/docker/Makefile
This PR allows users to override the builder image.
Fixes #
=> 🌱 Add build arg to override builder image

Makefile
=> :bug: Makefile should reference the correct Go version var

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile, test/infrastructure/docker/cloudinit/runcmd.go, test/infrastructure/docker/cloudinit/writefiles.go, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller_test.go, test/infrastructure/docker/docker/machine.go, test/infrastructure/docker/docker/types/node.go, test/infrastructure/docker/exp/controllers/dockermachinepool_controller.go, test/infrastructure/docker/exp/docker/nodepool.go, test/infrastructure/docker/main.go
=> :seedling: Enable golanci-lint for test/ submodule

README.md
=> 📖 Update README for a more up-to-date view

docs/book/Makefile
=> :seedling: Update mdbook to v0.4.10

docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/4782#issuecomment-858150519
=> 📖 update v1alpha4 migration documentation

docs/developer/releasing.md
=> :book: Add note that test/ tag must never be annotated

docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/4782#discussion_r649065219
=> 📖  update v1alpha4 migration documentation

docs/book/theme/css/chrome.css, docs/book/theme/css/custom.css, docs/book/theme/highlight.css
- Uses system fonts whenever possible
- Fixes an issue with tabs not displaying in the quick start (packet wasn't working)
- Removes the big < and > buttons from the page
- Enlarges the content area
=> :seedling: Improve book readability, fix bug with tabs in quick start

docs/book/src/reference/providers.md
Make API Adopters more explicitly
Fixes #
=> 📖 providers.md: Make API Adopters more explicitly

hack/tools/release/notes.go
=> 🌱 Release notes gen categorize proposals and summarize doc changes

cmd/clusterctl/internal/util/objs.go, cmd/clusterctl/internal/util/objs_test.go
=>  🌱 include deamonsets in list images in clusterctl - 0.3.x

docs/book/src/introduction.md
**What this PR does / why we need it**: Change the "old" docs reference from v1alpha2 to v1alpha3. Depends on https://github.com/kubernetes/k8s.io/pull/2269
Fixes #
=> 📖  Update v1alpha3 API book link in introduction

Makefile
Per @scottslowe's request https://twitter.com/scott_lowe/status/1408526196090957825?s=20  😊 
Fixes #
=> :seedling: Build clusterctl arm64 for linux and darwin

cmd/clusterctl/api/v1alpha3/metadata_type.go, cmd/clusterctl/client/cluster/installer.go, cmd/clusterctl/client/repository/metadata_client.go, cmd/clusterctl/client/repository/repository_github.go, cmd/clusterctl/client/repository/repository_github_test.go, cmd/clusterctl/client/repository/repository_local.go
**What this PR does / why we need it**: backport of #4866 
Fixes #4856
=> 🐛 Use metadata.yaml in github repo to fetch latest release for older contracts

Makefile, bootstrap/kubeadm/config/rbac/role.yaml, bootstrap/kubeadm/controllers/kubeadmconfig_controller.go, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/machine_controller.go, controllers/machinedeployment_controller.go, controllers/machinehealthcheck_controller.go, controllers/machineset_controller.go, exp/addons/controllers/clusterresourceset_controller.go, exp/controllers/machinepool_controller.go, test/infrastructure/docker/config/rbac/role.yaml, test/infrastructure/docker/controllers/dockercluster_controller.go, test/infrastructure/docker/controllers/dockermachine_controller.go, test/infrastructure/docker/exp/controllers/dockermachinepool_controller.go, test/infrastructure/docker/exp/controllers/exp.go
=> :bug: Ensure /finalizer permissions for OwnerReferencesPermissionEnforcement admission controller
