internal/controllers/machine/machine_controller_phases_test.go

The test patches the status of the Machine, while the reconciliation may be already happening. This leads to inconsistent state which is not deterministic and into the Machine's status to never reach the targeted state of the test.
With this change, the test just ensures that the LastUpdated timestamp gets set to a later time.
See [this](https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20after%2010&job=.*-cluster-api-.*&test=sigs.k8s.io%2Fcluster-api%2Finternal&xjob=.*-provider-.*) for current flake occurency.
Fixes #8477

🐛 internal/machine-controller fix flakes in phases test

---

api/v1beta1/index/machine.go
api/v1beta1/index/machine_test.go
api/v1beta1/index/machinepool.go
api/v1beta1/index/machinepool_test.go
api/v1beta1/index/node.go
api/v1beta1/index/node_test.go
controllers/noderefutil/providerid.go
controllers/noderefutil/providerid_test.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_noderef.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_noderef_test.go

This PR updates code flows that use a strongly typed, constructed `ProviderID` object to represent a CAPI-opinionated version of a cloud provider's node providerID: instead of wrapping the raw providerID in a CAPI object, we now simply evaluate machine-node affinity by simply comparing the providerID strings for equality.
As an exercise in best practices, the existing `ProviderID` type definition is kept in place and marked for deprecation. This is to allow this change to be backported to existing minor releases so that cloud providers who are blocked on the current CAPI-opinionated `ProviderID` validations can make forward progress towards CAPI adoption.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

🌱 use providerID string as-is

---

docs/book/src/reference/versions.md

(cherry picked from commit af03bdd9d68918ff37113cb5764975a6394ef811)
Manually cherry-picks #https://github.com/kubernetes-sigs/cluster-api/pull/8520 considering [this comment](https://github.com/kubernetes-sigs/cluster-api/pull/8520#issuecomment-1506923176) from original PR and assumes support for v1.27 will start from v1.4.2. This will be on hold until 1.4.x release out with 1.27 support and will be left as is or updated accordingly
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8459
cc @kubernetes-sigs/cluster-api-release-team 
/hold

[release-1.4] 📖 Update versions doc with k8s v1.27 notes

---

Makefile
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
cmd/clusterctl/config/manifest/clusterctl-api.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml

PR to test controller-tools main ahead of the ct release. Will change to v0.12 once it is released.
Fixes #

🌱 Bump controller-tools to v0.12

---

cmd/clusterctl/client/tree/discovery.go

If no control plane reference is set in the Cluster object the describe cluster command will fail. We should validate the error in any case.
Fixes #8603
<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

🐛 Return error on infra cluster and control plane discovery

---

cmd/clusterctl/client/repository/repository_github.go
cmd/clusterctl/client/repository/repository_github_test.go
cmd/clusterctl/client/repository/repository_versions.go

This PR adds the ability to detect a 404 error from the github client and handle the error differently than just bubbling up the usual error message.
It now also does not retry fetching the release on 404 errors and immediately returns instead.
Old output was (after 1m timeout):
> Error: failed to get provider components for the "cluster-api" provider: failed to read "core-components.yaml" from provider's repository "cluster-api": failed to get GitHub release v1.3.6: failed to read release "v1.3.6": GET https://api.github.com/repos/kubernetes-sigs/cluster-api/releases/tags/v1.3.6: 404 Not Found []
New output is:
> Error: failed to get provider components for the "cluster-api" provider: failed to get repository client for the CoreProvider with name …

🐛 clusterctl: return early if release for latest tag does not exist yet

---

docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md

Fixes a reference between two examples in the cluster api book

:book: Fix documentation

---

docs/release/release-tasks.md

This PR adds some notes in order to reduce the risk of wrong copy&pasting when polishing the release notes for a new release. Relevant [slack discussion](https://kubernetes.slack.com/archives/C8TSNPY4T/p1683157724701359).
Fixes #
<sub>Johannes Frey <[johannes.frey@mercedes-benz.com](mailto:johannes.frey@mercedes-benz.com)>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

:book: Adjust release notes section to reduce the chance of wrong copy paste

---

controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/internal/cluster.go
controlplane/kubeadm/internal/workload_cluster.go

When connecting to etcd on the workload clusters KCP creates a temporary certificate, however, one step of this operation, creating the private key for the new certificate, is CPU-consuming (see data on https://github.com/kubernetes-sigs/cluster-api/issues/8602 for more details).
This PR adds a private key to the clusterAccessor in the ClusterCacheTracker, created once for each cluster, so that KCP can re-use it at every reconciliation/in all the reconcile methods.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8602
cc @sbueringer @lentzi90

🐛 Prevent KCP to create many private keys for each reconcile

---

api/v1beta1/cluster_types.go
api/v1beta1/clusterclass_types.go
cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/move.go
cmd/clusterctl/client/move_test.go

As a developer I would like to move capi resources from one cluster to another cluster and while doing so, i would want to control the namespace the resources are created in the target cluster. Right now, when i perform a move operation, clusters are always moved to the same namespace on target cluster as they are originally created in the originating cluster. I want to be able to control this so that I can move resources from multiple clusters to a single cluster and still organize them by namespace post move operation.
This PR takes the approach discussed in https://github.com/kubernetes-sigs/cluster-api/issues/7940#issuecomment-1398279360 An alternative to this PR was initially proposed at #7941 but that approach seemed inflexible. So this PR …

:sparkles: feat: accept resource mutators in Move operation

---

exp/addons/internal/controllers/clusterresourceset_controller.go

Previously as soon as apply for a single cluster failed the Reconcile func returned and other clusters were not reconciled.
With this PR we try to apply for all clusters and then requeue if one of them returned an `ErrClusterLocked` error.
Fixes #

🐛 ClusterResourceSet: continue applying when apply for a single cluster failed

---

controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/internal/cluster.go
controlplane/kubeadm/internal/workload_cluster.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8617

🐛 [release-1.3] Prevent KCP to create many private keys for each reconcile

---

exp/addons/api/v1beta1/clusterresourceset_webhook.go
exp/api/v1beta1/machinepool_webhook.go
internal/webhooks/clusterclass.go

Minor grammar clarification to code comments in `v1beta1`.

:book: Minor documentation grammar changes for code comments.

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Update cert manager version to v1.11.2
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.11.2

:seedling: Update cert-manager to v1.11.2

---

test/framework/docker_logcollector.go

When using ExecContainerInput to create the tarball, the same buffer got used for stdout and stderr. This broke the tarball which resulted in not extracting the files and having them not available in artifacts.
I noticed this when I wanted to debug a failed e2e test.
All e2e tests currently log the following per machine (no matter of succeeded or failed):
```
Failed to get logs for Machine mhc-remediation-zy726b-control-plane-gl7bs, Cluster mhc-remediation-fxvkzb/mhc-remediation-zy726b: exit status 2
```
And this should be resolved by this MR.
We maybe should cherry-pick this to v1.4 and v1.3? …

:bug: test/framework fix docker pod log collector

---

test/e2e/cluster_upgrade_runtimesdk.go

Sometimes when reaching the parts where we wait for the hooks, not all machines are ready. This results in the hook not even getting executed during the 30s period.
Failed test logs did show that it may only be a minute which is missing until everything would succeed.
This PR adds a check to ensure all machines are healthy before continuing.
Workaround for #8486
We want to still try to track it down to see if we have an underlying issue.
cc @killianmuldoon 
Note:
* for control plane nodes we already check if this condition is true (edit: when upgrading a cluster): …

🐛 test/e2e check for machines being ready after provisioning on Runtime SDK test

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

There are some CVE's in <v2.8.2, let's bump to get rid of the security alerts. To me it looks like they are not exploitable in any way in core CAPI (we only use one single package from this dependency)
xref: https://github.com/distribution/distribution/releases/tag/v2.8.2
Fixes #

🌱 Bump docker/distribution to v2.8.2

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

There's a couple of CVEs fixed as part of this release, so backporting to release-1.3
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8645

[release-1.3] :seedling:  Bump docker/distribution to v2.8.2

---

docs/book/src/tasks/experimental-features/ignition.md

This PR addresses an inconsistency found between our documentation and the actual code for setting the Ignition bootstrap feature gate environment variable. The aim is to ensure users are provided with accurate instructions, thus eliminating possible confusion or issues.
In the current [documentation](https://cluster-api.sigs.k8s.io/tasks/experimental-features/ignition.html#initialize-the-management-cluster), users are instructed to use
`export BOOTSTRAP_FORMAT_IGNITION=true` for the AWS provider.
However, in the [actual code](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d307586108c09543e3cdf4c5462228065081d20b/config/manager/manager.yaml#L22), the environment variable is …

:bug: Fix Documentation for Ignition Bootstrap Feature Gate Environment Variable

---

test/infrastructure/docker/internal/docker/kind_manager.go

Delegate port selection to the container runtime by passing 0 directly into the runtime on container creation.
Related to #8641

:bug: Delegate CAPD port selection to the container runtime

---

test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl

It is [common to mark kubeadm and related packages as held](https://v1-25.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#call-kubeadm-upgrade) at a specific version to avoid accidental upgrades. The script for injecting CI artifacts does not take this into account, which means that if the base image used already has some version of a package installed and held, the script will fail to install the asked for version. To avoid this, we unhold before installing the packages and then hold again, as customary. Holding after installation also avoids any unintended upgrades later.
An alternative could be to add the flag `--allow-change-held-packages` to the install command, but I think unholding is a nicer way to do it.
**Which …

🌱 E2e: Unhold CI packages before installing

---

scripts/ci-e2e.sh

Set `fail-fast=false` for e2e test jobs by default. This will give better test coverage by running more tests so more than one failure at a time can surface. 
Context: https://github.com/kubernetes-sigs/cluster-api/pull/8365#issuecomment-1519808239

:seedling: Disable fail-fast by default for e2e tests

---

scripts/ci-e2e.sh

Manual cherry-pick of #8548
Fixes #

[release-1.3] 🌱 Disable fail-fast by default for e2e tests

---

scripts/ci-e2e.sh

Manual cherry-pick of #8548
Fixes #

[release-1.4] 🌱 Disable fail-fast by default for e2e tests

---

scripts/ci-e2e.sh

Provides the output of `ps -ef` at the end of a test, to eventually detect existing zombie processes.
Tries to gather this data for inspecting #8560 some more.
Fixes #

🌱 e2e: log leftover processes to eventually detect zombies

---

test/e2e/data/cni/kindnet/kindnet.yaml
test/infrastructure/docker/internal/loadbalancer/const.go

Bump images used by kind for networking and load balancer to the latest published versions.

:seedling: Bump kindnet and haproxy images to latest

---

docs/book/src/user/quick-start.md
hack/kind-install-for-capd.sh

Update the quickstart guide and kind startup script to create a dualstack kind cluster by default. This keeps parity with a change made in the CAPI e2e tests in #8517.

:seedling: Use dualstack kind cluster in quick-start and startup script

---

docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
test/framework/cluster_proxy.go
test/framework/docker_logcollector.go
test/infrastructure/container/docker.go

This allows collecting logs from CAPD's lb container and hopefully helps to further debug #8641 .
Fixes #

🌱 test/framework: add functions to collect infrastructure logs in tests

---

Makefile

Update kpromo to release v3.6.0
Release notes: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.6.0

:seedling: Update kpromo to v3.6.0

---

Makefile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8680
Update kpromo to release v3.6.0
Release notes: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.6.0

[release-1.4] :seedling: Update kpromo to v3.6.0

---

Makefile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8680
Update kpromo to release v3.6.0
Release notes: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.6.0

[release-1.3] :seedling: Update kpromo to v3.6.0

---

internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

Sets `TopologyReconciled` status condition to `False` on cluster deletion 
Fixes #7926

:bug: update TopologyReconciled condition on cluster deletion

---

test/e2e/clusterctl_upgrade.go
test/e2e/kcp_remediations.go
test/framework/machinehealthcheck_helpers.go

Fix a minor typo in the the phrase "to exist" in different instances across the codebase.
/area testing

:seedling: Fix typos in phrase "to exist"

---

test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml

Pin the cgroup driver used in templates for v0.3 and v0.4. This is required when running the tests locally - otherwise the created clusters end up with crashing control plane pods. 
Should hopefully also work in CI, but these tests have been generally stable in CI without pinning the versions.

:seedling: Pin cgroup driver used in v0.3 and v0.4 templates

---

test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8684

[release-1.3] :seedling: Pin cgroup driver used in v0.3 and v0.4 templates

---

docs/community/20221115-managed-kubernetes.md

This CAEP and subsequent work that follows from it is sufficient to move Managed Kubernetes forward in Cluster API:
- https://github.com/kubernetes-sigs/cluster-api/pull/8500
Thanks, everyone!
Fixes #

📖 Retire Managed Kubernetes Feature Group

---

Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/internal/docker/machine.go

Bump kind to v0.19.0.
Release notes: https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0

:seedling: Bump kind to v0.19.0

---

docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md

Follow on from #8681.
Bumping the minimum supported kind version in places where it was missed in the docs.

:book: Bump kind version to v1.19.0 in docs

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/clusterclass.go
internal/controllers/topology/cluster/patches/variables/merge.go

Fix typo `exits` to `exists` across codebase.
Fixes

:seedling: Fix typo: exits -> exists

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
docs/book/src/user/troubleshooting.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.0

:seedling: Update cert-manager to v1.12.0

---

test/e2e/data/kubetest/conformance-fast.yaml
test/e2e/data/kubetest/conformance.yaml

Remove `ginkgo.no-color` flag which is not supported in earlier versions of the conformance tests. This flag was not functioning correctly even when enabled.
Currently causing failures in:
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-22-1-23
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-23-1-24

:bug: Remove non-functioning ginkgo.no-color flag 

---

docs/book/src/developer/providers/implementers-guide/generate_crds.md

Fix a broken link to outdated Kubernetes documentation.
In this case I removed the link as it seemed to be the wrong link in the first place, and not useful information in any case.

:seedling: Fix outdated link to Kubernetes docs

---

Tiltfile

Pin delve to a release that supports Go 1.19.
Note: After the 1.9.1 release delve changed to a release scheme matching the Go version.
/area devtools

:seedling: Pin delve to version supporting go 1.19

---

Tiltfile

Pin delve to use Golang v1.20. 
Note: This version should be kept in line with the Go minor version used. 
Fixes #8723 
/area devtools

:seedling: Pin delve to match go minor version

---

test/framework/machinepool_helpers.go

Add some additional information in the logs for the MachinePool upgrade function.
Related to [machinepool](https://github.com/kubernetes-sigs/cluster-api/issues/8718)

:seedling: Improve logging for MachinePool upgrade test

---

docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md

Removed duplicate text block in docs for ClusterClass.

:book: Removed duplicate text block

---

scripts/ci-e2e.sh

Collects information about leftover processes for ci jobs.
Helps on debugging #8560

✨ ci: collect debug information about leftover processes

---

hack/kind-install-for-capd.sh

Align our kind-install-for-capd script with changes being made upstream in kind, keeping the script in-line with that at https://kind.sigs.k8s.io/docs/user/local-registry/
The changes make the script / act of setting up a local registry more complex due to https://github.com/kubernetes-sigs/kind/issues/2875 
/area devtools

:seedling: Align kind registry script with upstream

---

controlplane/kubeadm/internal/controllers/controller.go

This fixes the bug described in #https://github.com/kubernetes-sigs/cluster-api/issues/8691 where KCP would fail to re-reconcile to a good state when the kube-apiserver was misconfigured and failing.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8691

:bug: Allow machine rollout if cert reconcile fails

---

test/infrastructure/docker/internal/docker/kind_manager.go

For more context see #8641.
We came to the conclusion that we can drop the `-sf 7` arguments when starting haproxy.
This seem to be able to exit the haproxy process immediately after start, resulting in not-running lb container and by that in flaky tests.
Kudos to @killianmuldoon for testing the updated arguments to see if config updating still works.
Tries to fix #8641

🐛 CAPD: change the haproxy entrypoint to prevent getting stopped immediately after start

---

test/framework/machinepool_helpers.go

Adjust the timeout in the PollImmediate call in getMachinePoolInstanceVersions. 
In this function we don't get the MachinePool so the nodeRefs stay the same on each call. Because the timeout for this function is 3 minutes per Node and the timeout of the wrapping Eventually call is set at 5 minuted in our end to end test the end result is that we only ever run one `get` request for the MachinePool - there are two nodes each gets a 3 minute timeout.
If upgrades aren't finished or it's out of sync when the function is initalized the nodes being looked for are never updated.
Also added some better logging - improving on #https://github.com/kubernetes-sigs/cluster-api/pull/8728 so if this doesn't fix the issue, or if there's additional flakes in future, we might get more information from the …

:bug: Adjust machinepool helper e2e timeout

---

exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go

…nges
**What this PR does / why we need it**:  Update MachinePool bootstrap dataSecretName when bootstrap config changes. Before, we would return early whenever the dataSecretName was set which means there's no way to update it.
Fixes #6563

🐛 Update MachinePool bootstrap dataSecretName when bootstrap config changes

---

CONTRIBUTING.md
REVIEWING.md
docs/book/src/introduction.md
docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md

Add a message to the note in the book about API version removal detailing the issues that may be caused in garbage collection and the actions necessary for fixing the issue.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8038

:book: Add note about v1alpha3 removal to book

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Update cert-manager to release v1.12.1
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.1

:seedling: Update cert-manager to v1.12.1

---

test/e2e/clusterclass_rollout.go

Increase the timeout on asserClusterObjects for the ClusterClass rollout test. Since https://github.com/kubernetes-sigs/cluster-api/pull/8711 this test has been flaky, due to the certificate reconciliation happening much later in the reconcile loop. Lengthening this timeout should fix the issue.
Fixes #8747

:bug: Increased assertClusterObjects timeout

---

test/e2e/clusterclass_rollout.go

Ignore the cert annotation always in the clusterclass rollout test and rollback timeout change from https://github.com/kubernetes-sigs/cluster-api/pull/8758
This is a tolerant modification of the `without` method which fails when the key does not exist. This is failing and causing a flake in #8747

:bug: Ignore cert annotation in rollout test

---

docs/book/src/developer/tilt.md

**What this PR does / why we need it**: In Tiltfile function prepare_all() expects the values to be substituted as strings but in the book the example contains machine_counts as integer so we need to wrap the numbers in quotes to make them string to prevent error

📖 Wrapped the values with quotes to make them string

---

Makefile
Tiltfile
hack/ensure-go.sh

- Bump golang version (1.20.3 -> 1.20.4)
This version update has 3 security fixes for go:
- https://github.com/golang/go/issues/59720 - https://github.com/advisories/GHSA-3q6h-q44p-xw88
- https://github.com/golang/go/issues/59721 - https://github.com/advisories/GHSA-7qhm-5mxq-x7vp
- https://github.com/golang/go/issues/59722 - https://github.com/advisories/GHSA-c9hr-fvm9-7c49
Fixes #

:seedling: Bump golang version (1.20.3 -> 1.20.4)

---

test/e2e/quick_start_test.go

and drop the regular quickstart test from e2e-main. It covers additional changes from #8224 
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8224

🌱 Move ClusterClass quickstart test from e2e-informing to e2e-main

---

cloudbuild-nightly.yaml
cloudbuild.yaml

- Bump gcb-docker-gcloud from v20230424-910a2a439d to v20230522-312425ae46
Fixes #

:seedling: Bump gcb-docker-gcloud from v20230424-910a2a439d to v20230522-312425ae46

---

test/e2e/clusterclass_rollout.go

Manual cherry-pick of #8769 
Improve the without function in the ClusterClass rollout test to take a gomega handler and fail when the key doesn't exist in the map.
This improves on the change made in https://github.com/kubernetes-sigs/cluster-api/pull/8761

:seedling: [release-1.4] Improve gomega fail handling in clusterClass rollout

---

Tiltfile
hack/observability/grafana/chart/kustomization.yaml
hack/observability/grafana/chart/values.yaml
hack/observability/grafana/dashboards/scale.json
hack/observability/grafana/kustomization.yaml
hack/observability/kube-state-metrics/chart/kustomization.yaml
hack/observability/kube-state-metrics/chart/values.yaml
hack/observability/parca/kustomization.yaml
hack/observability/parca/values.yaml
hack/observability/prometheus/kustomization.yaml
hack/observability/prometheus/values.yaml
hack/tools/tilt-prepare/main.go

✨ hack/observability: Add Parca, Bump observability tools, Add Grafana scale dashboard

---

test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/bases/md.yaml
test/e2e/data/infrastructure-docker/main/bases/mp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.4/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.4/clusterclass-quick-start.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

This PR adds a json patch for KubeadmControlPlanes and MachineDeployments, to set the `fail-swap-on` flag for the kubelet to `false` in our ClusterClasses for the release, main and v1.4 tests.
This prevents that the kubelet refuses to start for newer kind images which don't specify the flag anymore (because kind sets the configuration parameter in KubeletConfiguration.
Fixes #8766

🐛 test/e2e fix fail-swap-on=false flag not being part of kind images anymore

---

test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/bases/md.yaml
test/e2e/data/infrastructure-docker/main/bases/mp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.2/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.2/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.2/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/8767
/assign killianmuldoon

[release-1.4] :bug: fix fail-swap-on=false flag not being part of kind images anymore

---

docs/book/src/user/quick-start.md

This PR changes the Kubernetes version listed in the documentation for the quick-start tutorial as Kubernetes 1.27.0 had a bug which lead to a faster release of 1.27.1 and the rest of the documentation is already updated with this change 
Fixes #

:book: Changed inconsistency with kubernetes version in doc

---

docs/book/src/clusterctl/commands/upgrade.md

Update tested upgrade paths in the CAPI book.

:book: Update tested upgrade paths in docs

---

docs/release/release-tasks.md

Update the CI tasks in the release tasks doc. There is now a periodic job for ipv6 so there's no need to check it independently. Also added a task for running periodic deep dive sessions to debug failing and flaking tests in the CAPI CI.

:book: Release CI tasks: Remove IPv6, add deep dive sessions

---

api/v1beta1/condition_consts.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/machineset/machineset_preflight.go
internal/controllers/machineset/machineset_preflight_test.go

Adds support to surface failing pre-flight checks of a MachineSet on the `MachinesCreated` condition using the `PreflightCheckFailed` reason.
Fixes #

🌱 surface failed preflight checks on MachineSet in `MachinesCreated` condition

---

docs/book/src/tasks/experimental-features/runtime-sdk/deploy-runtime-extension.md
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md

- Add Point for registering the app
- Add an ExtensionConfig Example
This PR enhances the CAPI Book in the Runtime Extension Section. 
Fixes #8679 
/cc @killianmuldoon

📖 Update Runtime Extension CAPI Book

---

docs/book/src/tasks/experimental-features/machineset-preflight-checks.md

This PR updates the documentation of the `MachineSetPreflightChecks` feature gate.
Fixes #8717

📖 update MachineSet PreflightChecks documentation

---

test/infrastructure/docker/controllers/alias.go
test/infrastructure/docker/exp/controllers/alias.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/docker/main.go

CAPD had the command line flag but wasn't actually using it
Fixes #

🐛 CAPD: Implement watch filter

---

hack/observability/.gitignore
hack/observability/grafana/chart/kustomization.yaml
hack/observability/kube-state-metrics/chart/kustomization.yaml
hack/observability/loki/kustomization.yaml
hack/observability/parca/kustomization.yaml
hack/observability/prometheus/kustomization.yaml
hack/observability/promtail/kustomization.yaml
hack/observability/visualizer/kustomization.yaml

🌱 hack/observability: move charts so they are ignored by go mod

---

docs/book/src/reference/jobs.md
test/e2e/quick_start_test.go

Update the e2e jobs doc to reflect the changes made in https://github.com/kubernetes/test-infra/pull/29699 i.e. consolidating dualstack periodics and ipv6 jobs into the same run.

:book: Update e2e jobs list to reflect dualstack + IPv6 consolidation

---

controllers/remote/cluster_cache_tracker.go

This improves the error when a workload cluster is not reachable.
Before
> failed to create remote cluster client: failed to create cluster accessor: error adding index for field "spec.providerID" to cache for remote cluster "default/capi-quickstart": failed to get API group resources: unable to retrieve the complete list of server APIs: v1: client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: EOF
After
> failed to create remote cluster client: failed to create cluster accessor: error creating client for remote cluster "default/capi-quickstart": error getting rest mapping: failed to get API group resources: unable to retrieve the complete list of …

🌱 ClusterCacheTracker: improve error when workload cluster is not reachable

---

docs/release/release-tasks.md

It looks like this step is only relevant for minor releases.
Fixes #
<sub>Johannes Frey <[johannes.frey@mercedes-benz.com](mailto:johannes.frey@mercedes-benz.com)>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

:book: Add minor release prefix for title polishing

---

bootstrap/kubeadm/internal/ignition/clc/clc.go
bootstrap/kubeadm/internal/ignition/clc/clc_test.go

In certain baremetal environment, where there are multiple connected and/or disconnected network ports, the network target is reached more slowly, and the kubeadm.service might fail because it does not have the proper pre-kubeadm commands correctly done (like a ctr image pull) or it cannot connect to other k8s nodes.
Also, kubeadm.service and kubeadm.sh relies to on containerd to be working at that moment too. Please let me know if I need to remove the After=containerd.service part and maybe add this check in another place?

🐛 ignition: start kubeadm after network.target

---

test/infrastructure/inmemory/internal/controllers/goofycluster_controller.go
test/infrastructure/inmemory/internal/controllers/goofymachine_controller.go
test/infrastructure/inmemory/internal/server/api/handler.go
test/infrastructure/inmemory/internal/server/mux.go
test/infrastructure/inmemory/internal/server/mux_test.go

This PR makes the cluster deletion to work when using the in-memory API server; the issue was caused by the node drainer using application/json to delete pods (while the controller runtime client uses protobuf)
Rif https://github.com/kubernetes-sigs/cluster-api/issues/8814

🐛 fix cluster deletion in the in-memory API server

---

hack/tools/release/notes.go

Building on top of @oscr's [original PR](https://github.com/kubernetes-sigs/cluster-api/pull/8343) (all credit to oscar), adding support to handle multiple area labels. I added the changes in a separate commit since the original PR was already reviewed. I'll squash before merge.
Adds support for release notes script to lookup area labels. If found it uses the area tag for prefix. Otherwise it uses `MISSING_AREA` meaning it needs manual update.
If multiple area labels are found, it uses `MULTIPLE_AREAS[area1|area2...]`.
It also sorts each section alphabetically.
<details>
<summary>Example</summary>
```
> go run hack/tools/release/notes.go --from=v1.4.0
Changes since v1.4.0
---
- 192 new commits merged
- 3 breaking changes :warning:
- 9 feature …
```

🌱 Add area label lookup for prefixes to release notes tool

---

api/v1beta1/condition_consts.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/controllers/topology/cluster/scope/hookresponsetracker.go
internal/controllers/topology/cluster/scope/hookresponsetracker_test.go
internal/controllers/topology/cluster/scope/upgradetracker.go

This PR modified the topology controller so that it modified pushing any changes to ControlPlane/MachineDeployment if it is pending an upgrade.
If a ControlPlane or MD is pending an upgrade it implies that it will be rollouts after it picks up the upgrade. Therefore it is better to hold out other changes, potentially causing rollouts, to these objects as well in the mean time to avoid unnecessary machine churn.
Fixes #8656
Fixes #8695

🐛 topology controller should avoid unnecessary rollouts during upgrades

---

api/v1beta1/machine_webhook_test.go
api/v1beta1/machinedeployment_webhook_test.go
api/v1beta1/machinehealthcheck_webhook_test.go
api/v1beta1/machineset_webhook_test.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook_test.go
bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_webhook_test.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_webhook_test.go
exp/addons/api/v1beta1/clusterresourceset_webhook_test.go
exp/addons/api/v1beta1/clusterresourcesetbinding_webhook_test.go
exp/api/v1beta1/machinepool_webhook_test.go
exp/ipam/internal/webhooks/ipaddress_test.go
exp/ipam/internal/webhooks/ipaddressclaim_test.go
internal/webhooks/cluster_test.go
internal/webhooks/runtime/extensionconfig_webhook_test.go
test/infrastructure/docker/api/v1beta1/dockerclustertemplate_webhook_test.go
test/infrastructure/docker/api/v1beta1/dockermachinetemplate_webhook_test.go
util/defaulting/defaulting.go

**What this PR does / why we need it**: To validate the warnings in webhook unit tests
Fixes #8732

🌱 Validating the warnings in tests

---

docs/book/src/tasks/experimental-features/runtime-sdk/implement-lifecycle-hooks.md

This PR updates the Lifecycle Hooks documentation to document the updated affects of blocking an upgrade using the blocking hooks.
Fixes #

📖 update lifecycle hooks documentation with new upgrade rules

---

controllers/external/tracker.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machine/machine_controller_phases_test.go

This PR removes requeues in places where we already watch objects.
E.g. we don't have to requeue if the BootstrapConfig is not ready, because an update on a BootstrapConfig automatically triggers a reconcile (because we have a watch on BootstrapConfigs).
There should be no problems with stale caches after updates because we don't cache unstructured.
Fixes #8735

🌱 Remove unnecessary requeues

---

bootstrap/kubeadm/controllers/alias.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/kubeadm/main.go
controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/main.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_noderef.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/machineset/machineset_controller.go
main.go
test/infrastructure/docker/main.go

We still had a few places left where we created clients for the workload cluster via `NewClusterClient` instead of using ClusterCacheTracker. This PR replaces the last usages of `NewClusterClient`.
I expect that it's more efficent to use a cached client vs re-creating it all the time
Fixes #

🌱 Use ClusterCacheTracker consistently (instead of NewClusterClient)

---

cmd/clusterctl/client/config.go
cmd/clusterctl/client/config/client.go
cmd/clusterctl/client/config/reader_viper.go
cmd/clusterctl/client/config/reader_viper_test.go
cmd/clusterctl/client/repository/overrides.go
cmd/clusterctl/client/repository/overrides_test.go
cmd/clusterctl/cmd/config_repositories.go
cmd/clusterctl/cmd/config_repositories_test.go
cmd/clusterctl/cmd/generate_cluster.go
cmd/clusterctl/cmd/init.go
cmd/clusterctl/cmd/root.go
cmd/clusterctl/cmd/version_checker.go
cmd/clusterctl/cmd/version_checker_test.go
cmd/clusterctl/hack/create-local-repository.py
docs/book/src/clusterctl/commands/additional-commands.md
docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/configuration.md
docs/book/src/clusterctl/developers.md
docs/book/src/tasks/experimental-features/experimental-features.md
docs/book/src/user/troubleshooting.md
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

**What this PR does / why we need it**: This PR switches the hardcoded paths (`$HOME/.cluster-api`) to be [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) conform (`$XDG_CONFIG_HOME/cluster-api`).
This removes clutter in the users' home directory.
Open questions:
- I tried adding backwards compatibility to the old path inside the `reader_viper.go` but I'm not sure if this works for everything
- The script `cmd/clusterctl/hack/create-local-repository.py` creates a `dev-repository` at `$HOME/.cluster-api/dev-repository`. I see three solutions to this;
- The script uses an [xdg library](https://github.com/srstevenson/xdg), which has to be installed on the users' system, which we'll mention in the docs
- The script does everything by itself, without needing …

:warning: Follow XDG Directory standard for config/data/... files

---

Makefile
test/infrastructure/inmemory/Dockerfile

Fixes the bug in the current make target that builds the in-memory infrastructure provider.
The current bug: It builds the wrong image. It rebuild the cluster-api-controller-manager image.
Fixes #

🐛 fix inmemory provider docker build

---

cmd/clusterctl/hack/create-local-repository.py
docs/book/src/clusterctl/developers.md
docs/book/src/user/quick-start.md
docs/book/src/user/troubleshooting.md

Some additional doc fixes pointing toward the new XDG_CONFIG_HOME default location for clusterctl configuration.
Related to #6913

:book: Small doc fixes for XDG_CONFIG_HOME

---

controllers/remote/cluster_cache_tracker.go

Check if the clusterCacheTracker is running on the workload cluster using an uncached client. Previously Pods were being cached by the controller runtime client which could cause unnecessarily high memory usage.

:bug: ClusterCacheTracker: Stop pod caching when checking workload cluster

---

test/e2e/cluster_upgrade_runtimesdk.go
test/framework/machineset_helpers.go

🌱 add E2E test for MachineSet Preflight checks

---

docs/proposals/20220927-label-sync-between-machine-and-nodes.md
docs/proposals/20221003-In-place-propagation-of-Kubernetes-objects-only-changes.md

Fix formatting errors in yaml block for label sync and metadata propagation proposals.

:book: Fix formatting error on proposals

---

hack/tools/release/notes.go

Now that we retrieve the area labels from the PRs, the release notes generation can take up to 2 minutes for big releases like 1.5. Although in general this is not a problem since it should be a one time process, it does slow down the comms release team when iterating in the notes, adding missing labels, etc. It also makes development of the script painful when testing it manually.
The default is 10 concurrent routines, but this can be changed with command flag.
The default value of 10 doesn't seem to run into rate limiting problems. I had to bump it to a 100 and run the command multiple times in a row to be able to get rate limited.

🌱 Make release notes generation concurrent

---

bootstrap/kubeadm/main.go
controllers/remote/cluster_cache_healthcheck_test.go
controllers/remote/cluster_cache_tracker_test.go
controllers/remote/index.go
controlplane/kubeadm/internal/cluster_test.go
controlplane/kubeadm/main.go
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
internal/controllers/cluster/suite_test.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/suite_test.go
main.go
test/infrastructure/docker/main.go

Deprecate the `remote.DefaultIndex` due to confusing naming and replace its current valid usages with `[]Index{NodeProviderIDIndex}` instead.
Remove the use of the index entirely from places where it is not currently used: 
- CAPD
- CAPBK
- KCP

:seedling: Deprecate DefaultIndex usage and remove where not needed

---

hack/tools/release/notes.go

A few life of quality improvements that automate manual steps performed to cleanup the release notes:
* Capitalize/shorten some area labels into more legible prefixes (API vs api, KCP vs provider/kubeadm-control-plane...)
* Remove backport PR prefixes "[release-x.x]"
* Omit "num of change of type x" lines when there are no changes of
that kind (eg. no breaking changes)
* Use the area label for `documentation` to classify PRs that have the wrong emoji prefix in the title. We have seen in the past PR that use the 🐛 or 🌱 instead of 📖 , but they have the `area/documentation` label. In these cases, the label tends to be more reliable than the PR title, so this PR makes the label take precedence.
I put the last item in a separate commit, since we weren't …

🌱 Improve release notes formatting

---

controlplane/kubeadm/internal/workload_cluster_conditions.go

Looks like this issue doesn't occur with the real etcd server, but with the in-memory provider. I would adjust this in KCP regardless as I think KCP should not panic if the etcd server provides wrong data.
Fixes #

🌱 KCP: avoid panic if etcd server misbehaves

---

controlplane/kubeadm/internal/control_plane.go

The patchHelpers map gets initially build in NewControlPlane based on the passed in ownedMachines.
During the reconcile we update the map via SetPatchHelpers. Unfortunately the new map is missing patchHelpers for Machines with a deletionTimestamp. Later on when we want to patch all machines we cannot patch the Machines with deletionTimestamp because we dropped the patchHelpers for them.
This PR changes SetPatchHelper so it only updates the necessary patchHelpers and doesn't drop any.
Fixes #

🌱 KCP: fix noisy error log triggered by missing patch helper

---

scripts/ci-e2e-lib.sh

Working on fixing errors from the release of KIND v0.20.0 - more information here: https://github.com/kubernetes-sigs/cluster-api/issues/8815
This PR ensures images are always built for CAPI e2e tests.

:bug: Always build Kind images for upgrade tests

---

scripts/ci-e2e-lib.sh

Issue introduced in #8859 due to the use of a potentially unbound variable in the bash script. This variable should default to false if unset in the variables passed in to the script.

:bug: Ensure ALWAYS_BUILD_KIND_IMAGES is defaulted correctly in ci script

---

test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go

This PR changes the in-memory provider to set the providerID already after the VM is provisioned not after the Node is ready.
Fixes #

🐛 test/e2e/in-memory: set providerID after VM is provisioned

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Update cert manager to v1.12.2.
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.2

:seedling: Update cert-manager to v1.12.2

---

scripts/ci-test.sh
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
test/infrastructure/inmemory/internal/server/mux.go
test/infrastructure/inmemory/internal/server/mux_test.go
test/infrastructure/inmemory/main.go

This PR contains https://github.com/kubernetes-sigs/cluster-api/pull/8879 + enable tests
Kudos to @fabriziopandini for the second half of the implementation :)
Fixes #

🌱 test/e2e/in-memory: enable unit tests

---

.gitignore
test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml

🌱 test/e2e/in-memory: sync in-memory provider ClusterClass with test

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/util/configowner.go
bootstrap/util/configowner_test.go
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md

**What this PR does / why we need it**: This PR makes the lookup of the KubeadmConfig's owner use a cached client instead of the uncached unstructured client. To make the rest of the adjacent plumbing reusable, the new typed read by `GetOwnerByRefCached` converts the object into `Unstructured` to construct a `ConfigOwner`.
Fixes #8849

:sparkles: Use caching read for bootstrap config owner

---

test/infrastructure/inmemory/internal/cloud/runtime/cache/cache.go
test/infrastructure/inmemory/internal/cloud/runtime/cache/client.go
test/infrastructure/inmemory/internal/cloud/runtime/cache/client_test.go
test/infrastructure/inmemory/internal/cloud/runtime/cache/informer.go
test/infrastructure/inmemory/internal/cloud/runtime/controller/controller_test.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
test/infrastructure/inmemory/internal/server/api/handler.go
test/infrastructure/inmemory/internal/server/api/watch.go
test/infrastructure/inmemory/internal/server/listener.go
test/infrastructure/inmemory/internal/server/mux_test.go

Add watch to the CAPI in-memory provider's API server. This will allow the in-memory apiserver to deliver watch events when CAPI is watching resources like nodes on the workload cluster.
Part of #8814

:seedling: Add watch to in-memory server multiplexer

---

test/infrastructure/inmemory/internal/server/certs.go
test/infrastructure/inmemory/internal/server/mux.go

Currently the in-memory provider gets slow if we're getting to very high cluster numbers.
Basically the problem was that when we create a new apiserver we locked the global lock. This was slowing down all requests served by the apiserver because that lock is used during every tls handshake and in every request (to get the resourceGroup).
Kudos to @fabriziopandini for the collaboration on this.
Related to #8814

🌱 test/e2e/in-memory: improve performance by fixing locking issues

---

test/infrastructure/inmemory/internal/cloud/runtime/cache/client.go
test/infrastructure/inmemory/internal/server/api/handler.go
test/infrastructure/inmemory/internal/server/api/watch.go

Has a number of small improvements following on from reviews of #8851.
Related to #8814

:seedling: Fixups for watch in in-memory apiServer

---

controlplane/kubeadm/internal/cluster.go
controlplane/kubeadm/internal/cluster_test.go
internal/controllers/machine/machine_controller.go

🌱 Use rest config from ClusterCacheTracker consistently

---

test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/extension/handlers/topologymutation/handler.go
test/infrastructure/container/docker.go
test/infrastructure/container/interface.go
test/infrastructure/docker/exp/internal/docker/nodepool.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/docker/internal/docker/manager.go
test/infrastructure/docker/internal/docker/manager_test.go
test/infrastructure/kind/mapper.go
test/infrastructure/kind/mapper_test.go

CAPD doesn't have direct dependencies from Kind, however, it is using kindest/node images.
As a consequence CAPD must stay in sync with Kind with regards to how kindest/node images are run when creating a new DockerMachine.
kindest/node images are created using a specific Kind version, and thus it is required to keep into account the mapping between the Kubernetes version for a kindest/node and the Kind version that created that image, so we can run it properly.
This PR implements this mapping and use it to pick the right image to use and to start this image as expected.
Fixes #

🐛 Add kind mapper

---

test/README.md
test/infrastructure/inmemory/README.md

Fix readme for the in-memory provider

🌱 fix readme for in-memory provider

---

test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
test/infrastructure/inmemory/internal/server/api/const.go
test/infrastructure/inmemory/internal/server/api/handler.go
test/infrastructure/inmemory/main.go
test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml

Enable the CAPIM to respond to calls to update coreDNS and kube-proxy.
Part of #8814

:seedling: CAPIM: Enable update for coreDNS and kube-proxy

---

Tiltfile
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Update KIND to v0.20.0. 
Release notes: https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
There was some changes in the `kindest/node` build process in this release which caused additional work to adopt it. See more under issue #8788.
Fixes #8788

:seedling: Update KIND to v0.20.0

---

test/infrastructure/inmemory/internal/cloud/api/v1alpha1/etcdcluster_annotations.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
test/infrastructure/inmemory/internal/server/etcd/handler.go
test/infrastructure/inmemory/internal/server/mux_test.go

This PR improves etcd management in CAPIM, so it handles properly more than one control plane / etcd member joining the cluster
cc @ykakarap @killianmuldoon @sbueringer

🌱 Improve etcd management in CAPIM

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/status.go
controlplane/kubeadm/internal/controllers/status_test.go
controlplane/kubeadm/internal/controllers/suite_test.go
controlplane/kubeadm/internal/controllers/upgrade.go
controlplane/kubeadm/internal/controllers/upgrade_test.go

As of today, KCP creates the workloadCluster internal struct several times during every reconciliation, and this is one of the factors slowing down reconciliation duration in a way that can impact performance at scale.
This PR refactor KCP so only one workloadCluster internal struct is going to be created and re-used all around during the same reconcile
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8814

🌱 Kcp use one workload cluster for reconcile

---

controlplane/kubeadm/internal/etcd/etcd.go
controlplane/kubeadm/internal/etcd_client_generator.go
controlplane/kubeadm/internal/etcd_client_generator_test.go

This PR changes endpoints to endpoint in the etcd client, and also adds a comment making it clear how this parameter is used internally by the dialer
cc @sbueringer

🌱 Change endpoints to endpoint in the etcd client

---

controllers/alias.go
internal/controllers/cluster/suite_test.go
internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_noderef_test.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machine/machine_controller_phases_test.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/suite_test.go
main.go

I think we can cache all our get calls with unstructured in the Machine controller. This leads to huge performance improvements at scale (an average Machine reconcile goes from ~ 1 second to double digits milliseconds).
Most of this PR is just updating the tests.
While it could happen that a Machine reconcile is seeing stale BootstrapConfigs / InfraMachines, based on experiments and upstream documentation for every update on BootstrapConfig / InfraMachine we will get another Machine reconcile. During that reconcile the BootstrapConfig / InfraMachine will have been already updated in the cache.
This is the case because Kubernetes informers always first update the cache before they notify event …

🌱 controller/machine: use unstructured caching client

---

test/infrastructure/kind/mapper.go

Fixes a wrong entry in kind mapper and by that it fixes the broken tests for `capi-e2e-main-1-24-1-25`  and `capi-e2e-main-1-25-1-26`.
Follow-up for #8880
Fixes #

🐛 test/capd: fix kind mapper entry for v1.25.11

---

controlplane/kubeadm/internal/controllers/scale.go

This check is redundant as we already check this before:
* Reconcile calls initControlPlaneScope which stores the owned machines in control plane
* initializeControlPlane is then only called if the number of (owned) machines is 0
Fixes #

🌱 KCP: drop redundant get machines

---

bootstrap/kubeadm/types/utils.go
bootstrap/kubeadm/types/utils_test.go
docs/book/src/clusterctl/commands/alpha-topology-plan.md
docs/book/src/tasks/bootstrap/kubeadm-bootstrap.md
docs/book/src/tasks/experimental-features/ignition.md
test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/bases/md.yaml
test/e2e/data/infrastructure-docker/main/bases/mp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-ignition/ignition.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/go.mod
test/infrastructure/docker/exp/internal/docker/nodepool.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/docker/internal/provisioning/cloudinit/adapter.go
test/infrastructure/docker/internal/provisioning/cloudinit/adapter_test.go
test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go
test/infrastructure/docker/internal/provisioning/cloudinit/unknown.go
test/infrastructure/docker/internal/provisioning/cloudinit/unknown_test.go
test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go
test/infrastructure/docker/internal/provisioning/cloudinit/writefiles_test.go
test/infrastructure/docker/templates/clusterclass-quick-start.yaml

This PR uses the kind mapper introduced by https://github.com/kubernetes-sigs/cluster-api/pull/8880, and use it to automatically set some parameters in the node registration, so the kindest/node image are started as expected.
Fixes #

🌱 Automatically set kubelet args for capd

---

controllers/alias.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/cluster/cluster_controller_phases.go
internal/controllers/cluster/cluster_controller_phases_test.go
internal/controllers/cluster/cluster_controller_test.go
internal/controllers/cluster/suite_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/machineset/machineset_preflight.go
internal/controllers/machineset/machineset_preflight_test.go
internal/controllers/machineset/suite_test.go
internal/test/envtest/environment.go
main.go

For similar reasons as in #8896 and in #8913 we can also cache unstructured in the Cluster, MD and MS controllers
Fixes #

🌱 Cache unstructured in Cluster, MD and MS controller

---

Tiltfile
hack/tools/tilt-prepare/main.go

🐛 tilt: set CR logger in tilt-prepare, fix allowed contexts

---

controlplane/kubeadm/controllers/alias.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go
controlplane/kubeadm/main.go

In KCP we only ever use unstructured to get InfraMachine and InfraMachineTemplate. In both cases it absolutely does not matter if the object is stale:
* We only use InfraMachine to:
* check via the template annotations if we have to rollout. The annotations never change.
* as original object before we apply labels/annotations. Doesn't matter if it is slightly stale there (we also use SSA)
* We only use InfraMachineTemplate to set an ownerRef
Fixes #

🌱 KCP: cache unstructured

---

cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/cluster/objectgraph_test.go
cmd/clusterctl/client/tree/discovery.go
cmd/clusterctl/client/tree/discovery_test.go
cmd/clusterctl/internal/test/fake_objects.go

if a cluster as an empy bootstrap.configref in the machinedeployment (which is allowed), a nil pointer will raise if clusterctl describe cluster is called with --show-templates.
Also add a second type of a fake machinedeployment which has a secret reference in the boostrap object instead of a config ref
```
/*
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x19478c0]
goroutine 1 [running]:
sigs.k8s.io/cluster-api/cmd/clusterctl/client/tree.ObjectReferenceObject(0x0)
sigs.k8s.io/cluster-api/cmd/clusterctl/client/tree/util.go:116 +0x40
sigs.k8s.io/cluster-api/cmd/clusterctl/client/tree.addMachineDeploymentToObjectTree({0x2153e90, 0xc000120008}, {0x215ebf8, …
```

🐛 handle nil pointer in clusterctl describe

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Fix the deprecation marker for Cluster `.spec.Topology.RolloutAfter` so it is correctly picked up by go tooling. Deprecation markers should always be in a new paragraph block in the godoc comment.
I went through all of our deprecation markers and this was the only one I found that didn't meet the standard.

:bug: Fix deprecation marker for RolloutAfter

---

internal/controllers/topology/cluster/current_state.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go

Related https://github.com/kubernetes-sigs/cluster-api/issues/8814

🌱 cluster/topology: use cached MD list in get current state

---

exp/internal/controllers/machinepool_controller_phases_test.go

Add an eventually to the test `Should delete retired nodes when scaled to zero` for the MachinePool reconciler. This started flaking recently, likely due to changes in the use of the clusterCacheTracker in this reconciler.

:bug: Use CreateAndWait in MP ScaleFromZero test

---

hack/tools/tilt-prepare/main.go

🌱 hack/observability: skip preload images on non-kind clusters

---

test/e2e/config/docker.yaml
test/e2e/scale.go
test/e2e/scale_test.go
test/framework/namespace_helpers.go

This PR adds the following improvements to the scale E2E test:
- ability to set MachineDeployment count
- ability to skip clean up
- ability to skip waiting for cluster creation
- always use the same namespace for scale testing (this is primarily for the benefit of easy debuggability)
Fixes #

🌱 add improvements to scale e2e

---

test/e2e/scale.go
test/framework/clusterctl/clusterctl_helpers.go

We ran into some issues during scale tests where 10 seconds wasn't enough. let's increase this slightly.
Fixes #

🌱 test/e2e: increase apply timeout to 1m

---

internal/controllers/machinedeployment/suite_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/machineset_controller_test.go

This PR adds the `MachineFinalizer` during calculation of the `Machine` object so the finalizer is set on object creation.
Fixes #8172

🌱 add MachineFinalizer during machine computation

---

internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/cluster/reconcile_state.go

Basically the same optimization as in #8922. More information in the added godoc
Related https://github.com/kubernetes-sigs/cluster-api/issues/8814

🌱 cluster/topology: use cached Cluster get in Reconcile

---

test/infrastructure/inmemory/internal/server/api/handler.go
test/infrastructure/inmemory/internal/server/api/watch.go
test/infrastructure/inmemory/internal/server/etcd/handler.go

I consistently hit deadlocks when running a scale test with 40 clusters and 50 Machines per cluster.
Fixes #

🌱 test/e2e/in-memory: improve locking, return errors instead of panic

---

Tiltfile
docs/book/src/developer/tilt.md
hack/observability/metrics-server/kustomization.yaml
hack/observability/metrics-server/values.yaml

🌱 hack/observability: add metrics-server chart

---

controlplane/kubeadm/internal/controllers/controller.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/cluster/cluster_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockercluster_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go

As reported in https://github.com/kubernetes-sigs/cluster-api/issues/8946 Cluster API today tries to add a finalizer even if objects already has a deletionTimestamp set.
This results in the following error message from the APIserver:
>  "Reconciler error" err="Cluster.cluster.x-k8s.io \"sgcluster\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"cluster.cluster.x-k8s.io\"}" 
This case especially occurs if a finalizer of another controller is removed after our finalizer.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

🐛 all: only set finalizers if deletionTimestamp is not set

---

config/crd/bases/cluster.x-k8s.io_machinepools.yaml
exp/api/v1beta1/machinepool_types.go

Add a comment about the current status of the implementation of MinReadySeconds on the MachinePool. This field currently has no behaviour and should be documented as such.

:book: Add comment about MachinePool MinReadySeconds behaviour

---

hack/observability/prometheus/values.yaml

Increases the storage for Prometheus. I regularly hit "no space left on device" in scale tests with the current 8 Gi default
Fixes #

🌱 hack/observability: use 20 Gi of storage for Prometheus

---

docs/book/src/tasks/automated-machine-management/healthchecking.md

"If unhealthyRange is set to [3-5] and there are 10 Machines being checked".
It should: **6** or more nodes are unhealthy, remediation will not be performed
Reference Code:
```go
// isAllowedRemediation checks the value of the MaxUnhealthy field to determine
// returns whether remediation should be allowed or not, the remediation count, and error if any.
func isAllowedRemediation(mhc *clusterv1.MachineHealthCheck) (bool, int32, error) {
var remediationAllowed bool
var remediationCount int32
if mhc.Spec.UnhealthyRange != nil {
min, max, err := getUnhealthyRange(mhc)
if err != nil {
return false, 0, err
}
unhealthyMachineCount := unhealthyMachineCount(mhc)
remediationAllowed = unhealthyMachineCount >= min && unhealthyMachineCount <= max …
```

📖 Fix description of example values for MHC unhealthy ranges

---

controllers/alias.go
internal/controllers/machine/machine_controller.go
main.go

Allows configuring the kubernetes client configuration timeout used by the machine controller when draining nodes.
Fixes #8864

:sparkles: Enable configuring the kubernetes rest client timeout for draining nodes

---

docs/book/src/SUMMARY.md
docs/book/src/developer/architecture/controllers/tuning.md

This PR wraps up lessons learned while working on https://github.com/kubernetes-sigs/cluster-api/issues/8814, capturing also some notes about where we are and what we are still missing in our setup for allowing follow-up iterations on performance tuning.

📖 Add tuning guide

---

test/e2e/clusterctl_upgrade.go
test/e2e/self_hosted.go

🌱 test/e2e: improve logging for a detected rollout

---

Tiltfile

Following aa18c06 the podman detection has been moved below the `default_build_engine` variable usage,
breaking podman support.
This fix podman support by setting the `build_engine` directly instead of using a `default_build_engine` variable.
Fixes #

🐛 tilt: fix build_engine setting when using podman

---

test/framework/bootstrap/kind_provider.go

This image bump was missed in the process of bumping the KIND version to `v0.20.0` in https://github.com/kubernetes-sigs/cluster-api/pull/8908
Related slack thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1688679227454029

[release-1.4] :bug: Bump kindest/node image used in e2e tests

---

test/framework/bootstrap/kind_provider.go

Add a SHA to the default KIND image used for bootstrapping a cluster for the e2e tests. 
Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8974#discussion_r1255433718

:seedling: Add SHA to default KIND image used in e2e tests

---

test/e2e/scale.go

🌱 test/e2e: add field to scale test to deploy Clusters in separate namespace

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

This PR extends KCP to also log the reason why we trigger a rollout.
Would be nice if it could make it into the release, but if it doesn't it's okay :)
Fixes #5557

🌱 KCP: Log the reason of a Machine rollout

---

internal/topology/check/compatibility.go
internal/topology/check/compatibility_test.go
internal/webhooks/cluster.go
internal/webhooks/cluster_test.go

Add a warning in the Cluster webhook when the Cluster references a Cluster class which either does not exist or has not been successfully reconciled.
Warnings were added as a webhook feature in #8007.
Fixes #8496

:sparkles: Add webhook warning for missing ClusterClass

---

Tiltfile
docs/book/src/developer/tilt.md

This PR makes sure that if you are using tilt up without a local registry, you can't accidentally push to well know repository like our staging repo
cc @sbueringer

🌱 Protect well know registry from accidental push during tilt up

---

hack/observability/grafana/dashboards/cluster-api-mgmt-apiserver-requests.json
hack/observability/grafana/dashboards/cluster-api-wl-apiserver-requests.json
hack/observability/grafana/kustomization.yaml

This PR adds dashboards for workload & management cluster apiserver requests.
This should be the last PR for dashboards for now :)
Related to #8814

🌱 hack/observability: add apiserver request dashboards

---

api/v1beta1/machine_types.go
cmd/clusterctl/client/tree/discovery.go
cmd/clusterctl/client/tree/discovery_test.go
cmd/clusterctl/internal/test/fake_objects.go

**What this PR does / why we need it**: Allow clusterctl discovery to find MachinePool Machines and associated infraMachines.
Fixes #4063

✨ Add MachinePool Machine support in clusterctl discovery

---

cmd/clusterctl/OWNERS

This behaviour of automatically adding a code area based on the OWNERs file is not a great solution as it exists for release notes.
We should revisit automating these labels in a more holistic way, but for now this should be removed.

:seedling: Remove auto-labelling for clusterctl

---

controlplane/kubeadm/internal/controllers/controller_test.go

To stay in sync with the changes we do at #8991 and prevent regressions for #8989
Fixes #

🌱 controlplane: add a test case for syncMachines where the InfraMachine does not exist.

---

util/patch/patch.go

Extend docs for patch.NewHelper
It took me some time to understand why my first usage if the handy patch helper did not work.
You need to give NewHelper the original (unchanged) object.
I hope this PR makes it more obvious for the newcomer.

:seedling: Extend docs for patch.NewHelper

---

api/v1beta1/machineset_webhook.go
controlplane/kubeadm/internal/cluster_labels.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/machineset/machineset_controller.go
util/labels/format/helpers.go
util/labels/format/helpers_test.go

**What this PR does / why we need it**: We need `capilabels.MustFormatValue()` to be available for providers implementing MachinePool Machines.
Fixes #

🌱 Move `internal.labels` to `format` package for use by providers

---

docs/release/release-team.md
docs/release/releases/release-1.6.md

Fix role names in the release docs to align with current naming.
`Shadows` -> `Team members`
`Release writer` -> `Maintainer`
Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8988#discussion_r1267345341

:book: Fix role names in release docs

---

docs/book/src/clusterctl/commands/move.md

The details of "clusterctl move" are in the provider contract. A link to that helps new users.

:book: Add link to "clusterctl move" docs.

---

hack/tools/release/notes.go

Ensures the release note tool can again be used by other projects (in my case CAPV)
Fixes #

🐛 hack/release-notes: ensure relase notes tool can be used for external projects again

---

controllers/remote/cluster_cache_tracker.go

🌱 ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable

---

docs/release/release-tasks.md

🌱 Add more links to release-tasks doc

---

controllers/remote/cluster_cache_tracker.go

Part of #8948 (should fix the issue for main and release-1.5)

🌱 ClusterCacheTracker: fix accessor deletion on health check failure

---

controllers/remote/cluster_cache_tracker.go

[release-1.4] :seedling: ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable

---

controllers/remote/cluster_cache_tracker.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9028
Fixes #

[release-1.3] 🌱 ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable

---

controlplane/kubeadm/internal/controllers/controller.go

When the cluster is in the state that:
* The KCP in general is ready and
* All its conditions exist and are true, except the `ControlPlaneComponentsHealthyCondition` and
* KCP reconciles and has a no-op
Then the controller does reach the end of the `reconcile` function and does a `return ctrl.Result{}, nil`.
At the time of the relevant workload pods (etcd, kube-apiserver, kube-controller-manager, kube-scheduler) getting ready and reporting their ready state inside the workload cluster, no new additional event gets injected for the KCP object.
The KCP controller has to wait for an different change to the watched objects, or to reach the resync period to mark the condition to true.
This delays provisioning when the preflight checks for MachineSets are …

:bug: requeue KCP object if ControlPlaneComponentsHealthyCondition is not yet true

---

.github/dependabot.yml

Enable dependabot for the `hack/tools` and `test` go modules.
Dependabot needs to be pointed to each directory holding a go module seperately. Previously we got updates to some dependencies in these files due to our dependeabot go generation job which runs `go mod tidy` on all modules.
Fixes #

:seedling: Add dependabot for test and hack/tools module

---

hack/tools/release/notes.go

**What this PR does / why we need it**: fixed grammatically incorrect plurals in release tools as stated in #9009 
Fixes #9009

🌱 fixed grammatically incorrect plurals in release tools

---

docs/release/release-tasks.md

- Adds a note to the `mailing-list` step of `#### Continuously: Communicate key dates to the community` task.

📖 add a note to check with maintainers for blocked comms emails

---

Makefile
Tiltfile
hack/ensure-go.sh

Let's bump to Go 1.20.6 ahead of the release
Changelog:
> go1.20.5 (released 2023-06-06) includes **four security fixes** to the cmd/go and runtime packages, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/rsa, net, and os packages. See the [Go 1.20.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.20.5+label%3ACherryPickApproved) on our issue tracker for details.
> 
> go1.20.6 (released 2023-07-11) includes a **security fix** to the net/http package, as well as bug fixes to the compiler, cgo, the cover tool, the go command, the runtime, and the crypto/ecdsa, go/build, go/printer, net/mail, and text/template packages. See the [Go 1.20.6 …

🌱 Bump to Go 1.20.6

---

.github/dependabot.yml

Add an exclude to the dependabot configuration for `sigs.k8s.io/kustomize/api`. Bumping the kustomize API independently can break compatibility with client-go as they share `k8s.io/kube-openapi` as a dependency.
Related to https://github.com/kubernetes-sigs/cluster-api/pull/9049

:seedling: Add exclude for Kustomize API to dependabot config

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Bump docker/docker to version v24.0.5
Release Notes: https://github.com/moby/moby/releases/tag/v24.0.5
This is the first full release that fixes https://github.com/kubernetes-sigs/cluster-api/issues/9037 which was previously fixed by bumping to a commit.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9037

:seedling: Bump docker to v24.0.5

---

Tiltfile

Change the base image used in the Tiltfile for debug images to golang. This change fixes an error with the output:
```
/dlv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /dlv)
/dlv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /dlv)
```
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9070

[release-1.4] :seedling: Change tilt debug base image to golang

---

Tiltfile

Change the base image used in the Tiltfile for debug images to golang. This change fixes an error with the output:
```
/dlv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /dlv)
/dlv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /dlv)
```
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9070

[release-1.3] :seedling: Change tilt debug base image to golang

---

docs/book/src/user/quick-start.md

Updates clusterctl version to v1.5.x in quickstart.

:book: update clusterctl version to v1.5.x in quick start

---

docs/book/src/developer/architecture/controllers/control-plane.md
docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md

Sharing the new required labels for Secret objects generated by a Control Plane provider.
Fixes #9079

📖 Control Plane resources required label from v1.5.0

---

docs/release/releases/release-1.6.md

- Fixes formatting issues in the table
- adds v1.6 Release Team members GitHub/Slack handles in an alphabetical order
Fixes #

📖 Add v1.6 Release Team members' GitHub/Slack handles

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
docs/book/src/developer/logging.md
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
main.go
test/extension/main.go
test/infrastructure/docker/main.go
test/infrastructure/inmemory/main.go

🌱 Change default log level to 2

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry-pick of #9121
Semi-automated via:
```
function bump() { go mod edit -require golang.org/x/net@v0.13.0 && go mod tidy }
bump; cd hack/tools; bump; cd ../../test; bump; cd ..;  git commit -m "Bump golang.org/x/net to v0.13.0"
```
This bumps golang.org/x/net to v0.13.0 to address vulnerability GO-2023-1988.
We're not affected (according `govulncheck`) but after some time trivy may report the vulnerability so we bump better now and prior to get to that point.
More info: https://pkg.go.dev/vuln/GO-2023-1988
Fixes #

[release-1.5] 🐛 Bump golang.org/x/net to v0.13.0

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Semi-automated via:
```
function bump() { go mod edit -require golang.org/x/net@v0.13.0 && go mod tidy }
bump; cd hack/tools; bump; cd ../../test; bump; cd ..;  git commit -m "Bump golang.org/x/net to v0.13.0"
```
This bumps golang.org/x/net to v0.13.0 to address vulnerability GO-2023-1988.
We're not affected (according `govulncheck`) but after some time trivy may report the vulnerability so we bump better now and prior to get to that point.
More info: https://pkg.go.dev/vuln/GO-2023-1988
Fixes #

🐛 Bump golang.org/x/net to v0.13.0

---

bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
main.go
test/infrastructure/docker/main.go

Adds a separate flag `--clustercache-tracker-concurrency` to allow adjusting the concurrency of the created cluster cache tracker to all relevant executables: CAPI, CAPBK, KCP, CAPD.
This came up while adding the clustercache tracker to CAPV in [this discussion](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2132#discussion_r1282677508).
Before this PR the other concurrency flags got re-used to also set the concurrency for the clustercache tracker.
Example from @sbueringer why this change makes sense:
> Let's make an example. You have a mgmt cluster with 2k+ workload clusters. The cluster controller is doing some heavy lifting so you would want to use more workers (for 2k 10 should be still fine but it's just an example :D).
> …

🌱 Add separate concurrency flag for cluster cache tracker

---

cmd/clusterctl/cmd/root.go

🌱 Set controller-runtime logger for clusterctl

---

api/v1beta1/cluster_types.go
api/v1beta1/clusterclass_types.go
api/v1beta1/groupversion_info.go
api/v1beta1/machine_types.go
api/v1beta1/machinedeployment_types.go
api/v1beta1/machinedeployment_webhook_test.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/machineset_types.go
docs/book/src/developer/providers/implementers-guide/create_api.md
internal/test/builder/builders.go

To work towards #9011, we need to remove the reliance on controller-runtime from the API packages.
This updates the scheme building methods in the core v1beta1 API group to rely only on API machinery types and not controller runtime types.
Fixes #

🌱 Remove reliance on controller-runtime scheme builder

---

hack/observability/kube-state-metrics/crd-config.yaml
hack/observability/kube-state-metrics/metrics/machine.yaml

Adds a gauge metric to our kube-state-metrics configuration for exposing a machines `.status.certificatesExpiryDate`.
Fixes #9019

🌱 hack/observability: add capi_machine_status_certificatesexpirydate metric

---

api/v1beta1/cluster_types.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml

Adds a ClusterClass column to the Cluster CRD. Super helpful to determine if a Cluster is a classy cluster, and if yes which ClusterClass it uses
```bash
k get clusterclass,cluster,kcp,md
NAME                                        AGE
clusterclass.cluster.x-k8s.io/quick-start   5m44s
NAME                                       CLUSTERCLASS   PHASE         AGE     VERSION
cluster.cluster.x-k8s.io/capi-quickstart                  Provisioned   5m50s
cluster.cluster.x-k8s.io/my-cluster        quick-start    Provisioned   5m41s   v1.26.0
NAME                                                                              CLUSTER           INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED …
```

🌱 Add ClusterClass column to Cluster CRD

---

test/infrastructure/container/docker.go

Follow-up after discussions at https://github.com/kubernetes-sigs/cluster-api/pull/9125#discussion_r1286033049
Log would now look like e.g.:
```
[error starting container "clusterctl-upgrade-oh686r-control-plane-6hdqw": Error response from daemon: driver failed programming external connectivity on endpoint clusterctl-upgrade-oh686r-control-plane-6hdqw (637e7efe77a6abeb44ff037b39458562423c693c10f122156d32be2fc9081eda): Bind for 127.0.0.1:33369 failed: port is already allocated, error deleting container: Error response from daemon: driver failed to remove container]
```
Prior to the change it would have been:
```
error removing container after failed start: error starting container "clusterctl-upgrade-oh686r-control-plane-6hdqw": Error response from …
```

🌱 CAPD: fix multi error handling in RunContainer

---

hack/tools/release/notes.go

This applies the same user friendly areas substitutions to the multiple areas entries that it was already applied to single area entries.
As a bonus, add a case insensitive string sorting that avoids exponential string allocation. There was no major issue with the previous implementation, I just already had this one lying around and it should be a bit more efficient. This is mostly because strings are immutable in Go, so any `ToLower` call would basically have to allocate memory for a new string.
Part of #9008
/area release

🌱 Improve multiple areas PRs with user friendly subs

---

docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md

Documents changes from https://github.com/kubernetes-sigs/cluster-api/pull/9045 in v1.5-v1.6 migration document 
xref comment: https://github.com/kubernetes-sigs/cluster-api/pull/9045#discussion_r1286114504

📖 Document new scheme-builder patterns in provider migration doc

---

.github/PULL_REQUEST_TEMPLATE.md

We would like users to add labels to their PRs. This will help the release team know the areas of the code base update for better release notes. 
Ref #8051

:book: Add call out for area labels when making a PR

---

docs/book/src/SUMMARY.md
docs/book/src/reference/owner_references.md
test/framework/ownerreference_helpers.go

This guide caps of work done on ownerReferences in Cluster API over the last ~12 months. It sets out a set of heuristics for using ownerReferences in Cluster API which may be useful for related projects as a reference.
It also documents in a simple way the current state of ownership relationships in Cluster API.
Related: #8256,
Fixes  #5487

:book: Add a guide describing ownerReference usage in CAPI

---

scripts/ci-e2e.sh

**What this PR does / why we need it**: Use existing value of `SKIP_RESOURCE_CLEANUP` if set in environment for `./scripts/ci-e2e.sh` as it's currently being overwritten.
Fixes #

🌱 Use existing value of `SKIP_RESOURCE_CLEANUP` if set in environment

---

.golangci.yml
bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go

Found this while syncing golangci-lint config with CAPV.
The pprof imports for the boostrap and control plane controller are a duplicate to the ones provided via controller-runtime.
The linter exclusions are not necessary anymore.
Fixes #

🌱 Drop duplicate pprof and unused linter excludes

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

Completing the release comms [task](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions) for this week.
@kubernetes-sigs/cluster-api-release-team 

📖 Update CAPI support and guarantees for v1.6

---

hack/tools/release/notes.go

Add a warning to the release notes tool when a release note can not be generated at all - i.e. when the body is empty. We noticed this error when using the release tool to generate notes for the Cluster API provider for CAPV.
This error hasn't occured in releases of CAPI AFAICT. Running   `go run ./hack/tools/release/notes.go --from=v1.4.0` doesn't produce any errors.

:bug: Generate warning when release notes can not be generated 

---

.github/workflows/weekly-security-scan.yaml
Makefile
docs/release/release-tasks.md
hack/verify-container-images.sh

Adds:
* `verify-govulncheck` target, to scan the code via `govulncheck`
* `verify-vulnerabilities` target which runs `./hack/verify-vulnerabilities.sh`
* Runs `make verify-container-images`
* Runs `make verify-govulncheck`
* Exit code is 1 if one or both targets report vulnerabilities or errors
* Use `verify-vulnerabilities` in scan action instead of `verify-container-images`
Fixes #9091

🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action

---

.github/workflows/pr-golangci-lint.yaml

Bump golangci-lint to v1.54.1.
The main feature here is go v1.21 support. Notes:
v1.54.0: https://github.com/golangci/golangci-lint/releases/tag/v1.54.0
v1.54.1: https://github.com/golangci/golangci-lint/releases/tag/v1.54.1

:seedling: Bump golangci-lint to v1.54.1

---

util/annotations/helpers.go
util/annotations/helpers_test.go

The previous implementation worked well for most Object implementations (definitely all embedding metav1.ObjectMeta) because it relies on:
* The fact that GetAnnotations doesn't return a copy of the annotations but the underlying map storing them.
* When calling set annotations, the input map is used for storage in the Object implementation, hence when adding entries to that map from the outside, it changes the content of the Object's annotations.
This is not necessarily part of the contract specified by metav1.Object so we can't really guarantee all implementations will satisfy these 2 conditions. It turns out, unstructured.Unstructured doesn't.
This issue is probably and edge and hence why no one has run into it yet. But it bite me when writing …

🐛 Fix AddAnnotations for unstructured.Unstructured

---

test/framework/clusterctl/clusterctl_helpers.go

**What this PR does / why we need it**: As part of https://github.com/kubernetes-sigs/cluster-api/commit/caaa74482b51fae777334cd7a29595da1c06481e#diff-7084fa27f2b10b8d2472295c14187d21ea186aae39efa12e051f340562a4cca4, the `Waiter` interface input type in the e2e test framework was changed from `ApplyClusterTemplateAndWaitInput ` to `ApplyCustomClusterTemplateAndWaitInput`, however this is breaking for providers that use the `Waiter` interface outside of scale.go. 
When bumping CAPI to v1.5.0 in CAPZ, we ran into an issue where `Flavor` is no longer available from that input type (see [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3707/files#r1283473277)).
This PR adds `Flavor` to the new struct which should have no negative impacts for tests that don't use it but …

🌱 Add back flavor to Waiter interface

---

hack/tools/conversion-verifier/main.go
hack/tools/go.mod
hack/tools/go.sum

Replace hashicorp/go-multierror with kerrors. This bring the conversion-verifier in line with what's being done across the rest of the codebase. 
Related to https://github.com/cncf/foundation/issues/617 which investigates license changes in hashicorp repos. This is the only direct dependency on a hashicorp repo in the CAPI codebase. AFAICT this repo won't be impacted by the licensing changes, but it's a low impact change which drops a dependency and makes the code more consistent.

:seedling: Replace hashicorp/go-multierror with kerrors

---

.github/workflows/weekly-security-scan.yaml
Makefile
hack/verify-container-images.sh

Manual cherry-pick of #9144
/area ci

[release-1.5] 🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action

---

.github/workflows/pr-golangci-lint.yaml

Adds the colored-line-number output format for the golangci-lint action run in CI.
Idea taken from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2180.

:seedling: Add colored-line-number output for golangci-lint action

---

hack/kind-install-for-capd.sh

Fixed KIND Config requiring docker networking with ipv6 support.
Fixes #9000

:seedling: Make dev cluster networking configurable

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

….
Allow to drop useExperimentalRetryJoin from KubeadmControlPlane.kubeadmConfigSpec
Fixes #9169

:bug: Allow to drop useExperimentalRetryJoin field from KubeadmControlPlane.kubeadmConfigSpec

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.12.3
Fixes #9193 

🌱 Update cert-manager to v1.12.3

---

controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/scale_test.go
controlplane/kubeadm/internal/controllers/upgrade_test.go

Remove the unnecessary indicator `disableInPlacePropagation`, which is only used in tests
Fixes #8393

🌱 Remove disableInPlacePropagation field in KCP controller

---

Makefile

Previously, `make docker-push-all` would try to push the combined manifest and image of each component, while `make docker-build-all` would respect `ALL_DOCKER_BUILD` and only build the specified components. This change makes the Makefile target naming consistent (`docker-push-<component>` and `docker-push-manifest-<component>`, clusterctl not specially named anymore) and refactors so that `ALL_DOCKER_BUILD` defines which components are built and pushed.
Specifically, this allows a build of only production components using `ALL_DOCKER_BUILD="core kubeadm-bootstrap kubeadm-control-plane"`.
n/a

:seedling: Refactor docker-push* Makefile targets so users can control with ALL_DOCKER_BUILD which images are pushed

---

Makefile

🌱 Makefile: run doctoc only once

---

go.mod

Follow-up after discussion at https://github.com/kubernetes-sigs/cluster-api/pull/9189#discussion_r1294677973
Note: this does not add, remove or change any dependency. It only reformats the `go.mod` file.
Fixes #

🌱 go.mod reformat to have only two require blocks

---

internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go

Add topology-owned label to MachineHealthChecks.
Fixes #9134

:sparkles: Add topology-owned label to MachineHealthChecks.

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

This is a cherry-pick of changes merged in #9170 to `release-1.5`
Fixes #9169

[release-1.5] 🐛 Allow unsetting useExperimentalRetryJoin field from KubeadmControlPlane

---

controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go

This is a cherry-pick of changes merged in #9170 to `release-1.4`
Fixes #9169

[release-1.4] 🐛 Allow unsetting useExperimentalRetryJoin field from KubeadmControlPlane

---

docs/book/src/tasks/experimental-features/experimental-features.md

This paragraph in the [section describing describing the experimental features](https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features#enabling-experimental-features-on-existing-management-clusters) explains how to enable/disable features in a running mgmt cluster. Trying this for the `ClusterToplogy` feature flag revealed that the flag must also to be enabled for KCP. Otherwise the Webhook for KubeadmControlPlaneTemplate will deny the request. See: https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_webhook.go#L59
It might make sense for a user to get a list which deployments have to be edited for which feature. Not sure if this is the best way to …

:book: Reword and list which deployments have to be edited for exp features.

---

.github/workflows/lint-docs-pr.yaml

Update base branch so link checker is doing correct comparisons.
/area ci

:seedling: [release-1.4] Update base branch for link checker

---

.github/workflows/lint-docs-pr.yaml

Update base branch so link checker is doing correct comparisons.
/area ci

:seedling: [release-1.5] Update base branch for link checker

---

Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/kind/mapper.go

According to #8708 : Modify quickstart and CAPD to use the new Kubernetes release:
* Bump the Kubernetes version in:
* `test/*`: search for occurrences of the previous Kubernetes version
* `Tiltfile`
* Ensure the latest available kind version is used (including the latest images for this kind release)
* Verify the quickstart manually
* Prior art: [⚠️ Use Kubernetes 1.25 in Quick Start docs and CAPD. #7156](https://github.com/kubernetes-sigs/cluster-api/pull/7156)
* bump `InitWithKubernetesVersion` and `WorkloadKubernetesVersion` in `clusterctl_upgrade_test.go`
Open TODOs:
Relates to #8708

✨ v1.28: Prepare quickstart, capd and tests for the new release including kind bump

---

docs/release/release-tasks.md

Simplifies k8s-triage links the release-tasks markdown to a single link catching the same jobs.
Fixes #

📖 docs: update k8s-triage link to one which catches all relevant jobs

---

docs/book/src/developer/providers/version-migration.md
docs/book/src/reference/jobs.md
docs/book/src/reference/versions.md

Update book:
* Update supported versions in `versions.md`
* Update job documentation in `jobs.md`
* Prior art: [🌱 Update versions doc adding Kubernetes 1.25 #7194](https://github.com/kubernetes-sigs/cluster-api/pull/7194) [📖 docs update jobs.md #7196](https://github.com/kubernetes-sigs/cluster-api/pull/7196)
TODO
Related to #8708

📖 book: Update versions doc adding Kubernetes 1.28 + prowjob documentation

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md

After working on:
- https://github.com/kubernetes/test-infra/pull/30347
- #9160
this fixes or clarifies some points in the template for the test jobs and makes it more accurate. Also updates the prior art links.
Fixes #

📖 .github: improve kubernetes bump issue template

---

util/secret/certificates.go

The path separator in cloud-init scripts should always be "/" and independent of the platform, so path.Join instead of filepath.Join should be used when generating the paths. If Kubeadm bootstrap provider runs in a Windows pod, the certificate paths in cloud-init scripts will be incorrect, and created clusters will not be started due to incorrect certificate paths.
/area bootstrap

🐛Certificate paths in cloud-init scripts should not use a platform-dependent path separator

---

internal/controllers/machineset/machineset_preflight.go
internal/controllers/machineset/machineset_preflight_test.go

According to #8708 : Check and update the Kubernetes version skew policy in the MachineSet preflight checks.
This PR adjusts the machineset preflight checks to:
Allow minor version skew of 3 for kubelets, if the control plane is running kubernetes v1.28 and above.
See https://kubernetes.io/releases/version-skew-policy/#kubelet for more details.
Fixes #

✨ machineset: adjust preflight check to allow kubelet version skew of 3 for clusters running v1.28 and above

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go

- ~Log which `KubeadmConfig` gets reconciled so that every log line is easier to reason about~
- Fix patch errors not being logged (`rerr` vs. `err`)
n/a
-----
/area logging

🌱 Fix patch errors not being logged

---

docs/release/release-tasks.md

manual cherry-pick of 1fff6658870351ceff5921feb716e711d90d4b36 onto release-1.5 for #9198
/area release

[release-1.5] 📖 Add task to update link checker base branch

---

docs/release/release-team.md

Follow up on some recent discussions in Slack (https://kubernetes.slack.com/archives/C8TSNPY4T/p1690529653678859)

🌱 Clarify release team vs k8s/k8s-SIGs org membership

---

internal/topology/variables/clusterclass_variable_validation_test.go

Adds a test to document the current behaviour of defaulting required fields below properties in ClusterClass variables. 
Related to a slack discussion at https://kubernetes.slack.com/archives/C8TSNPY4T/p1690560631268189

:seedling: Add test for required properties in clusterclass variables

---

Tiltfile
docs/book/src/developer/tilt.md

The `context + "/.tiltbuild/bin/"` directory is created by a `local_resource` 
but `local_resource`s happens after `local` commands, including the one to create the Dockerfile for podman.
This PR ensures that the directory is present before writing the Dockerfile.
`mkdir -p` is idempotent so it's not an issue to call it twice for podman.
Fixes #9162

🐛 tilt: ensure .tiltbuild/bin directory is created early enough, add tilt troubleshooting guide

---

docs/release/release-tasks.md

manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/commit/1fff6658870351ceff5921feb716e711d90d4b36 onto release-1.4 for #9199 
/area release

[release-1.4] 📖 Add task to update link checker base branch

---

.github/workflows/release.yaml
.gitignore
CHANGELOG/OWNERS
CHANGELOG/README.md
Makefile
OWNERS_ALIASES
docs/release/release-tasks.md

**What this PR does / why we need it**:  This adds automated release branch and release tags creation via the release github action to enable the CAPI release team to cut releases without needing the maintainers to cut the releases (maintainers still need to be involved to manually hit the "publish" button and to review the release notes PR).
The process becomes as follows:
- Release team (docs/comms manager) opens a PR to add the auto-generated and manually revised release notes for the upcoming release **on the main branch**
- Release team (lead/everyone) and maintainers review and merge the PR
- Commit on main branch triggers the `Create Release` Action which will:
1. Validate the release version 
2. Create a release branch
3. Create and push release tags 
4. Generate release artifacts …

✨ Add automation to create release branch and tags

---

.github/workflows/pr-gh-workflow-approve.yaml
docs/book/src/reference/jobs.md

Prior art: https://github.com/kubernetes-sigs/metrics-server/blob/9dbb59e99addce5956f65d6e44749fb36eef339e/.github/workflows/gh-workflow-approve.yaml
Tested at https://github.com/chrischdi/cluster-api-provider-vsphere/pull/4
Fixes #9215

🌱 github: add workflow to auto-approve golangci-lint if ok-to-test label is set

---

test/e2e/config/docker.yaml
test/e2e/quick_start_test.go

Pins the container image used for kubernetes conformance tests in our dualstack tests to the version of commit: https://github.com/kubernetes/kubernetes/commit/18290bfdc8f
This is to include the following fixes:
- https://github.com/kubernetes/kubernetes/pull/119928
- https://github.com/kubernetes/kubernetes/pull/119966
Note: this fixes are getting cherry-picked to kubernetes `release-1.28` in:
- https://github.com/kubernetes/kubernetes/pull/119964
And the introduced changes should get dropped when we bump to a newer version than `v1.28.0` at 
https://github.com/kubernetes-sigs/cluster-api/blob/d57f454ab0185966348671a43beb46c1f6da7efd/test/e2e/config/docker.yaml#L241 …

🐛 test: pin conformance image to a version which includes a fix for the dualstack tests

---

.github/workflows/pr-gh-workflow-approve.yaml

Adds the types `edited` and `reopened` to the triggers for the `PR approve GH Workflows` action.
Before this PR the golangci-lint action could have been triggered by the `edited` or `reopened` actions.
The approval workflow would not get triggered in that case and did not approve the linter.
Fixes #9215
/area ci

🌱 github: add edited and reopened as triggers for the GH workflow approval

---

cmd/clusterctl/client/cluster/topology_test.go
internal/controllers/topology/cluster/util.go

🌱 Make ClusterClass generated object names consistent

---

.github/dependabot.yaml

Allow patch updates for the ignored dependencies in our dependabot config and group the `k8s.io` dependencies to reduce the number of individual PRs.
/area ci

:seedling: Add dependabot groups. Allow additional patch updates

---

hack/ensure-kubectl.sh

We recently bumped to kubekins 1.28 images which contain kubectl 1.28. With 1.28 the short flag has been removed (it's default now)
Fixes #

 🌱 Update ensure-kubectl.sh to 1.28

---

docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
docs/book/src/user/quick-start.md
hack/tools/go.mod
hack/tools/mdbook/releaselink/releaselink.go

Add a required "repo" tag to passed into usages of the `releaselink` tool. This is required in order to get rid of the deprecated `"golang.org/x/tools/go/vcs"`
This is a breaking change for downstream users of this tool who will have to add the new var - but it seemed simpler and easier to maintain than copying over the module -> repo resolution code from the go VCS tool.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9063

:warning: : Remove go-vcs dependency from releaselink tool

---

hack/observability/visualizer/kustomization.yaml

**What this PR does / why we need it**: Bump CAPI visualizer to v1.2.0, which allows it to support MachinePool Machines in the tree view.
Fixes #

🌱 Bump CAPI visualizer to v1.2.0

---

docs/release/release-tasks.md
docs/release/release-team.md

Part of #9216
- Doc improvement (add a recommendation to leads tasks):Communicate and set clear expectations between the leads and the shadows about timeline and rotation.
Fixes #9216

:book: Documentation improvements: suggestions for team leads

---

docs/release/release-tasks.md

Adds a step in the release cycle for ensuring the most recent release version is indexed for cluster API repo in [docs.crds.dev](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api) 
Part of #9290
/area release

📖 add step for indexing the CRDs of the latest release

---

test/framework/ownerreference_helpers.go

Add a function to force reconciliation of the ClusterResourceSet to the the ownerReference test. 
This ensures these ownerRefs are always reconciled before asserting the full graph. This hasn't been seen as an issue in core CAPI, but was causing flaky behaviour when using these utils in CAPV ref: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2209

:seedling: Add CRS re-reconcile to ownerReference test

---

docs/book/src/reference/owner_references.md
test/framework/ownerreference_helpers.go

Add tests and documentation for which ownerReferences should have `controller: true` for Cluster API objects.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/4014

:seedling: Test and document controller ownerReferences

---

Tiltfile

Support for duplicated resources when debugging with Tilt.
Providers could require add-ons which have duplicated Namespace objects, thus breaking the Tilt setup.
Fixes #9300

:bug: Allow duplicate objects in Tiltfile

---

util/resource/resource.go
util/resource/resource_test.go

I found [SortForCreate](https://github.com/kubernetes-sigs/cluster-api/blob/4abf44cd85c4590602e4c10543d53cd4ec914845/util/resource/resource.go#L50) to be very inefficient, it's basically O(n^2), it also needlessly allocates. In order to keep the contract (even though this exported function [is not widely used](https://github.com/search?type=code&q=SortForCreate+language%3AGo&l=Go&p=1)), I didn't change this function's behaviour (i.e. its purity), ~~but I did deprecate it~~. (It could've been even faster if we opted for an in-place sort, but I didn't want to change the function's behaviour.)
The function doesn't appear to be used in any tight loops or with a large number of elements, so it's a low prio PR, but it's something that could bite people …

:seedling: refactor SortForCreate to use sort.Slice

---

docs/book/src/reference/versions.md
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

🌱 Bump corefile-migration library to v1.0.21

---

docs/book/src/reference/versions.md
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry-pick of #9307
Fixes #

[release-1.5] 🌱 Bump corefile-migration library to v1.0.21

---

docs/book/src/reference/versions.md
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry-pick of #9307
Fixes #

[release-1.4] 🌱 Bump corefile-migration library to v1.0.21 

---

test/framework/ownerreference_helpers.go

Update some utils in the ownerRef e2e test package to make these functions easier to import.

:seedling: Refactor e2e ownerRef test utils

---

hack/tools/internal/tilt-prepare/main.go

Explicitly set `--leader-elect` to false instead of removing it when running tilt-prepare. This helps for providers which set leader-elect to true by default.
/area devtools

:bug: Fix tilt-prepare leader-elect setting

---

hack/tools/internal/tilt-prepare/main.go

`tilt-prepare` should add the `metrics` port to add-on workload containers only if it's missing to prevent API validation errors since ports must be unique.
Fixes #9306

🐛 Adding metrics container port in tilt-prepare only if it's missing

---

util/resource/resource.go

Just a naming fix to make things more understandable; followup to #9251
/area util
cc @sbueringer

:seedling: adjust naming in SortForCreate implementation

---

hack/tools/release/notes.go
hack/tools/release/notes_test.go

**What this PR does / why we need it**:Deduplicating prefix in release notes as stated in #9104 Release Notes section 3rd task
Fixes: #9190 
Part of: #9104

:bug: Deduplicating area in pr title in release notes

---

cmd/clusterctl/client/repository/repository_github.go

Remove API calls to the rate-limited GitHub API
Rif #https://github.com/kubernetes-sigs/cluster-api/issues/8426

🌱 use http get to download files from GitHub in clusterctl

---

cmd/clusterctl/cmd/version_checker.go
cmd/clusterctl/cmd/version_checker_test.go

Remove API calls to the rate-limited GitHub API
Rif #https://github.com/kubernetes-sigs/cluster-api/issues/8426

🌱 use goproxy to check version in clusterctl

---

internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machinedeployment/machinedeployment_sync_test.go

This PR drops the templateHash from the MachineSet Name inside the controller for MachineDeployments (responsible to create MachineSets).
It also adjusts `computeNewMachineSetName(...)` to generate and return the suffix with the length of the const so we always return a string of max length 63.
All in all this helps keeping the length of the name of a MachineSet lower or equal to 63, same as we nowadays do for Machines.
Example Created MD, MS and Machine before and afterwards (with maximum name length):
before:
```
❯ kubectl get md,ms,ma -o custom-columns=KIND:kind,NAME:.metadata.name
KIND                NAME
MachineDeployment   development-12400-md-0000000000000000000000000000000000000g6wzr
MachineSet …
```

🐛 MD controller: use regular random suffix for MachineSets, ensure max length 63

---

internal/controllers/topology/cluster/blueprint.go
internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/current_state.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/patches/patch.go
internal/controllers/topology/cluster/patches/template.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/scope/blueprint.go
internal/controllers/topology/cluster/scope/scope_test.go
internal/controllers/topology/cluster/scope/state.go
internal/controllers/topology/cluster/scope/upgradetracker.go
internal/controllers/topology/cluster/scope/upgradetracker_test.go
internal/controllers/topology/cluster/util.go
internal/topology/check/compatibility.go
internal/webhooks/cluster.go
internal/webhooks/clusterclass.go
internal/webhooks/patch_validation.go
test/extension/handlers/topologymutation/handler.go
test/infrastructure/docker/config/crd/kustomization.yaml
test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepooltemplates.yaml
test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
test/infrastructure/docker/exp/api/v1beta1/dockermachinepooltemplate_types.go

Follow-up to #9016
Part of https://github.com/kubernetes-sigs/cluster-api/issues/5991

🌱 Minor fixes for CC+MP implementation

---

Makefile

Fixes the go install path for kpromo which is used in `make promote-images` which we encountered during the v1.4.6/v1.5.1 release
Fixes #9335
/area release

:bug: fix go install path for kpromo v4.0.4

---

CONTRIBUTING.md
Makefile
hack/ensure-trivy.sh
hack/verify-container-images.sh
hack/verify-licenses.sh

This adds a trivy license scan to the Makefile `verify` target which runs on all pull requests. This should allow detection of undesired license changes in go dependencies.
Related to #9181

:seedling: Add licence-scan for pull requests

---

OWNERS_ALIASES

This PR adds @chrischdi (myself) to cluster-api-reviewers 🙂 🙃  .
I was added as reviewer back in January (#7996) for topology controller, CAPD and test*.
Since then I also took part in the [release team for v1.5](https://kubernetes.slack.com/archives/C8TSNPY4T/p1680105601984229) as shadow for the `CI Signal/Bug triage/Automation Manager` sub-team where I especially worked on deflaking some of our e2e tests during that cycle.
Besides that I contributed code for custom resource metrics for CAPI which got used e.g. for getting better insights for the scale testing (#8814) efforts.
By getting promoted to a reviewer of all parts in CAPI, I'd like to help the community to spread the work across more people.
To get a list of all my contributions to CAPI:
* …

🌱 Promote chrischdi to cluster-api reviewer

---

.golangci.yml

The local-prefixes setting is deprecated. (see the [docs](https://golangci-lint.run/usage/linters/#gci)).
This replaces it by the custom-order and sections setting.
Fixes #
<!-- 
Please label this pull request according to what area(s) you are addressing. For reference on PR/issue labels, see: https://github.com/kubernetes-sigs/cluster-api/labels?q=area+
Area example:
/area ci

🌱 golangci-lint: replace deprecated local-prefixes setting for gci

---

hack/verify-container-images.sh

Make the `GO_ARCH` setting explicit in this script.
Follow-on from discussion at https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2299#discussion_r1309889032

:seedling: Make GO_ARCH explicit in verify_containter script

---

hack/observability/kube-state-metrics/chart/kustomization.yaml
hack/observability/prometheus/kustomization.yaml

This bumps the prometheus and kube-state-metrics helm charts.
Especially this includes fixes for kube-state-metrics by bumping it to v2.10.0:
- https://github.com/kubernetes/kube-state-metrics/issues/2142
- Also the initialisation of custom resource metrics is now way faster on startup
Make sure to run `make clean-charts`!
Related to #8951
/area metrics

🌱 hack: bump kube-state-metrics and prometheus charts

---

internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/runtime/client/client.go
internal/runtime/client/client_test.go

Ensure the ClusterClass controller's watch on ExtensionConfigs correctly filters extensions so that only ClusterClasses referencing the config cause reconcile loops.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8495

:seedling: Improve ClusterClass watch for ExtensionConfigs

---

test/e2e/data/autoscaler/autoscaler-to-workload-workload.yaml
test/framework/autoscaler_helpers.go

Fixes the image repo.
Apparently new images are published to the new registry
Broke via #9349 (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1697533477378854912)
Fixes #

🐛 Fix autoscaler image repo

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Release notes for this release: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.4

:seedling: Bump cert-manager to v1.12.4

---

hack/tools/release/notes.go

This PR allows the existing release notes generation tool to generate (optionally in some cases) commonly used headers that have been manually filled out in the past:
* An optional header when generating a release candidate
* A highlights header with filler to manually replace
* An optional header about deprecation warnings
Fixes #9248
Part of #9104
---
Sample header output:
```
❯ go run hack/tools/release/notes.go -from release-1.5 -workers 1 -release-candidate -deprecation
🚨 This is a RELEASE CANDIDATE. Use it only for testing purposes. If you find any bugs, file an [issue](https://github.com/kubernetes-sigs/cluster-api/issues/new).
- Management Cluster: v1.**X**.x -> v1.**X**.x
- Workload Cluster: v1.**X**.x -> …
```

:seedling: Add additional blocks to release note generation

---

docs/proposals/20191017-kubeadm-based-control-plane.md

Issue was caught by the weekly run of the markdown link scanner: https://github.com/kubernetes-sigs/cluster-api/actions/runs/6073142652/job/16474488207

📖 Fix link to KCP v1alpha3 types

---

Makefile

This PR adds generation of the plantuml images to CI through a new job, which runs on PRs. The job fails in case the generated images differ from the contained images in PRs. 
This solution is not ideal:
1. I'm reinstalling git in CI, as I couldn't find an image containing plantuml and git, and am not sure if we should be building it ourselves.
2. The job refers to variables that are set in the `Makefile`, if e.g. the `PLANTUML_VER` changes, we might forget about this job.
Fixes #9331

🌱 Verify plantuml image generation in CI

---

docs/book/src/SUMMARY.md
docs/book/src/tasks/verify-container-images.md

- This PR documents verification steps for CAPI container images. 
Fixes #9292 
Image Ref: https://explore.ggcr.dev/?repo=registry.k8s.io/cluster-api

📖 document verification steps for capi images

---

docs/release/OWNERS

Based on the suggestion in https://github.com/kubernetes-sigs/cluster-api/pull/9270#issuecomment-1690394995, this PR proposes to add CAPI Release Team members: "cluster-api-release-team" as reviewers and "cluster-api-relase-lead" as approver to the **docs/release** folder in the repo
Fixes #
/area release

🌱 Add Release Team OWNERS file to docs/release folder

---

api/v1beta1/machinedeployment_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml

This PR improves the description for the field deployment.spec.strategy.type.
Fixes #9376

📖 Improve comment on MachineDeploymentStrategyType

---

internal/test/envtest/environment.go

We currently use MinK8sVersion only for ClusterClass tests to ensure we use Kubernetes >=1.22 testenv binaries. I think in this case we should fail now as there are no cases where we just want to silently skip the tests in that case.
Going forward if we have the use cases we could evolve the API to differentiate between "skip" and "fail", but I think that is not necessary for now
Fixes #

🌱 Fail tests if test env version check fails

---

internal/controllers/topology/cluster/conditions.go
internal/controllers/topology/cluster/conditions_test.go

Expand the message for this condition to give users additional clues about the likely cause.

🌱 Improve message for TopologyReconciledCondition

---

Makefile
api/.import-restrictions
api/v1alpha4/cluster_types.go
api/v1alpha4/clusterclass_types.go
api/v1alpha4/groupversion_info.go
api/v1alpha4/machine_types.go
api/v1alpha4/machinedeployment_types.go
api/v1alpha4/machinehealthcheck_types.go
api/v1alpha4/machineset_types.go
api/v1beta1/.import-restrictions
api/v1beta1/index/.import-restrictions
hack/verify-import-restrictions.sh

This PR adds `verify-import-restrictions` to enforce import restrictions on API packages
to prevent regression mentioned in #9011.
Fixes #

:seedling: Add verify-import-restrictions to enforce import restrictions

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.13.0
Fixes #9405 

🌱 Bump cert-manager to v1.13.0

---

hack/observability/grafana/dashboards/cluster-api-performance.json

* Fixes a column in the KCP overview table
* Adds a cluster filter which allows drilling down into specific clusters
Fixes #

🌱 Improve Performance dashboard

---

test/e2e/clusterctl_upgrade.go

This is a partial backport of commit 5c4ce8b.
The clusterctl upgrade test explicitly uses api version v1alpha3 to check for machine readiness, but this version is no longer served by CAPI 1.5. This means that the test now requires the 'before' version to be <1.5. While this doesn't impact the use of the clusterctl upgrade tests in CAPI itself, which explicitly tests upgrades from 1.3 and 1.4, but not 1.5, it does impact use by providers who are also running this test.
Fixes #9411
/area testing

[release-1.5] 🐛Don't use v1alpha3 in clusterctl upgrade test

---

Makefile

Looks like [1.2023](https://hub.docker.com/layers/plantuml/plantuml/1.2023/images/sha256-df362ccee11524c7f490c2e11a64d3abee8a78b7e5a83cf35fc10325ad721e09?context=explore) is the tag for the latest release in 2023 (?). In any case it got overriden yesterday. Pinning to a specific version now to avoid that the verify job randomly breaks because there is a small diff with a new plantuml version after they overwrite the tag
Fixes #

🐛 Pin Plantuml version

---

internal/webhooks/clusterclass.go
internal/webhooks/clusterclass_test.go

Fixes e2e-main which broke via #9340
The webhook did use an invalid name for testing the templates.
Fixes #
/area topology

🐛 topology: fix namingstrategy webhook to not use uppercase characters for testing the template and align unit test to e2e test

---

internal/controllers/machinehealthcheck/machinehealthcheck_targets.go

**What this PR does / why we need it**: Fix variable shadow bug in machine health checks
Fixes #9418

:bug: Fix excessive trace logging in the machine health check controller

---

docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md

Follow-up to #9340 
Adds a section in the book about naming strategy in clusterclasses.
Fixes #
/area book

📖 add documentation about namingStrategy in ClusterClasses

---

cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/cluster/objectgraph.go

This PR adds a check to the discovery phase of `clusterctl move` to collect whether the resource is blocking the move with the `clusterctl.cluster.x-k8s.io/block-move` annotation. This eliminates one extraneous API call during the actual move operation for all resources which already do not have the annotation.
Fixes #9196

:seedling: check resource blocking clusterctl move during discovery

---

docs/book/src/reference/jobs.md

PR to reflect the changes made in https://github.com/kubernetes/test-infra/pull/30709 which made many manually triggered jobs blocking.

[release-1.4] :book: Update jobs.md for newly blocking jobs

---

docs/book/src/reference/jobs.md

PR to reflect the changes made in https://github.com/kubernetes/test-infra/pull/30709 which made many manually triggered jobs blocking.

[release-1.5] :book: Update jobs.md for newly blocking jobs

---

docs/book/src/reference/jobs.md

PR to reflect the changes made in https://github.com/kubernetes/test-infra/pull/30709 which made many manually triggered jobs blocking.

:book:  Update jobs.md for newly blocking jobs

---

Makefile
exp/internal/webhooks/doc.go
exp/internal/webhooks/machinepool.go
exp/internal/webhooks/machinepool_test.go
exp/webhooks/alias.go
exp/webhooks/doc.go
internal/test/envtest/environment.go
main.go

To work towards https://github.com/kubernetes-sigs/cluster-api/issues/9011, we need to remove the reliance on controller-runtime from the API packages.
This updates the webhooks to use the CustomDefaulter and CustomValidator pattern and moves them to match the Cluster and ClusterClass webhooks. This Is a more major lift but removes quite a bit of the code from the API package itself, making it's reliance on controller-runtime a lot smaller.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

🌱 Move experimental API v1beta1 webhooks to separate package

---

Tiltfile
docs/book/src/developer/tilt.md
hack/tools/internal/tilt-prepare/main.go

After short discussions we considered renaming `deploy_kustomizations` to `additional_kustomizations` instead (which was added in #9390 )
Fixes #

🌱 Tiltfile: rename deploy_kustomizations to additional_kustomizations

---

internal/controllers/topology/cluster/desired_state.go

Thought about this for a bit. I think it makes sense to do the same as in the MD case.
Part of #5991

🌱 Add ownerRefs to BootstrapConfig/InfraMachinePool in classy Clusters

---

docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
test/e2e/common.go
test/framework/alltypes_helpers.go

Collects node yaml from workload cluster to assist in e2e failure analysis.
Fixes #9250

:seedling: extend test/framework to collect workload cluster nodes

---

docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
test/e2e/common.go

Dump all pods when running e2e tests. Previously only kube-system pods had their pod yamls dumped in the artifacts folder.

:seedling: Dump all pods in e2e test clusters

---

.golangci.yml
internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
test/infrastructure/docker/internal/docker/manager.go

🌱 Add loggercheck linter and fix findings

---

controlplane/kubeadm/internal/cluster.go

In this PR https://github.com/kubernetes-sigs/cluster-api/pull/3082, we treat failing to connect to the workload cluster as a transient error and do not add that error to the reconcile reterr.
https://github.com/kubernetes-sigs/cluster-api/blob/36cbd5bb9f14004bcbf71e25831c9c8704c95298/controlplane/kubeadm/internal/controllers/controller.go#L203-L211
But this improvement was missed when we migrated to getting the workload ClusterClient from ClusterCacheTracker, and it will causes reconcile always return an error when the workload cluster is unreachable, and the expected reconcile retry interval `RequeueAfter`  may does not take effect.
So we should re-add this improvement.
**Test**
Before re-add this improvement, when the first CP Machine fails to …

🐛 Fix KCP Controller reconcile always return error when workload cluster is unreachable

---

hack/tools/release/notes.go

We now trigger the release process (branches, tags, github draft PR, etc.) by merging a PR in main containing the release notes in markdown file.
This changes exclude these "trigger" PRs from the release notes, since they are not really changes we are shipping. All future trigger PRs will start with 🚀. We use "🌱 Release v1." as a fallback since the are existing PRs that didn't use the rocket emoji because they were created before we came up with the 🚀 idea.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/9104
/area release

🌱 Exclude release trigger PRs from release notes

---

controlplane/kubeadm/internal/cluster.go

🌱 Remove redundant GetRESTConfig in KCP Management.GetWorkloadCluster

---

Makefile
exp/addons/internal/webhooks/clusterresourceset_webhook.go
exp/addons/internal/webhooks/clusterresourceset_webhook_test.go
exp/addons/internal/webhooks/clusterresourcesetbinding_webhook.go
exp/addons/internal/webhooks/clusterresourcesetbinding_webhook_test.go
exp/addons/internal/webhooks/doc.go
exp/addons/webhooks/alias.go
exp/addons/webhooks/doc.go
internal/test/envtest/environment.go
main.go

To work towards https://github.com/kubernetes-sigs/cluster-api/issues/9011, we need to remove the reliance on controller-runtime from the API packages.
This updates the webhooks to use the CustomDefaulter and CustomValidator pattern and moves them to match the Cluster and ClusterClass webhooks. This Is a more major lift but removes quite a bit of the code from the API package itself, making it's reliance on controller-runtime a lot smaller.
**Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged)**:
Fixes #

🌱 Move experimental addons API v1beta1 webhooks to separate package

---

test/framework/alltypes_helpers.go

xref: https://github.com/kubernetes-sigs/cluster-api/pull/9416#discussion_r1330146206

🌱 test/e2e: structure resources by namespace/kind again

---

Makefile
test/infrastructure/docker/internal/webhooks/doc.go
test/infrastructure/docker/internal/webhooks/dockercluster_webhook.go
test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go
test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook_test.go
test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook.go
test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook_test.go
test/infrastructure/docker/main.go
test/infrastructure/docker/webhooks/alias.go
test/infrastructure/docker/webhooks/doc.go

To work towards https://github.com/kubernetes-sigs/cluster-api/issues/9011, we need to remove the reliance on controller-runtime from the API packages.
This updates the webhooks to use the CustomDefaulter and CustomValidator pattern and moves them to match the Cluster and ClusterClass webhooks. This Is a more major lift but removes quite a bit of the code from the API package itself, making it's reliance on controller-runtime a lot smaller.
**Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged)**:
Fixes #
/area api

🌱 Move docker infrastructure API v1beta1 webhooks to separate package 

---

Makefile
test/infrastructure/inmemory/internal/webhooks/doc.go
test/infrastructure/inmemory/internal/webhooks/inmemorycluster_webhook.go
test/infrastructure/inmemory/internal/webhooks/inmemoryclustertemplate_webhook.go
test/infrastructure/inmemory/internal/webhooks/inmemorymachine_webhook.go
test/infrastructure/inmemory/internal/webhooks/inmemorymachinetemplate_webhook.go
test/infrastructure/inmemory/main.go
test/infrastructure/inmemory/webhooks/alias.go
test/infrastructure/inmemory/webhooks/doc.go

To work towards https://github.com/kubernetes-sigs/cluster-api/issues/9011, we need to remove the reliance on controller-runtime from the API packages.
This updates the webhooks to use the CustomDefaulter and CustomValidator pattern and moves them to match the Cluster and ClusterClass webhooks. This Is a more major lift but removes quite a bit of the code from the API package itself, making it's reliance on controller-runtime a lot smaller.
**Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged)**:
Fixes #
/area api

🌱 Move inmemory infrastructure API v1beta1 webhooks to separate package

---

internal/controllers/topology/cluster/patches/engine_test.go

This PR adds tests for the new ClusterClass MachinePool implementation for `internal/controllers/topology/cluster/patches/engine_test.go`
Fixes part of https://github.com/kubernetes-sigs/cluster-api/issues/5991
/area testing
<sub>Johannes Frey <[johannes.frey@mercedes-benz.com](mailto:johannes.frey@mercedes-benz.com)>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

:seedling: Add MachinePool test cases to engine tests

---

Makefile
cloudbuild.yaml

This reverts commit d9814963ce77d31110d06755c58f4f9379337281, reversing changes made to 2639f2c4a445734ec78358380c07559bee9d57d6.
Addresses failing tests from `post-cluster-api-push-images` ([example link](https://github.com/kubernetes-sigs/cluster-api/pull/9392#issuecomment-1726077164)) that appear to have been caused by this pr: https://github.com/kubernetes-sigs/cluster-api/pull/9392
/area release

:bug: Reverts pull request from cahillsf/improve-release-speed

---

docs/book/src/clusterctl/commands/generate-cluster.md
docs/book/src/tasks/experimental-features/ignition.md

Currently, there is an incorrect version of `kubernetes-version` flag in the docs for the ignition part as the version that is currently used in the book does not have an AMI for this version.
I also changed all the occurences of `kubernetes-version` that does not reflect the newest stable release.
Fixes #9402 
/area docs

:book: Change kubernetes-version in ignition/cluster generation parts of the book

---

CONTRIBUTING.md

I would like to propose to change our backport policy. tl;dr is:
* On main: let's align to the Go minor version used by our k/k dependencies  (Makefile + go.mod)
* On release-branches: let's bump the Go minor version used to build our controller images if the Go minor version goes out of support (only Makefile)
The reason why I'm bringing this up is because Go 1.19 is out of support as of now but we still use it on the release-1.4 branch.
The idea would be to only bump the Go version we use to build our controller images. This means bumping the version in the Makefile, but not in go.mod (go.mod would break library consumers), similar to what Kubernetes is doing (they also don't bump the go.mod …

📖 Bump go minor versions in release branches if they are out of support

---

Makefile
Tiltfile
bootstrap/kubeadm/main.go
controlplane/kubeadm/main.go
hack/ensure-go.sh
main.go
test/infrastructure/docker/main.go

Bumps `release-1.4` to address new CVE causing our GH action `Weekly Security Scan` to fail ([example](https://github.com/kubernetes-sigs/cluster-api/actions/runs/6146074316/job/16674739006#step:5:659))
Pending merge of [https://github.com/kubernetes-sigs/cluster-api/pull/9415](https://github.com/kubernetes-sigs/cluster-api/pull/9415)

[release-1.4] 🌱 Bump to Go 1.20.8

---

docs/book/src/reference/owner_references.md
test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/framework/ownerreference_helpers.go

This PR adds MachinePools to existing topology templates for the quickstart E2E tests by changing the `cluster-with-topology.yaml` base, specifically the following templates:
- cluster-template-topology
- cluster-template-topology-dualstack-ipv4-primary
- cluster-template-topology-dualstack-ipv6-primary
- cluster-template-topology-single-node-cluster
Fixes part of #5991
/area testing

🌱 Add MachinePools to Topology Quickstart E2E Templates

---

test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

Small follow-up to: #9393
Didn't want to further hold up #9393
Fixes #

🌱 Improve labels/annotations in CAPD test ClusterClass

---

internal/controllers/topology/cluster/patches/engine_test.go

Some minor fixes as follow-up to #9373
I would have pushed a commit to #9373 directly, but I didn't have the permissions
(Johannes is on PTO and we decided that I take over his PR's while he's away)

🌱 Fix some nits in Cluster topology engine tests

---

Makefile

Bump apidiff to v0.7.0
Release notes: https://github.com/joelanford/go-apidiff/releases/tag/v0.7.0

:seedling: Bump apidiff to v0.7.0

---

internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go

Supersedes #9371
Pushed the fixes as a separate commit, will squash before merge.
(I unfortunately can't push onto #9371, I talked to Johannes that I"ll finish up his PRs while he's on PTO)

🌱 Add MachinePool test cases

---

internal/controllers/topology/cluster/blueprint_test.go
internal/controllers/topology/cluster/current_state_test.go
internal/controllers/topology/cluster/desired_state_test.go
internal/test/builder/infrastructure.go

This PR adds tests for the new ClusterClass MachinePool implementation for the following files:
- internal/controllers/topology/cluster/blueprint_test.go
- internal/controllers/topology/cluster/current_state_test.go
- internal/controllers/topology/cluster/desired_state_test.go
Fixes part of #5991
/area testing

:seedling: Add unit tests for CC MP blueprint, current_state, & desired_state

---

internal/topology/variables/cluster_variable_defaulting.go
internal/topology/variables/cluster_variable_validation.go

Before
>  The Cluster "my-cluster-2" is invalid: spec.topology.variables: Invalid value: []v1beta1.ClusterVariable{v1beta1.ClusterVariable{Name:"imageRepository", DefinitionFrom:"", Value:v1.JSON{Raw:[]uint8{0x22, 0x6b, 0x38, 0x73, 0x2e, 0x67, 0x63, 0x72, 0x2e, 0x69, 0x6f, 0x22}}}, v1beta1.ClusterVariable{Name:"imageRepository", DefinitionFrom:"", Value:v1.JSON{Raw:[]uint8{0x22, 0x6b, 0x38, 0x73, 0x2e, 0x67, 0x63, 0x72, 0x2e, 0x69, 0x6f, 0x22}}}, v1beta1.ClusterVariable{Name:"lbImage", DefinitionFrom:"", Value:v1.JSON{Raw:[]uint8{0x7b, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x3a, 0x22, 0x6b, 0x69, 0x6e, 0x64, 0x65, 0x73, 0x74, 0x22, …

🌱 Improve Cluster variable defaulting/validation errors

---

test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/drop-machinepools.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/kustomization.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/drop-machinepools.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/kustomization.yaml

Fixes a failure in the dualstack e2e tests caused by the introduction of MachinePools in https://github.com/kubernetes-sigs/cluster-api/pull/9393
This PR drops the MachinePools in the templates. I'll add info on the umbrella issue for how to make the dualstack e2e tests work with MachinePools.
Related to https://github.com/kubernetes-sigs/cluster-api/issues/5991

:bug: Drop MachinePools from Dualstack tests

---

docs/book/src/developer/providers/webhooks.md
docs/proposals/20200423-etcd-data-disk.md

Fix a couple of broken links in the book caught by the weekly markdown scanner.

:book: Fix broken link to docker webhook and d2iq

---

docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
exp/addons/internal/controllers/clusterresourceset_controller.go

Remove the dependency on `cluster-api/util` from the addons API package. This removes a large set of dependencies for importers of that API.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/9011
/area api

:seedling: Remove the dependency on cluster-api/utils from addons API

---

test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/cluster.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/cluster.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

Adds svariables and matching patches to set log levels for topology based clusters in e2e. The motivation for adding this is to help debug https://github.com/kubernetes-sigs/cluster-api/issues/8816. 
The patch is enabled for that test in this PR, but this seems like a generally useful flag for helping debug e2e tests.

:seedling: Add log level for kube components patch to ClusterClass

---

test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/cluster.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/cluster.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9493

[release-1.5] :seedling: Add log level for kube components patch to ClusterClass

---

.golangci.yml

Small fixups to the formatting of the CAPI .golangci.yml file to add comments on import sections - related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2058#issuecomment-1735243383

:seedling: Fix .golangci.yml comments

---

test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

Issue with required not being defined was introduced in https://github.com/kubernetes-sigs/cluster-api/pull/9501. I'm not sure of the root cause, but `required` only seems to be required on older versions of Kubernetes. 
The test was passing `e2e-min-k8s-main` - which runs with Kubernetes v1.25 - but failing `e2e-min-k8s-release-1-5` - which runs Kubernetes v1.24.
Either way we should make this change in both branches after we see if it fixes the underlying issue here.

[release-1.5] :bug: Fix broken e2e test clusterclass

---

test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml

Reverse cherry-pick for this one. The tests were failing on release-1.5, but I'd like to keep these ClusterClasses in sync where it makes sense.
Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9504

:seedling: Fix broken e2e test clusterclass

---

test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/kustomization.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-upgrades/kustomization.yaml
test/e2e/self_hosted.go
test/framework/cluster_topology_helpers.go

This PR adds checks for MachinePools in the cluster topology upgrade test. Template flavors `upgrade`, `topology`, and `kcp-scale-in` already contain MachinePools using the `cluster-with-topology.yaml` base.
Fixes part of #5991 
/area testing

🌱 Add MachinePools to topology upgrade test

---

internal/controllers/machinedeployment/machinedeployment_sync.go
internal/controllers/machineset/machineset_controller_test.go
internal/controllers/topology/cluster/conditions.go
test/framework/clusterctl/clusterctl_helpers.go

Fix `form` instead of `from` in a couple of places across the codebase.

:book: Fixup `from` typo

---

internal/controllers/topology/cluster/structuredmerge/dryrun.go
internal/controllers/topology/cluster/structuredmerge/options.go
internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go

**What this PR does / why we need it**:  
`HelperOption` is defined with the same fields as ssa.FilterObjectInput, which is redundant. This PR removes the duplication by embedding `ssa.FilterObjectInput` into `HelperOption` instead.  
The original request of the issue is `drop HelperOptions and replace all of it uses with ssa.FilterObjectInput`, but that would introduce a lot of diffs. I'd say it would be enough to replace duplicated fields by embedding `ssa.FilterObjectInput` directly, which makes the diffs small.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:  
Fixes #8395

🌱 Embed ssa.FilterObjectInput into HelperOption to remove duplication

---

test/e2e/scale_test.go

A test to ensure the scale test is running before adding to periodic.

:seedling: Add test for scale testing machinery

---

docs/book/src/clusterctl/configuration.md

**What this PR does / why we need it**:  
This PR adds a line in the docs to describe the format of keys for clusterctl config substitution.  
The format comes from [the Viper's behavior that doesn't accept lowercase letters](https://github.com/kubernetes-sigs/cluster-api/issues/8097#issuecomment-1476602450). Users should know the required format regardless of whether it's the Viper's expected behavior or not.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:  
Fixes #8097

:book: Add a line about the format of key for clusterctl config

---

config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
exp/ipam/api/v1alpha1/ipaddress_types.go
exp/ipam/api/v1alpha1/ipaddressclaim_types.go

This PR adds the `AGE` column to the output of kubectl for the IPAM resources `IPAdressClaim` and `IPAddress`.
Before:
```sh
❯ kubectl get ipaddressclaims,ipaddress
NAME                                             POOL NAME   POOL KIND
ipaddressclaim.ipam.cluster.x-k8s.io/foo-claim   foobar      bar
NAME                                     ADDRESS       POOL NAME   POOL KIND
ipaddress.ipam.cluster.x-k8s.io/foo-ip   192.168.0.2   foobar      bar
```
After:
```sh
❯ kubectl get ipaddressclaims,ipaddress
NAME                                             POOL NAME   POOL KIND   AGE
ipaddressclaim.ipam.cluster.x-k8s.io/foo-claim   foobar      bar         101s
NAME                                     ADDRESS       POOL NAME   POOL KIND   AGE …
```

🌱 ipam: add age column to kubectl output

---

docs/book/src/user/quick-start.md

Fix a broken link in the docs.

:book: Fix Equinix metal link in docs

---

test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Initialize configmap object before getting it, tries to use a nil value results in an error.
Fixes #

✨CAPD: Initialize configmap object before getting it

---

test/infrastructure/docker/config/rbac/role.yaml
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Add config maps to CAPD RBAC, these permissions are needed to fetch CM with custom HA proxy config. https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/api/v1beta1/dockercluster_types.go#L67
Fixes #

✨Add config maps to CAPD RBAC

---

docs/release/release-tasks.md

Part of the Improvement tasks for the v1.6 release cycle https://github.com/kubernetes-sigs/cluster-api/issues/9104
Add release tasks to update the GitHub actions to work with the new release
Fixes #9486
/area release

:book: Add release tasks to update the GitHub actions to work with the new release

---

Makefile
Tiltfile

Bump the go version used to build CAPI to v1.20.10

:seedling: Bump Go to v1.20.10

---

test/e2e/common.go
test/e2e/self_hosted.go

- The changes added in this PR will capture "destination clusters" nodes and pod info before they get cleaned.
- These changes are added to self_hosted cluster tests.
- Aiming to track down `When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane [ClusterClass]`
Fixes #

🌱 Dump all resource information for self-hosted tests

---

docs/release/release-tasks.md

Update release tasks for release notes:
- Add new instructions to build and use release notes tool.
- Update manual edits and review steps required for the notes.
- Make manual edits a checklist to be followed on the release day.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/9104
/area release

🌱 Update instructions checklist to generate release notes

---

Makefile
Tiltfile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9551
Bump Go to v1.20.10

[release-1.4] :seedling: Bump Go to v1.20.10

---

Makefile

This PR bumps:
- HADOLINT_VER to v2.12.0
- YQ_VER to v4.35.2
- GOVULNCHECK_VER to v1.0.1
- SETUP_ENVTEST_VER to latest
- GOTESTSUM_VER to v1.11.0
Part of https://github.com/kubernetes-sigs/cluster-api/issues/9094
/area dependencies

🌱 Bump some dependencies in Makefile

---

docs/release/release-tasks.md

To not over-formalize the process but still have some information about expanding the team even during the release cycle to handle no-shows, this PR adds a lightweight note about adding/removing RT members to make it a bit clearer. 
Fixes #9273 
/area release

📖 Clarify adding/removing release team members

---

docs/release/release-tasks.md

Part of the Improvement tasks for the v1.6 release cycle https://github.com/kubernetes-sigs/cluster-api/issues/9104
* Add release task about removing unsupported release version of CAPI
Fixes #9485
/area release

:book: Add release task about removing unsupported release version of CAPI

---

Makefile
docs/release/release-tasks.md

Updates the make target (which is not in use anymore) and the corresponding documentation for generating the release PR.  The notes tool is frequently iterated on and to avoid excess overhead of backporting all the changes to `release-*` branches the updated process is to always build the binary from main, then checkout the relevant branches.
Fixes #9556
/area release

🌱 update release-notes make target + corresponding doc

---

internal/controllers/machine/machine_controller.go

Reverts a part of https://github.com/kubernetes-sigs/cluster-api/pull/9583 that incorrectly checked for the ErrClusterLocked from a function that never returns it.
Ref: https://github.com/kubernetes-sigs/cluster-api/pull/9583#discussion_r1365927447

[release-1.4] :bug: Revert ErrClusterLocked check in Machine controller

---

docs/release/release-tasks.md

As agreed per Slack discussion, it might be useful to document the checking for stuck/pending jobs in CI in CI teams tasks notes. xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1698053707813519
/area release

 📖 Add a note to the CI team tasks to check for stuck/pending jobs in CI

---

hack/tools/release/notes.go

Historically we always added a line separator after the `Changes since` heading. This doesn't make the text more readable and it kind of looks misformatted. GitHub already adds a line separator after `##` headings.
/area release

🌱 Remove extra separator after title in release notes

---

docs/release/release-tasks.md
docs/release/release-templates.md

This PR adds release templates to the docs/release directory
Fixes #
/area release

:book: Add release templates

---

exp/internal/controllers/machinepool_controller_phases.go
exp/util/suite_test.go
exp/util/util.go
exp/util/util_test.go

**What this PR does / why we need it**: Add util function to get MachinePool by label. This will simplify the mapper in the MachinePool controller as well as make it easier for InfraProviders to fetch the MachinePool for a InfraMachinePoolMachine.
Fixes #
/area machinepools

🌱 Add util function to get MachinePool by label

---

CHANGELOG/v1.4.8.md

🌱 Release v1.4.8

---

hack/tools/release/notes.go

Now all areas will be capitalize by default except the ones that have an explicit "user friendly" substitution.
/area release

🌱 Capitalize area prefix in release notes by default

---

docs/release/release-tasks.md
docs/release/release-team-onboarding.md
docs/release/release-team.md
hack/generate-doctoc.sh

This PR adds an initial version of the release Team onboarding documentation which should serve as a starting point of the onboarding notes based on my experience being involved in the RT and can be evolved over time with more notes as the release team continues to serve in the future. 
Fixes #9274 
/area release

📖 Add onboarding documentation for the Release Team

---

test/e2e/self_hosted.go

I'm unsure if this should be 📖 or 🌱. Please change as needed.
The self hosted test has optional variables that can be used to switch the infrastructure machine template when doing the upgrade. This documents the variables and also explains that the templates will need to be labeled in order to move with the cluster.
Fixes #

📖 E2e: Document self hosted machine templates

---

docs/community/20231018-karpenter-integration.md

Adds a proposal for the Karpenter feature group. This will help us to organize the Cluster API community around the activity of [Karpenter](https://karpenter.sh) usage with Cluster API by creating a central point of contact for contributors.
Fixes #9523 
/area community-meeting

📖 add proposal for karpenter integration feature group

---

test/e2e/self_hosted.go

This PR adds a missing field in the self-hosted test spec that may have been causing flakes in the self-hosted clusterclass spec.
Fixes (maybe) #9522
/area testing

🌱  Add WaitForMachinePoolToBeUpgraded to self-hosted test 

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

:seedling: Bump cert-manager to **v1.13.2**
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.13.2

:seedling: Bump cert-manager to v1.13.2

---

docs/release/release-team.md
hack/tools/release/OWNERS

Give the release team more autonomy to iterate on the release tool.
Fixes #9524
/area release

🌱 Give permissions for release notes tool to release team

---

docs/community/20231016-in-place-upgrades.md

As proposed in office hours, creating a working group to work together in a proposal.
Starting with https://github.com/kubernetes-sigs/cluster-api/issues/9489

📖 Add In-place upgrades feature group

---

exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/machine/machine_controller.go
internal/webhooks/machine.go
test/framework/ownerreference_helpers.go

**What this PR does / why we need it**: The test framework runs a test to ensure that ownerRefs are resilient, i.e. if the ownerRef is deleted, a controller can set it back. The MachinePool controller only checks to see if the MachinePool Machine exists, not that their ownerRefs are up to date. It also removes redundant code for setting the infraMachine ownerRef as that is already being done by the Machine controller.
#8842 is also rebased off of this PR.
Fixes #

🐛 Fix bug where MachinePool Machine ownerRefs weren't updating

---

test/e2e/k8s_conformance.go

This PR adds environment variables to the test framework to allow overwriting the variables `NumberOfNodes` and `GinkgoNodes`, which are passed to kubetest runs.
Currently this variables resolve to the hardcoded value of 5, coming from the `workerMachineCount`.
We are trying to run the upstream serial, alpha-features and slow tests.
* serial and alpha-features requires a value of `1`
* slow tests require a value of `25`
related to: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2452

🌱 test/conformance: add variables to overwrite parralelization of kubetest runs

---

.github/workflows/pr-verify.yaml

🌱 Bump kubebuilder tools to v0.4.2

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9652
Fixes CVEs https://github.com/advisories/GHSA-jq35-85cj-fj4p

[release-1.5] :seedling: Bump github.com/docker/docker from 24.0.5 to 24.0.7

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9652
Fixes CVEs https://github.com/advisories/GHSA-jq35-85cj-fj4p

[release-1.4] :seedling: Bump github.com/docker/docker from 24.0.5 to 24.0.7

---

hack/verify-container-images.sh

Fix a bug in this script which caused some CVEs to not be correctly reported. 
Responsible for https://github.com/kubernetes-sigs/cluster-api/pull/9675#issuecomment-1794833675

:bug: Fix reporting bug in verify-container-image script

---

docs/book/src/reference/providers.md

Adds https://github.com/cluster-api-provider-k3s/cluster-api-k3s to the cluster-api book.
Fixes #
No existing issue ... can create one if needed.

🌱 Add k3s providers to cluster-api book

---

docs/release/releases/release-1.7.md

This PR adds release-1.7 cycle schedule document with preliminary dates taking into account [Kubecon Europe 2024](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) between March 19-22, 2024 on week 16th in the schedule.
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/9094
/area release

📖 Add Cluster API release-1.7 timeline document

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
cmd/clusterctl/client/move.go
controllers/remote/cluster_cache_tracker_test.go
controlplane/kubeadm/internal/controllers/helpers_test.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
controlplane/kubeadm/internal/workload_cluster_test.go
exp/internal/controllers/machinepool_controller_test.go
exp/internal/webhooks/machinepool_test.go
exp/ipam/internal/webhooks/ipaddress_test.go
exp/ipam/internal/webhooks/ipaddressclaim_test.go
exp/runtime/hooks/api/v1alpha1/discovery_types.go
exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/mdutil/util_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
internal/controllers/machineset/machineset_controller_test.go
internal/topology/check/compatibility.go
internal/webhooks/cluster.go
internal/webhooks/machine_test.go
internal/webhooks/machinedeployment_test.go
internal/webhooks/patch_validation_test.go
test/framework/machinedeployment_helpers.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
test/infrastructure/inmemory/internal/server/mux_test.go
util/predicates/cluster_predicates_test.go
util/version/version.go

This PR bumps the golangci-lint from v1.54.1 -> v1.55.1
The major changes proposed in this PR include version updates to the following linters:
`gosec` - _G601: Implicit memory aliasing in for loop._ 
`goconst` - _string `xyz` has X occurrences, make it a constant_ 
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9589

🌱 Bump golangci-lint to v1.55.1

---

controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/upgrade.go
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_rbac.go

Add support to the Kubeadm Control Plane provider for the new Kubeadm ClusterRoles to use the super-admin config introduced in the v1.29 cycle. 
Part of https://github.com/kubernetes-sigs/cluster-api/issues/9578
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9633

:seedling: Support admin config for Kubeadm v1.29

---

Makefile
Tiltfile

Bump the go version used to build CAPI to v1.20.11
xref: https://go.dev/doc/devel/release#go1.20.11

🌱 Bump Go version to v1.20.11

---

Makefile
Tiltfile

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9683
Bump the go version used to build CAPI to v1.20.11
xref: https://go.dev/doc/devel/release#go1.20.11

[release-1.4] 🌱 Bump Go version to v1.20.11

---

test/infrastructure/docker/internal/controllers/dockercluster_controller.go

Up to now CAPD only logs, if creating the external LB fails.
This PR sets the corresponding condition, so that this error is easier to see.
Related question: https://kubernetes.slack.com/archives/C8TSNPY4T/p1699367691120419

:seedling: CAPD: Set Condition, if creating external LB failed.

---

Tiltfile

We updated the Go version in this file in https://github.com/kubernetes-sigs/cluster-api/pull/9687 but never updated the delve version to be compatible.

[release-1.4] :seedling: Fix delve version in Tiltfile

---

cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/client.go
cmd/clusterctl/client/cluster/components.go
cmd/clusterctl/client/cluster/crd_migration.go
cmd/clusterctl/client/cluster/inventory.go
cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/ownergraph.go
cmd/clusterctl/client/cluster/proxy.go
cmd/clusterctl/client/cluster/upgrader.go

**What this PR does / why we need it**: In the spirit of of #8733, this PR adds a `context.Context` parameter to the `retryWithExponentialBackoff` helper used throughout clusterctl. This allows backoff to short circuit if a context is canceled during a sleep between retries instead of only while the retried function is running. The primary change is to call apimachinery's `wait.ExponentialBackoffWithContext` instead of `wait.ExponentialBackoff`.
Almost every call to this helper already had a context available, but there are a couple that needed `context.Background()`s.
Fixes #

:seedling: propagate ctx to retryWithExponentialBackoff in clusterctl

---

docs/book/src/reference/glossary.md
docs/proposals/20220725-managed-kubernetes.md
docs/proposals/20230407-flexible-managed-k8s-endpoints.md
docs/proposals/20230407-managed-k8s-capi-contract-changes.md

This PR introduces a proposal to make Cluster Infra Resource Optional in Cluster API to aid Managed Kubernetes provider scenarios.
After this PR we will want to create an issue that describes the implementation tasks
- e.g.
- https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane
- https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure
Fixes #7494
References #5295

📖 CAEP: Flexible Managed Kubernetes Endpoints

---

test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/clusterclass_changes.go
test/e2e/clusterclass_rollout.go
test/e2e/self_hosted.go

This PR adds MachinePools to runtime SDK and rollout tests for ClusterClass. This will help unblock MachinePoolMachines which is affected by these tests not accounting for MachinePools in the quickstart spec. #8842 
Fixes part of #5991
/area testing

🌱  Add MachinePools to Runtime SDK and Rollout tests

---

docs/book/src/SUMMARY.md
docs/book/src/user/quick-start-operator.md
docs/book/src/user/quick-start.md

Creates a new quickstart path for using the CAPI Operator instead of clusterctl
Fixes #9473 

:book: Add CAPI Operator Quickstart

---

test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_runtimesdk.go

I guess there's no reason why we shouldn't set the timeouts for those two tests as well
Might even help with some flakes (just speculation, I didn't take a closer look)
Follow-up to #9540

🌱 Add MP timeouts to cluster upgrade tests

---

config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
exp/ipam/api/v1beta1/ipaddress_types.go
exp/ipam/api/v1beta1/ipaddressclaim_types.go

Looks like we probably added this column at the same time as we promoted the types to v1beta1
Fixes #

🌱 Add age also to v1beta1 IPAM types

---

Tiltfile
hack/tools/internal/tilt-prepare/main.go

This PR updates the Tilt dev setup to still install, but otherwise ignore, Deployment resources without a `cluster.x-k8s.io/provider` that come with a provider. CAPI may overwrite the `command` for the container in a way that isn't compatible with the image, for example if the image doesn't contain `sh`, such that the container fails to start.
Fixes #
/area devtools

:seedling: allow non-provider Deployments in Tilt

---

cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/objectgraph_test.go

`clusterclt move` didn't include secrets in provider namespace, for example:
I have claimed `AWSClusterStaticIdentity` for cluster A, and add the reference secret to `capa-system`. But when I tried to use `clusterclt move` to migrate the cluster, only the AWSClusterStaticIdentity will be included, but the secret for the identity not included and causing issue in target management cluster after move.
The root cause of this is that the `discoveryType`  is `Secret` but the filter set for provider namespace check is `SecretList` , so that part of logic will never run into.
Part of  #9630

:bug: fix provider namespace secret not included in clusterctl move

---

internal/contract/infrastructure_machinepool_template.go
test/e2e/clusterclass_changes.go
test/e2e/clusterclass_changes_test.go
test/e2e/clusterclass_rollout.go

This PR follows up #9703 with fixes listed here: https://github.com/kubernetes-sigs/cluster-api/pull/9703#pullrequestreview-1729685341
Fixes #
/area testing

🌱  Follow-up fixes: Add MachinePools to Runtime SDK and Rollout tests

---

.github/workflows/pr-golangci-lint.yaml

This PR bumps the golangci-lint version to [v1.55.2](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2)
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9589

🌱 Bump golangci-lint to v1.55.2

---

Makefile

🌱  Avoid cd'ing into test folders when building Docker images

---

test/extension/main.go

Set the user agent for test/extension correctly. More importantly add a constant string to the binary that we can later use with the `strings` command to easily identify the binary.
Fixes #

🐛 Set User Agent for test extension correctly

---

Makefile
cloudbuild.yaml

Reverts kubernetes-sigs/cluster-api#9536

🌱 Revert "Improve release staging build speed"

---

.github/workflows/weekly-md-link-check.yaml
.github/workflows/weekly-security-scan.yaml
.github/workflows/weekly-test-release.yaml

Updates the GitHub Actions to work with the new release branch version
Part of: #9094 and addresses: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-release-branch:
```
Update the GitHub Actions to work with the new release version.
Prior art: https://github.com/kubernetes-sigs/cluster-api/pull/9115
```
/area ci

🌱 Update GH actions to work with new release-1.6 branch

---

cmd/clusterctl/cmd/topology_plan.go
test/framework/cluster_proxy.go
test/framework/clusterctl/client.go
test/framework/exec/kubectl.go

🌱 Improve output of exec.KubectlApply

---

cmd/clusterctl/cmd/topology_plan.go
test/framework/cluster_proxy.go
test/framework/clusterctl/client.go
test/framework/exec/kubectl.go

Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9737
Fixes #

[release-1.4] 🌱 Improve output of exec.KubectlApply

---

cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/objectgraph_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9694
Note: In order to minimize the impact, I backported only the actual changes, not the cleanup in the tests

[release-1.4] 🐛 fix provider namespace secret not included in clusterctl move

---

cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/objectgraph_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9694
Note: In order to minimize the impact, I backported only the actual changes, not the cleanup in the tests

[release-1.5] 🐛 fix provider namespace secret not included in clusterctl move

---

docs/book/src/introduction.md

Document that the default documented version is now release-1.6 and provide backlink to release-1.5
Part of: https://github.com/kubernetes-sigs/cluster-api/issues/9094
/area release

:book: add release 1.5 book link

---

hack/tools/release/notes/main.go

Since now all areas are capitalized by default, when looking for the docs area label we need to use a capitalized constant.
/area release

🐛 Fix documentation area comparison in release notes

---

api/v1beta1/machineset_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
docs/book/src/tasks/automated-machine-management/autoscaling.md
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/webhooks/machinedeployment.go
internal/webhooks/machinedeployment_test.go
internal/webhooks/machineset.go
internal/webhooks/machineset_test.go
webhooks/alias.go

**What this PR does / why we need it**: MachineSet.spec.replicas defaulting should take into account autoscaler min/max size if defined. This PR applies the same default replicas policy of MD to MS.
Fixes #8085

🌱 MS: improve replica defaulting for autoscaler

---

controlplane/kubeadm/internal/controllers/controller.go
internal/controllers/machineset/machineset_controller.go

This will remove occurrences of the hardcoded conditions.WithStepCounterIf(false) #9754
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9754

:seedling: KCP/MS remove hardcoded WithStepCounterIf(false)

---

docs/release/release-tasks.md

[Relevant slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1701089100217369?thread_ts=1700642823.525959&cid=C8TSNPY4T) - sometimes we needs to add new subdomains to the netlify certificate
/area release

📖 [release] adds a clarifying note regarding netlify updates

---

hack/tools/release/notes/main.go

Tons of stupid mistakes from my side lately. Hopefully we can get https://github.com/kubernetes-sigs/cluster-api/pull/9617 merged soon to avoid these :) 
/area release

🐛 Fix Community meeting area formatting in release notes

---

exp/addons/internal/controllers/clusterresourceset_controller.go

Sets `RequeueAfter: time.Minute` instead of `Requeue: true` on ErrClusterLocked.
Fixes #9775
Area example:

🐛 clusterresourceset: requeue after 1 minute if ErrClusterLocked got hit

---

docs/release/releases/release-1.6.md
docs/release/releases/release-1.7.md

This PR updates the release-1.6/1.7 timelines where it:
- moves dates a week at the end of the release-1.6 cycle timeline doc due to the delay of week in release candidate cutting
- moves preliminary dates for release-1.7 cycle timeline for a week consequently
/area release

📖 Reflect a week of delay in the release-1.6/1.7 timelines

---

.github/ISSUE_TEMPLATE/release_tracking.md
docs/proposals/20230407-flexible-managed-k8s-endpoints.md
docs/release/release-tasks.md
docs/release/release-team.md
docs/release/releases/release-1.7.md
hack/generate-doctoc.sh

This PR adds all missing tasks/notes that are either missing or not clearly enough documented in the release team docs in general. It also:
- moves around some RL tasks in time chronological order 
- documents optional tasks for the Release Lead in the release tasks list. 
- clarifies RT and Release Day Meetings venue/time/day etc
- fixes a `doctoc` issues in the `release-team.md ` and proposals folder
- documents a task from #9104
```
Doc improvement: communication guidelines (moved from Misc section)
Public should be default - it gives visibility on the work being done, it is inclusive, it is a track of record -
Group DM as a safe space, but not for the actual work
```
Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/9726
/area release …

📖 Remove maintainer role in release team and improve release team docs

---

test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go

**What this PR does / why we need it**: Follow up cleanups from #9096. 
- fix ensure ownerRefs to make sure DockerMachines always have an owner
- Don't use RequeueAfter in DockerMachinePool controller delete, instead watch DockerMachines
- Use ssa.Patch() for creating Machines in MachinePool controller
Fixes #

🌱 Remove requeues in DockerMachinePool

---

exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_phases.go
exp/internal/controllers/machinepool_controller_phases_test.go

**What this PR does / why we need it**: Refactors MachinePool controller phase unit test to use envtest in order to be able to leverage SSA for Machine creation and update in the MachinePool controller.
Fixes #9755

🌱 Use SSA Patch to create machines in MP controller

---

exp/addons/internal/controllers/clusterresourceset_controller.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9777
/assign sbueringer

[release-1.4] 🐛 clusterresourceset: requeue after 1 minute if ErrClusterLocked got hit

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
controlplane/kubeadm/internal/controllers/controller.go
exp/internal/controllers/machinepool_controller.go
internal/controllers/machine/machine_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
test/infrastructure/docker/internal/controllers/dockermachine_controller.go

Sets RequeueAfter: time.Minute instead of Requeue: true on ErrClusterLocked.
This way the requeue does not end up in the Rate Limited Queue with exponential time
Follow-up of #9775
/area clustercachetracker

🐛 ClusterCacheTracker: Use RequeueAfter instead of immediate requeue on ErrClusterLocked to not have exponentially increasing requeue time

---

cmd/clusterctl/client/alpha/kubeadmcontrolplane.go
cmd/clusterctl/client/alpha/machinedeployment.go
cmd/clusterctl/client/alpha/rollout_pauser_test.go
cmd/clusterctl/client/alpha/rollout_restarter_test.go
cmd/clusterctl/client/alpha/rollout_resumer_test.go
cmd/clusterctl/client/alpha/rollout_rollbacker.go
cmd/clusterctl/client/alpha/rollout_rollbacker_test.go
cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/cert_manager_test.go
cmd/clusterctl/client/cluster/components.go
cmd/clusterctl/client/cluster/components_test.go
cmd/clusterctl/client/cluster/crd_migration_test.go
cmd/clusterctl/client/cluster/installer.go
cmd/clusterctl/client/cluster/inventory.go
cmd/clusterctl/client/cluster/mover.go
cmd/clusterctl/client/cluster/mover_test.go
cmd/clusterctl/client/cluster/objectgraph.go
cmd/clusterctl/client/cluster/proxy.go
cmd/clusterctl/client/cluster/template.go
cmd/clusterctl/client/cluster/topology.go
cmd/clusterctl/client/cluster/upgrader.go
cmd/clusterctl/client/cluster/workload_cluster.go
cmd/clusterctl/client/clusterclass.go
cmd/clusterctl/client/clusterclass_test.go
cmd/clusterctl/client/config.go
cmd/clusterctl/client/delete_test.go
cmd/clusterctl/client/describe.go
cmd/clusterctl/client/tree/discovery_test.go
cmd/clusterctl/client/upgrade_test.go
cmd/clusterctl/internal/test/fake_proxy.go

This PR:
- Replaces the `context.TODO()` with the underlying context in the function 
- adjust tests
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9442

🌱  replace context.TODO() from clusterctl proxy.go

---

CHANGELOG/v1.4.9.md

🌱 Release v1.4.9

---

.github/workflows/pr-verify.yaml

kubebuilder-release-tools [v0.4.3](https://github.com/kubernetes-sigs/kubebuilder-release-tools/releases/tag/v0.4.3
) is out, let's use it to be able to use 🚀 emoji in release PRs
/area release

🌱 Bump kubebuilder-release-tools to v0.4.3

---

Tiltfile

cluster-template.yaml was ignored because it doesn't start with cluster-template-
Fixes #

🐛Tilt: Show default cluster-template

---

exp/internal/controllers/machinepool_controller_phases_test.go

I've managed to reproduce the flakes on my local machine, it seems that the test flakes due to some random cache sync delays when creating a node with envtest, CAPI Testing documentation recommends using `CreateAndWait` for such cases.
Fixes #8993 

🐛 Fix TestReconcileMachinePoolScaleToFromZero flakes

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

After 1.6.0 release, this is an extension to some of the task done via this PR https://github.com/kubernetes-sigs/cluster-api/pull/9119
Fixes #

📖 Set 1.4 EOL date and update coredns version table

---

Makefile

This will ensure the same golangci config is used across the entire codebase
/area devtools

🌱  Explicitly set golangci config for sub modules

---

test/framework/machinedeployment_helpers.go

Fixes a race condition in the test function `ScaleAndWaitMachineDeploymentTopology`, when:
* The Cluster object gets patched:
* https://github.com/kubernetes-sigs/cluster-api/blob/3711210d42714669208d57f625c9151c04e3fd14/test/framework/machinedeployment_helpers.go#L536
* And the Machinedeployment gets retrieced
* https://github.com/kubernetes-sigs/cluster-api/blob/3711210d42714669208d57f625c9151c04e3fd14/test/framework/machinedeployment_helpers.go#L542
It could be the case that the topology controller did not yet update the MachineDeployment with the new number of replicas. But we use `.spec.replicas` from the machinedeployment.
This fixes the race condition by using the replicas from the provided input instead. …

🐛 test: wait for topology to get rolled out before continuing with scaling checks

---

hack/tools/release/notes/main.go
hack/tools/release/notes/release_notes_integration_test.go
hack/tools/release/notes/test/golden/v1.5.0.md

🐛 Fix kubeadm bootstrap prefix in release notes

---

docs/book/src/reference/providers.md
docs/book/src/user/quick-start.md
docs/book/theme/css/custom.css

Since we added proxmox to default clusterctl, we also need to reference it in the docs.
Fixes #

🌱  Add proxmox to provider list

---

cmd/clusterctl/client/cluster/components.go
cmd/clusterctl/client/cluster/components_test.go
cmd/clusterctl/client/delete.go
cmd/clusterctl/client/delete_test.go

Manual cherry-pick of #9808
Fixes #
/assign @chrischdi @fabriziopandini

[release-1.5] 🐛 clusterctl: validate no objects exist from CRDs before deleting them

---

Makefile
Tiltfile

Fixes sum CVE's by bumping Go
Fixes #

🌱 Bump to Go 1.20.12

---

docs/proposals/20190919-machinepool-api.md

github throw error `Error in user YAML: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1` when user visit this proposal
None

:seedling: Fix markdown format error in MachinePool API proposal

---

config/webhook/manifests.yaml
exp/ipam/internal/webhooks/ipaddress.go
exp/ipam/internal/webhooks/ipaddressclaim.go

During the bump of IPAM resources to `v1beta1` the version in the `kubebuilder:webhook` comment was missed which leads to a 'resource not found' error when they are called by the apiserver.
Fixes #9860 
/area ipam

🐛 ipam: fix webhooks using mixed api versions

---

docs/book/src/SUMMARY.md
docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md

This PR adds a migration doc for `v1.6` to `v1.7`.
Fixes Task: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers

📖 Add v1.6 -> v1.7 migration doc

---

docs/book/src/developer/testing.md
docs/book/src/developer/tilt.md
docs/book/src/user/concepts.md
docs/book/src/user/troubleshooting.md

This PR corrects a few formatting issues and an incorrect flag reference, encountered in the test documentation. 
Fixes #

:book: chore: Correct few issues in test docs

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
docs/proposals/20191017-kubeadm-based-control-plane.md
util/collections/machine_filters.go
util/collections/machine_filters_test.go

With this PR KCP defers remediation when another control plane machine is still provisioning
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9398

🐛 KCP should defer remediation when a control plane machine is still provisioning

---

cmd/clusterctl/client/repository/repository_github_test.go
cmd/clusterctl/client/repository/repository_gitlab_test.go
internal/goproxy/goproxy_test.go
internal/goproxy/test/test_utils.go
test/e2e/clusterctl_upgrade.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/common.go
test/e2e/config/docker.yaml
test/framework/clusterctl/e2e_config.go
test/framework/clusterctl/e2e_config_test.go

:sparkles: Resolve release markers

---

docs/book/src/reference/glossary.md

Fix typo in heading of "Cluster API Provider Outscale"

:seedling: Update glossary.md: Fix typo in level of heading.

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

This PR updates the supported versions for the next release cycle (1.7).
Task: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions
@kubernetes-sigs/cluster-api-release-team

📖 Update CAPI support and guarantees for v1.7

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/main.go
controllers/remote/cluster_cache_tracker.go
controlplane/kubeadm/main.go
docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
internal/controllers/cluster/suite_test.go
internal/controllers/machine/suite_test.go
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machinehealthcheck/suite_test.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/machineset/suite_test.go
internal/controllers/topology/cluster/suite_test.go
main.go
test/infrastructure/docker/main.go

🐛 Improve log k/v pairs and a improve/drop a few log lines

---

controlplane/kubeadm/internal/controllers/controller.go
internal/controllers/topology/cluster/cluster_controller.go

Makes the event recorder names consistent across all controllers (they are usually <controller-name>-controller)
Fixes #

⚠️ Make event recorder names consistent for KCP and topology controller

---

exp/internal/controllers/machinepool_controller_phases_test.go

If the bootstrap config reference changes, e.g. `KubeadmConfig/{a => b}`, CAPI would previously just return early if the bootstrap secret is ready instead of reconciling towards the new bootstrap config's `dataSecretName`. That was luckily already fixed by https://github.com/kubernetes-sigs/cluster-api/pull/8667. With _this_ PR, I want to add a test that covers the actual use case of switching to a bootstrap config within `MachinePool`.
Part of https://github.com/kubernetes-sigs/cluster-api/issues/8858 (specifically https://github.com/kubernetes-sigs/cluster-api/issues/8858#issuecomment-173793089 …

🌱 Add MachinePool test for switching bootstrap config to another ready/non-ready object with different name

---

controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go

I went over the entire KCP struct and audited for fields that can be mutated.
The goal was to avoid further PRs to make more fields mutable only after someone hit a problem
Fixes #

✨ KCP: Allow mutation of all fields that should be mutable

---

test/e2e/clusterctl_upgrade.go

Since #9799 we are testing the upgrade from v1.6. In v1.6 we introduced support for MachinePools in ClusterClass.
Before this PR we assumed that the number of expected machines is controlPlaneMachineCount+workerMachineCount
With this PR we are now taking a closer look at Cluster / MachineDeployment / MachinePool objects to calculate the actual expected count.
Fixes #9886

🐛 test/e2e: Calculate correct worker count in clusterctl upgrade test

---

test/e2e/data/infrastructure-docker/main/cluster-template-ignition/ignition.yaml
test/infrastructure/docker/internal/provisioning/ignition/kindadapter.go

While developing for k8s v1.29 support (#9872 and #9890) ignition tests started to fail because kube-proxy was not able to start due to the following error:
```
❯ k logs -n kube-system kube-proxy-brfk2
I1218 12:12:16.663929       1 server_others.go:72] "Using iptables proxy"
I1218 12:12:16.670800       1 server.go:1050] "Successfully retrieved node IP(s)" IPs=["172.18.0.5"]
I1218 12:12:16.671585       1 conntrack.go:118] "Set sysctl" entry="net/netfilter/nf_conntrack_max" value=196608
E1218 12:12:16.671607       1 server.go:556] "Error running ProxyServer" err="open /proc/sys/net/netfilter/nf_conntrack_max: permission denied"
E1218 12:12:16.671633       1 run.go:74] "command failed" err="open /proc/sys/net/netfilter/nf_conntrack_max: permission …
```

🐛 capd: fix ignition to also set the kube-proxy configuration to skip setting sysctls

---

Tiltfile
docs/book/src/developer/tilt.md
docs/book/src/reference/versions.md
docs/book/src/user/quick-start.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/e2e/quick_start_test.go
test/framework/bootstrap/kind_provider.go
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/kind/mapper.go

Modify quickstart and CAPD to use the new Kubernetes release:
* Bump the Kubernetes version in:
* `test/*`: search for occurrences of the previous Kubernetes version
* `Tiltfile`
* Ensure the latest available kind version is used (including the latest images for this kind release)
* Add new images in the [kind mapper.go](https://github.com/kubernetes-sigs/cluster-api/blob/48ae58e51f9723ab7b9635d0e05ee54c4843707a/test/infrastructure/kind/mapper.go#L79).
* See the [kind releases page](https://github.com/kubernetes-sigs/kind/releases) for the list of released images.
* Set new default image for the [test framework](https://github.com/kubernetes-sigs/cluster-api/blob/48ae58e51f9723ab7b9635d0e05ee54c4843707a/test/framework/bootstrap/kind_provider.go#L40) …

✨ v1.29: Prepare quickstart, capd and tests for the new release including kind bump

---

docs/book/src/user/quick-start.md

The manifests of the topology flavor for CAPD also include a MachinePool.
This flavor is used in quick-start which is why it should also note enabling the Machine Pool related feature gate.
Fixes #
/area docs

📖 capd: fix quickstart to also enable the machine pool feature gate

---

internal/util/ssa/patch_test.go

During the test at the additional Patch calls the defaulting webhook did always set the .spec.infrastructureRef.namespace field.
This caused flaky behaviour because there was a chance for the resourceVersion to getting bumped with the only change being the timestamp in managedFields.
This flake was reproducible by either the following command:
```
go test -race -count 120 -failfast -shuffle on -timeout 30s -run '^TestPatch$' sigs.k8s.io/cluster-api/internal/util/ssa
```
Or by adding a `time.Sleep(time.Second)` at:
https://github.com/kubernetes-sigs/cluster-api/blob/ec92803b4708c2e40656adfaaa6b4d22942f8d3f/internal/util/ssa/patch_test.go#L157
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

🐛 ssa: fix flaky test TestPatch/Test patch with Machine

---

docs/release/release-tasks.md

Relates to https://github.com/kubernetes-sigs/cluster-api/issues/9800
follow up from last v1.6 release cut

📖 update links in release tasks docs

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Fixes failing security scan: https://github.com/kubernetes-sigs/cluster-api/actions/runs/7321592425/job/19942156373

🌱 bump crypto dep version

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
cmd/clusterctl/client/cluster/mover.go
controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/internal/controllers/helpers.go
controlplane/kubeadm/internal/controllers/remediation.go
docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
exp/internal/controllers/machinepool_controller_noderef.go
exp/runtime/internal/controllers/extensionconfig_controller.go
internal/controllers/clusterclass/clusterclass_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
internal/controllers/machineset/machineset_controller.go
internal/controllers/topology/cluster/cluster_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machineset/machineset_controller.go
internal/hooks/tracking.go
test/framework/autoscaler_helpers.go
test/infrastructure/docker/internal/docker/machine.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
util/patch/patch.go

With this PR the patch helper returns errors with the entire available error context. Before this PR we only added error context in some cases and very inconsistently
Fixes #

🌱 Improve patch helper error handling

---

test/e2e/autoscaler_test.go

🌱 Bump cluster-autoscaler to v1.29.0

---

controlplane/kubeadm/internal/controllers/remediation.go
hack/tools/internal/log-push/main.go
internal/controllers/machinedeployment/machinedeployment_rolling.go
internal/controllers/machinedeployment/mdutil/util.go

🌱 Use min/max funcs from Go SDK

---

docs/book/src/developer/guide.md

This PR adds the 2023 KubeCon talks to the book.
Thx everyone for the talks :)
Fixes #

🌱 Add 2023 KubeCon talks to the book

---

test/e2e/autoscaler_test.go

Manual cherry-pick of #9942 
Fixes #

[release-1.6] 🌱 Bump cluster-autoscaler to v1.29.0

---

test/framework/cluster_topology_helpers.go

Tried to run an upgrade test without MachinePools and it didn't work anymore. I assume this affects plenty of other tests across core CAPI and providers.
Fixes #

🐛 Make MachinePools and MachineDeployments optional in ApplyClusterTemplateAndWait

---

test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/self_hosted.go
test/framework/cluster_topology_helpers.go
test/framework/controlplane_helpers.go

We should not force infra providers to set etcd and coreDNS version to be able to test Kubernetes upgrades (and thus have corresponding  etcd & coreDNS variables if they use ClusterClass)
Fixes #

🌱 Make etcd and CoreDNS optional in upgrade and self-hosted tests

---

Tiltfile
docs/book/src/developer/tilt.md
hack/tools/internal/tilt-prepare/main.go

Small improvement to tilt
- rename "kustomize_config" to a more explicit "apply_provider_yaml"
- add support for defining a "kustomize_folder" (defaults config/default)
- add support for defining "kustomize_options", e.g. `"kustomize_options": "--load-restrictor=LoadRestrictionsNone"`
- automatically scale down deployments to 1 + remove resource limits/requests when activating the debugger
/area devtools

🌱 Small improvements to tilt

---

Makefile
docs/release/release-tasks.md

After the last refactor the required CLI args and build steps are different.
In addition, fixing the build and test commands to work with go 1.21.
/area release

📖 Update instructions to generate release notes

---

test/e2e/scale_test.go

Drops the not necessary duplicated scale test.
Fixes #
/area testing

🌱 e2e: drop duplicated scale test

---

test/e2e/scale_test.go

Manual cherry-pick of #9968
Renames only the existing test to match the tests on the other branches (where we removed the test)

🌱 [release-1.5] e2e: Rename scale test to drop [Scale] tag

---

docs/book/book.toml

For this iteration, we'll keep using the 2023 agenda until the 2024 and the historical ones are available somewhere safe.
Fixes #

:book: Add /agenda redirect in book

---

internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
test/framework/finalizers_helpers.go
util/util.go

This PR adds a Watch on `Cluster` Resources in the topology based `MachineDeployment` controller, thereby triggering reconciliation on `Cluster` resource / status update.
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9532
/area testing

🌱 Watch for Cluster resources in topology MD controller

---

CONTRIBUTING.md
docs/book/src/developer/e2e.md

- change `InitManagementCluster` to `InitManagementClusterAndWatchControllerLogs`; otherwise it won't point to the correct reference link. ([current doc](https://cluster-api.sigs.k8s.io/developer/e2e#writing-portable-e2e-tests))
- change the heading level according to the context; otherwise, it might confuse users. ([current layout](https://cluster-api.sigs.k8s.io/contributing#contributing-guidelines))

📖 Fix function link reference and heading level

---

hack/tools/release/weekly/main.go

This PR fixes a small grammar mistake in the release script.
Area example:
/area release

:seedling: Fix grammar in release script

---

internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/topology/machinedeployment/machinedeployment_controller.go
test/framework/finalizers_helpers.go
util/util.go

This reverts commit a8dafb07a3f2e62e90ac9548205d798b73e2e9f1.
Reverting commit which is potentially the cause of CI Flakes ([example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1745396788560400384)) by PR https://github.com/kubernetes-sigs/cluster-api/pull/9865. 
Fixes #
/area testing

🐛 Revert "Watch for Cluster resources in topology MD controller"

---

test/framework/clusterctl/e2e_config.go
test/framework/clusterctl/e2e_config_test.go

This PR adds a deepcopy func for E2EConfig. This makes it a lot easier to overwrite configuration (mostly variables) for specific test cases without having to resort to workarounds like setting environment variables.
An example would be the following:
```go
var _ = Describe("When testing K8S conformance with K8S latest ci [Conformance]", func() {
capi_e2e.K8SConformanceSpec(ctx, func() capi_e2e.K8SConformanceSpecInput {
kubernetesVersion, err := kubernetesversions.LatestCIRelease()
Expect(err).NotTo(HaveOccurred())
localE2EConfig := e2eConfig.DeepCopy()
localE2EConfig.Variables["KUBERNETES_VERSION"] = kubernetesVersion
return capi_e2e.K8SConformanceSpecInput{
E2EConfig:             localE2EConfig, …
```

🌱 Add DeepCopy method for E2EConfig

---

test/framework/clusterctl/e2e_config.go
test/framework/clusterctl/e2e_config_test.go

[release-1.6] 🌱 Add DeepCopy method for E2EConfig

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
exp/addons/internal/controllers/clusterresourceset_controller.go
exp/internal/controllers/machinepool_controller.go
exp/internal/controllers/machinepool_controller_noderef.go
internal/contract/references.go
internal/controllers/clusterclass/clusterclass_controller_test.go
internal/controllers/clusterclass/suite_test.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machinedeployment/suite_test.go
internal/controllers/machineset/suite_test.go
internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/patches/engine.go
internal/controllers/topology/cluster/patches/template.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go
internal/test/builder/builders.go
test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go
test/infrastructure/docker/internal/controllers/dockermachine_controller_test.go

Today controller-runtime doesn't set the GVKs of objects in all cases.
The current state is:
* APIReader:
* sets GVK on Unstructured objects
* does not set GVK on regular typed objects
* Cached reader:
* sets GVK on Unstructured objects
* sets GVK on regular typed objects (if disableDeepCopy = false, which is default)
* fake client
* sets GVK on Unstructured objects
* sets GVK on regular typed objects
* Note: This will probably be changed with CR v0.17 (https://github.com/kubernetes-sigs/controller-runtime/pull/2633)
Because of these inconsistencies (that cannot be easily changed upstream) and because it's hard to tell across entire call stacks where objects come from I would suggest to only rely …

🌱 Stop relying on GVK being set on regular typed objects

---

test/framework/daemonset_helpers.go
test/framework/deployment_helpers.go

Implements `WatchDaemonSetLogsByLabelSelector` function.
Fixes #9983
/area test-framework

🌱 test/framework add WatchDaemonSetLogsByLabelSelector method

---

test/framework/kubernetesversions/versions.go
test/framework/kubernetesversions/versions_test.go

🌱 Add test util to resolve Kubernetes versions

---

Makefile
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
cmd/clusterctl/config/manifest/clusterctl-api.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepooltemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclustertemplates.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachinetemplates.yaml

🌱 Bump controller-tools to v0.14

---

api/v1beta1/condition_consts.go
internal/controllers/machine/machine_controller_noderef.go
internal/controllers/machine/machine_controller_test.go

🌱 Mark Machine healthy condition as unknown if we can't list wl nodes

---

docs/book/src/clusterctl/commands/upgrade.md

:book: add docs/examples for pre-release and nightly img version deployments with clusterctl

---

test/e2e/quick_start_test.go
test/framework/finalizers_helpers.go

Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9969
/area testing

🌱 test: add dynamic finalizer assertions for e2e framework

---

exp/runtime/topologymutation/walker.go

Use keys/values structured log interface
Previously, the log message was malformed, e.g.
```
"Generated patch (uid: %q): %q\n" template="infrastructure.cluster.x-k8s.io/v1beta1/DockerClusterTemplate" holder="cluster.x-k8s.io/v1beta1/Cluster/default/docker-quick-start" cc9b55a6-2ac0-470a-9b0e-444e5a08b5de="]"
```
With this change, the log message is:
```
"Generated patch" template="infrastructure.cluster.x-k8s.io/v1beta1/DockerClusterTemplate" holder="cluster.x-k8s.io/v1beta1/Cluster/default/docker-quick-start" uid="cc9b55a6-2ac0-470a-9b0e-444e5a08b5de" patch="]"
```
Fixes #

:bug: Use keys/values structured log interface

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Addresses CVE https://github.com/advisories/GHSA-9763-4f94-gfch
Fixes #

🌱 go.mod: bump github.com/cloudflare/circl to v1.3.7

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_test.go

As described in the issue, a failing drain can currently block a scalable resource scale down / delete operation transparently.
This PR attemps to fix this issue by adding `DrainingSucceededCondition` to the summary of `MachinesReadyCondition`, bubbling up the drain result in the `MachineSet` and in the `MachineDeployment` after https://github.com/kubernetes-sigs/cluster-api/pull/9262.
Fixes #9285
/area machine

🐛 Bubble up machine drain condition in `MachinesReadyCondition`

---

controlplane/kubeadm/internal/filters.go
controlplane/kubeadm/internal/filters_test.go

KCP uses the following method to update the coredns version, this does not require rolling updates of control plane nodes, and we can optimize it.
https://github.com/kubernetes-sigs/cluster-api/blob/9d36ddcbf8381574a86cebeacdcdfc85bafa71e9/controlplane/kubeadm/internal/controllers/controller.go#L466-L469
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9832
**Test**:
1. Create CAPI Cluster with dns config.
```
kc get kcp -n default hw-sks-test-no-gpu-controlplane -ojson | jq '.spec.kubeadmConfigSpec.clusterConfiguration.dns'
{
"imageRepository": "registry.smtx.io/kubesmart/coredns", …
```

🐛 Skip checking `clusterConfiguration.dns` fields when KCP checking MachineNeedRollout 

---

docs/book/src/clusterctl/commands/upgrade.md

Comment was incorrect, so I fixed it. Also rewrote it to be easier to digest for our users.
Fixes #

📖 Improve doc for clusterctl update test coverage

---

test/e2e/quick_start_test.go
test/framework/finalizers_helpers.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9970
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9969
/area testing

[release-1.6] :seedling: test: add dynamic finalizer assertions for e2e framework

---

hack/tools/release/weekly/main.go

Fix the branch name display issue after running the command `make release-weekly-update-tool` from branch other than `main`.
Example: Output of command after bug fix!!
```bash
$:: github.com/sigs.k8s.io/cluster-api ‹release-1.6*› » ./bin/weekly --from 2023-12-11 --to 2023-12-17 --milestone v1.7
Weekly update :rotating_light:
Changes from 2023-12-11 to 2023-12-17 a total of 7 new commits where merged into release-1.6.
- 1 :sparkles: New Features
- KCP: Allow mutation of all fields that should be mutable (#9885)
- 4 :bug: Bug Fixes
- capd: fix ignition to also set the kube-proxy configuration to skip setting sysctls (#9895)
- Improve log k/v pairs and a improve/drop a few log lines (#9880)
- ipam: fix webhooks using mixed api versions (#9863)
- …
```

:bug: Fix wrong branch name display for weekly update script

---

test/e2e/clusterctl_upgrade_test.go

Part of #9578
Bumps the k8s version used because the test now uses CAPI v1.6.1 which supports v1.29.0.
Fixes #
/area ci

🌱 test/e2e: bump WorkloadKubernetesVersion for v1.6 clusterctl upgrade test

---

OWNERS
OWNERS_ALIASES

First of all, @ykakarap thank you very much for all the work you did on Cluster API. It was always great working with you!!
This PR moves Yuvaraj to emeritus approver, given that he wasn't actively contributing for a while now and considering that we want to keep our OWNERS files reasonably up-to-date.
Fixes #

🌱 Move ykakarap to emeritus approvers

---

hack/tools/prowjob-gen/generator.go

Adjusts prowjob-gen to not create files which would have been empty otherwise.
Fixes #
/area ci

🌱 hack/prowjob-gen skip creating empty files

---

Makefile

Note: Previous version had some problems related to generics (we found this in controller-runtime)
Fixes #

🌱 Bump go-apidiff to v0.8.2

---

CONTRIBUTING.md
docs/book/src/reference/versions.md
docs/release/release-cycle.md

Considering the maturity of the release process and the maturity of the process we are using to validate support for new Kubernetes releases, I would like to propose the introduction in our release schedule of a new "extra" patch release to be created approximately one week after a new Kubernetes minor release is available.
This will ensure the project will quickly provide official support for new Kubernetes releases to Cluster API users.
Additionally, this PR clarifies the 4-month cadence which we are de-facto using (mostly a cleanup of leftovers from previous versions).
/area release
/hold 
For discussion in the next office hours meeting

🌱 Provide faster support for new k8s minor releases

---

cmd/clusterctl/hack/create-local-repository.py
docs/book/src/clusterctl/developers.md
metadata.yaml

Provide a quick solution to test nightly builds with clusterctl
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9999
/area devtools

🌱 Simplify testing nightly builds with clusterctl

---

cmd/clusterctl/cmd/completion.go

this commit adds completions for fish shell and completions have description enabled with them.
Fixes #9913

🌱 Add completion for fish shell

---

hack/docker-image-verify.sh
test/infrastructure/docker/Dockerfile

Follow up for https://github.com/kubernetes-sigs/cluster-api/pull/9932#discussion_r1461535941
Fixes #
/area ci

🌱 test: adjust capd dockerfile so the binary exposes the package in the built binraries path variable

---

CONTRIBUTING.md
docs/book/src/reference/versions.md
docs/release/release-cycle.md

Includes changes from #9971 #9972

[release-1.6] 📖 Sync version and release docs with main

---

docs/book/src/user/quick-start.md

Fixes #9953 
This PR renames the instances of "others..." tab to "Other providers..." in the quickstart guide.

📖 Rename "others..." tab with "Other providers..."

---

docs/book/src/clusterctl/commands/init.md
docs/book/src/clusterctl/provider-contract.md

This PR is a follow-up to the discussion in https://github.com/kubernetes-sigs/cluster-api/issues/9869, to avoid similar cases from happening again in the future.

🌱 Clarify rules for adding new clusterctl default providers

---

OWNERS
OWNERS_ALIASES

**What this PR does / why we need it**: Moving myself to emeritus. After 6+ years at Microsoft and the last 3+ years spent working with the Cluster API community, I've decided to try something new which means I'll have less time to dedicate to this project going forward. I am removing myself as an approver to make room for future approvers. I've learned so much from the folks in this community and am proud to see how far the project has come. I will still be around in the k8s slack, feel free to reach out! 
Fixes #

🌱 Move CecileRobertMichon to emeritus

---

OWNERS_ALIASES

This PR adds @chrischdi (that's me 😂 ) to cluster-api-maintainers.
I'm now working with the community and am contributing to the CAPI project for a good amount of time and also a reviewer for quite some time. I especially did work on ClusterClass features and on keeping the CI stable, deflaking issues, doing reviews, ... and want to continue with that in future.
I don't think we have the data quality to filter down for those specific areas so I'll just list all CAPI contributions:
* PRs: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Achrischdi+sort%3Aupdated-desc
* Reviews: https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Achrischdi+is%3Aclosed
* Issues: …

🌱 Promote chrischdi to Cluster API maintainer

---

test/framework/bootstrap/kind_provider.go
test/framework/bootstrap/kind_util.go

Support configuring ExtraPortMappings for the kind cluster created in e2e test. So the workload cluster nodes can access the service exposed via NodePort in the kind cluster. Refer to https://kind.sigs.k8s.io/docs/user/configuration/#nodeport-with-port-mappings.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the 
issue(s) when PR gets merged)*:
Fixes #

🌱 test/e2e: Support configuring ExtraPortMappings for the kind cluster

---

Makefile

For the image builds that do require a Dockerfile not located in the root directory, this implements the workaround metioned here: https://github.com/moby/buildkit/issues/1368#issuecomment-738015222 for avoiding an incorrectly cached Dockerfile
All of the unmodified `docker-build-*` targets leverage the `--build-arg package` option and intentionally use the same Dockerfile located in the root dir
Fixes #9752
details of findings in this comment: https://github.com/kubernetes-sigs/cluster-api/issues/9752#issuecomment-1873048812
/area release

🌱 read in dockerfiles from stdin 

---

Makefile

Failed build (https://prow.k8s.io/log?job=post-cluster-api-push-images&id=1750536211677581312) after merge due to incorrect Dockerile being read in for clusterctl after merging this pr: https://github.com/kubernetes-sigs/cluster-api/pull/9990

🌱 fix dockerfile for clusterctl build

---

controllers/remote/cluster_cache_tracker.go

Decouple the code that creates uncached client from the code that creates the cached client. This way, we don't start the cache until the cached client is created.
This avoids scenarios where the `ClusterCacheTracker` cache is started when only an uncached client is needed.
There is an existing code path, described in the original issue, where the `ClusterCacheTracker` cache is started when only an uncached client is needed. The cache is re-created later, and the initial cache is still running continuously in the background.
Fix the memory leak described in the issue https://github.com/kubernetes-sigs/cluster-api/issues/9542, when cluster `kubeconfig` is rotated frequently,
Fixes #9542

🐛 Fix ClusterCacheTracker memory leak

---

cmd/clusterctl/cmd/init.go

…r repository info and configurations
Refining the "clusterctl init --help" command documentation. As `clusterctl config provider` is modified to used `clusterctl config repositories` updated the document for the same.
Fixes #9374 

📖 Refining 'cluster init --help' command documentation

---

test/e2e/scale.go
test/e2e/scale_test.go
test/framework/cluster_topology_helpers.go
test/framework/controlplane_helpers.go
test/framework/machine_helpers.go
test/infrastructure/inmemory/pkg/server/api/handler.go
test/infrastructure/inmemory/pkg/server/mux_test.go

Add upgrades to the Cluster API scale tests.
Part of #8814

:seedling: Add scale testing for upgrades

---

docs/proposals/20181121-machine-api.md

Fixup a link to v1alpha4 go code in an older proposal.
/area documentations

:bug: Fix link to v1alpha4 types

---

test/e2e/autoscaler.go
test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_runtimesdk.go
test/e2e/clusterclass_changes.go
test/e2e/clusterclass_rollout.go
test/e2e/clusterctl_upgrade.go
test/e2e/common.go
test/e2e/k8s_conformance.go
test/e2e/kcp_adoption.go
test/e2e/kcp_remediations.go
test/e2e/machine_pool.go
test/e2e/md_remediations.go
test/e2e/md_rollout.go
test/e2e/md_scale.go
test/e2e/node_drain_timeout.go
test/e2e/quick_start.go
test/e2e/scale.go
test/e2e/self_hosted.go

This PR adds a new PostNamespaceCreated to all E2E tests input objects, thus allowing to inject a function to be run after the test namespace is created. If not specified, this is a no-op.
This can be useful to apply environment settings that apply at the namespace level, eg. setting ResourceQuotas
/area E2E-testing

🌱 Add PostCreateNamespace hook to E2E tests

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md
docs/book/src/reference/jobs.md

Updated the jobs.md and got rid of some toil. Not very useful to try to keep this doc 100% up-to-date with links etc. if we can just link to the source of truth instead.
Part of #10062

🌱 Update jobs.md and make it version-independent

---

exp/runtime/topologymutation/errors.go
exp/runtime/topologymutation/variables.go
exp/runtime/topologymutation/variables_test.go
test/extension/handlers/topologymutation/handler.go

Add more function. For example to unmarshal nested variable from topology spec, and unmarshal bool variable from topology spec.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9669

🌱Add more helper functions in topologymutation varaible.go to help unmarshal variables

---

scripts/ci-e2e-lib.sh
scripts/ci-e2e.sh
test/e2e/k8s_conformance_test.go

🌱 Fix ci-latest test to actually use ci latest

---

scripts/ci-e2e-lib.sh

Fixes the error:
```
/home/prow/go/src/sigs.k8s.io/cluster-api/scripts/ci-e2e-lib.sh: line 71: GINKGO_FOCUS: unbound variable
```
introduced in #10080 .
Fixes #

🐛 ci: fix unset GINKGO_FOCUS variable

---

cmd/clusterctl/cmd/init.go

Remove example from --runtime-extension flag in clusterctl as clusterctl doesn't include any default runtime extensions.
Fixes #9796 

📖 Remove example from --runtime-extension flag in clusterctl

---

test/infrastructure/container/docker.go

If btrfs or zfs is used CAPD adds the /dev/mapper mount twice. This PR ensures we only do it once.
xref to where kind implements this:  https://github.com/kubernetes-sigs/kind/pull/1464
Fixes #8317

:bug: remove duplicate fix for btrfs/zfs support

---

test/e2e/quick_start.go

This allows folks using the E2E test quick start to use deterministic cluster names
Area example:

🌱 Allow to specify cluster name for E2E quick-start

---

Makefile
cloudbuild.yaml

This reintroduces changes made in: https://github.com/kubernetes-sigs/cluster-api/pull/9536
Last time this change was merged it exposed use to a bug in the docker build server version we are using and the change was reverted.  Details here: https://github.com/kubernetes-sigs/cluster-api/issues/9752
---
This change has been merged to prevent this bug from occurring: https://github.com/kubernetes-sigs/cluster-api/pull/9990
And we have also introduced an additional step in the `release-staging` target to ensure the images contain the expected binaries: https://github.com/kubernetes-sigs/cluster-api/pull/9932
/area release

🌱 improve release-staging build

---

docs/book/src/user/quick-start.md

Tab content was added to the quick start guide for k0smotron, but the tab heading was missed. This results in selecting anything after the IBM provider tab displaying the incorrect provider information.
This adds the tab title so the tabs and their contents match up correctly.
Fixes #10098

📖 Add provider tab for k0smotron

---

test/framework/clusterctl/client.go
test/framework/clusterctl/clusterctl_config.go
test/framework/clusterctl/repository.go

In CAPV we made a copy of the `copyAndAmendClusterctlConfig` function because it was very useful in tests.
In CAPV we use it to dynamically set a variable for different tests.
This PR makes the function `CopyAndAmendClusterctlConfig` and struct `CopyAndAmendClusterctlConfigInput` public so providers could make use of the function.
Fixes #

🌱 test/framework: expose CopyAndAmendClusterctlConfig function

---

docs/book/src/user/quick-start.md

The ProxMox initialization steps mention adding the IPAM provider to the config file. This is the first mention of the config file in the doc, with very little context as to what it is or how to work with it.
This updates the text to also provide a link to the clusterctl config documentation to make it easier to find out more about what is being asked. It also updates the path given to the current XDG-based path instead of the older `$HOME/.cluster-api` directory path.

📖 Update reference to clusterctl config file

---

cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/crd_migration.go
cmd/clusterctl/client/cluster/upgrader.go

Add public function to create new CRD migrator, we would like to reuse the code in CAPI Operator helm chart hook to help migrate CRDs if needed.
Fixes #

✨ clusterctl: Add public function to create new CRD migrator

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.14.1
**Which issue(s) this PR fixes:**
Fixes #10112

🌱 Bump cert-manager to v1.14.1

---

docs/release/release-tasks.md

Clarify Netlify update steps in release tasks
Fixes #9850
/area release

📖 clarify netlify release guidance

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.14.2
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/10123
~~Testing test flake  https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-conformance-ci-latest-main
https://github.com/cert-manager/cert-manager/releases/tag/v1.14.1~~
~~These issues may not be related with the above flake.~~
_Edited: test flake not caused by cert-manager uplift_

🌱 Bump cert-manager to 1.14.2

---

test/infrastructure/inmemory/api/v1alpha1/inmemorycluster_types.go
test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
test/infrastructure/inmemory/pkg/server/listener.go
test/infrastructure/inmemory/pkg/server/mux.go
test/infrastructure/inmemory/pkg/server/mux_test.go

With this PR it is now possible to use different resource group and listener name with the in-memory server.
This will greatly simplify using the in-memory server in context where the control plane endpoint and the in-memory resources are managed separately or where the name of the cluster is not known in advance, e.g. E2E tests
Note: for convenience we will continue to use the same name for resource group and listener within the in-memory, but this is not required anymore for other consumers of the in-memory server
/area provider/infrastructure-in-memory

🌱 Allow using different resource group and listener name with the in memory server

---

docs/book/src/user/quick-start.md

Provides instructions for users to set up OpenStack as an external cloud provider.

📖 Add OpenStack to External Cloud Providers in quick-start.md

---

internal/controllers/machine/machine_controller.go

Changes the log output when skipping Node deletion in a Cluster so it's clearer that reconciliation does not stop. This has lead to confusion at least once (#10129).

🌱 be more explicit when skipping node deletion

---

docs/release/release-tasks.md
hack/tools/go.mod
hack/tools/go.sum
hack/tools/release/weekly/main.go

Currently, the usage of the weekly PR update generation script is a bit confusing because it requires checking out the right branches as well as providing the right milestones for these branches. This PR attempts to address this issue by clarifying the documentation and updating the script to only use the branch parameter for the whole flow.
This PR updates the `Generate weekly PR updates to post in Slack` flow:
- the script has been updated 
- it now pulls from github instead of needing a local correct checkout and right branch
- the time range was previously off by a day, this is now fixed
- `--milestone` is now `--branch` and should no more cause confusion between the relationship of branch to milestone
- a parameter check for `--branch` was …

🌱 Improve weekly PR update generation script and documentation

---

bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
bootstrap/kubeadm/internal/controllers/token.go
controllers/remote/cluster_cache_tracker_fake.go
exp/internal/controllers/machinepool_controller_phases_test.go
internal/controllers/machine/machine_controller_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go

Right now, the bootstrap token is refreshed every time until nodes have joined. This creates unnecessary etcd writes. Only extend the expiry timestamp (called "refresh" in code) if we're getting a bit closer to reaching it. Particularly if KubeadmConfig reconciliation is triggered from other sources than CAPA's `RequeueAfter` interval, this can pile up to quite noisy logs and API accesses.
Along the way, I did some other improvements and will add inline comments to explain.
This was a drive-by along the way of fixing https://github.com/giantswarm/roadmap/issues/2217, but isn't really related. …

🐛 Only refresh bootstrap token if needed, requeue in all cases where node hasn't joined yet

---

.golangci.yml
cmd/clusterctl/client/client.go
cmd/clusterctl/cmd/topology_plan.go
docs/book/src/clusterctl/commands/alpha-topology-plan.md

🌱 Deprecate clusterctl alpha topology plan

---

test/framework/clusterctl/client.go

Just noticed that this is hard-coded only for the `Init` func but not `InitWithBinary`. Shouldn't make much difference as we wait for controller deployments anyway in InitManagementClusterAndWatchControllerLogs. Nevertheless it's better this way.
Fixes #

🌱 Use --wait-providers in test framework InitWithBinary func

---

test/framework/clusterctl/clusterctl_helpers.go

Introducing the new test upgrading from v0.3.x lead to some flakes in CI.
This PR will fix the flakes. The new tests are entirely stable on release-1.6, because on release-1.6 we still exclude this namespace (it was only missing on main)
Fixes #

🐛 Re-introduce exclude capi-webhook-system to fix test flake

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
Tiltfile
cmd/clusterctl/client/move.go
exp/runtime/hooks/api/v1alpha1/discovery_types.go
exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
hack/ensure-go.sh
internal/controllers/machinedeployment/machinedeployment_controller.go
internal/topology/check/compatibility.go
internal/webhooks/cluster.go
test/framework/machinedeployment_helpers.go
test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
test/infrastructure/inmemory/internal/server/mux_test.go
util/version/version.go

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/10025

[release-1.5] 🌱 Bump Go to 1.21.5 

---

internal/controllers/clusterclass/clusterclass_controller_test.go
internal/webhooks/cluster_test.go
internal/webhooks/clusterclass_test.go
internal/webhooks/patch_validation_test.go

This PR adds unit tests for MachinePool workers in ClusterClass for the following files:
- internal/webhooks/cluster_test.go
- internal/webhooks/clusterclass_test.go
- internal/webhooks/patch_validation_test.go
- internal/controllers/clusterclass/clusterclass_controller_test.go
Fixes part of #10028

🌱 Add unit tests for MachinePools for webhooks and cc controller

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machine/machine_controller_test.go

This fixes a race condition in the machine controller when the controller is restarted after a machine has been marked for deletion but before the infra machine or bootstrap config are deleted. In that case, the controller doesn't have watches on those external objects, so the reconciliation is not triggered once they are deleted. This means that Machines stay in Deleting state for the resync period, the default is 10 minutes.
/area machine

🐛 Watch external objects for machine before deleting

---

docs/book/src/user/quick-start.md

In quick start documentation we have some incorrect urls for downloading `clusterawsadm`. This PR mainly fixes the urls for Linux and MacOS operating systems. As #9870 is fixing it for Windows.
Fixes #10169 
Fixes #9795

🐛 Fix broken release links for clusterawsadm in Quick starts

---

docs/book/src/reference/providers.md
docs/book/src/user/quick-start.md

The CAPG docs are now available as a book at https://cluster-api-gcp.sigs.k8s.io/. This PR updates links in the CAPI book to point to the new CAPG book.
Fixes #

:book: docs: add links to capg book

---

internal/controllers/machine/machine_controller.go
internal/controllers/machine/machine_controller_phases.go
internal/controllers/machine/machine_controller_test.go

Backport of https://github.com/kubernetes-sigs/cluster-api/pull/10041
This fixes a race condition in the machine controller when the controller is restarted after a machine has been marked for deletion but before the infra machine or bootstrap config are deleted. In that case, the controller doesn't have watches on those external objects, so the reconciliation is not triggered once they are deleted. This means that Machines stay in Deleting state for the resync period, the default is 10 minutes.
/area machine

[release-1.6] 🐛 Watch external objects for machine before deleting

---

test/e2e/quick_start_test.go

:seedling: test: combine Finalizers tests to default quick start tests

---

controlplane/kubeadm/internal/controllers/controller_test.go
controlplane/kubeadm/internal/controllers/fakes_test.go
controlplane/kubeadm/internal/controllers/upgrade.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go
controlplane/kubeadm/internal/workload_cluster.go
controlplane/kubeadm/internal/workload_cluster_coredns.go
controlplane/kubeadm/internal/workload_cluster_coredns_test.go
controlplane/kubeadm/internal/workload_cluster_etcd.go
controlplane/kubeadm/internal/workload_cluster_etcd_test.go
controlplane/kubeadm/internal/workload_cluster_test.go

This PR aims at:
1. Enabling mutation of [FeatureGates](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/api/v1beta1/kubeadm_types.go#L143) in webhooks
2. Updating the target field for FeatureGates in Kubeadm config map
3. Reducing the number of API calls to update Kubeadm config map to 1 
Fixes #10050
/area api

✨ enable kubeadm feature gates mutation

---

Tiltfile
docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md
docs/book/src/developer/tilt.md
docs/book/src/user/quick-start.md
hack/ensure-kind.sh
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/docker.yaml
test/framework/bootstrap/kind_provider.go
test/go.mod
test/go.sum
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/kind/mapper.go
test/infrastructure/kind/mapper_test.go

🌱 bump kind version to v0.22.0

---

CHANGELOG/v1.5.6.md
CHANGELOG/v1.6.2.md

🌱Changelog entry to include cert-manager to v1.14.2

---

internal/controllers/machinedeployment/machinedeployment_controller_test.go
internal/controllers/machinedeployment/machinedeployment_sync.go

This is a follow-up from: https://github.com/kubernetes-sigs/cluster-api/pull/10124/files#r1484483425
This code recently got changed in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/10124/files#diff-d9a80cabbd6ae2ad7412b4e57a7f3d474b4816a021e4b84987c0895c6b1189c6R117
Before that, when calling `r.updateMachineDeployment` did never make any sense, because inside the anonymous function we never passed through the variable from the function, but our global machinedeployment instead.
So technically we already always used patching using `defer` instead of immediately patching the object.
There also seems to be no race when patching in defer, because the annotation gets never read **from the machinedeployment**. (We read it from …

🌱 machinedeployment: set revision on machinedeployment and patch via defer

---

cmd/clusterctl/client/repository/overrides.go

Aids troubleshooting when dealing with overrides, at least it helped me when looking at #10179 

:seedling: Better verbose logging on override path

---

test/e2e/data/kubetest/conformance.yaml
test/e2e/data/kubetest/dualstack.yaml

🌱 Fixing kubetest warnings for deprecations

---

cmd/clusterctl/cmd/generate_cluster.go

Cobra nicely adds the default value for arguments, except in the case where the default is 0 or empty. This causes the help output for `clusterctl generate cluster` `--worker-machine-count` to not include its default of 0, unlike `--control-plane-machine-count` that has a default of 1.
This change explicitly adds the default value to the help text for `--worker-machine-count` to make it easier to discover what to expect when running the command without this argument.
Help text after this change:
```txt
--worker-machine-count int           The number of worker machines for the workload cluster. (default 0)
```
Fixes #10173

🌱 clusterctl: Add 0 default to worker-machine-count help

---

test/framework/alltypes_helpers.go

This should avoid 6 minutes of retry in case of E2E where the workload cluster cannot be reached from the machine running the test
Area example:
/area ci

 🌱 Add fail fast to DumpResourcesForCluster in case of no route to host

---

bootstrap/kubeadm/config/manager/manager.yaml

Add pod metadata to capbk manager manifests. This
will allow the ClusterCacheTracker to access the
cluster directly when possible
Fixes #10165 

:seedling: Add pod metadata to capbk manager

---

test/infrastructure/inmemory/pkg/server/mux.go

This PR makes the in-memory API server wait slightly more before declaring an error on startup; this could help when starting many instances in parallel.
Area example:
/area provider/infrastructure-in-memory

🌱 Make in memory API server more tolerant when starting

---

cmd/clusterctl/cmd/root.go

This PR moves the call to `handlePlugins()` from `init()` to `Execute()`.
Calling `handlePlugins()` at the init function leads to not being able to debug tests using dlv, instead it exits with the following error message:
```
Error: flags cannot be placed before plugin name: -test.run
```
Reason for that is that the test execution will try to run a plugin because running tests provides args. At the end it always exits with an error and `os.Exit(1)` here:
https://github.com/kubernetes-sigs/cluster-api/blob/02b8789fd75b8065a5491065dbd4e7887644b09a/cmd/clusterctl/cmd/root.go#L221
Moving the call to `handlePlugins` from the init function to `Execute` leads to not running it when running tests.
Found this while trying to investigate the following test: …

🐛 clusterctl: move handlePlugins function call out of init to allow debugging tests

---

test/e2e/data/kubetest/conformance.yaml
test/e2e/data/kubetest/dualstack.yaml

Reverting ginkgo.show-node-events to ginkgo.progress, because older versions of the kubetest images we use (depends on k8s version) have a too old ginkgo version. Tests are failing because of it: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-upgrade-1-24-1-25-main/1762531387493060608
Fixes #

🐛 Reverting ginkgo.show-node-events to ginkgo.progress

---

Makefile
cloudbuild.yaml

Backport of https://github.com/kubernetes-sigs/cluster-api/pull/10095
removes the `docker-image-verify` sub-make from `release-staging` as [the PR](https://github.com/kubernetes-sigs/cluster-api/pull/9932) introducing it was not backported
/area release

[release-1.6] 🌱 improve release-staging build

---

Makefile
cloudbuild.yaml

Backport of https://github.com/kubernetes-sigs/cluster-api/pull/10095
removes the `docker-image-verify` sub-make from `release-staging` as [the PR](https://github.com/kubernetes-sigs/cluster-api/pull/9932) introducing it was not backported
/area release

[release-1.5] 🌱 improve release-staging build

---

docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
docs/book/src/tasks/certs/using-custom-certificates.md

This documents a change in requirements for user provided certificates
Fixes #9568

📖 Document changes to BYO certificates

---

test/infrastructure/container/docker.go

Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8376#issuecomment-1921871963
Support for btrfs/zfs was upstreamed to kind in https://github.com/kubernetes-sigs/kind/pull/1464, removing the need for us to hack support in ourselves.
Helps https://github.com/kubernetes-sigs/cluster-api/issues/8317
chore: PR feedback
Removes the now-unused function mountDevMapper(...)
chore: fix ci lint
fix: restore missing storage consts
chore: fix bad rebase
mountDevMapper() is unused
Fixes #

🐛 [release-1.6] fix(capd): remove hack for btrfs/zfs support

---

docs/book/book.toml

:book: Update agenda links w/ shared drive

---

docs/book/src/user/quick-start.md

Tab content was added to the quick start guide for k0smotron, but the tab heading was missed. This results in selecting anything after the IBM provider tab displaying the incorrect provider information.
This adds the tab title so the tabs and their contents match up correctly.
- #10099
Fixes #
/area book

[release-1.6] 📖 Add provider tab for k0smotron

---

Tiltfile
hack/tools/internal/tilt-prepare/main.go

With this PR it is now possible to use tilt providers with probuilt images (images already pushed somewhere, not manage by tilt build_docker_image).
This is useful for test published images, and it came at the cost that for those images it is not possible to activate debud/live reload, which is acceptable for the given use case.
/area devtools

🌱 Allow tilt provider with pre-build images

---

test/framework/alltypes_helpers.go

A small improvement trying to save time on E2E tests when bumping resources and the API server is not reacheable from the machine where E2E tests are running
/area ci

🌱 DumpResourcesForCluster should fail fast for i/o errors

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

manual backport of: https://github.com/kubernetes-sigs/cluster-api/pull/10248

[release-1.6] 🌱 bump protobuf to v1.33.0 to address CVEs

---

docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md

Fix a flaky link in the provider implementers guide.
Replace the link with a simple definition.

📖  Fix flaky link in docs

---

CHANGELOG/v1.6.3.md

🌱  Release v1.6.3

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.14.4
Fixes #10266

🌱 Bump cert-manager to 1.14.4

---

Makefile

No idea what is different in that version, I couldn't find release notes. But should be fine to bump.
Fixes #

🌱 Bump govulncheck to v1.0.4

---

hack/tools/release/internal/update_providers/README.md
hack/tools/release/internal/update_providers/provider_issues.go
hack/tools/release/internal/update_providers/provider_issues_test.go

- This PR helps streamlines the documentation team's effort while updating providers for a new beta release.
- We export `RELEASE_TAG` before running `make promote-images` as part of release process. I noticed that the same `RELEASE_TAG` cannot be used before running `make release-provider-issues-tool`.
-  `release-provider-issues-tool` expected users to `export RELEASE_TAG` as `1.7.0` whereas the release team initially sets `RELEASE_TAG` to `v1.7.0-beta.0` during the release workflow. 
- Since this tool (`release-provider-issues-tool`) is only expected to run once every release, i.e., at the time of releasing a beta version, it is important that we streamline the `RELEASE_TAG` to one format to avoid any user errors.
- I have also added supporting …

🐛 Add tests and update provider_issues.go

---

test/framework/clusterresourceset_helpers.go
test/framework/clusterresourceset_helpers_test.go

Check all bindings to see if the resource is applied. If multiple ClusterResourceSets match a cluster, the ClusterResourceSetBinding will have multiple bindings and so only the ResourceSetBinding related to the specific ClusterResourceSet must be checked.
I discovered this when using the e2e test framework in an external project that applied multiple ClusterResourceSets to a cluster as part of the e2e tests.

:seedling: Fix CRS e2e helper with multiple bindings

---

errors/pointer.go
exp/internal/controllers/machinepool_controller_phases.go
internal/controllers/machine/machine_controller_phases.go

🐛  Use ptr instead of own implementation

---

cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
cmd/clusterctl/client/cluster/assets/topology-test/existing-my-second-cluster.yaml
cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
docs/book/src/clusterctl/commands/alpha-topology-plan.md
docs/book/src/tasks/bootstrap/kubeadm-bootstrap/index.md
docs/book/src/tasks/bootstrap/kubeadm-bootstrap/kubelet-config.md
internal/controllers/topology/cluster/reconcile_state_test.go
test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.5/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-docker/v1.6/bases/cluster-with-kcp.yaml
test/e2e/data/infrastructure-docker/v1.6/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml
test/infrastructure/docker/templates/clusterclass-quick-start.yaml
test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml

See https://github.com/kubernetes/kubernetes/issues/123804
See https://github.com/kubernetes/kubernetes/issues/123804#issuecomment-1985360589

:bug: remove --enable-hostpath-provisioner flag

---

hack/tools/internal/tilt-prepare/main.go

This PR creates a ` updateNamespacePodSecurityStandard` function to ensure that the `pod-security.kubernetes.io/enforce` label is set to `"privileged"` for Namespace objects. This change is essential for compatibility with CAPIs tilt-prepare and Tiltfile when using CAPM3 (and other providers?), where accessing securityContext is required. Without this update, the existing pod-security policy restricts the usage of securityContext, hindering necessary operations. This aligns the behavior with CAPD, where the privileged policy is already set for Namespace objects.
/area  provider/infrastructure-in-memory

🌱 Implement privileged namespace security policy update for tilt-prepare

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Bumps [github.com/docker/docker](https://github.com/docker/docker) from 25.0.4+incompatible to 25.0.5+incompatible.
Dependabot will probably get around to this, but I wanted to update it because it's problematic for CAPZ incorporating CAPI v1.7.0-beta.0. Docker becomes an indirect import in CAPZ, and then our dependency checker fails:
See https://github.com/advisories/GHSA-mq39-4gv4-mvpx
See kubernetes-sigs/cluster-api-provider-azure#4646
/area security

🌱 bump github.com/docker/docker from 25.0.4+incompatible to 25.0.5+incompatible

---

webhooks/alias.go

Uses the alias instead of the internal Interface when defining the Cluster struct.
Follow-up for #10063
Fixes #

🌱 webhooks: use the alias for ClusterCacheTrackerReader instead of the internal reference

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Fixes failing security scan: https://github.com/kubernetes-sigs/cluster-api/actions/runs/8419719374/job/23052938445
follow up to https://github.com/kubernetes-sigs/cluster-api/pull/10302

[release-1.6]🌱 bump docker to address CVE

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Fixes failing security scan: https://github.com/kubernetes-sigs/cluster-api/actions/runs/8419719374/job/23052938757
follow up to https://github.com/kubernetes-sigs/cluster-api/pull/10302

[release-1.5]🌱 bump docker to address CVE

---

Makefile
hack/verify-go-directive.sh

🌱 Added go directive test

---

test/e2e/clusterctl_upgrade.go

trying to fix the flake mentioned here: https://github.com/kubernetes-sigs/cluster-api/issues/9688#issuecomment-1988364796

🐛 Add wait for MachineList to be available

---

test/infrastructure/inmemory/pkg/server/api/const.go

... because the service account reconciler in CAPV needs it! 😉 
/area provider/infrastructure-in-memory

🌱 Add namespaces to the list of resource handled by the in-memory API server

---

internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go

🐛 Fix for TestServerSideApplyWithDefaulting

---

bootstrap/kubeadm/config/manager/manager.yaml
config/manager/manager.yaml
controlplane/kubeadm/config/manager/manager.yaml
controlplane/kubeadm/config/rbac/role.yaml
controlplane/kubeadm/internal/controllers/controller.go
controlplane/kubeadm/main.go
docs/book/src/developer/testing.md
docs/book/src/developer/tilt.md
docs/book/src/tasks/experimental-features/experimental-features.md
docs/book/src/tasks/experimental-features/machine-pools.md
docs/book/src/user/quick-start.md
exp/internal/controllers/machinepool_controller_phases_test.go
exp/internal/webhooks/machinepool_test.go
feature/feature.go
internal/controllers/topology/cluster/cluster_controller_test.go
internal/controllers/topology/cluster/reconcile_state_test.go
test/infrastructure/docker/config/manager/manager.yaml

Sets the default for `EXP_MACHINE_POOL` to `true`, so MachinePools are an "always on" feature (unless the user disables it).
This seems like the first step en route to moving MachinePools to beta status based on discussion at last week's community meeting, but please let me know if there are other prerequisites or details I've missed.
Refs #9005

⚠️ Set MachinePool feature flag default to true + Beta

---

internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go

This PR fixes https://github.com/kubernetes-sigs/cluster-api/issues/10275 and improves how the topology controller handles referenced objects in case of errors, and more specifically
- if InfrastructureCluster is created, but ControlPlane creation fails, InfrastructureCluster is tracked (the issue)
- if infrastructureMachineTemplate is created, but ControlPlane creation fails, infrastructureMachineTemplate is cleaned up
- if infrastructureMachineTemplate is created, but an error happens before MD is created, infrastructureMachineTemplate is cleaned up
- if bootstrapTemplate is created, but an error happens before MD is created, bootstrapTemplate is cleaned up
- if infrastructureMP is created, but an error happens before MP is created, …

🐛 Improve handling of topology orphaned objects 

---

internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go

manual backport of https://github.com/kubernetes-sigs/cluster-api/pull/10277
/cc @sbueringer @chrischdi

[release-1.6] 🐛 Improve handling of topology orphaned objects

---

CHANGELOG/v1.7.0-beta.0.md
CHANGELOG/v1.7.0-beta.1.md

This PR fixes the release notes for v1.7.0-beta.0 and v1.7.0-beta.1. It called the release a RELEASE CANDIDATE instead of a BETA RELEASE.
/area release

:book: Change release candidate to beta in beta release notes

---

config/manager/manager.yaml
docs/book/src/developer/testing.md
docs/book/src/developer/tilt.md
docs/book/src/tasks/experimental-features/cluster-resource-set.md
docs/book/src/tasks/experimental-features/experimental-features.md
docs/book/src/user/quick-start.md
test/e2e/config/docker.yaml

Updates the documentation (and two manifests) to reflect the status of the ClusterResourceSet experimental feature as Beta and `true` by default.
When creating a PR to promote the MachinePools experimental feature to Beta / `true`, it seemed there was similar cleanup that should be done to CRS.
N/A, but see also #10141

📖 Update docs for beta ClusterResourceSet

---

docs/release/release-tasks.md
hack/tools/release/notes/main.go
hack/tools/release/notes/print.go

Currently the tool prints the same warning for both beta and rc releases.
This PR removes the parameter `--pre-release-version` and let the binary determine from the given tag what type of release it is.
Related to https://github.com/kubernetes-sigs/cluster-api/pull/10323
/area release

🌱 Determine release type from tag to also handle beta releases

---

internal/controllers/clusterclass/clusterclass_controller_test.go

As a follow up to #10337 where I missed using the correct `testing.T`:
This helps to show the individual table test which failed to do an assertion.
/area testing

🐛 Fix using corerect testing.T when creating gomega object

---

hack/tools/release/notes/generator.go
hack/tools/release/notes/list.go
hack/tools/release/notes/main.go
hack/tools/release/notes/print.go
hack/tools/release/notes/process.go

Add expander in generated release notes
```bash
./bin/notes --release v1.6.0 --pre-release-version true > CHANGELOG/v1.6.0.md
$ cat CHANGELOG/v1.6.0.md 
🚨 This is a RELEASE CANDIDATE. Use it only for testing purposes. If you find any bugs, file an [issue](https://github.com/kubernetes-sigs/cluster-api/issues/new).
- Management Cluster: v1.**X**.x -> v1.**X**.x
- Workload Cluster: v1.**X**.x -> v1.**X**.x
[More information about version support can be found here](https://cluster-api.sigs.k8s.io/reference/versions.html)
* REPLACE ME
REPLACE ME: A couple sentences describing the deprecation, including links to docs.
* [GitHub issue #REPLACE ME](REPLACE ME)
- 417 new commits merged
- 6 breaking changes :warning:
- 16 feature additions ✨
- 46 bugs fixed …
```

:sparkles: Add release notes expander functionality

---

docs/book/src/SUMMARY.md
docs/book/src/user/manifesto.md

Taking inspiration from [Tim Hockin’s talk at KubeCon NA 2023](https://www.youtube.com/watch?v=WqeShpaztZY), also for
Cluster API project is important to define the long term vision, the manifesto of “where we are going” and “why”.

📖 Cluster api manifesto

---

.github/workflows/pr-md-link-check.yaml

This PR sets linkchecker base branch to release-1.6 
/area ci

🌱 [release-1.6] Set linkchecker base branch to release-1.6

---

internal/controllers/topology/cluster/desired_state.go
internal/controllers/topology/cluster/desired_state_test.go
internal/controllers/topology/cluster/reconcile_state.go
internal/controllers/topology/cluster/reconcile_state_test.go

manual backport of https://github.com/kubernetes-sigs/cluster-api/pull/10277
/cc @sbueringer @chrischdi

[release-1.5] 🐛 Improve handling of topology orphaned objects

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum
test/infrastructure/container/docker.go

manually bumps github.com/docker/docker from 25.0.5+incompatible to 26.0.0+incompatible
Ref: https://github.com/kubernetes-sigs/cluster-api/pull/10322
Fixes #

🌱 bump docker/docker to 26.0.0+incompatible

---

docs/release/release-tasks.md

Adds more explanation on how to generate prowjob configuration on release-tasks.md file
Area example:

 📖 Improve clarity of prowjob configuration regeneration instructions

---

docs/release/release-tasks.md

During the `v1.7-rc.0` release both release lead + ci opened the same pr due to duplicated task in docs.  This PR removes the task from CI team + update the prior art link for the release lead task
/area release

📖  rm duplicated release task

---

util/secret/certificates.go
util/secret/certificates_test.go

In some circumstances `AsFiles()` can panic. The PR adds additional nil check for `c.KeyPair` to avoid it.
```
2024-02-02T09:15:35Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "k0scontrollerconfig", "controllerGroup": "bootstrap.cluster.x-k8s.io", "controllerKind": "K0sControllerConfig", "K0sControllerConfig": {"name":"bar-2-1","namespace":"default"}, "namespace": "default", "name": "bar-2-1", "reconcileID": "8a558d44-7dcf-406e-a7e0-e47c895189f6"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16ca8fd] …
```

:bug: Checking cert's keypair for nil before accessing to avoid panics

---

hack/tools/release/notes/main.go

* While we don't do it / plan for it today. It's entirely possible that we want to cut alpha releases in CAPI at some point
* This tool is also used in (at least) CAPV / controller-runtime. Also relatively realistic that we have alpha releases there
Fixes #

🌱 release notes: also detect alpha releases as pre releases

---

docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md

Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
#10141 enabled the MachinePool feature flag by default, and this change will cause errors if providers do not update their code to reflect the change.

:book: Document MachinePool feature flag promotion

---

api/v1beta1/clusterclass_types.go
api/v1beta1/machinehealthcheck_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
docs/book/src/user/concepts.md
internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
internal/webhooks/cluster_test.go
internal/webhooks/clusterclass.go
internal/webhooks/clusterclass_test.go
internal/webhooks/machinehealthcheck.go
internal/webhooks/machinehealthcheck_test.go
test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
test/framework/machinehealthcheck_helpers.go

The MHC API doesn't allow creating a health check for a missing node only,
it requires you to create fake conditions.
This PR, make the `spec.unhealthyConditions` to allow creating MHC for missing nodes.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/9762

:bug: Change MachineHealthCheck.spec.unhealthyConditions to optional

---

docs/proposals/20220411-cluster-api-state-metrics.md

A set of the files were moved to a different location in the target repo. This updates the links to point to the new location.

📖 Fix broken kube-state-metrics links

---

exp/internal/webhooks/machinepool.go
exp/internal/webhooks/machinepool_test.go
test/e2e/autoscaler.go
test/e2e/autoscaler_test.go
test/e2e/data/infrastructure-docker/main/cluster-template-topology-autoscaler/cluster-autoscaler.yaml
test/framework/autoscaler_helpers.go
test/framework/machinepool_helpers.go

This PR adds MachinePools to the autoscaler e2e tests. This is a follow-up task to enabling MachinePools in ClusterClass.
Fixes part of #10028 

🌱 Add MachinePools to autoscaler e2e test

---

cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
cmd/clusterctl/client/cluster/assets/topology-test/mock-CRDs.yaml
cmd/clusterctl/client/cluster/assets/topology-test/modified-CP-dockermachinepooltemplate.yaml
cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
cmd/clusterctl/client/cluster/topology_test.go
test/extension/handlers/topologymutation/handler_test.go

This PR adds MachinePools to the unit tests in `handler_test.go` and `topology_test.go`. This is a follow-up task to enabling MachinePools in ClusterClass.
Fixes part of #10028

🌱 Add MachinePools to handler and topology test

---

docs/release/release-tasks.md

This PR changes the order of the tasks to generate release notes, as it makes sense to first go through the tasks that require re-generation before manually modifying the generated notes.
/area release

🌱 Update order of release note generation tasks

---

bootstrap/kubeadm/config/crd/kustomization.yaml

Not really important but noticed the order got flipped recently (comments don't match anymore)
Fixes #

🌱 Fixup patch order in CABPK

---

internal/util/ssa/patch.go
internal/util/ssa/patch_test.go

Ensures that the SSA library recovers the gvk of the objects.
Fixes #10405
/area util

🐛 SSA: recover gvk after scheme.Convert

---

api/v1beta1/cluster_types.go
api/v1beta1/zz_generated.openapi.go
config/crd/bases/cluster.x-k8s.io_clusters.yaml
controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml

Improves documentation for the values of KCP.status.Ready & cluster.status.ControlPlaneReady fields
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8923

📖 Improve docs for KCP.status.ready & cluster.status.ControlPlaneReady

---

scripts/ci-e2e-lib.sh
scripts/ci-e2e.sh
test/extension/handlers/topologymutation/handler.go
test/extension/handlers/topologymutation/handler_test.go
test/framework/kubetest/run.go
test/infrastructure/kind/mapper.go

* e2e: makes sure to always build the kind image if it cannot be pulled
* docker: do not overwrite pre-releases in kindmapper
Tested in
- #10384
Fixes #
/area e2e

🌱 e2e: enable ability to test pre-releases of kubernetes

---

internal/controllers/machinedeployment/machinedeployment_controller.go
internal/controllers/machineset/machineset_controller.go

`Owns()` watches for child resources and enqueues requests for owners (owner reference) with controller reference. This PR aims at removing `Owns()` where such enqueuing is already in place via `Watches()`, thereby removing both redundant watch and enqueuing of resources.
Fixes #

🌱 remove redundant watch event handlers via `Owns()`

---

scripts/ci-e2e-lib.sh
scripts/ci-e2e.sh
test/extension/handlers/topologymutation/handler.go
test/extension/handlers/topologymutation/handler_test.go
test/framework/kubetest/run.go
test/infrastructure/kind/mapper.go

This is an manual cherry-pick of:
- #10412.
Supersedes:
- #10413

[release-1.7] 🌱 e2e: enable ability to test pre-releases of kubernetes

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
docs/proposals/20191017-kubeadm-based-control-plane.md
util/collections/machine_filters.go
util/collections/machine_filters_test.go

Fixes #
Fix https://github.com/kubernetes-sigs/cluster-api/issues/10093
**Test**
1. Create 1 CP 1 Worker CAPI Cluster.
```
kubectl get cluster,kcp,machine -n default | grep hw-sks-test-unhealthy-cp
cluster.cluster.x-k8s.io/hw-sks-test-unhealthy-cp   Provisioned   8m2s   
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/hw-sks-test-unhealthy-cp-controlplane   hw-sks-test-unhealthy-cp   true          true                   1          1       1         0             8m2s   v1.25.15
machine.cluster.x-k8s.io/hw-sks-test-unhealthy-cp-controlplane-9nbvm             hw-sks-test-unhealthy-cp …
```

🐛 Delete out of date machines with unhealthy control plane component conditions when rolling out KCP

---

controlplane/kubeadm/internal/control_plane.go
controlplane/kubeadm/internal/control_plane_test.go
controlplane/kubeadm/internal/controllers/remediation.go
controlplane/kubeadm/internal/controllers/remediation_test.go
controlplane/kubeadm/internal/controllers/scale.go
controlplane/kubeadm/internal/controllers/scale_test.go
docs/proposals/20191017-kubeadm-based-control-plane.md
util/collections/machine_filters.go
util/collections/machine_filters_test.go

This was manually picked from https://github.com/kubernetes-sigs/cluster-api/pull/10196 because https://github.com/kubernetes-sigs/cluster-api/pull/10196#issuecomment-2049527429

[release-1.6] 🐛 Delete out of date machines with unhealthy control plane component conditions when rolling out KCP

---

test/e2e/cluster_upgrade.go
test/e2e/k8s_conformance.go
test/e2e/quick_start_test.go
test/framework/kubetest/run.go

Adjusts the kubetest.Run function to include the cluster name at the reportDir and at the report filename of ginkgo.
This should allow running kubetest.Run in parallel.
As of now one kubetest.Run would e.g. have overwritten the kubeconfig of the other as well as the junit reports, which may also have caused a race condition leading to the flaky dualstack tests (the only e2e prowjobs where we currently run kubetest in-parallel.
Fixes #

🐛 e2e: fix kubetest to allow parallel execution on different clusters

---

test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Just to test if we can run these tests without requiring a kind image.
Fixes #

✨ test: Bump Kubernetes version used for testing to v1.30.0-rc.1

---

cmd/clusterctl/client/cluster/cert_manager.go
cmd/clusterctl/client/cluster/cert_manager_test.go

Make shouldUpgrade() accept the list of objects to be installed too.
Compare the installed and to-be-installed objects in case the
installed and to-be-installed versions are the same. If their length is
different, assume that an upgrade is required.
Update unit tests.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/10389
(the linked issue was a but unclear what's going on, but we established that shouldUpgrade can check len of objects too)
/kind feature

🌱 clusterctl/client/cert_manager: improve shouldUpgrade

---

test/e2e/autoscaler.go
test/framework/clusterctl/client.go
test/framework/clusterctl/clusterctl_helpers.go

🌱 Allow setting worker machine count to nil in ApplyClusterTemplateAndWait & ConfigCluster

---

test/e2e/cluster_upgrade.go
test/e2e/k8s_conformance.go
test/e2e/quick_start_test.go
test/framework/kubetest/run.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/10424

[release-1.5] 🐛 test: fix kubetest to allow parallel execution on different clusters

---

test/framework/cluster_proxy.go
test/framework/kubetest/run.go

When running `e2e` with WSL, the API address from the Docker network could not be used to connect to the workload cluster, instead, we need to use `localhost:load-balancer-host-port`. `fixConfig` done the fix, but for now it only applies to `darwin`.
This PR add check to see if the current environment is WSL, based on the env variable `WSL_DISTRO_NAME`. If so, it will use load balancer host port to access the workload cluster.
After the fix, on WSL, the e2e will be supported.
Fixes #10103
/area testing

:sparkles: Support e2e for WSL

---

CHANGELOG/v1.5.8.md

🌱  Release v1.5.8

---

docs/book/src/introduction.md

Document that the default documented version is now release-1.7 and provide backlink to release-1.6
**Which issue(s) this PR fixes:**
Part of: #9800 
/area release

:book: add release 1.6 book link

---

docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
docs/proposals/20210526-cluster-class-and-managed-topologies.md

This PR adds relevant documentation for added MachinePool workers support in ClusterClass.
Fixes part of #10028 

📖 Add MachinePools to ClusterClass Documentation

---

docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md

Updates guidelines for runtime hook implementation
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/7812

📖 Update guidelines for runtime hook implementation

---

CONTRIBUTING.md

Writing down some practices / lesson learned from bug triage /backlog grooming sessions
/hold
For discussion in the office hours + give time to folks to review

📖 Document the triage process

---

test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/drop-machinepools.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/kustomization.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/drop-machinepools.yaml
test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/kustomization.yaml

This PR adds MachinePools back to the dualstack E2E test and fixes the issue found in #9477 
Fixes part of #10028

🌱 Add MP back to dualstack E2E test

---

.golangci.yml
Makefile
Tiltfile
cloudbuild-nightly.yaml
cloudbuild.yaml
go.mod
hack/ensure-go.sh
hack/tools/go.mod
netlify.toml
test/go.mod

Bumps Go to v1.22.2
Part of #10026

🌱 Bump Go to v1.22.2

---

test/infrastructure/docker/internal/docker/loadbalancer.go
test/infrastructure/docker/internal/docker/types/node.go

Adds a check to ensure the written configuration for haproxy matches the one we just wrote.
Part of #10356

🐛 CAPD: verify lb config after writing it

---

docs/book/src/reference/versions.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml
test/infrastructure/docker/examples/machine-pool.yaml
test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
test/infrastructure/docker/examples/simple-cluster.yaml

Requirements:
Steps:
* >  Modify CAPD to use the new Kubernetes release after it is GA:
* >  Update book:
Part of #10026
/area testing
/hold due to waiting for v1.30 GA

🌱 Bump Kubernetes in tests to v1.30.0 and claim support for v1.30

---

Makefile
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
cmd/clusterctl/config/manifest/clusterctl-api.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
config/crd/bases/cluster.x-k8s.io_clusters.yaml
config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
config/crd/bases/cluster.x-k8s.io_machinepools.yaml
config/crd/bases/cluster.x-k8s.io_machines.yaml
config/crd/bases/cluster.x-k8s.io_machinesets.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepooltemplates.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclustertemplates.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachinetemplates.yaml

Bump to latest main for now (4th April)
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10026

🌱 Bump controller-gen to v0.15

---

hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

Only happens on main, no need to cherry-pick: https://github.com/sbueringer/cluster-api/actions/runs/8783862977/job/24100909738
Fixes #

🌱 Bump github.com/docker/docker to v26.0.2

---

.github/ISSUE_TEMPLATE/release_tracking.md

Add the labels which should always get set to exit triage.
Fixes #

🌱 github: add labels to release-tracking issue template

---

docs/book/src/tasks/experimental-features/cluster-resource-set.md

The current documentation links to the original enhancement proposal for examples, but these examples are for an older API version. This commit adds examples directly in the book for the latest API version.
Fixes #

📖 Update docs for ClusterResourceSets

---

.github/ISSUE_TEMPLATE/kubernetes_bump.md

This PR changes the github template we normally use to track the kubernetes bump.
The change targets to decouple the process of
* Supporting managing and running on the new Kubernetes version
and
* waiting for a new kind release / publishing new kindest/node images after a kubernetes release
because the new kind release and/or images get published some time after the final kubernetes minor release.
The changes of:
- #10412
Allow us to test a released kubernetes version although there are no kindest/node images yet, by building the `kindest/node` images like we already do for other e2e tests. …

📖 decouple the support new kubernetes version process from kind releases

---

test/framework/kubetest/run.go

Ensures to always bubble-up junit reports to prow so there are visible when the ginkgo failed.
Follow-up from: https://github.com/kubernetes-sigs/cluster-api/issues/5123#issuecomment-2072101355
Fixes #

🐛 kubetest: also gather junit reports in case of errors observed from ginkgo

---

CHANGELOG/v1.7.1.md

🚀 Release v1.7.1

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum
util/container/image_test.go

Bumps [github.com/distribution/reference](https://github.com/distribution/reference) from 0.5.0 to 0.6.0.
Regarding test change: xref:
- https://github.com/distribution/reference/pull/9
Replaces #10373

🌱 Bump github.com/distribution/reference from 0.5.0 to 0.6.0

---

cmd/clusterctl/client/repository/components.go
test/framework/clusterctl/ca_injection.go
test/framework/clusterctl/clusterctl_helpers.go
test/framework/convenience.go

* clusterctl: ensure cert-manager objects get applied before other provider objects, but after creating the namespace
* test: wait for ca injection in case we use an external clusterctl binary for upgrading
part of #9688
supersedes #10433

🐛 clusterctl: ensure cert-manager objects get applied before other provider objects

---

Makefile

🐛 Fix conversion-gen outside of GOPATH

---

internal/test/envtest/environment.go

🌱 envtest: Setup Machine webhook only once

---

Makefile
docs/book/src/clusterctl/commands/upgrade.md
docs/book/src/clusterctl/developers.md

This PR starts publishing the nightly artifacts to the `k8s-staging-cluster-api` bucket, instead of to the `artifacts.k8s-staging-cluster-api.appspot.com`. 
The latter is the backing bucket of the google container registry and will go away eventually when we migrate from the container registry to the artifact registry. It was never meant to be used to store files that are not part of container images.
Please note that the new location has a retention of 60 days (as of now). But that should be okay for nightly manifests.
Fixes #

🌱 Publish nightly manifests to staging bucket

---

cmd/clusterctl/client/config/cert_manager_client.go
docs/book/src/clusterctl/commands/init.md
docs/book/src/developer/guide.md
scripts/ci-e2e-lib.sh
test/e2e/config/docker.yaml

Updates cert-manager to v1.14.5
Which issue(s) this PR fixes: https://github.com/kubernetes-sigs/cluster-api/issues/10515

🌱Bump cert-manager to 1.14.5

---

Makefile

This target is run on main and all release-branches (https://github.com/kubernetes/test-infra/blob/996976242b664e8f55ce6873692b0ebc2da5de02/config/jobs/image-pushing/k8s-staging-cluster-api.yaml#L13).
While we already have images like: `gcr.io/k8s-staging-cluster-api/cluster-api-controller:release-1.7`, `gcr.io/k8s-staging-cluster-api/cluster-api-controller:main` available. This PR will give us corresponding manifests.
This should make it very easy for folks to consume manifests / images based on the last commit of main and release branches.
Bonus: we'll also get manifests for release tags in the staging bucket. …

🌱 Push manifests for main & release-.*

---

CONTRIBUTING.md
docs/book/src/reference/versions.md

This PR updates the supported versions for the next release cycle (1.8).
Fixes Task: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions
@kubernetes-sigs/cluster-api-release-team

📖 Update CAPI support and guarantees for v1.8

---

docs/book/src/reference/versions.md

📖 Drop v1.4 column, set v1.5 to EOL in versions.md

---

OWNERS_ALIASES

🌱 Swap in new 1.8 RT members in OWNERS

---

cmd/clusterctl/client/cluster/mover.go

The clusterObj will be empty after failure and the log will not print the actual cluster that the cli is trying to get. If there is a bad reference in one of the objects in the graph this leads to a lot of confusion about what's actually failing.

🐛 Fix log in clusterctl move
